### ISSUE TITLE
Better support for multiecho?

### ISSUE THREAD

**Issue by dangom** [rordenlab/dcm2niix#101]
Multiecho EPI data from Siemens scanners are saved as multiple distinct DICOM series, e.g.:

> 006-Task_protocol1_MBME_Echo_0/ 
> 007-Task_protocol1_MBME_Echo_1/ 
> 008-Task_protocol1_MBME_Echo_2/ 

Default dcm2niix (`$ dcm2niix .`) conversion of such series will, as expected, yield three different nifti files:

> echo3.nii.gz
> _e2echo3.nii.gz
> _e3echo3.nii.gz

But their naming isn't optimal.
Even when using `dcm2niibatch` and specifically setting the target filename for each echo series, the `_eN` prefix is added to the output.

What would have to be done to deactivate this feature, or to only activate it in case multiple echoes are found within a single series?  Alternatively, wouldn't it be better to have suffixes instead of prefixes, and also include them for the first echo (for consistency reasons)?

**Comment by neurolabusc** [comment]
In your case it is saving echo number implicitly, as you did not request this. It is only doing this emergently to prevent overwriting files. If you want orderly naming of echoes you should explicitly request it by using a %e in the filename, e.g.  `dcm2niix -f %p_%s_%e ~/dicomdir`.

In theory, one could submit a patch to dcm2niix that would auto-detect if a sequence has multiple echoes and in that case generate the an '_e1' as well as '_e2' and '_e3'. I do not think the total number of echoes is stored in the regular DICOM tags, though perhaps there is a CSA tag. Otherwise, we would need to generate a special flag when images are segmented due to varying echoes. 

Providing details regarding your current `"-f ???"` parameter would help.

**Comment by dangom** [comment]
Thanks for the quick answer. I didn't know about `%e`. Just noticed it also works with `dcm2niibatch`, which is cool =)

In my example above, I was just calling the default conversion with `dcm2niix .`, without any further parameters.
There is a DICOM Tag for NumberOfEchoes, `[0019,107E]`, but vendors don't use it. To make matters worse, some sequences write all echoes to a single series, and some to separate series, so any auto-detect would have to take care of both cases.

**Comment by neurolabusc** [comment]
Thanks for the sample image. I have updated the code and maybe you want to test this. Below I show 3 examples of output:

 a.) if the user explicitly requests echo in output name (%e), the echo is always reported, even for images with only a single echo.
 b.) if user does not want echo number but does want series (%s), and echoes are stored in different series, the echo number is not reported. The series number is sufficient to discriminate echoes.
 c.) if the user does not provide any method to distinguish echo numbers in the file name, and the multiple echoes would cause overwriting of files, all echoes after the first '_eN' appended to their filename to avoid conflict.

The behavior 'b' is new (previously the user would get 'task-rest_acq-phantom_6_e2' in the %p_%s situation), and maybe you want to tell me if you prefer this or not. It might be confusing to users why different images with the same protocol name are saved as different series, while the 'e2' makes the rationale explicit. On the other hand, the addition of '_e2' is not explicitly requested and may not be expected. Maybe @satra and @chrisfilo can comment on what the desired behavior is in this situation.

./dcm2niix -f %p_%s_%e ~/tst
 task-rest_acq-phantom_5_1 (84x84x48x50)
 task-rest_acq-phantom_6_2 (84x84x48x50)
 task-rest_acq-phantom_7_3 (84x84x48x50)

./dcm2niix -f %p_%s ~/tst
 task-rest_acq-phantom_5 (84x84x48x50)
 task-rest_acq-phantom_6 (84x84x48x50)
 task-rest_acq-phantom_7 (84x84x48x50)

./dcm2niix -f %p ~/tst 
 task-rest_acq-phantom (84x84x48x50)
 task-rest_acq-phantom_e2 (84x84x48x50)
 task-rest_acq-phantom_e3 (84x84x48x50)
