### ISSUE TITLE
Citation for dcm2niix

### ISSUE THREAD

**Issue by dangom** [rordenlab/dcm2niix#102]
I know it's uncommon, but if I were to write that I converted my DICOMs to NIfTIs following the Brain Image Data Structure using dcm2niibatch, should I ref. the authors? And if yes, how?

Maybe just link to the repo?

**Comment by neurolabusc** [comment]
While not required, if you do use dcm2niix I would be grateful if you cite my article
  https://www.ncbi.nlm.nih.gov/pubmed/26945974
the yaml-based dcm2niibatch extension was created by @benjaminirving, and he may have his own preferences for citations.

**Comment by yarikoptic** [comment]
It would be nice to have that reference listed in the README.md as a preferred way to reference (unless you decide now to use zenodo to mint citations and dois for each release)
