### ISSUE TITLE
Homebrew - new formula: dcm2niix

### ISSUE THREAD

**Issue by dangom** [rordenlab/dcm2niix#106]
For convenience I've submitted a brewing [formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/dcm2niix.rb) for dcm2niix to homebrew-core, and it has been merged. From now on, MacOS users that like `brew` can install the latest release of dcm2niix with:

`brew install dcm2niix`.

A flag `--with-batch` also installs dcm2niibatch. As usual, a flag `--HEAD` with clone and build the latest commit of this repository.

This isn't properly an issue, but I didn't know where to write it.

**Comment by neurolabusc** [comment]
Thanks, I think many will find this useful. I have copied this post to the [NITRC questions forum](https://www.nitrc.org/forum/forum.php?thread_id=8169&forum_id=4703) so users can find it (my sense is that github is for developers and NITRC is for users).
