### ISSUE TITLE
Content of generated json file

### ISSUE THREAD

**Issue by anbai106** [rordenlab/dcm2niix#112]
Hi, I use dcm2niix to generate the json file for my Siemens sequences, and it works, but I am confused with the content in the json file, **"PhaseEncodingDirection": "j-"**, I konw this corresponds to 'AP' or 'PA', but the minus means that this corresponds to 'AP'??? Because I used another converter(dcmstack) to generate the same json which has different result; **"PhaseEncodingDirection": "COL"**, **"PhaseEncodingDirectionPositive": "1"**

Can you explain it to me a little??

Thanks in advance

**Comment by neurolabusc** [comment]
dcmstack is reporting the DICOM information, whereas dcm2niix is reporting the NIfTI information. Be aware that the left-right and aneterior-posterior dimensions have reversed polarity in DICOM vs NIfTI. Also, in [NIfTI](https://nifti.nimh.nih.gov/pub/dist/src/niftilib/nifti1.h) convention the raw image dimensions saved to disk are i,j,k for rows, columns and slices. In contrast x,y,z refers to the left-right, posterior-anterior and foot-head dimensions, which is what you get after multiplying the i,j,k coordinate with the s-form or q-form.

**Comment by anbai106** [comment]
@neurolabusc so for my data with the json of dcm2niix, the phase encoding direction is AP??? no?

**Comment by neurolabusc** [comment]
You have not provided enough information for me to answer this. Assuming your acquisition is axial than it is AP (it is FH if your acquisition is sagittal or coronal). The dcm2niix output is correct for BIDS JSON, for details see
  http://bids.neuroimaging.io/bids_spec1.0.0.pdf

**Comment by ilkayisik** [comment]
Hello, I have a question related to this closed issue. 
I am doing dicom to nifti conversion using heudiconv [which uses dcm2niix]. 
Siemens protocol file for my bold sequence says: 
```
Position L0.0 P0.0 F0.0 [mm]
Orientation T > C-30.0
Rotation 0 [deg]
R >> L 192 [mm]
A >> P 192 [mm]
F >> H 95 [mm]
PhaseBlipsPolarity = 1
```
[I also have a reference image having the same params except ```PhaseBlipsPolarity = -1```].

Because my phase encoding dir is A>>P and the PhaseBlipsPolarity is 1, I thought that this should correspond to j. However, the json output I get after the conversion says that the phase encoding dir is 'j-' for the BOLD image. 
Is it correct? Maybe you answered it above but sorry that I am still not quite sure.

**Comment by neurolabusc** [comment]
@ilkayisik [be aware that by default NIfTI and DICOM use opposite spatial coordinates](https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#Spatial_Coordinates) for the ROW (j) direction. The BIDS tag PhaseEncodingDirection is in image space: it refers to rows/columns/slices not A<>P/R<>L/H<>F (hence i,j,k not x,y,z).

The first line of a DICOM image as stored on disk tends to refer to the top of the screen, with subsequent lines below (like we read English). In contrast, the default behavior for Analyze/NIfTI matches how you would draw a graph using cartesian coordinates, with increasing Y corresponding to a higher position. 

In theory, a DICOM to NIfTI converter can flip the rows or not, and store the change in the SForm/QForm. However, not all software reorients images based on these values: FSLview expected NIfTI style while MIPAV expects DICOM style. In contrast, viewers like MRIcroGL and FSLeyes show images correctly. You can go to MRIcro's "Preferences" to control how you see an image as saved to disk, or re-oriented.

For completeness, by default dcm2niix will flip rows when converting DICOM to NIfTI, matching the default assumptions of NIfTI. However, you can turn off this behavior with the undocumented `-y n` which instructs the converter to not flip the y dimension. Doing this reverses the `PhaseEncodingDirection` reported in the BIDS header - images that appeared upside down with MIPAV will look correct, images that looked correct with FSLview will look upside down, it will have no influence on MRIcroGL/SPM/FSLeyes or any tool that inspects the SForm/QForm: the rotation is reported, the difference is lossless. I do not recommend this feature, but it does allow you to directly compare dcm2niix's solution with other tools that do not flip rows (e.g. I presume dcmstack).

**Comment by mharms** [comment]
I'm curious, what sequence are you using that has a parameter called `PhaseBlipsPolarity`?  That's a parameter name I've never seen before.

**Comment by ilkayisik** [comment]
@neurolabusc Thank you so much for the answer. I was not aware that the default behavior flips rows, now it makes sense. 
@mharms I am using a custom sequence developed by our physicist at the BIC.
