### ISSUE TITLE
GEIIS warning.

### ISSUE THREAD

**Issue by qinqian** [rordenlab/dcm2niix#113]
Hi, 

The software did great jobs in converting DICOM to nii files. However, when used it with GEIIS data, I've got the following warnings,  will this affect the conversion results? 

"Warning: GEIIS violates the DICOM standard. Inspect results and admonish your vendor."

Thanks!

**Comment by neurolabusc** [comment]
Hello-
 Your images were touched by GE PACS software which added a [thumbnail image](http://forum.dcmtk.org/viewtopic.php?p=7162&sid=3b516cc751aae51fbb5e73184abe37c2). Unfortunately, the   implementation was breaks DICOM compatibility. Hopefully my software detects this error and converts the images correctly. I strongly urge you to have your GE PACS software upgraded to ensure compatibility with DICOM devices. To be clear, this if an issue with your GE PACS and not my software. My software is simply detecting the error and attempting to implement a kludge to extract the images correctly.
