### ISSUE TITLE
phasemap dicom conversion issue

### ISSUE THREAD

**Issue by nimzodisaster** [rordenlab/dcm2niix#114]
I needed to downgrade to an older release after upgrading to the latest version from this month because dcm2niix would no longer correctly convert my phasemap dicom images.

**Comment by neurolabusc** [comment]
Thanks for sample images. Current version works as expected. The older versions may have used slightly different output folders when the output directory was [not specified](https://github.com/rordenlab/dcm2niix/issues/81). The new version should consistently save to the parent input folder in these cases.
