### ISSUE TITLE
stdout for DTIs

### ISSUE THREAD

**Issue by leej3** [rordenlab/dcm2niix#115]
The text printed to stdout for DTI scans can be different depending on the DICOM. Would be helpful for downstream processing if it was always the same. See https://github.com/nipy/nipype/issues/2109

**Comment by neurolabusc** [comment]
I changed the stdout when creating vectors for GE from `Reorienting %s : %d GE DTI vectors` to `Saving %d DTI gradients`, matching what is generated for Siemens and Philips. If you wish to validate, there are [DTI datasets for each of the major vendors on NITRC](http://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#Diffusion_Tensor_Imaging).

**Comment by leej3** [comment]
great. Thanks!
