### ISSUE TITLE
failure to reconstruct GE fieldmaps

### ISSUE THREAD

**Issue by josephdviviano** [rordenlab/dcm2niix#118]
Hi there,

We're having trouble reconstructing fieldmaps from our GE MR750x using dcm2niix (built 2017-02-21). These same files reconstruct fine using dcm2nii (built 2015-06-22).

This is what we get:

![screenshot from 2017-07-18 18-01-58](https://user-images.githubusercontent.com/4142570/28384603-4db95132-6c93-11e7-84d8-486a2d14789b.png)

Here's the data: https://www.dropbox.com/s/9v43jcmyl43vj90/recon_compare_fieldmap.zip?dl=0

Thanks for your help!

**Comment by josephdviviano** [comment]
FYI I'm being told that the dicom tag (0020,0013) is an instance number that can be used to sort the volumes into the 4 correct 3D sets, which appear to be getting shuffled here.

**Comment by neurolabusc** [comment]
Both the latest release of dcm2niix (v1.0.20170624)
 https://github.com/rordenlab/dcm2niix/releases 
as well as the latest release with MRIcroGL on NITRC(v1.0.20170528)
 https://www.nitrc.org/projects/mricrogl/
appear to convert the magnitude image (first volume) fine. All tools (including the excellent Matlab based dicm2nii and my deprecated dcm2nii) do generate odd-looking phase maps (subsequent volumes). I think you just need to unwrap those:  https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FUGUE/Guide

**Comment by josephdviviano** [comment]
Hi @neurolabusc -- you're correct, the newer release does resolve the issue. Hopefully this is useful to others having the same problem.
