### ISSUE TITLE
Errors don't print to stderr

### ISSUE THREAD

**Issue by ForrestCKoch** [rordenlab/dcm2niix#122]
It would be helpful to have the error messages print to stderr so they can be captured separately to other output.

all of the `printf("Error: ....` statements just need to be changed to `fprintf(stderr, "Error: ...`

I'm happy to fix it myself, but I'm not sure of the protocol for contributing here...

**Comment by neurolabusc** [comment]
@satra can you ensure this patch does not break [heudiconv](https://github.com/nipy/heudiconv/)? The latest release will pipe errors to stderr. However, if you compile with the myErrorStdOut directive the old behavior of piping errors to stdout will be used, which helps GUI applications like [MRIcro](https://github.com/neurolabusc/MRIcro) report errors.

**Comment by satra** [comment]
@neurolabusc - will check it out. we are waiting on a big merge and then updating dcm2niix.
