### ISSUE TITLE
core dump after build

### ISSUE THREAD

**Issue by xfgavin** [rordenlab/dcm2niix#132]
Hi Chris,

My build in Ubuntu was successful, but got core dump when executing it. This issue seems to exist for nearly one month. I also saw lots of recent build errors on travis. Can this be fixed soon?

**Comment by neurolabusc** [comment]
Patch should avoid core dump, but Travis will continue to report errors until @mharms closes [127](https://github.com/rordenlab/dcm2niix/issues/127) - at that stage we will update dcm_qa and test releases.

**Comment by xfgavin** [comment]
Thanks, it's fixed now.
