### ISSUE TITLE
acquisition time should be removed from anonymized metadata

### ISSUE THREAD

**Issue by poldrack** [rordenlab/dcm2niix#133]
Acquisition time is a unique identifier according to HIPAA so it should be removed when the -ba flag is set, as should any other possible markers of acquisition time/date

**Comment by poldrack** [comment]
my bad, I realize it doesn't include the date.

**Comment by mharms** [comment]
Are you sure that that acquisition time, in the absence of acquisition date, is considered identifying?  (And if so, can you provide the link?)  Acquisition time is necessary to know if you want to study diurnal effects, and we (for example) make acquisition time available in the HCP data.

**Comment by poldrack** [comment]
https://medschool.duke.edu/research/clinical-and-translational-research/duke-office-clinical-research/irb-and-institutional-14

"All elements (except years) of dates related to an individual (including birthdate, admission date, discharge date, date of death, and exact age if over 89)"

**Comment by poldrack** [comment]
and I agree that acquisition time w/o date would be useful

**Comment by mharms** [comment]
Yes, that I what I recall seeing previously from our project manager.  Notably, those are all dates, and it says nothing that the *time* of a scan is considered PHI.  Our project manager, who is very sensitive to these issues, does not consider the time of a scan to be PHI.

I would like to encourage that we revert to “time” still being included in the presence of the ‘-ba’ flag.

--
Michael Harms, Ph.D.
-----------------------------------------------------------
Conte Center for the Neuroscience of Mental Disorders
Washington University School of Medicine
Department of Psychiatry, Box 8134
660 South Euclid Ave.                        Tel: 314-747-6173
St. Louis, MO  63110                                          Email: mharms@wustl.edu

**Comment by mharms** [comment]
Sorry, I just realized that I read this thread wrong.  Looking at the code, I see that the issue was closed without any actual change to the code, so the "default" (-ba flag) continues to be that `AcquisitionTime` is reported, but `AcquisitionDateTime` is not.
