### ISSUE TITLE
Truncation of ImageComments

### ISSUE THREAD

**Issue by mharms** [rordenlab/dcm2niix#135]
It looks like there might be some truncation occurring in the new ImageComments field in the json that I didn't catch previously.  I have a DICOM for which Matlab's `dicominfo` returns
```
>> info.ImageComments
ans =
R: -0.0003 -0.2166 0.7416 -0.6350 T:   0.14 0.08 -0.01 F:  -1.29 (1.00)
```
but the json contains

`"ImageComments": "R:_-0.0003_-0.2166_0.7416_-0.6350_T:_0.14_0.08_-0.01_F:_-1.29_(",`

**Comment by neurolabusc** [comment]
We define strings as a maximum of 64-bytes
  #define kDICOMStr 64
seeing that we often load tens of thousands of DICOM image headers to sort them, it is best to have some relatively small and fixed size.

**Comment by mharms** [comment]
Do you know what is the maximum length of the ImageComments field itself (0020 4000) ?


--
Michael Harms, Ph.D.
-----------------------------------------------------------
Conte Center for the Neuroscience of Mental Disorders
Washington University School of Medicine
Department of Psychiatry, Box 8134
660 South Euclid Ave.                        Tel: 314-747-6173
St. Louis, MO  63110                                          Email: mharms@wustl.edu

**Comment by neurolabusc** [comment]
0020,0040 has a value representation (VR) of long text (LT) and can be up to [10240 characters long](http://dicom.nema.org/dicom/2013/output/chtml/part05/sect_6.2.html).

**Comment by neurolabusc** [comment]
Note that with dcm2niix, the user can also insert the ImageComments into the filename (e.g. `-f %p_%c ` will generate a filename based on the ProtocolName and ImageComments. In most implementations of C, max_path is set to 4096 characters, which would include the filename and its full path.

**Comment by mharms** [comment]
The Comment portion of ‘-f %p_%c’ is limited to the same 64 bytes/characters (which is fine, because I’m not planning on including the Comments in the file name anyway).

I guess the solution is for us to compile with #define kDICOMStr 64 set a little bit higher.  80 characters would probably be enough, but would the performance penalty be bad if we were generous and increased it up to 128 characters?



--
Michael Harms, Ph.D.
-----------------------------------------------------------
Conte Center for the Neuroscience of Mental Disorders
Washington University School of Medicine
Department of Psychiatry, Box 8134
660 South Euclid Ave.                        Tel: 314-747-6173
St. Louis, MO  63110                                          Email: mharms@wustl.edu

**Comment by mharms** [comment]
What do you think of increasing the allotted characters for only the imageComments variable?  In that case, I’d assume that the performance penalty would be non-existent.

e.g.,
```
#define kDICOMStrLarge 256
…
char imageComments[kDICOMStrLarge];
```

**Comment by mharms** [comment]
That commit works -- I get the full text in the json ImageComments field, and if I run with `-f %c` the full text of 0020,0040 is now included as part of the NIFTI/json file name as well.
