### ISSUE TITLE
centos -lstdc++ linking error: need libstdc++-static

### ISSUE THREAD

**Issue by WillForan** [rordenlab/dcm2niix#137]
`cd build/console-build && make`
> /usr/bin/ld: cannot find -lstdc++
> collect2: error: ld returned 1 exit status

resolved with `yum install libstdc++-static`

on

> CentOS Linux release 7.3.1611 (Core)
> centos-release-0:7-4.1708.el7.centos.x86_64

I'm not sure if this qualifies as a proper issue. It probably says more about the distribution install than the "no dependencies" claim of the read me. But it took me a while to figure out. So here's trail for anyone else having the issue.

**Comment by WillForan** [comment]
resolved with `yum install libstdc++-static` which provides
> /usr/lib/gcc/x86_64-redhat-linux/4.8.2/libstdc++.a

**Comment by neurolabusc** [comment]
I have updated the documents to reflect this. @ningfei do you think we could [upgrade your SuperBuild to ensure libstdc++ is installed](https://stackoverflow.com/questions/38694058/cmake-linking-statically-against-libgcc-and-libstdc-into-a-shared-library)?

**Comment by ningfei** [comment]
@neurolabusc have a quick look of this, no quick solution so far... We probably need to find a way to check the existence of `libstdc++.a` to ensure this.
Currently we use a file [ucm.cmake](https://github.com/rordenlab/dcm2niix/blob/master/console/ucm.cmake) (which contains a collection of useful cmake macros) to handle the static/dynamic link option. And static runtime (link option `-static-libstdc++` and `-static-libgcc`) is chosen by default for ease of release/distribution. One can set `USE_STATIC_RUNTIME` to `OFF` in cmake if a shared build is desired or static libstdc++ is not available.

**Comment by fedorov** [comment]
@WillForan thank you! I had the same problem with a docker build, and this issue was the first hit from google search! 👍

**Comment by BrennanHickson** [comment]
I'm running into this error while attempting to install on a supercomputer account for which I have no elevated privileges. I am therefore unable to resolve the issue with `yum install libstdc++-static`. Are there any alternatives?

**Comment by ningfei** [comment]
@BrennanHickson You  can try to set the option `USE_STATIC_RUNTIME` to `OFF` in CMake.

**Comment by BrennanHickson** [comment]
@ningfei That was the solution I opted for initially. 

@neurolabusc offered another successful command to be entered directly in the console directory:

`g++ -O3 -I.  main_console.cpp nii_foreign.cpp nii_dicom.cpp jpg_0XC3.cpp ujpeg.cpp nifti1_io_core.cpp nii_ortho.cpp nii_dicom_batch.cpp  -o dcm2niix -DmyDisableOpenJPEG `
