### ISSUE TITLE
slices not stacked: orientation varies , File not large enough to store image data while converting a DICOM to nifti 

### ISSUE THREAD

**Issue by athanell** [rordenlab/dcm2niix#140]
### Summary
While converting a DICOM folder to nifti
 `dcm2niix -z y /media/sf_SharedVMUbuntuFolder/data/ANON11641`
 I got the following error

```
Chris Rorden's dcm2niiX version v1.0.20170923 GCC5.4.0 (64-bit Linux)
Found 40 DICOM image(s)
slices not stacked: orientation varies (localizer?) [1 0 0 0 0.983825 -0.179131] != [0 0.951056 -0.309017 0 -0.309017 -0.951056]
File not large enough to store image data: /media/sf_SharedVMUbuntuFolder/data/ANON11641/1I00037.dcm
slices not stacked: orientation varies (localizer?) [0 0.951056 -0.309017 0 -0.309017 -0.951056] != [1 0 0 0 0.983825 -0.179131]
File not large enough to store image data: /media/sf_SharedVMUbuntuFolder/data/ANON11641/1I00004.dcm
 
```

Any ideas on why the conversion failed and how to overcome this?

Thank you

**Comment by neurolabusc** [comment]
The warning
  slices not stacked: orientation varies (localizer?) 
is generated when images in a single series are not aligned to the same plane. The NIfTI format requires all images in a volume are co-planar, so in this case the images must be saved as separate files. You typically get this warning if you convert localizer images, where orthogonal, axial and sagittal images are acquired in a single series. These images do not have the coverage to be useful for typical analyses so they are typically discarded. You use the 'i'gnore flag to skip these images (`dcm2niix -i y ...`).

I am not sure while the file is not large enough to store the image data. This typically suggests an acquisition that was interrupted or a conversion error. Does this image open correctly with a conventional DICOM viewer like Horos? If you can send me a sample (e.g. email me a dropbox link) I can provide more information. However, I think these are images you do not want, so the ignore option should hopefully skip these problematic files and convert the significant ones.

**Comment by athanell** [comment]
This particular DICOM data set is a brain CT scan (consists of 40 .dcm items/slices and its total size is 6MB) which I can load and view it in itksnap or Slicer 
It has an inplane axial resolution of 0.44 x 0.44 mm and a 4 mm resolution in the 3rd dimension ( 512x512x39 ).

If it is of any help Slicer gives me some warning before hand "There is no pixel data attribute for the DICOM objects but they might be readable as secondary captures. Images are not equally spaced(a difference of 52.15 in spacings was detected)Slicer will load this series as if it had a spacing of 4" 

Unfortunately I cannot share this volume due to patient confidentiality reasons but I will ask if I am allowed to share a sample of it.
Thanks again

**Comment by neurolabusc** [comment]
I understand. Without further information I can not provide any more feedback. Given the thousands of scans from the BioBank and elsewhere that have been put through dcm2niix this sounds perculiar to your sequence. My one thought on the orientation is that some GE images have exhibited rounding errors between slices of a single series, and therefore the slices are not technically co-planar. This explains why several lines of my code attempt to provide some tolerance to detect differences. The lack of a pixel data attribute suggests this is not a valid DICOM file, as that would be a violation of the DICOM standard. If you do have a chance to acquire a phantom with this sequence or find a way to anonymize the sample I would be happy to investigate. You may also want to see if this is raw DICOM data or was manipulated by a tool that corrupted it (e.g. GE's GEIIS was famous for borking DICOM images). If this is the case, you may want to avoid the offending DICOM handling to ensure easy viewing/conversion in the future.

**Comment by athanell** [comment]
Hello again Chris, 

You were correct about your assumption for data corruption during the anonymization process. I was informed that during the anonymization process something went wrong and some slices were totally missing (even though all the slices were numbered correctly).

Hopefully this information might be useful to other users if they experience a similar error during the conversion.

Thank you for the assistance

**Comment by neurolabusc** [comment]
@athanell can you provide information on which tool was used for anonymization - this would help replicate the issue.

**Comment by athanell** [comment]
Hello @neurolabusc ,
 
I was told by the person who did the anonymization that the
error (missed slices) happened when transferring the DICOM from the anonymization server (that uses the dcmodify) to the DVTK server.

AnonymServ -> DVTK Serv  (corrupted image) 

 When the trafficking though went through the PACS server the data remained intact.

AnonymServ -> PACS -> DVTK Serv (intact image)

He was not aware yet though of which particular step was responsible for the data corruption.
