### ISSUE TITLE
BIDS json file doesn't contain MultiBandAccelerationFactor for DWI sequences

### ISSUE THREAD

**Issue by mvdoc** [rordenlab/dcm2niix#141]
Hi,
using heudiconv I realized that for DWI sequences `dcm2niix` doesn't store the field `MultiBandAccelerationFactor`. See nipy/heudiconv#110 for more info.

The information seem to be present in the dicom headers though (assuming I'm looking at the right field):

GRAPPA 2 (in this case the json file contains ` "ParallelReductionFactorInPlane": 2` correctly)
```
[bids@rolando test_dwi_dcm2niix] > grep 0051,1011 dump_dwi_grappa.txt
(0051,1011) LO [p2]                                     #   2, 1 Unknown Tag & Data
```

SMS 4
```
[bids@rolando test_dwi_dcm2niix] > grep 0051,1011 dump_dwi_sms.txt
(0051,1011) LO [s4]                                     #   2, 1 Unknown Tag & Data
```

This is the version we're using

```
bids@rolando:~/test_dwi_dcm2niix$ dcm2niix
Compression will be faster with 'pigz' installed
Chris Rorden's dcm2niiX version v1.0.20170923 (OpenJPEG build) GCC6.3.0 (64-bit Linux)
```

**Comment by neurolabusc** [comment]
I see you are using v1.0.20170923 - can you test to see if the latest [release](https://github.com/rordenlab/dcm2niix/releases) also has this problem. dcm2niix should read multiband directly from the CSA header rather than relying on the DICOM header. If there is still a problem, I would guess it is because you are using the Siemens SMS product rather than the CMRR sequences. I do not have the Siemens SMS license, so if this is the case I would be grateful if you could send me a sample dataset to examine.

**Comment by mvdoc** [comment]
I can confirm that with the latest release the MultiBand field is not reported. I'm emailing you a sample dataset of the DWI without acceleration/with grappa/with sms.

Thanks!

**Comment by mvdoc** [comment]
Thank you!

**Comment by neurolabusc** [comment]
Hello, can I suggest you acquire your diffusion data with the `mosaic` option selected. I just checked our system, and if you do not have this checked each 2D slice is saved as a separate DICOM image and the `MosaicRefAcqTimes` CSA tag is omitted.  Without that you will not get the `SliceTiming` field in your BIDS file. That will help you use eddy_cuda's `--slspec file` option. As an aside I keep the trace, ADC, FA and tensor buttons unchecked, as you can create better derived images after processing with dwidenoise, topup and eddy.

![mosaics](https://user-images.githubusercontent.com/8930807/32624971-ed847b38-c558-11e7-9af2-24a63b81eb33.png)

**Comment by mvdoc** [comment]
@neurolabusc thank you so much for this! I will try on our system and run some tests.

**Comment by mharms** [comment]
FYI: One peculiarity related to dMRI and the “Mosaic” output format is that at least under Siemens VE11 and VD13 (but I don’t think earlier versions), you have to set “Diff. weightings” >= 2 for the Mosaic option to be selectable.

Assuming you are using a custom gradient table, we set “b-value 1” = 0, and “b-value 2” = <your desired maximum b-value>.  You’ll then get an extra “b=0” volume at the front end of your acquisition, but you can use the Mosaic output format.

Cheers,
-MH

--
Michael Harms, Ph.D.
-----------------------------------------------------------
Conte Center for the Neuroscience of Mental Disorders
Washington University School of Medicine
Department of Psychiatry, Box 8134
660 South Euclid Ave.                        Tel: 314-747-6173
St. Louis, MO  63110                                          Email: mharms@wustl.edu

**Comment by mvdoc** [comment]
Today I tested with the mosaic option on, and everything works perfectly. Thank you!!
