### ISSUE TITLE
Inconsistent naming and image distortion while transforming dicom to nifti

### ISSUE THREAD

**Issue by athanell** [rordenlab/dcm2niix#143]
Hello @neurolabusc , 

I am transforming DICOM images to nifti using the dcm2niix utility.

I have a total of 9 patients, 20 studies and 130 series all in one folder named DICOM.
While I used the command below to tranform them to nifti:

`dcm2niix -o ~/dcm2nifti/ DICOM/5971A000` 

where 5971A000 is just a random DICOM file in the folder,

I have noticed the following:
The nfiti files are named using the convention DICOM_SeriesDescription_SeriesDateSeriesTime_SeriesNumber.nii.gz

So the highlighted DICOM file:
![untitled2](https://user-images.githubusercontent.com/20206739/32843986-dfde8dcc-ca29-11e7-8d61-61d34a8d9a3e.png)

will create a nifti image named
DICOM_ANGIO_20160909074126_2.nii.gz

Notice that only the 3 first digits of the SeriesTime  (074) are correct in the nifti file. The SeriesTime 074126 corresponds to the SeriesDescription SCOUT and Dose Report but these two have a different SeriesNumber (1 and 999 respectively). 
Is this a normal behavior during the conversion?

I verified that both the nifti DICOM_ANGIO_20160909074126_2.nii.gz and the highlighted DICOM image are the same image by inspecting them with a viewer. 

For another DICOM file that you see hightlighted below
![untitled1](https://user-images.githubusercontent.com/20206739/32843592-d173147a-ca28-11e7-82a1-0c3848547fb2.png)

after the conversion multiple nifti files were created corresponding to it as can be seen below:

![untitled3](https://user-images.githubusercontent.com/20206739/32845183-cb66d5fe-ca2c-11e7-9c24-483b2decedd4.png)

Notice also the same pattern where the 3 first figits of the SeriesTime are correct in the nifti files. The SeriesTime 110200 corresponds to the SeriesDescription SCOUT and Dose Report.

In this second data set I would like to ask why there are multiple nifti images created? Like the 3a, 3b, 3c? I understand that the *_Tilt_1.nii.gz images is an effort of the software to correct for gantry tilt. But what about the rest? 
The problem here is that all of them are distorted versions of the original DICOM as you can see in the snapshots below:

The DICOM file looks like this:
![dicom-orig](https://user-images.githubusercontent.com/20206739/32847583-0eeaf52a-ca33-11e7-8567-93f8feb40084.png)

The nifti files that correspond to the DICOM look like this:
![nifti3](https://user-images.githubusercontent.com/20206739/32847728-799a6ca2-ca33-11e7-9277-2cd1dda4be4f.png)

![nifti3a](https://user-images.githubusercontent.com/20206739/32847734-8084c71a-ca33-11e7-898b-3f4858ff93e7.png)

![nifti3b](https://user-images.githubusercontent.com/20206739/32847742-85e7623a-ca33-11e7-849c-544f85ee7496.png)

![nifti3c](https://user-images.githubusercontent.com/20206739/32847760-905393d8-ca33-11e7-808a-239eff01dd1b.png)

Thank you

**Comment by neurolabusc** [comment]
1.) If you want to explicitly set the file naming convention, use the "-f" option. The naming is consistent - it is defined as the STUDY TIME (0008,0030)  not the SERIES TIME (0008,0031). 
  https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#General_Usage
Using the study time is nice, as it groups all files together from the same study, which is important for MRI scans, where we usually use some modalities (e.g. T1) to guide the normalization of others (e.g. fMRI). So the naming scheme "-f %t_%s_%p" will create filenames with study date, series number and protocol name. If you prefer a different convention you can always make your own fork that uses series time.

2.) Your CT issue is described here
 https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#Special_Considerations_for_Computed_Tomography_.28CT.2C_CAT.29
  In particular, your "DICOM file image" shows artifacts from table tilt (and perhaps unequal slice distances as well). Since these attributes are unable to be encoded in the NIfTI standard, my software attempts to correct for them. It looks like it has succeeded for the main brain, but was unable to include the inferior and superior slices. Without the command line output, I am not sure what went on, but my guess is that these slices are described as not being co-planar. I would guess this reflects a rounding error in the system that generated the DICOM images. If you share a dataset with me I can provide more details, or if you can issue a pull-request I would be happy to review code you have to fix this problem.

**Comment by athanell** [comment]
Hello @neurolabusc, 
1) Thank you for pointing out that the STUDY TIME is the field used during the name convention and not the SERIES TIME as I wrongly thought.
2) The output of dcm2niix for the particular subject and series is the following:


```
slices stacked despite varying acquisition numbers (if this is not desired please recompile)
slices not stacked: Study Data/Time (0008,0020 / 0008,0030) varies 20170619110200.000000000000 ~= 20121231094145.000000000000
slices not stacked: X-Ray Exposure varies (exposure 20, 12; number 1, 1). Use 'merge 2D slices' option to force stacking
 Warning: note these images have gantry tilt of 14.5 degrees (manufacturer ID = 2)
Convert 64 DICOM as /home/athanell/dcm2nifti/DICOM_Luinen_kallo_20170619110200_3 (512x512x64x1)
compress: "/usr/bin/pigz" -n -f -6 "/home/athanell/dcm2nifti/DICOM_Luinen_kallo_20170619110200_3.nii"
Gantry Tilt Correction is new: please validate conversions
compress: "/usr/bin/pigz" -n -f -6 "/home/athanell/dcm2nifti/DICOM_Luinen_kallo_20170619110200_3_Tilt_1.nii"

slices stacked despite varying acquisition numbers (if this is not desired please recompile)
slices not stacked: Study Data/Time (0008,0020 / 0008,0030) varies 20170619110200.000000000000 ~= 20160909073726.000000000000
slices not stacked: X-Ray Exposure varies (exposure 12, 6; number 1, 1). Use 'merge 2D slices' option to force stacking
 Warning: note these images have gantry tilt of 14.5 degrees (manufacturer ID = 2)
Convert 16 DICOM as /home/athanell/dcm2nifti/DICOM_Luinen_kallo_20170619110200_3a (512x512x16x1)
compress: "/usr/bin/pigz" -n -f -6 "/home/athanell/dcm2nifti/DICOM_Luinen_kallo_20170619110200_3a.nii"
Gantry Tilt Correction is new: please validate conversions
compress: "/usr/bin/pigz" -n -f -6 "/home/athanell/dcm2nifti/DICOM_Luinen_kallo_20170619110200_3a_Tilt_1.nii"

slices stacked despite varying acquisition numbers (if this is not desired please recompile)
slices not stacked: X-Ray Exposure varies (exposure 6, 12; number 1, 1). Use 'merge 2D slices' option to force stacking
slices not stacked: Study Data/Time (0008,0020 / 0008,0030) varies 20170619110200.000000000000 ~= 20160909073726.000000000000
 Warning: note these images have gantry tilt of 14.5 degrees (manufacturer ID = 2)
Convert 16 DICOM as /home/athanell/dcm2nifti/DICOM_Luinen_kallo_20170619110200_3b (512x512x16x1)
compress: "/usr/bin/pigz" -n -f -6 "/home/athanell/dcm2nifti/DICOM_Luinen_kallo_20170619110200_3b.nii"
Gantry Tilt Correction is new: please validate conversions
compress: "/usr/bin/pigz" -n -f -6 "/home/athanell/dcm2nifti/DICOM_Luinen_kallo_20170619110200_3b_Tilt_1.nii"


slices stacked despite varying acquisition numbers (if this is not desired please recompile)
slices not stacked: Study Data/Time (0008,0020 / 0008,0030) varies 20170619110200.000000000000 ~= 20121231094145.000000000000
slices not stacked: X-Ray Exposure varies (exposure 17, 20; number 1, 1). Use 'merge 2D slices' option to force stacking
 Warning: note these images have gantry tilt of 14.5 degrees (manufacturer ID = 2)
Dims 512 512 32 1 1
Warning: Interslice distance varies in this volume (incompatible with NIfTI format).
 Distance from first slice:
dx=[0 1.24988 2.49976 3.74964 4.99952 6.24939 7.50024 8.75012 10 11.2499 12.4998 13.7496 14.9995 16.2494 17.5002 18.7501 100 101.25 102.5 103.75 104.999 106.249 107.5 108.75 110 111.25 112.5 113.75 114.999 116.249 117.5 118.75]
Convert 32 DICOM as /home/athanell/dcm2nifti/DICOM_Luinen_kallo_20170619110200_3c (512x512x32x1)
compress: "/usr/bin/pigz" -n -f -6 "/home/athanell/dcm2nifti/DICOM_Luinen_kallo_20170619110200_3c.nii"
Gantry Tilt Correction is new: please validate conversions
compress: "/usr/bin/pigz" -n -f -6 "/home/athanell/dcm2nifti/DICOM_Luinen_kallo_20170619110200_3c_Tilt_Eq_1.nii"
```
Unfortunately I cannot share a dataset due to patient confidentiality but I can provide you with any metadata that might be useful ( and do not reveal any information that can be linked to the patient), as well as snapshots of the particular images.

**Comment by neurolabusc** [comment]
I think the relevant line is
```
slices not stacked: X-Ray Exposure varies (exposure 20, 12; number 1, 1). Use 'merge 2D slices' option to force stacking
```
I would suggest you run the conversion again with "-m y" as a parameter (it seems you are converting all your participants in a single pass, if you have any problems with the merge option try converting each participant's folder one at a time).

The issue here is that some users want to separate images based on exposure, while [other teams do not](https://github.com/rordenlab/dcm2niix/issues/91).

I suspect this will resolve your issue. If so I think we can close this issue.

**Comment by athanell** [comment]
Hello @neurolabusc , 

I used dcm2niix: 

1) with all 9 patients and their studies in one folder and  with the "-m y" setting:
  In that particular way all files got distorted.
 They typically look like the snapshot below
![luinen-kallo-m-setting-allsubjects-anonym](https://user-images.githubusercontent.com/20206739/32942991-595ec760-cb93-11e7-86b4-420e28f4a1a8.png)

and the logfile of the conversion is attached here:
[dicom2nifti_conversion_log_file_m_setting.txt](https://github.com/rordenlab/dcm2niix/files/1482031/dicom2nifti_conversion_log_file_m_setting.txt)


2) With every study of every patient separated in a different folder and tested both with the "-m y" and "-m n" settings:
Some files were converted to nifti without distortions using the "-m y" and in that sense were better compared to the same conversion without using the "-m y". 
But some other files were distorted with the "-m y" while the "-m n" worked better for them.

As an example for one study of one patient that contained 4 series:
3mm_sag_aivot_20170619110200_602
4mm_cor_aivot_20170619110200_601
ax_20170619110200_200
Luinen_kallo_20170619110200_3 (its the same file you've seen in my previous posts)

with a log file and "-m y":
[dcm2niix_log_file_m_setting_anonym.txt](https://github.com/rordenlab/dcm2niix/files/1481975/dcm2niix_log_file_m_setting_anonym.txt)

with a log file and "-m n":
[dcm2niix_log_file_anonym.txt](https://github.com/rordenlab/dcm2niix/files/1481984/dcm2niix_log_file_anonym.txt)

the conversion looked like the following snapshots:
A) "-m n"
![200-before-m-anonym](https://user-images.githubusercontent.com/20206739/32944699-1c244888-cb99-11e7-91a8-4818460ab632.png)
![601_before-m-anonym](https://user-images.githubusercontent.com/20206739/32944700-1c46136e-cb99-11e7-8c91-b1180f39d011.png)
![602-before-anonym](https://user-images.githubusercontent.com/20206739/32944701-1c6732ec-cb99-11e7-97ca-e1d85c18c12e.png)
![luinen_kallo_before-m-anonym](https://user-images.githubusercontent.com/20206739/32944704-1c8d446e-cb99-11e7-80b3-66945c745033.png)

B) "-m y"
![200-after-anonym](https://user-images.githubusercontent.com/20206739/32944797-66424168-cb99-11e7-813d-00b8d67a6258.png)
![601-afterm-anonym](https://user-images.githubusercontent.com/20206739/32944798-66651c74-cb99-11e7-9e99-2941437464e6.png)
![602-after-anonym](https://user-images.githubusercontent.com/20206739/32944799-6684f800-cb99-11e7-988d-45491451866d.png)
![luinen-after-anonym](https://user-images.githubusercontent.com/20206739/32944800-66a7c380-cb99-11e7-8e63-43d09202296e.png)

**Comment by neurolabusc** [comment]
Thanks, this looks like you have resolved this issue. The output reports that some scans come from a Siemens system and others come from a GE system. One set requires the images to be merged while the other does not. Without access to your images, I can not provide a good method to auto-detect a solution. Perhaps you can acquire phantom data or develop a patch that you can submit. In the meantime, use the 'm'erge command as required.

**Comment by athanell** [comment]
Thank you for the assistance @neurolabusc
