### ISSUE TITLE
GE diffusion data

### ISSUE THREAD

**Issue by mattgs1** [rordenlab/dcm2niix#149]
Hi, when converting DWI data from a GE scanner I'm getting b-values of zero and sets of b-vectors of zeros too. Looking at the DICOM header the data seems to be contained in dicom tag (0043,1039) in an unusual format of "1000001000\8\0\0" where the b-value in this case is 1000. Is this issue familiar and is there any way of getting the correct bvalues and bvectors in this case?

**Comment by neurolabusc** [comment]
Sounds like you have a Signa Excite 12.0 or later
  https://www.na-mic.org/wiki/NAMIC_Wiki:DTI:DICOM_for_DWI_and_DTI
I do not have access to data from one one these systems. Can you share a dataset with me (e.g. send a link to dropbox archive in a private email, or share with the [whole world)?](https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#Diffusion_Tensor_Imaging) Otherwise, feel free to submit a patch as a pull request.

**Comment by neurolabusc** [comment]
I looked at several sample GE datasets, and they all seem to conform to the description on the [na-mic](https://www.na-mic.org/wiki/NAMIC_Wiki:DTI:DICOM_for_DWI_and_DTI) web site.
The b-values stored in 0043,1039: e.g. B-value of zero listed as "0\8\0\0" and b-value of 1000 as "1000\8\0\0" (with b-vectors stored in 0019,10BB; 0019,10BC; 0019,10BD). Unfortunately 0043,1039 is a private tag, so there is no formal definition. I do think you will need to contact GE for details. One thought is that perhaps these are derived images, such as ADC maps. While the DICOM standard requires that derived images are saved as a separate series, not all vendors have respected this. For example, some Philips systems will save derived ADC maps where the b-vector is set with no length (0,0,0) but the b-value is saved as a positive value (e.g. 1000). So perhaps "1000001000" has some special meaning for GE, or perhaps it is a bug. If it does have a special meaning, your dataset is in violation of the DICOM standard if the image has the same series number as the raw data. So in either case (DICOM violation or bug), it is worth contacting your vendor. You might gain some insight by comparing the number of volumes stored with the number of volumes acquired and conducting visual inspection to determine if it is a B=0 image, a B-weighted image or a derived image (ADC, MD, FA, etc).

**Comment by mattgs1** [comment]
Thanks for your reply. I've sent you the data separately via email and I'll contact GE too.

**Comment by neurolabusc** [comment]
Thanks for the example. I can confirm that your dataset has tag 0043,1039 (SlopInt_6_9) reporting an implausible b-value (1000000010). Either this is a bug, or our understanding of this vendor private element is incorrect. Furthermore, these images report no vector direction. At the moment this is not an issue with dcm2niix, but rather either an issue with the vendor or our understanding of the vendors use of private tags. Please tell me if you learn anything more about these images.

**Comment by mattgs1** [comment]
Seems like the b-value is given by: 
b =(0043,1039)-(0043,107F)
(SlopInt6_SlopInt9 - ReservedForFutureUse1)

This works for my dataset. Would this work for the other sample GE datasets you've looked at?

I will let you know if I hear anything else about the bvector.

**Comment by neurolabusc** [comment]
I have not seen other datasets where SlopInt6 does not match the b-value. I also can not see any tags in your dataset that look like plausible bvectors.

**Comment by ihnorton** [comment]
You might want to look at DWIConvert's [GE extraction routine](https://github.com/BRAINSia/BRAINSTools/blob/c1289e6686f3fd27db2ce0ea19c36e9792e40d2a/DWIConvert/GEDWIConverter.cxx#L24-L46) (Apache licensed), especially the comment.

FWIW, I have a local copy of the DWIConvert test data "GeSignaHDx" dataset, which has the following scanner version:
```
(0018,1020) LO [14\LX\MR Software release:14.0_M5A_0828.b] #  42, 3 SoftwareVersions
```

and the bval also looks reasonable:
```
(0043,1039) IS [1000\67108872\0\0]                      #  18, 4 Unknown Tag & Data
```

**Comment by neurolabusc** [comment]
@ihnorton - thanks for the link. Your sample data does seem to conform to your link as well as the NAMIC link I provided. However, @mattgs1 images do not appear to follow these conventions in either b-value or bvector. 

```
(0018,1020) LO [26\LX\MR Software release:MP24.0_R03_1712.b]
(0043,1039) IS [1000000030\8\0\0]
```
For the moment, I will close this. The sample dataset does not appear to match any known GE encoding scheme. Perhaps this is a bug in how the data was created, or perhaps GE is using a unknown encoding scheme. But we can not solve this with the available information.
