### ISSUE TITLE
'PhaseEncodingDirection' from philips scans for BIDS topup

### ISSUE THREAD

**Issue by zswgzx** [rordenlab/dcm2niix#151]
Hi.

I'm using dcm2niix (v1.0.20171103 (OpenJPEG build) GCC5.3.1) to convert acquisitions with opposite phase encoding directions from Philips scanner, in order to obtain the PhaseEncodingDirection in the json file for BIDS topup correction. Is it possible currently?

Thanks.

**Comment by neurolabusc** [comment]
Assuming that your DICOM data reports the In-plane Phase Encoding Direction [0018,1312](http://dicomlookup.com/lookup.asp?sw=Tnumber&q=(0018,1312)), and you use dcm2niix to create a BIDS file ("-b y"), you should be able to detect a difference in the BIDS field InPlanePhaseEncodingDirectionDICOM. I do not have access to a Philips system, but I assume this is correct. If this does not work for you and you can provide further information, please reopen this issue.

**Comment by mharms** [comment]
I think this user was inquiring about getting the PE *polarity* from Philips DICOMs.

**Comment by neurolabusc** [comment]
Yes, @mharms is right: 0018,1312 tells us if the phase encoding direction is in the COLUMN (i) or ROW (j) direction, but it does not tell us if the direction is in ascending or descending within this dimension. I do not know if this information is encoded in the Philips DICOMs: does anyone know, and do we have sample datasets that validate this property? At the moment, I do not know how to solve this problem (or even if it is solvable: e.g. is the information stored in the header).

**Comment by neurolabusc** [comment]
According to Matthew Clemence at Philips, the phase encoding gradient polarity is not encoded in r5.3 (even in the private headers). A request has been made for a future release. Therefore, I am closing this issue as dcm2niix can not provide this information based on the current Philips DICOMs.
