### ISSUE TITLE
do you think Image Orientation (Axial, Coronal, Sagital) could be placed into sidecar?

### ISSUE THREAD

**Issue by yarikoptic** [rordenlab/dcm2niix#153]
[NDA](https://ndar.nih.gov/data_structure.html?short_name=image03) now requires an `image_orientation` field, which is limited to three those values (although allowing for a string with length up to 20).  So I wondered, if the deduction of the orientation (probably from the ImageOrientationPatientDICOM quaternion (?)) should be done, who should do it: bids2nda, or may be dcm2niix? ;-)

attn: @chrisfilo , @mtnhuck

**Comment by chrisfilo** [comment]
This could be derived from the BIDS field SliceEncodingDirection if such
was present in the JSON file created by dcm2niix.

Best,
Chris

**Comment by yarikoptic** [comment]
those are in i,j,k ... would it be directly translatable to the notion of Axial/Coronal/Sagital which really depend on how you position your matrix?

**Comment by chrisfilo** [comment]
Good point!

Best,
Chris

**Comment by neurolabusc** [comment]
The current version of dcm2niix creates the tag "ImageOrientationPatientDICOM" filled with DICOM vectors from tag (0020,0037). I would think bids2nda shouldbe able to use this to determine if the slice is axial, coronal, or transverse (though as you note having only those 3 values does cause a problem as many scans are oblique). 

https://stackoverflow.com/questions/34782409/understanding-dicom-image-attributes-to-get-axial-coronal-sagittal-cuts

ftp://dicom.nema.org/MEDICAL/dicom/2015b/output/chtml/part03/sect_C.7.6.2.html#sect_C.7.6.2.1.1

My sense is for the moment this should be handled with bids2nda, to reduce redundancy in the BIDS specification. If someone wants to create and maintain a direct nda export for dcm2niix, they can submit a pull request.

**Comment by yarikoptic** [comment]
Thanks! Makes sense.
