### ISSUE TITLE
Are there any reliable way to tell if a image is T1w or T2w or whatever?

### ISSUE THREAD

**Issue by suxpert** [rordenlab/dcm2niix#155]
For example, I have tons of data to analysis, they may from different scanners.

After I convert them using dcm2niix, the same modality images may have variety names, renaming each data file will be quite boring.

So if there exist some easier way in doing such a job, to rename files according to their modality using information in the sidecar json file?

**Comment by chrisfilo** [comment]
For writing heuristics to automatically rename files created by dcm2niix you might want to check out https://github.com/nipy/heudiconv.

**Comment by neurolabusc** [comment]
As @chrisfilo notes, there several tools that call dcm2niix and use it to categorize your data (e.g. [Dcm2Bids, bidskit, DAC2BIDS, heudiconv](https://github.com/rordenlab/dcm2niix)). As @hanayik notes you can also write a simple script to do this for your own data. This task is beyond the remit of dcm2niix. First of all, while some scans have predominantly T1-weighting, and others have predominantly T2-weighting, one can devise sequences with a mixture of these static contrasts. In addition, sequences can combine static, endogenous, exogenous, and motion contrasts. Further, different vendors use different terms for the same sequence (3D FGRE, 3D TFE, MPRAGE). One needs to consider issues like inversion time,  fat suppression, etc. Depending on your analyses, you may want to clump together sequences that vary these parameters, while other users may feel these variations impact the pre-processing and need to be modeled. The DICOM to BIDS converters I listed help solve this issue. By using scripting languages they allow the users the flexibility to control discrete categorization of datasets.
