### ISSUE TITLE
Confusion with calculation of qform matrix

### ISSUE THREAD

**Issue by jstutters** [rordenlab/dcm2niix#159]
I'm having some difficulty working out how dcm2niix is working out the qform matrix from a set of DICOM images.

Based on the [nibabel documentation](http://nipy.org/nibabel/dicom/dicom_orientation.html#dicom-3d-affines) rows 1-3 of the final column of the qform matrix should match the image position patient vector from the first slice of the collection of DICOMs but that's not the case in my converted images.  Is dcm2niix scaling this or computing it in some other way.

I'm trying to convert some images I have in a legacy format for which I have the DICOM headers and pixel data but not DICOM format files.

Thanks for any help that can be provided.

**Comment by neurolabusc** [comment]
I wrote that a while ago. But be aware that the X and Y dimensions flipped in NIfTI (RAS) vs DICOM (LPS) as described [here](http://www.cs.ucl.ac.uk/fileadmin/cmic/Documents/DavidAtkinson/DICOM.pdf), [here](https://www.slicer.org/wiki/Coordinate_systems) and [here](https://nifti.nimh.nih.gov/nifti-1/documentation/faq#Q14). When you flip the axis, you also need to flip the origins. Canonically, DICOM writes images to disk the way you read english: with the first row being on top, while by default NIfTI images are stored to disk with cartesian graphing coordinates, with values ascending from the bottom of the screen to the top. You can choose the output of the data with `opts.isFlipY`, and the sform/qform is rotated appropriately. The heavy lifting is done by the function `verify_slice_dir()`. In my opinion, C is a low level language that can obscure transforms, I would suggest you look at the elegant Matlab [dicm2nii](https://www.mathworks.com/matlabcentral/fileexchange/42997-dicom-to-nifti-converter--nifti-tool-and-viewer) for clear code for manipulating between DICOM and NIfTI space.

As an aside, things are a bit more complicated if your images are stored as mosaics. Here I assume the conventional 2D slices.

**Comment by jstutters** [comment]
Thanks very much for your help.  Reading through dicm2nii gave me enough information to reproduce the affine transforms from dcm2niix in the cases I have to deal with.
