### ISSUE TITLE
file not large enough to store image data

### ISSUE THREAD

**Issue by renero69** [rordenlab/dcm2niix#162]
Dear Chris,

I'm running dcm2niix on a Centos7 server to convert some dynamic DICOM sequences.
The program works well for some subjects using the cmd:

/usr/local/mricrogl_lx/dcm2niix -f %n .

In some other cases it gives the error reported in the Object of this mail.
This is an example:

Chris Rorden's dcm2niiX version 1Jan2017 (64-bit Linux)
Found 3080 DICOM image(s)
Philips Precise RS:RI:SS = 1.32161:0:0.000224734 (see PMC3998685)
Philips Precise RS:RI:SS = 1.32161:0:0.000224734 (see PMC3998685)
Philips Precise RS:RI:SS = 1.32161:0:0.000224734 (see PMC3998685)
Philips Precise RS:RI:SS = 1.32161:0:0.000224734 (see PMC3998685)
Philips Precise RS:RI:SS = 1.32161:0:0.000224734 (see PMC3998685)
Philips Precise RS:RI:SS = 1.32161:0:0.000224734 (see PMC3998685)
Philips Precise RS:RI:SS = 1.32161:0:0.000224734 (see PMC3998685)
Philips Precise RS:RI:SS = 1.32161:0:0.000224734 (see PMC3998685)
Philips Precise RS:RI:SS = 1.32161:0:0.000224734 (see PMC3998685)
Philips Precise RS:RI:SS = 1.32161:0:0.000224734 (see PMC3998685)
Philips Precise RS:RI:SS = 1.32161:0:0.000224734 (see PMC3998685)
Philips Precise RS:RI:SS = 1.32161:0:0.000224734 (see PMC3998685)
Philips Precise RS:RI:SS = 1.32161:0:0.000224734 (see PMC3998685)
Philips Precise RS:RI:SS = 1.32161:0:0.000224734 (see PMC3998685)
Philips Precise RS:RI:SS = 1.32161:0:0.000224734 (see PMC3998685)
Philips Precise RS:RI:SS = 1.32161:0:0.000224734 (see PMC3998685)
..............................................
Philips Precise RS:RI:SS = 1.32161:0:0.000224734 (see PMC3998685)
Philips Precise RS:RI:SS = 1.32161:0:0.000224734 (see PMC3998685)
Philips Precise RS:RI:SS = 1.32161:0:0.000224734 (see PMC3998685)
Philips Precise RS:RI:SS = 1.32161:0:0.000224734 (see PMC3998685)
Philips Precise RS:RI:SS = 1.32161:0:0.000224734 (see PMC3998685)
Philips Precise RS:RI:SS = 1.32161:0:0.000224734 (see PMC3998685)
Philips Precise RS:RI:SS = 1.32161:0:0.000224734 (see PMC3998685)
Philips Precise RS:RI:SS = 1.32161:0:0.000224734 (see PMC3998685)
Philips Precise RS:RI:SS = 1.32161:0:0.000224734 (see PMC3998685)
Philips Precise RS:RI:SS = 1.32161:0:0.000224734 (see PMC3998685)
Philips Precise RS:RI:SS = 1.32161:0:0.000224734 (see PMC3998685)
swizzling 3rd and 4th dimensions (XYTZ -> XYZT), assuming interslice distance is 2.500000
**File not large enough to store image data: ./IM-0011-1521-0003.dcm**
Conversion required 0.450000 seconds.

The system is a 64 bit OS. I run the same command on my macbook and it works fine.
I suppose it could be due to the version of dcm2niix (32 bit? How do I verify it?). I re-downloaded it from the official site but the *.zip file (linux 64 bit) is corrupted.

Which could be the problem?

Thank you so much

Domenico

**Comment by neurolabusc** [comment]
The issue is you are using `version 1Jan2017` [the latest release (v1.0.20171215)](https://github.com/rordenlab/dcm2niix/releases). With regards to the Philips scaling warnings, these reflect the fact that your images provide [two contradictory ways to map the raw image intensity to scaled values](https://www.nitrc.org/forum/message.php?msg_id=20990). This reflects a property of your images - my software allows you to extract either of the scaling values.

**Comment by renero69** [comment]
Dear Chris,

I downloaded the version you suggested but now I have the following errors:

/usr/local/dcm2niix: /lib64/libm.so.6: version `GLIBC_2.15' not found (required by /usr/local/dcm2niix)

Could you please suggest me something? I hope this is the last question.

Sorry

Domenico

**Comment by neurolabusc** [comment]
If you have a version of Linux with libraries that predate those used by the Travis auto-build script, you can simply compile your own copy. The typical install would be:

```
git clone https://github.com/rordenlab/dcm2niix.git
cd dcm2niix
mkdir build && cd build
cmake ..
make
```
For a very stripped-down build (which does not require your system to have OpenJPEG libraries installed) you could do

```
git clone https://github.com/rordenlab/dcm2niix.git
cd dcm2niix/console
make
```
See the [dcm2niix homepage](https://github.com/rordenlab/dcm2niix) for compilation details.

If you do not have compilers or git installed, another option is to get the most recent release of [MRIcroGL](https://github.com/neurolabusc/MRIcroGL/releases). I create that on an ancient CentOS 6 system, so it is compatible with most recent systems. The version of dcm2niix bundled with MRIcroGL tends not to be the leading edge (as versions of MRIcroGL are much more arduous to compile and validate), but hopefully the versions of dcm2niix is good enough for your case.

**Comment by renero69** [comment]
Thanks a lot

Domenico

Il 14 Feb 2018 18:34, "Chris Rorden" <notifications@github.com> ha scritto:
