### ISSUE TITLE
Error during conversion of 4D sequences

### ISSUE THREAD

**Issue by renero69** [rordenlab/dcm2niix#164]
Dear Chris,

as you know, I'm converting some 4D sequences with dcm2nii/dcm2niix.
I don't understand why, some of them are correctly converting whereas some other are not.
Here is the command I use:

**/usr/bin/dcm2nii -4 Y -d y -e n -f n -g n -i y -n y -p n -s n name_first_dicom.dcm**

and here is a typical error:

> Chris Rorden's dcm2nii :: 4AUGUST2014 (Debian) 64bit BSD License
> reading preferences file /home/neurorad/.dcm2nii/dcm2nii.ini
> 0 files in working directory /home/dati/PR_2018_DENDR1/DCE/coregistrazione/XXX_010917/Rm_Encef__Fossa_Cranica_Post_Con_Mdc - 536239423/XXX_DCEt1dinamica_01_09_2017
> Data will be exported to /home/dati/PR_2018_DENDR1/DCE/coregistrazione/XXX_010917/Rm_Encef__Fossa_Cranica_Post_Con_Mdc - 536239423/SXXX_DCEt1dinamica_01_09_2017
> Validating 3082 potential DICOM images.
> dcm Error: not a DICOM image: /home/dati/PR_2018_DENDR1/DCE/coregistrazione/XXX_010917/Rm_Encef__Fossa_Cranica_Post_Con_Mdc - 536239423/XXX_DCEt1dinamica_01_09_2017/IM-0165-0952.dcm
> Found 3079 DICOM images.
> *Warning: Number of images in series (3079) not divisible by number of volumes (70)
> *  Perhaps the selected folder only has some of the images
> *  Potential partial acquisition or improper segmentation of files
> *  Possible solution: use -c Y and use folder containing subdirectories as input
> *            or change .ini file to read: CollapseFolders=1
> Warning: Number of slices per volume (43)appears different than reported in DICOM header (44)
>   Perhaps the selected folder only has some of the images
> Converting 3079/3079  volumes: 70
> IM-0165-0001.dcm->20170901_132343XXX.nii
>  brightest voxel was 4095: data will be saved as 16-bit signed integer.
> Saving ...
> 

The RM sequence is a dynamic sequence (4D) composed by 70 volumes (44 slices each). The total amount of DICOM images should be 3080.

Thanks a lot,

Domenico

**Comment by neurolabusc** [comment]
You are using software from 2014. I suspect your images are from a modern system that uses features we had not seen back then. Can I suggest you use a [recent release](https://github.com/rordenlab/dcm2niix/releases). Unfortunately, DICOM conversion is an arms race, where the specifications and vendors are evolving over time. In addition, our understanding of this usage changes over time. If this fails to fix your problem, please send sample images that illustrate the problem to me directly.

The other likely possibility is that the software is correct, and not all the files acquired are stored in the folder (or the acquisition was halted mid-way through the acquisition of a volume).

**Comment by renero69** [comment]
Dear Chris,

I would like to send you the images using WeTransfer.
Could you please tell me which mail address to use?

Thank you so much,

Domenico

2018-02-19 15:29 GMT+01:00 Chris Rorden <notifications@github.com>:

**Comment by renero69** [comment]
Dear Chris,

I'm sending you some example files. They are a part of the same sequence (that should be 3080 images and 70 volumes, as previously said). Could you please help me? I tried with the new dcm2niix version but instead of producing 70 volumes of 44 slices each, it produces one volume of 3079 images.

Thank you

Domenico
[Dce-ex.zip](https://github.com/rordenlab/dcm2niix/files/1740256/Dce-ex.zip)

**Comment by neurolabusc** [comment]
The dataset you sent me can not be converted, there are 268 slices from a much larger series. The series is saved in order of ascending time and then ascending slice (s1t1, s1t2, s1t3...s1tn, s2t1, s2t2...) so there are no complete volumes. Either send me the complete dataset or send me complete volumes (e.g. all slices from specific time points). You can see the issue if you view the slices you sent me with Horos or any other DICOM viewer.

**Comment by renero69** [comment]
Dear Chris,

after sending you the images, I perhaps found the problem. One of the
images (in a lot of subjects...!) is not identified as a DICOM image. I
verified it using matlab too. So I transferred again the images to the
server and now, for that patient, dcm2nii works. It was not a problem of
your script.

Thank you so much

Domenico

2018-02-20 16:17 GMT+01:00 Chris Rorden <notifications@github.com>:
