### ISSUE TITLE
Problems with Philips Dicom to Nifti extraction

### ISSUE THREAD

**Issue by garikoitz** [rordenlab/dcm2niix#165]
Hi!
we have several Philips flat dicoms that look ok when visualized with Philips software but that they fail in the conversion. We see this error in the conversion (this error is from Flywheel, but same output when converted in command line):

[scitran/dcm2niix]  running...
[scitran/dcm2niix]  Unzipping /flywheel/v0/input/dcm2niix_input/WIP DTI 64dir_b1000 SENSE.zip
Error: Patient position repeats 50 times, but this does not evenly divide number of volumes (65)
Chris Rorden's dcm2niiX version v1.0.20170923 (OpenJPEG build) GCC4.8.4 (64-bit Linux)
Found 2 DICOM image(s)
Warning: Philips R3.2.2 can report different positions for the same slice. Attempting patch.
Converting XYTZ to XYZT with 64 slices (Z) and 65 volumes (T).
Warning: Saving 65 DTI gradients. Validate vectors (images are not axial slices).
Convert 1 DICOM as /flywheel/v0/output/WIP DTI 64dir_b1000 SENSE (128x128x64x65)
Philips Precise RS:RI:SS = 4.05421:0:0.000509404 (see PMC3998685)
 R = raw value, P = precise value, D = displayed value
 RS = rescale slope, RI = rescale intercept,  SS = scale slope
 D = R * RS + RI    , P = D/(RS * SS)
 D scl_slope:scl_inter = 4.05421:0
 P scl_slope:scl_inter = 1963.08:0
 Using P values ('-p n ' for D values)

Are there options we could select in the software to have the conversion right?
Thanks!

**Comment by neurolabusc** [comment]
I have been struggling to deal with the fact that Philips tends to use multiple patient positions for the same data. I think this is technically legal as one is in a private tag, but this subtlety is hard to detect, in particular if one uses implicit VRs. 

1.  I would first see if the latest stable release fixes your problem 15-Dec-2017 (v1.0.20171215)
  https://github.com/rordenlab/dcm2niix/releases
2. If that fails, why not try building from the latest source on Github
3. If that fails, please tell me. As a stop gap, you could see if the Matlab-based dicm2nii works (though I would still like to know - I do not have access to Philips hardware, so examples where dcm2niix fails are very instructive).

**Comment by garikoitz** [comment]
Thanks! 
I will try and update results here
