### ISSUE TITLE
Fieldmap BIDS issue

### ISSUE THREAD

**Issue by dkp** [rordenlab/dcm2niix#166]
I am looking at the bids spec and the output of dcm2niix for my fieldmaps.
Our data were acquired on a Siemens Skyra 3T with Syngo MR V11a software. I believe they are pretty standard fieldmap sequences for that system.

dcm2niix generates 3 images for the fieldmap sequence. 

Here's my confusion: if the phase image is a phasediff image, I would expect two echo times in the json file, as per my reading of the bids spec, but I only see one echo time. 

If it is a phase image (rather than phasediff), then I would expect to have 4 images (2 magnitude and 2 phase) for my fieldmap output....but I don't get that either.

The images and the json files are here, including the dcm images in gre_field_mapping.tgz: https://arizona.box.com/s/3y3z0fn4s04oopd8uyvpl8eugxmjq85z

I appreciate your time.

-Dianne Patterson

**Comment by mharms** [comment]
This issue was addressed here #139.  The DICOM itself only reports a single echo for the "Phase difference" map, so that is what 'dcm2niix' is reporting.

**Comment by neurolabusc** [comment]
I am going to close this issue for now. If anyone knows how to solve this (e.g. peaking at the ASCII portion of the CSA header), please reopen this issue and we can add this information into the BIDS header. At present, dcm2niix is faithfully decoding all the available information that we know about. Users may also want to lobby the vendor to explicitly include this information (e.g. using a private DICOM tag).
