### ISSUE TITLE
dcm2niix fails for Philips PAR/REC to Nifti conversion (only BOLD-fMRI files)

### ISSUE THREAD

**Issue by lukassnoek** [rordenlab/dcm2niix#171]
Hi!

I noticed that dcm2niix fails to convert Philips PAR/REC files to Nifti in the latest release (v1.0.20171215). There is no error message apart from `Done reading PAR header version 4.2, with 1 volumes` (see image below).

![image](https://user-images.githubusercontent.com/6350135/37606587-1918f6a4-2b96-11e8-9f04-4b20a67d9ef1.png)

I've did some testing and it only seems to occur for BOLD-fMRI files, but not for T1-weighted images or fieldmaps (based on phase-difference images). Also, the problem is still present in the master-version on Github (compiled on Ubuntu 16.04), but *not* in the version from December 8, 2017 (v1.0.20171204).

I've prepared a 'minimal dataset' (a fieldmap scan and BOLD-fMRI scan) with PAR/REC files on which dcm2niix fails - this may be helpful in debugging? If so, to which email-address should I send the download link?

Let me know if you need more information and thanks for the effort!

**Comment by neurolabusc** [comment]
Should be fixed in [v1.0.20180325](https://github.com/rordenlab/dcm2niix/releases/tag/v1.0.20180325). @lukassnoek can you please test and report if any issues linger.
