### ISSUE TITLE
Slice timing in JSON files

### ISSUE THREAD

**Issue by mfalkiewicz** [rordenlab/dcm2niix#181]
Dear developers,
  I am not sure this is an issue with dcm2niix, but since it might be I'm posting it here. I am currently working on a simple tool that injects the slice timing estimates to the JSON files to allow slice timing correction even if the slice timing data was not present in the DICOMs. A natural way of testing my estimates is against "real" data, i.e. files for which the slice timings were successfully extracted with dcm2niix. Here is where it gets tricky. 

http://www.mccauslandcenter.sc.edu/crnl/tools/stc claims that the last slice is acquired at time TR - (TR/n_slices). Thus, I generated the following estimates of slice times for TR = 3 and n_slices = 48:

last_slice = TR - TR/n_slices
st_estimated = np.linspace(0, last_slice, n_slices)

Then I compared the estimates to the values contained in a dcm2niix-generated JSON file. To my surprise, there is some offset:

>In[67]: list(zip(true_st, st_estimated))
Out[67]:
[(0, 0.0),
 (0.0625, 0.0625),
 (0.125, 0.125),
 (0.1875, 0.1875),
 (0.2475, 0.25),
 (0.31, 0.3125),
 (0.3725, 0.375),
 (0.435, 0.4375),
 (0.4975, 0.5),
 (0.56, 0.5625),
 (0.62, 0.625),
 (0.6825, 0.6875),
 (0.745, 0.75),
 (0.8075, 0.8125),
 (0.87, 0.875),
 (0.9325, 0.9375),
 (0.9925, 1.0),
 (1.055, 1.0625),
 (1.1175, 1.125),
 (1.18, 1.1875),
 (1.2425, 1.25),
 (1.305, 1.3125),
 (1.365, 1.375),
 (1.4275, 1.4375),
 (1.49, 1.5),
 (1.5525, 1.5625),
 (1.615, 1.625),
 (1.6775, 1.6875),
 (1.7375, 1.75),
 (1.8, 1.8125),
 (1.8625, 1.875),
 (1.925, 1.9375),
 (1.9875, 2.0),
 (2.0475, 2.0625),
 (2.11, 2.125),
 (2.1725, 2.1875),
 (2.235, 2.25),
 (2.2975, 2.3125),
 (2.36, 2.375),
 (2.42, 2.4375),
 (2.4825, 2.5),
 (2.545, 2.5625),
 (2.6075, 2.625),
 (2.67, 2.6875),
 (2.7325, 2.75),
 (2.7925, 2.8125),
 (2.855, 2.875),
 (2.9175, 2.9375)]

It seems like the time gap between slices is usually 0.0625, but sometimes it's 0.06. In this case it's 0.06 since the 4th slice (indexed from 1) every 6 slices, with one exception - 5 slices between slice 28 and 33. Note that this is a single-band acquisition on Prisma.

My questions are: 
1. how are the slice times extracted by dcm2niix? Are they extracted directly, or somehow inferred? 
2. assuming that the dcm2niix-extracted values are "true", do you think the offset introduced in the approximation "badly mess up the signal" ?
3. assuming that the dcm2niix values are "true", what would be the method of recovering these times based on other parameters?

Thanks for your help!

**Comment by neurolabusc** [comment]
Would the stc web page be clearer if I changed the `Therefore` to `In these situations` for the sentences `Typically, we acquire fMRI data continuously with no gaps between volumes. Therefore, the acquisition time (TA)...`? As noted later in this paragraph, this approximation (with the same formula provided in SPM) and will have an error if there is a slice time delay added. This difference is typically negligible: we acquire data as fast as we can and the error is tiny compared to the overall TR. However, this error can become sizeable for sparse designs (where slice timing is inappropriate).

1. Assuming you have a Siemens scanner, dcm2niix will read the tag [MosaicRefAcqTimes](https://en.wikibooks.org/wiki/SPM/Slice_Timing) from the proprietary Siemens CSA header.
2. I think the error from your formula is tiny, in terms of interpolation this can be seen as a fraction of TR, so at maximum it is about the max error is 0.006666667. Or you could see the max error of the approximation is 0.02s, which is tiny when you consider we are modeling the HRF which is a sluggish function that has a positive pulse of about 12s.
 3. Assuming you are not using multiband, and having the BIDS fields "RepetitionTime"=TR and "DelayTime"=Delay the TA is TR-Delay. The Delay time is from the dreaded ASCII portion of the Siemens CSA header, with the identifier `lDelayTimeInTR`. The slice time increment is then TA - TA/n_slices. You can see concrete examples at [dcm_qa](https://github.com/neurolabusc/dcm_qa/tree/master/Ref). For example, consider the protocol cor_asc_35sl where the TR is 3, the Delay is 0.5 and the number of slices is 35. In this case the slice increment is 0.071428571s. So if the first slice is acquisition starts at time 0, and the start of the final slice begins at 2.428571429s (to finish at 2.5, the fence post problem). The Siemens MosaicRefAcqTimes reports the final slice time as 2.4375s, suggesting the true Delay was 0.49s. It is common to see small rounding errors between requested values and actual (when specifying parameters the interface is limited to a small number of significant digits).

**Comment by mfalkiewicz** [comment]
Hello,
  thank you very much for a quick reply. Regarding point 3, I do not believe that I am dealing with a sparse acquisition here. If you look at the times in the .json, 40/48 slices have 0.0625s delay between them and 8 have a 0.06s delay. With linspace, the estimated delay is constant (0.0625) and that's where the discordance comes from. I agree that this difference is tiny, especially with respect to TR and HRF characteristics, but this implies that the slices are not equally spaced in time and thus estimation errors are unavoidable. On the margin - I do not have the DelayTime field in the JSON files. 

Also, the change of phrasing on the website would definitely help.

Thank you for your thorough explanations!

**Comment by neurolabusc** [comment]
As I described in the dcm_qa example above, there are often very small differences between what Siemens explicitly reports in MosaicRefAcqTimes and what you would derive from the values. I suspect these reflect rounding errors in the acquisition, but potentially also rounding errors in how the values are saved in MosaicRefAcqTimes. If DelayTime is not reported it might reflect a DelayTime of zero, an old version of dcm2niix or the fact that the CSA header omitted this value. The first option seems the most likely, especially as your errors are very small.
