### ISSUE TITLE
Merge ECAT conversion from older release into current release

### ISSUE THREAD

**Issue by lwallace233** [rordenlab/dcm2niix#183]
We have tested the ecat conversion using the dcm2niix v1.0.20170428 release (https://github.com/rordenlab/dcm2niix/releases/tag/v1.0.20170428 ). The results of the conversion were successfully processed through our PET analysis pipelines. However we noticed the conversion is no longer available in current versions. Would you mind adding this to the current release so we can use one tool for ecat and dicom conversion?

Thanks

**Comment by neurolabusc** [comment]
ECAT support seems functional with the latest source code (v1.0.20180404). You should be able to provide a file name or have it search for files in a folder. The examples below show both methods:

```
$ ./dcm2niix ~/tst/ecat/ECAT7_test.v 
Chris Rorden's dcm2niiX version v1.0.20180404 GCC6.1.0 (64-bit MacOS)
Warning: ECAT support VERY experimental (Spatial transforms unknown)
Saving ECAT as '/Users/rorden/tst/ecat/ecat_listmode204_19770703150928_1'

./dcm2niix ~/tst/ecat/
Chris Rorden's dcm2niiX version v1.0.20180404 GCC6.1.0 (64-bit MacOS)
Warning: ECAT support VERY experimental (Spatial transforms unknown)
Saving ECAT as '/Users/rorden/tst/ecat/ecat_listmode204_19770703150928_1'
Error: Unable to find any DICOM images in /Users/rorden/tst/ecat
```

**Comment by lwallace233** [comment]
Here is the behavior we are getting, using an ECAT file from the OASIS project (my colleague Pamela LaMontagne believes you should already have a copy of some of our ECAT files, this test file is one of those.)

In the 4/28/2017 release, the file converts:

/dcm2niix-2017.04.28/dcm2niix  ./ecat_test/OAS30001_PIB_d0423pib1.v
Compression will be faster with /usr/local/bin/pigz
Chris Rorden's dcm2niiX version v1.0.20170428 GCC4.4.7 (64-bit Linux)
Warning: ECAT support VERY experimental (Spatial transforms unknown)
Saving ECAT as './ecat_test/OAS30001_PIB_d0423pib1'
Conversion required 10.087062 seconds (8.730000 for core code).

But by the 10/17/2017 release, the conversion seems to have broken:

/dcm2niix-2017.10.17/dcm2niix  ./ecat_test/OAS30001_PIB_d0423pib1.v
Compression will be faster with 'pigz' installed
Chris Rorden's dcm2niiX version v1.0.20171017 GCC4.4.7 (64-bit Linux)
Error reading ECAT file

We tried the pre-release 3/28/2018 version (this time on Windows) and are getting the same behavior:

dcm2niix.exe OAS30001_PIB_d0423\scans\1_Dynamicemission\test\OAS30001_PIB_d0423pib1.v
Compression will be faster with pigz.exe in the same folder as the executable
Chris Rorden's dcm2niiX version v1.0.20180328 (OpenJPEG build) MSC1900 (64-bit Windows)
Error reading ECAT file

Ideally, we would like a version that can both convert the data from ECAT and that includes the PET BIDS sidecar generation in the latest versions of the code so we can both convert DICOM and ECAT to NIFTI and generate BIDS sidecars for both.

**Comment by neurolabusc** [comment]
Issue will be fixed in upcoming build. For a few releases dcm2niix would not convert ECAT data where the images were saved with 16-bit precision but different intensity scaling values were specified for different slices (requiring conversion to 32-bit float format).
