### ISSUE TITLE
dcm2niix setting sform_code to 1 even when the sform is bogus

### ISSUE THREAD

**Issue by captainnova** [rordenlab/dcm2niix#186]
Hi, we have been given a couple of GE SPECT images that do not have the ImageOrientationPatient (0020,0037) tag that we are used to from MRI, but the voxel size parameters are OK.  dcm2niix is setting pixdim correctly, but it is also setting both qform_code and sform_code to 1 even though it knows they are bogus.  This confuses downstream software that prefers the sform over the qform or pixdim if sform_code = 1.  dcm2nii sets both codes to 0.  Is there a reason for the change?

dcm2niix's output:
dcm2niix -o . DICOM
Chris Rorden's dcm2niiX version v1.0.20171215 (OpenJPEG build) GCC4.4.7 (64-bit Linux)
Found 1 DICOM image(s)
Unable to determine spatial orientation: 0020,0037 missing (probably not a problem: derived image)
Unable to determine spatial orientation: 0020,0037 missing (probably not a problem: derived image)
Unable to determine spatial orientation: 0020,0037 missing (probably not a problem: derived image)
Warning: Unable to determine slice direction: please check whether slices are flipped (derived image)
Warning: Bogus spatial matrix (perhaps non-spatial image): inspect spatial orientation
Convert 1 DICOM as ./TRANSVERSE_BRAIN_I123-DATSCAN_3_HR_20180207130341_10085 (128x128x39x1)
Conversion required 0.106858 seconds (0.000000 for core code).

These are the geometry parameters according to AFNI's nifti_tool for the dcm2nii made .nii followed by the dcm2niix one:

$ less *nii | egrep '(pixdim|qform|sform|quat|qof|srow|intent)'
  name                offset  nvals  values
  ------------------- ------  -----  ------
  intent_p1             56      1    0.0
  intent_p2             60      1    0.0
  intent_p3             64      1    0.0
  intent_code           68      1    0
  pixdim                76      8    0.0 1.820729 1.820729 3.64146 0.0 1.0 1.0 48294.0
  qform_code           252      1    0
  sform_code           254      1    0
  quatern_b            256      1    0.0
  quatern_c            260      1    0.0
  quatern_d            264      1    0.0
  qoffset_x            268      1    0.0
  qoffset_y            272      1    0.0
  qoffset_z            276      1    0.0
  srow_x               280      4    1.0 0.0 0.0 0.0
  srow_y               296      4    0.0 1.0 0.0 0.0
  srow_z               312      4    0.0 0.0 1.0 0.0
  intent_name          328     16    

$ less dcm2niix/*nii | egrep '(pixdim|qform|sform|quat|qof|srow|intent)'
  intent_p1             56      1    0.0
  intent_p2             60      1    0.0
  intent_p3             64      1    0.0
  intent_code           68      1    0
  pixdim                76      8    1.0 1.820729 1.820729 3.64146 0.0 0.0 0.0 0.0
  qform_code           252      1    1
  sform_code           254      1    1
  quatern_b            256      1    0.0
  quatern_c            260      1    0.0
  quatern_d            264      1    0.0
  qoffset_x            268      1    0.0
  qoffset_y            272      1    -127.0
  qoffset_z            276      1    0.0
  srow_x               280      4    1.0 0.0 0.0 0.0
  srow_y               296      4    0.0 1.0 0.0 -127.0
  srow_z               312      4    0.0 0.0 1.0 0.0
  intent_name          328     16    

I found some private tags which might be enough to make a qform: 
(0011, 1063) [Spatial Offset]                    OB: Array of 24 bytes
(0011, 1064) [Spatial Orientation]               OB: Array of 24 bytes

In this case they are all zeroes and the image does not show any obliquing, so there is not much evidence here to confirm that the tag labels are correct.

Thanks,

Rob

**Comment by neurolabusc** [comment]
Rob -
  Can you test the latest code. I do not have a sample image available. I have seen this in derived Siemens mosaics once upon a time.

**Comment by captainnova** [comment]
Thanks, but it still produces qform_code and sform_code = 1.  It does set them to 0 several times, but near the end it hits 
unsigned char * nii_flipY(unsigned char* bImg, struct nifti_1_header *h) in nii_dicom.cpp, which has the line
setQSForm(h,Q44, true);

At this point Q44 is {m = {{1, 0, 0, 0}, {0, 1, 0, -127}, {0, 0, 1, 0}, {0, 0, 0, 1}}}
and noNaN(Q44) finds no NaNs.

**Comment by neurolabusc** [comment]
Hmm, try the latest code.

**Comment by captainnova** [comment]
Success!  I also tested a 2D FLAIR with a valid sform to make sure it is preserved, and it is.

I had to comment out #define DEBUG_READ_NOT_WRITE, and added a line to COMPILE.md with instructions on building with debugging symbols.  I will try pushing them upstream now.

**Comment by neurolabusc** [comment]
If you send me your COMPILE.md or generate a pull request, I will include it. Thanks for testing this.
