### ISSUE TITLE
Output json gets an 'a' appended as a suffix

### ISSUE THREAD

**Issue by josephmje** [rordenlab/dcm2niix#188]
I'm using dcm2niix v1.0.20180328. 

After running dcm2niix on a single dicom file to generate a json sidecar:
`dcm2niix -b o -s y -f [scan_filename] -o [session_nii_dir] [dcm_file]`

the output json is `[scan_filename]a.json`.

Do you know where the 'a' is coming from?

Thanks,
Michael

**Comment by neurolabusc** [comment]
You will tend to see 'a','b','c' when there are filename conflicts that would cause the software to overwrite images. For example, consider you acquired a T1 scan in Series 3 and a T1 in series 4 and your ran "dcm2niix -f %p ~/indir", in this case you would get "T1.nii", "T1a.nii" as your naming scheme does not distinguish these images. On the other hand, if you ran "dcm2niix -f %p_%s ~/indir", you would get "T1_3.nii" and ""T1_4.nii" as your naming scheme now avoids conflicts. 

I notice you are running with the "bids only" output (-b o). I think if you look in your output folder you will find an image file where the name would conflict (e.g. [`scan_filename].nii`).
