### ISSUE TITLE
How to extract the magnitude and phase images from nifti file?

### ISSUE THREAD

**Issue by wangboc** [rordenlab/dcm2niix#194]
Hi expert, recently I used the dcm2niix to convert my dicoms to nifti. In the output fold, I found two files named _20121108072035_Field_Mapping_601_e2.nii.gz_ and _20121108072035_Field_Mapping_601.nii.gz_. I know that the suffix of e2 is meaning the second echo time. While, when I open that in MRICROGL, a volume picker comes front to me. I guess the first volume is the magnitude image, and the other is phase. Here comes the problem, how can I extract both image ? I cannot see any file name containing 'ph'. And how can I extract the B0 map information ?
Thank you
Bocheng Wang

**Comment by wangboc** [comment]
I wander if the .nii.gz file contains real and image data ? or magnitude and phase data ? Please help

**Comment by neurolabusc** [comment]
Hello, the way that fieldmaps are stored depends on the version of dcm2niix (e.g. v1.0.20180328) you are using, the vendor of your scanner and how the scanner was set up. You may want to try the latest [pre-release version of dcm2niix](https://github.com/rordenlab/dcm2niix/releases) to see if it clarifies the situation. In general, a gradient echo phase map is based on acquiring two images with different echo times, and computing the phase difference between these images. Therefore, you can think of five images: a magnitude image for each TE, a phase image for each TE, and a difference image. Modern versions of dcm2niix should be pretty good about separating out the phase map from the magnitude image (using the "_ph" suffix for phase maps), but its ability to distinguish these will depends on the data included in the DICOM image by the vendor. If dcm2niix fails to distinguish your phase and magnitude image (saving both 3D volumes in a single 4D file) you can use fslsplit and distinguish the phase and magnitude image by visual inspection.

**Comment by wangboc** [comment]
![image](https://user-images.githubusercontent.com/12145052/40755190-de66a5d0-64af-11e8-9558-fc3f4df17f9f.png)
![image](https://user-images.githubusercontent.com/12145052/40755196-e82034f6-64af-11e8-94ec-631304e5f708.png)
there come two volume in my nii file. I cannot distiguish what information in it.  Magnitude or phase? Real or image? 
Below is my json file generated by the newest version of dcm2niix: thank u very much !
{
	"Modality": "MR",
	"MagneticFieldStrength": 3,
	"Manufacturer": "Philips",
	"ManufacturersModelName": "Intera",
	"InstitutionName": "OHSU_MRI3",
	"DeviceSerialNumber": "4sEr9bzYud6E",
	"BodyPartExamined": "BRAIN",
	"PatientPosition": "HFS",
	"SoftwareVersions": "3.2.1_3.2.1.1",
	"MRAcquisitionType": "3D",
	"SeriesDescription": "Field_Mapping",
	"ProtocolName": "Field_Mapping",
	"ScanningSequence": "GR",
	"SequenceVariant": "SP",
	"ScanOptions": "FC",
	"ImageType": ["ORIGINAL", "PRIMARY", "R", "FFE", "R", "FFE"],
	"SeriesNumber": 1001,
	"AcquisitionTime": "08:33:14.430000",
	"AcquisitionNumber": 10,
	"PhilipsRescaleSlope": 2.20073,
	"PhilipsRescaleIntercept": -4506,
	"PhilipsScaleSlope": 0.000126599,
	"UsePhilipsFloatNotDisplayScaling": 1,
	"SliceThickness": 3,
	"SpacingBetweenSlices": 3,
	"SAR": 0.00912379,
	"EchoTime": 0.0023,
	"RepetitionTime": 0.02,
	"FlipAngle": 10,
	"PercentPhaseFOV": 83.3333,
	"EchoTrainLength": 2,
	"PhaseEncodingSteps": 96,
	"AcquisitionMatrixPE": 96,
	"ReconMatrixPE": 256,
	"PixelBandwidth": 1004,
	"ImageOrientationPatientDICOM": [
		1,
		0,
		0,
		0,
		1,
		0	],
	"InPlanePhaseEncodingDirectionDICOM": "COL",
	"ConversionSoftware": "dcm2niix",
	"ConversionSoftwareVersion": "v1.0.20180328 (OpenJPEG build) MSC1900"
}

**Comment by drmclem** [comment]
These look like both real or real and imaginary  images.

Matthew
________________________________

**Comment by neurolabusc** [comment]
I will close this issue, as it appears dcm2niix is converting your images faithfully. You may want to go back to the scanner console and make sure you have set up the MRI system to store phase maps. The BIDS JSON file should report the image type as phase, e.g. `"ImageType": ["ORIGINAL", "PRIMARY", "PHASE", "MAP", "P", "FFE"],`.

**Comment by neurolabusc** [comment]
@wangboc - as @drmclem noted these are your real and imaginary images. 
 - The latest commit of dcm2niix should detect these and append "_real" and "_imaginary" even if your image omits the Complex Image Component tag (0008,9208). Specifically, I use the Image Type tag (0008,008) to detect these. For details, [see Philips Table 3-28](http://incenter.medical.philips.com/doclib/enc/fetch/2000/4504/577242/577256/588723/5144873/5144488/5144982/DICOM_Conformance_Statement_Intera_R7%2c_R8_and_R9.pdf%3fnodeid%3d5147977%26vernum%3d-2). 
 - You can convert your real and imaginary images to magnitude and phase images using fslcomplex, or you can use this [SPM/Matlab script](https://github.com/rordenlab/spmScripts/blob/master/nii_complex2magPhase.m).
 - I have updated my [field mapping web page](http://www.mccauslandcenter.sc.edu/crnl/tools/fieldmap) to help users identify these images.
 - For users of older versions of dcm2niix, you can detect these scans by looking at the BIDS ImageType tag (assuming `"Manufacturer": "Philips"`): The element `"R"` indicates a REAL image, `"I"` indicates a IMAGINARY image, `"M"` indicates a MAGNITUDE image, `"P"` indicates a PHASE image.

**Comment by neurolabusc** [comment]
See the [FSL FUGUE guide](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FUGUE/Guide). Note for `Step 2 - Getting (wrapped) phase in radians` you can either use the complex image created by `fslcomplex -complex realvol imagvol complexvol`  directly or the phase volume you get by following that function with `fslcomplex -realphase complexvol phasevol`.

**Comment by wangboc** [comment]
Using the SPM/Matlab ni_complex2magPhase.m, I have already extract the **magnitude** and **phase** images. Do you mean that I should follow the FUGUE guide to calculate the fieldmap in rad/s？ or to pass my original **Real** and **imaginary** images (from dcm2niix) to _fslcomplex -complex_ command, to get the wrapped/unwrapped phase ?

**Comment by neurolabusc** [comment]
Your choice. See the FSL FUGUE guide for details.

**Comment by alexsayal** [comment]
> Successfully extracted the magnitude and phase images by downloading the newest update, while I wonder how to calculate the phase difference image?

Hi! Have you managed to find out how to build the phase difference image?

**Comment by neurolabusc** [comment]
I would suggest looking at the [FSL Fugue](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FUGUE/Guide#Non-SIEMENS_data) documentation. If you still have questions, you can try [posting a question on the FSL forum](https://www.jiscmail.ac.uk/cgi-bin/webadmin?A0=fsl). @wangboc has not shown any GitHub activity in a while, so unlikely to be monitoring this thread.
