### ISSUE TITLE
dcm2niix.exe: keep the input filename

### ISSUE THREAD

**Issue by Brunnocampos1** [rordenlab/dcm2niix#200]
Hi, is there any way to keep the input filename using the whole folder conversion?
I know that is possible to do that using the single file option, giving the output name, but automatically for several files? (this option is available on the GUI version ("input filename")
Why not a loop? Because of the single file option does not merge multiple files (classical) dicom series automatically.

Thanks!

**Comment by neurolabusc** [comment]
Hello-
 I would suggest you make a fork of dcm2niix and make your own version that does this - you would only need to make a couple edits to nii_dicom_batch.cpp. For example, the code below shows how the `-f %f ` option appends the folder name. Your approach might work nicely for Philips Enhanced DICOM, however I would be worried about including this in the general release, as with classic DICOM thousands of randomly named input filenames contribute to a single output file.

```
            if (f == 'F')
                strcat (outname,opts.indirParent);


```

**Comment by Brunnocampos1** [comment]
Thank you, professor!

**Comment by neurolabusc** [comment]
@Brunnocampos1  can you test the newest source code. It includes the `%b` base DICOM name option `./dcm2niix -f %s_%b ~/DICOMS`. This works well for enhanced DICOM where a while series can is stored in a single file - for classic DICOM (where one series generates a number of files) you will get the base name of the first DICOM. 

There is another new naming parameter `%r` which adds the instance number. Most DICOM series include many instances, but this is useful for the new DICOM renaming and sorting function. `dcm2niix -r y -f %s_%d/%4r.dcm -o ~/sorted ~/unsorted`.
