### ISSUE TITLE
How to cite you?

### ISSUE THREAD

**Issue by katjaq** [rordenlab/dcm2niix#202]
Hi!
We would like to put a first version of our article on bioRxiv and I was wondering how to cite you. Currently, in the methods section I say 
```
The MRI data from the MNHN was converted to Nifti 1 format (Cox et al 2004) using FLS 5.0.10 (Jenkinson et al 2012, https://fsl.fmrib.ox.ac.uk) and dcm2niix (Chris Rorden, version v1.0.20170724, https://www.nitrc.org/projects/mricrogl/).
```

And in the reference list of the article? 

Many thanks for advice :)
best wishes
katja

**Comment by neurolabusc** [comment]
Katja: This is the best reference:

Li X, Morgan PS, Ashburner J, Smith J, Rorden C. (2016) [The first step for neuroimaging data analysis: DICOM to NIfTI conversion](https://www.ncbi.nlm.nih.gov/pubmed/26945974). J Neurosci Methods. 264:47-56.

**Comment by TamerGezici** [comment]
Hi, what is the most recent citation at the moment? @neurolabusc

**Comment by neurolabusc** [comment]
@TamerGezici this remains the best reference:

Li X, Morgan PS, Ashburner J, Smith J, Rorden C. (2016) [The first step for neuroimaging data analysis: DICOM to NIfTI conversion](https://www.ncbi.nlm.nih.gov/pubmed/26945974). J Neurosci Methods. 264:47-56.

**Comment by TamerGezici** [comment]
> @TamerGezici this remains the best reference:
> 
> Li X, Morgan PS, Ashburner J, Smith J, Rorden C. (2016) [The first step for neuroimaging data analysis: DICOM to NIfTI conversion](https://www.ncbi.nlm.nih.gov/pubmed/26945974). J Neurosci Methods. 264:47-56.

Thanks.
