### ISSUE TITLE
dcm2niix with Vida data

### ISSUE THREAD

**Issue by mitchem890** [rordenlab/dcm2niix#203]
Hi, 
I'm using dcm2niix to convert vida data. It seems like the jsons that are produced during the conversion are missing some parameters that I normally use to run preprocessing.
Specifically when looking at the SpinEcho Field Maps json I'm not seeing an EffectiveEchoSpacing
And when looking at Structural images I don't see a DwellTime parameter listed. 
Are these know issues?
Is there a way to calculate these values out of the header files?

Thanks,
Mitch

**Comment by neurolabusc** [comment]
Hello Mitch,

- This is an inherent property Siemens Vida XA10 DICOMs: they no longer include the CSA header
 [CSA header](http://nipy.org/nibabel/dicom/siemens_csa.html).
- Be aware that the Siemens XA10 mosaic data I have seen is missing the slice orientation values. This will impact not only spatial processes (coregistration, normalization, etc) but also make it impossible to infer diffusion gradients (as these are only reported WRT the scanner bore). I reported this issue to Siemens, so hopefully it has been/will be resolved. However with XA10, Siemens has deprecated the mosaic format, and I strongly recommend you do not use it.
- The XA10 format is compact and fast to decode, but it lacks the rich meta-data scientists are used to. It is more similar to Philips enhanced DICOM than previous Siemens DICOM data. You may want to contact your Siemens research collaboration manager and request that they consider adding more information. Also, perhaps Siemens could help describe some of the new private tags e.g. is 0021,1156 equivalent to the old 0051,1011?
