### ISSUE TITLE
Too many NIFTI images with the same name and du

### ISSUE THREAD

**Issue by armaneshaghi** [rordenlab/dcm2niix#211]
I receive the following error when batch converting from a bunch of dicom images to nfiti and the results are individual nfiti files from each slice, rather than being a proper 3D volume. The error looks pretty self explanatory, therefore, I artificially changed the acquisition time and series time with `pydicom` so that when the dicoms are internally sorted this will not clash with others. However, this has not helped. Do you have any suggestions? The dicoms behave well on other programmes, such as `DicomBrowser`. 

Error message
```
Some images have identical time, series, acquisition and image values. DUPLICATES REMOVED.
Error: Too many NIFTI images with the name /tmp/arman/arman_Anonymized_20140425093922_601
```

Thank you.

**Comment by neurolabusc** [comment]
It looks like your file anonymization has stripped out the series, acquisition and image tags that are required to discriminate different images. You have a couple solutions:
 

1. If each series is stored in a different folder, you can process one at a time, e.g. if series 1,2,, and 3 each are stored in separate folders `~/dcm2niix ~/DICOM/s1`, `~/dcm2niix ~/DICOM/s2`, `~/dcm2niix ~/DICOM/s3` will avoid the conflict you would get with `~/dcm2niix ~/DICOM`
2. Apply dcm2niix to data that has not been anonymized, or use a anonymization tool that retains this crucial information. Given that the anonymization has removed these crucial tags, it is likeyl it has removed other important tags that provide sequence details. 
 3. Does DicomBrowser actually discriminate these files, or does it simply not care that they have conflicting information? When we convert to NIfTI, we need to stack images from the same series and keep them separate from other series. This demands different information than a tool that simply shows you the information from each image independently.

**Comment by armaneshaghi** [comment]
Thanks Chris. 

1. Series are in different forlders, but still I get the error. 
2. This is not possible; at least in multi-centre studies I work on.
3- I am not sure, but other tools with the same functionality as dcm2niix work. One example is https://github.com/icometrix/dicom2nifti that worked for me.

**Comment by neurolabusc** [comment]
Thank you for sharing a sample. The core issue is that your anonymization method sets all instance numbers (0020,0013) to 2147483647. Instance number is no more private data than the series or acquisition number. I understand the concerns regarding privacy for multi-center studies, but as @drmclem has noted regarding several previous issues one needs to use extreme caution when applying an anonymization method to your dataset.  Large multi-center studies represent a huge investment of time and resources, and you want to ensure your data is of archival quality. While I have included a kludge to deal with your particular issue, your anonymized data is likely to disrupt many other tools and future archival work based on your dataset. I urge you to fix the anonymization tool. 

As an aside, the sample you provided me the data is from a Philips system generating classic DICOM. You will want to be particularly vigilant if this system ever generates enhanced DICOM, as that includes features that did not exist when most anonymization tools were developed.

My kludge takes advantage of the fact that classic DICOM does not use Dimension Index Values (0020,9157). When 0020,9157 is not populated, I use now use the acquisition time to discriminate scans acquired at least 1ms apart.

**Comment by armaneshaghi** [comment]
Thank you. I close this issue.

**Comment by neurolabusc** [comment]
For those interested in the topic, there are many free DICOM anonymizers available. However, I suggest carefully validating them on your datasets to ensure they work as expected. I would recommend users investigate [gdcmanon](http://gdcm.sourceforge.net/html/gdcmanon.html). Note that this tool can be optionally used to store private data in an encrypted form (providing a reversible method to audit private information), or it can completely remove the private data. 

When de-identifying data, one should also carefully consider whether the date and time stamps are [protected health information](https://www.hhs.gov/hipaa/for-professionals/privacy/special-topics/de-identification/index.html#testmeasures). Therefore, the anonymization method described above incorrectly anonymized the instance numbers which are not identifiable (they are repeated for every acquisition and are in no way unique), while it preserved the acquisition time that in some domains would be considered protected health information. 

If one does remove date/time information, make sure it does not compromise other measures. For example, users of Siemens scanners often acquire respiration and pulse data in the Siemens RESP/PULS format, and these need to be synchronized with the DICOM data.

The potential of open science and multi-center trials is huge. However, one needs to carefully curate these datasets.
