### ISSUE TITLE
niis not being made for nonEPI GE series

### ISSUE THREAD

**Issue by captainnova** [rordenlab/dcm2niix#222]
The latest beta (20180826) has several changes to handle more-research-lab-type features of GE datasets, but unfortunately fails my test suite on older and more nearly clinical nonEPI GE scans.

The symptoms look like:
dcm2niix -o . /mnt/mrimages/test_image_data/dicom_to_nii/T2st/ge/dicom/
Chris Rorden's dcm2niiX version v1.0.20180826 BETA  (JP2:OpenJPEG) GCC4.4.7 (64-bit Linux)
Found 36 DICOM file(s)
No valid DICOM images were found

and (thanks to some help from Chris Rorden) appear to stem from line 5204 of console/nii_dicom.cpp:

      				int check =dcmInt(2,(unsigned char*)hdr + epi_chk_off,true) & 0x800;
     				if (check == 0) {
						if (isVerboseX > 1) printMessage("%s: Warning: Data is not EPI\n", fname);
					 	continue;

      				}

The continue makes dcm2niix skip the rest of each slice once it hits 0043,102A for nonEPI data, so it never hits kImageStart (7FE0, 0010). Replacing the continue with a break appears to fix the problem (it passes my test suite again, and explains why dcm2niix was failing for most GE scans but working for dMRI and fMRI).

I will try setting up a pull request and providing phantom data next, but it boils down to a typo fix.

**Comment by neurolabusc** [comment]
@captainnova - I have applied your patch. I have applied one other patch to fix another regression that has occurred with respect to the last stable version. The challenge I have is understanding how many slices will be in the final volume when different GE tags provide conflicting numbers. My current solution is below, but I am still not convinced this is the perfect solution. If you have issues with the current version please see if we can tweak these conditionals:

```
    	//printMessage("Check number of slices, discrepancy between tags (0054,0081; 0020,1002; 0021,104F)\n");
    	if (d.locationsInAcquisition < locationsInAcquisitionGE) d.locationsInAcquisition = locationsInAcquisitionGE;


```
