### ISSUE TITLE
Exporting of multiple DICOM fields in bids sidechar

### ISSUE THREAD

**Issue by takhs91** [rordenlab/dcm2niix#224]
Hi,
I am interested in exporting some extra dicom fields to the BIDS json file such as
Patient Birth Day, Accession Number, StudyDate, StudyTime. I would kindly request to simply add them if possible but because I might need more in the future and I prefer a more future proof solution than asking every time for extra fields I came up with two proposals.

The addition of a `-ba a` all options which exports all the common dicom tags across a Series in the bids after any appropriate transformation to json
The addition of a ‘-add-tags [dicom_tag1, dicom_tag2 ...]’ or similar option which lets you pick the additional tags you are interested in exporting to bids if found similar across a Series

What are your thoughts?

**Comment by neurolabusc** [comment]
dcm2niix currently has a function to switch off BIDS anonymization: `-ba n` If this is switched the additional tags are added to the BIDS output

```
SeriesInstanceUID
StudyInstanceUID
ReferringPhysicianName
StudyID
PatientName
PatientID
PatientSex
PatientWeight
```

@chrisfilo has the final decision on any BIDS related issues for dcm2niix. However, I do worry that adding all the tags will make an unwieldy BIDS file, make make harmonization with future BIDS definitions challenging, and will depend on accurate conversion of many private tags where the VR is not known for implicit data. This latter point would require a constantly updated dictionary that would have dramatic performance impact on dcm2niix. 

You can always make a fork of dcm2niix adds any features you wish. If you want to merge your new version into the main branch you can generate a pull request and @chrisfilo can decide if it should become a standard output.

Alternatively, my own sense is you may want to use dcmdump to save a text form of the DICOM header for one example DICOM image in each series. You could evaluate this.

In general I would suggest keeping your raw DICOM data for archival purposes (using proper protocols to protect confidential information) and use the BIDS format for the anonymized, share-able data that is quick to parse and less vulnerable to data breaches.

**Comment by neurolabusc** [comment]
takhs91 I am going to close this issue. This feature request seems to fall outside the remit of dcm2niix which is to convert DICOM images into NIfTI/BIDS compliant datasets. I can think of two reasonable strategies:

1. Develop an independent tool that adds desired DICOM tags into your BIDS files. You could harness pyDICOM, dcmdump, etc.
2. If you want to look at Matlab, I think [dicm2nii](https://github.com/xiangruili/dicm2nii) already has almost precisely what you want. When it converts a DICOM to NIfTI it generates a Mat file with the representative DICOM tags. You could either look at that Mat file directly or inject the DICOM tags into your BIDS file.

**Comment by ihnorton** [comment]
FWIW, @filip-szczepankiewicz and I were also hoping for extended export functionality.  Ideally we would like to be able to give users a config file, which they could pass as an argument to dcm2niix. The config file would specify a set of extra tags (+VR if needed for private tags); the resulting JSON file would not be BIDS-compliant, of course, so I guess it would need to be a separate sidecar. Right now it looks like our best option is either writing something ourselves, or using [dcm2json](https://support.dcmtk.org/docs/dcm2json.html) from DCMTK, with another tool+step to filter (dcm2json it dumps *everything* to [Official  DICOM JSON Format 🕴](https://www.dicomstandard.org/dicomweb/dicom-json-format/)).

Was going to open a similar issue until I found this one, and figured I would voice support here in case you reconsider in the future.

**Comment by chrisfilo** [comment]
To clarify - BIDS does not prevent users from adding additional custom field to JSON sidecars as long as they have names that do not clash with existing names defined in the specification.
