### ISSUE TITLE
what is the meaning of '_c2' tail of the converted file?

### ISSUE THREAD

**Issue by BigEricZ** [rordenlab/dcm2niix#230]
I found some possible filename tail like '_c2', '_ph', '_e'. Some are easy to understand (phase, echo), while some not (eg. '_c2'). Can you provide some documentation for these filename tails. I briefly searched the wiki on NITRC, and didn't find what I am looking for. Maybe I searched the wrong place? 
Thank you in advance.

**Comment by neurolabusc** [comment]
The file naming scheme is described [here](https://raw.githubusercontent.com/rordenlab/dcm2niix/master/FILENAMING.md). I have also added a link to the [wiki](https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#File_Naming). As an aside, the [head coil channel detection](https://github.com/rordenlab/dcm2niix/issues/187) has become more refined with recent releases, so please check that you are using the latest stable version.

**Comment by BigEricZ** [comment]
Thank you very much for the info.
