### ISSUE TITLE
Mistaking a localizer image for DTI 

### ISSUE THREAD

**Issue by jeffyager** [rordenlab/dcm2niix#231]
We've noticed a difference between the version 1.0.20180622 of dcm2niix and older versions on some data.  It seems to mistake this localizer for a diffusion image.

```
[scitran/dcm2niix]  running...
[scitran/dcm2niix]  Unzipping /flywheel/v0/input/dcm2niix_input/4784_1_1_loc.dcm.zip
Chris Rorden's dcm2niiX version v1.0.20180622 (JP2:OpenJPEG) GCC4.8.4 (64-bit Linux)
Found 14 DICOM file(s)
Warning: This diffusion series does not have a B0 (reference) volume
Note: this appears to be a b=0+trace DWI; ADC/trace removal has been disabled.
Warning: GE DTI only tested for axial acquisitions (solution: use Xiangrui Li's dicm2nii)
Saving 1 DTI gradients. GE Reorienting 3Plane_Loc_SSFSE : please validate. isCol=0 sliceDir=1 flp=1 1 0
 reorienting for ROW phase-encoding untested.
Convert 14 DICOM as /flywheel/v0/output/4784_1_1_localizer (256x256x14x1)
compress: "/usr/bin/pigz" -n -f -6 "/flywheel/v0/output/4784_1_1_localizer.nii"
Conversion required 0.074407 seconds (0.021171 for core code).
[scitran/dcm2niix]  Generating metadata from BIDS Sidecar
INFO:metadata:  job start: 2018-08-06 21:28:58.894309
INFO:metadata:  job stop: 2018-08-06 21:28:58.896407
INFO:metadata:  generated /flywheel/v0/output/.metadata.json
[scitran/dcm2niix]  Success!
```

This localizer is just an example image of what we're seeing with multiple image datasets, including some T1 MPRAGE, etc.  
[4784_1_1_loc.dcm.zip](https://github.com/rordenlab/dcm2niix/files/2411305/4784_1_1_loc.dcm.zip)

**Comment by neurolabusc** [comment]
The issue is with your scanner, not my software. Specifically, group/element [0043,1039](https://www.na-mic.org/wiki/NAMIC_Wiki:DTI:DICOM_for_DWI_and_DTI#Private_vendor:_GE) reports a B-value of 2000, even though no gradient vectors are provided. As I do not have GE hardware, I can not resolve this for you. I suggest you contact your GE Research Collaboration Manager and ask them to resolve this. In the mean time, I have uploaded a small patch that will not generate BVec/BVal files if all the images in the set have positive B-values with zero vector length. 

I also do not know how to discriminate this type of localizer from a traditional MRI scan. If you or your contacts at GE know how to do this, we could allow the `-i y` option to skip these files. At the moment, they look like legitimate co-planar MRI slices. 

Personally, I never export my localizers off the scanner - they are just used for planning.

**Comment by jeffyager** [comment]
Thanks for the response. It's good to know that you're looking at (0043,1039), and I confirmed that the  T1 image I have also reports a b-value of 2000 for some reason, so I'm assuming that's the issue with all the data I have. (I have data from multiples scanners at different institutions.) This one in particular is from a GE750 running DV22 software.  Thanks for the patch!

**Comment by fedorov** [comment]
Just for the reference, we observe a similar issue in a T2 prostate scan acquired on Philips Ingenia. This is by no means a DWI scan! This scan is from a public dataset, so investigating this with a vendor is not an option. 

![image](https://user-images.githubusercontent.com/313942/230629312-688f4431-4168-41ec-9cae-a21dab16b6cd.png)
![image](https://user-images.githubusercontent.com/313942/230629328-4c5ffb15-5bce-4d87-8c68-06beefa88687.png)

The image sample is here (you can use "Tag viewer" button to examine the header): https://viewer.imaging.datacommons.cancer.gov/viewer/1.3.6.1.4.1.14519.5.2.1.73817330564297277045402819763812121589?seriesInstanceUID=1.3.6.1.4.1.14519.5.2.1.243716140659674087806014851424171910099. If you want to download the actual files, you can follow the instructions here https://learn.canceridc.dev/data/downloading-data to select and download files corresponding to `SeriesInstanceUID` 1.3.6.1.4.1.14519.5.2.1.243716140659674087806014851424171910099 from [Imaging Data Commons](https://portal.imaging.datacommons.cancer.gov/explore/).

Kudos to @deepakri201 for investigating this and connecting with this issue!

**Comment by ccosmin97** [comment]
To add to the comment above, please find the google colab notebook [here](https://colab.research.google.com/drive/1CuAy2spA2AaG5EjFh7CFKWYYX--vMd5V?usp=sharing) to reproduce downloading the referenced image and convert it using dcm2niix version v1.0.20220505.

**Comment by neurolabusc** [comment]
@fedorov and @ccosmin97 as you note, this dataset **does** report a [Diffusion b-value (0018,9087)](https://dicom.innolitics.com/ciods/enhanced-mr-image/enhanced-mr-image-multi-frame-functional-groups/52009229/00189117/00189087). For Philips MR, a positive b-value without a b-vector (0018,9089) is used to signify a non-directional DWI image, for example a TRACE image. 

```
(0018,9087) FD 7.23e+75  # 8,1 Diffusion b-value
```
In general, dcm2niix assumes that DICOM images are truthful. I agree the reported value is implausible, but one worries about unintended consequences of merely disregarding information explicitly reported by the DICOM.


As an aside, dcm2niix will ignore the b-matrix (0018,9602..9607) as the tools like FSL's [Eddy](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/eddy) needs to know the distinguish vectors of opposite polarities (e.g. the opposite b-vectors [-1 0 0] and [1 0 0] generate identical b-matrices).
