### ISSUE TITLE
Gantry tilt error 

### ISSUE THREAD

**Issue by muschellij2** [rordenlab/dcm2niix#232]
## Description of the problem

When running with`-m y`, gantry tilt correction may not work if the stacks have < 3 slices.  

## Steps to Reproduce

From this data: [Routine_Head_093502.zip](https://github.com/rordenlab/dcm2niix/files/2412878/Routine_Head_093502.zip)
```bash
dcm2niix -9  -m y -z y -f %p_%t_%s ./
```
I got the following error/warning:
```
Only able to correct gantry tilt for 16-bit integer data with at least 3 slices.Only able to make equidistant slices from 3D 8,16,24-bit volumes with at least 3 slices.
```

## dcm2niix version
```
dcm2niix
```
```
Chris Rorden's dcm2niiX version v1.0.20171017 (OpenJPEG build) Clang7.3.0 (64-bit MacOS)
```

Same thing while using version `v1.0.20180404`:

```bash
dcm2niix -m y ./
Chris Rorden's dcm2niiX version v1.0.20180404 Clang9.0.0 (64-bit MacOS)
Found 48 DICOM image(s)
slices stacked despite varying acquisition numbers (if this is not desired please recompile)
 Warning: note these images have gantry tilt of 13.5 degrees (manufacturer ID = 2)
```

Same with today's version:
```
macbook-pro-6:Routine_Head_093502 johnmuschelli$ dcm2niix -m y ./
Chris Rorden's dcm2niiX version v1.0.20180918  (JP2:OpenJPEG) Clang9.0.0 (64-bit MacOS)
Found 48 DICOM file(s)
 Warning: note these images have gantry tilt of 13.5 degrees (manufacturer ID = 2)
Dims 512 512 48 1 1
Warning: Interslice distance varies in this volume (incompatible with NIfTI format).
 Distance from first slice:
dx=[0 2.49996 4.99992 7.49989 9.99985 12.4998 14.9998 17.4997 20.0017 22.5016 25.0016 27.5015 30.0015 32.5015 35.0014 37.5014 40.0033 42.5033 45.0032 47.5032 50.0032 52.5031 55.0031 57.503 60.005 62.5049 65.0049 67.5048 70.0048 72.5048 75.0047 77.5047 77.5465 82.5464 87.5463 92.5463 97.5482 102.548 107.548 112.548 117.55 122.55 127.55 132.55 137.551 142.551 147.551 152.551]
Convert 48 DICOM as ./Routine_Head_19971212093303_2b (512x512x48x1)
compress: "/usr/local/bin/pigz" -n -f -6 "./Routine_Head_19971212093303_2b.nii"
Only able to correct gantry tilt for 16-bit integer data with at least 3 slices.Only able to make equidistant slices from 3D 8,16,24-bit volumes with at least 3 slices.
```

**Comment by muschellij2** [comment]
Looks like a "successful" conversion - no warnings, but obviously an odd scan as the changes in slice thickness and tilt.  The version is still `v1.0.20180918` for the time being, correct?  Also, will this be a tagged commit (therefore potentially released?).

**Comment by muschellij2** [comment]
Also, just alerting @jonclayden to the update.

**Comment by jonclayden** [comment]
Noted, thanks. Very recent improvements to `dcm2niix` like this should appear in the next non-patch release of `divest`.

**Comment by neurolabusc** [comment]
New version number along with stable release will appear when [163](https://github.com/rordenlab/dcm2niix/issues/163) and [225](https://github.com/rordenlab/dcm2niix/issues/225) are closed. After the next stable release, active development will move to a separate development branch.
