### ISSUE TITLE
dcm2niix with resting-state multiband data

### ISSUE THREAD

**Issue by mm4355** [rordenlab/dcm2niix#233]
I want to convert dicom MUX 6 to .nii.gz

I attached a picture on the problem when using dcm2niix, It seams dcm2niix needs a guide on how to read the headers... not sure if I am doing it correctly. Please advice on how to use dcm2niix with multiband resting data.

Thanks
![dicom2niix - error](https://user-images.githubusercontent.com/43613600/46090096-f462f980-c17d-11e8-87a1-f1b1538040f9.png)

**Comment by neurolabusc** [comment]
This appears to be a replication of [issue 220](https://github.com/rordenlab/dcm2niix/issues/220). I assume these are DICOM images from a GE scanner running the older WIP rather than the recent GE product `hyperband` sequence. With the WIP package the recon is not computed on-line. 

We do not have GE hardware at my center, but Gareth Barker at King's College London described this to me as:

> The WIP saves the raw (k-space) data (as a GE proprietary "Pfile") for later offline reconstruction, but also does a (non-multiband aware) online recon which will created the aliased images you're seeing.  The online recon images are really only intended to a) allow the user to check something is actually running and b) provide a full, GE standard, DICOM header that can then be used during the offline recon.  (The offline recon (at least in the form I've seen it) takes a single DIOCM image from the online recon, plus the raw data, as inputs).  This means that: a) I don't think there is any way to recover the full dataset from these aliased images alone, unfortunately, on the console or otherwise and b) even if the user can find and reconstruct the original raw data, the
> DICOM headers should be treated with a degree of caution.  (The offline recon correctly updates things to ensure unique UIDs, etc, but I'm not sure every tag necessarily gets correctly updated to allow for the 3-fold increase in slice numbers.
> 

If I am correct, you will need to [reconstruct from your P files](https://cni.stanford.edu/wiki/MUX_EPI).

**Comment by mm4355** [comment]
Thanks for your response. 
Yes, these are DICOM images from a GE scanner but we are running the recent GE product hyperband sequence. Please advice on how or what to do.

**Comment by mm4355** [comment]
Attachment available until Oct 27, 2018
I want to share this dataset with you, please find attached 1 resting-state fMRI run from a test subject.

Thanks for your help.

Click to Download
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAS71ZY-bGujz0NBkMK-2JlMoa-Q_AWdrJVKJ1mwcvXfvMYESQjRALK0z%2F%24%7Bf%7D%3Fo%3DAn5LTgNz4C17OXCWV3u6qvR3j6-Fl6YRPVviFqlZzURn%26v%3D1%26x%3D3%26a%3DB8aPFhW6utfRaGAsM56HIl6-_XFKA2nJRgEACAHIAP84Z-MsA6kgRg%26e%3D1540648814%26k%3D%24%7Buk%7D%26fl%3D%26r%3DEDDAF24E-1423-402A-909A-5A81529DFCB8-1%26ckc%3Dcom.apple.largeattachment%26ckz%3D92459E3B-D997-4FEF-B828-EAE0127F506F%26p%3D16%26s%3DDOBykxVV5RL4v5am_O-e-1L8cSo&uk=BPgYhx2E8pHR7losgNXivA&f=s000009.zip&sz=336614837>s000009.zip
336.6 MB

*******************************************
Leah Moreno, PhD
Research Scientist
Division of Experimental Therapeutics
Department of Psychiatry
Columbia University Medical Center
1051 Riverside Drive, Unit 21
New York, NY 10032
phone: (914) 218-7311
email: mm4355@cumc.columbia.edu <mailto:mm4355@cumc.columbia.edu>

**Comment by neurolabusc** [comment]
I can not replicate your issue. These files seem to convert well with dcm2niix  v1.0.20180918 and displayed using MRIcroGL, FSLeyes, FSLview, etc. Can you check the version of dcm2niix you are using and also using one of the display tools I used. For Linux and Mac, you can build the latest code from the script below. For Windows computers you can click on the green "AppVeyor" icon on the dcm2niix Github home page, then click the "artifacts" button to get a compiled copy of the most recent commit.

```
$ git clone https://github.com/rordenlab/dcm2niix.git
$ cd dcm2niix/console
$ make
$ ./dcm2niix
Chris Rorden's dcm2niiX version v1.0.20180918  GCC6.1.0 (64-bit MacOS)
...


```
![test](https://user-images.githubusercontent.com/8930807/46153757-c5ae5700-c241-11e8-93f7-3e021e1a14cb.jpg)

**Comment by mm4355** [comment]
Attachment available until Oct 27, 2018
I was expecting an image like the attached, I can not see full brain in the parasagittal or coronal view, I am now using the script you sent for Mac.

Here I have attached a .nii file converted from p-files using the old multi band from GE. So was expecting the same output when converting DICOMS to nii using the hyperband sequence. Am I wrong?

Thanks a lot.

Click to Download
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FASR-DkoQFs3AVh5stDmG_8VSM4vAASTj8On_lCorxSOUMPxH6-EyYPYK%2F%24%7Bf%7D%3Fo%3DAvqHmNvgq8FJ_r42hfF3Zl0rSwdAxzutMS_0ibcqnKSu%26v%3D1%26x%3D3%26a%3DB3X4HMjLY2j76X5a6eB0LZJE3zxxA83JRgEACAHIAP9uuPK6Aw0hRg%26e%3D1540654816%26k%3D%24%7Buk%7D%26fl%3D%26r%3D5EE0BC18-D62C-4B72-A4C3-16C1F4F30510-1%26ckc%3Dcom.apple.largeattachment%26ckz%3D92459E3B-D997-4FEF-B828-EAE0127F506F%26p%3D16%26s%3DHsPNm-8B5GoEjyqRuyEMW2HdyNk&uk=h_ypPmetXPH3r9Z_L5fnNw&f=E15386_S11_mux6_arc1.nii.gz&sz=1519851386>E15386_S11_mux6_arc1.nii.gz
1.52 GB

*******************************************
Leah Moreno, PhD
Research Scientist
Division of Experimental Therapeutics
Department of Psychiatry
Columbia University Medical Center
1051 Riverside Drive, Unit 21
New York, NY 10032
phone: (914) 218-7311
email: mm4355@cumc.columbia.edu <mailto:mm4355@cumc.columbia.edu>

**Comment by mm4355** [comment]
using wb_view compare both images, the full brain one is converted from p-files using the old GE multiband sequence, the other one is converted from DICOM using the hyperband GE sequence with dcm2niix.


*******************************************
Leah Moreno, PhD
Research Scientist
Division of Experimental Therapeutics
Department of Psychiatry
Columbia University Medical Center
1051 Riverside Drive, Unit 21
New York, NY 10032
phone: (914) 218-7311
email: mm4355@cumc.columbia.edu

**Comment by neurolabusc** [comment]
dcm2niix faithfully converted the DICOM images it was provided.
