### ISSUE TITLE
Changing default output format

### ISSUE THREAD

**Issue by lrq3000** [rordenlab/dcm2niix#242]
Hey there,

The default output format for the filename is not very informative when using the GUI in MRIcroGL. Indeed, it's for example missing the sequence name.

For example, this is what I am using (which also allows to store all files in a "nifti" folder):
```
nifti/%t_%p_%s_%d_%z
```

**Comment by lrq3000** [comment]
Additionally, these options are not shown anywhere in the GUI, one needs to run in commandline ```dcm2niix --help```

**Comment by neurolabusc** [comment]
This is a comment regarding the behavior of MRIcroGL, not dcm2niix. If you want to see this addressed file a [Github MRIcroGL Issue](https://github.com/neurolabusc/MRIcroGL/issues). A couple comments:
 

- When you run the MRIcroGL Import/ConvertDICOMtoNifti menu item for the first time it should have the output filename '%f_%p_%t_%s' - this will include the input folder name, protocol name, time and series number in the output. These seems pretty informative to me. However, it is fully editable.
 - Note that a tooltip appears that shows the options (see image below).
 - Note that as you change the output filename you see the changes dynamically with an example filename below, e.g. "myFolder_MPRAGE...", so as you edit the filename you get a sense of what it will look like. While you might like having both the protocol name and sequence name, be aware that is vendor specific - some systems do not distinguish between these, so sequence name and protocol name are the same. While that may be good for your situation, I am not sure it is a terrific default for users with other systems. Note it remembers your personal settings, so if you change these preferences it will be retained the next time you run the software. What is intuitive for you on your system might not be an ideal default.

![dcm2niix_import](https://user-images.githubusercontent.com/8930807/47726121-1802df00-dc17-11e8-82d3-ed7f6a0274e5.png)

**Comment by lrq3000** [comment]
Ok thank you for the details, but I will clarify (and open a ticket there):

* For the tooltip, I am aware, but compare this:
![dcm2niixtooltip](https://user-images.githubusercontent.com/1118942/47728014-cc275880-dc5d-11e8-9960-b034f2afd1d0.png)
with this (from commandline):
```  -f : filename (%a=antenna  (coil) number, %b=basename, %c=comments, %d=description, %e=echo number, %f=folder name, %i=ID of patient, %j=seriesInstanceUID, %k=studyInstanceUID, %m=manufacturer, %n=name of patient, %p=protocol, %r=instance number, %s=series number, %t=time, %u=acquisition number, %v=vendor, %x=study ID; %z=sequence name; default '%t_%p_%s')```
My suggestion is simply to either make the tooltip longer or add this info in the default message in the console.

* The default formatting on my 2 computers and another computer of my colleague is this one: ```%t_%p_%s```, there's no %f. But I mistakenly suggested that the sequence name was missing, when I meant sequence description in fact (%d). I suggest to add this and that it should be useful to almost everyone, because this is apparently the only way to disambiguate some sequences, particularly variants of the same sequence that can be generated by the machine in a dual stream (eg, with and without bias or motion correction). A concrete example are MoCoSeries of bold sequences on Siemens machines: without %d, you get 2 bold sequences without any way to tell them apart. Adding the %d allows to show "MoCoSeries".

* Thank you for the tip, I did not notice that the example was changing dynamically!

**Comment by lrq3000** [comment]
Wait I'm going to confirm if it's %d or %z which allows to disambiguate...

**Comment by lrq3000** [comment]
I confirm it's indeed %d which allows disambiguation, but in other cases it just repeats %p.

Here is a comparison and a new proposition of default (the last one):
```
%t_%p_%s_%d_%z: 20140519131916_ep2d_bold_repos_7_MoCoSeries__epfid2d1_64.nii
%t_%p_%s: 20140519131916_ep2d_bold_repos_7.nii
%f_%p_%t_%s: DICOM_ep2d_bold_repos_20140519131916_7.nii
%n_%t_%p_%d_%z_%s: NAME_20140519131916_ep2d_bold_repos_MoCoSeries__epfid2d1_64_7.nii
```
