### ISSUE TITLE
Interslice distance varies in this volume

### ISSUE THREAD

**Issue by RiqiangGao** [rordenlab/dcm2niix#248]
I am trying to convert dicom to nifti, but I get this error:

```
Warning: Interslice distance varies in this volume (incompatible with NIfTI format).
 Distance from first slice:
dx=[0 1.59998 3.20105 4.80103 6.40002 8 9.59998 11.201 12.801 14.4 16 17.6 19.201 20.801 22.4 24 25.6 27.201 28.801 211.201 212.801 214.4 216 217.6 219.201 220.801 222.4 224 225.6 227.201 228.801 230.4 232 233.6 235.201 236.801 238.4]
```

Do you know the best way to fix this? It seems like the slice distance is slightly off (i.e. 0 1.599 3.201 vs 0 1.6 3.2). Is there an option that thresholds this or maybe I can specify the slice distance is 1.6? 

Thanks,

-Riqiang

**Comment by jstutters** [comment]
It looks like you have a large discontinuity in your slice distances ("27.201 28.801 211.201 212.801") are you certain there are no slices missing?

**Comment by neurolabusc** [comment]
As @jstuffers notes, it is the 182.4mm gap between the slice that is 28.8mm fro the 1st and the one that is 211.2mm away. dcm2niix does have a tolerance for small variation. However, the NIfTI format requires that all slices in a volume are equidistant. I suspect this sequence was acquired with 150 slices, but only 37 are provided to dcm2niix.

**Comment by RiqiangGao** [comment]
If I zip the dicoms can I ship them to you to take a look? There are 209 dicoms and they should all be a single scan. They open fine in mipav in the correct order, but maybe mipav makes some assumption about slice ordering or something.

**Comment by neurolabusc** [comment]
@RiqiangGao - note the message that mentions `slices not stacked: X-Ray Exposure varies (exposure 112, 60; number 1, 1). Use 'merge 2D slices' option to force stacking` - this suggests that you can create a single volume by using the `-m y` option (albeit the single volume will be composed of slices that vary in their X-Ray Exposure). Some teams prefer to analyze these separately, while others prefer to combine them. This is discussed in issues [48](https://github.com/rordenlab/dcm2niix/pull/48) and [91](https://github.com/rordenlab/dcm2niix/issues/91).

```
$ dcm2niix ~/tst
Chris Rorden's dcm2niiX version v1.0.20181125  GCC6.1.0 (64-bit MacOS)
Found 210 DICOM file(s)
slices not stacked: X-Ray Exposure varies (exposure 112, 60; number 1, 1). Use 'merge 2D slices' option to force stacking
Convert 18 DICOM as /Users/rorden/tst/zap/zap_CHEST_20180124085637_5_e1 (512x512x18x1)
...
Warning: Interslice distance varies in this volume (incompatible with NIfTI format).
...
$ dcm2niix -m y ~/tst
Chris Rorden's dcm2niiX version v1.0.20181125  GCC6.1.0 (64-bit MacOS)
Found 210 DICOM file(s)
Convert 210 DICOM as /Users/rorden/tst/zap/zap_CHEST_20180124085637_5a (512x512x210x1)
...
```

**Comment by RiqiangGao** [comment]
> @RiqiangGao - note the message that mentions `slices not stacked: X-Ray Exposure varies (exposure 112, 60; number 1, 1). Use 'merge 2D slices' option to force stacking` - this suggests that you can create a single volume by using the `-m y` option (albeit the single volume will be composed of slices that vary in their X-Ray Exposure). Some teams prefer to analyze these separately, while others prefer to combine them. This is discussed in issues [48](https://github.com/rordenlab/dcm2niix/pull/48) and [91](https://github.com/rordenlab/dcm2niix/issues/91).
> 
> ```
> $ dcm2niix ~/tst
> Chris Rorden's dcm2niiX version v1.0.20181125  GCC6.1.0 (64-bit MacOS)
> Found 210 DICOM file(s)
> slices not stacked: X-Ray Exposure varies (exposure 112, 60; number 1, 1). Use 'merge 2D slices' option to force stacking
> Convert 18 DICOM as /Users/rorden/tst/zap/zap_CHEST_20180124085637_5_e1 (512x512x18x1)
> ...
> Warning: Interslice distance varies in this volume (incompatible with NIfTI format).
> ...
> $ dcm2niix -m y ~/tst
> Chris Rorden's dcm2niiX version v1.0.20181125  GCC6.1.0 (64-bit MacOS)
> Found 210 DICOM file(s)
> Convert 210 DICOM as /Users/rorden/tst/zap/zap_CHEST_20180124085637_5a (512x512x210x1)
> ...
> ```

Thanks so much! It solves my problem.
