### ISSUE TITLE
Warning: only processing last of XXX input files (recompile with 'myEnableMultipleInputs' to recursively process multiple files)

### ISSUE THREAD

**Issue by seralouk** [rordenlab/dcm2niix#254]
Dear all,

I am trying to run "dcm2niix" command on a linux server.
I am in a directory where I have multiple folders, each representing a subject.

When I run the command, I get the following warning and only the data of 1 subjects are converted:

Warning: only processing last of 48 input files (recompile with 'myEnableMultipleInputs' to recursively process multiple files)

Any idea how to convert all the folders that are inside the directory where I run the command ?

**Comment by neurolabusc** [comment]
You have a few options:
1. Pass a parent folder that contains data from each participant. For example, if you have data from participant 1 in `/studyA/s1` and data from participant 2 in` /studyA/s2`, you could run `dcm2niix /study` and it will process data from both participants. For this approach, you will just want to make sure your [filenaming](https://github.com/rordenlab/dcm2niix/blob/master/FILENAMING.md) disambiguates the converted images. For example `-f %t/%s_%p` will create a separate folder for each study time (and within the folder segment based on series and protocol number). If you do not create unique file names, data from one person will overwrite data from the next.
2. You can simply write a batch script (bash, Matlab, Python) to call dcm2niix once per folder, e.g. `dcm2niix /studyA/s1`, `dcm2niix /studyA/s2`,...
3. You could run [dcm2niixbatch](https://github.com/rordenlab/dcm2niix/blob/master/BATCH.md).
4. You could follow the directions and compile your own version that will accept multiple input folders.

**Comment by seralouk** [comment]
In case 1, where I pass the main directory that contains all the subjects folders, the convertion will happen inside each subject's directory right? Not in the main directory (i.e. input directory to the function).

Thank you for the fast and useful response.

**Comment by neurolabusc** [comment]
You usually specify the output directory with the `-o` option, if you do not specify an output directory it will use the input folder, so if you choose `dcm2niix /studyA/` and the DICOMs are in `/studyA/s2` and `/studyA/s1` all the NIfTI images will be written to `dcm2niix /studyA/`. The reason for this is that data for a single series is often written into multiple folders. That is why I suggested you provide a folder structure in your file naming scheme, e.g. `-f %t/%s_%p` will create a separate folder for every study, with the folder name based on the time of study (from DICOM tags 0008,0020 and 0008,0030). See the [filenaming](https://github.com/rordenlab/dcm2niix/blob/master/FILENAMING.md) for more details.

**Comment by seralouk** [comment]
Thank you again. I finally decided to go with option 2. I will call dcm2niix through matlab for each folder separately.
