### ISSUE TITLE
Incorrect origin for tilt-corrected NIfTI images

### ISSUE THREAD

**Issue by alund** [rordenlab/dcm2niix#259]
When a DICOM has a negative gantry tilt angle, the image origin in the NIfTI header of the tilt-corrected output of `dcm2niix` is incorrect.

Without tilt (or tilt correction), the DICOM origin is the inferior anterior right corner of the image. The NIfTI origin is the inferior posterior left corner.

![notilt](https://user-images.githubusercontent.com/68935/51848798-e10a9b00-22e3-11e9-93bb-cc50ff02a9d0.png)

With positive tilt, the padding introduced by the `dcm2niix` tilt correction is on the anterior side of the most inferior slice, so the NIfTI origin is unchanged by the padding. (Although, as we will see below, this is not entirely true.)

![positivetilt](https://user-images.githubusercontent.com/68935/51848883-1d3dfb80-22e4-11e9-87c4-6fe65b941d09.png)

With negative tilt, however, the padding introduced by the tilt correction is on the posterior side of the most inferior slice, so the origin of the image should be adjusted to reflect the padding.

![negativetilt](https://user-images.githubusercontent.com/68935/51848922-38107000-22e4-11e9-8520-5d27712fdabc.png)

As far as I can tell, both from the output and from looking at the code, this is not happening.

I do not have any DICOM series that have negative tilt angles as provided, but I wrote a small Python script that introduces tilt to an existing (untilted) DICOM series by removing voxels and making corresponding adjustments to the position of each slice. Using `dcm2niix` to convert these back to NIfTI, I expect the origin to be the same as what I would get from converting the original DICOM series to NIfTI. Instead, the origin is shifted to the anterior, reflecting the position of the last "real" voxel of the tilted image, not the position of the most posterior padding voxel.

My master test script looks like this:
```
dcm2niix -b n -m y -p n -z i -o . -f original postop_ct

# Generate a DICOM with positive tilt angle and convert to NIfTI
./tiltify.py postop_ct pos_postop_ct 15.0
dcm2niix -b n -m y -p n -z i -o . -f pos_postop pos_postop_ct

# Generate a DICOM with negative tilt angle and convert to NIfTI
./tiltify.py postop_ct neg_postop_ct -15.0
dcm2niix -b n -m y -p n -z i -o . -f neg_postop neg_postop_ct

echo "Original Affine"
nii_affine.py original.nii.gz

echo "Positive Tilt Affine"
nii_affine.py pos_postop_Tilt_1.nii.gz

echo "Negative Tilt Affine"
nii_affine.py neg_postop_Tilt_1.nii.gz
```

The affines matrices that result look like this:
```
Original
[[  -0.42968801    0.           -0.          110.        ]
 [  -0.            0.42968801   -0.         -132.87057495]
 [   0.            0.            0.625       -53.06000137]
 [   0.            0.            0.            1.        ]]
Positive Tilt
[[  -0.42968801    0.           -0.          110.        ]
 [  -0.            0.42968801   -0.         -132.78686523]
 [   0.            0.            0.62500024  -53.06000137]
 [   0.            0.            0.            1.        ]]
Negative Tilt
[[ -0.42968801   0.          -0.         110.        ]
 [ -0.           0.42968801  -0.         -83.88613892]
 [  0.           0.           0.62499923 -53.06000137]
 [  0.           0.           0.           1.        ]]
```
Note particularly that in the negative tilt case, the y origin is -83.89 instead of -132.79. There is also a small discrepancy of 0.1mm between the y origin of the original and the positive tilt case. This is because of the padding introduced on the anterior side of the most inferior slice, which then requires shifting of voxel centers to align correctly with the most superior slice's voxels. So even in the positive tilt case, the NIfTI origin may be slightly incorrect, depending on exactly how `dcm2niix` does its padding. The NIfTI origin of the padded image should be recalculated as necessary to reflect the effects of padding.

The two scripts referenced above and a `requirements.txt` describing their dependencies can be found this zip file: [scripts.zip](https://github.com/rordenlab/dcm2niix/files/2803874/scripts.zip).

**Comment by neurolabusc** [comment]
Yes, this is true. I have never worried about this as the origin of CT scans is table center (whereas for MRI scans it is magnet isocenter). Therefore, the origin is not useful as a starting estimate for neuroimaging templates. I have always used a [Matlab script](https://github.com/rordenlab/spmScripts/blob/master/nii_setOrigin12x.m) to reset the origin of CT scans. If you contact me directly, I can send you some sample scans where tilt is either included or not included for the same phantom. Applying a translation to the matrix should correct this. I would be happy to review a pull request (and I promise not to try to solve this myself).

**Comment by alund** [comment]
I will work on this.

**Comment by alund** [comment]
Just to provide some context, I have tests where the expected results are expressed in the patient coordinate system (e.g., the tip of an implanted electrode). I want to use those same expected results with tilted images that were derived from the original images by the `tiltify.py` script used above, to ensure that the entire processing pipeline handles gantry tilt correctly. This only works if the position of the image in the patient coordinate system is maintained correctly. So while I would agree that the origin of CT scans has little meaning on its own, knowing that the image is not being relocated can be important.

**Comment by alund** [comment]
#260 is merged, so closing this.

**Comment by alund** [comment]
One followup comment: the fix from #260 does not work correctly for negatively tilted non-axial images, at least not those that I have constructed artificially using my `tiltify.py` script. None of the images that were acquired with gantry tilt that I have access to were non-axial, and I have not figured out how to make the code more general nor can I devote more time right now to figure it out.

**Comment by neurolabusc** [comment]
I have uploaded [real CT scans with Gantry tilt](https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#Computed_Tomography_.28CT.2C_CAT.29) courtesy of Paul Morgan. I am not a CT expert, but I think your concerns are not an issue for human imaging. While MRI acquisition can be set up to acquire Axial, Coronal or Sagittal slices, I do not think the same is true for CT. Since the X-ray source rotates around the participant, you want to minimize the diameter of rotation. Circling the body axially is a much smaller radius than having to go around the feet, which would be required for the coronal and sagittal acquisitions.

**Comment by alund** [comment]
I wondered about that. My biggest hesitation is that I do have a few CT's (without tilt) where the slices are non-axial. As is often the case, I do not know the history of these images, so perhaps there was some post-acquisition processing that changed the orientation.
