### ISSUE TITLE
Gantry tilt interpolation should respect pixel padding value

### ISSUE THREAD

**Issue by alund** [rordenlab/dcm2niix#262]
DICOM tags (0028, 0120), (0028, 0122) or (0028, 0123) can be used to specify pixel padding values. The presence of these values in the image itself indicate pixels without valid data, for example outside the cylindrical acquisition volume of a CT.

When interpolating, these pixels should not be treated as "normal" values that can be used in linear interpolation. My suggestion is, when at least one of the two values used in the interpolation equals the padding value, to use nearest neighbor interpolation instead.

While the effects of this are limited to the border between the padding and real pixels, it changes the intensity histogram enough to confuse our code for a couple of images.

I will submit a pull request with a proposed fix.

**Comment by neurolabusc** [comment]
Fixed with [pull request 246](https://github.com/rordenlab/dcm2niix/pull/246)
