### ISSUE TITLE
Minor issue: “FSPGR 3D 8 900_Series0003” read w/ numDTI>0?

### ISSUE THREAD

**Issue by ihnorton** [rordenlab/dcm2niix#264]
The “FSPGR 3D 8 900_Series0003” series from the Nottingham GE test set seems to be read with `numDTI>0` somewhere in the converter process, so dcm2niix writes invalid/unnecessary DWMRI tags in NRRD output mode (`modality: DWMRI`, a single `DWMRI_gradient` with all zeros, etc.)

(Slicer decides how to read a file in part based on these tags, and fails to read this dataset from dcm2niix NRRD output -- because the NRRD claims to be DWMRI, but the file only has 3 dimensions)

**Comment by neurolabusc** [comment]
@ihnorton the latest commit will decide a sequence is not a DWI scan when a B-value is reported but where the reported number of diffusion directions (0019,10e0) is less than 1. Hopefully, the vendor will fix this in the future, but this should be a robust fix. Thanks to Paul Morgan for suggesting this heuristic.
