### ISSUE TITLE
64 characters long SeriesInstanceUID is stripped to 63 characters

### ISSUE THREAD

**Issue by takhs91** [rordenlab/dcm2niix#268]
Hi,
I have some datasets with a SeriesInstanceUID of 64 characters.

As far as I understand the standard http://dicom.nema.org/medical/dicom/current/output/chtml/part05/chapter_9.html
this is OK. 64 is basically the maximum allowed, and because it is even no trailing NULL is needed.

Although the current  behaviour of dcm2niix strips the last character leaving the 63 first both in BIDS json and in the name when using the "%j" option.

**Comment by neurolabusc** [comment]
Do you have a copy? I like 64 bits as it preserves byte alignment. My reading of the standard is the maximum length is 63 characters plus one NULL terminating character. Since DICOM tags must be an even length, are the length of your tags 64 or 66 bytes? Do you have a sample you can provide?

UIDs, shall not exceed 64 total characters, **including** the digits of each component, separators between components, and **the NULL (00H)** padding character if needed.

**Comment by takhs91** [comment]
Sorry I can't share that case but it SeriesInstanceUID looks like 
1.2.840.113704.1.11.111.1.111.1111.11111111.11111.1111111111.111 which is 64 characters.

Yes my point is in the `and **the NULL (00H)** padding character if needed.`  part.

Because just above it states that:

If ending on an odd byte boundary, except when used for network negotiation (see PS3.8), one trailing NULL (00H), as a padding character, shall follow the last component in order to align the UID on an even byte boundary.

I understand that if it was 63 bytes we should add the trailing NULL to make it even.
Now that is 64 bytes it not needed

I also tried David A. Clunie's `dciodvfy` and didn't report an error when it was 64 bytes.
Then I made a copy and modified with pydicom to 65 characters

In that case I got a 
```
Error - Value invalid for this VR - (0x0020,0x000e) UI Series Instance UID  UI [0] = <1.2.840.113704.1.11.111.1.111.1111.11111111.11111.1111111111.1111> - Length invalid for this VR = 65, expected <= 64

```

**Comment by neurolabusc** [comment]
I see. Unfortunately, C strings must always be null terminated. Please test latest development branch and close if this resolve your issue. All DICOM strings now have a length of 66 bytes. If you have a MacOS or Linux computer with a C compiler installed you can download and compile the latest version with:

$ git clone --branch development https://github.com/rordenlab/dcm2niix.git
$ cd dcm2niix/console
$ make
$ ./dcm2niix

If you are using Windows, you can go to the [development branch web page](https://github.com/rordenlab/dcm2niix/tree/development) and click the green AppVeyor button. The AppVeyor includes a compiled version in the  'Artifacts' link.

**Comment by takhs91** [comment]
Thanks for the prompt response!
I will test it in the asap during the day

Why not 65 though? the required 64 plus the mandatory C null termination. Is it because you also prefer even byte alignment?

**Comment by takhs91** [comment]
I tested with the dev branch. All series now had their full SeriesInstanceUID both in the json bids and in their name using the '%j' as filename.

Although one of them, which happens to be a perfusion(4d) series gets a '_t91912' appended to the filenames after the SeriesInstanceUID. The SeriesInstanceUID appears correct in the json bids.

There is no nifti file with the same name in that dir so it could have to append something for making it unique, and either way you add 'a', 'b', 'c' etc in that case.

Any ideas why this may happen? Is it regular behavior to append suffixes in some cases or could it be a bug?

**Comment by neurolabusc** [comment]
The [filenaming](https://github.com/rordenlab/dcm2niix/blob/master/FILENAMING.md) page describes the file naming. For example '_t91912' reveals the `trigger delay time (0020,9153)`. This helps discriminate volumes with different trigger delays acquired in a series. When you get images with the 'a','b','c' it suggests that your filenaming scheme was unable to disambiguate the output images, and so these post-fixes were appended to overwrite data. There are typically two solutions to this:

1. Provide a better file naming scheme, for example `-f %t` will name files only based on the study time, so all series acquired in a session will conflict with each other. On the other hand, `-f %t_%s_%p` will dissociate images from different series.
2. Localizer/scout scans are acquired for planning upcoming scans, but are useless for analyses. These typically acquire orthogonal slices, while NIfTI requires all slices to be co-planar. The `-i y` option will attempt to ignore (not convert) localizer and derived images. Hopefully, this will disregard the images that are not required for your processing.

**Comment by takhs91** [comment]
I've never noticed that doc file. I will have a look. Thank you for the information.

**Comment by takhs91** [comment]
Ok this probably needs a new issue, but I don't think I should have the '_t91912' suffix appendix on that series since all files haven no  (0020,9153) tag at all. 

This is happening in the development branch but not with the latest master.

**Comment by neurolabusc** [comment]
If you look at those images with your favorite DICOM header viewer (e.g. Horos, dcmdump) I think you will find that a value is listed in [0018,1060](http://dicomlookup.com/lookup.asp?sw=Tnumber&q=(0018,1060)).

**Comment by takhs91** [comment]
Yes you are right this value is populated. It starts with 88 and adds up slice by slice by 88 to 89 with an interleaved scheme inside a volume. Its actually the same as the SliceTiming reported in the bids. 

May I ask what is the meaning of '_t91912' it looks as its the slice time of the slice before the last one +> 92000 - 88.
The TR is 2300 there are 40 volumes and there are 26 slices per volume

**Comment by neurolabusc** [comment]
It is however your vendor interpreted [0018,1060](http://dicomlookup.com/lookup.asp?sw=Tnumber&q=(0018,1060)) with respect to your sequence. dcm2niix is simply rote reporting what it is told by the DICOM header.

**Comment by takhs91** [comment]
I see. I will have a look at some point. Thanks for resolving this!
