### ISSUE TITLE
Conversion Issue: Can't read Mosaic

### ISSUE THREAD

**Issue by dlevitas** [rordenlab/dcm2niix#275]
Hello,

I've been organizing my data into the BIDS format (using dcm2bids and dcm2niix); however, I've recently come across an issue where when I convert my functional bold dicoms, the json files do not contain any slice timing information. For reference, I'm using dcm2niix version v1.0.20181125. I was able to temporally resolve the issue by using dcm2nii instead; however, since dcm2bids doesn't work with dcm2nii, I can't get my data into the proper BIDS format. 

Is there a way I can fix the issue using dcm2niix?

Thank you for the assistance .

**Comment by neurolabusc** [comment]
Thanks for sharing examples. When converting these files dcm2niix notes ` Warning: 0008,0008=MOSAIC but number of slices not specified`.  To determine the number of slices in a mosaic, the DICOM header needs to report the `Number Of Images In Mosaic` (0019,100A) tag or include include a `CSA Image Header Info` (0029,1010) tag with the `NumberOfImagesInMosaic` field. While my old dcm2nii converts your images, it does so be inferred that all slices are populated, an assumption which for 9x9 mosaics like yours will only be correct in 1/9 times, so most of the time it will put poor starting estimates in the SForm and QForm. Furthermore, without 0019,100A you will have an impoverished BIDS sidecar. The approach of dcm2niix is clearly superior: you should be alerted to rescue your data at the earliest stage.

While I do not know the providence of your image, the tag
`(0002,0013) SH [MATLAB IPT 9.4] `
reveals this is not the raw data off the console. I suspect someone was over aggressive in anonymizing the data, and removed all the private tags. The private tags are critical for determining parameters like slice timing, diffusion directions, field mapping, etc. 

In brief, this is not a limitation of dcm2niix, but rather the DICOM files it was provided.
