### ISSUE TITLE
Issue during conversion when localizer dicoms missing

### ISSUE THREAD

**Issue by dlevitas** [rordenlab/dcm2niix#277]
This is a [cross post](https://github.com/cbedetti/Dcm2Bids/issues/40) from the dcm2bid's github page. 

Long story short, I don't have any localizer dicoms, but the dcm2niix process seems to assume that they should be there. This seems like a rare issue (most raw dataset dicoms seem to include localizer), but I'm still curious to see how to deal with this potential issue in the future.

Thank you.

**Comment by neurolabusc** [comment]
dcm2niix converts each series independently: each conversion has no knowledge of other series in the  study. Unless your file naming fails to disambiguate images (so one series would overwrite another), there is no interaction. You want to run dcm2niix independently from the command line to see the images that are generated. In general I use the `-i y` to ignore localizer images (so they are not converted). However, your description makes this sound like the situation is specific to the dcm2bids setup.

**Comment by dlevitas** [comment]
I just re-ran dcm2niix two separate times. The first followed the command used in dcm2bids:
```
dcm2niix -b y -ba y -z y -f '%3s_%f_p_%t' -o $dicomdir/test1 $dicomdir/sub-001
```

The second was with the ```-i y``` option
```
dcm2niix -b y -ba y -z y -f '%3s_%f_p_%t' -o $dicomdir/test1 $dicomdir/sub-001
```
In both cases, they converted the dicoms in the same manner. For example, "002_sub-001_p_20180928130637.nii.gz" should be "001_sub-001_p_20180928130637.nii.gz" I believe, since the localizer dicoms are missing, and 001_000001_000001.dcm is one of the dicoms for the non-normalized T1 anatomical.

**Comment by neurolabusc** [comment]
Please see the page on [file naming](https://github.com/rordenlab/dcm2niix/blob/master/FILENAMING.md), for example `-f %3s` will insert the series number stored in the DICOM tag 0020,0011 into the file name. This is a rote copy, dcm2niix is making no inference regarding other images in the series, it is simply transcribing the value from the DICOM header. If the localizer was the first series, and the T1 was the 2nd series, than `-f %3s` will save the T1 scan as 002.nii regardless of whether you decide to convert the localizer or not (unless some other DICOM tool re-ordered the series numbers). 

The leading cause of DICOM issues is how the DICOM files are handled after they leave the scanner. If you are having problems I would check the providence of your images. Specifically, did your images go through an anonymization stage, an attempt to change the transfer syntax, or a change in the value representations from explicit to implicit? A good first step is to see if you can get the images direct from the scanner - if this fixes your issue, than a downstream tool influenced your images. Many DICOM tools that predate the release of enhanced DICOM formats will catastrophically mangle modern DICOM images. A good second step is to check the SourceApplicationEntityTitle in your DICOM header (0002,0016). This typically reveals the last tool that saved your DICOM header. If this is not your scanner console, it will suggest that some tool manipulated your images.  In my experience, the modern versions of popular freeware tools "dcm4che","GDCM" and "OFFIS DCMTK" are very robust (that are heavily used, and problems are rapidly identified). However, the quality of less popular tools tends to be more problematic.

**Comment by dlevitas** [comment]
Got it. I just checked, and that looks like it was indeed the case! The scan did include a localizer, but those dicoms were for whatever reason not in with the rest.

Closing this issue.
