### ISSUE TITLE
Extract more informations from Philips enhanced DICOM

### ISSUE THREAD

**Issue by arnaudbore** [rordenlab/dcm2niix#279]
Hi,

I would like to know if there is some ongoing work to be able to extract the phase encoding direction from Philips DWI enhanced DICOM into the json. So far the only information I've got is the phase encoding axis. I would have the same question for the totalreadouttime needed for topup FSL.

Thank you in advance for your help.

Arnaud

**Comment by drmclem** [comment]
Hi

I'm afraid that at the moment this information is not stored in the Dicom headers for Philips, only the axis.

Best

Matthew

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by neurolabusc** [comment]
duplicate. See issue [151](https://github.com/rordenlab/dcm2niix/issues/151) and [258](https://github.com/rordenlab/dcm2niix/issues/258). Philips does not encode this information in their DICOMs.

**Comment by arnaudbore** [comment]
If I understand [this link](https://na-mic.org/wiki/NAMIC_Wiki:DTI:DICOM_for_DWI_and_DTI#Private_vendor:_Philips) does not help.

**Comment by neurolabusc** [comment]
That link (the current version of which I wrote) describes how Philips encodes diffusion directions in their DICOM data. See here for further details on how dcm2niix handles Philips [DICOM](https://github.com/rordenlab/dcm2niix/tree/master/Philips) images. While we are able to extract the bval/bvec data, we are not able to extract readout time and phase encoding polarity since they are not included by Philips. Note that you can guess on readout time: it only influences the calibrated estimates for effect sizes, the images that are calculated and used for further processing are not influenced by this value. Also, dcm2niix is able to tell you "PhaseEncodingAxis" (e.g. R<->L vs A<->P), but the is no way to determine phase encoding polarity (e.g. A->P vs  P->A). If the protocol name reveals this you should be able to write a heuristic to encode this property.

**Comment by unimusic** [comment]
Hi, I have a question that might be basic, but I can't find the answer anywhere. If I have an Axial scan, that goes from left to right, what would the corresponding phase encoding direction be? i, -i, j, or -j?

How do these parameters map to the letters?

Thanks,

- Angela

**Comment by neurolabusc** [comment]
Angela, the [dcm_qa](https://github.com/neurolabusc/dcm_qa/tree/master/Ref) includes validation images in both DICOM and NIfTI, each saved in the RPI convention:

```
>fslhd noPF_noPAT_noPOS_PEres100_ES0p60_BW2222_RL_30.nii
...
sform_xorient	Right-to-Left
sform_yorient	Posterior-to-Anterior
sform_zorient	Inferior-to-Superior
...
>more noPF_noPAT_noPOS_PEres100_ES0p60_BW2222_RL_30.json
        "PhaseEncodingDirection": "i",
...        
>fslhd noPF_noPAT_noPOS_PEres100_ES0p60_BW2222_LR_31.nii
sform_xorient	Right-to-Left
sform_yorient	Posterior-to-Anterior
sform_zorient	Inferior-to-Superior
...
>more noPF_noPAT_noPOS_PEres100_ES0p60_BW2222_LR_31.json
...
        "PhaseEncodingDirection": "i-",
```

I do not think any tools care if you label arbitrarily label one image "i" and the other "I-" as long as the phase encoding is along the columns (fastest changing dimension as stored on disk). For more details, see [here](http://justinblaber.org/brief-introduction-to-dwmri/) and [here](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FDT/FAQ#What_conventions_do_the_bvecs_use.3F). Feel free to post a message on the [FSL mailing list](https://www.jiscmail.ac.uk/cgi-bin/webadmin?A0=fsl) for more details.

I presume you have Philips data, as you posted on this thread. I would encourage you to reach out to your Philips Research Collaboration Manager for help. I also urge you to lobby them to include phase encoding polarity in their DICOM headers. It is their job to be your advocate.

**Comment by unimusic** [comment]
Thank you so much for the fast response. So, either i or i- would work in my case?

I will certainly bring up the issue but I am not sure they will have an effect :)

**Comment by neurolabusc** [comment]
If you have the sign wrong, TOPUP will estimate have the sign of the correct wrong, but apply it in the opposite order, so all will be well. It assumes that the two blips have distortions of identical magintude, but opposite direction, and its job is to find the midpoint. You can also use these [images](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/topup/Faq) to help guide you with visual inspection.

**Comment by unimusic** [comment]
Okay, so one of my images is the 1st picture, and the other one is the 2nd picture. Can you please help me confirm that corresponds to i and i-? How do the vectors correspond to the letters? Thank you!
