### ISSUE TITLE
Adding a `--version` argument

### ISSUE THREAD

**Issue by cbedetti** [rordenlab/dcm2niix#280]
It could be a nice feature to have.
It's not difficult to parse automatically but if the output format of dcm2niix change, the parsing method will probably break.

**Comment by neurolabusc** [comment]
Do you want to try the latest commit to the development branch. Normally the verbose command is always followed by an argument (`-v y` or `-v n`). The latest commit changes the behavior, so if `-v` is the last argument it will output the version date on a separate line. The program will also terminate with the exit code "3", whereas prior versions (which did not have this feature) will exit with "0". This allows you to discriminate new versions from versions that pre-dated this feature. Alternatively, just parse the first line for the first occurrence of "v1." - I do not anticipate a v2 (or even a 1.1) ever, but this would indicate a dramatic break in the API.

```
$ ./dcm2niix -v
Chris Rorden's dcm2niiX version v1.0.20190308  GCC8.2.0 (64-bit MacOS)
v1.0.20190308
$ echo $?
3
```
