### ISSUE TITLE
EffectiveEchoSpacing Units

### ISSUE THREAD

**Issue by dlevitas** [rordenlab/dcm2niix#281]
Hello,

I'm using version ```v1.0.20181125```, and have the following value for my effective echo spacing : 0.000580009. Is this value in milliseconds? My analysis requires me to state the effective EPI echo spacing in ms, so I wanted to clarify the unit of time dcm2niix uses for this field?

Thanks,

Dan

**Comment by neurolabusc** [comment]
dcm2niix creates a BIDS format JSON sidecar. The [format](https://bids.neuroimaging.io/bids_spec.pdf) requires `time SHOULD be expressed in seconds. Please note that some DICOM parameters have been traditionally expressed in milliseconds. Those need to be converted to seconds.`
