### ISSUE TITLE
Bruker Enhanced MR DICOM - parametric maps

### ISSUE THREAD

**Issue by isolovey-robarts** [rordenlab/dcm2niix#282]
Another issue with a multi-frame (Enhanced MR) DICOM from a Bruker scanner, this time with a parametric map.

I've uploaded a T2 map DICOM file [here](https://www.dropbox.com/s/di5lppdcf3ahqab/Bruker_enhanced_MR_T2map.zip?dl=0).

The volumes in this series represent different contrasts/outputs and should end up in separate Nifti files. The uploaded series is a T2 fit, so the 5 volumes are relaxation time, signal intensity (parameters fitted), as well as their standard deviations and the standard deviation of the fit.

There are a few issues here:

- `v1.0.20181125` splits up the volumes into separate files as needed, but the latest development branch build combines them into a 4D Nifti.
- In both `v1.0.20181125` and `development` builds, the slice and volume ordering is swapped, similar to [this](https://github.com/rordenlab/dcm2niix/issues/241#issuecomment-435935079). Swapping the last two dimensions using the linked snippet fixes the problem (but each volume of the corrected dataset should then be saved separately).
- Ideally, the Nifti file names should include `(0020,9453) Frame Label`, if present. In our specific case, they are meaningful and useful. Not sure how generalisable that is.

**Comment by neurolabusc** [comment]
Feel free to submit pull requests to address this. I would suggest waiting for Bruker to update their DICOMs to resolve [issue 265](https://github.com/rordenlab/dcm2niix/issues/265).

Once they have fixed their images it would be great to have a validation dataset that showcases unique features of Bruker images. We can use those images to regression test every commit. This would parallel the validation datasets for [GE](https://github.com/neurolabusc/dcm_qa_nih), [Philips](https://github.com/neurolabusc/dcm_qa_philips), [Siemens](https://github.com/neurolabusc/dcm_qa) and [UIH](https://github.com/neurolabusc/dcm_qa_uih). In the meantime, I would suggest exporting to their proprietary format (or use your code snippet for images like this one).

As you note, one could use FrameComments (0020,9158) or FrameLabel (0020,9453) for naming the different volumes.

For the record, here is how 2D slices in your sample enhanced DICOM image are saved.

```
        (0020,9057) UL 1                                        #   4, 1 InStackPositionNumber
        (0020,9128) UL 1                                        #   4, 1 TemporalPositionIndex
        (0020,9156) US 1                                        #   2, 1 FrameAcquisitionNumber
        (0020,9157) UL 1\1\1                                    #  12, 3 DimensionIndexValues
        (0020,9158) LT [signal intensity]                       #  16, 1 FrameComments
...
        (0020,9056) SH [1]                                      #   2, 1 StackID
        (0020,9057) UL 1                                        #   4, 1 InStackPositionNumber
        (0020,9128) UL 1                                        #   4, 1 TemporalPositionIndex
        (0020,9156) US 2                                        #   2, 1 FrameAcquisitionNumber
        (0020,9157) UL 1\1\2                                    #  12, 3 DimensionIndexValues
        (0020,9158) LT [std dev of signal intensity]            #  28, 1 FrameComments
...
        (0020,9057) UL 1                                        #   4, 1 InStackPositionNumber
        (0020,9128) UL 1                                        #   4, 1 TemporalPositionIndex
        (0020,9156) US 3                                        #   2, 1 FrameAcquisitionNumber
        (0020,9157) UL 1\1\3                                    #  12, 3 DimensionIndexValues
        (0020,9158) LT [T2 relaxation time]                     #  18, 1 FrameComments
...
        (0020,9057) UL 1                                        #   4, 1 InStackPositionNumber
        (0020,9128) UL 1                                        #   4, 1 TemporalPositionIndex
        (0020,9156) US 4                                        #   2, 1 FrameAcquisitionNumber
        (0020,9157) UL 1\1\4                                    #  12, 3 DimensionIndexValues
        (0020,9158) LT [std dev of T2 relaxation time]          #  30, 1 FrameComments
...
        (0020,9057) UL 1                                        #   4, 1 InStackPositionNumber
        (0020,9128) UL 1                                        #   4, 1 TemporalPositionIndex
        (0020,9156) US 5                                        #   2, 1 FrameAcquisitionNumber
        (0020,9157) UL 1\1\5                                    #  12, 3 DimensionIndexValues
        (0020,9158) LT [std dev of the fit]                     #  18, 1 FrameComments
...
        (0020,9057) UL 2                                        #   4, 1 InStackPositionNumber
        (0020,9128) UL 1                                        #   4, 1 TemporalPositionIndex
        (0020,9156) US 6                                        #   2, 1 FrameAcquisitionNumber
        (0020,9157) UL 1\2\1                                    #  12, 3 DimensionIndexValues
        (0020,9158) LT [signal intensity]                       #  16, 1 FrameComments
```

**Comment by isolovey-robarts** [comment]
Thanks, we'll look into fixing this and submit a PR. Regarding #265, we are in the process of testing our new diffusion phantom and will have a good validation dataset shortly.

**Comment by neurolabusc** [comment]
Great. Be aware that a solution to #265 will require new software from Bruker that records the BVec into (0018,9089). Even if Bruker corrects their BMatrix (0018,9602..9607) it is insufficient to extract the bvec. To demonstrate this, consider the polar opposite BVecs [1 0 0] and [-1 0 0]: they both generate an identical BMatrix. Therefore, the BMatrix is insufficient to recover the BVec we need.

**Comment by neurolabusc** [comment]
@isolovey-robarts am I correct that your pull request resolves this issue in the developmental branch? If so, I suggest we close this issue and generate a new stable release.
