### ISSUE TITLE
Strange skipping of some sequences

### ISSUE THREAD

**Issue by lrq3000** [rordenlab/dcm2niix#283]
Hello,

I have a weird error with some dicom folders/subjects, where all sequences are converted except one, here the structural, which is quite bothering. However, if I try to convert ONLY this sequence (by providing the fullpath to only this sequence subfolder), then it gets converted alright.

Would it be possible to send you the data via an email? I cannot publish here as it is not anonymized.

Thank you in advance

**Comment by lrq3000** [comment]
Update: I think I know what is happening, dcm2niix.exe is chocking on some malformatted dicoms, and then stops conversion from there. Is there a way to pass such errors and continue conversion of the rest?

**Comment by neurolabusc** [comment]
This is the expected behavior - dcm2niix should terminate when there is a fatal error. You can interrogate the output by looking at the last exit code (from the command line or bash scripts, you can use `$?` for the last exit code). An exit code other than 0 suggests a fatal error. You can look at the log to get more details. I think you want to check the providence of your images and correct the problem at the root.

```
$ dcm2niix
Chris Rorden's dcm2niiX version v1.0.20190308 Clang10.0.0 (64-bit MacOS)
...
$ echo $?
0

```

**Comment by lrq3000** [comment]
Yes I have the error status here it is:

```exit status -1073740791```

It might be the behavior you expected (and implemented), but when using dcm2niix as a recursive converter, this is not expected: how can I know which files were converted and which files aren't because dcm2niix stopped before? It's normal it can't convert the ones that are buggy, but I would expect it to continue converting the ones it can in recursive mode. Would it be possible to provide such a switch please?

**Comment by lrq3000** [comment]
Digging a bit more, since I have 7 acquisitions for which there is an issue (over a total of more than 400 acquired over 10 years, so not too shabby, dcm2niix is working quite well ;-) ).

For example, there is a BOLD sequence that cannot be converted (but they can be opened alright), here is the dcm2niix output:

```
Compression will be faster with pigz.exe in the same folder as the executable
Chris Rorden's dcm2niiX version v1.0.20181125  (JP2:OpenJPEG) (JP-LS:CharLS) MSC1900 (64-bit Windows)
Found 300 DICOM file(s)
Image Decompression is new: please validate conversions
slices stacked despite varying acquisition numbers (if this is not desired recompile with 'mySegmentByAcq')
File not large enough to store image data: input\1.3.12.2.1107.5.2.32.35033.2016092613464767712171978.dcm
```

And indeed when I looked at the dicom files, there are 3 volumes that got corrupted over 300. If I remove these volumes, the conversion runs alright. I know it might tamper with the temporal integrity, but it's debatable whether one would like to keep or reject a subject in such a case. In my case, this data is quite difficult to acquire, so I would like to keep.

So there are two levels of possible "ignoring": between sequences (if one sequence is corrupted, ignore and go to the next) or within-sequence (if this sequence is corrupted but has multiple volumes like BOLD, try to skip to the next and build with only valid ones).

I really think that it would be greatly beneficial to the robustness of dcm2niix (which is already awesome) to:
1. give the ability to skip corrupted sequences, or even just corrupted volumes in timeseries (using 2 different switches? Or one switch with 3 possible values: n, y, v?).
2. output error messages in the console, and not only return an error code, to be more explicit for commandline users who are not using the tool in a batch.

About 2., for example I have an acquisition where it seems to choke on the very first dicom, so here is the output:
```
Compression will be faster with pigz.exe in the same folder as the executable
Chris Rorden's dcm2niiX version v1.0.20181125  (JP2:OpenJPEG) (JP-LS:CharLS) MSC1900 (64-bit Windows)
Found 1269 DICOM file(s)
```
Seems everything went alright to a beginner, but the output folder is totally empty! An explicit error message would be greatly helpful here.

**Comment by lrq3000** [comment]
BTW: I am not saying there should be no return error code, it should of course be maintained (it could be saved and returned at the end), but just be able to continue if the related switch is provided :-)

**Comment by neurolabusc** [comment]
The expected behavior is for dcm2niix to terminate with both an error message message as well as an exit code as soon as it encounters a catastrophic error. There are many situations where dcm2niix can ignore images (localizers, derived images, etc) and skip DICOM files that are not DICOM images (e.g. DICOM sound files). A catastrophic error should only be generated when an image seriously violates the DICOM standard. Can you share an example that replicates your issue where it says it founds 1269 DICOMs but terminates without an error message? This is not expected behavior. It sounds like the data is compressed, I wonder if this is an issue with one of the external decompression libraries (e.g. CharLS or OpenJPEG). This situation should be fixed.

**Comment by neurolabusc** [comment]
Please test the latest commit on the developmental branch. It will immediately exit as soon as a corrupt DICOM image is detected and provide the user with a clear error message. Your dataset had some corrupt DICOM files that only stored the first 4-16kb of the header for a file that should have been 1.7mb in size. Unfortunately, some of these files were clipped inside the proprietary Siemens CSA header, where the error detection was not as thorough as the main DICOM header.

The latest revision ensures that dcm2niix responds predictably to this situation: no files are converted, a clear error message is generated and the program terminates with an error code. The new commit improves dcm2niix's error detection. However, this does highlight a fatal problem with your dataset. I would check the providence of your data and determine why some of the files were not stored in their entirety. 

```
$ ./dcm2niix -b i -v 0 ~/tst/issue283
Chris Rorden's dcm2niiX version v1.0.20190323  GCC8.2.0 (64-bit MacOS)
Found 217 DICOM file(s)
Error: Conversion aborted due to corrupt file: /tst/issue283/1.3.12.2.1107.5.2.32.35033.2015030916041244015825299.dcm
```
