### ISSUE TITLE
single volume instead of multivolume

### ISSUE THREAD

**Issue by mishmash85** [rordenlab/dcm2niix#284]
Hi there,
I have been using the older version (dcm2nii) to convert dicom to nifti files. This gave me single volume nifti files, one for each time volume (say I had 300 tr time points, i'd get 300 nifti files). With the new dcm2niix i seem to get multi volume nifti images (e.g. 300 time volumes as 1 mega nifti). Is it possible to get single nifti files ? I am pretty sure I need these single volume files to work with them in SPM.

**Comment by neurolabusc** [comment]
SPM has no problem with 4D volumes. To do so with the graphical interface just put 1:9999 in the volume selection box. My [course web page](https://people.cas.sc.edu/rorden/tutorial/html/blockspm.html) provides a 4D fMRI dataset with step by step instructions for analyzing it with SPM.
