### ISSUE TITLE
Request: Flag to skip call to removeDuplicates

### ISSUE THREAD

**Issue by halfSpinDoctor** [rordenlab/dcm2niix#287]
I have an issue opening DICOM data exported from the MIM radiotherapy software (https://www.mimsoftware.com/). It is malformed DICOM, and there is no Instance Number (0020,0013) set for any of the images.

Would you consider adding a flag to skip the call to removeDuplicates() line #4142 in nii_dicom_batch.cpp: nConvert = removeDuplicates(nConvert, dcmSort);

This would enable conversion of these images. My workaround is to comment this call out and recompile the software. I am happy to do the modifications and submit a pull request for this, if you like. I know this is non-standard DICOM, and thus should not need be handled here, but it would be really useful to have a flag to enable this. Thanks! -Sam Hurley

**Comment by neurolabusc** [comment]
As @drmclem has [noted](https://github.com/rordenlab/dcm2niix/issues/184), Instance Number (0020,0013) is not required to be unique. Therefore, while unique instance numbers are desirable for archival data, it is not required for valid DICOM images. Can you tell me if MediaStorageSOPInstanceUID (0002,0003) is unique for each of your images? You can check using dcmdump, gdcmdump or `dcm2niix -v 2` to view the DICOM headers.

**Comment by neurolabusc** [comment]
Can you please try the latest developmental release (v1.0.20190410). It will attempt to use the MediaStorageSOPInstanceUID (0002,0003) to disambiguate images. I have not seen your dataset, so not sure if this will work. But it minimizes unintended consequences relative to merely ignoring duplicates.
