### ISSUE TITLE
hdr/img to nii

### ISSUE THREAD

**Issue by Student-HXJ** [rordenlab/dcm2niix#292]
hi, could this script convert hdr/img to nii?

**Comment by neurolabusc** [comment]
dcm2niix is a standalone executable, not a script. It is designed to convert DICOM data as used in medical imaging to the NIfTI format used in science. It creates single file NIfTI images (.nii or .nii.gz). If you want to convert NIfTI images from two file (.hdr/.img) to single file (.nii and .nii.gz) I would suggest using [https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/Fslutils](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/Fslutils) as a stand alone executable. If you prefer Matlab scripts, I would suggest @xiangruili's outstanding [nii_tool](https://github.com/xiangruili/dicm2nii).
