### ISSUE TITLE
dcm2niix does not create bvec/bval files from Siemens DICOM files

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [rordenlab/dcm2niix#293]
Some DWI series exported from a Siemens Skyra are not properly converted by _dcm2niix_: no bvec/bval files are created. Other DWI series from the same scanner do get properly converted. More on differences between series below. On the other hand _dcm2nii_ does always succeed. The exit status of _dcm2niix_ is always 0. Strangely enough we even have the case of a single session with two DWI series, one properly converted and the other not:
```
$ dcm2niix dwi 
Chris Rorden's dcm2niiX version v1.0.20181125  GCC5.3.1 (64-bit Linux)
Found 1980 DICOM file(s)
slices stacked despite varying acquisition numbers (if this is not desired recompile with 'mySegmentByAcq')
Convert 1980 DICOM as dwi/dwi_DTI_20170927155418_12 (128x128x60x33)
Conversion required 1.601712 seconds (1.600897 for core code).
$ 
$ dcm2niix dwi_rev
Chris Rorden's dcm2niiX version v1.0.20181125  GCC5.3.1 (64-bit Linux)
Found 540 DICOM file(s)
slices stacked despite varying acquisition numbers (if this is not desired recompile with 'mySegmentByAcq')
Saving 9 DTI gradients. Validate vectors.
Convert 540 DICOM as dwi_rev/dwi_rev_DTI_REVERSED_20170927155418_13 (128x128x60x9)
Conversion required 0.472357 seconds (0.472108 for core code).
$ 
```

Hopefully we're not doing anything wrong as in #267: we have checked that _dcm2niix_ doesn't properly convert DICOM files directly out of the PACS.

Back to the case of a single session with DWI series, here are the differences I see between the two DWI series, _dwi_ which _dcm2niix_ fails to convert properly and _dwi_rev_ which is properly converted:
* Some of the private tags that store the [CSA header](https://nipy.org/nibabel/dicom/siemens_csa.html) are empty in _dwi_ but not _dwi_rev_:
  * **(0029,1010)**
  * **(0029,1020)**.
* Some private tags are completely missing from from _dwi_ but not _dwi_rev_:
  * **(0029,0011)**
  * **(0029,1160)**

These private tags are not emptied/removed by our anonymization process. They might have been removed by the Siemens MRI console or even the PACS - we haven't been able to understand if and how they are modified so far.

We can provide the anonymized (or perhaps even non-anonymized) files if needed.

Do the above missing private tags explain the failed conversion? Is it really unexpected to see those tags missing? Any clue how they could be missing?

**Comment by DimitriPapadopoulos** [comment]
Diff between the outputs of _dcmdump_ runs on _dwi_ and _dwi_rev_ series:
![meld](https://user-images.githubusercontent.com/3234522/56511621-52e23180-652d-11e9-8dc3-06023d8b376a.png)

**Comment by neurolabusc** [comment]
This is a limitation of your images, not dcm2niix. Siemens-specific details for dcm2niix are described [here](https://github.com/rordenlab/dcm2niix/tree/master/Siemens). As you note, some of your images are missing the crucial [CSA Image Header Info](https://nipy.org/nibabel/dicom/siemens_csa.html) (0029,1010). Beyond the gradient directions, the CSA image header is required to determine the number of slices in a mosaic, slice measurement duration, bandwidth, slice timing, etc. You really need this for archival quality data. I think you need to check the providence of your images to understand which stage removed this important information. I would suggest copying these files to a memory stick directly off the console. This should show that all images originally have the CSA header (if not, contact your Siemens research collaboration manager), next look at the images that have been touched by your PACS to see if these tags were removed. Working step by step, you should be able to determine the tool that corrupted your images. At my center, our Siemens system sends images directly to [dcmtk](https://dicom.offis.de/dcmtk.php.en), which archives all of your images. I strongly recommend dcmtk: it is free, and the combination of popularity and active development has led to a very robust tool.

**Comment by neurolabusc** [comment]
As an aside, I note that the DTI and reverse-phase encoded DTI appear to be acquired in the same session, but they use different slice angulation (Sag 3.2 vs 1.5). The typical reason for acquiring these two scans is to use Eddy and TOPUP to reduce distortions that are of identical magnitude but opposite polarity in these two sequences. It is crucial to ensure that when you do this you acquire the two series with identical slice centers and rotations. Otherwise, you will have different fields of view, and likely the system will use a different shim. 

In general, you can use the "Copy References" to ensure that your two diffusion series are aligned with each other. If you are using E11C, be aware that there are two bugs with the Siemens DWI product: a.) copy references can swap P>A encoding to R>L even when set to NOT copy phase encoding. b.) When using monopolar scans (which allow better SNR, at the cost of correctable distortion) the Siemens product sequence will convert gradients to half-sphere acquisitions, which is not ideal for Eddy. Therefore, if you do use E11C, I strongly suggest you get the free and excellent CMRR sequences, which do not exhibit these problems.

**Comment by mharms** [comment]
Just to expand briefly, the CMRR ep2d sequences (DWI and BOLD) include an option on the "Sequence:Special" tab to "Invert RO/PE Polarity", which provides a _work-around_ to the bug that Chris mentions in item (a) above.  If you attempt to achieve a "P>A" PE polarity in the CMRR sequences by setting the phase encoding rotation to 180 deg (which is the only approach available in the Siemens ep2d product sequences) the CMRR sequences will exhibit the same bug.

**Comment by DimitriPapadopoulos** [comment]
Thank you for looking into this. I'll see what we can do to investigate where the images have been corrupted between the MRI console and the PACS. Probably too late to do anything about it though, as the images have probably been erased from the console.

I agree about [dcmtk](https://support.dcmtk.org/docs/storescp.html), that's what we have been using in my research centre for more than a decade to archive images. However these specific datasets have been acquired in a hospital where everything is set up to go straight to a commercial PACS as far as I can understand.

**Comment by DimitriPapadopoulos** [comment]
Also note that the images extracted straight from the PACS contain tag **(0002,0013)** _Implementation Version Name_ with value `OFFIS_DCMTK_354`. Therefore the hospital might be using _dcmtk_ as a PACS after all - although an [old version released in 2005](https://github.com/DCMTK/dcmtk/releases/tag/DCMTK-3.5.4).
