### ISSUE TITLE
Slice timing not reported for "4D" Siemens NX-VA10A DICOMs

### ISSUE THREAD

**Issue by lucijj** [rordenlab/dcm2niix#294]
Hi again:

It seems that when the data are saved as "4D" DICOMs, the slice timing is not reported in NX-VA10A. I am using v1.0.20190410.

When the data are saved as a single DICOM for an EPI scan with dimensionality nRE × nPE × 1 × (nS × nVol), with nRE=number of point in read direction, nPE=number of points in phase direction, nS=number of slices, and nVol=number of volumes, the slice timing is not reported. I've been able to get slice timing when the volumes are stored in separate DICOMs, but we have some users who have acquired data this way, and it's not easy to go back and fix it.

Sample data can be obtained here:
https://utexas.box.com/v/dcm2niix-data

If you need me to acquire test data, I'm happy to do so.

Thanks as always,
Jeff

**Comment by neurolabusc** [comment]
The sample data provided are all 3D acquisitions (T1/T2 anatomical scans). Slice timing refers to 2D (EPI) acquisitions, and is only relevant for 4D datasets.
