### ISSUE TITLE
CT and MR images in same go

### ISSUE THREAD

**Issue by sportnoah14** [rordenlab/dcm2niix#295]
Hi,

When converting a MR session of dicom images to niftis, could anything go wrong if the -m flag is used? I work with CT scans as well so that flag is used quite often. Thanks for this amazing app!

**Comment by neurolabusc** [comment]
For MRI sequences, generally one does not want to merge data from a single series where echo time, coil, or orientation varies. Hence the default is to not merge (`-m n`). For example, most tools want a field map with two echoes to be saved as two distinct 3D images. Unfortunately, there is no such consistency in CT users. Some teams want to separate CT data for different exposures or different current voltage, while other teams while other teams want to combine [them](https://github.com/rordenlab/dcm2niix/issues/91). This does not reflect a limitation in dcm2niix, rather different expectations by different groups. 

I guess the question is whether you ever want to merge your CT data. If so, you may want to write a simple script that separates the CTs from the MRs.
