### ISSUE TITLE
Wiki Link not working

### ISSUE THREAD

**Issue by ASVBPREAUBV** [rordenlab/dcm2niix#297]
The Link to your Wiki is not working.
https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#General_Usage
Maybe its just temporary.

**Comment by neurolabusc** [comment]
Link works for me. Not sure if NITRC fixed this or you have specific issues with their site (maybe check your DNS). If you have problems with NITRC, you can contact them directly at moderator@nitrc.org.
