### ISSUE TITLE
Is there a way to specify a list of fields we want in the BIDS JSON side car?

### ISSUE THREAD

**Issue by cmadjar** [rordenlab/dcm2niix#304]
Hello,

I was wondering if there was a way to specify to `dcm2niix` a list of fields we want to see in the JSON side car. For example, we would like to have the SeriesUID, StudyUID and other unique IDs in the JSON sidecar file for databasing purposes but I don't see those in the JSON file created by `dcm2niix`. 

Is that something possible? If not, is that something you would think of adding?

Ideally, for our use case, it would be great to be able to give `dcm2niix` a list of headers we want available for the dataset.

Let me know. Thank you!

**Comment by neurolabusc** [comment]
The JSON file attempts to follow the BIDS Specification. I think there are two options: 
 1. Lobby to have these tags included in the BIDS specification.  @chrisgorgo is the maintainer for BIDS inclusion in dcm2niix, but I would be happy to help if these were defined in the specification.
 2. It is possible to add tags that are not defined in the BIDS specification. You could fork dcm2niix and modify it to include the tags you want. Optionally, you could add a pull request to contribute this feature in the main code base. @chrisgorgo could then decide whether or not to include these into the master code.

**Comment by cmadjar** [comment]
Thank you for the quick reply!

Actually, I just saw that if I specify `-ba n`, many of the fields we need are present. I see there are still a few that appear to be missing though. I'll investigate and let you know.

Thanks!

**Comment by neurolabusc** [comment]
Well spotted. If you choose `-ba n` the following tags will be populated in the BIDS JSON: SeriesInstanceUID, StudyInstanceUID, ReferringPhysicianName, StudyID, PatientName, PatientID, AccessionNumber, PatientBirthDate, PatientSex, PatientWeight.
