### ISSUE TITLE
Number of slice error

### ISSUE THREAD

**Issue by xfgavin** [rordenlab/dcm2niix#305]
Hi there,

I found dcm2niix has some problem determining number of slices per volume for some GE BOLD fieldmap data (DV26). In my case, the data is a 128*128*60*8 matrix however, dcm2niix thinks it is a 128*128*240*2 matrix.

**Comment by neurolabusc** [comment]
1. Can you confirm you are using the latest stable release ([v1.0.20190410](https://github.com/rordenlab/dcm2niix/releases))? Using "gdcmdump" or "dcmdump" might unusual features of your DICOM data. Failing that, can you send me an example that replicates the problem?

**Comment by neurolabusc** [comment]
Closing issue: unable to replicate. Recent releases convert DV26 data available [here](https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#Slice_timing_correction) and [here](https://github.com/neurolabusc/dcm_qa_nih). If problem persists, please ensure you are using the latest release, next consider looking at output of software to see if some files have been corrupted. If these do not resolve the issue, send an example dataset that replicates the issue.
