### ISSUE TITLE
Private tags to retain

### ISSUE THREAD

**Issue by michaelkain** [rordenlab/dcm2niix#310]
Dear developers of dcm2niix,

at first congratulation to your very good and widely used tool! Thank you for that!
I work for Inria in France on a Neuro-Imaging-Database called ([Shanoir](https://github.com/fli-iam/shanoir-ng)) and we use dcm2niix internally for NIfTI conversion.

Currently I work on optimizing our de-identification module of the DICOM files, where the private tags are an important point. My question now is: do you have a list of private tags,
cross-vendor, to keep for NIfTI conversion as you use them?

This would be a great help for us, as currently only the NIfTI conversion is a critical point,
when we would delete all private tags to be conform with the basic app profile of supplement 142 for de-identification.

Thank you for your time and have a nice summer,
Michael Kain

**Comment by neurolabusc** [comment]
All the DICOM tags used by dcm2niix are defined in nii_dicom.cpp. Each GROUP:ELEMENT tag is stored as a 32-bit integer, with GROUP being the lower 16-bits. An odd numbered group identifies it as a private tag. You can write a simple script to extract these. Note that some tags that can be stored as either INT32 or UINT32 use 'define', while tags that require UINT32 use an explicit type-cast. Regardless, you can write a script in your favorite language  to parse these. Classic Java does not define [UINT32](https://docs.oracle.com/javase/tutorial/java/nutsandbolts/datatypes.html), so develop your DICOM parser accordingly.

Another option would be to use [gdcmanon](http://gdcm.sourceforge.net/html/gdcmanon.html).

```
#define  kStart 0x0002+(0x0000 << 16 )
...
uint32_t kSequenceDelimitationItemTag = 0xFFFE +(0xE0DD << 16 );

```

Finally, be aware that once upon a time Siemens software did not zero the fixed length arrays used in the private CSA header. This was a particular problem for the [64 bytes reserved for each tag's name](https://nipy.org/nibabel/dicom/siemens_csa.html) - the name was zero terminated, but the subsequent bytes were not cleared. Therefore, a short name like "EchoTime" was followed by reused data. I have personally seen cases where private data was leaked into these crevices. The CSA header is very important for determining slice timing, phase encoding, post label delays, etc. Therefore, you will want to be very careful with these.

As this case illustrates, it is really hard to be perfectly confident that a complicated format like DICOM has been completely expunged of personal data. My own strategy would be to store the DICOM data privately and only publicly share simpler formats such as NIfTI, where there are fewer crevices to hide personal information.

**Comment by michaelkain** [comment]
Dear developer, thank you a lot for your very helpful answer. I will evalute an approach with the brilliant informations you gave. Have a nice day!
