### ISSUE TITLE
Why is the `ParallelReductionFactorInPlane` no longer extracted for 3D?

### ISSUE THREAD

**Issue by pvelasco** [rordenlab/dcm2niix#314]
Hi,
I'm looking at the `json` files of some anatomical sequences (both T1w and T2w) and I have noticed that the `ParallelReductionFactorInPlane` is no longer present.

Looking at the history of `nii_dicom_batch.cpp`, I found that the change was introduced in commit [`c014f25`](https://github.com/rordenlab/dcm2niix/commit/c014f251086c8b368a7e91966dcdc4ffbd969a22#diff-bd7896a7ce2642d4692df15016c231e7), but I cannot find any explanation of why 3D sequences no longer report it.

Does anybody remember why?

**Comment by neurolabusc** [comment]
Reinstated in latest development commit. I think I removed this simply because I did not think it was required for 3D files and I added ParallelReductionFactor detection for UIH data. This was reported in the dcm_qa_uih submodule. I will update the dcm_qa_uih submodule for the next stable release.
