### ISSUE TITLE
New release (v1.0.20190720)

### ISSUE THREAD

**Issue by neurolabusc** [rordenlab/dcm2niix#320]
The developmental branch has been merged with the master branch to create [the new v1.0.20190720 release](https://github.com/rordenlab/dcm2niix/releases). This release is still labelled a 'pre-release' - this label will be removed next week unless someone reports a regression. 

There are two changes that may impact tools that use dcm2niix

1. 2D slices from a 3D CT series will be merged as a single volume, even if the X-Ray exposure varies between slices. MRI scans are not influenced. To elicit the old behavior, select `-m n`.
2. There was an audit that changed some of the warning, error and messages generated. In general the output is less verbose. However, this might impact tools that expect a specific message.

**Comment by yarikoptic** [comment]
FWIW all neurodebian builds seems to pass. So uploaded this version to neurodebian

**Comment by neurolabusc** [comment]
This is still a pre-release, due to [issue 322](https://github.com/rordenlab/dcm2niix/issues/322) I would wait for the imminent stable release. Glad to hear it passes all your tests.

**Comment by neurolabusc** [comment]
This pre-release will not become a stable release due to [issue 322](https://github.com/rordenlab/dcm2niix/issues/322). Unless I hear otherwise, the current development branch version will soon become the next stable release.
