### ISSUE TITLE
PhilipsScaleSlope

### ISSUE THREAD

**Issue by caspiyaron** [rordenlab/dcm2niix#323]
Hello, 

I was wondering how does dcm2niix determine the value of the PhilipsScaleSlope field when converting dicom files from a philips MRI machine. 

When dcm2niix converts dicom files, it creates a json file with some information that was obtained from the dicom header. One of the fields in the json file is the PhilipsScaleSlope. 

When looking in the dicom header, I saw that some of the times, the value that is kept in tag: (2005, 100e) is directly equal to the value that is provided by the PhilipsScaleSlope field of the dcm2niix json file. However, in other times the two numbers differ (as was read by python - pydicom). 

Is the PhilipsScaleSlope just a copy of the value in the (2005, 100e) tag, or does dcm2niix take into account other tags and from these calculate the value of the PhilipsScaleSlope? 

Also, I was  trying to look on the PhaseEncodingAxis field. I know that the InPlanePhaseEncodingDirectionDICOM field is related to the PhaseEncodingAxis one by the transformation "COL" = "j" and "ROW" = "i" and that Philips does not keep the information regarding the +/- sign. However, in some cases (as was read by python - pydicom), the dicom header has "ROW" and the json output of dcm2niix state "j' as the PhaseEncodingAxis value. 

Do I miss something or is the conversion between the two field really that simple? 

Thanks,
Yaron Caspi

[Json_File.pdf](https://github.com/rordenlab/dcm2niix/files/3501860/Json_File.pdf)

**Comment by neurolabusc** [comment]
It is unfortunate that Philips stores different scaling factors in their DICOM header. For most MRI modalities where the intensity brightness is relative, this has no impact. However, for modalities like ASL it can have an impact. It seems different tool chains are hard wired to expect different image scaling. The NIfTI format requires a single intensity intercept and slope is chosen. Therefore, dcm2niix will choose the "Real World" values if provided. If these are not available, dcm2niix will choose either the "precise" (default) or "display" (if "-p n") value. dcm2niix will also populate the folllowing tags in the BIDS header that allow the user to select between different intensity scaling formats: "PhilipsRescaleSlope", "PhilipsRescaleIntercept", "PhilipsScaleSlope", "UsePhilipsFloatNotDisplayScaling" (where "1" indicates NIfTI uses precise value, and "0" indicates display values)., "PhilipsRWVSlope" and "PhilipsRWVIntercept".

The relevant DICOM tags are

- RS = rescale slope ([0028,1053](http://dicomlookup.com/lookup.asp?sw=Tnumber&q=(0028,1053)))
- RI = rescale intercept ([0028,1052](http://dicomlookup.com/lookup.asp?sw=Tnumber&q=(0028,1052)))
- SS = scale slope (2005,100E)
- RealWorldIntercept = (0040,9224) 
- Real World Slope = (0040,9225)

The transformation formulas are:

- R = raw value, P = precise value, D = displayed value
- D = R * RS + RI
- P = D/(RS * SS)

As you note, one can determine the phase encoding axis from [0018,1312](http://dicomlookup.com/lookup.asp?sw=Tnumber&q=(0018,1312)). See [here](https://github.com/neurolabusc/dcm_qa_nih/tree/master/Ref) for Axial DICOM/NIfTI examples of A<->P ("ROW","i") and R<->L ("COL","j") encoding. Note that 0018,1312 reports this component orthogonal to how FSL/BIDS think of it. Consider an axial scan acquired with A->P phase encoding such that the top and bottom (rows) of the image can wrap around: in this case 0018,1312 reports "COL", whereas if acquired R->L the left and right (columns) could wrap and the tag would report "ROW". The example you provide conforms to this (PhaseEncodingAxis=j, InPlanePhaseEncodingDirectionDICOM=COL). You did not provide an example that supports your suggestion that `the dicom header has "ROW" and the json output of dcm2niix state "j' as the PhaseEncodingAxis value`. I think this might occur for 3D acquisitions where dcm2niix losslessly reorients the image, but the phase encoding is typically of interest to 2D EPI sequences.

I would suggest upgrading from an old developmental release to a recent [stable release] (https://github.com/rordenlab/dcm2niix/releases)
