### ISSUE TITLE
rename _Tilted to _tilt_corrected

### ISSUE THREAD

**Issue by ASVBPREAUBV** [rordenlab/dcm2niix#324]
Is it just me or is this confusing?
The output, if the image has a gantrytilt, is not tilted anymore.

Or am i getting the naming wrong?

**Comment by neurolabusc** [comment]
In general, dcm2niix strives to losslessly convert DICOM data to NIfTI. However, most NIfTI viewers require that volumes are rectangular (e.g. VTK, any tools that use the S-Form). CT scans acquired with a gantry tilt are [rhomboidal](https://github.com/rordenlab/dcm2niix/issues/259). In this case, dcm2niix converts the raw data but also creates an interpolated rectangular copy with "_Tilt" appended to the file name. I am sorry if this is confusing. It is trying to highlight the fact that the data is interpolated. The text output generated during conversion should help clarify this.
