### ISSUE TITLE
Pixdim change from previous version

### ISSUE THREAD

**Issue by anthonysali** [rordenlab/dcm2niix#325]
Hello,

I am trying to convert a series of dicoms from a GE scanner. I first used version v1.0.20180622, which came with MRIcroGL, and the resultant nifti image had a pixdim3 value of 3.000016. When I've updated to version v1.0.20190410 it now gives me an even value of 3.  The slice thickness and spacing between slices entries are both 3 in the dicom header. I realize that these are very similar, but could you confirm if something was changed in how pixdim3 is set?

Thank you!
Anthony

**Comment by neurolabusc** [comment]
Unfortunately, distance between slices is [poorly defined in DICOM](http://dclunie.blogspot.com/2013/10/how-thick-am-i-sad-story-of-lonely-slice.html). The robust approach dcm2niix uses is to compare the Patient Position (0020,0032) of successive slices. Unfortunately, this tag stores numbers as text and is stored in low precision (in particular, by GE). This leads to rounding errors when estimating slice distance. The recent versions of dcm2niix compare interstice distance from other tags (0018,0050) and use these if this is within rounding error expected from Patient Position (0020,0032). 

In brief, this reflects a limitation of your images. You may want to lobby your GE research collaboration manager to store more precision in Patient Position (0020,0032). The old version of dcm2niix treats the values provided by GE as correct, more recent versions distrust this if it is very close to other values.

The relevant code is:

```
if ((dx > 0) && (!isSameFloatGE(dx, hdr0.pixdim[3])))
            	hdr0.pixdim[3] = dx;
```
