### ISSUE TITLE
Philips DICOM conversion "corrupted" files (XX_####)

### ISSUE THREAD

**Issue by hippocampo** [rordenlab/dcm2niix#328]
Hello,
I am hoping for some help with DCM2NIIx conversion of certain Philips DICOM files, which are reported as corrupted and interrupt the process with an error code 4.  This may be related to the XX_#### (and PS_#### files), which are identified as corrupted. I suspect this may be specifically related to a QSM data collection, I'm not sure.  Here is the DCM2NIIx code that throws the error:

//20190524: Philips MR 55.1 creates non-image files that report kDim1/kDim2 - we can detect them since 0008,0016 reports “RawDataStorage”
printError(“Conversion aborted due to corrupt file: %s %d %d\n”, fname, d.xyzDim[1], d.xyzDim[2]);

Thanks very much,
Chris

**Comment by captainnova** [comment]
@hippocampo, I think those are exam card type files, and not images. You
could check whether the PixelData tag is present.

Rob

**Comment by drmclem** [comment]
Hi
Xx and ps are auxiliary data and presentation states respectively - also XX is used to store spectrosccopy time domain data - images are always in IM_ files. The auxillary data is to allow the scan to be repeated on the philips systems and contains sufficient acquisition details and examcards to do this but are not needed for image viewing.

You should not need to check for pixel data - tag 0002,0002 should be sufficient to discriminate - the public ones are decoded correctly by dcmtk.

MR Image Storage = 1.2.840.10008.5.1.4.1.1.4
Enhanced MR Image Storage = 1.2.840.10008.5.1.4.1.1.4.1
MR Spectroscopy Storage = 1.2.840.10008.5.1.4.1.1.4.2
Secondary Capture Image Storage = 1.2.840.10008.5.1.4.1.1.7
Grayscale Softcopy Presentation State = 1.2.840.10008.5.1.4.1.1.11.1
Raw Data Storage = 1.2.840.10008.5.1.4.1.1.66

Older classic tags

Private MR Spectrum Storage = 1.3.46.670589.11.0.0.12.1
Private MR Series Data Storage = 1.3.46.670589.11.0.0.12.2
Private MR Examcard Storage = 1.3.46.670589.11.0.0.12.4

Matthew

________________________________

**Comment by drmclem** [comment]
Hi

Just to follow up on the previous post – the SOP 0002,0002 should differentiate them and any “similarity” is to allow DICOM transport to correctly route and store them.

Matthew

**Comment by hippocampo** [comment]
Hi all,
Thanks for your help on this- I just emailed Chris separately; happy to
share phantom data I just acquired (Philips, MPRAGE and QSM), and can
confirm it yields this error with the July/August 2019 dcm2niix release.
Would like to help in case others are having the same issue.
Best regards,
Chris

**Comment by captainnova** [comment]
Hi,

dcm2niix handles them perfectly well. They had coincidentally popped up as
a problem for me a couple of weeks ago, but it was in the dicom
classification and storage part of our pipeline, not dcm2niix. Both the IM
and XX files had been renamed to MR.(SOPinstanceUID), making the XX files
only stand out by being RawImages that weren't images, because they have no
pixel data. The local Phillips scientist soon confirmed that they were just
XX files, though. I agree that 0002,0002 is sufficient for separating them
out, but it's too vague to explain what they are when there's no context.

Rob

**Comment by neurolabusc** [comment]
Thanks @hippocampo for the examples. The upcoming release does fine with these.
