### ISSUE TITLE
Mojave OSX 

### ISSUE THREAD

**Issue by muschellij2** [rordenlab/dcm2niix#329]
If installing from source for OSX Mojave, please refer people to: https://stackoverflow.com/a/52900711/2549133

**Comment by neurolabusc** [comment]
Thanks, I have updated the COMPILE.md notes to reflect this. The future looks bleak for neuroimaging on MacOS, and users should consider this when making new purchases:
 - OpenGL is deprecated. This is required by many tools I use (Slicer, FreeSurfer, FSLview).
 - Terminal programs will require notarization (which requires a paid developers account even for free software and is an excessively convoluted process).
 - 32-bit executables are not supported, which prevents one from using older but useful tools.
 - Features like application sandboxing are not compatible with unenhanced DICOMs (e.g. an application will not have permission to read a 3D volume if a user drags and drops a single 2D slice from the series).

Most users at the center where I work use MacOS, but the trajectory looks grim. In the mean time, the combination of Windows 10 and Windows Subsystem for Linux (WSL) looks far more viable.
