### ISSUE TITLE
make dcm_qa*/batch.sh ignore differences in endianness (where/if expected)

### ISSUE THREAD

**Issue by yarikoptic** [rordenlab/dcm2niix#333]
follow up to #327 .

ATM the copies of batch.sh do direct binary comparison of binary files and just report when/if files are different, which could be "legit" if data stored in native endianness. So if that is expected, ideally comparison script should account for that.  external tools such as `nib-ls` or `nifti_tool` could be used to facilitate desired comparison, but I think dcm2niix might just carry/provide a simple helper.

**Comment by neurolabusc** [comment]
I would rather not add an extra dependency for other tools. Why don't you try out the latest commit to the developmental branch. One can use the argument `--big-endian n` to force dcm2niix to generate little-endian NIfTI images regardless of the operating systems native format. Inserting this line into the batch.sh scripts of the `dcm_qa` repositories should provide identical results for little and big endian compilations.

I have updated the [dcm_qa](https://github.com/neurolabusc/dcm_qa) to use this command on big-endian systems. If you are happy with this approach, the same change would be made to the other validation submodules (dcm_qa_nih, dcm_qa_uih) and these submodules will be updated on the master branch. Once I have your blessing I will update all of those submodules and update them to the master branch.

My sense is we do not report the argument `--big-endian`, it adds clutter and the only time it is relevant is when validating conversion on big-endian systems (which are currently exceedingly rare).
