### ISSUE TITLE
Long Conversion Time

### ISSUE THREAD

**Issue by dlevitas** [rordenlab/dcm2niix#342]
Hello,

I'm using the most recent version of dcm2niix (v1.0.20190902), and typically when I'm converting raw dicoms the conversion time will be quite long:
```
Conversion required 413.162163 seconds (27.180000 for core code).
```

I see that once dcm2niix begins running the time is relatively short (27.18 seconds), but the waiting period prior eats up a lot of time. I was wondering what cause this long time delay at the beginning? Is there a way to reduce this time at all?

Thanks,

Dan

**Comment by neurolabusc** [comment]
Dan

1. Perhaps you can send a more complete output that reports the number of DICOM headers that is being parsed, for example `Found 7892 DICOM file(s)` in the example below. Before dcm2niix can convert the images it must decode the headers. Unfortunately, the DICOM header is not only complex, but many of the critical numerical values are stored as ASCII, incurring the typical performance penalties. I would guess you are using data from a GE scanner, or data from a pre-XA series Siemens system where the user did not select to store EPIs as mosaics. In both cases, every single 2D slice is saved as a separate DICOM image. dcm2niix is a very fast DICOM decoder, but it still takes around 1ms per simple 2D slice.

2. You can use the argument  `--progress` argument to see performance between the stages. This will probably reveal that most of the time is spent decoding the DICOM headers. This is particularly the case for 2D DICOMs. Enhanced DICOMs from Philips and Siemens store series with one header per 4D series, while older Siemens in Mosaic mode save one header per 3D volume. 

3. Reading DICOM headers depends a lot on the speed of your disks. In general, a RAM disk or SSD will have much higher throughput than a spinning platter. I am surprised how small the proportion of time spent by the core code, so this may suggest a system or I/O bottleneck. Be aware that computer clusters tend to have very poor disk I/O (though very strong parallel compute). On many clusters, judicious use of RAM disk caching can have tremendous benefits for all stages of a Neuroimaging pipeline.

4. If you are analyzing data from different sessions or individuals, it will be much faster to process each session independently than all together. You can even run copies of dcm2niix asynchronously. These concepts are described [here](https://github.com/neurolabusc/dcm2niiXL).

5. Your comments suggest that most of the lag is in the decoding of headers. However, the GZ compression also takes a lot of time. Consider turning off compression (-z n) or see if your hardware can support parallel piped compression (-z o). 

6. For future acquisitions, if you have a Siemens scanner prior to XA10 (e.g. VB17, VE11, etc) make sure the 'mosaic' checkbox is selected for all EPI scans. If you have a GE system, lobby your research collaboration manager to support enhanced DICOM in future software releases.

```
>dcm2niix --progress y ~/GE
Chris Rorden's dcm2niiX version v1.0.20190926  Clang11.0.0 (64-bit MacOS)
Progress: 0
Found 7892 DICOM file(s)
Progress: 0.05
Progress: 0.1
Progress: 0.15
Progress: 0.2
Progress: 0.25
Progress: 0.3
Progress: 0.35
Progress: 0.4
Progress: 0.45
Progress: 0.5
Convert 56 DICOM as /Users/chris/GE/Ax_SWAN (512x512x56x1)
Warning: Unabled to compute slice times for GE multi-band. SliceOrder=-1 (seq=0, int=1)
Warning: Some images had bval>0 but bvec=0 (either Trace or b=0, see issue 245)
GE BVal scaling (e.g. 2000 -> 999.698 s/mm^2)
Convert 7632 DICOM as /Users/chris/GE/DTI (104x104x72x106)
Progress: 0.95
Convert 204 DICOM as /Users/chris/GE/MPRAGE (256x256x204x1)
Progress: 1
Conversion required 14.871178 seconds (12.048056 for core code).
```

**Comment by dlevitas** [comment]
Hi Chris,

1). Thanks for the information. I should clarified how large my data was:
```
Found 7601 DICOM file(s)
```
This data is from our Siemens Prisma scanner (software version syngo_MR_E11), so I'm unsure if there's the option to store EPIs as mosaics, but I'll check.

2). The output from dcm2niix with --progress is as follows
```
Chris Rorden's dcm2niiX version v1.0.20190902  GCC6.3.0 (64-bit Linux)
Progress: 0
Found 7601 DICOM file(s)
Progress: 0.05
Progress: 0.1
Progress: 0.15
Progress: 0.2
Progress: 0.25
Progress: 0.3
Progress: 0.35
Progress: 0.4
Progress: 0.45
Progress: 0.5
Convert 870 DICOM as /N/dc2/scratch/dlevitas/fMRI_data/std/BIDS_conversion_testing/Dan_STD/tmp_dcm2niix/sub-1036/20190610.DAN_STD_1036.10029@thwjames_Dan_STD_func_task-std_run-08_20190610141451_21 (72x72x48x870)
Progress: 0.55
Convert 208 DICOM as /N/dc2/scratch/dlevitas/fMRI_data/std/BIDS_conversion_testing/Dan_STD/tmp_dcm2niix/sub-1036/20190610.DAN_STD_1036.10029@thwjames_Dan_STD_anat_T2w_20190610141451_22 (300x320x208x1)
Slices not stacked: orientation varies (vNav or localizer?) [1 0 0 0 0 -1] != [0 1 0 0 0 -1]
Warning: Slice timing appears corrupted (range 0..0, TR=20 ms)
Convert 1 DICOM as /N/dc2/scratch/dlevitas/fMRI_data/std/BIDS_conversion_testing/Dan_STD/tmp_dcm2niix/sub-1036/20190610.DAN_STD_1036.10029@thwjames_Dan_STD_anat-scout_acq-localizer_20190610141451_1_i00002 (192x192x1x1)
Warning: Check that 2D images are not mirrored.
Warning: Slice timing appears corrupted (range 0..0, TR=20 ms)
Convert 1 DICOM as /N/dc2/scratch/dlevitas/fMRI_data/std/BIDS_conversion_testing/Dan_STD/tmp_dcm2niix/sub-1036/20190610.DAN_STD_1036.10029@thwjames_Dan_STD_anat-scout_acq-localizer_20190610141451_1_i00001 (192x192x1x1)
Warning: Check that 2D images are not mirrored.
Warning: Slice timing appears corrupted (range 0..0, TR=20 ms)
Warning: Weird CSA 'ProtocolSliceNumber' (System/Miscellaneous/ImageNumbering reversed): VALIDATE SLICETIMING AND BVECS
Convert 1 DICOM as /N/dc2/scratch/dlevitas/fMRI_data/std/BIDS_conversion_testing/Dan_STD/tmp_dcm2niix/sub-1036/20190610.DAN_STD_1036.10029@thwjames_Dan_STD_anat-scout_acq-localizer_20190610141451_1_i00003 (192x192x1x1)
Warning: Check that 2D images are not mirrored.
Convert 870 DICOM as /N/dc2/scratch/dlevitas/fMRI_data/std/BIDS_conversion_testing/Dan_STD/tmp_dcm2niix/sub-1036/20190610.DAN_STD_1036.10029@thwjames_Dan_STD_func_task-std_run-05_20190610141451_15 (72x72x48x870)
Progress: 0.6
Convert 1 DICOM as /N/dc2/scratch/dlevitas/fMRI_data/std/BIDS_conversion_testing/Dan_STD/tmp_dcm2niix/sub-1036/20190610.DAN_STD_1036.10029@thwjames_Dan_STD_func_task-std_run-05_20190610141451_14 (72x72x48x1)
Convert 870 DICOM as /N/dc2/scratch/dlevitas/fMRI_data/std/BIDS_conversion_testing/Dan_STD/tmp_dcm2niix/sub-1036/20190610.DAN_STD_1036.10029@thwjames_Dan_STD_func_task-std_run-03_20190610141451_11 (72x72x48x870)
Progress: 0.65
Convert 870 DICOM as /N/dc2/scratch/dlevitas/fMRI_data/std/BIDS_conversion_testing/Dan_STD/tmp_dcm2niix/sub-1036/20190610.DAN_STD_1036.10029@thwjames_Dan_STD_func_task-std_run-04_20190610141451_13 (72x72x48x870)
Progress: 0.7
Convert 1 DICOM as /N/dc2/scratch/dlevitas/fMRI_data/std/BIDS_conversion_testing/Dan_STD/tmp_dcm2niix/sub-1036/20190610.DAN_STD_1036.10029@thwjames_Dan_STD_func_task-std_run-01_20190610141451_6 (72x72x48x1)
Convert 1 DICOM as /N/dc2/scratch/dlevitas/fMRI_data/std/BIDS_conversion_testing/Dan_STD/tmp_dcm2niix/sub-1036/20190610.DAN_STD_1036.10029@thwjames_Dan_STD_func_task-std_run-06_20190610141451_16 (72x72x48x1)
Convert 870 DICOM as /N/dc2/scratch/dlevitas/fMRI_data/std/BIDS_conversion_testing/Dan_STD/tmp_dcm2niix/sub-1036/20190610.DAN_STD_1036.10029@thwjames_Dan_STD_func_task-std_run-06_20190610141451_17 (72x72x48x870)
Progress: 0.8
Convert 1 DICOM as /N/dc2/scratch/dlevitas/fMRI_data/std/BIDS_conversion_testing/Dan_STD/tmp_dcm2niix/sub-1036/20190610.DAN_STD_1036.10029@thwjames_Dan_STD_func_task-std_run-08_20190610141451_20 (72x72x48x1)
Convert 3 DICOM as /N/dc2/scratch/dlevitas/fMRI_data/std/BIDS_conversion_testing/Dan_STD/tmp_dcm2niix/sub-1036/20190610.DAN_STD_1036.10029@thwjames_Dan_STD_fmap_run-01_20190610141451_4 (64x64x48x3)
Convert 208 DICOM as /N/dc2/scratch/dlevitas/fMRI_data/std/BIDS_conversion_testing/Dan_STD/tmp_dcm2niix/sub-1036/20190610.DAN_STD_1036.10029@thwjames_Dan_STD_anat_T1w_20190610141451_3 (300x320x208x1)
Convert 870 DICOM as /N/dc2/scratch/dlevitas/fMRI_data/std/BIDS_conversion_testing/Dan_STD/tmp_dcm2niix/sub-1036/20190610.DAN_STD_1036.10029@thwjames_Dan_STD_func_task-std_run-01_20190610141451_7 (72x72x48x870)
Progress: 0.85
Convert 3 DICOM as /N/dc2/scratch/dlevitas/fMRI_data/std/BIDS_conversion_testing/Dan_STD/tmp_dcm2niix/sub-1036/20190610.DAN_STD_1036.10029@thwjames_Dan_STD_fmap_run-02_20190610141451_5 (64x64x48x3)
Convert 1 DICOM as /N/dc2/scratch/dlevitas/fMRI_data/std/BIDS_conversion_testing/Dan_STD/tmp_dcm2niix/sub-1036/20190610.DAN_STD_1036.10029@thwjames_Dan_STD_func_task-std_run-03_20190610141451_10 (72x72x48x1)
Convert 870 DICOM as /N/dc2/scratch/dlevitas/fMRI_data/std/BIDS_conversion_testing/Dan_STD/tmp_dcm2niix/sub-1036/20190610.DAN_STD_1036.10029@thwjames_Dan_STD_func_task-std_run-02_20190610141451_9 (72x72x48x870)
Progress: 0.9
Convert 870 DICOM as /N/dc2/scratch/dlevitas/fMRI_data/std/BIDS_conversion_testing/Dan_STD/tmp_dcm2niix/sub-1036/20190610.DAN_STD_1036.10029@thwjames_Dan_STD_func_task-std_run-07_20190610141451_19 (72x72x48x870)
Progress: 0.95
Convert 1 DICOM as /N/dc2/scratch/dlevitas/fMRI_data/std/BIDS_conversion_testing/Dan_STD/tmp_dcm2niix/sub-1036/20190610.DAN_STD_1036.10029@thwjames_Dan_STD_func_task-std_run-07_20190610141451_18 (72x72x48x1)
Convert 208 DICOM as /N/dc2/scratch/dlevitas/fMRI_data/std/BIDS_conversion_testing/Dan_STD/tmp_dcm2niix/sub-1036/20190610.DAN_STD_1036.10029@thwjames_Dan_STD_anat_T1w_20190610141451_2 (300x320x208x1)
Progress: 1
Convert 1 DICOM as /N/dc2/scratch/dlevitas/fMRI_data/std/BIDS_conversion_testing/Dan_STD/tmp_dcm2niix/sub-1036/20190610.DAN_STD_1036.10029@thwjames_Dan_STD_func_task-std_run-04_20190610141451_12 (72x72x48x1)
Convert 1 DICOM as /N/dc2/scratch/dlevitas/fMRI_data/std/BIDS_conversion_testing/Dan_STD/tmp_dcm2niix/sub-1036/20190610.DAN_STD_1036.10029@thwjames_Dan_STD_func_task-std_run-02_20190610141451_8 (72x72x48x1)
Conversion required 77.170538 seconds (24.379999 for core code).
```

3). Ah yes, I've been running this on my university's HPC. Are there any general recommendations for use of RAM, or is that something that needs to be discussed with the IT people?

4). This is just a single session, but in the future I'll give dcm2niiXL a harder look.

5). Turning off all compression (-z n) definitely seemed to help a bit
```
Conversion required 77.170538 seconds (24.379999 for core code).
```
but it still took longer than in your example with 7892 DICOMS found. 

6). I'll have to ask our MRI physicist about this, since I'm not sure what we have.

**Comment by neurolabusc** [comment]
1. Your data is already in mosaic format: 870-volume fMRI saved as 870 3D DICOMs rather than 41760 2D volumes.

2. I suspect most of your poor speed relates to the HPC I/O. You can test by copying this to a local machine (e.g. the numbers I gave were the SSD of a basic laptop). As noted [here](https://github.com/neurolabusc/dcm2niiXL), the mode '-z y' will be slower on I/O constrained HPC systems than either '-z i' (internal, single thread) or '-z o' (multiple-threads piped). I would chat with your local HPC team, but it is clear that your situation is constrained by disk I/O. This will also likely impact all other tools in your pipeline, so coming up with a strategy for your hardware will have massive gains. Rather than dealing with one stage at a time, you probably want to think about your pipeline holistically.
