### ISSUE TITLE
Fail to convert MR images with maximum voxel value > 4095

### ISSUE THREAD

**Issue by cwying** [rordenlab/dcm2niix#343]
Hello,

I'm using dcm2niix to convert some dicom from Siemens to NIFTI. The dicom data was in 16-bit and the maximum voxel intensity can be very large (as large as 2^15 -1). When converting to nii.gz using the newest version of dcm2niix, the software seems to give 12-bit output and the value will be capped at 4095, so those voxels with high values won't be converted correctly. The older version I was using (last modification date 7/26/2017) worked perfectly fine. I was wondering whether there is any way to fix it. 

Thanks a lot,
Chunwei

**Comment by neurolabusc** [comment]
1.) Can you confirm you are using the latest [release (v1.0.20190902)](https://github.com/rordenlab/dcm2niix/releases)? Every commit of dcm2niix is tested for accurate conversion of UINT16 data, e.g. [dcm_qa](https://github.com/neurolabusc/dcm_qa/tree/master/Ref]). The FSL functions below show that the image is saved as UINT16 and uses most of the precision provided by the UINT16 data type:
 
```
>fslhd noPF_noPAT_100POS_PEres100_ES0p59_BW2222_PA_15.nii
size of header	348
data_type	UINT16
...
scl_slope	1.000000
scl_inter	0.000000
...
>fslstats noPF_noPAT_100POS_PEres100_ES0p59_BW2222_PA_15.nii -R
0.000000 55843.000000 
```

With regards to your images:
 1. You may want to use fslhd and fslstats to inspect your data. In other words, if you have a scaled range of 0..4095 but the scleras_slope is 0.1, then the raw intensity is 0..40950. Be aware that some Siemens scans like FieldMaps use this trick, e.g. 4095 is equal to pi.
 2. Some sequences (e.g. CMRR) allow you to set a calibration scaling factor. If this is set too low, you will not get full precision, if it is set to high your will get clipping of the brightest values. The default tends to be fine for the standard usage, but if you change the coil used or drastically change the sequence, you may want to adjust that value.

If these suggestions do not resolve your issue, feel free to send me a sample (email is shown in my avatar) via Box, DropBox or GoogleDrive.

**Comment by neurolabusc** [comment]
Was this a DICOM image generated by Siemens or was it generated locally? If the former, please contact Siemens as this is a violation of the DICOM standard and is likely to cause issues with many tools.

**Comment by cwying** [comment]
It was generated by the scanner, and the scan was done several years ago. We will contact Siemens for it. Thanks a lot.
