### ISSUE TITLE
Occasional errors when converting scans with variable interslice distance

### ISSUE THREAD

**Issue by stilley2** [rordenlab/dcm2niix#347]
I've noticed occasional failures when converting localizing scans. I think the issue is that these scans have variable interslice distance, and therefore enter [this conditional](https://github.com/rordenlab/dcm2niix/blob/f54be46667fce7994d2062e2623d12253c1bd968/console/nii_dicom_batch.cpp#L4663). Here, sliceMMarray is allocated, but only intialized if opts.isVerbose is true. Because sliceMMarray is initialized, nii_saveNII3Deq is called (assuming dcmList[indx0].isResampled is False). This function access sliceMMarray, which may be uninitialized, causing errors.

**Comment by neurolabusc** [comment]
Well spotted. Can you validate that the latest commit to the developmental branch resolves this issue? I have also created a new repository [dcm_qa_ct](https://github.com/neurolabusc/dcm_qa_ct) for regression testing.

**Comment by stilley2** [comment]
That seems to have done the trick! Thanks
