### ISSUE TITLE
DTI dicom to nii probem

### ISSUE THREAD

**Issue by Suradech164** [rordenlab/dcm2niix#348]
Hello Everyone,

I am having a problem with converting spinal cord DTI dicom to nii. Even though we have the same parameters and sequence and same scanner: some cases have dicom dti file display as one stack images (260 images) but some case have dicom dti display as mosaic images (5x4) 13 images. When I use MRICroGL with newest version of dicom2niix the result are look like the attached images below...
1. stack dicom (260 images) has Warning: 0008,0008=MOSAIC but number of slices not specified and the nii display looks strange attached...
![Slide1](https://user-images.githubusercontent.com/49734817/67148308-72ec7680-f26c-11e9-8719-b59407dbf283.JPG)

2. mosaic 5x4 (13 images) has Warning: Mosaic inferred without CSA header (check number of slices and spatial orientation)... the nii display look ok but not sure if it is correct...

![Slide2](https://user-images.githubusercontent.com/49734817/67148312-77b12a80-f26c-11e9-93ce-9fe20d79d39c.JPG)

I am not sure which one is correct. Have any one experience this issues? How to solve this?
Thank you for your help.

**Comment by neurolabusc** [comment]
I assume your data are from a Siemens scanner. If they are from an Siemens XA system you must never save images as mosaic, as these are for display purposes only and do not contain information critical for analysis (in fact, they are not valid DICOM images at all). More likely, you data is from a Siemens A..E series system (e.g. E11C). In this case, you need to check the providence of your images and convert a copy before the [CSA header](https://nipy.org/nibabel/dicom/siemens_csa.html) has been stripped off. I suspect your images went through an anonymization stage that removed the critical CSA tags. Without the CSA header, the images no longer contain the details required to process your diffusion data. This is not a limitation of dcm2niix, but a reflection that your DICOM images are lacking vital details. Other details that will be unavailable are:

```
SliceNormalVector
DiffusionGradientDirection
SliceMeasurementDuration
BandwidthPerPixelPhaseEncode
NumberOfImagesInMosaic
PhaseEncodingDirectionPositive
SliceTiming
```

While dcm2niix might be able to guess the number of images in mosaic, the other crucial details can not be inferred. You need to get images that include this rich meta data.

**Comment by neurolabusc** [comment]
A basic step if you are having problems converting a DICOM image is to look at the DICOM header. You can use a graphical tool like Horos, or a command line tool like dcmdump or gdcmdump to view the full header. However, since you are hoping to use dcm2niix to convert your images, it is often useful to run dcm2niix in logorrheic verbose mode (`-v 2`). This will show you precisely how dcm2niix parses your header. Since this mode is so verbose, I tend to apply it to a single image (`-s y`) and run in internal mode (`-b i`) where no BIDS or NIfTI files are created (since I only want to examine the DICOM header). Here is an example for a Siemens EPI image in mosaic mode from the [dcm_qa_nih](https://github.com/neurolabusc/dcm_qa_nih) repository:

```
dcm2niix -s y -b i -v 2  ./epi_pe_ap-00001.dcm
Chris Rorden's dcm2niiX version v1.0.20191018  Clang11.0.0 (64-bit MacOS)
 0002,0000 4@140 UL 212 
 0002,0001 2@156 OB 
 0002,0002 26@166 UI  1.2.840.10008.5.1.4.1.1.4
 0002,0003 52@200 UI  1.3.12.2.1107.5.2.19.45160.2018091812250026676990470
 0002,0010 20@260 UI  1.2.840.10008.1.2.1
 0002,0012 28@288 UI  1.2.276.0.7230010.3.0.3.6.0
 0002,0013 16@324 SH  OFFIS_DCMTK_360
 0002,0016 8@348 AE  AWP45160
 0008,0005 10@364 CS  ISO_IR_100
 0008,0008 36@382 CS  ORIGINAL_PRIMARY_M_ND_ECHO_00_MOSAIC
 0008,0012 8@426 DA  20180918
 0008,0013 14@442 TM  122503.073000
 0008,0016 26@464 UI  1.2.840.10008.5.1.4.1.1.4
 0008,0018 52@498 UI  1.3.12.2.1107.5.2.19.45160.2018091812250026676990470
 0008,0020 8@558 DA  20180918
 0008,0021 8@574 DA  20180918
 0008,0022 8@590 DA  20180918
 0008,0023 8@606 DA  20180918
 0008,0030 14@622 TM  121229.940000
 0008,0031 14@644 TM  122503.070000
 0008,0032 14@666 TM  122458.102500
 0008,0033 14@688 TM  122503.073000
 0008,0050 0@710 SH  
 0008,0060 2@718 CS  MR
 0008,0070 8@728 LO  SIEMENS
 0008,0080 4@744 LO  NIH
 0008,0081 68@756 ST  10_Center_Drive_Building_10_Room_B1D307_Bethesda--_Maryland_US_20
 0008,0090 0@832 PN  
 0008,1010 8@840 SH  AWP45160
 0008,1030 8@856 LO  FMRIF_QA
 0008,103e 10@872 LO  EPI_PE=AP
 0008,1040 10@890 LO  FMRIF_3TD
 0008,1050 0@908 PN  
 0008,1090 6@916 LO  Skyra
...
 0018,1020 12@2124 LO  syngo_MR_E11
...
 0028,1051 4@2986 DS  1179
 0028,1055 6@2998 LO  Algo1
 0029,0010 18@3012 LO  SIEMENS_CSA_HEADER
 0029,0011 22@3038 LO  SIEMENS_MEDCOM_HEADER2
 0029,1008 12@3068 CS  IMAGE_NUM_4
 0029,1009 8@3088 LO  20180918
   100 CSA of EchoLinePosition 6
   292 CSA of EchoColumnPosition 6
   484 CSA of EchoPartitionPosition 6
   676 CSA of UsedChannelMask 0
   760 CSA of UsedChannelString 6
   976 CSA of Actual3DImaPartNumber 0
   1060 CSA of ICE_Dims 6
   1268 CSA of B_value 0
   1352 CSA of Filter1 0
   1436 CSA of Filter2 0
   1520 CSA of ProtocolSliceNumber 6
   1712 CSA of RealDwellTime 6
   1904 CSA of PixelFile 0
   1988 CSA of PixelFileName 0
   2072 CSA of SliceMeasurementDuration 6
   2268 CSA of SequenceMask 6
   2460 CSA of AcquisitionMatrixText 6
   2648 CSA of MeasuredFourierLines 6
   2840 CSA of FlowEncodingDirection 0
   2924 CSA of FlowVenc 0
   3008 CSA of PhaseEncodingDirectionPositive 6
   3200 CSA of NumberOfImagesInMosaic 6
   3392 CSA of DiffusionGradientDirection 0
   3476 CSA of ImageGroup 0
   3560 CSA of SliceNormalVector 6
   SliceNormalVector 0.000000 0.000000 1.000000
   3776 CSA of DiffusionDirectionality 0
   3860 CSA of TimeAfterStart 6
   4052 CSA of FlipAngle 0
   4136 CSA of SequenceName 0
   4220 CSA of RepetitionTime 0
   4304 CSA of EchoTime 0
   4388 CSA of NumberOfAverages 0
   4472 CSA of VoxelThickness 0
   4556 CSA of VoxelPhaseFOV 0
   4640 CSA of VoxelReadoutFOV 0
   4724 CSA of VoxelPositionSag 0
   4808 CSA of VoxelPositionCor 0
   4892 CSA of VoxelPositionTra 0
   4976 CSA of VoxelNormalSag 0
   5060 CSA of VoxelNormalCor 0
   5144 CSA of VoxelNormalTra 0
   5228 CSA of VoxelInPlaneRot 0
   5312 CSA of ImagePositionPatient 0
   5396 CSA of ImageOrientationPatient 0
   5480 CSA of PixelSpacing 0
   5564 CSA of SliceLocation 0
   5648 CSA of SliceThickness 0
   5732 CSA of SpectrumTextRegionLabel 0
   5816 CSA of Comp_Algorithm 0
   5900 CSA of Comp_Blended 0
   5984 CSA of Comp_ManualAdjusted 0
   6068 CSA of Comp_AutoParam 0
   6152 CSA of Comp_AdjustedParam 0
   6236 CSA of Comp_JobID 0
   6320 CSA of FMRIStimulInfo 0
   6404 CSA of FlowEncodingDirectionString 0
   6488 CSA of RepetitionTimeEffective 0
   6572 CSA of CsiImagePositionPatient 0
   6656 CSA of CsiImageOrientationPatient 0
   6740 CSA of CsiPixelSpacing 0
   6824 CSA of CsiSliceLocation 0
   6908 CSA of CsiSliceThickness 0
   6992 CSA of OriginalSeriesNumber 0
   7076 CSA of OriginalImageNumber 0
   7160 CSA of ImaAbsTablePosition 6
   7376 CSA of NonPlanarImage 6
   7568 CSA of MoCoQMeasure 0
   7652 CSA of LQAlgorithm 0
   7736 CSA of SlicePosition_PCS 6
   7960 CSA of RBMoCoTrans 0
   8044 CSA of RBMoCoRot 0
   8128 CSA of MultistepIndex 6
   8320 CSA of ImaRelTablePosition 6
   8536 CSA of ImaCoilString 6
   8724 CSA of RFSWDDataType 6
   8916 CSA of GSWDDataType 6
   9108 CSA of NormalizeManipulated 0
   9192 CSA of ImaPATModeText 0
   9276 CSA of B_matrix 0
   9360 CSA of BandwidthPerPixelPhaseEncode 6
   9552 CSA of FMRIStimulLevel 0
   9636 CSA of FmriConditionsDataSequence 0
   9720 CSA of FmriResultSequence 0
   9804 CSA of MosaicRefAcqTimes 6
   sliceTimes 0	1450	482.5	1932.5	967.5	
   10060 CSA of AutoInlineImageFilterEnabled 0
   10144 CSA of QCData 0
   10228 CSA of ExamLandmarks 0
   10312 CSA of ExamDataRole 0
   10396 CSA of MRDiffusion 0
   10480 CSA of RealWorldValueMapping 0
   10564 CSA of PhaseContrastN4 0
   10648 CSA of MRVelocityEncoding 0
   10732 CSA of VelocityEncodingDirectionN4 0
   10816 CSA of ImageType4MF 0
   10900 CSA of VolumetricProperties4MF 0
   10984 CSA of MorphoQCThreshold 0
   11068 CSA of MorphoQCIndex 0
   11152 CSA of ImageHistory 6
   11376 CSA of MR_ASL 0
   11460 CSA of Distorcor_IntensityCorrection 0
   11544 CSA of UserDefinedImage 0
 0029,1010 11548@3108 OB <11548 bytes> 
...
```
A few things we can see from this dataset:
- Transfer Syntax (0002,0010) reports this is an uncompressed [Explicit VR Little Endian](https://www.dicomlibrary.com/dicom/transfer-syntax/) image.
- ImplementationVersionName (0002,0013) reports the image was created by [OFFIS_DCMTK_360](https://dicom.offis.de/dcmtk.php.en).
- Tags 0008,0070, 0008,1090, and 0018,1020 reveal this image was created on a Siemens Skyra running E11 software.
 - 0008,0008 reveals that this is a mosaic image
- The [CSA Image Header Info](https://nipy.org/nibabel/dicom/siemens_csa.html) 0029,1010 provides rich information about this sequence (indeed, only details from the binary portion are printed, more data is often in the ASCII portions).

I think this makes it clear how important the CSA header is to handling Siemens mosaic data.

**Comment by Suradech164** [comment]
Thank you so much for you reply. To summerize as I understand from your reply, there is no way to correctly convert Mosaic format to Nii if CSA have been removed but we can check for the CSA and heading... Am I correct?

**Comment by neurolabusc** [comment]
In brief, if the CSA header is removed from the DICOM file (e.g. anonymization removes this tag) the resulting dataset is impoverished and many of the details required for subsequent processing are lost. Often, the number of slices in the mosaic can not be inferred if the CSA header is missing.

For completeness, dcm2niix has several strategies for guessing the number of images in the mosaic if the CSA header is missing. As I noted previously, even if the number of slices can be inferred, many of the crucial parameters required for subsequent processing are still missing.
 - The number of slices can be determined if the tag numberOfImagesInMosaic 0019,100A is present.
 - The number of slices can be determined if the tag slice times (0019,1029) is present.
 - The number of slices can be guessed if the image is not interpolated, and the full dimensions are evenly divisible by the phaseEncodingLines or phaseEncodingSteps. This guess is not precise: it does not distinguish between a 7x7 mosaic with 49 slices from one with just 43 slices. This error will result in the origin not precisely identifying the isocenter origin. Hopefully subsequent coregistration can resolve this.
