### ISSUE TITLE
bvec/bval files for diffusion scan with containing a single b0 volume?

### ISSUE THREAD

**Issue by akhanf** [rordenlab/dcm2niix#352]
Hello,

I have Siemen's Prisma scans where one series is a dwi volume but only containing a single b0 (non-diffusion-weighted image). The current behaviour is to not generate a bval/bvec (would be something like 0;  0,0,0; if created), but wondering if this is the desired behaviour? The specific use case here is when acquiring a negative phase encode direction image for top-up but saving time by not repeating the entire gradient table. 

Thanks,
Ali

**Comment by neurolabusc** [comment]
Why don't you try the latest developmental commit (v1.0.20191031). If the DICOM image type (0008,0008) reports the data is `DIFFUSION`, there is no evidence that the data is derived (FA, TRACE, etc), and no diffusion gradients are reported the software will assume this is a B=0 series and create zero-filled bval and bvec files. 

This may have unintended consequences. For example, a user may adapt a SE-EPI sequence to undistort GE-EPI resting state or fMRI series (using [TOPUP](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/topup)). If the image type for this SE-EPI sequence retains `DIFFUSION`, then bval and bvec files will be generated.

Likewise, if your intention is to have a B=0 sequence, and you build this from a SE-EPI sequence that does not label the series as `DIFFUSION` then bval/bvec files will not be generated. You will want to build a script that generates these - here is [mine](https://github.com/rordenlab/spmScripts/blob/b0d8001ae97e28e662f2052751669bdb7e4bc68e/nii_merge_dti.m).

As a final comment, if you have a Siemens research agreement, I would strongly encourage you to generate an [optimal](http://www.emmanuelcaruyer.com/q-space-sampling.php) set of gradients with B=0 images embedded ([perhaps 1/16](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/eddy#If_you_haven.27t_already_acquired_your_data)). Be aware that the Siemens product directions are half-sphere which are [not optimal for Eddy correction](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/eddy#eddy_--_a_tool_for_correcting_eddy_currents_and_movements_in_diffusion_data). Further comments on DWI are provided [here](https://www.mccauslandcenter.sc.edu/crnl/tools/advanced-dti) and [here](https://osf.io/brvak/wiki/home/).

**Comment by akhanf** [comment]
In my case the DICOM image type tag is still `DIFFUSION`, so this commit should generate the bval/bvec files, will test that out now -- 

Thanks also for the script, my plan was to do just that if this couldn't be amended here.

As for those unintended consequences, it seems rare to me that someone would build from a diffusion sequence rather than from the EPI they were already using for bold, but yes that could happen..

Yes we are using custom-generated gradient tables with full-sphere coverage and b0's intermittently embedded, and if there is time we repeat that entire scan for the negative phase encode, but for time-restricted protocols we are just doing a single b0 in the negative phase encode.

**Comment by akhanf** [comment]
I tried the latest commit, but doesn't generate bvec/bval, I believe because the b-value is not exactly zero (b-value = 5).. If this is looking like more of an esoteric case, I am happy to just use a post-hoc correction to add the bval/bvec when needed.

**Comment by neurolabusc** [comment]
Typical BOLD sequences are GE-EPI. For un-distorting BOLD data with TOPUP (rather than FUGUE) one acquires SE-EPI images with both blip directions. The SE-EPI images have the spatial distortion of the GE-EPI images, but hopefully minimize the signal loss (e.g. the signal location is moved but not lost).

The rational is described [here](https://humanconnectome.org/storage/app/media/documentation/s1200/HCP_S1200_Release_Appendix_I.pdf):

> The BOLD_{RL,LR}_SB_SE scans are single-band spin- echo EPI variants (available in the same multiband sequence package) that provide a mechanism for correcting for susceptibility distortion via FSL’s ‘TOPUP’ tool. These scans are preferred to a traditional gradient-echo fieldmap approach because they allow matching (and subsequent correction) of z-gradient-blip-induced spatial distortions that are present in the multiband fMRI acquisitions (see Glasser et al., submitted). These scans were renamed to SpinEchoFieldMap_{RL,LR} in the ConnectomeDB.

The commit I submitted works with our Prisma data. In reality "B=0" images with a low but non-zero b-value. Some sequences save the applied b-value while others save the specified value. Can you send me a sample of your images via box, dropbox or google drive to me directly (email in my avatar).

**Comment by akhanf** [comment]
works like a charm, thank you very much!!
