### ISSUE TITLE
incomplete acquisitions (scan stopped early)

### ISSUE THREAD

**Issue by pcklink** [rordenlab/dcm2niix#357]
Is there a way to deal with incomplete acquisitions (scans that were stopped before their planned end) when converting dicoms to nifti files? The problem is that the volume during which the scan is stopped (Philips) is incomplete which means that the total number of slices is not an integer multiple of the number of slices per volume. When I convert the dicoms with dcm2niix, I do get a warning about this issue, but dcm2niix still converts the dicoms to a nifti file. This file however, cannot be read.

I can of course manually check the slice numbers in the dicom filenames and delete the dicom images from the incomplete volume before running dcm2niix, but this is a bit involved and I have a feeling that there must be a way to handle this situation more easily. I don’t see an option in dcm2niix that will solve this for me but maybe I’m missing something.

If there are other obvious (automated) solutions, they are very welcome as well.

**Comment by pcklink** [comment]
Example:
`$ dcm2niix -b y -f %p_%s_%t -o ./ ./scan19`
`Chris Rorden's dcm2niiX version v1.0.20190902 (JP2:OpenJPEG) GCC7.3.0 (64-bit Linux)`
`Found 6793 DICOM file(s)`
`Slice positions repeated, but number of slices (6793) not divisible by number of repeats (165): missing images?`
`Hint: expected 41 locationsWarning: Interslice distance varies in this volume (incompatible with NIfTI format).`
`Warning: Missing images? Expected 6793 images, but instance number (0020,0013) ranges from 1 to 8565`
`Warning: Unable to determine slice direction: please check whether slices are flipped Philips Scaling Values RS:RI:SS = 21.7915:0:0.124764 (see PMC3998685) Convert 6793 DICOM as ./task-xxx_run-03_func-bold_1901_20191114094227 (240x240x6793x1)`
`Compress: "/usr/bin/pigz" -b 960 -n -f -6 "./task-xxx_run-03_func-bold_1901_20191114094227.nii"
Unable to equalize slice distances: slice order not consistently ascending. Recompiling with '-DmyInstanceNumberOrderIsNotSpatial' might help.`

With this info I can manually fix it by taking the mod of the number of slices and the number of repeats, then deleting the last n slice dicoms and rerunning dcm2niix. I suppose I could somehow script this procedure.

What would `Recompiling with '-DmyInstanceNumberOrderIsNotSpatial'` do and how would I do that?

**Comment by pcklink** [comment]
I have tried to compile dcm2niix by downloading from the repo and doing:
`mkdir build && cd build`
`cmake -DmyInstanceNumberOrderIsNotSpatial=ON ..`
`make`

But it tells me:
`CMake Warning:
Manually-specified variables were not used by the project:

MYINSTANCENUMBERORDERISNOTSPATIAL`

so I guess I'm doing it wrong. It does compile and `dcm2niix` is usable, but functionality is (of course) exactly the same as my pre-existing version.

**Comment by pcklink** [comment]
I now wrote a little python script to do this for me, but would still be interested to learn whether it's possible directly with dcm2nii.

**Comment by neurolabusc** [comment]
1. Can you share your python script - I suspect others would find it useful. It is unfortunate that Philips increments instance number to cluster all slices of the same position next to each other, such that instances 1,2,3,...n are the first slice for all time points and n+1.,n+2... the second slice. This is legal with DICOM, but since Philips does not explicitly store volume number (at least with the DWI series I have seen) it does make any solution a kludge. Fortunately, Philips enhanced DICOMs should help resolve this for future datasets.

2. For future reference, [notes for compiling are here](https://github.com/rordenlab/dcm2niix/blob/master/COMPILE.md). The cmake scripts are for super builds, and I prefer using the command `make` in the console folder for simple compiles, so a basic compile would look like this
```
g++ -I.  main_console.cpp nii_foreign.cpp nii_dicom.cpp jpg_0XC3.cpp ujpeg.cpp nifti1_io_core.cpp nii_ortho.cpp nii_dicom_batch.cpp  -o dcm2niix -DmyDisableOpenJPEG -DmyInstanceNumberOrderIsNotSpatial
```

**Comment by pcklink** [comment]
The script can be found here: https://github.com/VisionandCognition/NHP-Process-MRI/blob/master/python/fix_dcm_incompletevols.py

It uses the `pydicom` python package (https://pydicom.github.io/ ) to get the ‘Temporal Position Identifier’ for each dcm file, then identifies the incomplete volume and separates the corresponding dcm files from those belonging to complete volumes.

Running dcm2niix on the cleaned up dataset gives a correct nifti file.

**Comment by neurolabusc** [comment]
Nice. @drmclem is there any chance that Philips could include some incremented volume number in the DWI datasets, similar to the [Temporal Position Identifier(0020,0100)](https://dicom.innolitics.com/ciods/mr-image/mr-image/00200100) found in fMRI time series? This would allow us to generalize the method @pcklink uses.

**Comment by drmclem** [comment]
Hi

Not really sure what is needed to process aborted scans - for the fMRI type we would normally suggest fix this on the scanner (you can trim the data set in patient adminsitration before export to ensure it is consistent) and for fMRI this makes sense. But for aborted DWI scans ? given the readout order may be scrambeled for maximum temporal separation (and perhaps even thermal load) - then I can't really see how to guarantee that the data is usable as a block. The main problem is one of consistency - for fMRI you end up with certain slices having, eg, 66 slices and some 67 depending on when the scanner was stopped.

But for DWI - you would need to generate separate bVector tables potentially for each slice.

I would suggest that any fix would be a major cludge.

Matthew

**Comment by pcklink** [comment]
I did not know I could trim runs this at the scanner as well. I'll look into that to see how straightforward it is. Would be a nicer solution actually.

**Comment by drmclem** [comment]
Hi - this is obviously Philips specific - so apologies if not appropriate for the list,

If you are able to load the data back on the scanner (I.e. you still have the DICOMDIR file), or if you do abort a scan you can see in the patient administration the problem

![image](https://user-images.githubusercontent.com/35807311/69137485-c4c72d00-0ab4-11ea-9efe-f269bc91540b.png)

The total slices (9970) does not equal Dynamics (290) x slices (35) = 10150.
You can trim the data set by double clicking on the data set and bringing up the edit menu

![image](https://user-images.githubusercontent.com/35807311/69137517-d6103980-0ab4-11ea-80d8-3d7746340433.png)

And set the dynamic range to the correct value (I.e. the last complete dynamic collected). In this case 284 – change the dynamic entry to 1-284 and use “KEEP”

After this the data set contains 9940 slices (which is a multiple of 35) and you can re-export it and the conversion tools should be happier.

Matthew

**Comment by pcklink** [comment]
Sweet. That solves everything at the source! Thanks for explaining! Too bad I did not know about this earlier...

**Comment by neurolabusc** [comment]
@drmclem I think your comments are appropriate and extremely helpful. Latest commit includes a few new features:
 - Philips/README.md describes issue and solutions (linking to this issue).
 - FILENAMING.md describes how temporal position (0020,0100) can be inserted into the filename, providing a simple method to rename DICOMs and remove partial volumes by hand.
 - [dcm_qa_philips[https://github.com/neurolabusc/dcm_qa_philips] now includes a sample fMRI dataset. This provides a nice open source dataset for testing automated solution (e.g. future version of dcm2niix).

**Comment by Arslan1881** [comment]
Hello,

I get a similar error when trying to convert my DICOM to Nifti in MRIcroGL

Found 2048 DICOM file(s)
DICOM images may be missing, expected 60 spatial locations per volume, but found 2048 slices.
Slice positions repeated, but number of slices (2048) not divisible by number of repeats (208): missing images?
Hint: expected 60 locations
Warning: Interslice distance varies in this volume (incompatible with NIfTI format).
Unable to equalize slice distances: slice order not consistently ascending.
First spatial position repeated 400 times

Could the solution be the same, to change the Philips range to 284?

**Comment by neurolabusc** [comment]
@Arslan1881 sounds like some files are missing - either due to a PACS error or because a time series was interrupted before completion. This sounds like a situation where manual inspection and intervention is required. It might also help to have some sequence details (how many fMRI/DWI volumes were acquired).

1. The method described by @drmclem sounds like the best approach. You should try that if the hardware is available to you.
2. If this is unavailable, I would think the first step would be to convert your DICOMs to logical filenames, and work out what the happened:
```
dcm2niix -r y /path/to/DICOMs
```
Unfortunately, unlike the other manufacturers, Philips often assigns instance numbers in the order TZ rather than ZT (where T is time and Z is slice number). This makes your task more difficult if your scan was interrupted (as with the ZT naming you just remove the last slices to make the number of slices divisible by 60). 

I do think this is a great opportunity for you to reach out to your Philips Research Collaboration manager. It is their role to help people like you. Our community has benefited from their engagement (in particularly @drmclem and @sandeepganji).

**Comment by neurolabusc** [comment]
Also, do try the [script](https://github.com/VisionandCognition/NHP-Process-MRI/blob/master/python/fix_dcm_incompletevols.py) @pcklink developed. Even if this works, you should do an inquest to understand why some volumes were lost. This is a kludge, and you really want to make sure you have complete datasets.

**Comment by Arslan1881** [comment]
Ok thanks, I will proceed with the aforementioned steps. Hope it works!

**Comment by brianwskim** [comment]
Apologies for opening an old discussion, but I have run into the exact same problem with Philips MRI! 

I have tried @pcklink script. I have also tried renaming to include the Instance Number in each .dcm abd then reapplying dcm2niix (plus trying the fix_incomplete_vols.py script). Sadly, all .dcm go into *orphan_dcm* and there are no *corrected_dcm* files. 

Any further tips apart from the script and renaming? I'm not in contact with the original MR technicians/radiographers so I am unsure we can reload and trim slices to match a multiple of 35.

`Chris Rorden's dcm2niiX version v1.0.20230411  Clang14.0.3 ARM (64-bit MacOS)
Found 421 DICOM file(s)
Slices not stacked: echo varies (TE 2.372, 1.186; echo 1, 1). Use 'merge 2D slices' option to force stacking
DICOM images may be missing, expected 227 spatial locations per volume, but found 106 slices.
Warning: Instance Number (0020,0013) order is not spatial.
Warning: Instance Number (0020,0013) order is not spatial.
Warning: Interslice distance varies in this volume (incompatible with NIfTI format).
Error: Missing images. Found 106 images, expected 227 slices per volume and instance number (0020,0013) ranges from 228 to 454
Philips Scaling Values RS:RI:SS = 2.21758:0:0.00252782 (see PMC3998685)
Convert 106 DICOM as nifti/WIP_SAG_W_mDIXON_HEAD_NECK_e1 (384x384x106x1)
Warning: Unable to rotate 3D volume: slices not equidistant: 2 != 5
Compress: "/opt/homebrew/bin/pigz" -b 960 -n -f -6 "nifti/WIP_SAG_W_mDIXON_HEAD_NECK_e1.nii"
Compress: "/opt/homebrew/bin/pigz" -b 960 -n -f -6 "nifti/WIP_SAG_W_mDIXON_HEAD_NECK_e1_Eq_1.nii"
DICOM images may be missing, expected 227 spatial locations per volume, but found 109 slices.
`

**Comment by neurolabusc** [comment]
Perhaps you could see if [dicm2nii](https://github.com/xiangruili/dicm2nii) resolves your issue. Alternatively, you could try to rename your DICOM images with `dcm2niix -r y /path/to/dicoms` which will clone your DICOMs but the filenames will begin with the instance numbers. For most manufacturers (GE, Siemens, UIH, Canon) the instance number is sequential, so you simply have to discard the slices that belong to the final partial volume. Unfortunately, in my experience Philips instance numbering often does not match the temporal order of acquisition. I do think you should reach out to the Philips Clinical Scientist associated with your center. It is their role to aid users like you. They may have a clever script to help you out. I would be happy to improve dcm2niix support if Philips adds additional grouping tags to their DICOMs (similar to their competitors).
