### ISSUE TITLE
Siemens filedmap converted error

### ISSUE THREAD

**Issue by shiningtt** [rordenlab/dcm2niix#360]
Hi,

We just used the latest version of dcm2niix to convert siemens fieldmap sequence dicom data to nii format. However, the converted magnitude nii image could not be opened by a typical nii image viewer and it indicated "Matrix is singular".  

The fieldemap sequence has magnitude images from two echoes and a phase difference image. Mag and Pha images were stored in seperate folders. During the conversion, we used the command  dcm2niix -m y + foldername trying to merge magnitude images from two echoes.  

After then, we've tested the dcm2niix version of 20181125. Using the same command, the converted nii file of Mag image can be opened by nii viewer. However, there was Mag image from only one echo. 

Could you please help to address this issue?
Thanks.

Best, 
yfan

**Comment by neurolabusc** [comment]
Can you share a sample with me by sending a Box/DropBox/GoogleDrive link to the email address embedded in my avatar. Assuming this is a Siemens scan, this sounds like a tool upstream was unaware that instance numbers are not unique for Siemens field maps, resulting in some of the images [overwriting](https://neurostars.org/t/field-mapping-siemens-scanners-dcm2niix-output-2-bids/2075/10) others.

**Comment by shiningtt** [comment]
> Can you share a sample with me by sending a Box/DropBox/GoogleDrive link to the email address embedded in my avatar. Assuming this is a Siemens scan, this sounds like a tool upstream was unaware that instance numbers are not unique for Siemens field maps, resulting in some of the images [overwriting](https://neurostars.org/t/field-mapping-siemens-scanners-dcm2niix-output-2-bids/2075/10) others.

**Comment by shiningtt** [comment]
Dear Chris,

Thanks for your quick reply. I just send you a sample through goolge drive. 

Best,
yfan
