### ISSUE TITLE
[question] dcm2niix gz compression using pigz

### ISSUE THREAD

**Issue by um4r12** [rordenlab/dcm2niix#361]
Hi!

I have been running dcm2niix on hpc's serially, i.e. one job for every subject. I request 1 cpu per job, and have been using pigz for compression using the following command:

`dcm2niix -f %f_%p_%d_%s -o $OUTPUT_DIR -m y -z y -9  $INPUT_DIR`

I wasn't aware that pigz did parallel compression, and so during the compression portion of the job, too many threads are created and I only have 1 cpu resulting into a high number of context switches. Looking at the man for pigz, I could specify "-p 1" to limit the number of threads created to 1. Is there anyway I could incorporate that flag?

If not, would you suggest I use a different compressor? 

Also regarding the dcm2niibatch script, is it able to execute jobs in parallel, or does it do it serially?

Thanks!

**Comment by neurolabusc** [comment]
Use the `-z i` for the internal serial zip compression.  This will only use a single thread. Since dcm2niix is typically built with the CloudFlare zlib as its internal compressor, it will only use a single thread but be about as fast as pigz using two threads. In general, HPC systems have a lot of CPU power but very slow disk I/O. In these cases I would always use `-z i` (single threaded) or `-z o` (piped parallel threads). These details are discussed [here](https://github.com/neurolabusc/dcm2niiXL).

You can always run dcm2niix without any arguments to see your options:

```  
>dcm2niix
Chris Rorden's dcm2niiX version v1.0.20191111  Clang11.0.0 (64-bit MacOS)
...
-z : gz compress images (y/o/i/n/3, default n) [y=pigz, o=optimal pigz, i=internal:miniz, n=no, 3=no,3D]
```

The yaml batch script variant was created by @benjaminirving and only runs one batch at a time in serial. I have never tried it, but it might compile with openmp for the for loop. It is possible to run [dcm2niix asynchronously](https://github.com/neurolabusc/dcm2niiXL). This will spawn multiple instances, each using a CPU. Since the software typically I/O bound, this approach is not guaranteed to be faster, it may result in a lot of disk contention.

**Comment by neurolabusc** [comment]
Are you working with MRI or CT data? The `-m y` will merge images from a series even if they differ in parameters like echo time or X-Ray exposure. Most MRI users should never merge data, while for CT systems it depends on whether you want to analyze different exposures differently. Assuming you are using current stable release (v1.0.20190902) or later, I would suggest most users stick with the default  (which is `-m 2`, meaning that CT scans are merged but MRI scans are not). The only typical exception is CT users who want to analyze exposures separately and should choose `-m n`.

For Siemens MRI users, the `-m y` can be particularly problematic, as Siemens field maps do not generate unique instance numbers for images of a single series that have different echo times.

**Comment by um4r12** [comment]
> 
> 
> Use the `-z i` for the internal serial zip compression. This will only use a single thread. Since dcm2niix is typically built with the CloudFlare zlib as its internal compressor, it will only use a single thread but be about as fast as pigz using two threads. In general, HPC systems have a lot of CPU power but very slow disk I/O. In these cases I would always use `-z i` (single threaded) or `-z o` (piped parallel threads). These details are discussed [here](https://github.com/neurolabusc/dcm2niiXL).
> 
> You can always run dcm2niix without any arguments to see your options:
> 
> ```
> >dcm2niix
> Chris Rorden's dcm2niiX version v1.0.20191111  Clang11.0.0 (64-bit MacOS)
> ...
> -z : gz compress images (y/o/i/n/3, default n) [y=pigz, o=optimal pigz, i=internal:miniz, n=no, 3=no,3D]
> ```
> 
> The yaml batch script variant was created by @benjaminirving and only runs one batch at a time in serial. I have never tried it, but it might compile with openmp for the for loop. It is possible to run [dcm2niix asynchronously](https://github.com/neurolabusc/dcm2niiXL). This will spawn multiple instances, each using a CPU. Since the software typically I/O bound, this approach is not guaranteed to be faster, it may result in a lot of disk contention.

This is perfect, thanks for all the information!





> 
> 
> Are you working with MRI or CT data? The `-m y` will merge images from a series even if they differ in parameters like echo time or X-Ray exposure. Most MRI users should never merge data, while for CT systems it depends on whether you want to analyze different exposures differently. Assuming you are using current stable release (v1.0.20190902) or later, I would suggest most users stick with the default (which is `-m 2`, meaning that CT scans are merged but MRI scans are not). The only typical exception is CT users who want to analyze exposures separately and should choose `-m n`.
> 
> For Siemens MRI users, the `-m y` can be particularly problematic, as Siemens field maps do not generate unique instance numbers for images of a single series that have different echo times.

Oh that did not occur to me. I am using MRI data across a few of vendors (GE, Siemen and Philips).  
There are a couple of sequences that are the same but vary in TE (ex. SWI/R2Star), so you're right, that would merge them into one single nii file, and ideally, they should be separated. I will exclude the flag and compare the ouputs. Thanks for the heads up!
