### ISSUE TITLE
Can I manually specify # of slices?

### ISSUE THREAD

**Issue by iPsych** [rordenlab/dcm2niix#364]
I have some data from Siemens Verio Scanner.
It's a time-series data (fMRI).
The .dcm file can convert to nifti one by one properly, but when I try to convert them once, 
It shows below warning, and gives strange result (384x384x1 2D matrix rather than 3D one).

> WarningL 0008, 0008=MOSAIC but number of slices not specified: file.dcm

I believe something gone wrong between the file processing btw. Scanner to PACS and finally my disk.

Since re-downloading from PACS will be huge work, can I manually set the slice numbers?

**Comment by iPsych** [comment]
I believe it's a similar issue with https://github.com/rordenlab/dcm2niix/issues/275.
Is there any manual work-around if I know the slice order or timings?

**Comment by neurolabusc** [comment]
See [issue 337](https://github.com/rordenlab/dcm2niix/issues/337). You can try the developmental branch, assuming you have a Unix computer you could build this with:

```
git clone --branch development https://github.com/rordenlab/dcm2niix.git
cd dcm2niix/console
make
```

If you are lucky, this will report
```
Warning: Guessing this is a mosaic up to 49 slices (issue 337). Slice positioning will be inaccurate if fewer slices.
```
with the caveats listed in issue 337.

**Comment by iPsych** [comment]
It works, and of course, slice-timing/order should be specified in .json file manually (since the information is not existing in the dicom).
I am suspicious about several 'anonymizing' tool for dicom aggressively destroy some metadata NOT contain private information.

**Comment by neurolabusc** [comment]
Can you provide some context - is this data from the ADNI dataset? Feel free to send me an example DICOM image by sending a link to my email (shown in my avatar). I suspect that these DICOM images were corrupted either by the insertion of a image icon or an anonymization tool that stripped out the CSA header.
