### ISSUE TITLE
Problem Converting GE Scans

### ISSUE THREAD

**Issue by willi3by** [rordenlab/dcm2niix#365]
Hi,

I am using dcm2niix to convert dicoms obtained from a GE Signa Architect 3T scanner. I have a few structural (T1 and T2) images as well as a diffusion sequence. When using dcm2niix, the diffusion sequences are converted properly but the structural scans are not (see attached).  I have also tried using dcm2nii, which works as expected for structural scans but not for diffusion (incorrect bvalues, but I think this is the expected behavior for dcm2nii). The images were acquired with acceleration (compressed SENSE and multiband, when appropriate). I can work around these issues by using dcm2nii for anatomical and dcm2niix for diffusion, but it would be better if I could use dcm2niix for all conversions. Could you help me troubleshoot this issue? 

On the attached image, it seems the scan is being converted as two time steps instead of as a single volume. 

Thanks very much,
Brady

![Screen Shot 2020-01-02 at 9 45 10 AM](https://user-images.githubusercontent.com/42728698/71672634-9770ce80-2d44-11ea-9f10-65f59f16a6e6.png)

**Comment by neurolabusc** [comment]
1. Can you confirm you are using the latest [release (v1.0.20190902)](https://github.com/rordenlab/dcm2niix/releases)? 
2. I assume the image appears to be incorrectly converted when viewed with [MRIcroGL](https://www.nitrc.org/plugins/mwiki/index.php/mricrogl:MainPage) and FSLview?
3. I do not have access to GE equipment. If the suggestions above do not explain your issue, can you send a link (DropBox, GoogleDrive, Box, etc) to the e-mail address shown in my avatar.

**Comment by willi3by** [comment]
1. Yes I am using the most up-to-date version. 
2. That is correct. 
3. Sure, I will send a OneDrive link now. 

Thanks for your time,
Brady

**Comment by neurolabusc** [comment]
Can you use a different file sharing service. My institution has a fraught relationship with OneDrive.

![microsoft](https://user-images.githubusercontent.com/8930807/71683369-5dadc100-2d60-11ea-8aab-1cf1eb209a27.png)

**Comment by willi3by** [comment]
Hi,

I created a DropBox account with a shared folder. Let me know if you have any trouble accessing. Here is a link just in case you didn’t get a notification.

https://www.dropbox.com/sh/oeqrs6137ou9xtk/AACCLeSFw-WaIqJMnOkk47ECa?dl=0


Thanks,

Brady Williamson, Ph.D.
Department of Radiology
UC College of Medicine
234 Goodman Street<x-apple-data-detectors://63>
Cincinnati, OH 45267-0525<x-apple-data-detectors://63>
Tel: 513-558-2334

**Comment by neurolabusc** [comment]
I can replicate your problem with the current stable release, but it appears resolved in the current developmental branch (which will soon mature into the next stable release). I suspect this is a replication of [issue 336](https://github.com/rordenlab/dcm2niix/issues/336). Can you test the current developmental release and if it resolves your issue can you close this issue.

On MacOS and Linux you can build the developmental branch with these commands:

```
git clone --branch development https://github.com/rordenlab/dcm2niix.git
cd dcm2niix/console
make
./dcm2niix
```

Windows users should be able to get a compiled version from [AppVeyor](https://ci.appveyor.com/project/neurolabusc/dcm2niix).

**Comment by willi3by** [comment]
Works great! Thanks for the help. I will close the issue.

Thanks again,

Brady Williamson, Ph.D.
Department of Radiology
UC College of Medicine
234 Goodman Street<x-apple-data-detectors://63>
Cincinnati, OH 45267-0525<x-apple-data-detectors://63>
Tel: 513-558-2334
