### ISSUE TITLE
GEIIS thumbnail detection

### ISSUE THREAD

**Issue by neurolabusc** [rordenlab/dcm2niix#367]
As describes previously, once upon a time GE GEIIS PACS systems would insert a thumbnail image into any DICOM image they touched. Unfortunately, the same public tags used for the main image were also used for the thumbnail. The thumbnail was stored in its own SQ, so while unconventional this would technically be legal. However, all previous GEIIS thumbnails I have seen were stored compression, while the main image transfer syntax described uncompressed image data (which is a violation of the DICOM standard). In practice, many anonymization tools remove the SQ flags, making it impossible to discriminate the thumbnail from the main image. While one could argue whether the root cause of the issue was the original GEIIS thumbnail, or subsequent tools modification, the end result is that dcm2niix uses several heuristics to attempt to detect thumbnails and discriminate them from actual images. @tashrifbillah has just sent a GEIIS dataset where the thumbnail is uncompressed (which I have never seen before). This image misleads my GEIIS thumbnail detection algorithm. A new commit relaxes adjusts the thumbnail detection. Hopefully, this will be a good universal solution, but there may be unintended consequences for other GEIIS images that have been borked by anonymization scripts.

I would urge every user who sees the dcm2niix warning:
`Warning: GEIIS violates the DICOM standard. Inspect results and admonish your vendor.
`
to take it seriously, and see if the PACS system that touched the images can be upgraded to a modern version of software. I suspect that my software does a very good job of correctly detecting these thumbnails, but I also suspect these images cause problems with many other tools. I would not consider these archival quality, and all GEIIS thumbnails that use a different transfer syntax than the main image are by definition invalid images that violate the DICOM standard. The vendor should honor their DICOM conformance statement, updating your PACS and providing a tool to repair the broken DICOMs they created. This is not a limitation of dcm2niix, but reflects an issue with the images.

**Comment by tashrifbillah** [comment]
I confirm that the commit works for the particular example I shared. I would test it on a few more cases I have.
