### ISSUE TITLE
Questions about GUI options and automatic slice order correction 

### ISSUE THREAD

**Issue by jean2033** [rordenlab/dcm2niix#368]
Dear dcm2niix experts, 

Hello, this is Jean who is new to neuro imaging world.! 
I am currently working on DTI data sets, and the slice order of my data is not correct, but with the pattern. So I first made a code to correct the slice order to create rigid diffusion images after converting my PAR/REC files to NIFTI format (compressed one). 
Then, my colleague recommended me to use dcm2niix, and the tool actually corrected the slice order by taking bzero images to the front which was originally on the last volume. 
![image](https://user-images.githubusercontent.com/60031981/72661929-b1d4c880-3a23-11ea-9923-77e957d53d16.png) <-- I used this option. 

1. I want to know what options of dcm2niix are responsible for correcting slice order of data. 
2. I wonder why it gives two different output images of 33 volume and 34 volume? but with bval/bvec files that is matched with 33volumes one only. 
![image](https://user-images.githubusercontent.com/60031981/72661949-f3fe0a00-3a23-11ea-80f3-bc2645af8ab5.png)
<-- file named ADC, at last, is the one with 34 volumes. 
3. Is there any recommendation for a tutorial or have a full explanation about the option in MRIcroGL dcm2niix GUI? want to know the exact function of each option (e.g. verbose, automatic series merging (<- probably this one is correcting the slice order ?) ) 

Thank you in advance! Looking for kind response. I am very excited to use new tool here.!

**Comment by neurolabusc** [comment]
1. dcm2niix will save images in the order ijkt where I=column, J=row, K=slice, T=time/dynamic/direction. The is no single Philips DICOM format, their interpretation of the standard has changed over time. Assuming your data is modern enhanced DICOM, the [Dimension Index Values (0020,9157)](http://dicomlookup.com/lookup.asp?sw=Tnumber&q=(0020,9157)) are used to sort slices.
2. Philips will save [derived images](https://github.com/rordenlab/dcm2niix/tree/master/Philips) in the same series as the raw DICOM data. For example, if you acquire a diffusion dataset and elect to have the scanner generate a TRACE image, the trace image will be appended to the raw data. This is technically a violation of the DICOM standard. Furthermore, these derived images will disrupt subsequent processing (e.g. dtifit). Finally, you can create better derived images after processing data (e.g. degibbs, denoise, TOPUP, eddy). Therefore, dcm2niix copies the entire series (with the [_ADC postfix](https://github.com/rordenlab/dcm2niix/blob/master/FILENAMING.md)), but also generates a series where the derived images have been removed. For future work, I would suggest you set up the scanner console to not generate these derived images.
3. You can get brief help by hovering your mouse over each item to see a tooltip hint. More details are in the [wiki](https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage) as well as the markdown (.MD) files provided on [Github](https://github.com/rordenlab/dcm2niix).
