### ISSUE TITLE
Empty nii from PET images

### ISSUE THREAD

**Issue by lamaresh** [rordenlab/dcm2niix#374]
If I use stable branch conversion works fine.
Using development branch when I try to convert GE PET images the output is a nii file with only 0

**Comment by neurolabusc** [comment]
Hard to provide feedback without seeing an example. You could try running the development and stable builds using the `-v 2` parameter and seeing if this reveal the change. I have very little experience with GE PET images, so unclear why the recent changes would have an impact.

**Comment by lamaresh** [comment]
It seems like, after reading all DICOM files, the last dicom file is processed twice

```
JPEG signature 0xFFD8FF found at offset 5788 of ./IM-0002-0047.dcm
btMarkerType 0XC4 length 36@6
 [Huffman Length 36]
DHT has 1 combinations with 1 bits
DHT has 0 combinations with 2 bits
DHT has 0 combinations with 3 bits
DHT has 5 combinations with 4 bits
DHT has 4 combinations with 5 bits
DHT has 3 combinations with 6 bits
DHT has 1 combinations with 7 bits
DHT has 1 combinations with 8 bits
DHT has 1 combinations with 9 bits
DHT has 1 combinations with 10 bits
DHT has 0 combinations with 11 bits
DHT has 0 combinations with 12 bits
DHT has 0 combinations with 13 bits
DHT has 0 combinations with 14 bits
DHT has 0 combinations with 15 bits
DHT has 0 combinations with 16 bits
DHT combination 1 has a value of 0
DHT combination 2 has a value of 1
DHT combination 3 has a value of 2
DHT combination 4 has a value of 3
DHT combination 5 has a value of 10
DHT combination 6 has a value of 11
DHT combination 7 has a value of 4
DHT combination 8 has a value of 8
DHT combination 9 has a value of 9
DHT combination 10 has a value of 12
DHT combination 11 has a value of 5
DHT combination 12 has a value of 6
DHT combination 13 has a value of 7
DHT combination 14 has a value of 13
DHT combination 15 has a value of 14
DHT combination 16 has a value of 15
DHT combination 17 has a value of 16
 [FrameCount 1]
btMarkerType 0XC3 length 11@44
 [Precision 16 X*Y 128*128 Frames 1]
btMarkerType 0XDA length 8@57
 [Predictor: 1 Transform 0]
JPEG ends 13696@19484
Converting ./IM-0002-0047.dcm
JPEG signature 0xFFD8FF found at offset 5788 of ./IM-0002-0047.dcm
btMarkerType 0XC4 length 36@6
 [Huffman Length 36]
DHT has 1 combinations with 1 bits
DHT has 0 combinations with 2 bits
DHT has 0 combinations with 3 bits
DHT has 5 combinations with 4 bits
DHT has 4 combinations with 5 bits
DHT has 3 combinations with 6 bits
DHT has 1 combinations with 7 bits
DHT has 1 combinations with 8 bits
DHT has 1 combinations with 9 bits
DHT has 1 combinations with 10 bits
DHT has 0 combinations with 11 bits
DHT has 0 combinations with 12 bits
DHT has 0 combinations with 13 bits
DHT has 0 combinations with 14 bits
DHT has 0 combinations with 15 bits
DHT has 0 combinations with 16 bits
DHT combination 1 has a value of 0
DHT combination 2 has a value of 1
DHT combination 3 has a value of 2
DHT combination 4 has a value of 3
DHT combination 5 has a value of 10
DHT combination 6 has a value of 11
DHT combination 7 has a value of 4
DHT combination 8 has a value of 8
DHT combination 9 has a value of 9
DHT combination 10 has a value of 12
DHT combination 11 has a value of 5
DHT combination 12 has a value of 6
DHT combination 13 has a value of 7
DHT combination 14 has a value of 13
DHT combination 15 has a value of 14
DHT combination 16 has a value of 15
DHT combination 17 has a value of 16
 [FrameCount 1]
btMarkerType 0XC3 length 11@44
 [Precision 16 X*Y 128*128 Frames 1]
btMarkerType 0XDA length 8@57
 [Predictor: 1 Transform 0]
JPEG ends 13696@19484
```

this doesn't happens with -s called on that specific dicom file

**Comment by lamaresh** [comment]
I found the commit when it stopped working: https://github.com/rordenlab/dcm2niix/commit/ca474998c38ede22e003363b81f2b97785c604c5?diff=split

I think the problem is that iVaries is set to true instead of false

**Comment by lamaresh** [comment]
I made a pull request with a possible fix
https://github.com/rordenlab/dcm2niix/pull/375

**Comment by neurolabusc** [comment]
You have done a good job identifying the root problem. Unfortunately, your pull request will have unintended consequences. Specifically, you have identified that the [detection of variable slice intensity scaling](https://github.com/rordenlab/dcm2niix/issues/363) has issues. However, as shown in that issue, the slice scaling can vary not only between volumes, but within slices of a single volume.

**Comment by neurolabusc** [comment]
@lamaresh can you please test my latest commit. I have very little experience with GE PET data. I would suggest you carefully validate the resulting output and make sure my software is behaving as expected. @halfSpinDoctor may also have some thoughts on this. If anyone has a phantom or other data that can be shared, it would nice to have a validation dataset, not only for dcm2niix but for other conversion tools.

**Comment by lamaresh** [comment]
After your last commit the output nii has a "plausible" content, but I have little experience either with PET data so I can't help you validate it for sure,
