### ISSUE TITLE
Is it possible to store all echo times in a single NIFTI with 4-D vol field?

### ISSUE THREAD

**Issue by jaystock** [rordenlab/dcm2niix#376]
Hello,

Is it possible to write DICOMS from a multi-echo MRI acquisition to a single NIFTI file, with the different echo times stored in the 4th index of the .vol field in the NIFTI data structure?  This is often much easier to work with than opening a separate NIFTI file for every echo time.  

--- Jason

**Comment by neurolabusc** [comment]
Jason-

dcm2niix attempts to save data in BIDS-compatible format where [Multi-echo data MUST be split into one file per echo](https://bids-specification.readthedocs.io/en/latest/04-modality-specific-files/01-magnetic-resonance-imaging-data.html), see [here](https://openneuro.org/datasets/ds000258/versions/1.0.0) for a concrete example. The NIfTI header would not allow us to encode the precise echo times, and the BIDS `EchoTime` field expects a scalar value and not an array. Many tools like [tedana](https://tedana.readthedocs.io/en/latest/) expect inputs consistent with the BIDS standard. While the BIDS format might feel unwieldy and inelegant for some applications, it is a standard and maintaining consistency helps the tools that target this format.

If you want, you could always create a fork of dcm2niix to provide what you want (stacking all multi-echo images as 4D or 5D NIfTI images, and finding some mechanism to encode echo times). However, I would be reluctant to include a pull request as this would increase the complexity and hinder maintainability of the core code. 

I think an easier approach would be a simple script (potentially calling fslmerge) that stacks your images as you prefer.
