### ISSUE TITLE
Possibility to ask for a specific manufacturer tag to split output nifti

### ISSUE THREAD

**Issue by arnaudbore** [rordenlab/dcm2niix#384]
Hi,

I've got some Philips dicom (inhomogeneous Magnetization Transfer images) I need to split into folders before running dcm2niix otherwise it will combine them together as one image. I think it could be fixed if I was able to split the output nii.gz file with a specific tag into the dcm2niix command line. I'm looking at a tag known as TemporalPositionIdentifier. Also to run my scripts I would need these tags as well  [0x2005, 0x0100d] and [0x2005, 0x0100e]. It would be nice to have a way to extract these values into the json file.

Thank you in advance
Arnaud

**Comment by neurolabusc** [comment]
1. Hello, can you tell me the first line reported by dcm2niix, so I know the version and OS your are using. If it is older than v1.0.20190902 please upgrade.
```
Chris Rorden's dcm2niiX version v1.0.20190902  (JP2:OpenJPEG) (JP-LS:CharLS) Clang10.0.1 (64-bit MacOS)
```
2 This sounds like the expected behavior. Does `fslsplit input.nii output.nii -t` resolve your issue? Feel free to send a sample via DropBox/Box to the email in my avatar. Does the BIDS format expect these volumes to be separated? Do volumes differ based on 0018, 9020 [Magnetization Transfer](https://github.com/bids-standard/bep001/blob/master/src/04-modality-specific-files/01-magnetic-resonance-imaging-data.md)? I do not have access to Philips hardware, and their new Enhanced format is very different from previous DICOM images. However, recent versions of dcm2niix should handle many [unusal](https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#Unusual_MRI) sequences.

**Comment by arnaudbore** [comment]
1. dcm2niix 
`Chris Rorden's dcm2niiX version v1.0.20190902  (JP2:OpenJPEG) (JP-LS:CharLS) GCC5.5.0 (64-bit Linux)`
2. Yes it resolve my issue but my goal would be to be able to split them directly while running the conversion as well as be able to extract tag (into the json file) [0x2005, 0x0100d] and [0x2005, 0x0100e] mandatory to analyse this kind of data.
BIDS is not there yet. ihMT is an extension of MT. For a "classic" MT sequence, there are two contrasts. For ihMT MT-OFF is basically the same but for MT-ON it's divided into 5 conditions. These 5 conditions are all about saturations pulses: positive frequency, negative frequency, alternating frequency (+-), alternating frequency (-+) and last volume finally without any saturation (reference). 

I just sent you some data.
Thank you again for your help.

**Comment by neurolabusc** [comment]
@chrisgorgo historically you have been the maintainer for BIDS compatibility from dcm2niix. Do you want to continue this role? Alternatively, now that you have left the ivory tower do you want to pass the role to someone else (e.g. @effigies)? We always have a choice whether 4D series are saved as a single NIfTI (e.g. DWI, fMRI) or split into separate files (e.g. multi-echo sequences). Can you provide guidance for how ihMT data should be handled? I have no preference, I just want my handling to be consistent with the standard. Users can always employ fslsplit or fslmerge if they are unhappy with the result.

**Comment by drmclem** [comment]
Hi

I'm only guessing - but I suspect this will be a research sequence without any associated descriptive dicom tags and will probably use the dyanamic axis (4D sets can have have several different 4th dimensions described) with the dynamic looping re-purposed for the MT changes.

M

**Comment by neurolabusc** [comment]
@arnaudbore thanks for a sample. I note that different volumes have unique trigger times ([0018,1060](http://dicomlookup.com/lookup.asp?sw=Tnumber&q=(0018,1060))). I think this can be handled with the _t filename post-fix, which is also used for Trigger delay time ([0020,9153](http://dicomlookup.com/lookup.asp?sw=Tnumber&q=(0020,9153))). GE seems to use this tag [differently](https://www.slicer.org/wiki/Documentation/4.4/Modules/MultiVolumeExplorer), but I think my patch avoids any unintended consequences. Why don't you try out the developmental branch and see what you think. As @drmclem notes, you are using a WIP (Work In Progress) sequence, so it is often worth waiting until these protocols graduate to product sequences before modifying a general purpose tool like dcm2niix.

**Comment by effigies** [comment]
This particular case may be covered already by BEP 001. I will tag in @gilles86, as he will certainly be more familiar with both the scan sequences and the proposed solutions.

**Comment by arnaudbore** [comment]
@neurolabusc, the development branch seems to do exactly what I was looking for. 
Thank you.I will give it a try with few other examples to check the consistency of the output. I will let you know.
