### ISSUE TITLE
Philips Implausible InversionTimes (0018,9079)

### ISSUE THREAD

**Issue by neurolabusc** [rordenlab/dcm2niix#385]
@drmclem I have data from a Philips Ingenia_CX 5.3.1_5.3.1.3 where the Enhanced DICOMs report 
```
(0018,0082) DS [0]                                      #   2, 1 InversionTime
```
However, the same data exported as Classic DICOM omits (0018,0082) but reports 
```
 (0018,9079) FD 0\1.7976931348623167e+308                #  16, 2 InversionTimes
```
Can you explain the second value in this array? I had hoped to use 0018,9079 as a fall back when 0018,0082 is absent. However, I can not explain the values generated by Philips. It is easy to simply read the first value, but I wonder whether there will be some situations where knowing multiple inversion times will be meaningful for dcm2niix users.

Single DICOM exhibiting the issue (shared with permission and courtesy of [Pravesh Parekh](https://mbial.weebly.com/pravesh-parekh.html) ):
[0040.dcm.zip](https://github.com/rordenlab/dcm2niix/files/4338416/0040.dcm.zip)

**Comment by drmclem** [comment]
Hi

Are you sure that single dicom is from Phiips MR or the same data set ? - there are I tags I don't recognise (Elscint is in 01f7,0010 which is a CT tag)- the implementation creator is "PORTAL_8" which might be our multi-vendor workstation but will struggle to explain the inversion times from this data.

M

**Comment by neurolabusc** [comment]
The entire enhanced and classic datasets are included in [NIMHANS_DICOM.zip](https://osf.io/xvguw/files/).

**Comment by neurolabusc** [comment]
Closing issue: issue with DICOM images, not limitation of dcm2niix.
