### ISSUE TITLE
Conversion to NIfTI removes/excludes half of image volume

### ISSUE THREAD

**Issue by mattlyon93** [rordenlab/dcm2niix#386]
Converting certain datasets into NIfTI creates a NIfTI image with only half of the image data available (see below).

This bug is present on `v1.0.20190902` but not `v1.0.20190410`, as the April version converts the image correctly. I've tested this on both OSX 10.15 and Ubuntu 18.04.

The command used to create the image below was
```dcm2niix -z y -x n -o ./ -f t1_incorrect DCM_ANON/```

<img width="669" alt="Screen Shot 2020-03-18 at 4 26 25 pm" src="https://user-images.githubusercontent.com/32886639/76928321-3dd87300-6935-11ea-8e5d-c4f0a0eba1ad.png">

I have uploaded the anonymised DICOMs, and the incorrectly converted NIfTI image to [GDrive](https://drive.google.com/open?id=1Y-6HjTPL23aj5cksS0A_LcmiIAundFNY).

**Comment by neurolabusc** [comment]
Replicates issues [373](https://github.com/rordenlab/dcm2niix/issues/373), [355](https://github.com/rordenlab/dcm2niix/issues/355), [306](https://github.com/rordenlab/dcm2niix/issues/306). I would recommend acquiring future data without interpolation ([ZIP2](http://mriquestions.com/zip.html)) increases resolution at the cost of blurring, processing speed, and disk space.

This issue will be resolved in next stable release, which will be generated when [issue 377](https://github.com/rordenlab/dcm2niix/issues/377) is closed. In the mean time, I would suggest using the development build:

```
git clone --branch development https://github.com/rordenlab/dcm2niix.git
cd dcm2niix/console
make
./dcm2niix
```

Windows users should be able to get a compiled version from [AppVeyor](https://ci.appveyor.com/project/neurolabusc/dcm2niix).
