### ISSUE TITLE
How the images are separated within the same DICOM directory? 

### ISSUE THREAD

**Issue by chrisfoulon** [rordenlab/dcm2niix#387]
Dear dcm2niix team, 

First, thank you for your amazing work. It is so useful!

I have a question about the way dcm2niix decides to separate the images into several nifti within the same DICOM folder. I noticed that a single DICOM folder can lead to several nifti files, but without knowing the fields used to separate them, I end up having several files with the same name except for a number added by dcm2niix to prevent it from overwriting the files. 
 I would like to know which fields from the DICOM headers are used to do that, if possible. 

Thank you in advance for your help!

**Comment by neurolabusc** [comment]
1. You can type `dcm2niix` on the command line without any arguments to see basic help.
2. You can use the graphical interface of [MRIcroGL](https://github.com/rordenlab/MRIcroGL12/releases/tag/v1.2.20191219). With this approach, if you Import/ConvertDICOMtoNIfTI and then type `%s_%p_%t` in the output filename, you will see a sample naming appear on the right (e.g. series number, protocol name, study time `1_MPRAGE_19770703150928`) and you can see a hint appear if you leave your mouse over the field.
3. You might find the [wiki](https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#File_Naming) useful.
4. Perhaps the best answer to your questions is to direct you to the [Filenaming](https://github.com/rordenlab/dcm2niix/blob/master/FILENAMING.md) page, for example `%p=protocol name (from 0018,1030)`.

Individual preference vary, but `-f %t/%s_%p` might be a good start. This create output folders by study time, and within each folder the image name should be the series number and the protocol name. Obviously, you are at the mercy of the scanner vendor and the person who set up the sequences with regards to what information will be available.
