### ISSUE TITLE
Output More Than One NIfTI Files

### ISSUE THREAD

**Issue by chirayukong** [rordenlab/dcm2niix#396]
Hi there,

I use the `dcm2niix` command to convert the lung dicom images to the nifti file. It went very well in most cases. But some of them generated more than one nifti files. When I looked at those NIfTI files. It seems like they were split from the dicom images.  When, I looked at the json file associated with, I saw that the difference between them is value of XRayExposure metadata. 

Is there any argument of the `dcm2niix` to ignore the 'XRayExposure' value and generate only one NIfTI file.

Thank you so much,

Chirayu and @gatechke

**Comment by neurolabusc** [comment]
1.) I assume you are running the latest version ([v1.0.20200331](https://github.com/rordenlab/dcm2niix/releases)).

2.) If you run the software without any parameters, it will generate a brief list of options. This suggests that `-m y` should merge all images of a series regardless of exposure:

```
Chris Rorden's dcm2niiX version v1.0.20200331  (JP2:OpenJPEG) (JP-LS:CharLS) Clang11.0.0 (64-bit MacOS)
....
  -m : merge 2D slices from same series regardless of echo, exposure, etc. (n/y or 0/1/2, default 2) [no, yes, auto]
```

Please close this issue if this resolves your problems.

**Comment by chirayukong** [comment]
It works like a charm. :-) Thanks a lot.
