### ISSUE TITLE
DICOM conversion error

### ISSUE THREAD

**Issue by armaneshaghi** [rordenlab/dcm2niix#397]
Using `dcm2niix` v1.0.20200331 on Ubuntu 18:

I can load a set of files with the Python's `pydicom` library. However, when converting these files with `dcm2niix` , Freesurfer's `mri_convert` and `dicom2nifti` I get an error . In `dcm2niix` the error is not very informative:  

```
Found 160 DICOM file(s)
No valid DICOM images were found
```

I have attached one file from these series to this message and would appreciate any hints on converting these set of files to Nifti. Please use `gunzip` to unzip the file as Github did not allow me to upload the file directly. 

[IM000001.gz](https://github.com/rordenlab/dcm2niix/files/4600945/IM000001.gz)

**Comment by neurolabusc** [comment]
This is a DICOM header fragment without an image. The file is 5122 bytes, it describes an uncompressed 256x256x2 image (131072 bytes), but no Pixel Data Element (7FE0,0010) is provided. You can view the header with pydicom, dcmdump or gdcmdump. dcm2niix is designed to convert DICOM images, and this is not a complete DICOM image.

```
(0002,0010) UI =LittleEndianImplicit                    #  18, 1 TransferSyntaxUID
(0028,0010) US 256                                      #   2, 1 Rows
(0028,0011) US 256                                      #   2, 1 Columns
(0028,0100) US 16                                       #   2, 1 BitsAllocated
```
