### ISSUE TITLE
forbidden characters

### ISSUE THREAD

**Issue by ntraut** [rordenlab/dcm2niix#398]
Hi, I saw that when I convert DICOM using dcm2niix, the caret character (^) is replaced with _. For example we can see this with the command `dcm2niix -f %s^%p ~/DICOM`.

I saw [there](https://github.com/rordenlab/dcm2niix/blob/master/FILENAMING.md#list-of-forbidden-characters-based-on-windows) that some characters are forbidden because of Windows restrictions but it seems OK to use ^ in a Windows file name. I would want to know why caret is forbidden in dcm2niix and what is the complete list of forbidden characters?

**Comment by neurolabusc** [comment]
Acknowledged, fixed in current development branch and future stable releases. Caret is not allowed in filenames. Please test and close if OK.

**Comment by ntraut** [comment]
Hi, the fix does not work totally for me because when the caret is the name field of the DICOM, it is still converted to _. The fix seems to work only when ^ is directly given in the -f option.

I have to say that I found some rumors saying that ^ is forbidden on FAT file systems, but in fact it is more complicated than that because in new Windows ^ is allowed in file names even if the file system is FAT.

**Comment by neurolabusc** [comment]
On further reflection, I think it is better to change the documentation than the software. Specifically, I think that the caret symbol (^) should be added to the list of forbidden characters. The rationale is that
 1. Not supported by at least some [FAT file systems](https://stackoverflow.com/questions/122400/what-are-reserved-filenames-for-various-platforms)
 2. Has a special meaning [for SPM](http://jpeelle.net/mri/misc/spm_select.html) file searches.

It seems that allowing this character to survive in filenames is likely to have unintended consequences. dcm2niix has been used for many years, and you are the first to raise this issue. My sense is that the behavior of prior releases is justified, but the documentation should reflect these choices. Do you concur?

**Comment by ntraut** [comment]
Personally I'm not sure that any of the above reasons is well founded. I checked in Windows 3, and '^' is forbidden but also '['. In windows 98, the list of forbidden characters is the same as in Windows 10.

For SPM, searches are made with regular expressions but there are also '.' and '$' which are special characters. I think the negative impact would be very marginal but I understand your point of view of keeping things like they are.

**Comment by neurolabusc** [comment]
@effigies and @satra since you are involved in a lot of large projects and big-picture leadership, do you have any suggestions. I do not have a strong view on this. There are two options:

 1. Old behavior: carets (^) are replaced with underscore (_) in file names.
 - caret illegal for some FAT file systems.
 - caret has special meaning for some scripts (SPM, [windows](https://superuser.com/questions/785232/processing-files-with-names-that-contain-a-caret-in-windows), [Python](https://help.semmle.com/wiki/display/PYTHON/Unmatchable+caret+in+regular+expression)) so avoids unintended consequences.
 2. Proposed behavior: Allow carets in filenames if user explicitly requests them (`-f %s^%p`) or if they are part of the DICOM header (e.g. `-f %p` where protocol name is `MPRAGE^T1`).
 - preserves input data.

If we do decide to keep the old behavior, should we also replace the dollar symbol ($) with underscore (_) as it is used a special character for a lot of scripts?

**Comment by ntraut** [comment]
I give those links if that can help:
http://jpeelle.net/mri/misc/spm_select.html#using-regular-expressions-to-filter-files
https://en.wikipedia.org/wiki/Filename#Comparison_of_filename_limitations

In fact I did not check properly and ^ is even allowed in Windows 3.x using FAT16 file system (anyway this file system allows only up to 11 for characters length).

**Comment by satra** [comment]
@neurolabusc - i'm generally in favor of accepting a broader space of things so your 2 is fine. 

however, certain things like bids will place constraints on output names (i think, and @effigies can correct me, that bids names are alphanumeric). so is someone named their subject `^_^`, it won't pass bids validation. but does not mean it is not usable as a valid name. so i think dcm2niix should be more broad than what any standard may dictate. a person using dcm2niix with a standard can choose to be more specific with how they use it.

this impacts, as you said, only filenames, and most modern systems accept a host of unicode settings. storing the information in a database would also not be a problem.

**Comment by ntraut** [comment]
Thanks @satra.

In my opinion it's still a good idea to prevent the characters `0x00-0x1F 0x7F " * / : < > ? \ |` to avoid problems when running dcm2niix on Windows but I don't think there is a need to do more.

The fix is working for me now. I am asking for this because there are some non-alpanumeric characters in DICOM fields which can be useful for me but I don't keep them when I finally convert the dataset in BIDS format.

**Comment by neurolabusc** [comment]
@ntraut  the development branch and future stable releases will permit the caret character.
