### ISSUE TITLE
bval/bvec not generated

### ISSUE THREAD

**Issue by vblsu** [rordenlab/dcm2niix#401]
Dear Chris,
I had tried to convert my DTI DICOM data from Philips MRI to NIfTI but it is showing
Warning: No bvec/bval files created: only single value after ADC excluded when used MRIcro for conversion.
The following was the message when I used MRIcron
_**Found 1768 DICOM file(s)
Warning: This diffusion series does not have a B0 (reference) volume
Using RWVSlope:RWVIntercept = 1.38608:0
 Philips Scaling Values RS:RI:SS = 1.38608:0:0 (see PMC3998685)
Convert 1768 DICOM as /Users/vinita/Desktop/DTItest (144x144x52x34)
Conversion required 1.995563 seconds (0.931139 for core code).**_

I have tried MRIcro, MRIconvert and MRIcron without success.

I would really appreciate your help.

Thanks !

VB

**Comment by neurolabusc** [comment]
Can you send a sample dataset via Box/DropBox/GoogleDrive to the email address in my avatar? In general, dcm2niix will automatically extract bvecs/bvals from Philips data, for example [dcm_qa_philips](https://github.com/neurolabusc/dcm_qa_philips) provides validation datasets acquired over many years. Also, any details about the sequence would help. For example, of the 34 volumes acquired, how many were b=0 and how many had diffusion gradients applied?

**Comment by neurolabusc** [comment]
Unable to replicate. Validation [Philips images](https://github.com/neurolabusc/dcm_qa_philips) correctly generate bevy/bval

**Comment by vblsu** [comment]
![IMG_5340](https://user-images.githubusercontent.com/65729223/83772892-80167400-a649-11ea-8116-6818874b6385.JPG)
![IMG_5341](https://user-images.githubusercontent.com/65729223/83772897-81e03780-a649-11ea-966a-fbd434a23fa8.JPG)

Please find attached images about our equipment. I would appreciate your help to resolve this matter

**Comment by vblsu** [comment]
Hello Chris, 

I have sent my DTI dcm files on your avatar email via dropbox and also attached the equipment details image here.

Please let me know if you have any further questions.

Thank you for your help !

VB

**Comment by vblsu** [comment]
Hello,
Quick question will sending the raw files from a CD to Sectra-PACS alter the header ?
We usually have our patient data on a CD which is stored in a propreitary format and we put it in Horos to decipher the files for further use.
