### ISSUE TITLE
Conversion of localizers results in 3 different NIfTIs (one for each orientation)

### ISSUE THREAD

**Issue by Hershkovitz-hub** [rordenlab/dcm2niix#404]
Hello,

I'm trying to convert localizers using dcm2niix and receiving the following messages:

```
Slices not stacked: orientation varies (vNav or localizer?) [1 0 0 0 1 0] != [0 1 0 0 0 -1]
Warning: Siemens MoCo? Bogus slice timing (range -1..-1, TR=7.6 seconds)
Warning: Weird CSA 'ProtocolSliceNumber' (System/Miscellaneous/ImageNumbering reversed): VALIDATE SLICETIMING AND BVECS
```

The result of the conversion is 3  3D NIfTIs, each containing single orientation of the localizer.
Any way to fix this issue?

Thank you,
Gal.

**Comment by neurolabusc** [comment]
@Hershkovitz-hub: This is an inherent property of the NIfTI format. The format requires that all slices in a volume are co-planar and equidistantly spaced. A localizer that acquires images with sagittal, coronal and axial orientation as a single DICOM series must be saved as three different NIfTI files (or must ignore spatial coordinates).

In general, we want to discard localizers. This explains the dcm2niix option `-i y`. Localizer scans are designed for planning subsequent high-quality images. They are typically quick and dirty sequences. They often show interference effects at locations where the orthogonal slices are made, they are often very sensitive to MR artifacts. I actually like this latter aspect, as they can help you see if issues like RF leakage that might have a More subtle influence on subsequent scans. Furthermore, most NIfTI tools are designed for 3D volumes, and have a hard time interpolating oblique cuts with 2D slices.

**Comment by Hershkovitz-hub** [comment]
Okay, I get that the scan isn't useful in pretty much all cases, just wondered why it was happening.
Anyway, Thank you for the quick response! I'll close the issue.
