### ISSUE TITLE
README.md first sentence misses a noun

### ISSUE THREAD

**Issue by jhuguetn** [rordenlab/dcm2niix#411]
Just a minor issue. 
The very first paragraph of the readme document, describing what `dcm2niix` is, misses a noun. Something like: _tool_, _piece of software_ or _program_.

> dcm2niix is a **(??)** designed to convert neuroimaging data from the DICOM format to the NIfTI format. This web page hosts the developmental source code - a compiled version for Linux, MacOS, and Windows of the most recent stable release is included with MRIcroGL. A full manual for this software is available in the form of a NITRC wiki.

**Comment by neurolabusc** [comment]
Thanks. Fixed in developmental branch.
