### ISSUE TITLE
Supporting older linuxes

### ISSUE THREAD

**Issue by kousu** [rordenlab/dcm2niix#413]
Hi there! Thanks for maintaining this software.

I noticed in your README that you say your Linux binaries are not compatible with older linuxes.

There's a strategy around this: Python adopted CentOS's oldstable as "universal linux" in their https://github.com/pypa/manylinux project, and it's worked well. Currently that means CentOS-7. For simple C programs without a lot of dependencies, it turns out that glibc is stable enough about backwards compatibility that you can compile on CentOS-7 and have your code work everywhere.

I was able to get Travis to run CentOS 7 this way:

- https://github.com/neuropoly/spinalcordtoolbox/blob/48496b28eec9900456eed66da73152d83c0902e2/.travis.yml#L85
- https://github.com/neuropoly/spinalcordtoolbox/blob/48496b28eec9900456eed66da73152d83c0902e2/util/dockerize.sh

please feel free to adapt that to your needs if it seems useful

**Comment by neurolabusc** [comment]
@ningfei manages Travis, so I will defer to him. At the moment, Travis generates a Linux executable with each commit and tests this against the [validation datasets](https://github.com/neurolabusc/dcm_qa). This executable is also attached to each release as `dcm2niix_lnx.zip`. This version seems to be compatible with most modern releases of Linux. I can see the advantage of targeting an older version of Linux to provide better compatibility, but one also worries about targeting the least common denominator. Should we create two executables - a legacy one for ancient systems and a modern one for more recent versions of Linux? 

By the way, as noted on the project home page, the Linux version of dcm2niix distributed with [MRIcroGL](https://github.com/rordenlab/MRIcroGL12/releases) is compiled on a [holy build box](https://github.com/phusion/holy-build-box), so it should run on any Linux distribution. This is a good option for users who have older versions of Linux, but are unable to build dcm2niix themselves (e.g. users of a HPC system that do not have permissions to install compilers and libraries).

Again, I will defer to @ningfei for a response. There seem to be several options: 
 1. Adopt Travis modifications that always target older systems.
 2. Create multiple builds, for older and more recent systems.
 3. Make no changes, and guide users of older systems to use the executable provided with MRIcroGL.
 4. Make no changes to main repository, but make a branch/fork that targets older systems.

**Comment by ningfei** [comment]
@kousu Thanks for the links! Didn't know that it's also possible to specify docker image as env in Travis. 

Currently, we set the Linux build env to Ubuntu Trusty 14.04 which has Glibc 2.19 (initially release on Feb 7, 2014), while in CentOS 7 it's 2.17 (initially released on Dec 25, 2012) by default. I think the current version should be compatible in most of the cases. Could  think of targeting older versions. But as I checked, there seems no easy way to set up GCC-5 in the CentOS 7 docker image in Travis? The default GCC to be installed is 4.8.5.

If we really want to target older systems, the simplest way would be using Ubuntu Precise 12.04, which has Glibc 2.15.

**Comment by neurolabusc** [comment]
Targeting for 14.04 and later does seem to cover most users. Maybe we should simply update the documentation to note that the provided compiled version supports  `Glibc 2.19 (from 2014) and later. Users of older systems can compile their own version or download the compiled version included with MRIcroGL Glibc  2.12 (from 2011).`

Ubuntu 14.04 reached end-of-life on  April 30, 2019. Therefore, I do not think we need to support older systems. Also supporting older distributions requires compiling without support of some modern libraries like [CharLS](https://github.com/team-charls/charls). This is seen in the dcm2niix version provided with MRIcroGL, which is unable to handle DICOM images that use the JPEG-LS transfer syntax.

In my experience, individual users tend to use modern distributions. On the other hand, institutional HPCs often run `proven` older releases. I would argue that HPC teams should really be encouraged to use Glibc 2.29 or later which resolved the [pthread](https://sourceware.org/bugzilla/show_bug.cgi?id=23275) issues that can impact popular tools like [pigz](https://github.com/madler/pigz/issues/68). This should provide sufficient incentive for users to run a version of Linux that supports the pre-compiled versions of dcm2niix we provide.

**Comment by ningfei** [comment]
If it's only about Glibc, the maximum version required by the current compiled version of dcm2niix from Travis is 2.15 (for `__pow_finite`). So should also work on CentOS 7.

True that the newer Glibc could bring stability and performance improvement. But according to my experience, it's not easy to make it happen for HPC. For example, some of the HPCs I used just got updated to CentOS 7 from CentOS 6...

**Comment by kousu** [comment]
In my experimenting Ubuntu 14.04 and CentOS7 are about equally compatible. They have approximately equivalent EOL schedules:

* https://endoflife.software/operating-systems/linux/ubuntu#14-04-4-lts
* https://endoflife.software/operating-systems/linux/centos

And on my end, I didn't know about https://github.com/phusion/holy-build-box. It sounds like that project is doing the equivalent of running on CentOS 7, so if that's working for you then I'd say stick with it.
