### ISSUE TITLE
Siemens magnitude and phase DICOMs are converted into a single NIfTI file

### ISSUE THREAD

**Issue by gaspardcereza** [rordenlab/dcm2niix#414]
## Context
Hello, I am currently trying to convert some `DICOM` files acquired on a 7T Siemens Magneton Terra scanner using `dcm2niix`. I would like my phase and magnitude images to be separated in two different `NIfTI` files.

The problem I encounter is that when I run `dcm2niix` on a folder containing phase and magnitude DICOM files it only outputs one `NIfTI` file (and its corresponding `json` file) that gathers magnitude and phase. 

I think that might be related to the fact that these `DICOM` files don't have the exact same fields as most of the other I have seen (but I don't really now how `dcm2niix` usually separate `DICOM` files). Is there any way to chose how the different files are separated ?

 A field that could be used to separate phase and magnitude images is `ImageComments` that has the value `'flip angle map, TraRefAmpl: 400.0 V'` for the magnitude and `'relative phase map'` for the phase.

I found [that issue](https://github.com/rordenlab/dcm2niix/issues/408) that seems quite similar but with Philips data. You probably had a lot of similar issues opened but I couldn't find any solution to my problem... I hope I didn't miss any obvious solution.

## Data
Here are two DICOM files (one magnitude and one phase):
[RF_dicoms.zip](https://github.com/shimming-toolbox/shimming-toolbox-py/files/5018048/RF_dicoms.zip)

Here's the output I got when running `dcm2niix` on these files: 
``` 
Compression will be faster with pigz.exe in the same folder as the executable
Chris Rorden's dcm2niiX version v1.0.20200331  (JP2:OpenJPEG) (JP-LS:CharLS) MSC1900 (64-bit Windows)
Found 2 DICOM file(s)
Warning: All images appear to be a single slice - please check slice/vector orientation
Convert 2 DICOM as RF_dicoms\RF_dicoms_standard_20200221110129_106 (64x64x1x2)
Warning: Check that 2D images are not mirrored.
Conversion required 0.082000 seconds. 
```
It seems that the software detected an anomaly but couldn't separate the data.
Thank you.

**Comment by neurolabusc** [comment]
This is a limitation of your images, not my software. 

The images lack the optional (but crucial for disambiguation of complex component) tags  ImageType ([0008,0008](https://dicom.innolitics.com/ciods/enhanced-mr-image/enhanced-mr-image/00080008)) and ComplexImageComponent ([0008,9208](https://dicom.innolitics.com/ciods/enhanced-mr-image/enhanced-mr-image/00089208)). The Siemens private tag CsaImageHeaderInfo ([0029,1010](https://nipy.org/nibabel/dicom/siemens_csa.html)) does not include the tag `CC:ComplexAdd`. Therefore, there is no way to determine the image type from the DICOM header. 

It is possible that these tags were removed by an overly aggressive PACS or Anonymization step, so as a sanity check I would copy the images directly from the MRI console to a USB drive and see if those images include these tags. If that fails to resolve your issue, I would work with your Siemens Research Collaboration Manager to resolve why these useful tags were omitted by the scanner. I strongly suspect this latter explanation is more likely. The system is using development software (it reports `E12`, where even numbers are development and odd numbers are stable).

**Comment by jcohenadad** [comment]
> so as a sanity check I would copy the images directly from the MRI console to a USB drive and see if those images include these tags.

that's what we did for the images @gaspardcereza shared at the beginning of this issue thread-- so i guess we'll talk with siemens 😉 
thanks for the quick reply @neurolabusc !

**Comment by neurolabusc** [comment]
In the meantime, you could create a fork of dcm2niix or [dicm2nii](https://github.com/xiangruili/dicm2nii) that uses the  ImageComments ([0020,4000](http://dicomlookup.com/lookup.asp?sw=Tnumber&q=(0020,4000))) as @gaspardcereza suggests. This would be specific to your site, as this modification will have many unintended consequences if included in the main branch (e.g. ImageComments can be any user defined message, like `Phase 3 Clinical Trial`). Using a hex editor to compare the files shows there are no other tags that discriminate these scans.

**Comment by jcohenadad** [comment]
thanks for the suggestion-- i think we will take the "bandage" approach and simply volume-split the output nifti if our CLI's flag `--this-is-a-weird-siemens-dicom` is on. In the meantime we will also open a ticket on the Siemens IDEA's forum. I suspect we are not the only one in this situation (many users might have the same problem but don't report it).

**Comment by neurolabusc** [comment]
As a E11 user, I have a vested interest in seeing thorough beta testing by the brave E12 users. My understanding was that at some point the E-series will migrate from classic legacy DICOM to the enhanced DICOM pioneered by XA10. You may want to check your console and see if it provides export as Enhanced DICOM (image below shows XA10). The XA series saves much less meta data for legacy images relative to enhanced, and this may explain your issue. If enhanced DICOM is supported, make sure NOT to save EPI images as Mosaics (mosaics save disk space for classic legacy DICOM, but are poorly supported for Siemens enhanced DICOM). If enhanced is an option, presumably it will not include the CSA header, so you will want to test this format thoroughly to ensure it includes the needed meta data (and I assume you will lose the ability to [Phoenix](https://www.diagnosticimaging.com/view/embedded-protocols-mri-promise-productivity-boost-siemens-users) these images).

![xa11](https://user-images.githubusercontent.com/8930807/89319429-15d07e80-d64e-11ea-9f08-018d2aa6ee44.jpg)

**Comment by jcohenadad** [comment]
thanks for the tip @neurolabusc 👍
