### ISSUE TITLE
DICOM files with Icon Image Sequence where the icon has been purged

### ISSUE THREAD

**Issue by neurolabusc** [rordenlab/dcm2niix#415]
The Icon Image Sequence ([0088,0200](http://dicomlookup.com/lookup.asp?sw=Tnumber&q=(0088,0200))) is created so a DICOM image can be inserted into the DICOM file, with the icon stored in using the same PixelData ([7fe0,0010](http://dicomlookup.com/lookup.asp?sw=Tnumber&q=(7FE0,0010))) tag as other images. One expects thisPixelData to be stored before the Sequence Delimitation. Recent versions of dcm2niix have relaxed this expectation to deal with some mangled files. However, this has caused an unintended consequence with some images such as ADNI 941_S_6058. In this dataset, there is a IconImageSequence, but the sequence no longer contains any pixel data (presumably, the PixelData was selectively deleted to reduce file size or other complications, but the sequence itself remains). This confounds the current logic. As noted in issue [409](https://github.com/rordenlab/dcm2niix/issues/409), some icons use several levels of sequences to embed an icon, so the correct approach is to assume that the PixelData refers to the icon if it is at the same depth or deeper in a IconImageSequence. Once the delimiters un-nest the data beyond the depth of 0088,0200, one should no longer expect that the Pixel Data refers to the icon, but rather refers to the main image.  

In other words, the PixelData (7fe0,0010) shown in **bold** below has been removed, with the subsequent PixelData (7fe0,0010) which follows the delimiter referring to the main image, not the icon. Again, this seems legal, but as I recall my current method was required for some DICOMs that used implicit VR which were anonymized by tools that do not preserve the SQ limit and delist scheme. A much more elegant approach would have been to remove the entire  IconImageSequence (0088,0200), rather than only its PixelData. 

<pre>
...
(0088,0200) SQ (Sequence with explicit length #=1)      # 142, 1 IconImageSequence
  (fffe,e000) na (Item with explicit length #=11)         # 134, 1 Item
    (0028,0002) US 1                                        #   2, 1 SamplesPerPixel
    (0028,0004) CS [PALETTE COLOR]                          #  14, 1 PhotometricInterpretation
    (0028,0010) US 64                                       #   2, 1 Rows
    (0028,0011) US 64                                       #   2, 1 Columns
    (0028,0100) US 8                                        #   2, 1 BitsAllocated
    (0028,0101) US 8                                        #   2, 1 BitsStored
    (0028,0102) US 7                                        #   2, 1 HighBit
    (0028,0103) US 0                                        #   2, 1 PixelRepresentation
    (0028,1101) US 256\0\8                                  #   6, 3 RedPaletteColorLookupTableDescriptor
    (0028,1102) US 256\0\8                                  #   6, 3 GreenPaletteColorLookupTableDescriptor
    (0028,1103) US 256\0\8                                  #   6, 3 BluePaletteColorLookupTableDescriptor
    <b>(7fe0,0010) OW <4096 bytes> PixelData</b>
  (fffe,e00d) na (ItemDelimitationItem for re-encoding)   #   0, 0 ItemDelimitationItem
(fffe,e0dd) na (SequenceDelimitationItem for re-encod.) #   0, 0 SequenceDelimitationItem
(7fe0,0010) OW <401408 bytes> PixelData
</pre>

**Comment by Youguang** [comment]
When will next version of dcm2niix without this issue be released? I am in this problem, and turned to use older version.

**Comment by neurolabusc** [comment]
Typical stable release cadence is about once per 6 months. So presumably soon. However, there are two open issues that need to be addressed. In particular [issue 425](https://github.com/rordenlab/dcm2niix/issues/425) impacts translation of non-English characters. This has lots of potential for unintended consequences. All of the DICOM data at my site is restricted to English-characters, so it is hard to fully confirm the quality of the solution.
