### ISSUE TITLE
Anomalous ADNI Datasets

### ISSUE THREAD

**Issue by neurolabusc** [rordenlab/dcm2niix#416]
The Alzheimer’s Disease Neuroimaging Initiative ([ADNI](http://adni.loni.usc.edu)) provides carefully curated datasets. It has been brought to my attention that a few of these datasets have issues. These reflect issues with the datasets, not dcm2niix. Until the ADNI database is updated, human intervention will be required to censor or fix these images. Possible solutions are provided, but users should use their own judgement.

**019_S_4293 Series 901 fcMRI**

-  Issue: Instance number 4184 erroneously claims to "(0008,9208) CS [REAL]" whereas it and all other images are magnitude
-  Solution: Use "gdcmanon --dumb --remove 0008,9208 ..." to remove tag
-  Issue:  Instance number 4184 claims different echo time (30.0000991821289) vs others (30)
-  Solution: Use "-m y" to force merging despite variable TE

**006_S_6441 Series 901 fcMRI**

-  Issue: Image with instance number 549 is missing
- Issue: Images with instance numbers 9387..9456 are missing. Note that instance numbers are generated in the slice then time order (s1t1,s1t2...s1tn,s2t1...s2tn....sytn) rather than time then slice order (s1t1,s2t1...syt1, s1t2...).
-  Solution: Do not use this participant

 
**006_S_6277 Series 801 fcMRI** 

-  Issue: Only 8740 of the 9456 images are provided
-  Solution: Do not use this participant

 
**006_S_6243 Series 901 fcMRI** 

-  Issue: Only 8626 of the 9456 images are provided
-  Solution: Do not use this participant

**Comment by i3roly** [comment]
thank you for this information chris.

i have passed it on to the appropriate individuals as well.

**Comment by i3roly** [comment]
i should note the dates for the scans above to help userse.

019_S_4293 - 2018-06-15
006_S_6441 - 2019-08-19
006_S_6277 - 2018-03-28
006_S_6243 - 2019-04-01

the suggestion for 019_S_4293 did work (and well, i think)

however duplicating the 541st instance to 549 did not. it still outputs a skewed fMRI. any tips chris?

**Comment by neurolabusc** [comment]
Why not send me your attempt at a repaired instance 541.

By the way, I always find DICOM file names crazy, you can use the function
 dcm2niix -r y /path/to/dicom
To rename an individuals DICOMs. It will sort them by date, series number and name files by instance number and instance UID.

-c

Chris Rorden, PhD
Endowed Chair of Neuroimaging
Co-Director, McCausland Center for Brain Imaging
Department of Psychology
University of South Carolina
Columbia, SC 29208, USA
phone +1 803 404 2573
email rorden@sc.edu<mailto:rorden@sc.edu>
web www.mricro.com

On Aug 11, 2020, at 4:42 PM, gagan sidhu <notifications@github.com<mailto:notifications@github.com>> wrote:



i should note the dates for the scans above to help userse.

019_S_4293 - 2018-06-15
006_S_6441 - 2019-08-19
006_S_6277 - 2018-03-28
006_S_6243 - 2019-04-01

the suggestion for 019_S_4293 did work (and well, i think)

however duplicating the 541st instance to 549 did not. it still outputs a skewed fMRI. any tips chris?

**Comment by i3roly** [comment]
hi chris,

sent the link via email (it's sensitive data).

what i did was i opened the 541th instance (ADNI_006_S_6441_MR_Axial_fcMRI__EYES_OPEN___br_raw_20190820110042952_541_S862695_I1214057.dcm)
then copied it to
ADNI_006_S_6441_MR_Axial_fcMRI__EYES_OPEN___br_raw_20190820110042952_549_S862695_I1214057.dcm 
then i opened matlab and changed the dicom instance number to 549 for the copied file.

still getting the 
"Chris Rorden's dcm2niiX version v1.0.20200808  Clang10.0.1 x86-64 (64-bit MacOS)
Found 9386 DICOM file(s)
Slice positions repeated, but number of slices (9386) not divisible by number of repeats (195): missing images?
Hint: expected 48 locationsWarning: Interslice distance varies in this volume (incompatible with NIfTI format).
Using RWVSlope:RWVIntercept = 0.733333:0
 Philips Scaling Values RS:RI:SS = 0.733333:0:0.00919335 (see PMC3998685)
Convert 9386 DICOM as ./Axial_fcMRI_(EYES_OPEN)a (64x64x9386x1)
Unable to equalize slice distances: slice order not consistently ascending:
dx=[0 0 0 0 0 0 ...
"

issue (tried with -m y as well)

**Comment by neurolabusc** [comment]
Updated comments on 6441 above to details that it also has missing slices.
