### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by asadmalik85** [rordenlab/dcm2niix#421]
Dear Rorden Lab,

I just wanted to clarify if the sentence in license.txt "This Software has been developed for research purposes only and is not a clinical tool." means that the tool **must** not be used for clinical research?

Thanks for your help.

Best,
Asad

**Comment by neurolabusc** [comment]
The software uses a [2-Clause BSD license](https://opensource.org/licenses/BSD-2-Clause) that contains no restrictions on use of the software. However,  the software is **not** approved for clinical use. Permissions and compliance with applicable rules are the responsibility of the user. 

I use dcm2niix myself for clinical research on stroke. However, I do not use it to make clinical decisions regarding patient care.

**Comment by asadmalik85** [comment]
Thank you Chris for this clear response.
