### ISSUE TITLE
Is it possible to extract one or both magnitude image(s) from the phase map?

### ISSUE THREAD

**Issue by LeilaDar** [rordenlab/dcm2niix#423]
Hi everyone,

My goal is to conduct a distortion correction via fieldmap. Unfortunately, our Siemens scanner only acquired a phase map and no magnitude image. Is there any possibility to extract one or both magnitude image(s) from the phase map? Or is there any other possibility to conduct the distortion correction?

Thanks for your input!

**Comment by neurolabusc** [comment]
The role of dcm2niix is to losslessly convert the complicated DICOM format to the simpler NIfTI format. It does not change the images. 

I suggest you look at the [FUGUE guide](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FUGUE/Guide#Non-SIEMENS_data) to see how you can proceed if your scanner did not generate a magnitude image and a phase-difference map.
