### ISSUE TITLE
Different Dimension in NIFTI (Dicom acquired by  GE SIGNA Premier scanner)

### ISSUE THREAD

**Issue by h-w-k** [rordenlab/dcm2niix#426]
Dear all,

I am writing to seek your precious advices on the nifti dimensions.

In the GE SIGNA Premier Scanner, the sMRI protocol has the following settings: 
FOV: 24.0cm, 
phase: 240, 
magnitude: 240, 
slice thickness   >> 1cm
voxel size 1mm x1mm x1mm.

Using the latest release of dcm2niix (version 20200331), the converted image (nifti) has the following dimensions:
dim1: 512
dim2: 49
dim3; 512
pixdim1: 0.4688mm
pixdim2: 5mm
pixdim3: 0,4688mm

The image's voxel dimensions are different from the scanning protocols.

Please kindly advise how to fix the issue.

Thank you very much.

**Comment by neurolabusc** [comment]
dcm2niix is a lossless converter. It does not stretch a 256x256 matrix to 512x512. Is it possible that interpolation was turned on for the reconstruction. This will save 256x256 acquisitions as DICOMs of resolution 512x512. The resulting images will require x4 the disk space, and will be unsuitable for some tools (e.g. mrdegibbs). I would always turn off interpolation. Your description of slices is unclear. Unsure what is meant by the large slice thickness (1cm) and much smaller distance between slice centers (1mm). It is common to have a small gap between slices, but overlap can lead to interference effects. I suggest looking at your DICOM images with a DICOM viewer like HOROS, or examining the DICOM headers with dcmdump/gdcmdump to confirm the stored data.

For 3D acquisitions, dcm2niix will losslessly replica to the nearest orthogonal of the NIfTI identity matrix, so 49 sagittal images each of 512x512 will. be. saved as 512x49x512 (so slices are in the axial plane).

You could always try the latest development release, which does support the [GE ZIP2 interpolation](https://github.com/rordenlab/dcm2niix/issues/386).

Unix users can test the latest developmental commit:
```

git clone --branch development https://github.com/rordenlab/dcm2niix.git
cd dcm2niix/console
make
./dcm2niix


```Windows users should be able to get a compiled version from [AppVeyor](https://ci.appveyor.com/project/neurolabusc/dcm2niix).

**Comment by h-w-k** [comment]
Thank you very much for your advices. I will try the above  suggestions and seek your advices soon again.

Sorry for the typing mistake,  Slice thickness is 1mm  instead of 1cm.

**Comment by neurolabusc** [comment]
OK. I wonder if your slices are 1mm thick with a 4mm gap. That would explain the 5mm distance between voxel centers reported in the NIfTI header. It can be hard to determine [slice thickness](http://dclunie.blogspot.com/2013/10/how-thick-am-i-sad-story-of-lonely-slice.html) from [DICOM](https://stackoverflow.com/questions/14930222/how-to-calculate-space-between-dicom-slices-for-mpr/14944200) images. The robust method (used by dcm2niix) is to compare the  Image Position (0020,0032) from two adjacent slices.

**Comment by h-w-k** [comment]
Thank you so much. It is the first time I worked on GE images and i do find myself opening the derived image of T1 instead of the real T1.  Sorry for making the confusion.
 
I redo all the conversion and check the image again. Here come the results.
1. Used BIDS to find out the contents of the DICOM dataset. And there are 3 images related to T1.  

![sMRI_web_enquiry04](https://user-images.githubusercontent.com/66808713/93300808-1140dd80-f82a-11ea-8b25-84d468234d0f.png)

2. Converted DICOM using dcm2niix (version 2020 09 09). Also 3 images related to T1.
For the real T1 (3D_SAG_T1),
Image dimensions are (1mm x 0.4688mm x 0.4688mm)    
![sMRI_web_enquiry03](https://user-images.githubusercontent.com/66808713/93300854-274e9e00-f82a-11ea-9bf7-2c925f514b93.png)

For derived T1 images ( (MPR)_Ob_Cor_) and ( (MPR)_Ob_Ax_)
image dimensions are (0.4688mm x 5mm x 0.4688mm) and (0.4688mm  x 0.4688mm x 5mm) respectively

![sMRI_web_enquiry01](https://user-images.githubusercontent.com/66808713/93301040-6ed52a00-f82a-11ea-9f15-ff637037a49a.png)

![sMRI_web_enquiry02](https://user-images.githubusercontent.com/66808713/93301058-75fc3800-f82a-11ea-9596-00f00c29b621.png)

sMRI dimension in the scanning protocol is  1mm x 1mm x 1mm (confirmed on the MRI scanner console)
![sMRI_web_enquiry05](https://user-images.githubusercontent.com/66808713/93301653-56b1da80-f82b-11ea-9c4a-0d0f6de0946a.png)

What are the possibilities of the different dimensions shown in the real T1 image (1mm x 0.4688mm x 0.4688mm)? Should i try to turn off interpolation (thank you for your advice in the previous reply) in the scanner and see if it works? 

Thank you very much in advance for your generous help and precious advices.

**Comment by neurolabusc** [comment]
For future acquisitions I would turn off interpolation and the creation of derived images. You will be able to create better derived images after post processing (e.g. intensity homogeneity correction). 

For existing DICOM datasets, you can always use the dcm2niix option `-i y` to ignore conversion of derived series.
