### ISSUE TITLE
One series DICOMs got converted into 2 Nfiti files

### ISSUE THREAD

**Issue by HanyinWang** [rordenlab/dcm2niix#427]
Hi,

Thanks for the great software.

I was trying to convert a series of DICOMs using dcm2niix (v1.0.20190902), but I finally got 2 sets of nii.gz files (Brain_2__1_Brain_Without_Fast_20121125151338_2a.nii.gz & Brain_2__1_Brain_Without_Fast_20121125151338_2.nii.gz).

According to the previous solutions to similar problems, I tried to use the option -m y, but it didn't work. 

There are 33 DICOMs in total, they have the same (0020, 0011) Series Number IS: "2", the same (0018, 0050) Slice Thickness DS: "4.8", the same Transfer Syntax UID UI: Explicit VR Little Endian, the same (0002, 0013) Implementation Version Name  SH: 'AcuoWS6.0'. But 15 of them (Instance number 2,4,7,8,9,10,15,18,21,22,24,26,28,29,32) got transferred into one file and the rest got transferred into another. 

Thanks,
Hanyin

**Comment by neurolabusc** [comment]
I would always suggest using the latest stable [release (v1.0.20200331)](https://github.com/rordenlab/dcm2niix/releases). Often the output generated in the command line reveals why slices of a stack are not stacked. Is it possible these slices are not co-planar. The NIfTI standard requires all slices in a volume are co-planar. For DICOM series where this is not the case, the slices can not be stacked. Did you check if [Image Orientation  (0020,0037)](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.7.6.2.html) is identical for all slices?

**Comment by HanyinWang** [comment]
Thanks for the quick reply! I tried the new version but still got the same issue.
And yes, I checked all the 33 scans, they have exactly the same Image Orientation.

Here's the message I got:

`Chris Rorden's dcm2niiX version v1.0.20200331  (JP2:OpenJPEG) (JP-LS:CharLS) GCC5.5.0 (64-bit Linux)
Found 33 DICOM file(s)

Gantry Tilt based on 0018,1120 -15, estimated from slice vector 15
Warning: Note these images have gantry tilt of 15 degrees (manufacturer ID = 1)
Warning: Interslice distance varies in this volume (incompatible with NIfTI format).
Warning: Missing images? Expected 15 images, but instance number (0020,0013) ranges from 2 to 32
Warning: Siemens MoCo? Bogus slice timing (range -1..-1, TR=0 seconds)
Convert 15 DICOM as XXX_Brain_2__1_Brain_Without_Fast_20121125151338_2_e1 (512x512x15x1)
Gantry Tilt Correction is new: please validate conversions
Gantry Tilt based on 0018,1120 -15, estimated from slice vector 15
Warning: Note these images have gantry tilt of 15 degrees (manufacturer ID = 1)
Warning: Interslice distance varies in this volume (incompatible with NIfTI format).
Warning: Missing images? Expected 18 images, but instance number (0020,0013) ranges from 1 to 33
Warning: Siemens MoCo? Bogus slice timing (range -1..-1, TR=0 seconds)
Convert 18 DICOM as XXX_Brain_2__1_Brain_Without_Fast_20121125151338_2_e1a (512x512x18x1)
Gantry Tilt Correction is new: please validate conversions
Conversion required 5.920422 seconds (2.450000 for core code).`

Thanks,
Hanyin

**Comment by neurolabusc** [comment]
I suspect that you are attempting to merge two different mediaObjectInstanceUIDs (0002,0003). You can check this with dcmdump or gdcmdump. Alternatively, convert your images with the media object instance in the output filename:
 
```
  dcm2niix -f %s_j%j_k%k_o%o /Path/To/DICOMS 
```

If this is the case, and the two sets of images really belong to the same series, you will want to check the provenance of your images and determine at what stage they were separated. Combining slices with different UIDs is catastrophic (the most common example is tools that corrupt Siemens field maps). 

If I am correct, I suspect some tool (e.g. anonymization) corrupted your images. If the images really came off the. scanner this way, you will need to work with your Siemens collaboration managers to resolve the issue. As a Hail Mary you could remove or unify this tag using gdcmanon, e.g.

```
gdcmanon --dumb --remove 0002,0003 -i ... -o ...
```

**Comment by neurolabusc** [comment]
@HanyinWang does this resolve your issue? If not can you send a sample via DropBox/GoogleDrive to my email (listed in avatar).
