### ISSUE TITLE
Philips dicom fMRI timeseries get converted in 3D in stead of 4D files.

### ISSUE THREAD

**Issue by treanus** [rordenlab/dcm2niix#428]
I have a rather old (2 year old) dicom dataset exported from a Philips system. Running the latest locally compiled dcm2niix results in converting the dicoms into multiple 3D files, e.g.

DICOM_WIP_Main_Pavlovian_TR2_MB2_20200112142318_501_t324000.nii    DICOM_WIP_rsfMRI_TR1_20200112142318_401_t91000.nii
DICOM_WIP_Main_Pavlovian_TR2_MB2_20200112142318_501_t326000.json   DICOM_WIP_rsfMRI_TR1_20200112142318_401_t92000.json
DICOM_WIP_Main_Pavlovian_TR2_MB2_20200112142318_501_t326000.nii    DICOM_WIP_rsfMRI_TR1_20200112142318_401_t92000.nii
DICOM_WIP_Main_Pavlovian_TR2_MB2_20200112142318_501_t328000.json   DICOM_WIP_rsfMRI_TR1_20200112142318_401_t93000.json
DICOM_WIP_Main_Pavlovian_TR2_MB2_20200112142318_501_t328000.nii    DICOM_WIP_rsfMRI_TR1_20200112142318_401_t93000.nii

An older version of dcm2niix (v1.0.20181125) does convert them into a single 4D file.

Is there any option I can specify to get the 4D behavior?
Furthermore, I'm actually using dcm2bids which calls dcm2niix automatically. Would need to make an alias in bash, I suppose.

Thanks in advance for any help.

**Comment by neurolabusc** [comment]
This sounds like a replication of [issue 408](https://github.com/rordenlab/dcm2niix/issues/408). Specifically, your files have a bogus value for [cardiac trigger time (0018,1060)](http://dicomlookup.com/lookup.asp?sw=Tnumber&q=(0018,1060)). This is a limitation of your images, not dcm2niix. You should work with your Philips Research Collaboration manager to fix your scanner. For archival-quality data you could purge the invalid tags from your images, e.g. `gdcmanon --dumb --remove 0018,1060  -i ... -o ..`.

Alternatively, you could try the developmental release of dcm2niix which contains a kludge to handle these images. However, while this will convert your DICOMs, it will not repair them, and strictly speaking they are not valid DICOMs.

Unix users can test the latest developmental commit:

```
git clone --branch development https://github.com/rordenlab/dcm2niix.git
cd dcm2niix/console
make
./dcm2niix


```
Windows users should be able to get a compiled version from [AppVeyor](https://ci.appveyor.com/project/neurolabusc/dcm2niix) (click on the Artifacts button).

**Comment by treanus** [comment]
I confirm, it is the cardiac trigger time (0018,1060).
The latest development branch does convert these images in to 4D files.
This issue can be closed. Thank you!
