### ISSUE TITLE
Siemens Vida DICOMS - slice timing corrupted and BOLD task stacking warnings

### ISSUE THREAD

**Issue by brainnetworklab** [rordenlab/dcm2niix#429]
Hi rordenlab,

Thank you for an amazing product. Long time user!

We recently started acquiring data on a new Siemens Vida (software version syngo MR XA20). I've read what I can about issues with mosaics/enhanced dicoms. As far as I know, our MR techs are exporting in enhanced dicom format. The scanner shows the correct number of volumes sent, but then shows then shows a different number of "instances" sent. When i use dcm2niix to process all of the dicoms, i am getting the following warnings:

Chris Rorden's dcm2niiX version v1.0.20200331  (JP2:OpenJPEG) (JP-LS:CharLS) GCC5.5.0 (64-bit Linux)
Found 4388 DICOM file(s)
Warning: Slice timing appears corrupted (range 9375..10067.5, TR=800 ms)
Convert 668 DICOM as ./TASK_ep2d_bold_mb8h (88x88x72x668)
Compress: "/usr/bin/pigz" -b 960 -n -f -6 "./TASK_ep2d_bold_mb8h.nii"
Warning: Slice timing appears corrupted (range 9687.5..10380, TR=800 ms)
Convert 1115 DICOM as ./BOLD_SMS8_LR (88x104x72x1115)
Compress: "/usr/bin/pigz" -b 960 -n -f -6 "./BOLD_SMS8_LR.nii"
Warning: Slice timing appears corrupted (range 0..5275, TR=800 ms)
Convert 3 DICOM as ./TASK_ep2d_bold_mb8i (88x88x72x3)
Compress: "/usr/bin/pigz" -b 960 -n -f -6 "./TASK_ep2d_bold_mb8i.nii"
Warning: Slice timing appears corrupted (range 9375..10067.5, TR=800 ms)
Convert 514 DICOM as ./TASK_ep2d_bold_mb8j (88x88x72x514)
Compress: "/usr/bin/pigz" -b 960 -n -f -6 "./TASK_ep2d_bold_mb8j.nii"
Convert 1 DICOM as ./TASK_ep2d_bold_mb8k (180x668x1x1)
Warning: Check that 2D images are not mirrored.
Compress: "/usr/bin/pigz" -n -f -6 "./TASK_ep2d_bold_mb8k.nii"
Warning: Slice timing appears corrupted (range 9687.5..10382.5, TR=800 ms)
Convert 1115 DICOM as ./BOLD_SMS8_RL (88x104x72x1115)
Compress: "/usr/bin/pigz" -b 960 -n -f -6 "./BOLD_SMS8_RL.nii"
Slices not stacked: echo varies (TE 7.65, 5.19; echo 1, 1). Use 'merge 2D slices' option to force stacking
Warning: Slice timing appears corrupted (range 752.5..752.5, TR=752 ms)
Convert 72 DICOM as ./gre_field_mapping_e1 (92x104x72x1)
Compress: "/usr/bin/pigz" -b 960 -n -f -6 "./gre_field_mapping_e1.nii"
Warning: Slice timing appears corrupted (range 0..0, TR=752 ms)
Convert 72 DICOM as ./gre_field_mapping_e1a (92x104x72x1)
Compress: "/usr/bin/pigz" -b 960 -n -f -6 "./gre_field_mapping_e1a.nii"
Warning: Slice timing appears corrupted (range 0..5275, TR=800 ms)
Convert 1 DICOM as ./TASK_ep2d_bold_mb8l (88x88x72x1)
Compress: "/usr/bin/pigz" -b 960 -n -f -6 "./TASK_ep2d_bold_mb8l.nii"
Slices not stacked: orientation varies (vNav or localizer?) [0.999962 0.008727 -3.855e-11 6.97088e-10 -8.42915e-08 -1] != [1 4.897e-12 0 -4.897e-12 1 0]
Warning: Slice timing appears corrupted (range 12670..12670, TR=11 ms)
Convert 5 DICOM as ./LOC_i00006 (192x192x5x1)
Compress: "/usr/bin/pigz" -n -f -6 "./LOC_i00006.nii"
Warning: Slice timing appears corrupted (range 17422.5..17422.5, TR=11 ms)
Convert 5 DICOM as ./LOC_i00001 (192x192x5x1)
Compress: "/usr/bin/pigz" -n -f -6 "./LOC_i00001.nii"
Warning: Slice timing appears corrupted (range 4750..4750, TR=11 ms)
Convert 5 DICOM as ./LOC_i00011 (192x192x5x1)
Compress: "/usr/bin/pigz" -n -f -6 "./LOC_i00011.nii"
Convert 176 DICOM as ./MP2RAGE (240x256x176x1)
Compress: "/usr/bin/pigz" -b 960 -n -f -6 "./MP2RAGE.nii"
Convert 176 DICOM as ./t2_space_sag_p4_isoa (256x256x176x1)
Compress: "/usr/bin/pigz" -b 960 -n -f -6 "./t2_space_sag_p4_isoa.nii"
Warning: Slice timing appears corrupted (range 752.5..752.5, TR=752 ms)
Convert 72 DICOM as ./gre_field_mapping_ph (92x104x72x1)
Compress: "/usr/bin/pigz" -b 960 -n -f -6 "./gre_field_mapping_ph.nii"
Convert 176 DICOM as ./MP2RAGEa (240x256x176x1)
Compress: "/usr/bin/pigz" -b 960 -n -f -6 "./MP2RAGEa.nii"
Warning: Slice timing appears corrupted (range 0..5275, TR=800 ms)
Convert 1 DICOM as ./TASK_ep2d_bold_mb8m (88x88x72x1)
Compress: "/usr/bin/pigz" -b 960 -n -f -6 "./TASK_ep2d_bold_mb8m.nii"
Convert 1 DICOM as ./TASK_ep2d_bold_mb8n (180x514x1x1)
Warning: Check that 2D images are not mirrored.
Compress: "/usr/bin/pigz" -n -f -6 "./TASK_ep2d_bold_mb8n.nii"
Convert 176 DICOM as ./MP2RAGEb (240x256x176x1)
Compress: "/usr/bin/pigz" -b 960 -n -f -6 "./MP2RAGEb.nii"
Warning: Slice timing appears corrupted (range 0..5275, TR=800 ms)
Convert 3 DICOM as ./TASK_ep2d_bold_mb8o (88x88x72x3)
Compress: "/usr/bin/pigz" -b 960 -n -f -6 "./TASK_ep2d_bold_mb8o.nii"
Conversion required 61.537841 seconds (8.807456 for core code).

We've also been having a problem exporting our files to our PACS system and OSIRIX  since the BOLD files are no longer in mosaic form, it overwhelms the system as each volume is sent separately. We are working with our Siemens rep on these issues. I mention this as I'm sure someone else will come looking for answers in the near future with the new Siemens software update, but wonder if you can offer a suggestion as to what we can do about the warnings in the meantime?

Thank you in advance for your help. Appreciate all you do!

**Comment by neurolabusc** [comment]
@brainnetworklab I have never seen XA20 data, though I have seen XA10, XA11 and prototype XA30 data. Can you see if the latest development branch (v1.0.20200909) is able to extract the slice times. You can compile it on Linux using the commands:

```
git clone --branch development https://github.com/rordenlab/dcm2niix.git
cd dcm2niix/console
make
./dcm2niix
```

If that does not work, can you share a sample series with me (email in avatar) using DropBox or Google Drive? This looks like a large dataset, but I just need a single series of fMRI data. You can rename DICOM images so different series are saved in different folders using the `-r y `option, e.g. `dcm2niix -r y /path/to/DICOMs`

**Comment by brainnetworklab** [comment]
Thank you for your rapid response. I tried the development version and unfortunately ran into the same problem. Is there an an anonymizer you'd prefer I use that you trust so I can upload the data? I always have just anonyimzed when converting to niftis.

**Comment by neurolabusc** [comment]
1. I only need around 10 sequential images from series 8 (TASK_ep2d_bold_mb). Unlike the T1/T2, these do not retain facial features
2. Rename DICOM images so it is easy to identify series 8
a.
   dcm2niix -r y -f /%s/%p/%4r.dcm /Path/To/DICOMs
b. Remove all new folders except for "8"
c. In Folder 8, remove all *.dcm files except 0001.dcm..0010.dcm
d. Anonymize data
```
gdcmanon --dumb --remove 400,500 --remove 12,62 --remove 12,63   --remove 0010,0010   --remove 0010,0020   --remove 0010,0040   --remove 0010,1010   --remove 0010,1030   --remove 0010,0030   -i 0001.dcm -o 0001.dcm
gdcmanon --dumb --remove 400,500 --remove 12,62 --remove 12,63   --remove 0010,0010   --remove 0010,0020   --remove 0010,0040   --remove 0010,1010   --remove 0010,1030   --remove 0010,0030   -i 0002.dcm -o 0002.dcm
gdcmanon --dumb --remove 400,500 --remove 12,62 --remove 12,63   --remove 0010,0010   --remove 0010,0020   --remove 0010,0040   --remove 0010,1010   --remove 0010,1030   --remove 0010,0030   -i 0003.dcm -o 0003.dcm
gdcmanon --dumb --remove 400,500 --remove 12,62 --remove 12,63   --remove 0010,0010   --remove 0010,0020   --remove 0010,0040   --remove 0010,1010   --remove 0010,1030   --remove 0010,0030   -i 0004.dcm -o 0004.dcm
gdcmanon --dumb --remove 400,500 --remove 12,62 --remove 12,63   --remove 0010,0010   --remove 0010,0020   --remove 0010,0040   --remove 0010,1010   --remove 0010,1030   --remove 0010,0030   -i 0005.dcm -o 0005.dcm
gdcmanon --dumb --remove 400,500 --remove 12,62 --remove 12,63   --remove 0010,0010   --remove 0010,0020   --remove 0010,0040   --remove 0010,1010   --remove 0010,1030   --remove 0010,0030   -i 0006.dcm -o 0006.dcm
gdcmanon --dumb --remove 400,500 --remove 12,62 --remove 12,63   --remove 0010,0010   --remove 0010,0020   --remove 0010,0040   --remove 0010,1010   --remove 0010,1030   --remove 0010,0030   -i 0007.dcm -o 0007.dcm
gdcmanon --dumb --remove 400,500 --remove 12,62 --remove 12,63   --remove 0010,0010   --remove 0010,0020   --remove 0010,0040   --remove 0010,1010   --remove 0010,1030   --remove 0010,0030   -i 0008.dcm -o 0008.dcm
gdcmanon --dumb --remove 400,500 --remove 12,62 --remove 12,63   --remove 0010,0010   --remove 0010,0020   --remove 0010,0040   --remove 0010,1010   --remove 0010,1030   --remove 0010,0030   -i 0009.dcm -o 0009.dcm
gdcmanon --dumb --remove 400,500 --remove 12,62 --remove 12,63   --remove 0010,0010   --remove 0010,0020   --remove 0010,0040   --remove 0010,1010   --remove 0010,1030   --remove 0010,0030   -i 0010.dcm -o 0010.dcm
```
e. Send images to my email (noted in avatar). You can use GoogleDrive,DropBox,etc to share a zip archive, alternatively, rename the file archive.zip to archive.zap and send to my email as an attachment (my institution will reject zip files sent as direct attachments to emails).

**Comment by brainnetworklab** [comment]
Great! Thank you. I sent the data to your email.

**Comment by brainnetworklab** [comment]
The new development version worked perfectly. Thanks again!
