### ISSUE TITLE
Error Message Received When Converting From Database

### ISSUE THREAD

**Issue by agbelden** [rordenlab/dcm2niix#433]
Hello,

I've been experiencing an issue with data I have downloaded from the ADNI database. This is not happening consistently, but for a number of participants we keep receiving the error message "Warning: Assuming 7FE0,0010 refers to an icon not the main image" followed by "No valid DICOM images were found." This problem has persisted when downloading the data from various browsers and on different computers, and the support staff from the database says everything is fine when they use their internal converter. I was hoping you might have insight into what may be causing the issue, and how to best rectify it. Thanks!

**Comment by neurolabusc** [comment]
Replication of [issue 415](https://github.com/rordenlab/dcm2niix/issues/415). Also see [issue 416](https://github.com/rordenlab/dcm2niix/issues/416) when dealing DICOMs from ADNI.
