### ISSUE TITLE
-x flag not working

### ISSUE THREAD

**Issue by ramonemiliani93** [rordenlab/dcm2niix#434]
Hi, I am having trouble keeping the origin while transforming a series. Even though I use the `-x` flag with `i` I get the same results.

**Comment by neurolabusc** [comment]
I do not understand your issue. 

The -x argument only influences 3D acquisitions (ensuring slice timing is preserved for 2D sequences). For these scans, if you look at the BIDS JSON file it should report `"MRAcquisitionType": "3D",`.  Consider the 3D T1 scan from here:

If we tell dcm2niix to ignore the transform, the sagittal slices are saved in NIfTI in the same order as the DICOMs (AIL):
```
dcm2niix -x i ~/Desktop/uih
fslhd uih_t1_gre_fsp_3d_sag_134431_2.nii
...
dim1		460
dim2		512
dim3		160
...
sform_code	1
sto_xyz:1	0.002297 0.012944 0.999649 -75.002533 
sto_xyz:2	-0.499994 0.000941 0.004547 111.779350 
sto_xyz:3	0.000882 0.499832 -0.025896 -130.818298 
sto_xyz:4	0.000000 0.000000 0.000000 1.000000 
sform_xorient	Anterior-to-Posterior
sform_yorient	Inferior-to-Superior
sform_zorient	Left-to-Right
```

If we tell dcm2niix not to ignore the transform, but also not to crop the image, the image is resliced to match the identity transform of the NIfTI s-form (LPI):
```
dcm2niix -x n ~/Desktop/uih
fslhd uih_t1_gre_fsp_3d_sag_134431_2a.nii
...
dim1		160
dim2		460
dim3		512
...
sto_xyz:1	0.999649 -0.002297 0.012944 -73.948166 
sto_xyz:2	0.004547 0.499994 0.000941 -117.717873 
sto_xyz:3	-0.025896 -0.000882 0.499832 -130.413361 
sto_xyz:4	0.000000 0.000000 0.000000 1.000000 
sform_xorient	Left-to-Right
sform_yorient	Posterior-to-Anterior
sform_zorient	Inferior-to-Superior
```

These are lossless transforms, the volume is rotated by 90-degrees. The residual values for the rotation are stored in the s-form. Therefore, the transform of both indicates the same voxel. The data is **identical** for any tool that respects the s-form, we have merely permuted the rows/columns/slices. The results should not change, only the order that the data is stored to disk.

**Comment by ramonemiliani93** [comment]
Chris, I greatly appreciate your fast and thorough response. I think the issue arises from my misunderstanding of how the flag works. At the moment, I have a DICOM series of 3DFLAIR images with a DICOM RT associated. When I proceed to convert the series both the origin and the direction change hence the information on the DICOM RT has a spatial mismatch. Is there a way to keep the same origin and direction? I tried to follow the response you gave here: [dcm2niix reorients all images to RPI, origins are changed
](https://www.nitrc.org/forum/forum.php?thread_id=9324&forum_id=4703)

**Comment by neurolabusc** [comment]
dcm2niix is lossless. It preserves the origin and spatial information. Note that DICOM and NIfTI [encode space differently](https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#Spatial_Coordinates), which might explain your confusion.
