### ISSUE TITLE
CT nrrd fails

### ISSUE THREAD

**Issue by emmanuels7** [rordenlab/dcm2niix#436]
Hi. What would be the best way to transform a dicom folder to a nrrd file. 

All options available produces corrupted files.

My curren options configuration are the next: 

` .\dcm2niix.exe -f venous -9 -b n -e y -p y -r n "C:\Users\venous"`

Regards

**Comment by neurolabusc** [comment]
What version of dcm2niix are you using? Every time you run the software it reports the version. I would suggest the latest stable release [v1.0.20200331](https://github.com/rordenlab/dcm2niix/releases). What output is generated? How is the file corrupt - can you open it with MRIcroGL? Have you tried converting some of the validation [DICOM datasets](https://github.com/neurolabusc/dcm_qa) to determine if this is an issue with your DICOMs or the conversion?

**Comment by emmanuels7** [comment]
Hi.

Thanks for your response. I am using v1.0.20200331
Yes. I can open and visualize those files with MRIcroGL.
Not working with validation DICOM datasets

Thats how images looks like:
![image](https://user-images.githubusercontent.com/52512792/96284684-ee7e2200-0fab-11eb-96ea-dd5513d1323d.png)

The parameters used
![image](https://user-images.githubusercontent.com/52512792/96284763-0d7cb400-0fac-11eb-91dc-974cd1748866.png)

**Comment by neurolabusc** [comment]
Can you share the DICOMs with me privately (send link to Box, DropBox, GoogleDrive, etc. to email address shown in my avatar).

**Comment by emmanuels7** [comment]
Hi @neurolabusc.

Thanks a lot for your help, but that wouldn't be possible because of EPR issues. 

Do we have other sets of options to keep testing by ourselves? 

Again thanks a lot.

**Comment by neurolabusc** [comment]
1. When you convert a file, output is generated on a panel to the left of your screenshot for parameters used. Can you show me what the software reported for this image?

2. When you say `Not working with validation DICOM datasets` can you describe how those images fail? Those are all open source images, so if we can replicate problems with those, we can fix your issue. However, on my computer they all convert to NRRD files without issue.

**Comment by neurolabusc** [comment]
Closing issue. Unable to replicate and no diagnostics provided. A good place to start would be to look at the messages generated on the right side of the import panel (or by using dcm2niix from the command line). This should provide hints for unusual images.

![info](https://user-images.githubusercontent.com/8930807/96505515-3c9d5a80-1224-11eb-9661-3f1cab9ababd.png)
