### ISSUE TITLE
"Validate vectors" warning

### ISSUE THREAD

**Issue by baxpr** [rordenlab/dcm2niix#442]
https://www.dropbox.com/s/ci5ptv779tn7hmk/IM_0002?dl=0
Here is a DICOM obtained directly from a Philips scanner that gives this warning:

`Warning: Saving 7 DTI gradients. Validate vectors (image slice orientation not reported, e.g. 2001,100B).`

What to make of it? I couldn't figure out quite what the practical implications are. Many of our diffusion images are giving us this now.

**Comment by neurolabusc** [comment]
This is a warning, not an error. You may want to acquire your own [validation dataset](https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#Diffusion_Tensor_Imaging) to ensure gradient vectors are correctly transformed from the private vendor tags to the FSL bvec/bval format.

ImageOrientationPatient (0020,0037) suggests this is an axial scan. However, your scans differ from the [reference Philips DWI](https://github.com/neurolabusc/dcm_qa_philips) datasets, which were only acquired as axial slices. As your images are missing the private Philips slice orientation tag (2001,100B), it seems logically possible that they represent coronal or sagittal sequences. No exemplars of those scans have been tested for Philips.

**Comment by baxpr** [comment]
@neurolabusc thanks. I'm guessing the DICOM tags might have seen this minor change at a recent software upgrade, or something like that.
