### ISSUE TITLE
FLAIR image with corresponding bval/bvec files

### ISSUE THREAD

**Issue by dlevitas** [rordenlab/dcm2niix#449]
I believe this in relation to #393, but wanted to clarify. I've got what appears to be a FLAIR acquisition (though only 2D) with bval and bvec files (all values are zero). My thought is that this is some form of localizer and should be disregarded, but want to double check before proceeding. I've shared the specific dicoms through Google Drive.

Thanks,

Dan

**Comment by neurolabusc** [comment]
Your sample DICOMs include the private tag [0043,1039)](https://www.na-mic.org/wiki/NAMIC_Wiki:DTI:DICOM_for_DWI_and_DTI) which suggests it does not have a b-weighted. dcm2niix infers that this might be a b=0 series used for spatial undistortion with TOPUP. In your case, this is a false positive, as this is not a diffusion sequence despite the presence of 0043,1039. I would suggest you just ignore the bvec/bval file created. For the developmental branch I have changed the heuristic for GE data so the image must both have a b-value associated with it as well as being an EPI sequence ([0018,9018](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.8.13.4.html)). This will avoid your exemplar of a false alarm, though risks missing true diffusion sequences where 0018,9018 is not provided. 

@mr-jaemin do you have a preferred method for determining if a GE DICOM series is from a diffusion sequence (including series where all volumes are b=0)?

**Comment by mr-jaemin** [comment]
You could use the private tag "Vas collapse flag" (0043, 1030) SS. 

For DTI, the values should be 14 (T2) or 16 (DTI including b0 with gradient (0, 0, 0). For DWI, the values should be 14 (T2) or one of the following values depending on diffusion gradient direction applied:

// Diffusion image type values for the diffusion direction annotation field (0x0043,0x1030)
DiffusionRightLeftDicomValue = 3;
DiffusionAnteriorPosteriorDicomValue = 4;
DiffusionSuperiorInferiorDicomValue = 5;
DiffusionObliqueRightLeftDicomValue = 9;
DiffusionObliqueAnteriorPosteriorDicomValue = 10;
DiffusionObliqueSuperiorInferiorDicomValue = 11;
DiffusionT2DicomValue = 14;
DiffusionCombinedDicomValue = 15;
DiffusionDtiDicomValue = 16;
DiffusionDirection1DicomValue = 43;
DiffusionDirection2DicomValue = 44;
DiffusionDirection3DicomValue = 45;
DiffusionDirection4DicomValue = 46;

DTI_ADC = 20
DTI_FA = 18
DTI_T2W = 19

Alternately, For EPI, you can re-use this logic in the sliceTimingGE:
(This criteria doesn't apply to PROFELLER Diffusion (DWI, not DTI)
// Diffusion
else if ( (d->epiVersionGE == 2) || (d->internalepiVersionGE == 2) || (strstr(ioptGE,"DIFF") != NULL) )

**Comment by dlevitas** [comment]
Great, thanks. Should I also disregard the FLAIR acquisition, since it appears to be a 2D slice?

**Comment by dlevitas** [comment]
I recant my earlier statement -- I realize now that the FLAIR is anisotropic. All good here, thanks!
