### ISSUE TITLE
cxx issue compiler issue

### ISSUE THREAD

**Issue by leej3** [rordenlab/dcm2niix#450]
I am driving the dcm2niix as part of the AFNI build. On certain systems I get an error when trying to compile dcm2niix.

An example command (Fedora 30, cmake 3.17.2):
```
export CC=`which gcc`
export CXX=`which g++`
cmake -GNinja -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX /path/to/src
ninja
```

Any ideas? 

<details open>
<summary>Error message</summary>
<br>
/crorden/dcm2niix_console/CMakeFiles/dcm2niix.dir/nii_dicom.cpp.o src/crorden/dcm2niix_console/CMakeFiles/dcm2niix.dir/jpg_0XC3.cpp.o src/crorden/dcm2niix_console/CMakeFiles/dcm2niix.dir/ujpeg.cpp.o src/crorden/dcm2niix_console/CMakeFiles/dcm2niix.dir/nifti1_io_core.cpp.o src/crorden/dcm2niix_console/CMakeFiles/dcm2niix.dir/nii_foreign.cpp.o src/crorden/dcm2niix_console/CMakeFiles/dcm2niix.dir/nii_ortho.cpp.o src/crorden/dcm2niix_console/CMakeFiles/dcm2niix.dir/nii_dicom_batch.cpp.o  -o targets_built/dcm2niix_afni  -Wl,-rpath,:::::::::::::::: && :
/usr/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
</details>

**Comment by neurolabusc** [comment]
@ningfei is the cmake expert, so I am sure he has insight. Is /path/to/src the parent folder 'dcm2niix' or the folder 'dcm2niix/console'? The parent folder CMakeLists.txt links to the Superbuild which supports several DICOM transfer syntaxes OpenJPEG for JPEG2000; CharLS for JPEG-LS) and the enhanced CloudFlare zlib.

**Comment by leej3** [comment]
Thanks Chris. I was unclear: /path/to/src is the AFNI code repository. The dcm2niix cmake build is configured at configure time of the AFNI project:
https://github.com/afni/afni/blob/b7f60bb333e8c148ba8f1cda19a0cc5fc22d6d90/src/CMakeLists.txt#L75

I suspect it is likely some rpath/compiler flag that I am setting/not setting that is breaking your build. 

Note it is not the master branch of this repo (it is stored in the AFNI repository directly).

**Comment by ningfei** [comment]
@leej3  The error msg said -lstdc++ load error. Have you tried to set CMake option `USE_STATIC_RUNTIME` to `OFF`? i.e., use shared stdc++ lib instead of static one.

**Comment by leej3** [comment]
That is it. Thank you!

**Comment by ningfei** [comment]
Great! As Chris wrote [here](https://github.com/rordenlab/dcm2niix/blob/master/COMPILE.md#user-content-trouble-shooting), you will need to install `libstdc++-static` if you want to use the static runtime, which is on by default in the CMake option.

**Comment by leej3** [comment]
Didn't spot that. Good to know. Thanks
