### ISSUE TITLE
question regarding magnitude & phase(diff) field map acquisitions

### ISSUE THREAD

**Issue by dlevitas** [rordenlab/dcm2niix#451]
I've got an acquisition (shared via Google Drive) that I believe is considered case 3 of the BIDS spec for field maps (i.e. 2 magnitude images and 2 phase images). I'm not particularly familiar with these however, and was hoping for clarification on this. Assuming this is the case, is this how dcm2niix performs the labeling?

```
*_e1.nii.gz (magnitude1)
*_e1_ph.nii.gz (phase1)
*_e2.nii.gz (magnitude2)
*_e2_ph.nii.gz (phase2)
```

Thanks for the help.

**Comment by neurolabusc** [comment]
Precisel. Variation in the JSON files can also reveal whether the images are phase/magnitude and the echo number:
```
"ImageType": ["ORIGINAL", "PRIMARY", "T1", "NONE"],
"ImageType": ["ORIGINAL", "PRIMARY", "T1", "NONE", "PHASE"],
"EchoNumber": 1,
"EchoNumber": 2,
```

I note your images are from [ADNI](http://adni.loni.usc.edu/data-samples/data-types/mri/). I provide notes on some of their field maps [here](https://www.mccauslandcenter.sc.edu/crnl/tools/fieldmap).

**Comment by dlevitas** [comment]
Perfect, thanks for the explanation!
