### ISSUE TITLE
Question regarding PhaseEncodingDirection

### ISSUE THREAD

**Issue by dlevitas** [rordenlab/dcm2niix#452]
I've noticed that the JSON files produced by dcm2niix don't always contain the `PhaseEncodingDirection` field, which I assume means this information wasn't stored in the DICOM header. Are there any other values that can be used to determine this field, or does it have to come from the DICOM? 

Asking because I have a DWI acquisition where I'd like to specify the `_dir-` BIDS field if possible. Data comes from a Philips scanner, which I've heard doesn't generally store this info in the DICOM header.

**Comment by neurolabusc** [comment]
There is no public DICOM tag for specifying phase encoding polarity. GE and Siemens provide private tags with this information, but Philips does not. This is described in the Missing Information section of the [dcm2niix Philips notes](https://github.com/rordenlab/dcm2niix/tree/master/Philips). This is a limitation of Philips DICOMs, not dcm2niix. I suggest you lobby your Philips research collaboration manager to have this information provided in future scanner software.
