### ISSUE TITLE
Possibly incorrect RepetitionTimeExcitation in multiple sequences

### ISSUE THREAD

**Issue by dagra** [rordenlab/dcm2niix#457]
Hi,

As I was checking the field `RepetitionTimeExcitation` in the latest release, I noticed that if I convert a lot of sequences at once and for one of them the field is filled, then for some of the remaining series the field is also filled with the same value (which seems incorrect), but if I convert each sequence separately, then the field is filled only for the one that seems correct and it's missing from the others. I also checked the latest development branch and the output is the same. So, is it possible that an initialization is missing somewhere or I get something wrong?

**Comment by neurolabusc** [comment]
@dagra can you check the latest solution from the development branch. This should resolve your issue.

**Comment by dagra** [comment]
I checked the latest solution and the problem seems resolved. Great, thanks!
