### ISSUE TITLE
Which dcm2niix version is fully BIDS-compliant

### ISSUE THREAD

**Issue by dlevitas** [rordenlab/dcm2niix#464]
I was looking through the dcm2niix version [change logs](https://github.com/rordenlab/dcm2niix/releases), and it appears that the BIDS sidecar output become an addition sometime in 2016-2017 with the `-b y` option. I understand that over the years, additional fields in the sidecar have become required for BIDS compliancy. I was wondering what's the oldest dcm2niix version that would produce BIDS compliant output, by today's BIDS standard?

Thanks,

Dan

**Comment by neurolabusc** [comment]
The answer depends on the vendor and the sequence. Early versions had good support for vendor `Siemens` and typical fMRI, T1, DWI data. More recent releases have provided a lot more meta data for the vendor `GE` and nascent BIDS [BEPS](https://bids.neuroimaging.io/get_involved) like ASL and PET. As usual, this is an evolution as we reverse engineer the required information. More recent releases have also begun to support enhanced DICOM from `Philips` and `Siemens` (XA).

**Comment by neurolabusc** [comment]
Closing this question. It is a bit like asking when the [War of 1812](https://en.wikipedia.org/wiki/War_of_1812#Treaty_of_Ghent) ended (when the treaty was signed in 1814, or the battles ended in 1815), or whether you can put your foot in the same river twice. dcm2niix was the reference software used for the original BIDS release, but the BIDS standard has evolved, manufacturer data has evolved, and our understanding of the manufacturer meta data has improved.
