### ISSUE TITLE
dcm2niix -v returns exit code 3 on Linux

### ISSUE THREAD

**Issue by kytk** [rordenlab/dcm2niix#469]
I use dcm2niiX version v1.0.20201102  (JP2:OpenJPEG) (JP-LS:CharLS) GCC5.5.0 x86-64 (64-bit Linux).

I have just noticed that `dcm2niix -v` returns exit code 3 on Linux.

```
dcm2niix -v
echo $?
```

Are there any reason it returns 3 instead of 0?
(dcm2niix -h returns 0.)

I found it when I used bash kernel on Jupyter-notebook.
"Run All" on Jupyter-notebook stopped at `dcm2niix -v`
I think Jupyter-notebook considered that `dcm2niix -v` returned an error.

**Comment by neurolabusc** [comment]
This is the intended behavior. This helps debug scripts where the user was expecting output files, but dcm2niix thought that only a version string was required. It also allows scripts to know that the request for a version string was detected: if an executable does not return exit code 3 for `executablename -v` it is not a valid version of dcm2niix. 

For completeness, the exit codes are:

0. EXIT_SUCCESS
1. EXIT_FAILURE (unspecified)
2. EXIT_NO_VALID_FILES_FOUND
3. EXIT_REPORT_VERSION
4. EXIT_CORRUPT_FILE_FOUND
5. EXIT_INPUT_FOLDER_INVALID
6. EXIT_OUTPUT_FOLDER_INVALID
7. EXIT_OUTPUT_FOLDER_READ_ONLY
8. EXIT_SOME_OK_SOME_BAD 
9. EXIT_RENAME_ERROR

**Comment by kytk** [comment]
Thank you for clear explanation!
