### ISSUE TITLE
dcm2niix 1.0.20201224 release tag is gone

### ISSUE THREAD

**Issue by chenrui333** [rordenlab/dcm2niix#470]
👋  it looks like the release tag is gone? Just raise this issue to confirm it is intended, thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/67572

**Comment by neurolabusc** [comment]
This was an unintended consequence of my attempts to deal with [issue 467](https://github.com/rordenlab/dcm2niix/issues/467). The current stable release is [v1.0.20201102](https://github.com/rordenlab/dcm2niix/releases/tag/v1.0.20201102). Version v1.0.20201224 exists only on the unstable branch. Stable releases are reviewed by others, beyond the automatic testing done with each commit. Typically there are two stable releases per year (spring, fall).

**Comment by chenrui333** [comment]
I got you, thanks for clarifying it.
