### ISSUE TITLE
dcm2niix output JSON format issue

### ISSUE THREAD

**Issue by rvangala936** [rordenlab/dcm2niix#472]
Hi,
  dcm2niix generates a Json file that has data format issues. Please find below DICOM tag causes the issues along with a generated JSON file output. 

Can you please look into this issue?

Ex: If the **DICOM** has a Tag like shown below(note the Value has data on separate lines):

================================================================
 **Tag=(0008, 0081), Desc=InstitutionAddress, VR=ST, Value=200
Rochester/
MN
US**
================================================================

Then **dcm2niix** generates the JSON as follows but it is NOT a valid JSON:

================================================================
{
  "Manufacturer": "ABC",
  "ManufacturersModelName": "ModelName",
  "InstitutionName": "TEST",
  **"InstitutionAddress": "200
  Rochester_
  MN
  US",**
  "DeviceSerialNumber": "00000",
  "SoftwareVersions": "CT_2011A",
  "BodyPartExamined": "ABDOMEN",
  "ProtocolName": "IRB_09_000702_LD_ENTEROG",
  "ImageType": ["ORIGINAL", "PRIMARY", "AXIAL", "CT", "SOM5", "SPI"],
  "AcquisitionTime": "07:43:11.010000",
  "XRayExposure": 68,
  "PhaseEncodingLines": 512,
  "ConversionSoftware": "dcm2niix",
  "ConversionSoftwareVersion": "v1.0.20170624 (OpenJPEG build) GCC4.8.4"
}
================================================================

**Comment by neurolabusc** [comment]
You are using a release that is more than 3 years old. Does the [current stable version](https://github.com/rordenlab/dcm2niix/releases) resolve your issue?

**Comment by rvangala936** [comment]
Latest version worked. Thank you very much for quick and prompt response. 

Best Regards
Ravindar Vangala
