### ISSUE TITLE
dcm2niix creates 2 "channel" nifti

### ISSUE THREAD

**Issue by vpapaioannou** [rordenlab/dcm2niix#475]
**Describe the bug**
I have 2X dcm files of size axb and at the output I get one nifti file where the image is stored as [a, b, X, 2] whereas I would expect [a, b, 2X] as usual.

**To Reproduce**
Run as `./bin/dcm2niix_Linux --terse -w 1 -z y -m y -b n -o ...` and the files in total are 874 if the amount plays a role.

**Expected behavior**
One nifti file where the image is stored as [a, b, 2X].

**Output Log**
Chris Rorden's dcm2niiX version v1.0.20200331  (JP2:OpenJPEG) GCC4.8.2 (64-bit Linux)
Found 2X DICOM file(s)
Warning: Assuming icon SQ 07a3,10ce.
...
Swizzling 3rd and 4th dimensions (XYTZ -> XYZT), assuming interslice distance is 0.625000

**Comment by neurolabusc** [comment]
Please upgrade to the [latest stable release](https://github.com/rordenlab/dcm2niix/releases), as this changes the formula for dealing with DICOM images corrupted by a GEIIS PACS system. I would trace the provenance of your DICOMs and archive images that have not been corrupted. Corrupted images are not of archival quality and will result in unpredictable behavior with many tools. Please follow the instructions provided by the `New Issue` template:

 - Is this the [latest stable release](https://github.com/rordenlab/dcm2niix/releases)? If not, does the latest stable release resolve your issue?
 - If the latest stable version fails, and you are using Windows. Does the latest commit on the development branch resolve your issue? You can get a pre-compiled version from [AppVeyor](https://ci.appveyor.com/project/neurolabusc/dcm2niix) (click on the Artifacts button).
 - If the latest stable version fails, and you are using macOS or Linux. Does the latest commit on the development branch resolve your issue? You can build this using the recipe below:

```
git clone --branch development https://github.com/rordenlab/dcm2niix.git
cd dcm2niix/console
g++ -O1 -g -fsanitize=address -fno-omit-frame-pointer  -I.  main_console.cpp nii_foreign.cpp nii_dicom.cpp jpg_0XC3.cpp ujpeg.cpp nifti1_io_core.cpp nii_ortho.cpp nii_dicom_batch.cpp  -o dcm2niix -DmyDisableOpenJPEG
./dcm2niix ....
```

**Comment by vpapaioannou** [comment]
Thanks!
