### ISSUE TITLE
dcm_qa_nih tests fail if ran on development branch (1.0.20200427+git100-ge32fb1b)

### ISSUE THREAD

**Issue by yarikoptic** [rordenlab/dcm2niix#479]
Sorry about the delay with providing feedback on the state of development branch.  Not sure what is going on and could be operator (mine) error somehow (but git submodules with test data seems to be in the state they should be) but trying to build a debian package from the state of development

```shell
$> git describe --tags development 
v1.0.20200427-100-ge32fb1b
```

results in following failures
```
I: Running tests under dcm_qa_nih
Running command:
dcm2niix -b y -z n -f %p_%s -o /build/dcm2niix-1.0.20200427+git100-ge32fb1b/dcm_qa_nih/Out /build/dcm2niix-1.0.20200427+git100-ge32fb1b/dcm_qa_nih/In
Chris Rorden's dcm2niiX version v1.0.20210124  (JP2:OpenJPEG) GCC10.2.1 x86-64 (64-bit Linux)
Found 608 DICOM file(s)
ASSET= 1 PE_AcquisitionMatrix= 64 ESP= 388 TotalReadoutTime= 0.024444
Convert 150 DICOM as /build/dcm2niix-1.0.20200427+git100-ge32fb1b/dcm_qa_nih/Out/Axial_EPI-FMRI_(Interleaved_S_to_I)_6 (64x64x15x10)
Warning: Adjusting for negative MosaicRefAcqTimes (issue 271).
Convert 2 DICOM as /build/dcm2niix-1.0.20200427+git100-ge32fb1b/dcm_qa_nih/Out/EPI_PE=RL_5 (72x72x5x2)
ASSET= 1 PE_AcquisitionMatrix= 64 ESP= 388 TotalReadoutTime= 0.024444
Convert 150 DICOM as /build/dcm2niix-1.0.20200427+git100-ge32fb1b/dcm_qa_nih/Out/Axial_EPI-FMRI_(Interleaved_I_to_S)_4 (64x64x15x10)
Warning: Adjusting for negative MosaicRefAcqTimes (issue 271).
Convert 2 DICOM as /build/dcm2niix-1.0.20200427+git100-ge32fb1b/dcm_qa_nih/Out/EPI_PE=PA_4 (72x72x5x2)
ASSET= 1 PE_AcquisitionMatrix= 64 ESP= 388 TotalReadoutTime= 0.024444
Convert 150 DICOM as /build/dcm2niix-1.0.20200427+git100-ge32fb1b/dcm_qa_nih/Out/Axial_EPI-FMRI_(Sequential_S_to_I)_7 (64x64x15x10)
Warning: Adjusting for negative MosaicRefAcqTimes (issue 271).
Convert 2 DICOM as /build/dcm2niix-1.0.20200427+git100-ge32fb1b/dcm_qa_nih/Out/EPI_PE=LR_6 (72x72x5x2)
Warning: Adjusting for negative MosaicRefAcqTimes (issue 271).
Convert 2 DICOM as /build/dcm2niix-1.0.20200427+git100-ge32fb1b/dcm_qa_nih/Out/EPI_PE=AP_3 (72x72x5x2)
ASSET= 1 PE_AcquisitionMatrix= 64 ESP= 388 TotalReadoutTime= 0.024444
Convert 150 DICOM as /build/dcm2niix-1.0.20200427+git100-ge32fb1b/dcm_qa_nih/Out/Axial_EPI-FMRI_(Sequential_I_to_S)_5 (64x64x15x10)
Conversion required 0.333695 seconds (0.316577 for core code).
Running command:
diff -x '.*' -br /build/dcm2niix-1.0.20200427+git100-ge32fb1b/dcm_qa_nih/Ref /build/dcm2niix-1.0.20200427+git100-ge32fb1b/dcm_qa_nih/Out -I ConversionSoftwareVersion
diff -x ''\''.*'\''' -br -I ConversionSoftwareVersion /build/dcm2niix-1.0.20200427+git100-ge32fb1b/dcm_qa_nih/Ref/Axial_EPI-FMRI_(Interleaved_I_to_S)_4.json /build/dcm2niix-1.0.20200427+git100-ge32fb1b/dcm_qa_nih/Out/Axial_EPI-FMRI_(Interleaved_I_to_S)_4.json
16c16
<       "SeriesDescription": "Axial EPI-FMRI (Interleaved I to S)",
---
>       "SeriesDescription": "DCM2NIIX regression test",
37d36
<       "EffectiveEchoSpacing": 0.000388,
38a38
>       "EstimatedEffectiveEchoSpacing": 0.000388,
diff -x ''\''.*'\''' -br -I ConversionSoftwareVersion /build/dcm2niix-1.0.20200427+git100-ge32fb1b/dcm_qa_nih/Ref/Axial_EPI-FMRI_(Interleaved_S_to_I)_6.json /build/dcm2niix-1.0.20200427+git100-ge32fb1b/dcm_qa_nih/Out/Axial_EPI-FMRI_(Interleaved_S_to_I)_6.json
16c16
<       "SeriesDescription": "Axial EPI-FMRI (Interleaved S to I)",
---
>       "SeriesDescription": "DCM2NIIX regression test",
37d36
<       "EffectiveEchoSpacing": 0.000388,
38a38
>       "EstimatedEffectiveEchoSpacing": 0.000388,
diff -x ''\''.*'\''' -br -I ConversionSoftwareVersion /build/dcm2niix-1.0.20200427+git100-ge32fb1b/dcm_qa_nih/Ref/Axial_EPI-FMRI_(Sequential_I_to_S)_5.json /build/dcm2niix-1.0.20200427+git100-ge32fb1b/dcm_qa_nih/Out/Axial_EPI-FMRI_(Sequential_I_to_S)_5.json
16c16
<       "SeriesDescription": "Axial EPI-FMRI (Sequential I to S)",
---
>       "SeriesDescription": "DCM2NIIX regression test",
37d36
<       "EffectiveEchoSpacing": 0.000388,
38a38
>       "EstimatedEffectiveEchoSpacing": 0.000388,
diff -x ''\''.*'\''' -br -I ConversionSoftwareVersion /build/dcm2niix-1.0.20200427+git100-ge32fb1b/dcm_qa_nih/Ref/Axial_EPI-FMRI_(Sequential_S_to_I)_7.json /build/dcm2niix-1.0.20200427+git100-ge32fb1b/dcm_qa_nih/Out/Axial_EPI-FMRI_(Sequential_S_to_I)_7.json
16c16
<       "SeriesDescription": "Axial EPI-FMRI (Sequential S to I)",
---
>       "SeriesDescription": "DCM2NIIX regression test",
37d36
<       "EffectiveEchoSpacing": 0.000388,
38a38
>       "EstimatedEffectiveEchoSpacing": 0.000388,
```

**Comment by neurolabusc** [comment]
These differences reflect improvements in the upcoming release for dcm2niix to GE. The results are different because they are better.
 1. Prior releases inserted the ProtocolName for the SeriesDescription when converting  GE MRI [see issue 476](https://github.com/rordenlab/dcm2niix/issues/476). The upcoming release preserves both SeriesDescription and ProtocolName.
 2. Jesper Andersson, Jaemin Shin, and Brice Fernandez updated the formula for EchoSpacing and TotalReadOutTime. The formula is described in the file ./GE/README.md.

So the results are expected to be different.

**Comment by yarikoptic** [comment]
I might be missing something, but shouldn't then tests be adjusted to reflect that improvement along side with the improvement?

**Comment by neurolabusc** [comment]
@yarikoptic prior to a stable release I ask users with large datasets to test the release candidate with their own datasets and their own calling methods. The goal is to prevent situations like your [issue 465](https://github.com/rordenlab/dcm2niix/issues/465) where you detected a [problem](https://github.com/rordenlab/dcm2niix/pull/448) with the last stable release that was not detected by any of the default tests.

Every commit of dcm2niix is automatically evaluated with these default tests:
 
 - [dcm_qa](https://github.com/neurolabusc/dcm_qa) 
 - [dcm_qa_nih](https://github.com/neurolabusc/dcm_qa_nih)
 - [dcm_qa_uih](https://github.com/neurolabusc/dcm_qa_uih)

Every stable release must also pass these tests:

 - [dcm_qa_agfa](https://github.com/neurolabusc/dcm_qa_agfa)
 - [dcm_qa_toshiba](https://github.com/neurolabusc/dcm_qa_toshiba)
 - [dcm_qa_stc](https://github.com/neurolabusc/dcm_qa_stc)
 - [dcm_qa_enh](https://github.com/neurolabusc/dcm_qa_enh)
 - [dcm_qa_asl](https://github.com/neurolabusc/dcm_qa_asl)
 - [dcm_qa_me](https://github.com/neurolabusc/dcm_qa_me)
 - [dcm_qa_philips](https://github.com/neurolabusc/dcm_qa_philips)
 - [dcm_qa_canon](https://github.com/neurolabusc/dcm_qa_canon)
 - dcm_qa_enh (an enhanced DICOM test too large for GitHub)

If new features are added to dcm2niix that improve the output, the default tests will report these and return a failure. Failure means things are dfiferent. A submodule is only updated with a stable release, the "passing" behavior is always that of the current stable release. This allows developers to see changes they should expect, and also allows developers to debate the modifications. For example, FSL has an unintuitive definition of TotalReadoutTime that must be tested across partial Fourier, acceleration, interpolation, etc. In the current release cycle we proposed several changes and let Jaemin, Brice and Jesper approve them. 

In the current issue, you are reporting a change detected by the dcm_qa_nih submodule, which is a default test. All developers are aware that changes to this test are [flagged](https://travis-ci.org/github/rordenlab/dcm2niix/jobs/756777186) with the current commits.

The goal of this excercise would be for you to evaluate the release candidate with your own datasets and calling conventions to see if you discover any unintended consequences.
