### ISSUE TITLE
Siemens mosaic series of BOLD and DTI into individual/multi-slice dicoms

### ISSUE THREAD

**Issue by skimcnmc** [rordenlab/dcm2niix#482]
We want to convert Siemens mosaic series of BOLD and DTI into individual/multi-slice dicoms.

Does dcm2niix help this before dicom2nifti conversion?

If not, could you suggest approaches to convert mosaic into separate dicoms per slice?

Please let us know.

Thank you.

**Comment by neurolabusc** [comment]
@skimcnmc this is beyond the scope of dcm2niix's remit. Individual slices will have to report not only the individual image position patient (0020,0032) but also adapt the proprietary [CSA headers](https://nipy.org/nibabel/dicom/siemens_csa.html). The opportunity for errors seems large. I am not sure what you are trying to achieve, but implementing this properly will not be trivial. You may want to contact your Siemens Research Collaboration Manager to see if they have tools for this task.
