### ISSUE TITLE
JSON keys with dots (periods)

### ISSUE THREAD

**Issue by neurolabusc** [rordenlab/dcm2niix#483]
The BIDS standard stores values in JSON key-value pairs. Users are allowed to define their own filenames (keys) as long as they are not defined. At the request of the Oxford [BASIL](https://github.com/physimals/basil) team, recent versions of dcm2niix now copy a large number of fields from the Siemens [CSA header](https://nipy.org/nibabel/dicom/siemens_csa.html) to the BIDS sidecar. I copied the filenames verbatim. However, it has been brought to my attention that a few of these include a dot in the key name, and that this confounds usage with tools like Matlab and JavaScript (which requires square bracket syntax to handle these). For example:

```
	"sWipMemBlock.AdFree3": -25,
	"sWipMemBlock.AdFree4": 25,
	"sWipMemBlock.AdFree5": 25,
	"sWipMemBlock.AdFree6": 25,
	"sWipMemBlock.AdFree7": -25,
	"sWipMemBlock.AdFree8": -25,
	"sWipMemBlock.AdFree9": 25,
	"sWipMemBlock.AdFree10": -25,
```

I would like to suggest that we simply remove the dot from these keys, e.g. `sWipMemBlockAdFree7`. However, I would like to make sure that no one feels strongly about this change.

I know that @satra has raised concerns about [sanitizing information](https://github.com/rordenlab/dcm2niix/issues/425), and in general I try to avoid changes that might impact other code. @effigies  and @mcraig-ibme might have thoughts on this.

**Comment by effigies** [comment]
The other thing I could see is promoting to an object and getting

```json
    "sWipMemBlock": {"AdFree3": -25, ...}
```

Not sure if that would collapse onto some other notation that produces objects...

**Comment by pvelasco** [comment]
For what is worth, `AdFree` (in the Siemens programming environment) is an array of doubles that the programmer can use for whatever they need. So maybe it would make sense to just make it a list (or a tuple):

```python
	"sWipMemBlock.AdFree4": [-25, 25, 25, 25, -25, -25,...]
```

**Comment by neurolabusc** [comment]
Closing this. The upcoming version will remove the dots.
