### ISSUE TITLE
Keeping series time tag after conversion

### ISSUE THREAD

**Issue by lidialuq** [rordenlab/dcm2niix#484]
Hi Chris, 
Great software! An issue I'm having: When processing data I need to have the (0008,0031) Series Time tag, which is not a part of the Nifti header. -f %t gives the study time, which doesn't help since I need to differentiate between series. Is there any way of keeping this tag after the conversion, be it in the json file, file name or otherwise?

**Comment by neurolabusc** [comment]
dcm2niix will populate the key `AcquisitionTime` in the BIDS JSON sidecar using the value from the DICOM Tag [0008,0032](http://dicomlookup.com/lookup.asp?sw=Tnumber&q=(0008,0032)). I believe the Acquisition Time is preferable to the Series Time, as it occurs after the variable length shimming time.

**Comment by lidialuq** [comment]
Interesting. I run dcm2niix with this command `dcm2niix -f '%d' -ba n -o path\to\output`. The json files I get do not have the AcquisitionTime key. I'm attaching the (anonymized) json file. The dicom files do have this key, am I missing something in the command, maybe? 
[AX_SWAN_(hemo).txt](https://github.com/rordenlab/dcm2niix/files/6050462/AX_SWAN_.hemo.txt)

**Comment by neurolabusc** [comment]
@lidialuq I believe this reflects anonymization applied to the DICOMs before they were seen by dcm2niix. GE DICOMs should [AcquisitionTime](https://github.com/neurolabusc/dcm_qa_stc). It is interesting that [SeriesTime](https://dicom.innolitics.com/ciods/pet-image/pet-series/00080031) is Type 1 (required) while [AcquisitionTime](https://dicom.innolitics.com/ciods/cr-image/general-image/00080032) is Type 3 (optional). So there might be some sense in recording the former. However, I am confident that if you check the provenance of your images, you will find that this attribute got stripped from the data at some stage.

**Comment by lidialuq** [comment]
This is the relevant part of the header of one of the dicom files in this series, after anonymization: 

(0008,0030) Study Time                                        125400
(0008,0031) Series Time                                        130553
(0008,0032) Acquisition Time                                130554
(0008,0033) Content Time                                    130554

These files are the input to dcm2niix, there is no processing step in between. 
I'm having the same problem with all series, which include series from other manufacturers (philips). I do get the warning "Unable to determine manufacturer (0008,0070), so conversion is not tuned for vendor" (which is because of the anonymization). Not sure if this have anything to do with the issue.

**Comment by neurolabusc** [comment]
I would strongly encourage you to use anonymization tools that preserve manufacturer name and vendor specific private tags. Without this information, you will get impoverished output. Meta data like slice timing, phase encoding polarity, etc. may be lost. The stripped DICOMs may not be of archival quality.

**Comment by lidialuq** [comment]
Makes sense, but unfortunaly for this data I don't have access to the original files. All DICOM files have the Acquisition Time key in the header though, do you still think it's anonymization that is causing the issue?

**Comment by lidialuq** [comment]
I tryed with other non-anonymized data and the tag appears in the json file. I'll just have to live with it, but at least now I know it will work on other data. Thanks for your help!
