### ISSUE TITLE
Windows 10 

### ISSUE THREAD

**Issue by Gresliebear** [rordenlab/dcm2niix#485]
**Describe the bug**

Traceback (most recent call last):
  File ".\dcm2nifti.py", line 62, in <module>
    convert_dcm_2_nii_x(dcm_folder, output_folder)
  File ".\dcm2nifti.py", line 28, in convert_dcm_2_nii_x
    converter.run()
  File "D:\L_pipe\pipeline_env\lib\site-packages\nipype\interfaces\base\core.py", line 434, in run
    runtime = self._run_interface(runtime)
  File "D:\L_pipe\pipeline_env\lib\site-packages\nipype\interfaces\dcm2nii.py", line 445, in _run_interface
    runtime, correct_return_codes=(0, 1,)
  File "D:\L_pipe\pipeline_env\lib\site-packages\nipype\interfaces\base\core.py", line 827, in _run_interface
    runtime = run_command(runtime, output=self.terminal_output)
  File "D:\L_pipe\pipeline_env\lib\site-packages\nipype\utils\subprocess.py", line 137, in run_command
    _process()
  File "D:\L_pipe\pipeline_env\lib\site-packages\nipype\utils\subprocess.py", line 124, in _process
    res = select.select(streams, [], [], timeout)
OSError: [WinError 10038] An operation was attempted on something that is not a socket

**To Reproduce**
1. Run the command 'dcm2niix ...'
2. See error ...

**Expected behavior**

**Output Log**
If applicable, output generated converting data.

** Version (please complete the following information):**
 - dcm2niix version string, e.g. `dcm2niiX version v1.0.20201207  Clang12.0.0 ARM (64-bit MacOS)` The version string is always the first line generated when dcm2niix is run.
 - Is this the [latest stable release](https://github.com/rordenlab/dcm2niix/releases)? If not, does the latest stable release resolve your issue?
 - If the latest stable version fails, and you are using Windows. Does the latest commit on the development branch resolve your issue? You can get a pre-compiled version from [AppVeyor](https://ci.appveyor.com/project/neurolabusc/dcm2niix) (click on the Artifacts button).
 - If the latest stable version fails, and you are using macOS or Linux. Does the latest commit on the development branch resolve your issue? You can build this using the recipe below:

```
git clone --branch development https://github.com/rordenlab/dcm2niix.git
cd dcm2niix/console
g++  -I.  main_console.cpp nii_foreign.cpp nii_dicom.cpp jpg_0XC3.cpp ujpeg.cpp nifti1_io_core.cpp nii_ortho.cpp nii_dicom_batch.cpp  -o dcm2niix -DmyDisableOpenJPEG
./dcm2niix ....
```

**Comment by neurolabusc** [comment]
There is no evidence that this has anything to do with dcm2niix.

I am unfamiliar with the Python script `dcm2nifti.py`. Please contact the developer who created that script. You may want to try running dcm2niix from the command line
```
dcm2niix c:\path\to\DICOMs
```
To convert your images without using Python. You might also want to use the graphical interface of [MRIcroGL](https://www.nitrc.org/plugins/mwiki/index.php/mricrogl:MainPage): the Import menu's `Convert DICOM to NIfTI` may help.
