### ISSUE TITLE
test failures on ppc64el

### ISSUE THREAD

**Issue by aqw** [rordenlab/dcm2niix#486]
I am packaging dcm2niix v1.0.20201102 with GCC8.3.0 on Debian buster on IBM POWER8 systems (ppc64el). The build succeeds, but a few tests fail.

```
Running command:
diff -x '.*' -br /tmp/port/dcm2niix-1.0.20201102/dcm_qa_uih/Ref /tmp/port/dcm2niix-1.0.20201102/dcm_qa_uih/Out -I ConversionSoftwareVersion
Binary files /tmp/port/dcm2niix-1.0.20201102/dcm_qa_uih/Ref/dti_tra_dir16_AP_9_134431.nii and /tmp/port/dcm2niix-1.0.20201102/dcm_qa_uih/Out/dti_tra_dir16_AP_9_134431.nii differ
Binary files /tmp/port/dcm2niix-1.0.20201102/dcm_qa_uih/Ref/dti_tra_dir16_PA_6_134431.nii and /tmp/port/dcm2niix-1.0.20201102/dcm_qa_uih/Out/dti_tra_dir16_PA_6_134431.nii differ
Binary files /tmp/port/dcm2niix-1.0.20201102/dcm_qa_uih/Ref/dti_tra_dir16_PA_rot_12_132222.nii and /tmp/port/dcm2niix-1.0.20201102/dcm_qa_uih/Out/dti_tra_dir16_PA_rot_12_132222.nii differ
Binary files /tmp/port/dcm2niix-1.0.20201102/dcm_qa_uih/Ref/dti_tra_dir16_PA_rot_12_134431.nii and /tmp/port/dcm2niix-1.0.20201102/dcm_qa_uih/Out/dti_tra_dir16_PA_rot_12_134431.nii differ
Binary files /tmp/port/dcm2niix-1.0.20201102/dcm_qa_uih/Ref/t1_gre_fsp_3d_sag_2_134431.nii and /tmp/port/dcm2niix-1.0.20201102/dcm_qa_uih/Out/t1_gre_fsp_3d_sag_2_134431.nii differ
E: Tests in following batteries have failed: dcm_qa_uih 
```

Diffing the output of `fslhd` for those files:
```
< filename       /tmp/port/dcm2niix-1.0.20201102/dcm_qa_uih/Ref/dti_tra_dir16_AP_9_134431.nii
---
> filename       /tmp/port/dcm2niix-1.0.20201102/dcm_qa_uih/Out/dti_tra_dir16_AP_9_134431.nii
```
```
< filename       /tmp/port/dcm2niix-1.0.20201102/dcm_qa_uih/Ref/dti_tra_dir16_PA_6_134431.nii
---
> filename       /tmp/port/dcm2niix-1.0.20201102/dcm_qa_uih/Out/dti_tra_dir16_PA_6_134431.nii
```
```
< filename       /tmp/port/dcm2niix-1.0.20201102/dcm_qa_uih/Ref/dti_tra_dir16_PA_rot_12_132222.nii
---
> filename       /tmp/port/dcm2niix-1.0.20201102/dcm_qa_uih/Out/dti_tra_dir16_PA_rot_12_132222.nii
```
```
< filename       /tmp/port/dcm2niix-1.0.20201102/dcm_qa_uih/Ref/dti_tra_dir16_PA_rot_12_134431.nii
---
> filename       /tmp/port/dcm2niix-1.0.20201102/dcm_qa_uih/Out/dti_tra_dir16_PA_rot_12_134431.nii
```
```
< filename       /tmp/port/dcm2niix-1.0.20201102/dcm_qa_uih/Ref/t1_gre_fsp_3d_sag_2_134431.nii
---
> filename       /tmp/port/dcm2niix-1.0.20201102/dcm_qa_uih/Out/t1_gre_fsp_3d_sag_2_134431.nii

< qto_xyz:1      0.999654  -0.002297  0.012944  -73.948166
---
> qto_xyz:1      0.999654  -0.002297  0.012944  -73.948181

< sto_xyz:1      0.999649  -0.002297  0.012944  -73.948166
---
> sto_xyz:1      0.999649  -0.002297  0.012944  -73.948181
```

Four have identical headers, but one is slightly different on the Z-axis.

Thoughts or suggestions? I'm happy to provide additional logs or info if it would help. :-)

---Alex

**Comment by aqw** [comment]
Diffing the output of `xxd` for each of the files yields the following:

dti_tra_dir16_AP_9_134431.nii:
```
17c17
< 00000100: 5d88 7a3c 78f1 7fbf a12e 68b9 e95d f242  ].z<x.....h..].B
---
> 00000100: 5d88 7a3c 78f1 7fbf a22e 68b9 e95d f242  ].z<x.....h..].B
20c20
< 00000130: 6666 862f 2625 d8c2 ca73 cf3d 451d 4b3b  ff./&%...s.=E.K;
---
> 00000130: 000f 4d2f 2625 d8c2 ca73 cf3d 451d 4b3b  ..M/&%...s.=E.K;
```
dti_tra_dir16_PA_6_134431.nii:
```
17c17
< 00000100: 5d88 7a3c 78f1 7fbf a12e 68b9 e95d f242  ].z<x.....h..].B
---
> 00000100: 5d88 7a3c 78f1 7fbf a22e 68b9 e95d f242  ].z<x.....h..].B
20c20
< 00000130: 6666 862f 2625 d8c2 ca73 cf3d 451d 4b3b  ff./&%...s.=E.K;
---
> 00000130: 000f 4d2f 2625 d8c2 ca73 cf3d 451d 4b3b  ..M/&%...s.=E.K;
```
dti_tra_dir16_PA_rot_12_132222.nii:
```
20c20
< 00000130: 6666 86b1 206d 0dc3 1242 bc3d a9c3 2ebd  ff.. m...B.=....
---
> 00000130: 0b26 4db1 206d 0dc3 1242 bc3d a9c3 2ebd  .&M. m...B.=....
```
dti_tra_dir16_PA_rot_12_134431.nii:
```
20c20
< 00000130: 0000 0080 d289 99c2 b2a1 c73d ac1e e33c  ...........=...<
---
> 00000130: 8801 daaf d289 99c2 b2a1 c73d ac1e e33c  ...........=...<
```
t1_gre_fsp_3d_sag_2_134431.nii:
```
17,21c17,21
< 00000100: c70a 6fba d61f 543c 6ac8 153b 76e5 93c2  ..o...T<j..;v...
< 00000110: 8d6f ebc2 d269 02c3 02e9 7f3f 288b 16bb  .o...i.....?(...
< 00000120: 6112 543c 76e5 93c2 d1fe 943b 35ff ff3e  a.T<v......;5..>
< 00000130: 40c7 763a 8d6f ebc2 9623 d4bc ae43 67ba  @.v:.o...#...Cg.
< 00000140: ebe9 ff3e d269 02c3 0000 0000 0000 0000  ...>.i..........
---
> 00000100: c70a 6fba d71f 543c 6ac8 153b 78e5 93c2  ..o...T<j..;x...
> 00000110: 8d6f ebc2 d269 02c3 03e9 7f3f 288b 16bb  .o...i.....?(...
> 00000120: 6212 543c 78e5 93c2 d1fe 943b 35ff ff3e  b.T<x......;5..>
> 00000130: 41c7 763a 8d6f ebc2 9723 d4bc ae43 67ba  A.v:.o...#...Cg.
> 00000140: ece9 ff3e d269 02c3 0000 0000 0000 0000  ...>.i..........
```

Trying to convert this to anything meaningful is a bit beyond me. But I hope identifying the altered offsets helps you. ;-)

**Comment by neurolabusc** [comment]
See [issue 327](https://github.com/rordenlab/dcm2niix/issues/327)

1. The diff error with the filenames simply reflects that sone image is in the folder `Out` and the other in the folder `Ref`.
2. I suspect the sub-voxel difference in the spatial transform probably just reflects differences in rounding errors for floating point. For example, some compilers will use fused multiply add instructions on some machines which reduces rounding relative to computing the multiply and add instructions sequentially. Likewise, old Intel FPU instructions used 80-bits internally whereas modern SIMD instructions use 64-bits. 
3. This is a big-endian machine, and dcm2niix saves the image data in the machines native format. Therefore, you should not expect the .nii files to be identical to a little-endian machine. For validation purposes, you can force dcm2niix to generate NIfTI data with an explicit byte-order, so `dcm2niix --big-endian n /path/to/dicoms` should generate little-endian images regardless of 
```
  --big-endian : byte order (y/n/o, default o) [y=big-end, n=little-end, o=optimal/native]
```
If you look at the [dcm_qa](https://github.com/neurolabusc/dcm_qa/blob/master/batch.sh) script, you will see how it detects big-endian machines and uses this flag, but [dcm_qa_uih](https://github.com/neurolabusc/dcm_qa_uih/blob/master/batch.sh) does not. You may want to update the dcm_qa_uih for validating on big-endian machines.

**Comment by aqw** [comment]
Thanks for the fast response! :-)

I did see #327, but in this case my arch is little endian (the `el` signifies that).

I'll play with `dcm_qa_uih` as you suggested and see if it has any impact. But I'm pretty sure I'm not running into an endian-ness problem.

The rounding is an interesting idea, and does make sense.

If it does turn out to be a rounding issue: any ideas on how to adjust the tests to allow for such small variations? From a packaging viewpoint, I could disable these specific tests on this particular arch, but ideally all tests remain enabled on all arches and all run cleanly (for obvious reasons).

**Comment by neurolabusc** [comment]
It does look like the binary differences you are seeing are at the start of the images, where the NIfTI header is stored. I suspect that is the [sform and qform](https://brainder.org/2012/09/23/the-nifti-file-format/) offsets are stored at 268..328 decimal (10C..148 hex), which is where you are seeing a difference. 

You will see that internally dcm2niix uses the `isSameFloat()` function with a tolerance level to ignore tiny errors (e.g. rounding errors in slice positions that might slices in a 3D volume appear to be non-equidistant). However, standard `diff` commands are not intelligent in this way. 

With the gcc compiler [there is no general, high-level option to enforce any particular arithmetic model.  Thus running floating point code on different CPUs may give different results.](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=31114).  You might see if llvm compiler matches the input across machines (I know for the ARM-based Apple M1 llvm provides the same precision as gcc and llvm code on x86-64 machines).

I appreciate your attention to detail.

**Comment by neurolabusc** [comment]
I am closing this issue. The differences seem limited to the spatial transforms and of very small magnitude. These tiny differences will not significantly impact starting estimates for subsequent coregistration. I recognize this makes validation more challenging.

**Comment by aqw** [comment]
That makes sense. :-)

Sorry I havn't had the time to follow up on this as much as I'd like. I agree with your identification that the offsets are where we are seeing the differences.

Where I've left-off is compiling this with LLVM. The resulting binaries segfault, which I'm sure is entirely self-inflicted, but I need to find time to look into more fully.

If I have success with Clang (and remember), I will report back here, for the sake of completeness.

Thanks for your help and insight. It is much appreciated. :-)
