### ISSUE TITLE
Feature Request: Python API

### ISSUE THREAD

**Issue by jbteves** [rordenlab/dcm2niix#488]
It would be a neat feature to be able to access the `dcm2niix` core code through python with a call like this:
```
dcm2niix.dcm2niix('dicomfile', 'outputnifti', args=values)
```
Having the interface available in Python would accomplish a few things:
1. Make it easier for people to see what fields `dcm2niix` is picking up, potentially making troubleshooting easier when manufacturers make annoying choices.
2. Having the python interface makes batch converting much easier since you can

It's true that a simple interface could be built in Python as a `subprocess` call, however, this does not guarantee that `dcm2niix` is present on the machine and will be a touch slower.

**Comment by neurolabusc** [comment]
@jbteves this sounds like the Python equivalent of @jonclayden's [divest](https://github.com/jonclayden/divest) for R. Jon inserted a bit of R-specific code by inserting a few `#ifdef USING_R...#endif' compiler directives into the main code. This keeps divest and dcm2niix from forking from each other, as they have the same core code base. It seems like a great idea, but it is outside my skillset. I think the best approach is if you (or another skilled person) develops the needed changes and generates a pull request. An alternative approach would be a fully-Python based conversion, as proposed for [nibabel](https://github.com/nipy/nibabel/issues/977).

**Comment by neurolabusc** [comment]
I am closing this enhancement as it is outside my expertise. Happy to review a pull request from anyone who wants to tackle this.
