### ISSUE TITLE
No bvecs and bvals files generated from siemens DTI data

### ISSUE THREAD

**Issue by vctorwei** [rordenlab/dcm2niix#489]
Hi

I was using dcm2niix to convert a retrospective DTI data of 12 directions
The sequences were acquired from the Siemens scanner.

Can you check if this is the problem with the data or do I need a special setting of the dcm2niix?

Thank you
[DTI.zip](https://github.com/rordenlab/dcm2niix/files/6097405/DTI.zip)

**Comment by neurolabusc** [comment]
This is a limitation of these DICOM images, not dcm2niix. These images do not have the [proprietary Siemens CSA header](https://nipy.org/nibabel/dicom/siemens_csa.html) that contains the [diffusion vectors and weighting](https://www.na-mic.org/wiki/NAMIC_Wiki:DTI:DICOM_for_DWI_and_DTI#Private_vendor:_Siemens). There are two possibilities:
 1. These images were acquired using software version `syngo MR 2004V 4VB11D` from 2004. I am not sure if the CSA header was invented in 2004. Regardless, these systems did not have modern gradients or tricks like multi-band that can dramatically improve diffusion images.
 2. These images report a Deidentification Method of `NBIA Default w/ extra date removal`. No private tags survive, so it is possible that the original images did have a CSA header, but this was removed by an anonymization stage.
