### ISSUE TITLE
Compile with "mySegmentByAcq"

### ISSUE THREAD

**Issue by lyndonboone** [rordenlab/dcm2niix#494]
Hi Chris,

Not so much an issue, just a quick question:

I often see the message, "slices stacked despite varying acquisition numbers (if this is not desired recompile with 'mySegmentByAcq')". How would one go about compiling the software with "mySegmentByAcq"? I can't seem to find that option in the documentation or the COMPILE.md file.

Apologies if this is a basic question. I'm a bit new to compiling from source on linux.

Thanks for your help.

**Comment by neurolabusc** [comment]
The simplest way is to modify the command executed when you run `make` from the terminal in the `console` folder adding the parameter `-DmySegmentByAcq`, e.g. 

```
g++ -O3 -I.  main_console.cpp nii_foreign.cpp nii_dicom.cpp jpg_0XC3.cpp ujpeg.cpp nifti1_io_core.cpp nii_ortho.cpp nii_dicom_batch.cpp  -o dcm2niix -DmyDisableOpenJPEG -DmySegmentByAcq
```
Be aware that segmenting by acquisition number should be an extremely unusual configuration and it is likely to have unintended consequences for typical DICOM data. Only use this if your DICOMs have been mangled in some way.

**Comment by lyndonboone** [comment]
Thanks for the quick reply. That worked!
