### ISSUE TITLE
magnitude/phase designation for mp2rages acquisitions 

### ISSUE THREAD

**Issue by dlevitas** [rordenlab/dcm2niix#502]
With[ mp2rage acquisitions](https://github.com/bids-standard/bids-specification/blob/c8f5827d549d519ca9ebb0d3eebf6661ff348484/src/99-appendices/11-qmri.md#inputs-are-file-collections) being incorporated into the BIDS standard, I've noticed that the `_part-` label can be used to specify magnitude or phase. Dcm2niix typically includes `_e1`, `_e2`, `_e2_ph` for designating such acquisitions; however, with dcm2niix version v1.0.20201102 this doesn't appear to be the case with mp2rage acquisitions. I'm curious if this is a feature that can be added to future releases? I've shared three mp2rage acquisitions (INV1, INV2, UNIT1) for reference, and wanted to note that they only contain magnitude, not phase.

**Comment by neurolabusc** [comment]
The current stable release is [v1.0.20210317](https://github.com/rordenlab/dcm2niix/releases). It will distinguish echoes and phases for some vendors and some sequences, for example [Siemens Fieldmaps](https://github.com/neurolabusc/dcm_qa_me/tree/master/Ref). I believe it also works for [Siemens ME-MPRAGE](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2408694/) and Siemens SWI scans. If you have scans that are not segmented correctly, feel free to send me a set. dcm2niix is limited by the information provided by the manufacturers and the fact that I have only observed a small subset of the possible sequences. Each vendor has their own convention, and manufacturers can even change their own formats pretty dramatically (e.g. Siemens VA...VE vs Siemens XA).

**Comment by dlevitas** [comment]
I updated my dcm2niix to v1.0.20210317 but still get the same file naming outputs as with the old version. I've shared a set of our Siemens mp2rage data through Google Drive if that helps.

**Comment by neurolabusc** [comment]
Thanks for sharing a sample dataset. In your case, each dataset is being saved as a separate Series Number. Therefore, the DICOM `recipe` is telling dcm2niix to consider these independent scans. You will want to use some higher level tool to combine these if they belong together.

```
	"SeriesNumber": 13,
	"ImageType": ["ORIGINAL", "PRIMARY", "M", "ND", "NORM"],
	"EchoTime": 0.00298,
	"RepetitionTime": 5,
	"InversionTime": 0.7,
	"FlipAngle": 4,
	
	"SeriesNumber": 14,
	"ImageType": ["ORIGINAL", "PRIMARY", "M", "ND", "NORM"],
	"EchoTime": 0.00298,
	"RepetitionTime": 5,
	"InversionTime": 2.5,

	"SeriesNumber": 15,
	"ImageType": ["DERIVED", "PRIMARY", "M", "ND", "UNI"],
	"EchoTime": 0.00298,
	"RepetitionTime": 5,
```

**Comment by dlevitas** [comment]
I see, thanks. I'm used to seeing magnitude/phase[diff] acquisitions with the same SeriesNumber and forgot that these acquisitions have separate ones.

**Comment by francopestilli** [comment]
thanks for the help @neurolabusc
