### ISSUE TITLE
Bvals not correctly generated for GE data if adhering to the DICOM standard

### ISSUE THREAD

**Issue by Svdvoort** [rordenlab/dcm2niix#503]
**Describe the bug**

I'm trying to create datasets where the bvals/bvecs are in the official tags according to the latest DICOM 2021a guidelines.
For example, I have a GE dataset where the data is originally stored in tag (0043, 1039). 
I'm trying to update the data to put it in the correct tags, namely (0018, 9117), (0018, 9087) etc. 
However, when the manufacturer is GE and the data is stored in the official tags, only b-vals of 0 are produced.
Removing the manufacturer correctly identifies the b-vals (it is then seen as a Philips scan).
Although this only works when putting the diffusion data in the root tags, not in the sequence at (0018, 9117)

Although this might not be the GE way of storing the diffusion tags, I assumed this would work since it is the official DICOM way of storing the tags. 
Can the official tags be checked regardless of the manufacturer? Perhaps with an additional flag? 

**To Reproduce**

[Data is available here to reproduce](https://drive.google.com/drive/folders/1yJSb1Q5RvRnIkGiNT30zOK99KeTxc29q?usp=sharing)
(This is open source data from The Cancer Imaging Archive). 
Original data has diffusion tags in (0043, 1039), albeit incorrectly because it only specifies a b-val of 1000 and not one of 0.
The fixed data has the diffusion data in (0018,9117) as a sequence, and the individual tags at a root level as well.
The fixed data without manufacturer is the same as fixed data, except it has tag (0008, 0070) removed.

1. Run `dcm2niix DICOM_fixed`
2. Check the outputted bval file -> only 0 b-values
3. Run `dcm2niix DICOM_fixed_no_manufacturer`
4. Check outputted bval file -> Correctly identifies b=0, and b=1000

It is DWI (not DTI) data, so there are no bvecs, everything is just trace, but still relevant for ADC calculation.

**Expected behavior**

To check the standardized DICOM tags regardless of manufacturer if the manufacturer-specific checks fail.
Preferably the sequence in 0018, 9117 according to the DICOM standard would work.

**Output Log**
N/A

**Version (please complete the following information)**

Latest stable release: dcm2niiX version v1.0.20210317  (JP2:OpenJPEG) (JP-LS:CharLS) GCC5.5.0 x86-64 (64-bit Linux)

**Comment by neurolabusc** [comment]
@Svdvoort the provided sample dataset is for isotropic diffusion images (I believe they are TRACE and  b=0). This explains the warning for each dataset:
```
Warning: Some images had bval>0 but bvec=0 (either Trace or b=0, see issue 245)
```
Therefore, bval and bvec files are not appropriate for this series. The bval and bvec files are for the original raw directional diffusion data.

Be aware that [GE gradient vectors (0019,10bb, 0019,10bc and 0019,10bd)](https://github.com/rordenlab/dcm2niix/tree/master/GE) are stored in “MR physics” logical coordinate, i.e Freq (X), Phase (Y), Slice (Z). On the other hand, the public tag [0018,9089]( http://dicomlookup.com/lookup.asp?sw=Tnumber&q=(0018,9089)) stores diffusion gradient vector with respect to the patient. Therefore, you will want to be exceptionally careful transforming between these coordinate systems. 

Different vendors have interpreted the DICOM standard differently, and use proprietary conventions for storing meta data. While I applaud your desire to generate generic DICOM images where all the information is stored in the public tags, be aware that a lot of vendor meta data has no corresponding public tags. In this case, the Image Type (0008,0008) of `ORIGINAL\PRIMARY\OTHER` is not informative of the image type.

**Comment by neurolabusc** [comment]
@mr-jaemin can you take a look at the 'DICOM_original` folder in the data provided above. The images report MagneticFieldStrength (0018,0087) DS [15000] and ImagingFrequency (0018,0084) DS [638733160]. The specification defines the units for [0018,0087](http://dicomlookup.com/lookup.asp?sw=Tnumber&q=(0018,0087)) as Tesla and [0018,0084](http://dicomlookup.com/lookup.asp?sw=Tnumber&q=(0018,0084)) as MHz. The values are implausible (presumably a 1.5T magnet with 63.87 MHz frequency).

**Comment by mr-jaemin** [comment]
Here are some relevant DICOM tags for GE Diffusion as an example:
```
(0008,1090) LO [SIGNA Premier]                          #  14, 1 ManufacturerModelName
(0018,1020) LO [27\LX\MR Software release:RX27.0_R03_1850.a] #  44, 3 SoftwareVersions
(0018,9087) FD 3000                                     #   8, 1 DiffusionBValue
(0019,10b2) DS [4321.000000]                            #  12, 1 Unknown Tag & Data
(0019,10bb) DS [-0.19061738752537763]                   #  20, 1 Unknown Tag & Data
(0019,10bc) DS [-0.5852443794202555]                    #  20, 1 Unknown Tag & Data
(0019,10bd) DS [-0.7881333469172587]                    #  20, 1 Unknown Tag & Data
(0021,105a) SL 16                                       #   4, 1 Unknown Tag & Data
(0043,1039) IS [1000\1073741832\0\0]                    #  20, 4 Unknown Tag & Data
```
But, looking at the 'DICOM_original` folder, I noticed the "UN" and was expecting "DS" for bvec or "IS" for private bval (0043,1039). The values are obvious odd but, the "UN" may indicate that data doesn't contain original header information from scanner any more

from 1-56.dcm
```
(0008,1090) LO [GENESIS_SIGNA]                          #  14, 1 ManufacturerModelName
(0018,1020) LO [09]                                     #   2, 1 SoftwareVersions
(0019,10b2) UN 30\20                                    #   2, 1 Unknown Tag & Data
(0019,10bb) UN 30\20                                    #   2, 1 Unknown Tag & Data
(0019,10bc) UN 30\20                                    #   2, 1 Unknown Tag & Data
(0019,10bd) UN 30\20                                    #   2, 1 Unknown Tag & Data
(0021,105a) UN 07\00\00\00                              #   4, 1 Unknown Tag & Data
(0043,1039) UN 31\30\30\30\5c\38\5c\30\5c\37            #  10, 1 Unknown Tag & Data
```

**Comment by Svdvoort** [comment]
Thanks for looking into this!

Indeed I believe the dataset contains a b=0 and TRACE b=1000 as well. I agree that a bvec file will not make sense for this case, 
but the bval file can still be valuable as it still allows for the calculation of an (isotropic) ADC does it not? 

The warning also seems to detect multiple b-vals (hence the 'Warning: Some images had bval>0 but bvec=0') but these are not written to the bval file (since they're all 0).

If I look at the DICOM standard 2021a diffusion macro (C.8.13.5.9) I would expect the following to be valid in this case:

(0008, 0008) having a value of ORIGINAL/PRIMARY/DIFFUSION
(0008, 9007) having a value of ORIGINAL for all slices
(0018, 9087) having a value of either 0 or 1000 as appropriate
(0018, 9075) having a value of ISOTROPIC for the b=1000 slices and a value of NONE for the b=0 slices

The other diffusion related tags (0018, 9601 through 9607) can be empty since (0018, 9075) is ISOTROPIC or NONE for all slices. 

In the original data I did not set (0008, 0008), this was the old data, and I set (0018, 9075) to ISOTROPIC for all slices instead of only for the b=1000 slices. 

With these settings I would expect a valid bval file to be produced. Or is the intent really only to do this for DTI (with multiple bvecs) data and not for DWI (with isotropic/TRACE data)? 

If the last option is the case, then I think it would still be nice to have this consistent. Right now removing tag (0008, 0070) does produce the expected bval file because dcm2niix then assumes that the manufacturer is Philips.


As for the data itself: I agree it is messy. It is from [The Cancer Imaging Archive](https://wiki.cancerimagingarchive.net/display/Public/TCGA-LGG). So unfortunately we cannot change anything about the PACS and we do not have access the original data anymore.

Hence why I'm trying to clean up the data. The diffusion data is just a small part of this, indeed I also intend on correction the image type tag (0008, 0008) to be actually informative according the latest DICOM standard, and check the other DICOM tags for their validity as well (such as the field strength which in GE scans is sometimes set with this scaling factor that they also seem to use for their b-vals sometimes, as noted from tag (0018, 0087)). 

So I guess the question/request/bug comes down to this: Is there a combination of setting the public tags (correctly) to output the bval file (and potentially bvec file)? If not, how can I ensure that it is consistent among data? For example, now if I would set the same tags in the same way, but the manufacturer is Philips in one case and GE in another it will give different results, which seems to defeat the purpose of trying to standardize the data.

**Comment by neurolabusc** [comment]
The rationale for the FSL format .bvec and .bval files is for tools like FSL's dtifit, AFNI's FATCAT, dti studio, etc. which are designed for directional diffusion data. They are not designed for isotropic diffusion scans. There is not a consensus for how vendors deal with these features, but I have seen image type tag (0008, 0008) that provides guidance for isotropic images with `B0 MAP`, `ADC`, `TRACE`, and  `TRACEW` tags. The BIDS standard provides clear definitions for the directional scans, and in practice one will be able to derive much better isotropic images after offline processing of the directional images (e.g. after running de-noise, de-Gibbs, TOPUP, Eddy). 

Therefore, there seems to be no consensus among manufacturers regarding how to identify these isotropic images, and no description from the scientists of how these should be handled. dcm2niix is already very complicated, and I try to solve problems where there is a clear consensus regarding what the solution should be. Therefore, it seems like your questions need to be resolved upstream with the manufacturers and the BIDS standard.

I have seen several issues with TCIA DICOMs. While it is a terrific resource, they are not typical DICOMs. This is a limitation of the TCIA processing, not dcm2niix. Adapting dcm2niix to handle these quirks would complicate the code and would likely have widespread unintended consequences on well-behaved DICOM images. I think you are much better off writing a wrapper that cleans up the NIfTI images dcm2niix creates from from TCIA DICOMs, rather than trying to fix the DICOMs.

**Comment by Svdvoort** [comment]
Just to clear things up so I know where to address these points: Is this a problem with the .bvec and .bval files (and thus this should be addressed for example with BIDS), or is this a problem with the DICOMs (as suggested by the ADC, TRACE etc tags)? 

The first problem is indeed something to address with BIDS/FSL, but I believe the second point is now resolved with the diffusion macro in the DICOM standard? The manufacturers indeed do not adhere to the standard (yet), but there is an official standard on how to specify isotropic diffusion scans in the DICOM.

**Comment by neurolabusc** [comment]
The bval/bvec files are not appropriate for derived isotropic images (TRACE, ADC, MD, etc). There is no defined method to report these derived images in the BIDS specification, and vendors do not provide a consistent method to identify them. This is a limitation of the formats and the DICOM images, not dcm2niix.In general, one should avoid generating derived images on the scanner console, as one can create better derived images after post-processing. For this reason, I do not think there has been much incentive to clarify this. If you work at a center with a MRI system, you could always lobby your manufacturer's research collaboration manager to provide a unified solution to this issue.
