### ISSUE TITLE
Warning: Missing images? Expected 10 images, but instance number (0020,0013) ranges from 5 to 6

### ISSUE THREAD

**Issue by vpapaioannou** [rordenlab/dcm2niix#504]
**Describe the bug**
It creates one extra file w/ name "*_Eq_1.nii". 

Also the error message does not help to understand the problem since according to the output log below, all Instance Numbers exist.

**To Reproduce**
1. Run the command 'dcm2niix ...'
`.../bin/dcm2niix_Linux --terse -v 0 -w 1 -z y -m y -b n -o "/newnifti" -f 0001_001_NA_Mb ./tmp`
2. See error ...```

`Chris Rorden's dcm2niiX version v1.0.20201102  (JP2:OpenJPEG) (JP-LS:CharLS) GCC5.5.0 x86-64 (64-bit Linux)`
`Found 10 DICOM file(s)`
`Warning: Assuming icon SQ 07a3,10ce.`
`Unsupported overlay origin 0/0`
`Unsupported overlay origin 0/0`
`Unsupported overlay origin 0/0`
`Unsupported overlay origin 0/0`
`Unsupported overlay origin 0/0`
`Unsupported overlay origin 0/0`
`Unsupported overlay origin 0/0`
`Unsupported overlay origin 0/0`
`Unsupported overlay origin 0/0`
`Unsupported overlay origin 0/0`
`Warning: Interslice distance varies in this volume (incompatible with NIfTI format).`
`Warning: Order specified by DICOM instance number is not spatial (reordering).`
`Warning: Missing images? Expected 10 images, but instance number (0020,0013) ranges from 5 to 6`
`Warning: Siemens MoCo? Bogus slice timing (range -1..-1, TR=7.8 seconds)`
`Convert 10 DICOM as /home/bill/carina/canopus/data/Deidentifier/34/output/newnifti/0001_001_NA_Mb (512x512x10x1)`
`Compress: "/usr/bin/pigz" -b 960 -n -f -6 "/newnifti/0001_001_NA_Mb.nii"`
`Compress: "/usr/bin/pigz" -b 960 -n -f -6 "/newnifti`/0001_001_NA_Mb_Eq_1.nii"`
`Conversion required 0.175756 seconds (0.036577 for core code).`

**Expected behavior**
To not create file `Compress: "/usr/bin/pigz" -b 960 -n -f -6 "/newnifti`/0001_001_NA_Mb_Eq_1.nii"`

**Output Log**

`Instance Number (0020,0013) 2 Series Number 2`
`Instance Number (0020,0013) 10 Series Number 2`
`Instance Number (0020,0013) 1 Series Number 2`
`Instance Number (0020,0013) 7 Series Number 2`
`Instance Number (0020,0013) 9 Series Number 2`
`Instance Number (0020,0013) 5 Series Number 2`
`Instance Number (0020,0013) 3 Series Number 2`
`Instance Number (0020,0013) 6 Series Number 2`
`Instance Number (0020,0013) 8 Series Number 2`
`Instance Number (0020,0013) 4 Series Number 2`

Logs of dcm2nii w/ `-v 1`
[dcm2nii_logs_v0.txt](https://github.com/rordenlab/dcm2niix/files/6279868/dcm2nii_logs_v0.txt)

** Version (please complete the following information):**
 - dcm2niiX version v1.0.20201102  (JP2:OpenJPEG) (JP-LS:CharLS) GCC5.5.0 x86-64 (64-bit Linux)
 - Is this the [latest stable release](https://github.com/rordenlab/dcm2niix/releases)? If not, does the latest stable release resolve your issue?
 I haven't tried but I am not expecting to given the release notes.

 - If the latest stable version fails, and you are using macOS or Linux. Does the latest commit on the development branch resolve your issue? You can build this using the recipe below:
I haven't tried.
```
I checked also this https://www.nitrc.org/forum/message.php?msg_id=31755 and I see that in my case and this case `dx` list does not have a consistent ascending order. Might that be the reason?

**Comment by neurolabusc** [comment]
I would always recommend using the latest [stable release](https://github.com/rordenlab/dcm2niix/releases) (v1.0.20210317). The DICOM standard is evolving rapidly, so tools need to keep pace.

For classic DICOM, a 3D volume is based on a series of 2D slices. This is analogous to how a 3D loaf of bread is segmented into discrete 2D slices. In classic DICOM parlance, a sustained acquisition of slices is called a `SERIES` and each slice is referred to as an `instance`. One expects instance numbers to be numerically sequential and spatially equidistant. This is not the case with your series. There are several explanations:
 1. Images were intentionally acquired with slices that are not equidistant.
 2. Some of the files have not been copied or the images have been corrupted.

I would suggest you check the provenance of these images. This will reveal if some of the images were corrupted or lost.

**Comment by vpapaioannou** [comment]
Thanks.
