### ISSUE TITLE
Cannot convert a 4D DICOM folder

### ISSUE THREAD

**Issue by colddie** [rordenlab/dcm2niix#509]
Hello,

I am trying to convert a 4D Dicom folder exported from a GE DMI PET machine. I encountered following error and I believed it is most likely due to the failure of reading individual 2d dicom slice. How to ignore these errors? Any instructions would be grateful. 

Tao

Here is the print out message:
Compression will be faster with pigz.exe in the same folder as the executable
Chris Rorden's dcm2niiX version v1.0.20210317  (JP2:OpenJPEG) (JP-LS:CharLS) MSC1900  (64-bit Windows)
Found 2769 DICOM file(s)
Illegal DICOM tag 0033,1057 (odd element length 540755): E:\Shenzhen_Cancer\liver_test\finesample\e1WholeBodyPETDynamic-1_3000001_PT030.dcm
Illegal DICOM tag 7562,6574 (odd element length 29029): E:\Shenzhen_Cancer\liver_test\finesample\e1WholeBodyPETDynamic-1_500001_PT057.dcm
Illegal DICOM tag 4853,000e (odd element length 8275): E:\Shenzhen_Cancer\liver_test\finesample\e1WholeBodyPETDynamic-1_500001_PT058.dcm
Illegal DICOM tag ffff,ffff (odd element length 65535): E:\Shenzhen_Cancer\liver_test\finesample\e1WholeBodyPETDynamic-1_500001_PT066.dcm
DICOM images may be missing, expected 71 spatial locations per volume, but found 2765 slices.
Slice positions repeated, but number of slices (2765) not divisible by number of repeats (39): missing images?
Hint: expected 71 locations
Warning: Seconds between volumes varies
Warning: Interslice distance varies in this volume (incompatible with NIfTI format).
Unable to equalize slice distances: slice order not consistently ascending.
First spatial position repeated 39 times
Error:  Recompiling with '-DmyInstanceNumberOrderIsNotSpatial' might help.

**Comment by neurolabusc** [comment]
A few of your DICOM files appear to be corrupted. All DICOM tag lengths must be even, so files like `e1WholeBodyPETDynamic-1_500001_PT066.dcm` appear broken. The most likely explanation is a file transfer error (e.g. bad sector on hard disk, USB drive removed before file finished writing, etc.). Another possibility is that some tool corrupted the files (e.g. poorly implemented anonymization script). I would try exporting your images direct from the scanner to a disk to examine this. You could also check the integrity of these files by using a tool other than dcm2niix to inspect them, e.g. `dcmdump e1WholeBodyPETDynamic-1_500001_PT066.dcm`. If you want, you can send a problematic fie to the email address in my avatar, and I can provide more advice. However, my sense is that this is a limitation of your files, not my software.

**Comment by neurolabusc** [comment]
I am closing this issue, some images in this series were corrupted and can not be opened with any tool. This is a limitation of these DICOMs, not dcm2niix.
