### ISSUE TITLE
dcm2niix wrong number of slices

### ISSUE THREAD

**Issue by renero76** [rordenlab/dcm2niix#513]
**Describe the bug**
I have to convert a 4D MRI sequence composed by 28 volumes from DICOM (1540 files) to NiFTI. dcm2niix produces 22 slices for each volume instead of 55. I have to say that 1540 is divisible both for 22 and 55 but I need a nifty file with these dimensions: X*Y*55*28  and not X*Y*22*70.
I have the last version of dcm2niix.

How can I resolve?

Thanks a lot

**To Reproduce**
- dcm2niix -f %n .
- no error, only wrong slices

** Version (please complete the following information):**
dcm2niiX version v1.0.20210317  (JP2:OpenJPEG) (JP-LS:CharLS) Clang8.1.0 x86-64 (64-bit MacOS)
v1.0.20210317
 - Is this the [latest stable release](https://github.com/rordenlab/dcm2niix/releases)? If not, does the latest stable release resolve your issue?
 - If the latest stable version fails, and you are using Windows. Does the latest commit on the development branch resolve your issue? You can get a pre-compiled version from [AppVeyor](https://ci.appveyor.com/project/neurolabusc/dcm2niix) (click on the Artifacts button).
 - If the latest stable version fails, and you are using macOS or Linux. Does the latest commit on the development branch resolve your issue? You can build this using the recipe below:

```
git clone --branch development https://github.com/rordenlab/dcm2niix.git
cd dcm2niix/console
g++  -I.  main_console.cpp nii_foreign.cpp nii_dicom.cpp jpg_0XC3.cpp ujpeg.cpp nifti1_io_core.cpp nii_ortho.cpp nii_dicom_batch.cpp  -o dcm2niix -DmyDisableOpenJPEG
./dcm2niix ....
```

**Comment by neurolabusc** [comment]
- Does the latest commit to the development branch ( v1.0.2021042) resolve your issue?
- Does the text reported by dcm2niix during conversion generate any warnings?
- Can you share a dataset with me (email address in avatar) via DropBox, GoogleDrive, etc?
