### ISSUE TITLE
Add "SiemensOrientationText" (0051,100E) (suggestion)

### ISSUE THREAD

**Issue by mharms** [rordenlab/dcm2niix#522]
Looks like we never included "Siemens Orientation Text" (0051,100E) as one of the parameters that populate the json sidecar.  I'm used to having this available for review in our HCP XNAT (which we must be grabbing as part of a DICOM Meta-Data extraction step).  Would be nice to include in the sidecar json as well.

**Comment by neurolabusc** [comment]
I have added this, but wonder if it is completely redundant with `ImageOrientationPatientDICOM`?

```
"ImageOrientationPatientDICOM": [
		0.924945,
		0.129034,
		0.35753,
		-8.64178e-09,
		0.940616,
		-0.339472	],
"ImageOrientationText": "Tra>Sag(23.6)>Cor(-18.3)",
```

**Comment by mharms** [comment]
Thanks.  Yes, it is in some sense redundant, but easier to interpret.  e.g., If its "Tra" you immediately know a scan was acquired in a strictly Transverse orientation, without needing to know/recall how that would be represented in the `ImageOrientationPatientDICOM` values.  Similarly, way easier to use that text version to check if AutoAlign was applied relative to the "Orientation" parameter set in a Siemens protocol, and thus be able to easily identify if there was a failure to apply AutoAlign.
