### ISSUE TITLE
LPS orientation to RAS orientation on dcm2niix affine matrix

### ISSUE THREAD

**Issue by BrunoFFPP** [rordenlab/dcm2niix#524]
Dear all,
I'm trying to calculate affine matrix from my dicom data but I can't reach the affine matrix of dcm2niix. 
I have a Philips 3DT1 sagittal data with 180 slices, matrix (240x240) and pixel (1x1x1 mm3). Image position(0020,0032) is : +89/-125/+143 and Image orientation(0020,0037) is : 0/1/0/0/0/-1.  When I use dcm2niix on this data I have the following RAS(L-->R,P-->A,I-->S) affine matrix:

1 0 0 -89
0 1 0 -114
0 0 1 -96
0 0 0 1

I read the closed issue "#152" and https://www.slicer.org/wiki/Coordinate_systems and I tried to calculate IJKtoLPS matrix. I draw a cube, i define the eight vertices of this cube in IJK coordinate system and LPD coordinate system as you can see on my notes (sorry for the sketch)
![20210628_105314](https://user-images.githubusercontent.com/86606485/123648869-b0562500-d7ff-11eb-9737-8f5e7f416d1f.jpg)

And I reach the  following IJKtoLPS matrix:
L  =   0 0 1    89     i
P      -1 0 0 -125    j
S       0 1 0   143    k
1        0 0 0    1      1

Considering the same origin for RAS and LPS coordinate system, the LPStoRAS matrix is a rotation matrix on IS axis of 180 degrees, So I have a flip sign of first an second lines of above matrix. But I couldn't reach the dcm2niix  affine matrix. What I doing wrong?  Have RAS and LPS the same origin, indeed?

I try another data, a SagittalLocalizer data with with 9 slices, matrix (256x256) and pixel (1x1x10 mm3). Image position(0020,0032) is : +40/-124.5/+124.5 and Image orientation(0020,0037) is : 0/1/0/0/0/-1.  When I use dcm2niix on this data I have the following PSR(A-->P,I-->S,L-->R) affine matrix:

 0 0 10   -40
-1 0 0   124.5
 0 1 0   -124.5
 0 0 0      1

Again I did a sketch 
![20210628_115908](https://user-images.githubusercontent.com/86606485/123660782-53ac3780-d80a-11eb-8115-3eda7fefc509.jpg)

and this time I reach the following IJKto LPS matrix:
L  =   0 0 10    40      i
P      -1 0 0 -124.5    j
S       0 1 0   124.5    k
1        0 0 0     1         1

that is closer to its correspondent dcm2niix affine matrix than 3DT1 data.

Why do the both sagittal data acquired in the same scanner are different? 
Why 3DT1 is RAS and Localizer is PSR if on Philips scanner the acquisition settings is RAS(SAG:L-->R; COR:P-->A;AX:I-->S) for both? 
What is the role of tag (0020,0037) ? I'm asking this because these tags are identical in both acquisitions (3DT1 sagittal and Localizer sagittal).
 
How to interpret the tag(0020, 0052) "Frame of Reference UID"?
For 3DT1 data, "Frame of Reference UID" is  1.3.46.670589.11.17448.5.0.11956.2021062409162716004  
For Localizer ,  "Frame of Reference UID" is  1.3.46.670589.11.17448.5.0.9372.2021061010292972006 
Thanks in advance and sorry for the long question.
Bruno

**Comment by neurolabusc** [comment]
Your high-resolution T1 scan is a 3D acquisition, and therefore it can be losslessly reoriented to match canonical NIfTI space (RAS) without any concern that the slice timing may be impacted. On the other hand, the localizer is a 2D acquisition, so dcm2niix will not reorient it for fear of impacting slice timing calculations. You can disable the rotation of 3D acquisitions with the `-x i` argument.

I believe that explains your situation. Here are a few more notes that are relevant to these issues in general.

You may find the notes on [DICOM and NIfTI spatial coordinates](https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#Spatial_Coordinates) useful. 

Be aware that the DICOM image row order has the first row at the top of the screen, with higher row numbers lower on the screen, the way we read English. NIfTI row order starts with the first row at the bottom of the screen, with higher row numbers ascending up the screen, the way we draw the Y coordinate in a cartesian graph.  Therefore, the default behavior of dcm2niix is to flip the row order, to match the convention of the base format. You can disable this y-flip with the `-y y` argument.

**Comment by BrunoFFPP** [comment]
Thanks for your reply.
I realize that in my sketchs A13, A21 and A32 values are sign changed, the corrected values are -1 , +1 and -1 respectively. So the correct IJKtoLPS matrix is:
0   0 -1     89 
1  0   0  -125 
0 -1   0   143 
0  0   0       1 

and as RAS system  is a rotation of 180 degree in relation of IS axis, the IJKtoRAS matrix should be:
0   0 +1     -89 
-1  0   0  +125 
0  -1   0  +143 
0   0   0       1 

I applied dcm2niix again on my data using "-x i" and "-y n" flags and now  the affine matrix is identical to IJKtoRAS above, but now,   x_orient, y_orient and z_orient are A-->P, S-->I; L-->R, respectively, i.e., PIR and not RAS  anymore, why? In other words, what is the matrices that represent the "-x y" and "-y y" flags that are used to reach

1 0 0 -89
0 1 0 -114
0 0 1 -96
0 0 0 1

? 

Thanks in advance and sorry for the silly doubts about linear algebra

**Comment by neurolabusc** [comment]
When you permute a 3D volume to RAS space, you permute the order of the image data columns, rows, slices so that they correspond with L->R, P->A and I->S respectively. Therefore, the first voxel on disk is the LPI corner (left-most, posterior-most and inferior-most). The final column of your matrix is simply the coordinates of this voxel (the translation from origin).  In your first Figure, you will note that Vertex 2 is the LPS voxel. If you look at the L,P,S column of your table, this voxel has DICOM coordinates 89, 114, -96 (as DICOM coordinates increase leftward, posterior, superior), which corresponds to NIfTI -89, -114, -96 (as NIfTI and MNI coordinates increase rightward, anterior, superior). 


Here is elegant Matlab code that illustrates [this transformation](https://github.com/xiangruili/dicm2nii/blob/d3a09d3371b0c2f7f7b430bbc2b0d2956c378fdf/nii_viewer.m#L1654).

**Comment by neurolabusc** [comment]
I have created a [Github repository with all 48 permutations of orthogonal spatial rotations and flips](https://github.com/rordenlab/NIfTIspace).

**Comment by BrunoFFPP** [comment]
Hi Chris,
Thanks for sharing this data. It is very helpful and now it's clear
the matrix transformation between all 48 permutations, but I still have
some doubts in relation to DICOM to NIFTI conversion.
I use HOROS to visualize my dicom data.
On HOROS, all sagittal image are displayed :
     S
A        P
      I
Coronal:
     S
R       L
      I
Axial:
     A
R       L
     P


After using dcm2niix, I use FSLEYES as a visualizer. And on FSLEYES:
Sagittal:
     S
P        A
      I
Coronal:
     S
R       L
      I
Axial:
     A
R       L
     P
The unique change is that the sagittal plane is 180 degree flipped in
relation to "IS" axis.


I know that DICOM is recorded on the LPS coordinate system. I have a
sagittal 3DT1 data with the first dicom voxel on ASL (anterior-most,
superior-most, left-most), i.e., the columns go from A to P, the lines go
from I to S ad slices go from L to R.  The image orientation for this data
is  (0/1/0/0/0/-1). When I use dcm2niix, the nifti is converted to a RAS
system, i.e, the first nifti voxel is LPI. OK I got it!

But I have an axial DWI data with the first dicom voxel on RAI (right-most,
anterior-most, inferior-most), i.e., the columns go from R to L, the lines
go from A to P ad slices go from I to S.  The image orientation for this
data is  (1/0/0/0/1/0). When I use dcm2niix, the nifti is converted to a
LAS system,i.e, the first nifti voxel is RPI. Why did this happen?  Why is
it not converted to RAS as well?

Thanks
Bruno

Bruno Fraccini Pastorello
Físico Médico | Ressonância Magnética | LIM44
Instituto de Radiologia do HCFMUSP
Ramal: +55 11 2661-7619
***@***.***

*Antes de imprimir* *pense em sua responsabilidade e compromisso com o*
* MEIO AMBIENTE*



Em ter., 6 de jul. de 2021 às 10:50, Chris Rorden ***@***.***>
escreveu:

**Comment by neurolabusc** [comment]
1. There is no convention regarding whether sagittal images should show the Anterior anatomy on the left or right side of the display. For FSLeyes, the `horizontal` Layout shows nose right, and the `grid` layout shows nose left. With [MRIcroGL](https://www.nitrc.org/plugins/mwiki/index.php/mricrogl:MainPage) the Display menu allows you to choose between `Sagittal` and `Sagittal (nose left)`. However, regardless of the display, the anatomical labels `A` and `P` are always correct.
2. Your T1 scan is a 3D sequence, and therefore can be losslessly reoriented. Your DWI scan is a 2D EPI sequence, and therefore the slice order is maintained as required by tools like Eddy/TOPUP. Again, the spatial transform is encoded in the S-Form and Q-Form, so the anatomical labels (A/P,L/R,S/I) are always preserved. 

![horizontal](https://user-images.githubusercontent.com/8930807/124990665-aa85ee00-e00e-11eb-868a-240679c41ba9.png)
![grid](https://user-images.githubusercontent.com/8930807/124990671-ace84800-e00e-11eb-855c-6da8e22df0d2.png)
