### ISSUE TITLE
Filename custom option -f with %u, NOT working

### ISSUE THREAD

**Issue by jeodai** [rordenlab/dcm2niix#526]
As the title descriped, `dcm2niix -f %f_%u ...` not working, the result filename is missing acquisition number.

And there is a warning: "Warning: Ignoring '%u' in output filename (recompile to segment by acquisition)".

Anyone knows what happened? Thank you!

**Comment by neurolabusc** [comment]
This is as intended. As required by the BIDS specification, many modalities stack a range of acquisitions into a single 4D NIfTI file (e.g. fMRI/ASL time series, DTI gradient directions and b-values). Therefore, a single file contains multiple acquisition values (from DICOM tag 0020,0012).  For a minimal example, consider [this fMRI dataset](https://github.com/neurolabusc/dcm_qa/tree/master/In/Orientation/ax/axasc35) where two timepoints are acquired: acquisition 1 and 2.

If you want to split a 4D NIfTI file into 3D files, consider a tool like [fslsplit](https://fsl.fmrib.ox.ac.uk/fslcourse/lectures/practicals/intro3/index.html).

**Comment by jeodai** [comment]
Thanks for your explanation,  I see the consideration.
However I have two small problems:
1. My test dicom data has no multiple acquisition values, but it is still ignored.
2. If I want to config it to NOT ignore, do I have to compile the dcm2niix source by myself?

**Comment by jeodai** [comment]
> This is as intended. As required by the BIDS specification, many modalities stack a range of acquisitions into a single 4D NIfTI file (e.g. fMRI/ASL time series, DTI gradient directions and b-values). Therefore, a single file contains multiple acquisition values (from DICOM tag 0020,0012). For a minimal example, consider [this fMRI dataset](https://github.com/neurolabusc/dcm_qa/tree/master/In/Orientation/ax/axasc35) where two timepoints are acquired: acquisition 1 and 2.
> 
> If you want to split a 4D NIfTI file into 3D files, consider a tool like [fslsplit](https://fsl.fmrib.ox.ac.uk/fslcourse/lectures/practicals/intro3/index.html).

Thanks for your explanation, I see the consideration.
However I have two small problems:

My test dicom data has no multiple acquisition values, but it is still ignored.
If I want to config it to NOT ignore, do I have to compile the dcm2niix source by myself?

**Comment by neurolabusc** [comment]
The development branch of dcm2niix will now allow inserting the acquisition number in the filename, though it will generate the warning:

```
Warning: '%u' in output filename can be misleading (issue 526)
```

Be aware that this value will not be meaningful for NIfTI files that contain image data from DICOMs with varying acquisition number. While this behavior is now allowed, I would advise against using the `-f %u` for DICOM to NIfTI conversion, as it was designed for DICOM renaming.

**Comment by neurolabusc** [comment]
1. There is no convention regarding whether a sagittal slice should be shown with the anterior location on the left or right side of the computer screen. For example, with FSLeyes, the `Horizontal` view shows nose right while the `Grid` view shows the nose left. For flexibility, I would suggest [MRIcroGL](https://www.nitrc.org/plugins/mwiki/index.php/mricrogl:MainPage). The `Preferences` menu allows you to choose between [neurological and radiological convention](https://www.nitrc.org/plugins/mwiki/index.php/mricrogl:MainPage#Neurological_versus_radiological_convention).  With regards to the Sagittal view, you can choose the Display/Sagittal and Display/Sagittal(NoseLeft) to choose whether anterior is shown on the left or right side of the screen. Note that with Horos, MRIcroGL and FSLeyes, the Anatomical labels (L/R, A/P, S/I) are always shown on screen at the correct locations, there are just different conventions for how slices are displayed.
2. Only 3D sequences are rotated to RAS. Your DWI scan is a 2D EPI sequence, so slices are not reoriented to preserve slice timing which is important for diffusion tools like Eddy and TOPUP.

![horizontal](https://user-images.githubusercontent.com/8930807/124981199-4a3d7f00-e003-11eb-8e83-8e02da465971.png)
![grid](https://user-images.githubusercontent.com/8930807/124981209-4dd10600-e003-11eb-9916-2e4f3c170121.png)
