### ISSUE TITLE
UIH data TotalReadoutTime calculation format adjustment

### ISSUE THREAD

**Issue by XYWCQM** [rordenlab/dcm2niix#531]
Hello:
    Previously, when dcm2niix converted UIH data, the calculation of TotalReadoutTime was achieved by reading the AcquisitionDuration of (0065, 1029). Now we have modified its definition, so there will be problems in calculating TotalReadoutTime directly through the Tag. Therefore, when calculating TotalReadoutTime, it is hoped to calculate through effectiveEchoSpacing * (reconMatrixPE-1.0)).  Looking forward to your reply, thank you.
![totalreadouttime](https://user-images.githubusercontent.com/49193137/126429438-4f33f445-b6f3-47cb-9662-9f4372a489ac.png)

**Comment by neurolabusc** [comment]
Thanks for the update. 

Can you confirm that your formula fits the [BIDS specification](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html) uses the unintuitive FSL definition of `TotalReadoutTime`: “the time from the middle of the first echo to the middle of the last echo, as it would have been had partial k-space not been used”. Consider three scans:

1. A Full-Fourier image without slice acceleration.
2. Identical to (1) but with partial-Fourier. Even though fewer lines are acquired, this will show the same spatial distortion as (1) so it will have the same effective TotalReadoutTime. 
3. Identical to (1) but with in-plane acceleration (e.g. SENSE). Fewer lines are acquired (but full coverage of K-space), this will show less spatial distortion than (1) so it has a faster TotalReadoutTime. 

This unusual definition explains some of the unintuitive formulas seen in dcm2niix. For example, consider the code used for [GE](https://github.com/rordenlab/dcm2niix/blob/e973e0ff5ba5ddde73bb2b95088a9fadc2f4997b/console/nii_dicom_batch.cpp#L1573) systems.

**Comment by mharms** [comment]
It really would have been better if BIDs had named it "EffectiveTotalReadoutTime" (or something similar), since it goes along with `EffectiveEchoSpacing`.  It's easier if you think of `TotalReadoutTime` as a value that is just computed from the `EffectiveEchoSpacing` and the size of the *reconstructed* matrix in the PE direction.  

Somewhat confusingly, the true physical total readout time and the "effective" total readout time basically end up being the same in the case of in-plane acceleration. i.e.,
```
true total readout time = true echo spacing * acquired matrix size in PE direction
"effective" total readout time =  "effective" echo spacing * recon matrix size in the PE direction = (true echo spacing / accel factor) * (acquired matrix size * accel factor)
```
The above equations don't account for the FSL convention of counting between the middle of the first and last echos (and thus the `-1` relative to the matrix size).

**Comment by mharms** [comment]
Note that in relation to @neurolabusc's comment above that acquisition **(3)** will indeed have a shorter `TotalReadoutTime` (as defined by `dcm2niix`, BIDS, and FSL) than acqusition **(1)**, but per my comment above the `TotalReadoutTime` of acquisition (3) is basically ends up being the same as the true readout time of acquisition **(3)**.

**Comment by XYWCQM** [comment]
@neurolabusc Thank you for your prompt reply，for the three points you mentioned (1) (2) (3), our understanding is the same, so you can calculate TotalReadoutTime by effectiveEchoSpacing * (reconMatrixPE-1.0)). Thank you.

**Comment by neurolabusc** [comment]
@XYWCQM can you provide explicit instructions for calculating effectiveEchoSpacing from UIH equipment. Siemens use private tags 0019,1028 and 0021,1153 for BandwidthPerPixelPhaseEncode. GE uses the private tag 0043,102C for effective echo spacing.  Should one use the PixelBandwidth (0018,0095) public tag?

For example, can you provide the formula we should use for [this example UIH sequence](https://github.com/neurolabusc/dcm_qa_uih/tree/master/In/DTI_132225/dti_tra_dir16_PA_rot_SaveBySlc__134057).

```
(0065,1029) SH [0.02]                                   #   4, 1 UIH AcquisitionDuration
(0018,0095) DS [1750]                                   #   4, 1 PixelBandwidth
(0018,1310) US 64\0\0\64                                #   8, 4 AcquisitionMatrix
```

**Comment by XYWCQM** [comment]
@neurolabusc UIH also use tags 0019,1028 for BandwidthPerPixelPhaseEncode, so you can use this tag to calculate effectiveEchoSpacing. Currently dcm2niix has been able to parse out effectiveEchoSpacing from UIH data. Thank you.
![image](https://user-images.githubusercontent.com/49193137/126734025-572c5d19-e10c-468b-a095-4cc8b7d6f2ae.png)

**Comment by neurolabusc** [comment]
None of the exemplars at [dcm_qa_uih](https://github.com/neurolabusc/dcm_qa_uih) include private tag 0019,1028. Is it possible to create a public example dataset that demonstrates this tag that could be included with the dcm_qa_uih repository? I do not like adding private tags without a concrete example.

**Comment by XYWCQM** [comment]
@neurolabusc Attached is the sample dicom I provided, you can verify it through the image, thank you.
[example_data.zip](https://github.com/rordenlab/dcm2niix/files/6871880/example_data.zip)

**Comment by neurolabusc** [comment]
@XYWCQM can you test the latest commit to the development branch (v1.0.20210724). It will use 0019,1028 for UIH scans where provided. If 0019,1028 is not present, it will fall back to the prior method. Please close this issue if this resolves your issue.

**Comment by XYWCQM** [comment]
@neurolabusc I now have the code of the development branch (v1.0.20210724), but the compilation fails, so I cannot verify the result.
![image](https://user-images.githubusercontent.com/49193137/127089849-63bf377f-0b3c-49f5-b533-506e31f0147d.png)

**Comment by neurolabusc** [comment]
I can not replicate your issue, the following cmake commands successfully complete:

```
git clone --branch development https://github.com/rordenlab/dcm2niix.git
cd dcm2niix
mkdir build && cd build
cmake ..
make
```

The minimal `make` also works:

```
git clone --branch development https://github.com/rordenlab/dcm2niix.git
cd dcm2niix/console
make
```

Perhaps you could provide information about your operating system (e.g. macOS 11.4, Windows 10, Linux Ubuntu 20.04). @ningfei is great at trouble shooting installation issues.

**Comment by XYWCQM** [comment]
@neurolabusc @ningfei I tried again according to your order, but the same error was reported. Below is the information of my system. Or is it convenient for you to test the compiled program for me?
![image](https://user-images.githubusercontent.com/49193137/127269633-86b279ae-6a7e-491e-bf04-25f7c37238ed.png)

**Comment by ningfei** [comment]
The above compiling issue was introduced in 1de5e5b. There `#include "tinydir.h"` was moved after `#include "nifti1_io_core.h"` in `nii_dicom_batch.cpp`. This causes the conflict.
- `dirent.h` is included in `tinydir.h`. In most of Ubuntu and CentOS releases (not ancient ones), `DT_UNKNOWN` is defined like [this](https://github.com/lattera/glibc/blob/master/dirent/dirent.h#L95-L117). That's why `undef` won't solve the problem. However, in some system `DT_UNKNOWN` is defined [this](https://github.com/apple/darwin-xnu/blob/mai`n/bsd/sys/dirent.h#L127-L135) way. So there's no conflict at all.
- To solve the problem, we simply need to move `"tinydir.h"` before `#include "nifti1_io_core.h"`.

If you agree I will push a fix for this.

**Comment by neurolabusc** [comment]
@ningfei I am really impressed you spotted this and the origin of the issue. My [kludge](https://github.com/rordenlab/dcm2niix/commit/21e9030327ec64ff63d83e13e569752bb4472e7b) was to simply remove the definition of DT_UNKNOWN, as it is never used in dcm2niix. It was simply copied over from the original [nifti1.h](https://nifti.nimh.nih.gov/pub/dist/src/niftilib/nifti1.h). Your detective work explains why the previous stable build compiles yet the latest development fails on some systems. Your solution is much more elegant. Please implement it.

**Comment by XYWCQM** [comment]
@neurolabusc @ningfei Thank you both for your prompt reply, now it can be compiled and passed. @neurolabusc In addition, the calculation result of TotalReadoutTime has also been verified, thank you again.

**Comment by ningfei** [comment]
Conflict of definition fixed in  358fb90

**Comment by Arshitha** [comment]
Hi - I'm using dcm2niix v1.0.20211006 with the following "-ba y" option. Some of the sidecars have `"TotalReadoutTime": inf,` which results in a JSONDecodeError. I'm mostly involved in curation of the dataset so I'm not sure why the field is 'inf' but my understanding from the BIDS spec is that it's expecting a number with units as seconds. I was wondering how if y'all had any recommendations on how to deal with it? 

```
{
	"Modality": "MR",
	"MagneticFieldStrength": 3,
	"ImagingFrequency": 127.697,
	"Manufacturer": "GE",
	"InternalPulseSequenceName": "EPI2",
	"ManufacturersModelName": "DISCOVERY MR750",
	"BodyPartExamined": "BRAIN",
	"PatientPosition": "HFS",
	"ProcedureStepDescription": "MRI Brain",
	"SoftwareVersions": "27\\LX\\MR Software release:DV26.0_R01_1725.a",
	"MRAcquisitionType": "2D",
	"SeriesDescription": "Trace:Mar 27 2018 16-44-00 EDT",
	"ProtocolName": "ADNI3 FMRIF Enhanced Pro",
	"ScanningSequence": "EP\\SE",
	"SequenceVariant": "NONE",
	"ScanOptions": "SAT_GEMS\\EPI_GEMS\\FILTERED_GEMS\\ACC_GEMS\\PFF\\FS",
	"ImageType": ["DERIVED", "SECONDARY", "PROCESSED"],
	"RawImage": false,
	"SeriesNumber": 750,
	"AcquisitionNumber": 1,
	"SliceThickness": 2,
	"SAR": 0.470471,
	"EchoTime": 0.0618,
	"RepetitionTime": 7.8,
	"FlipAngle": 90,
	"CoilString": "32Ch Head",
	"PercentPhaseFOV": 100,
	"PercentSampling": 100,
	"AcquisitionMatrixPE": 116,
	"ReconMatrixPE": 128,
	"TotalReadoutTime": inf,
	"PixelBandwidth": 3906.25,
	"PhaseEncodingAxis": "j",
	"ImageOrientationPatientDICOM": [
		1,
		0,
		0,
		0,
		1,
		0	],
	"InPlanePhaseEncodingDirectionDICOM": "COL",
	"ConversionSoftware": "dcm2niix",
	"ConversionSoftwareVersion": "v1.0.20211006"
}
```

**Comment by neurolabusc** [comment]
@Arshitha do you have access to the DICOMs, and can you share them as a zip archive via Box/GoogleDrive with a link sent to my email (listed in my avatar)? We require some [private tags](https://github.com/rordenlab/dcm2niix/tree/master/GE) to compute this for GE scans, so I wonder if some DICOM anonymization disrupted the detection of `TotalReadoutTime`.

Seeing that your manufacturer is GE not UIH, I think this should be a new issue.
