### ISSUE TITLE
GE ABCD epi_pepolar sequence 

### ISSUE THREAD

**Issue by neurolabusc** [rordenlab/dcm2niix#532]
This issue describes the `epi_pepolar` GE ABCD WIP (work in progress) sequence designed for acquiring data for [FSL TOPUP](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/topup). TOPUP undistorted EPI images by using a pair of spin-echo series that are identical except for the phase encoding polarity. For example, both an anterior-to-posterior and posterior-to-anterior EPI sequence will exhibit nonlinear spatial distortions. However, they exhibit distortions of equal magnitude but precisely opposite direction. Typically, these pairs are acquired as two series. However, the `epi_pepolar` acquires both phase encoding directions in a single series, with volumes every volume reversing the phase encoding polarity. The DICOM headers report the same phase encoding direction for all volumes. Bizarrely, the reversed images are stored to disk with the row order reversed, but no difference in spatial alignment is recorded in the DICOM header. Therefore, half of the volumes incorrectly specify the spatial alignment. 

These sequences are identified by the Private PulseSequenceName tag (0019,109C) including text `epi_pepolar` and the private UserData12 tag (0019,10B3) reports the phase encoding polarity scheme (0=fwd; 1=rev; 2=r-f; 3=f-r, default=2).

Consider the case of a scan where UserData12 is 2. Here, all odd scans are stored with reversed row order, and have the opposite phase encoding polarity than specified. Presumably, scans where UserData12 is 3 reverse the even volumes. No examples of UserData12 of 1 have been seen, so it is unclear if the DICOM header includes the correct or reversed spatial mapping for these scans.

Users need to be aware that the spatial encoding in half the volumes is incorrect, and this will cause valid DICOM tools to incorrectly display these images. Here a kludge is presented, but an upstream solution that generates valid DICOM images would be preferred.

The latest release of the dcm2niix developmental branch (v1.0.202100811) attempts to automatically split these sequences into two series, with the phase reversed series having the series number incremented by 1000. The row order is flipped, as is the `PhaseEncodingDirection` polarity. Validation is only based on a single example, so users should proceed with caution.

Links

 - This issue was first described [here](https://github.com/nipy/heudiconv/issues/479), with details provided by @mr-jaemin.
 - This issue has confounded users as described [here](https://neurostars.org/t/question-on-how-to-use-fieldmap-with-fmriprep/19924/10).

**Comment by neurolabusc** [comment]
The latest commit to the development branch (v1.0.202100814) comprehensively fixes this issue. I am grateful to Scott Peltier and Krisanne Litinas for providing an open source validation dataset that illustrates all possible modes:  [dcm_qa_polar](https://github.com/neurolabusc/dcm_qa_polar).

**Comment by xiangruili** [comment]
@neurolabusc 
I may miss something on this topic, but I agree with your original thought that any fix we apply for this may have unexpected consequence.

1. It is okay to save AP/PA into one series per DICOM standard, although it is unfortunate practically.
2. It is a HUGE MISTAKE per DICOM standard with wrong ImageOrientationPatient.

Given #2, DICOM tools in medical field will interpret the images incorrectly. So there is a chance that they will correct the mistake someday, given it is WIP. They may change the PulseSequenceName to indicate the correction, but more likely they will change their version number to indicate the correction. Then our fix will cause problem.

The cleanest solution, in my opinion, is for them to store the images in consistent orientation and to label the phase direction correctly, or more practically, to store images into 2 series.

**Comment by neurolabusc** [comment]
I entirely agree with you. Pragmatically, I decided to support this sequence because it has achieved widespread adoption, and it seems easiest to identify and fix the issue once at the DICOM to NIfTI stage. However,  the risk of unintended consequences is real, and I may live to regret this decision. Your view is completely justified.

**Comment by neurolabusc** [comment]
This issue is closed. All future releases will handle these unusual images. For any pipelines that expect the old behavior, or wish to match the canonical behavior of @xiangruili's dicm2nii, dcm2niix can be compiled without this kludge. This option also provides a mechanism to trouble shoot any unintended consequences of the kludge:

```
make CFLAGS=-DmyDisableGEPEPolarFlip
```

**Comment by mr-jaemin** [comment]
I have summarized this issue here with an illustrative example: 
[ABCD_epi_pepolar.pdf](https://github.com/rordenlab/dcm2niix/files/7212901/ABCD_epi_pepolar.pdf)

![Slide1](https://user-images.githubusercontent.com/72111485/134398483-51f8a491-1da7-43a1-a05e-531c08b75209.png)
![Slide2](https://user-images.githubusercontent.com/72111485/134398497-88e2cbe5-a496-48cd-a449-1d730aa46d19.png)
