### ISSUE TITLE
When I convert DWI dicoms, the dimension is wrong

### ISSUE THREAD

**Issue by mujinbao** [rordenlab/dcm2niix#537]
Dear author, hello
As you know, usually the DWI sequence contains twice the number of others (such as T1), because it contains two sets of pictures under b0 and b1000, so when I used the tool to convert, it was originally 40 slices, but after the conversion was completed Got a nii with 20 slices
I feel that because the heights of the two groups of images under the b value are the same, I only chose one of them. I don’t know if my guess is correct, so do you think this problem can be solved, thank you

**Comment by neurolabusc** [comment]
@mujinbao I am unable to provide a diagnosis based on the information you have provided. Feel free to share a dataset with me by sending a DropBox/GoogleDrive link to my email address (in my avatar).

Raw diffusion data for DTI analyses should have at least 6 directions, so it should generate a 4D image with at least 7 volumes (as it includes the b=0 volume). For some derived DWI data, a single series may result in several derived images (e.g. trace, ADC), each of which will be saved as a separate volume.

**Comment by neurolabusc** [comment]
Closing underspecified issue. Perhaps data is derived diffusion parameters (e.g. Trace, ADC) not raw diffusion data.
