### ISSUE TITLE
Potential Enhancement: include entity index value as metadata field?

### ISSUE THREAD

**Issue by dlevitas** [rordenlab/dcm2niix#547]
As of [BIDS Specification 1.6.0](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html), there are several entity labels ( besides `run`) that require a nonnegative integer index value: `echo`, `inv`, and `flip`. 

For multiecho data, dcm2niix provides both the EchoTime and EchoNumber metadata fields. I'm curious whether this same logic could be applied to `inv` (InversionTime) and `flip` (FlipAngle)? For example, if dcm2niix detects the presence of an InversionTime, another metadata field (perhaps InversionNumber) would be included as well. This would potentially be helpful for BIDS converters in situations where the specific acquisition requires such an entity label. 

I'm unsure how feasible this would be from the perspective of dcm2niix, or whether this addition would require the buy-in of the BIDS Standard team, but I wanted to see if such an enhancement would be possible and make sense to include?

Thanks

**Comment by neurolabusc** [comment]
I think if a user wants to see these features implemented, they should provide an open dataset that illustrates the features, similar to all the existing dcm_qa* regression datasets. For example, [dcm_qa_stc](https://github.com/neurolabusc/dcm_qa_stc) demonstrates how to extract the BIDS slice timing parameters from GE scanners. These validation datasets illustrate that the definitive DICOM tags, allow all DICOM to BIDS converters (e.g. dcm2niix, dicm2nii, etc) work consistently, and are available for regression testing. Without looking into it, I am not sure if any of the vendors list the total number of inversions, number of flips or echo numbers in their sequences.

Until we are confident that we can reliably extract these tags from the source images, these details should be handled by [higher level BIDS tools](https://github.com/rordenlab/dcm2niix#links) that are easier to script and modify for unique properties of a particular study. 

During the early development of BIDS, fields were chosen that met two criteria (1) useful for subsequent processing and (2) available in the source data. There are now far more scientists drafting new BIDS extensions, and the main focus seems to with issue (1). This will leave the onus on the user to supply data that is desirable, but not available in the source images.

**Comment by dlevitas** [comment]
Understandable. I forgot to check whether a DICOM tag with InversionNumber exists (there doesn't appear to be). DICOM tag 0018 0086 provides the EchoNumber, which I suppose is why it's contained in the metadata. 

If anything changes, I'll reopen this issue.
