### ISSUE TITLE
Building on MacOS Sierra - linker error: library not found -lyaml-cpp

### ISSUE THREAD

**Issue by dangom** [rordenlab/dcm2niix#55]
I suppose this has to do with MacOS Sierra, because I had no problems building `dcm2niibatch` before updating the OS. No matter what version of Cmake I use, I get the following linker error:

> ld: library not found for -lyaml-cpp

To get things working I have to manually add `-L/usr/local/lib` to the `console/CMakeFiles/dcm2niibatch.dir/link.txt` file.

I was wondering if this can be reproduced, or if anyone has had the same issues?

I'm linking against the latest yaml-cpp as installed per homebrew.

**Comment by neurolabusc** [comment]
@benjaminirving supports the YAML-based dcm2niibatch, and I do not have OSX Sierra. However, I assume you can still build the generic (non-batching) dcm2niix by using the "make" command which will run
  g++ -dead_strip -O3 -I. main_console.cpp nii_dicom.cpp jpg_0XC3.cpp ujpeg.cpp nifti1_io_core.cpp nii_ortho.cpp nii_dicom_batch.cpp  -o dcm2niix -DmyDisableOpenJPEG -DmyDisableJasper

**Comment by dangom** [comment]
Yes, building dcm2niix works just fine. 
The problem only affects linking dcm2niibatch against yaml-cpp.

**Comment by benjaminirving** [comment]
@neurolabusc,  the generic dcm2niix should also still run using cmake build. 

@dangom, thanks for the report.  that's strange. I have been holding off upgrading to macOS Sierra for the meanwhile. The upgrade Sierra might have broken your homebrew links. Have you tried uninstalling and reinstalling yaml-cpp after upgrade? Otherwise, I'll take the plunge and upgrade to Sierra.

**Comment by dangom** [comment]
I've tried reinstalling both `yaml-cpp` and `libyaml`, and rolling back to an earlier version of `cmake`. The problem persisted. 
I also don't think this has anything to do with homebrew. All paths look correct when I check the cmake generated files.

Unfortunately I can't go back and check the `links.txt `generated on El Capitan, because I don't have it anymore. Do you see if the flag `-L/usr/local/lib` is set?

Perhaps it's easier to add something to the CMakeLists.txt to add this extra flag, rather than risking the update?

**Comment by benjaminirving** [comment]
`-L/usr/local/lib` is not set in `links.txt` on El Capital. Only `-lyaml-cpp'

It sounds like for some reason `/usr/local/lib` has been dropped from the default compiler search path in macOS Sierra. 

Could you run `clang -Xlinker -v` in bash. I get

```bash
Library search paths:
/usr/lib
/usr/local/lib
```

I agree with you and I'll add it as an extra flag on the CMakeLists.txt to be safe.

**Comment by benjaminirving** [comment]
Could you see if this branch fixes your issue?

https://github.com/rordenlab/dcm2niix/tree/sierra_yaml_fix

Thanks,
Ben

**Comment by dangom** [comment]
Hi Ben,

the branch fixes the issue.
Running `clang -Xlinker -v` gives me the following lib search paths:

> Library search paths:
> 	/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/lib

And here is the version info:

```
$ clang -v
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin16.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Either a feature of the Sierra upgrade or an issue with my computer.

In any case, thanks for the quick answers.

Cheers,
Daniel

**Comment by benjaminirving** [comment]
Thanks Daniel.
