### ISSUE TITLE
Mosaic

### ISSUE THREAD

**Issue by rhedouin** [rordenlab/dcm2niix#550]
Hello, 
I have a problem [issue #369 about mosaic image], (I also posted there before to see that it was closed, sorry for the duplicate). I tried your solution (go to the development branch) but it doesn't work in my case. I still have the following warning

Warning: Assuming icon SQ 07a3,10ce.
Unsupported overlay origin 0/0
Warning: 0008,0008=MOSAIC but number of slices not specified: controls_Tours_cusp_dicom_1/ACTIDEP-03011_1.4.9.12.34.1.8527.2207176245825200820373228239247760676011.dcm

If I understand correctly your answer, dcm2niix guess that the mosaic is 7x7 images ? In my case it's 9x9.
I'm also not sure what the unsupported overlay origin means never.

Thanks for any help you could afford.
Best, 
Renaud

**Comment by neurolabusc** [comment]
Thanks for the example images. I think you want to check the provenance of these images, and convert copies prior to their corruption. These are limitations in your DICOM data, not dcm2niix. Here are some of the limitations of your DICOM images:

 1. The [CSA header](https://nipy.org/nibabel/dicom/siemens_csa.html) has been removed, beyond revealing the number of slices in a mosaic, this structure also stores the diffusion gradient vectors which will be required to analyze these diffusion images.
 2. Icons have been inserted into these images. This increases file size and often cause issues. I was surprised that these refer to [Elscint which merged in 1998](https://www.diagnosticimaging.com/view/picker-and-ge-complete-deals-acquire-elscint-business-units).
 3. I notice that these images were touched by a dcm4che PACS system. I would be wary of this, as these tools can [obfuscate DICOM](https://github.com/neurolabusc/dcm_qa_agfa) (which is already a complicated standard), disrupting popular tools.
 4. The images were acquired as a 9x9 mosaic. I assume the original images were saved as 990 rows and 990 columns, but the data has been reformatted to 992 columns. Presumably, some tool padded the rows to make them evenly divisible by 8. However, 992 is **not** evenly divisible by 9. This explains why dcm2niix refuses to de-mosaic the data.

```
(6000,0010) US 990                                      #   2, 1 OverlayRows
(6000,0011) US 992                                      #   2, 1 OverlayColumns
(0018,1310) US 110\0\0\110                              #   8, 4 AcquisitionMatrix
```
