### ISSUE TITLE
Which metadata fields are removed during anonymization?

### ISSUE THREAD

**Issue by dlevitas** [rordenlab/dcm2niix#557]
I was wondering if there's a list that specifies which metadata fields are excluded when the conversion process is anonymized? [This post](https://github.com/rordenlab/dcm2niix/issues/304#issuecomment-512766519) provides several fields; however, as of version (v1.0.20211006) at least, `AcquisitionDate` is excluded as well.

**Comment by neurolabusc** [comment]
The relevant code is [here](https://github.com/rordenlab/dcm2niix/blob/003f0d19f1e57b0129c9dcf3e653f51ca3559028/console/nii_dicom_batch.cpp#L1228) and [here](https://github.com/rordenlab/dcm2niix/blob/003f0d19f1e57b0129c9dcf3e653f51ca3559028/console/nii_dicom_batch.cpp#L1309). The following are not included in the BIDS if the file is anonymized:

```
SeriesInstanceUID
StudyInstanceUID
ReferringPhysicianName
StudyID
PatientName
PatientID
AccessionNumber
PatientBirthDate
PatientSex
PatientWeight
AcquisitionDateTime
```

While dcm2niix considers the day of the scan information that might reveal the identity, the time of day is not . Specifically, the [AcquisitionTime](https://github.com/rordenlab/dcm2niix/blob/003f0d19f1e57b0129c9dcf3e653f51ca3559028/console/nii_dicom.cpp#L651) will be saved directly into the `description` field of the NIfTI header. The rationale is that this includes synchronization with physiological measures.

Consider a few NIfTI images:

```
$ fslhd philips.nii
...
descrip		TE=2.9;Time=130013.040

$ fslhd siemens.nii
...
descrip		TE=30;Time=134935.305;phase=1
```

**Comment by dlevitas** [comment]
Ah, good to know, thanks
