### ISSUE TITLE
Orientation changed after converting to nii

### ISSUE THREAD

**Issue by cloudpanl** [rordenlab/dcm2niix#564]
I use dcm2niix to convert CT, and use ITK-SNAP to check that the direction of dicom is RAI. After converting to nii, the direction of nii becomes RPI. For other series, ASL becomes AIL. Why does the direction change? Is there something wrong with me? Thanks!My version is v1.0.20210317

**Comment by neurolabusc** [comment]
DICOM and NIfTI have [different spatial coordinate systems](https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#Spatial_Coordinates). The DICOM standard has the first row at the top of the screen, with later rows below (the way we write English). On the other hand, NIfTI has the first row at the bottom of the screen, with higher line numbers higher on the screen (the way we draw a cartesian graph, the the Y coordinate ascending up the screen). Likewise, DICOM the X coordinate becomes more positive as we move left, where for NIfTI the x increases as we move right.

This change is lossless. The row order is swapped in conversion, and the spatial transformation matrix reflects this.

I would always recommend the [latest stable release](https://github.com/rordenlab/dcm2niix/releases), the manufacturers are evolving DICOM and our understanding of their implementations is growing.
