### ISSUE TITLE
Error:  Recompiling with '-DmyInstanceNumberOrderIsNotSpatial' might help.

### ISSUE THREAD

**Issue by weberam2** [rordenlab/dcm2niix#565]
**Describe the bug**

I sometimes get this error: "Error:  Recompiling with '-DmyInstanceNumberOrderIsNotSpatial' might help." 
But I can rerun dcm2niix and then I don't get the error...
I'm not sure what's going on...

**To reproduce**
Example:
dcm2niix -b y -ba y -z y -f '%3s_%f_%d_%r' -o ./tmp_dcm2bids/sub-REGTRJ004A sourcedata/REGTRJ004A/

**Expected behavior**

I expect it to run every time... not just sometimes. This error will pop up, but if I run it again, exactly the same, sometimes it works...

**Output log**

INFO:dcm2bids.dcm2bids:--- dcm2bids start ---                                                         
INFO:dcm2bids.dcm2bids:OS:version: Linux-5.11.0-40-generic-x86_64-with-debian-bullseye-sid            
INFO:dcm2bids.dcm2bids:python:version: 3.7.10 (default, Jun  4 2021, 14:48:32) [GCC 7.5.0]            
INFO:dcm2bids.dcm2bids:dcm2bids:version: 2.1.6                                                        
INFO:dcm2bids.dcm2bids:dcm2niix:version: v1.0.20211006                                                
INFO:dcm2bids.dcm2bids:participant: sub-REGTRJ004A                                                    
INFO:dcm2bids.dcm2bids:session:                                                                       
INFO:dcm2bids.dcm2bids:config: /mnt/WeberLab/Projects/Trajectory_8Year/sourcedata/REGTRJ004A/BIDS_conf
ig.json                                                                                               
INFO:dcm2bids.dcm2bids:BIDS directory: /mnt/WeberLab/Projects/Trajectory_8Year                        
WARNING:dcm2bids.dcm2niix:Previous dcm2niix directory output found:                                   
WARNING:dcm2bids.dcm2niix:./tmp_dcm2bids/sub-REGTRJ004A                                               
WARNING:dcm2bids.dcm2niix:'force' argument is set to True                                             
WARNING:dcm2bids.dcm2niix:Cleaning the previous directory and running dcm2niix                        
INFO:dcm2bids.utils:Running dcm2niix -b y -ba y -z y -f '%3s_%f_%d_%r' -o ./tmp_dcm2bids/sub-REGTRJ004
A sourcedata/REGTRJ004A/                                                                              
Error:  Recompiling with '-DmyInstanceNumberOrderIsNotSpatial' might help.                            
Error: Converted 6724 of 12964 files                                                                  
Traceback (most recent call last):                                                                    
  File "/home/aweber/anaconda3/bin/dcm2bids", line 8, in <module>                                     
    sys.exit(main())                                                                                  
  File "/home/aweber/anaconda3/lib/python3.7/site-packages/dcm2bids/dcm2bids.py", line 291, in main   
    return app.run()                                                                                  
  File "/home/aweber/anaconda3/lib/python3.7/site-packages/dcm2bids/dcm2bids.py", line 120, in run    
    dcm2niix.run(self.forceDcm2niix)                                                                  
  File "/home/aweber/anaconda3/lib/python3.7/site-packages/dcm2bids/dcm2niix.py", line 77, in run     
    self.execute()                                                                                    
  File "/home/aweber/anaconda3/lib/python3.7/site-packages/dcm2bids/dcm2niix.py", line 100, in execute    output = run_shell_command(cmd)
  File "/home/aweber/anaconda3/lib/python3.7/site-packages/dcm2bids/utils.py", line 113, in run_shell_
command
    return check_output(shlex.split(commandLine))
  File "/home/aweber/anaconda3/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/home/aweber/anaconda3/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['dcm2niix', '-b', 'y', '-ba', 'y', '-z', 'y', '-f', '%3s_%f_%
d_%r', '-o', './tmp_dcm2bids/sub-REGTRJ004A', 'sourcedata/REGTRJ004A/']' returned non-zero exit status
 8.

**Version**

v1.0.20211006

**Comment by neurolabusc** [comment]
@weberam2 it is unclear to me if this is a dcm2niix issue or a dcm2bids issue. Further, the dcm2bids is only reporting the error, not the diagnostic message that precede the error. I think the first step is determining if running dcm2niix from the command line generates this error, and logging all the other messages that are elicited by this data: 

```
dcm2niix -b y -ba y -z y -f '%3s_%f_%d_%r' -o ./tmp_dcm2bids/sub-REGTRJ004A sourcedata/REGTRJ004A/
```

My best guess is that there are some slices missing from this dataset, either because of a storage issue or because the sequence was interrupted.

The next step would be to renaming the DICOMs to segment each series, and then identify the troublesome series in the dataset. The following command will rename the series, and then you would run dcm2niix individually for each new series subfolder that is created to divide and conquer:

```
dcm2niix -r y - sourcedata/REGTRJ004A/
```

**Comment by neurolabusc** [comment]
Closing issue, insufficient information to replicate or understand if this reflects an issue of the DICOMs, dcm2bids or dcm2niix.
