### ISSUE TITLE
Fall 2021 release incorrectly orders slices of Philips functional scan that appears okay when converted with the Spring 2021 release

### ISSUE THREAD

**Issue by psadil** [rordenlab/dcm2niix#567]
**Describe the bug**

The Fall 2021 release of `dcm2niix` seems to have trouble with a functional series collected on a Philips scanner. Towards the end of the run, slices from the brain appear at the top of the stack

![fall-central](https://user-images.githubusercontent.com/8172767/146086977-dc66269b-602b-4d43-b231-62d109a0bfc2.png)

In the next image, notice that the top slice looks like it's from the middle of the brain

![fall-dorsal](https://user-images.githubusercontent.com/8172767/146086976-006a2f05-5555-481f-9faa-5192c898136d.png)

The specific slice that is placed at the top appears to change with each volume, such that scrolling through time smoothly changes which axial slice has ended up at the top of the volume. 

**To reproduce**

If it would be helpful to diagnose the issue, a resting state scan that shows this issue is available to be shared (~300 MB zipped).

**Expected behavior**

A series that looks more like what was produced in the previous release. The image below is the same timepoint. Note the lack of a floating slice at the top of the image.

![march](https://user-images.githubusercontent.com/8172767/146086940-ab8d0cee-ef45-405c-9327-c00447df4bd4.png)

That an earlier version could produce a seemingly correct nifti makes me hopeful that there is information available in the dicoms. 

**Output log**

Fall Release (looks strange)

```
$ dcm2niix -o fall -z o REST2
Chris Rorden's dcm2niiX version v1.0.20211006  (JP2:OpenJPEG) (JP-LS:CharLS) GCC9.3.0 x86-64 (64-bit Linux)
Found 24300 DICOM file(s)
Error: Check sorted order: 4D dataset has 450 volumes, but volume index ranges from 1..2
Philips Scaling Values RS:RI:SS = 0.900611:0:0.0481327 (see PMC3998685)
Convert 24300 DICOM as fall/REST2_REST2_20201002090808_1101 (96x96x54x450)
Conversion required 26.469826 seconds (14.464492 for core code).


```

Spring Release (looks find)

```
$ dcm2niix -z o -o march REST2
Chris Rorden's dcm2niiX version v1.0.20210317  (JP2:OpenJPEG) (JP-LS:CharLS) GCC9.3.0 x86-64 (64-bit Linux)
Found 24300 DICOM file(s)
Philips Scaling Values RS:RI:SS = 0.900611:0:0.0481327 (see PMC3998685)
Convert 24300 DICOM as march/REST2_REST2_20201002090808_1101 (96x96x54x450)
Conversion required 24.822404 seconds (13.364827 for core code).
```

**Version**

The main comparison is between

 - `Chris Rorden's dcm2niiX version v1.0.20210317  (JP2:OpenJPEG) (JP-LS:CharLS) GCC9.3.0 x86-64 (64-bit Linux)
v1.0.20210317`

and

 - `Chris Rorden's dcm2niiX version v1.0.20211006  (JP2:OpenJPEG) (JP-LS:CharLS) GCC9.3.0 x86-64 (64-bit Linux)
v1.0.20211006`

**Troubleshooting**

Running with the latest development branch produces a nifti that looks like the one built by the Fall release

```
$ dcm2niix -z o -o dev REST2
Chris Rorden's dcm2niiX version v1.0.20211010  (JP2:OpenJPEG) (JP-LS:CharLS) GCC9.3.0 x86-64 (64-bit Linux)
Found 24300 DICOM file(s)
Error: Check sorted order: 4D dataset has 450 volumes, but volume index ranges from 1..2
Philips Scaling Values RS:RI:SS = 0.900611:0:0.0481327 (see PMC3998685)
Convert 24300 DICOM as dev/REST2_REST2_20201002090808_1101 (96x96x54x450)
Conversion required 29.625847 seconds (17.087879 for core code).
```

**Comment by neurolabusc** [comment]
I do not have access to Philips equipment. Feel free to package all DICOMs into a single zip archive and send a link to the GoogleDrive/DropBox file to my email (listed in my avatar).

**Comment by neurolabusc** [comment]
@psadil please try the latest commit to the development branch (v1.0.20211215). The prior version had given precedence to the private tag MRfMRIStatusIndication (2005,1063) over the public tag TemporalPositionIdentifier (0020,0100). I have no idea why they are in conflict for your data (SoftwareVersions : 5.6.1). However, the latest version will only use the private tag as a last resort. This will correctly sort your data and remove the error message.

**Comment by psadil** [comment]
@neurolabusc Thanks for the fix. This is to confirm that the patch seems to work, allowing the images to be converted without the floating slice. Though, I think the commit was made to the master rather than development branch.
