### ISSUE TITLE
How many images does dcm2niix generate for specific qMRI field maps?

### ISSUE THREAD

**Issue by dlevitas** [rordenlab/dcm2niix#569]
This a cross-post from [here](https://github.com/bids-standard/bids-specification/issues/964).  The documentation for some qMRI field maps (`TB1DAM`, `TB1SRGE`, `TB1map`, `RB1map`) is sparse, and our scanner can't acquire these specific sequences to test. I was wondering how many images dcm2niix produces for those qMRI field map sequences?

I found the [paper](https://onlinelibrary.wiley.com/doi/pdf/10.1002/mrm.23145) for the TB1SRGE sequence, which seems to suggest two images; however, I wanted to clarify whether that's how scanners outputs things.

**Comment by neurolabusc** [comment]
See my comments [here](https://github.com/bids-standard/bids-specification/issues/964).
