### ISSUE TITLE
Preventing reorientation?

### ISSUE THREAD

**Issue by lwallace233** [rordenlab/dcm2niix#57]
We have a DICOM dataset that is 16-bit with 256x256 resolution and 176 slices in coronal orientation and comes out of conversion as a NIFTI dataset that is 16-bit with 176x256 resolution and 256 slices in axial orientation. Is there a way to stop the reorientation from occurring?

In dcm2nii there seems to have been a MinReorientMatrix defined in the .dcm2nii.ini file where matrices over the size given (the default was 255) were reoriented and ones below that threshold were not, and the threshold could be changed as necessary, but I do not see a similar parameter anywhere in dcm2niix.

**Comment by neurolabusc** [comment]
I see this as a feature: by default dcm2nii, dcm2niix, and dicm2nii will lossless reorient 3D acquisitions so the data is saved to disk aligned orthogonally to the NIfTI identity rotation matrix. This allows the images to appear in sensible orientations for tools that ignore the NIfTI spatial orientation matrix (e.g. FSLview). I only due this for 3D acquisitions, so it is not applied to DTI data (where we would need to reorient the BVECs) and 2D EPI fMRI data (where we apply slice timing correction).

It is true that dcm2nii allowed you to control this, but the more features one adds the more daunting the usage is for new users and the more difficult the code is to maintain. I really do not know why one wouldn't want to reorient 3D images, so I removed this. However, if you download the latest code from github you will see that I have added a new compiler switch that allows you to disable this feature: "myDisableReorient3dToOrtho". So if you want to remove this feature simply compile your own copy with this command, e.g.

g++ -dead_strip -O3 -I. main_console.cpp nii_dicom.cpp jpg_0XC3.cpp ujpeg.cpp nifti1_io_core.cpp nii_ortho.cpp nii_dicom_batch.cpp  -o dcm2niix -DmyDisableOpenJPEG -DmyDisableJasper -DmyDisableReorient3dToOrtho
