### ISSUE TITLE
Windows installation

### ISSUE THREAD

**Issue by xyzthe117** [rordenlab/dcm2niix#571]
Can you provide the way to install in windows by command line please. I tried curl but it doesn't work

**Comment by neurolabusc** [comment]
1. What version of Windows are you using?  You can find out by running `systeminfo` from the command line.

2. Is curl not installed or is curl generating an error? If the latter, what error is reported? curl is included with Windows 10 build 17063 and later. So perhaps you simply need to update Windows. 

3. Do you have conda installed? If so, have you tried `conda install -c conda-forge dcm2niix`.

**Comment by ningfei** [comment]
@xyzthe117 what's the output of curl? Guess it might be your firewall?
