### ISSUE TITLE
Different scaling when using version 6-October-2021 (v1.0.20211006) and version 2-November-2020 (v1.0.20201102)

### ISSUE THREAD

**Issue by sandeepganji** [rordenlab/dcm2niix#575]
I was doing some ASL processing (Data from: Philips Scanner) and noticed very high values for the CBF maps. After some digging found that when I opened the NIFTI using MRICRO the "Image Intensity" -> "Calibration scaling" created from 6-October-2021 (v1.0.20211006) was ~275 times that of NIFTI created from version 2-November-2020 (v1.0.20201102), for the ASL sources images. It was also the case for the T1 and FLAIR data.

Was there a significant change of the scaling between the two releases?
The json sidecar values for "PhilipsRWVSlope", "PhilipsRWVIntercept", "PhilipsRescaleSlope", "PhilipsRescaleIntercept" where same from both the versions.

Any suggestions?

**Comment by neurolabusc** [comment]
Described in the release notes of [v1.0.20210317](https://github.com/rordenlab/dcm2niix/releases/tag/v1.0.20210317)
  - [Philips uses precise intensity scaling, not real world values](https://github.com/rordenlab/dcm2niix/issues/493)

For further details see the [Philips image scaling notes](https://github.com/rordenlab/dcm2niix/tree/master/Philips#image-scaling). The [DICOM](https://www.kitware.com/dicom-rescale-intercept-rescale-slope-and-itk/) and [NIfTI](https://nifti.nimh.nih.gov/pub/dist/src/niftilib/nifti1.h) standards each only allows one intensity transform to convert the integer-based voxel intensities to floating point values. For all manufacturers except Philips, the provides a one-to-one mapping for DICOM and NIfTI. However, Philips uses private tags that can specify different calibrations for the same image. Some tools rely on one method or the other, so dcm2niix will store the manufacturer specific transforms in the BIDS header.

@drmclem wrote the first draft of the Philips image scaling notes, and may be able to provide further information.

**Comment by neurolabusc** [comment]
@HenkMutsaerts and @jan-petr who are lead developers for [ExploreASL](https://github.com/ExploreASL/ExploreASL) may have comments. I am generally reluctant to change the default behavior of dcm2niix between versions. However, I have relied heavily on @drmclem for all things related to Philips. My sense is that different teams have come to rely on different Philips transforms, and these can [have an impact](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3998685/).

**Comment by jan-petr** [comment]
My experience was that v20190902 can safely recognize all "PhilipsRescaleSlope", “PhilipsRescaleIntercept", and "PhilipsRWVSlope" values and ouputs them correctly to JSON.

With the option "UsePhilipsFloatNotDisplayScaling": 1, it scaled everything correctly to the floating point and not display values.
However, in the presence of "PhilipsRWVSlope" (which was at least in my examples equivalent to "PhilipsRescaleSlope"), it scaled the output NII to these display values. I would assume that this behavior has changed in the latest version and the output is now scaled correctly to floating-point values also in the presence of "PhilipsRWVSlope" - but creating a large difference between versions.

Also note, that some older versions of dcm2niix only used to look into DICOM fields (2005x100e) and (2005x100d) for the PhilipsScaleSlope and Intercept and didn't try to look into (2005x110e) and (2005x110d) or (2005x120e) and (2005x120d), which are the alternative locations (to my understanding) - this might have been added though in the latest versions.

**Comment by neurolabusc** [comment]
My center does not have access to Philips equipment. In my experience, Philips is the only vendor that generates multiple potential scaling factors for a single image. Likewise, in my experience it is the only vendor that can apply different scaling factors to each 2D slice of a 3D volume (which is not supported by NIfTI, which requires dcm2niix to promote these images from integer to floating point representations).  @jan-petr dcm2niix is unaware of the private tags (2005x110e) and (2005x110d) or (2005x120e) and (2005x120d). If someone want to see these supported, they should either provide exemplar images or generate a pull request. 

Over the years, different teams have advocated for different Philips scaling factors to be given precedence when determining the NIfTI `scl_slope` and `scl_inter`. It is impossible to please all these conflicting requests, so I have tried to faithfully reproduce the various scaling factors in the BIDS JSON file. The current behavior of precedence was championed by @drmclem. He deserves tremendous credit for ensuring that dcm2niix provides robust support for Philips evolving interpretation of the DICOM standard.

**Comment by sandeepganji** [comment]
the issue is that the scaling number seem different even of T1W and FLAIR images.

**Comment by neurolabusc** [comment]
Closing this issue: Philips often provides multiple image intensity transforms for a single image, while NIfTI allows only one transform. There is no consensus regarding the precedence between the competing transforms. In these situations, dcm2niix records the possible transforms in the BIDS JSON header. The current dcm2niix precedence strategy is clearly described in the documentation. Users and developers should contact their regional Philips Clinical Scientist for guidance.
