### ISSUE TITLE
dcm2niix gives out too much warning messages 

### ISSUE THREAD

**Issue by JuenGuo** [rordenlab/dcm2niix#576]
I am using dcm2niix_afni to convert dcm to nii with  version v1.0.20211006  GCC5.4.0 x86-64 (64-bit Linux).
My dcm's are PET images (Positron emission tomography) from Siemens HRRT.  Somehow dcm2niix doesn't not recognize the name of manufacture in the header of dcm files and gives out tons of warning messages (one warning each dcm file). is it possible to suppress these warning message? 
The warning messages are like below:
Warning: Unknown Manufacturer CPS
Warning: Unknown Manufacturer CPS
.............(thousands of repeated warnings)....
Warning: Unknown Manufacturer CPS
Warning: Unable to determine manufacturer (0008, 0070) so conversion is not tuned for vendor.

**Comment by neurolabusc** [comment]
The DICOM standard is very complicated, and each manufacturer interprets DICOM differently: consider [Canon](https://github.com/rordenlab/dcm2niix/tree/master/Canon), [GE](https://github.com/rordenlab/dcm2niix/tree/master/GE), [Philips](https://github.com/rordenlab/dcm2niix/tree/master/Philips), [Siemens](https://github.com/rordenlab/dcm2niix/tree/master/Siemens), and [UIH](https://github.com/rordenlab/dcm2niix/tree/master/UIH). Your warnings suggest over agressive anonymization, which has removed the manufacturer tag (0008,0070) and likely much other crucial details. I would strongly suggest you determine why the manufacturer is not being detected, this warning should be taken seriously.

If you really want to disregard these warnings, you can make a fork of dcm2niix and modify it as you wish. You should carefully audit the behavior to ensure that there are not other issues.

**Comment by JuenGuo** [comment]
thank neurolabusc for your quick comments. I think dcm2niix was built for MRI scanner. I am dealing with PET images. Probably it is the reason why dcm2niix doesn't recognize the scanner. 
Hopefully the author of dcm2niix has some idea how to deal with this issue.

**Comment by neurolabusc** [comment]
I am the creator and primary author for this community project. The software does attempt to extract meta data for [Positron Emission Tomography](https://github.com/rordenlab/dcm2niix/tree/master/BIDS#modality-positron-emission-tomography) as described by [BEP009](https://bids-specification.readthedocs.io/en/v1.2.1/06-extensions.html) as well as other modalities. 

You can always run dcm2niix in logorrheic mode (`-v 2`) to see what tags are in your images (this is very verbose, so you might want to apply this to a single file). This may help reveal how what tampering has occurred to your images.

I can give you three ideas of how to deal with this issue:
 1. Check the provenance of your images and apply dcm2niix to images prior to having Type 1 tags altered.
 2. Use an [alternative](https://github.com/rordenlab/dcm2niix#alternatives) tool to convert your images.
 3. Make a fork of dcm2niix, modify the code so it does not generate these warnings.

**Comment by neurolabusc** [comment]
Based on [this article](https://www.healthimaging.com/topics/molecular-imaging/cti-siemens-restructure-their-cps-innovations-joint-venture) I wonder if `CPS` can be used as an alias for `Siemens`. Would it be possible for you to send me an example datasets (not just a single slice). The best way to share this would be compressing all the images as a .zip archive and sharing a link (via Google Drive, DropBox, etc) to my personal email address (shown in my avatar). This would allow me to ensure that your images follow Siemens conventions.

**Comment by neurolabusc** [comment]
Thank you for the sample images. I have added a commit to the `development` branch that identifies `CPS` as an alias for `Siemens`. The one bizarre (but legal) feature of your sample dataset is that the [Instance Number (0020,0013)](https://dicom.innolitics.com/ciods/mr-image/sop-common/00200013) is indexed from 0 not 1. I have never seen this before from any manufacturer. The BIDS JSON file [will report many PET-specific attributes](https://github.com/rordenlab/dcm2niix/tree/master/BIDS#modality-positron-emission-tomography).

Please test this development version `v1.0.20220123` on your dataset and report any anomalies. If you use Windows, you can get a pre-compiled copy of the development executable by clicking on the [AppVeyor Artifacts button](https://ci.appveyor.com/project/neurolabusc/dcm2niix). For UNIX (Linux, MacOS) you can build this version yourself:

```
git clone --branch development https://github.com/rordenlab/dcm2niix.git
cd dcm2niix/console
g++ -O1 -g -fsanitize=address -fno-omit-frame-pointer  -I.  main_console.cpp nii_foreign.cpp nii_dicom.cpp jpg_0XC3.cpp ujpeg.cpp nifti1_io_core.cpp nii_ortho.cpp nii_dicom_batch.cpp  -o dcm2niix -DmyDisableOpenJPEG
./dcm2niix ....
```

If this resolves your problems, please close this issue.
