### ISSUE TITLE
CPS/Siemens HRRT Volume ordering

### ISSUE THREAD

**Issue by neurolabusc** [rordenlab/dcm2niix#577]
The order of instance numbers for some HRRT sequences created by (0008,0070) CPS model (0008,1090) HRRT with software version (0018,1020) 06.00 is unclear. Unfortunately, there is no provided [Temporal Position Identifier](http://dicomlookup.com/lookup.asp?sw=Tnumber&q=(0020,0100)), though Content Time (0008,0033) might provide a surrogate. 

The latest commit to the development branch attempts to record this variability in the BIDS JSON header, listing the Frame Duration (0018,1242), FrameReference Time (0054,1300) and  Content Time (0008,0033). The volumes are stored to disk as indicated by the instance number (0020,0013). Perhaps the [PET2BIDS](https://github.com/openneuropet/PET2BIDS) developers (@CPernet, @bendhouseart, @mnoergaard, @GGonEsc, @agt24) want to suggest the proper way to segment and order these data. (provided by @JuenGuo).

```
	"FrameDuration": [
		15,
		60,
		15,
		300,
		15,
		60,
		15,
		29,
		15,
		60,
		300,
		600,
		600,
		600,
		30,
		15,
		30,
		60,
		600,
		30,
		15,
		150,
		15,
		150,
		28.833,
		300,
		30	],
	"FrameReferenceTime": [
		121,
		391,
		91,
		1531,
		106,
		571,
		46,
		362,
		136,
		451,
		1231,
		3631,
		2431,
		3031,
		211,
		76,
		151,
		511,
		1831,
		181,
		61,
		781,
		31,
		631,
		271,
		931,
		241	],
	"ContentTimeHHMMSS": [
		090201.00,
		090631.00,
		090131.00,
		092531.00,
		090146.00,
		090931.00,
		090046.00,
		090602.00,
		090216.00,
		090731.00,
		092031.00,
		100031.00,
		094031.00,
		095031.00,
		090331.00,
		090116.00,
		090231.00,
		090831.00,
		093031.00,
		090301.00,
		090101.00,
		091301.00,
		090031.00,
		091031.00,
		090431.00,
		091531.00,
		090401.00	],
```

**Comment by neurolabusc** [comment]
The latest commit to the development branch will reorder volumes based on [FrameReference Time (0054,1300)](https://dicom.innolitics.com/ciods/pet-image/pet-image/00541300) if the [modality (0008,0060)](https://dicom.innolitics.com/ciods/cr-image/general-series/00080060) is PT. While frame reference time seems the obvious way to order time series, the [instance number](https://dicom.innolitics.com/ciods/mr-image/general-image/00200013) suggest a different ordering. It would be great to have insight from the manufacturer regarding the rationale for the instance numbers. Perhaps this just reflects the temporal order that volumes were received from a parallel reconstructor. However, I would really like to have some insight from the manufacturer regarding their rationale. I wonder if there is some deeper meaning to the instance numbers that we are not encoding.

```
	"FrameDuration": [
		15,
		15,
		15,
		15,
		15,
		15,
		15,
		15,
		30,
		30,
		30,
		30,
		28.833,
		29,
		60,
		60,
		60,
		60,
		150,
		150,
		300,
		300,
		300,
		600,
		600,
		600,
		600	],
	"FrameReferenceTime": [
		31,
		46,
		61,
		76,
		91,
		106,
		121,
		136,
		151,
		181,
		211,
		241,
		271,
		362,
		391,
		451,
		511,
		571,
		631,
		781,
		931,
		1231,
		1531,
		1831,
		2431,
		3031,
		3631	],
```

**Comment by bendhouseart** [comment]
I'm not 100% sure, I (we) may have been mixing this up w/ [issue 521 ](https://github.com/rordenlab/dcm2niix/issues/521). That ended up being a very specific issue w/ dicoms if memory serves. Since then though I have been doing my own cumulative sum of the frame durations to calculate my FrameReferenceTime as it has seemed to me to be the most reliable method.

If you find a way to get in touch with manufacturers about this I would love to find out what you learn.

I agree with @CPernet that the second example (and current commit) of using the FrameReferenceTime is correct. It makes the most sense in the PET context. I still think I will calculate the cumlative sum and raise a warning if it differs from FrameReferenceTime, it might help to track down suspects/DOI (Dicoms of interest)

**Comment by neurolabusc** [comment]
I am closing this issue based on the comments from a Siemens engineer:
 
```
For your question regarding the use of Instance Number, I think we can rely on the DICOM Definition, it’s a number that identifies the image, it does not have any technical definition.  There are DICOM attributes which capture temporal and spatial information.
```
Future releases of dcm2niix will use `FrameReferenceTime` to order all PET volumes. This incurs a small performance penalty, but ensures consistent volume order.

Users of these systems should be aware that many DICOM tools assume that the instance number is the canonical order.
