### ISSUE TITLE
Possible AcquisitionTime to filename output w/ `-f %t` option bug

### ISSUE THREAD

**Issue by bendhouseart** [rordenlab/dcm2niix#581]
**Describe the bug**

The acquisition time does not match the time recorded in the filename when the option `-f %t` is used. Is this a bug or is the time displayed in dcm2niix output files when using the `%t` option pulled from somewhere else than the AcquisitionTime in the dicom header? Documentation on NITRC has led me to believe the time portion of %t should acquisition time be formatted in HHMMSS, but this is not the observed case.

```
# acq time taken from dicom header
acquisition_time = "170934.102500"
# acq date taken from dicom header
acquisition_date = "20211206"
# actual datetime portion of output from dcm2niix output
dcm2niix_output = "20211206163940"
```

Let me know if this is a bug between the keyboard and the user or w/ dcm2niix.

Thank you.

**To reproduce**

1. Collect AcquisitionDate and AcquisitionTime from the first dicom in a series of dicoms
2. run dcm2niix on that set of dicoms with the included format tag `-f %t`

**Expected behavior**

```
# acq time taken from dicom header
acquisition_time = "170934.102500"
# acq date taken from dicom header
acquisition_date = "20211206"
# Expected datetime portion of output from dcm2niix output
dcm2niix_output = "20211206170934"
```

**Version**

Chris Rorden's dcm2niiX version v1.0.20211006  Clang11.0.0 x86-64 (64-bit MacOS)
v1.0.20211006

**Troubleshooting**

```
git clone --branch development https://github.com/rordenlab/dcm2niix.git
cd dcm2niix/console
g++  -I.  main_console.cpp nii_foreign.cpp nii_dicom.cpp jpg_0XC3.cpp ujpeg.cpp nifti1_io_core.cpp nii_ortho.cpp nii_dicom_batch.cpp  -o dcm2niix -DmyDisableOpenJPEG
./dcm2niix ....
```

Output below from latest version obtained and compiled w/ commands listed above:

```MH02144183MACLT:console galassiae$ ./dcm2niix -w 1 -z y %p%i%t_%s -o . ~/Data/mydicoms/sanitized_categorized/fMRI_rest_bc_4tr/
Chris Rorden's dcm2niiX version v1.0.20220123  Clang12.0.0 x86-64 (64-bit MacOS)
Found 4 DICOM file(s)
Convert 4 DICOM as ./fMRI_rest_bc_4tr_fMRI_rest_bc_4tr_20211206163940_20 (64x64x32x4)
Compress: "/usr/local/bin/pigz" -b 960 -n -f -6 "./fMRI_rest_bc_4tr_fMRI_rest_bc_4tr_20211206163940_20.nii"
Conversion required 0.116742 seconds (0.021443 for core code).
MH02144183MACLT:console galassiae$ for file in ~/Data/mydicoms/sanitized_categorized/fMRI_rest_bc_4tr/*; do  dcmdump $file | grep AcquisitionTime; done
(0008,0032) TM [170932.102500]                          #  14, 1 AcquisitionTime
(0008,0032) TM [170934.102500]                          #  14, 1 AcquisitionTime
(0008,0032) TM [170936.102500]                          #  14, 1 AcquisitionTime
(0008,0032) TM [170938.102500]                          #  14, 1 AcquisitionTime
```

**Comment by neurolabusc** [comment]
This is the defined  [filenaming behavior](https://github.com/rordenlab/dcm2niix/blob/master/FILENAMING.md). The filename's `%t` refers to the time of study (from 0008,0020 and 0008,0030), not the acquisition time (0008,0032). This groups all series from a study together. For example, I often segment datasets so each study is saved in a separate folder:

```
dcm2niix -f %t/%s_%p.dcm /path/to/DICOMs
```
As an aside, I think there are a lot of manufacturer and sequence specific difference in the interpretation of a lot of the timing tags (0008,0032; 0008,0033; 0018,1060). Searching the previous dcm2niix issues will review some of these.

**Comment by bendhouseart** [comment]
Thanks!!!
