### ISSUE TITLE
Possible issue with output dimensions

### ISSUE THREAD

**Issue by naterichman** [rordenlab/dcm2niix#583]
Hello,

I'm not totally clear this is a bug, just behavior I didn't expect, which could be on me as well!

**Describe the bug**

I have an input dicom with 150 slices of 192x192 and the output nifti has the following dim field:

```
dim             : [  3 150 192 192   1   1   1   1]
```

**To reproduce**

[Here](https://drive.google.com/file/d/1ows0wTW6QYgWXu0Kk19yr6xXsExbtrux/view?usp=sharing) is the input and output data

And the command I ran using `dcm2niix v1.0.20211006` was

```bash
dcm2niix -ba y -l n -b y -z y -6 -x n -t n -i n -m 2 y -f %f -o /root/out -p y -s n -e n -v n /root/work/T1w
```

**Expected behavior**

I expected the output dimension to be
```
dim             : [  3 192 192 150 1   1   1   1]
```

**Output log**

Here is the last bit of the output log with `-v 1` (I assume the whole 150 slice output isn't needed but I can post if necessary):

```bash
DICOM file: /tmp/dicom/1.3.46.670589.11.42365.5.0.5176.2018102307240085135.MR.dcm
 patient position (0020,0032)   -33.9076        -132.45 152.505
 orient (0020,0037)     0.0180307       0.999837        0.00108923      0.0034243       0.00102764      -0.999994
 acq 5 img 98 ser 501 dim 192x192x1x1 mm 1.19792x1.19792x1.2 offset 9404 loc 150 valid 1 ph 0 mag 1 nDTI 1 3d 1 bits 16 littleEndian 1 echo 1 coilCRC 1552108064 TE 5.001 TR 20
   Patient Position 0020,0032 (#,@,X,Y,Z)       1       2860    70.4749 -134.333        152.861
DICOM file: /tmp/dicom/1.3.46.670589.11.42365.5.0.5176.2018102307240303198.MR.dcm
 patient position (0020,0032)   70.4749 -134.333        152.861
 orient (0020,0037)     0.0180307       0.999837        0.00108923      0.0034243       0.00102764      -0.999994
 acq 5 img 11 ser 501 dim 192x192x1x1 mm 1.19792x1.19792x1.2 offset 9404 loc 150 valid 1 ph 0 mag 1 nDTI 1 3d 1 bits 16 littleEndian 1 echo 1 coilCRC 1552108064 TE 5.001 TR 20
Converting /tmp/dicom/1.3.46.670589.11.42365.5.0.5176.2018102307240285188.MR.dcm
Philips Scaling Values RS:RI:SS = 0.886691:0:0.0103528 (see PMC3998685)
 R = raw value, P = precise value, D = displayed value
 RS = rescale slope, RI = rescale intercept, SS = scale slope
 D = R * RS + RI; P = D/(RS * SS)
 D scl_slope:scl_inter = 0.886691:0
 P scl_slope:scl_inter = 96.5924:0
 Using P values ('-p n ' for D values)
Convert 150 DICOM as ./dicomc (192x192x150x1)
Compress: "/usr/bin/pigz" -b 960 -n -f -6 "./dicomc.nii"
Conversion required 0.252411 seconds (0.123082 for core code).
```

**Version**

Please report the complete version string:

 `dcm2niiX version v1.0.20211220  GCC7.5.0 x86-64 (64-bit Linux)`

**Troubleshooting**

Same results on multiple versions including most recent master and development.

My questions are:
 
* is this expected?  I'm trying to convert back from nifti to dicom and I find that almost all nifti's come out with the slice dimension being at index 3 with Row/Col being index 1 and 2.  
* If this is expected, what is it that is different about this dicom that causes this ordering of the dimensions.

Thanks for any help and please let me know if I can share any more information.

**Comment by neurolabusc** [comment]
Default behavior is to losslessly rotate 3D acquisitions to match NIfTI identity matrix. To disable use the '-x n' option

**Comment by naterichman** [comment]
Okay thank you, is there anyway to determine that this rotation was done from the sidecar or nifti header?

**Comment by neurolabusc** [comment]
Compare json field ImageOrientationPatientDICOM to the sform

**Comment by naterichman** [comment]
Appreciate the help, thank you!

**Comment by neurolabusc** [comment]
Also you know the image was not reoriented if the field. "MRAcquisitionType": "3D" is not present. Be aware the rows and columns can be flipped to match DICOM vs NIfTI defaults. The -y option is relevant
