### ISSUE TITLE
RepetitionTime and TaskName

### ISSUE THREAD

**Issue by MareikeBT** [rordenlab/dcm2niix#586]
Hi, 

I have an issue with an fMRI data set in BIDS format. (I have this same issue with two different data sets).
When running the BIDS validator (https://jasmainak.github.io/bids-validator/)
I get a errors about RepetitionTime and TaskName
[You have to define 'RepetitionTime' for this file.](https://jasmainak.github.io/bids-validator/#)
sub-01_ses-01_task-finger_acq-highfreq_bold.nii
637157.152 KB |
Location:

fMRI_prep/sub-01/ses-01/func/sub-01_ses-01_task-finger_acq-highfreq_bold.nii
Reason:

You have to define 'RepetitionTime' for this file. It can be included one of the following locations: /bold.json, /task-finger_bold.json, /task-finger_acq-highfreq_bold.json, /sub-01/sub-01_bold.json, /sub-01/sub-01_task-finger_bold.json, /sub-01/sub-01_task-finger_acq-highfreq_bold.json, /sub-01/ses-01/sub-01_ses-01_bold.json, /sub-01/ses-01/sub-01_ses-01_task-finger_bold.json, /sub-01/ses-01/sub-01_ses-01_task-finger_acq-highfreq_bold.json, /sub-01/ses-01/func/sub-01_ses-01_task-finger_acq-highfreq_bold.json

[You have to define 'TaskName' for this file.](https://jasmainak.github.io/bids-validator/#). 
sub-01_ses-01_task-finger_acq-highfreq_bold.nii
637157.152 KB |
Location:

fMRI_prep/sub-01/ses-01/func/sub-01_ses-01_task-finger_acq-highfreq_bold.nii
Reason:

You have to define 'TaskName' for this file. It can be included one of the following locations: /bold.json, /task-finger_bold.json, /task-finger_acq-highfreq_bold.json, /sub-01/sub-01_bold.json, /sub-01/sub-01_task-finger_bold.json, /sub-01/sub-01_task-finger_acq-highfreq_bold.json, /sub-01/ses-01/sub-01_ses-01_bold.json, /sub-01/ses-01/sub-01_ses-01_task-finger_bold.json, /sub-01/ses-01/sub-01_ses-01_task-finger_acq-highfreq_bold.json, /sub-01/ses-01/func/sub-01_ses-01_task-finger_acq-highfreq_bold.json

[JSON file is not formatted according the schema.4 files](https://jasmainak.github.io/bids-validator/#)
sub-01_ses-01_task-finger_acq-highfreq_bold.json
1.969 KB | application/json
Location:

fMRI_prep/sub-01/ses-01/func/sub-01_ses-01_task-finger_acq-highfreq_bold.json
Reason:

JSON file is not formatted according the schema.
Evidence:

should have required property 'TaskName'
task-MPRAGE_bold.json
0.022 KB | application/json
Location:

fMRI_prep/task-MPRAGE_bold.json
Reason:

JSON file is not formatted according the schema.
Evidence:

should have required property 'RepetitionTime'
task-T1_bold.json
0.018 KB | application/json
Location:

fMRI_prep/task-T1_bold.json
Reason:

JSON file is not formatted according the schema.
Evidence:

should have required property 'RepetitionTime'
task-finger_bold.json
0.022 KB | application/json
Location:

fMRI_prep/task-finger_bold.json
Reason:

JSON file is not formatted according the schema.
Evidence:

should have required property 'RepetitionTime'

However my .json file has the RepetitionTime included. 
Please see the file here:

sub-01_ses-01_task-finger_acq-highfreq_bold.json

{
	"Modality": "MR",
	"MagneticFieldStrength": 7,
	"Manufacturer": "Siemens",
	"ManufacturersModelName": "Terra",
	"InstitutionName": "Erwin_L._Hahn_Institute",
	"InstitutionalDepartmentName": "Department",
	"InstitutionAddress": "Kokereiallee_7_Essen_NRW_DE_45141",
	"DeviceSerialNumber": "79129",
	"StationName": "AWP79129",
	"BodyPartExamined": "BRAIN",
	"PatientPosition": "HFS",
	"ProcedureStepDescription": "Shah_Seq_Test",
	"SoftwareVersions": "syngo_MR_E12",
	"MRAcquisitionType": "2D",
	"SeriesDescription": "func_bold_dir-PA_run-4_ses-1_acq-hcp",
	"ProtocolName": "func_bold_dir-PA_run-4_ses-1_acq-hcp",
	"ScanningSequence": "EP",
	"SequenceVariant": "SK_SS",
	"ScanOptions": "PFP_FS_EXT",
	"SequenceName": "epfid2d1_130",
	"ImageType": ["ORIGINAL", "PRIMARY", "M", "MB", "ND", "MOSAIC"],
	"SeriesNumber": 12,
	"AcquisitionTime": "16:15:29.795000",
	"AcquisitionNumber": 1,
	"ImageComments": "Unaliased_MB5_PE4_SENSE1",
	"SliceThickness": 1.6,
	"SpacingBetweenSlices": 1.6,
	"SAR": 0.104201,
	"EchoTime": 0.0222,
	"RepetitionTime": 1.0,
	"FlipAngle": 52,
	"PartialFourier": 0.875,
	"BaseResolution": 130,
	"ShimSetting": [
		473,
		1472,
		-253,
		-7,
		-104,
		-27,
		37,
		-25	],
	"TxRefAmp": 200,
	"PhaseResolution": 1,
	"ReceiveCoilName": "1Tx32Rx_Head",
	"PulseSequenceDetails": "%CustomerSeq%_cmrr_mbep2d_bold",
	"ConsistencyInfo": "N4_VE12U_LATEST_20181126",
	"MultibandAccelerationFactor": 5,
	"PercentPhaseFOV": 100,
	"EchoTrainLength": 57,
	"PhaseEncodingSteps": 114,
	"AcquisitionMatrixPE": 130,
	"ReconMatrixPE": 130,
	"BandwidthPerPixelPhaseEncode": 24.038,
	"ParallelReductionFactorInPlane": 2,
	"EffectiveEchoSpacing": 0.000320006,
	"DerivedVendorReportedEchoSpacing": 0.000640012,
	"TotalReadoutTime": 0.0412808,
	"PixelBandwidth": 1925,
	"DwellTime": 2e-06,
	"PhaseEncodingDirection": "j",
	"SliceTiming": [
		0,
		0.5275,
		0.0575,
		0.5875,
		0.1175,
		0.6475,
		0.175,
		0.705,
		0.235,
		0.765,
		0.2925,
		0.8225,
		0.3525,
		0.8825,
		0.41,
		0.94,
		0.47,
		0,
		0.5275,
		0.0575,
		0.5875,
		0.1175,
		0.6475,
		0.175,
		0.705,
		0.235,
		0.765,
		0.2925,
		0.8225,
		0.3525,
		0.8825,
		0.41,
		0.94,
		0.47,
		0,
		0.5275,
		0.0575,
		0.5875,
		0.1175,
		0.6475,
		0.175,
		0.705,
		0.235,
		0.765,
		0.2925,
		0.8225,
		0.3525,
		0.8825,
		0.41,
		0.94,
		0.47,
		0,
		0.5275,
		0.0575,
		0.5875,
		0.1175,
		0.6475,
		0.175,
		0.705,
		0.235,
		0.765,
		0.2925,
		0.8225,
		0.3525,
		0.8825,
		0.41,
		0.94,
		0.47,
		0,
		0.5275,
		0.0575,
		0.5875,
		0.1175,
		0.6475,
		0.175,
		0.705,
		0.235,
		0.765,
		0.2925,
		0.8225,
		0.3525,
		0.8825,
		0.41,
		0.94,
		0.47	],
	"ImageOrientationPatientDICOM": [
		1,
		0,
		0,
		0,
		0.974761,
		-0.22325	],
	"InPlanePhaseEncodingDirectionDICOM": "COL",
	"ConversionSoftware": "dcm2niix",
	"ConversionSoftwareVersion": "v1.0.20180403 GCC5.4.0"
}

What could be wrong with the RepetitionTime and how/where do I need to define the TaskName field (if it is not created automatically)? 

Thank you very much!
Mareike

**Comment by neurolabusc** [comment]
1. Since the BIDS file contains the tag `RepetitionTime` this issue is not with dcm2niix. Rather, either the [bids-validator](https://github.com/bids-standard/bids-validator) or your naming structure is faulty. You should seek help from the bids-validator developers or [neurostars](https://neurostars.org).
2. I notice you are using a development release of Siemens software (`E12`) and therefore you will want to be extra vigilant in ensuring your data integrity.
3. Is there a reason you are using a four year old version of dcm2niix created before E12 existed rather than the [current stable release](https://github.com/rordenlab/dcm2niix/releases)? Both the DICOM and BIDS standards are evolving rapidly.
