### ISSUE TITLE
DCM's Improperly Read, believes "Missing"

### ISSUE THREAD

**Issue by nseider** [rordenlab/dcm2niix#587]
I'm trying to convert ABCD DICOM's to nifti for a test subject. There are 81 dcm in the folder diffusion AP, and only 11/81 files are found so the Nifti is improperly built.  Using Quick Dicom Batch Editor to view the files, all 81 slices can be opened and viewed. Following other errors I made sure I was using the latest version of dcm2niix and built with cmake.  
Note that the full DWI sequence is converted properly, and the PA scan also has errors where only 8/81 dcm files are found. 

Command: 
~/dcm2niix/build/bin/dcm2niix -o ~/AP ~/sub-NDARINVBL9KRALR/ap_dcm

Output: 
Chris Rorden's dcm2niiX version v1.0.20211220  GCC7.5.0 x86-64 (64-bit Linux)
Found 11 DICOM file(s)
Warning: Interslice distance varies in this volume (incompatible with NIfTI format).
Warning: Missing images? Expected 11 images, but instance number (0020,0013) ranges from 4 to 81
Warning: Weird CSA 'ProtocolSliceNumber' (System/Miscellaneous/ImageNumbering reversed): VALIDATE SLICETIMING AND BVECS
Convert 11 DICOM as AP/DTI_sub-02 (140x140x11x1)
Conversion required 0.136364 seconds (0.136319 for core code)

Version of dcm2niix:  v1.0.20211220  GCC7.5.0 x86-64
Installed using cmake 2/28/2022

Any suggestions to troubleshoot this would be greatly appreciated!

**Comment by neurolabusc** [comment]
This seems to be an issue with the source data, not dcm2niix.

It looks like there are missing files, I suspect not all the images were copied. The [ABCD Siemens DTI protocol has ](https://abcdstudy.org/images/Protocol_Imaging_Sequences.pdf) has 81 slices per volume with 96 b-weighted volumes (not sure about number of b=0 volumes). You can always run `dcm2niix -r y /path/to/dicoms` to rename the DICOMs to separate folders and work out which series got corrupted.

As an aside, Siemens users should never acquire data with reversed image numbering. For details and a link to the Siemens white paper, see [here](https://crnl.readthedocs.io/stc/index.html). While I believe dcm2niix handles these correctly, I know that not all tools do.

**Comment by nseider** [comment]
Thank you for the quick response.  I dug into the report from the downloader.  In case others have a similar issue, we appeared to have intermittent internet and though all the files were "successfully downloaded" and 81/81 dcms appeared with an ls -v, the majority where corrupted/empty locally.

**Comment by neurolabusc** [comment]
Don Halger from the ABCD team provided the following advice:


> It looks like there are missing DICOM files for this series, which sometimes happens because of data transfer issues.
>  
>  
> If unprocessed raw imaging data is needed, DICOM files are also made publicly available via a Fast Track mechanism. These DICOM files are released on NDA (https://data-archive.nimh.nih.gov/abcd) on a continual basis within approximately one month of data collection using the ABCD fast-track image sharing scripts (RRID: SCR_016021). DICOM files are arranged in BIDS-compliant directory trees and packaged in individual archive files (tgz) for each series. Metadata are included in the form of json-format text files, and for task-fMRI series, also included are the files containing stimulus and behavioral response timing information exported from the stimulus program (E-prime). A copy of the metadata is uploaded to NDA’s image (version 03 – image03) database to link information to non-imaging-based assessments for the same participants. **Raw DICOM Fast Track data have not undergone quality control or curation.** The up-to-date index of Fast Track shared DICOM files can be downloaded in a separate image03 instrument.
>  
> The fastrackqc instrument has variables indicating whether data are usable or not. There is an option on NDA to download all "active" data or only the "recommended" data, based on the variables in fasttrackqc. In some cases, data are replaced on Fast Track; for example, if we are able to recover the missing files for a particular series. In those cases, the original series will still be available forever but will be marked as "recalled" and not usable in the fastrackqc.
>  
> If ABCD users have problems or questions about accessing the ABCD data available on NDA, they can send questions to the NDA Help Desk ndahelp@mail.nih.gov.
