### ISSUE TITLE
Pulse sequence details on GE

### ISSUE THREAD

**Issue by mharms** [rordenlab/dcm2niix#588]
On GE systems, it would seemingly be useful to include (0019,109c) as part of some json field. 
e.g.,

> (0019,109c) LO [research/ABCD/epi_pepolar]              #  26, 1 Unknown Tag & Data

or

> (0019,109c) LO [research/ABCD/muxepi]                   #  20, 1 Unknown Tag & Data
	
I see that the DICOMs from the ABCD/muxepi sequence currently generate the following json fields:

> "PulseSequenceName": "epi",
> "InternalPulseSequenceName": "EPI",

but those aren't particularly informative in this case.

I suspect that "InternalPulseSequenceName" is coming from (0019,109e), but it would be helpful to get (0019,109c) in the json output as well, as it is appreciably more informative as to what actually was used.  Perhaps it could be stashed in the `PulseSequenceDetails` field, where `dcm2niix` currently stashes some details about Siemens pulse sequences?

**Comment by neurolabusc** [comment]
@mharms please try out the development branch which should now insert 0019,109c into the JSON field `PulseSequenceName`. Please check the output, as I do not have GE files with customer sequences.

**Comment by mr-jaemin** [comment]
Great suggestion! Agreed `Pulse Sequence Name`(0019,109c) would be useful as well as `Internal Pulse Sequence Name` (0019,109e). Thank you, @neurolabusc and @mharms!

Just FYI, previously implementation was related to slice timing calculation (I will comment in your another thread) , categorizing EPI family into three major "epi" (fMRI), "epiRT" (Brainwave fMRI), "epi2" (Diffusion), not only for GE product PSD but also custom PSD. These three PSD behave slightly differently about how information is saved in DICOM and HyperBand (MB) behavior. But, again agreed that (0019,109c) would be useful in general. It would be sufficient to store internally `d.epiVersionGE` rather than explicitly writing this into JSON.

**Comment by mr-jaemin** [comment]
@mharms Related to `epi_pepolar`, I wanted to share this fix:
- kludge for incorrect spatial coding of [GE ABCD epipolar](https://github.com/rordenlab/dcm2niix/issues/532) sequence.

**Comment by mharms** [comment]
There is already a json field called `PulseSequenceName` and it's just `epi`.  Not sure where that particular entry is coming from currently.  It seems like (0019,109c) would fit in well with the existing `PulseSequenceDetails` field.

**Comment by mr-jaemin** [comment]
GE DICOM report two tags related to Pulse Sequence Name described in [GE MRI DICOM Conformance Statement](https://www.gehealthcare.com/products/interoperability/dicom/magnetic-resonance-imaging-dicom-conformance-statements)

(0019,109E) `Internal Pulse Sequence Name`
(0019,109C) `Pulse Sequence Name`

The `Internal Pulse Sequence Name` is defined/come from PSD source code.
`psdname("EPI");` for fMRI
`psdname("EPI2");` for Diffusion
Typically, protype (including ABCD) or external developer doesn't update this string.

The `Pulse Sequence Name` is come from PSD name specified on console UI. The name reflects PSD binary name or symbolic link specified in UI. Path would be included if specified in UI (research/ABCD/muxepi2).

Previously reported `PulseSequenceName` was come from my efforts to detect supported GE fMRI and to exclude unsupported EPI (#443) for slice timing based on these two names as well as ScanOptions

From [BIDs definition](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html), I see three relevant fields:
`PulseSequenceType`
`PulseSequenceDetails`
`SequenceName` corresponds to (0018,0024). As per GE MR DCS, this tag is Unused.

As @mharms suggested, `Pulse Sequence Name` may fit in well with `PulseSequenceDetails`. 

Please share your thoughts @mharms @neurolabusc 

![Screen Shot 2022-03-14 at 3 11 39 PM](https://user-images.githubusercontent.com/72111485/158244183-a16ea5fc-1e1b-459e-9da5-b4a51988c8e0.png)

**Comment by neurolabusc** [comment]
@mr-jaemin the current development release will include `0019,109C` in the JSON file. It does read `0019,109E` to determine image type, but does not store this in the JSON. I think we are too close to the spring 2022 release to change this behavior, but I will keep it in mind for a future update.

**Comment by mr-jaemin** [comment]
@neurolabusc the current release (including stable) already stores `0019,109E` in the JSON file as shown below (also above):
> "InternalPulseSequenceName": "EPI" 

So, the current development release will include both tags in the JSON file:
>`0019,109C` as `PulseSequenceName`
>`0019,109E` as `InternalPulseSequenceName`

I am good with this plan for the spring 2022 release.

We could consider to map these into the BIDS fields for a future update (Let me know anytime) or leave it up to next stage (i.e  BIDS wrapper/converter based on dcm2niix).

**Comment by neurolabusc** [comment]
Closing this issue, it does not make the cut for the Spring 2022 release.
