### ISSUE TITLE
lost slice gap information after conversion from multi-slice DICOM to nifti

### ISSUE THREAD

**Issue by ghisvail** [rordenlab/dcm2niix#59]
Hi Chris,

More of a question than an issue here.

I have used your tool to convert a stack of DICOM files for a short-axis cardiac scan, consisting of consecutive 2D+t slices with fixed slice gap, to the nifti format. So far, the tool outputs one nifti file per slice (2D+t), and the slice gap information appears to be lost. I am wondering where and how this information could and should be stored.

From a quick look at the nifti format specifications, it cannot find a field dedicated to this information unless I misread it. Or perhaps it can be calculated from other fields in the nifti header somehow. Do you have any clue regarding how people usually handles fixed slice gaps with nifti?

In my case, people would prefer to have these data to be stored as one fat 3D+t nifti file for convenience (easier to deserialize), but perhaps it is more sensible to keep them as separate 2D+t. In either cases, I reckon the slice gap information needs to stored somewhere to allow users to stitch the data the way they desire prior to performing volumetric and/or temporal analysis.

Thanks for your help,

**Comment by neurolabusc** [comment]
Hello-

In general, if your 2D images share the same series number they will be stacked as a single 3D volume (or if the compile time parameter "mySegmentByAcq" is set, the images must share the same series and acquisition number). The NIfTI format does only stores the distance between slice centers (the sum of slice thickness and slice gap). You can always look at the function "isSameSet()" to see the comprehensive set of criteria used to determine if 2D slices should be stacked: series number, acquisition number, date/time, echo time, echo number, coil number, protocol name, slice orientation.

I am not sure why your slices have not been stacked, but either using my software with the verbose ("-v y") conversion or using Osirix to inspect your images should reveal why they are not stacked. 

Note that in the case where my software saves the images as separate 2D slices, you can still infer the inter-slice distance: each slice stores its spatial coordinates and angulation as both a spatial transformation matrix (the s_form) and as a quaternion (q_form). So you can always compute the spatial position between slices (e.g. if they share the same angulation, just use Pythagorean theorem to compute the Euclidean distance between each slices' origin). So in this case, the NIfTI pixdim[3] gives you the slice thickness, pythagorean theorem provides the inter-slice difference, and the difference between these two values is your gap.

**Comment by ghisvail** [comment]
Thanks for the quick reply, lots of information here. Just as a recap:

What you are saying in your first paragraph is that assuming the data from the DICOM stack were only differing by the slice gap, your software would have stacked them right? Based on the list of criteria you gave me, I have a feeling that the data were given a distinctive name and acquisition number. I will check your list and verify which criterion is not fulfilled.

Also, assuming the nifti were stacked to 3D+t, then the inter-slice distance would be lost. But not for multiple 2D+t where inter-slice distance can be calculated via basic geometry. Could you confirm?

**Comment by neurolabusc** [comment]
If the slices are stacked as a 3D volume the resulting NIfTI image does not store the slice thickness or the slice gap, rather it stores the sum of those (the distance between voxel centers). If you want, you can email me the link to a DropBox archive of your images and I can provide more detail.

**Comment by ghisvail** [comment]
Thanks to your pieces of explanation, I think I got the limitations behind the single 3D+t versus multiple 2D+t files.

Do you happen to know how the stitching of these data into a 3D+t volume is usually done, i.e. how is the slice gap treated when processing this sort of data?

**Comment by neurolabusc** [comment]
All the image processing tools I use ignore slice gap, effectively assuming that voxels are contiguous in each of the 3 dimensions. For brain imaging, the gap is usually around 20% of slice thickness to reduce interference (sequential slices) or spin history (interleaved) effects. The slice selection is not actually perfectly discrete, so there is always some roll off. 

I would have expected my software should stack your slices for you. When you say 2D+t do you mean that each slice has multiple time points, and if so are all the slices acquired in the same acquisition (s1t1, s2t1, s1t2, s2t2...) or are they scanned one after the other (s1t1, s1t2, s1t3..., s2t1, s2t2, s2t3....). If it is the latter and you are using a GE scanner, you should make sure you are using the latest build of my software (1-Nov-2016) as I just added support for that feature.

**Comment by ghisvail** [comment]
> When you say 2D+t do you mean that each slice has multiple time points

Indeed, each time point corresponding to a different cardiac phase.

**Comment by neurolabusc** [comment]
Can you see if the current build (1-Nov-2016) correctly converts your images. You can try it with "-m y" and "-m n" parameters to see how forcing the software to stack across series influences the output. The NIfTI standard requires that time is the 4th dimension (with the first 3 dimensions reserved for spatial dimensions). If this works fine, lets close this issue, otherwise I would need to see a sample dataset.
