### ISSUE TITLE
Certain DWI metadata no longer appearing in version v20211006

### ISSUE THREAD

**Issue by dlevitas** [rordenlab/dcm2niix#592]
I've shared some DWI DICOMS via Google Drive, where important metadata (e.g. `PhaseEncodingDirection`, `DwellTime`) isn't contained in the metadata JSON file. This occurs using dcm2niix v20211006. However, using an older version of dcm2niix (v20201102) produces this metadata. I'm unsure whether or not this is a bug that was introduced, but I was wondering what might be causing this discrepancy?

cc'ing @giulia-berto, who alerted me to this.

**Comment by neurolabusc** [comment]
Unable to replicate. No version of dcm2niix will be able to extract these parameters from a pre-XA Siemens scanner if the [CSA header is removed](https://github.com/rordenlab/dcm2niix/tree/master/Siemens#csa-header). The images you sent me were acquired on a Siemens Trio Tim VB17 and have no CSA header. It looks like an extremely agressive anonymization step removed all private tags. Be aware that for these systems the CSA header also contains the b-vectors. I suggest you trace the provenance of these images and convert a copy before the crucial private tags were removed. Further, these images were touched by dcm4che-2.0 PACS, which can [cripple DICOMs](https://github.com/neurolabusc/dcm_qa_agfa). The images I was sent are not of archival quality.

It looks like these scans were acquired with a custom set of gradient directions, so without the CSA header you will need to know the requested gradient directions to recover the bvec/bval files (ensuring that you transfer these vectors from world space to image space coordinates).

**Comment by giulia-berto** [comment]
thank you @dlevitas and @neurolabusc for your help, it makes sense. I thought that the conversion to DICOMs was done starting from the same scans, but apparently some other steps had been performed in the middle. Thanks for the explanation, since it's an issue with the dataset and not of the dcm2niix version used, we can close this issue.
