### ISSUE TITLE
"Collage" vertical strips artifact

### ISSUE THREAD

**Issue by NinetLab-Redux** [rordenlab/dcm2niix#595]
Hello,
I'm not entirely sure this is related to dcm2niix but I see an artifact on all my nii images after convertion with dcm2niix that I do not see when I examine them directly as dicom (see images attached).
 When I visualize dicom as 3D using OsiriX I get the warning attached below. 

I'm looking for guidance about the nature of this artifact and whether is related to the conversion from dcm to nii. If it was related, how could I avoid it?

Thank you,

Fidel

![VerticalCollage2](https://user-images.githubusercontent.com/97552875/161480170-3af02ee8-be4b-4ae6-969a-66e0370b8c87.png)

![VerticalCollage_artifact](https://user-images.githubusercontent.com/97552875/161480093-18cf6050-19dd-4ff3-bfc7-6a4f75539a8f.png)
 
![Osirix3D_warning](https://user-images.githubusercontent.com/97552875/161480930-9f2b7499-4c31-42f0-8725-925d4ec0907c.png)

```

**Comment by NinetLab-Redux** [comment]
Thank you for your prompt reply. I use FSLeyes to visualize the nii files. I have also visualised the whole images without brain extraction and the same artifact is there.
What email address could I use to share a link to an example dataset only with you?
thanks,
fvr



On 4 Apr 2022, at 08:29, Chris Rorden ***@***.******@***.***>> wrote:

[CAUTION: Non-UBC Email]


@NinetLab-Redux<https://github.com/NinetLab-Redux> what software are you using to view your images? Does dcm2niix generate two images, one with the _tilt postfix? Can you share a sample dataset with me directly? Both images attached show artifacts. In the top image they are aligned with the slice plane and in the lower image they are not. While gantry tilt is common for CT scans, it is extremely unusual in MR. The NIfTI q-form is unable to store gantry tilt. Your images also show brain extraction, so they do not look like raw images. My sense is you want to check the provenance of these images and source images as acquired from the scanner.

**Comment by neurolabusc** [comment]
An ideal solution would be for you to send a link to a zip-archive of the files on Google drive to my [institution email](https://sc.edu/study/colleges_schools/artsandsciences/psychology/our_people/directory/rorden_chris.php).

**Comment by neurolabusc** [comment]
This issue has nothing to do with dcm2niix. These scans were angulated relative to the scanners world space, and therefore one will see [aliasing artifacts](https://neurostars.org/t/downsample-image/16677/7) when attempting to show them on a grid You may want to try [MRIcroGL](https://www.nitrc.org/plugins/mwiki/index.php/mricrogl:MainPage) which uses the voxels native space for 2D slices. 

A. Image appears aliased when `Display space` is `World coordinates` and `Interpolation` is `None` (nearest neighbor).

![nearest](https://user-images.githubusercontent.com/8930807/161831449-cc64342e-4853-4afe-b2ed-62eb08ddb9e0.png)

B. Setting `Interpolation` to `Linear` minimizes the aliasing 

![linear](https://user-images.githubusercontent.com/8930807/161831785-90dcf692-d7c9-454c-8a05-1c8c2c6da2dd.png)

C. Setting the `Display space` to the image's frame of reference eliminates the artifacts.

![imageSpace](https://user-images.githubusercontent.com/8930807/161831937-f0a4a7bc-bcdb-4df8-b59b-588818e5be8d.png)

As an aside, I not that dcm2niix accurately converts the series 401 phase map. However, very different phase values are used for the inferior half of the slices relative to the superior half. I would make sure that these images are correctly [unwrapped](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FUGUE/Guide). If there are problems, you may want to reach out to the Philips Clinical Scientist responsible for your instrument.
