### ISSUE TITLE
dcm2niix splits BOLD series (enhanced DICOM, Siemens Prisma XA30) into 2 series 

### ISSUE THREAD

**Issue by osamaNYUAD** [rordenlab/dcm2niix#599]
dcm2niix splits bold time series into 2 separate files, although both files belong to the same bold run. All the dcm files in the folder are the same size, and they belong to the same run, and although in this case dcm2niix finds 398 files, it outputs them into 2 separate files (containing 93 and 305 files respectively). Any suggestion how we can avoid this unwanted behavior? 

dcm2niix /Users/oa22/Desktop/dicom_from_prisma/Brain_Protocols/func-bold_task-BETS_run-01_14
Chris Rorden's dcm2niiX version v1.0.20211006  Clang12.0.5 x86-64 (64-bit MacOS)
Found 398 DICOM file(s)
Warning: Siemens XA exported as classic not enhanced DICOM (issue 236)
Convert 93 DICOM as /Users/oa22/Desktop/dicom_from_prisma/Brain_Protocols/func-bold_task-BETS_run-01_14/func-bold_task-BETS_run-01_1_0014 (80x80x44x93)
Warning: Siemens XA exported as classic not enhanced DICOM (issue 236)
Convert 305 DICOM as /Users/oa22/Desktop/dicom_from_prisma/Brain_Protocols/func-bold_task-BETS_run-01_14/func-bold_task-BETS_run-01_1_0014a (80x80x44x305)
Conversion required 13.120417 seconds (12.737073 for core code).

**Comment by neurolabusc** [comment]
I do not have access to a XA scanner. If you want detailed feedback, can you please send a link for a Dropbox/GoogleDrive DICOM archive to my institution email address. However, I do urge you to take a [careful look at issue 236](https://github.com/rordenlab/dcm2niix/issues/236). Specifically, Siemens notes that classic images are only for `Having the option to export data in interoperability format will provide room to continue developmental activities for our research partners and give the chance to more third party processing software vendors to catch on.` These images are limited relative to the enhanced export. This is an inherent limitation of the images, not dcm2niix and will be seen in [other tools](https://github.com/MRtrix3/mrtrix3/pull/2462). Moving forward, I urge you to consider enhanced data export.

**Comment by osamaNYUAD** [comment]
Hi Chris,

Thanks for your message. I read that thread you pointed out when we
upgraded to XA30 software, and that's why our DICOM data is now exported as
Enhanced Dicom without anonymization. The dcm2niix latest version works
properly at converting the data, so we are happy with it. However, for a
few subjects the BOLD time series is split into 2 separate nifti files.
Attached below in the google drive link are examples from (a) a subject
that dcm2niix splits its bold series (which we *don't* want), and (b) a
subjects which dcm2niix handles properly (i.e., it outputs a single file as
expected). Both subjects underwent an exact scan procedure (but the actual
number of timepoints might not be the same since each subject can take
different time in the scanner performing a certain task). Please let me
know your thoughts.

Thanks.

Osama
 toChris.zip
<https://drive.google.com/file/d/1SAaXTs0CuZrzhLMWWfFTBUx7oGaVkhDu/view?usp=drive_web>


*Osama Abdullah, PhD*
MRI Physicist II
Core Technology Platforms
NYU Abu Dhabi
UAE O: +971 2 628-4990
UAE C: +971 56 6793378

NYU Abu Dhabi, Saadiyat Campus
Computational Research Building (A2), 014
P.O. Box 129188
Abu Dhabi, United Arab Emirates (EST + 8 hours)

**Comment by neurolabusc** [comment]
@osamaNYUAD this is a limitation with your DICOM images, not dcm2niix. Specifically, the dataset explicitly uses to different [Series Instance UIDs (0020,000E)](http://dicomlookup.com/lookup.asp?sw=Tnumber&q=(0020,000E)), explicitly requiring that these images should not be combined as a single series. I am not sure why this was done, I suggest you work closely with your Siemens Research Collaboration Manager to rectify the situation. You could always make a fork of dcm2niix that ignores this tag, but the probability for unintended consequences would be very high, and therefore you would only want to use it on corrupted datasets.

**Comment by osamaNYUAD** [comment]
Thank you Chris for the helpful response. I'll check with Siemens and
escalate the issue. Best.


*Osama Abdullah, PhD*
MRI Physicist II
Core Technology Platforms
NYU Abu Dhabi
UAE O: +971 2 628-4990
UAE C: +971 56 6793378

NYU Abu Dhabi, Saadiyat Campus
Computational Research Building (A2), 014
P.O. Box 129188
Abu Dhabi, United Arab Emirates (EST + 8 hours)

**Comment by osamaNYUAD** [comment]
Hello Chris,

Following on the issue below. I checked the SeriesUID and they matched
across all dcm files in the series (the value
is  '1.3.12.2.1107.5.2.43.166043.30000022041109193489100003194' for all).

But dcm2niix is splitting the series into 2 files with this message:

Chris Rorden's dcm2niiX version v1.0.20211006  Clang12.0.5 x86-64 (64-bit
MacOS)

Found 398 DICOM file(s)

Warning: Siemens XA exported as classic not enhanced DICOM (issue 236)

Convert 93 DICOM as /Users/oa22/Downloads/DicomProblemXA30/Series Instance
UIDs
(0020,000E)-mismatch/Subject_0282/Brain_Protocols/func-bold_task-BETS_run-01_14/func-bold_task-BETS_run-01_14_func-bold_task-BETS_run-01_20220411122856_14
(80x80x44x93)

Warning: Siemens XA exported as classic not enhanced DICOM (issue 236)

Convert 305 DICOM as /Users/oa22/Downloads/DicomProblemXA30/Series Instance
UIDs
(0020,000E)-mismatch/Subject_0282/Brain_Protocols/func-bold_task-BETS_run-01_14/func-bold_task-BETS_run-01_14_func-bold_task-BETS_run-01_20220411122856_14a
(80x80x44x305)

Conversion required 1.428500 seconds (1.194218 for core code).


 I also checked the studyUID and FrameOfReferenceUID and they both matched
across all 398 time framnes

I am reattaching an example of a problematic dataset again in this email:
 DicomProblemXA30 2.zip
<https://drive.google.com/file/d/1aKUkuIX275_XZ7QBjlPe44djg90vz4GK/view?usp=drive_web>
Any other suggestions of why dcm2niix interprets the Series Instance UID
(0020, 000E) as mismatched?

*Osama Abdullah, PhD*
MRI Physicist II
Core Technology Platforms
NYU Abu Dhabi
UAE O: +971 2 628-4990
UAE C: +971 56 6793378

NYU Abu Dhabi, Saadiyat Campus
Computational Research Building (A2), 014
P.O. Box 129188
Abu Dhabi, United Arab Emirates (EST + 8 hours)

**Comment by neurolabusc** [comment]
You can see the issue yourself by renaming instead of converting the DICOMs, and using [0020,000E](https://github.com/rordenlab/dcm2niix/blob/master/FILENAMING.md) for the folder name:

```
$ dcm2niix -r y -f %s_%j/%r.dcm ~/issue599
```
Note that dcm2niix segments instances 1..93 into one folder and 94..398 into another.

```
$ dcmdump +F +P 0020,000E ~/issue599/14_1.3.12.2.1107.5.2.43.166043.2022041113414823450655743.0.0.0/1.dcm
# dcmdump (1/1): ~/issue599/14_1.3.12.2.1107.5.2.43.166043.2022041113414823450655743.0.0.0/1.dcm
(0020,000e) UI [1.3.12.2.1107.5.2.43.166043.2022041113293118947653042.0.0.0] #  60, 1 SeriesInstanceUID
(0020,000e) UI [1.3.12.2.1107.5.2.43.166043.30000022041109193489100003194] #  58, 1 SeriesInstanceUID
(0020,000e) UI [1.3.12.2.1107.5.2.43.166043.2022041113414823450655743.0.0.0] #  60, 1 SeriesInstanceUID
$ dcmdump +F +P 0020,000E ~/issue599/14_1.3.12.2.1107.5.2.43.166043.30000022041109193489100003194/94.dcm
# dcmdump (1/1): ~/issue599/14_1.3.12.2.1107.5.2.43.166043.30000022041109193489100003194/94.dcm
(0020,000e) UI [1.3.12.2.1107.5.2.43.166043.2022041113293118947653042.0.0.0] #  60, 1 SeriesInstanceUID
(0020,000e) UI [1.3.12.2.1107.5.2.43.166043.30000022041109193489100003194] #  58, 1 SeriesInstanceUID
```

You can see that SQs are added that modify the 0020,000e. The first 93 images include a SQ with:
```
    (0400,0565) CS [COERCE]                                 #   6, 1 ReasonForTheAttributeModification
```
For enhanced DICOMs, dcm2niix will use the final reported value of 0020,000e, regardless of whether it is in the main body or a SQ. I really do not understand why Siemens issues two different series UIDs for the same series. 

I note that Philips and Canon enhanced DICOMs each pack all images from a series into a single file. In contrast, Siemens enhanced saves each 3D volume as a separate file. So solutions might be to assume that either the first usage of a UID should be used for the file, or the UID that is in the main body (instead of a SQ) should be used. Either of these solutions would work for your data, but without knowing the rationale of why multiple UIDs are generated, it is hard to know if either method is reliable. We really need some insight for what is happening here.

**Comment by neurolabusc** [comment]
@osamaNYUAD can you test the current development branch (v1.0.20220429). This version will ignore all DICOM tags in the [Original Attributes SQ 0400,0561](https://dicom.innolitics.com/ciods/cr-image/sop-common/04000561). I do not understand why only some images were modified, but ignoring the original values prior to modification seems justified.

**Comment by osamaNYUAD** [comment]
Thanks Chris,

I cloned the latest development version
https://github.com/rordenlab/dcm2niix/tree/development, and compiled it per
the instructions. But I still get the split files so maybe I didn't clone
the correct version (couldn't find v1.0.20220429 specifically). Would you
point me to the path I should clone?

Thanks.

Osama

*Osama Abdullah, PhD*
MRI Physicist II
Core Technology Platforms
NYU Abu Dhabi
UAE O: +971 2 628-4990
UAE C: +971 56 6793378

NYU Abu Dhabi, Saadiyat Campus
Computational Research Building (A2), 014
P.O. Box 129188
Abu Dhabi, United Arab Emirates (EST + 8 hours)

**Comment by neurolabusc** [comment]
Assuming you are using MacOS/Linux:
```
$ git clone --branch development https://github.com/rordenlab/dcm2niix
$ cd dcm2niix/console
$ make
./dcm2niix
Chris Rorden's dcm2niiX version v1.0.20220429  Clang12.0.5 ARM (64-bit MacOS)
```

If you are using Windows, you can get a precompiled version from [AppVeyor](https://ci.appveyor.com/project/neurolabusc/dcm2niix/build/artifacts).

**Comment by osamaNYUAD** [comment]
Amazing, that worked. Thanks very much Chris.

I am in contact with Siemens Dicom folks in germany. I'll inquire why
the  Original
Attributes SQ 0400,0561
<https://urldefense.proofpoint.com/v2/url?u=https-3A__dicom.innolitics.com_ciods_cr-2Dimage_sop-2Dcommon_04000561&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=_qtxQtVtoeBxGIfwqYkiHXqtL6g12Y4QFAs-CoPhkvY&m=wG3qi7dyGYW7E7p5cZXR4RKUCll9QWW9Y4bhuUH2kgR4r2Qrfl_vm-zq9nIUM4WP&s=XGDVvms352EnqpgbgOZDsXTCI0THCGGmTbWy-jMj5RA&e=>
got
modified in the same sequence. Let me know if you have any comments for
them and I'll make sure to share your feedback.

Best.

Osama



*Osama Abdullah, PhD*
MRI Physicist II
Core Technology Platforms
NYU Abu Dhabi
UAE O: +971 2 628-4990
UAE C: +971 56 6793378

NYU Abu Dhabi, Saadiyat Campus
Computational Research Building (A2), 014
P.O. Box 129188
Abu Dhabi, United Arab Emirates (EST + 8 hours)

**Comment by rmartins-net** [comment]
Thank you @neurolabusc . That worked for me as well.


Ricardo 


> Assuming you are using MacOS/Linux:
> 
> ```
> $ git clone --branch development https://github.com/rordenlab/dcm2niix
> $ cd dcm2niix/console
> $ make
> ./dcm2niix
> Chris Rorden's dcm2niiX version v1.0.20220429  Clang12.0.5 ARM (64-bit MacOS)
> ```
> 
> If you are using Windows, you can get a precompiled version from [AppVeyor](https://ci.appveyor.com/project/neurolabusc/dcm2niix/build/artifacts).
