### ISSUE TITLE
precompiled dcm2niix not running on centos7

### ISSUE THREAD

**Issue by maartenmennes** [rordenlab/dcm2niix#60]
Hello,

we're trying to run the precompiled dcm2niix version on our centos7 installation, but it fails and returns the following error:

`sh: ./pigz_mricron: cannot execute binary file`

any pointers?
Thanks,
Maarten

**Comment by neurolabusc** [comment]
Hello-

Can you provide the command line call and the full output of my software that generates this error - I can not replicate this on either a MacOS or Linux system. For example, on my computer:

$ ./dcm2niix -z y ~/test_t1
Chris Rorden's dcm2niiX version 1Nov2016 (64-bit Linux)
Found 192 DICOM image(s)
Convert 192 DICOM as /Users/rorden/tst_t1/T1_mprage_ns_sag_p2_iso_1.0mm__1_0004 (256x256x192x1)
compress: "/usr/local/bin/pigz" -n -f "/Users/rorden/tst_t1/T1_mprage_ns_sag_p2_iso_1.0mm__1_0004.nii"
Conversion required 0.358249 seconds.

-----------
 pigz_mricron is included with the MRIcroGL/dcm2niix distribution from
    https://www.nitrc.org/frs/?group_id=889
However, it is not required - my software should fall back to its internal compressor if it can not find the external programs "pigz" (e.g. /usr/local/bin/pigz) or "pigz_mricron". That is why I can not explain your error.

"pigz_mricron" is just a generic compile of pigz, so it might be a touch slower than a copy of pigz compiled just for your hardware.

**Comment by neurolabusc** [comment]
One explanation for your problem is that the file pigz_mricron exists on your path, but you do not have the execute permissions set. For example, with the output I gave above (compress: "/usr/local/bin/pigz" ...) one can check for executable permissions ('x') with the command 
$ ls -l /usr/local/bin/pigz
-rwxr-xr-x  1 rorden  staff  240344 Mar  4  2014 /usr/local/bin/pigz

**Comment by maartenmennes** [comment]
Hi Chris,

thanks for getting back. Yes, the permissions were one of the first things we checked. They're good.

We downloaded and unzipped the package, then from the unzip directory we ran the dcm2niix command. Could it be a path-related issue?

This is the command and output we get:

[maamen@proc001 mricrogl_lx]$ ./dcm2niix /data/dart/evaluation/108-007/DICOM/
Chris Rorden's dcm2niiX version 10oct2016 (64-bit Linux)
Found 6659 DICOM image(s)
slices not stacked: orientation varies (localizer?) [0 1 0 0 0 -1] != [1 0 0 0 0 -1]
Convert 7 DICOM as /data/dart/evaluation/108-007/DICOM/DICOM_localizer_20161017143403_1f (512x512x7x1)
sh: ./pigz_mricron: cannot execute binary file
compress: "./pigz_mricron" -n -f "/data/dart/evaluation/108-007/DICOM/DICOM_localizer_20161017143403_1f.nii"

**Comment by maartenmennes** [comment]
Hi Chris,

looking a bit more into it, it looks like the dicom to nii conversion worked, and that it is simply the gzip compression that fails. Can we be certain that the dicom to nii conversion worked as intended, and that no information was lost before we crash at the compression step?

**Comment by neurolabusc** [comment]
the output of dcm2nii are the .nii files, it then calls the external program pigz if you requested compression (and did not use the built-in compressor). So the nit files are fine, you just have to work out why pigz failed. My guess is that you need to install a version of pigz that is compatible with your operating system (I am not familiar with CentOS 7, but perhaps "yum install pigz"). So technically this is not a fault of my software, though in future I will test my pro-compiled tools to make sure they run on CentOS 6 or later (e.g. perhaps pigz_mricron was compiled on a more recent Linux that is not backward compatible.

**Comment by maartenmennes** [comment]
Thanks for the feedback Chris! Installing pigz seemed to have done the trick!
