### ISSUE TITLE
Problems with different versions

### ISSUE THREAD

**Issue by Lorenzomarta** [rordenlab/dcm2niix#607]
Hi everyone, 
I currently have installed on macOS the Chris Rorden's dcm2niiX version v1.0.20211006  Clang13.0.0 ARM (64-bit MacOS) v1.0.20211006, but due to compatibility problems I have to install Chris Rorden's dcm2niiX version v1.0.20190902  (JP2:OpenJPEG) (JP-LS:CharLS) Clang8.1.0 (64-bit MacOS) v1.0.20190902. 
How can I do that?

**Comment by neurolabusc** [comment]
The easiest solution is to download a pre-compiled release. Use a web browser to go to the [dcm2niix releases](https://github.com/rordenlab/dcm2niix/releases) and select the [version you are interested in](https://github.com/rordenlab/dcm2niix/releases/tag/v1.0.20190902) and finally [download the precompiled software for your desired operating system](https://github.com/rordenlab/dcm2niix/releases/download/v1.0.20190902/dcm2niix_mac.zip).

Alternatively, you can download the source code and compile it yourself. Below I assume you want release `v1.0.20190902`, but you can use your web browser (see above) to determine stable release versions.

```
$ curl -fLO https://github.com/rordenlab/dcm2niix/archive/refs/tags/v1.0.20190902.zip
$ unzip v1.0.20190902.zip
$ cd dcm2niix-1.0.20190902/console
$ make
```
`make` is the easiest way to compile dcm2niix. However, if you need to support JPEG2000 and other obscure transfer syntaxes you will want to use `cmake` - see the [dcm2niix Github page for more details on using cmake](https://github.com/rordenlab/dcm2niix).

**Comment by Lorenzomarta** [comment]
Thank you but I have already tried both ways, only if I type in terminal: "dcm2niix --version" I see that version v1.0.20211006 is installed and not the one I need, i.e. v1.0.20190902

**Comment by neurolabusc** [comment]
You can run `which dcm2niix` to see the location of dcm2niix you are running. You can change your environment path to run a specific version or you can explicitly provide the path to the specific binary you want to run, e.g. `./dcm2niix` runs the copy of dcm2niix in the current working directory, `dcm2niix` runs the copy in your environment path, and `/path/to/my/dcm2niix` explicitly runs the version at the provided path.
