### ISSUE TITLE
nifti file read and edit header

### ISSUE THREAD

**Issue by jfkdaf** [rordenlab/dcm2niix#610]
i open a nifti file using niftiinfo('file.nii') and I'm trying to edit the header of that nifti file. 
For example, i try to do 
 info = niftiinfo('file.nii');
v = niftiread(info);

%then I go onto edit the header of the nifti file
info.ImageSize = [234 234, 200]
but when I go on to save it through
niftiwrite(v, 'file.nii', info)
it gives me an error, saying 'Assertion failed.'

**Comment by neurolabusc** [comment]
dcm2niix is an open source tool for converting DICOM data to NIfTI. The commands `niftiinfo`, `niftiread`, and `niftiwrite` are part of the [Image Processing toolbox](https://www.mathworks.com/help/images/ref/niftiwrite.html) of Matlab. Matlab has its own forums to support users. 

Be aware that many Matlab users do not purchase the Image Processing Toolbox. If you want to share your code you may want to use NIfTI routines in SPM, [dicm2nii](https://github.com/xiangruili/dicm2nii) or [NIfTI tools[(https://github.com/sergivalverde/nifti_tools). For example, here is [my Matlab code that uses SPM to crop NIfTI images](https://github.com/rordenlab/spmScripts/blob/bb984930e68952f359a7968536503b7e8dcbc419/nii_tight_crop.m).
