### ISSUE TITLE
TotalReadoutTime missing in BOLD JSON

### ISSUE THREAD

**Issue by zhengchencai** [rordenlab/dcm2niix#613]
Hello,

I'm not sure if this is a bug or just my way of using dcm2niix. We have some fMRI scans from 2006-2008, after converting from dcm to nii, they do not have TotalReadoutTime tag in BOLD JSON, resulting in fmriprep crushes during SDC. Do you know if it is possible to solve this? 

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_n>    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_inte>    return self._run_command(execute)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_comm>    result = self._interface.run(cwd=outdir)
  File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 428, in run
    runtime = self._run_interface(runtime)
  File "/opt/conda/lib/python3.8/site-packages/sdcflows/interfaces/epi.py", line 55, in _run_interface
    self._results["readout_time"] = get_trt(
  File "/opt/conda/lib/python3.8/site-packages/sdcflows/utils/epimanip.py", line 228, in get_trt
    raise ValueError("Unknown total-readout time specification")
ValueError: Unknown total-readout time specification
```

**Comment by neurolabusc** [comment]
Perhaps you want to provide one of the impoverished BIDS JSON files for more feedback. Be aware that on can not determine [TotalReadoutTime for data acquired on Philips MRI scanners](https://github.com/rordenlab/dcm2niix/tree/master/Philips#missing-information). This reflects a limitation of the Philips DICOMs, not dcm2niix.

**Comment by zhengchencai** [comment]
Thanks @neurolabusc, I don't think we used Philips scanner, here are two examples (1st scanned in 2006 and 2nd in 2007), I copied JSON of one BOLD run from dcm2niiX version v1.0.20211220  GCC9.3.0 x86-64 (64-bit Linux)

```
{
	"Modality": "MR",
	"MagneticFieldStrength": 2.89362,
	"ImagingFrequency": 123.248,
	"Manufacturer": "Siemens",
	"ManufacturersModelName": "Trio",
	"InstitutionName": "xxxx",
	"InstitutionAddress": "xxxx",
	"DeviceSerialNumber": "20603",
	"StationName": "MRC20603",
	"PatientPosition": "HFS",
	"ProcedureStepDescription": "FUNCTIONAL",
	"SoftwareVersions": "syngo MR 2004A 4VA25A",
	"MRAcquisitionType": "2D",
	"SeriesDescription": "BOLD MOSAIC 64",
	"ProtocolName": "BOLD MOSAIC 64",
	"ScanningSequence": "SE\\EP",
	"SequenceVariant": "SK",
	"ScanOptions": "FS",
	"SequenceName": "*epfid2d1_64",
	"ImageType": ["ORIGINAL", "PRIMARY", "M", "ND", "MOSAIC"],
	"SeriesNumber": 4,
	"AcquisitionTime": "14:56:15.745010",
	"AcquisitionNumber": 1,
	"SliceThickness": 5,
	"SpacingBetweenSlices": 5,
	"SAR": 0.062443,
	"EchoTime": 0.03,
	"RepetitionTime": 1.75,
	"FlipAngle": 90,
	"PartialFourier": 1,
	"BaseResolution": 64,
	"ShimSetting": [
		96,
		-6130,
		-1737,
		1116,
		563,
		-1868,
		1143,
		130	],
	"DelayTime": 0.25,
	"TxRefAmp": 229.286,
	"PhaseResolution": 1,
	"ReceiveCoilName": "CP_Head",
	"PulseSequenceDetails": "%SiemensSeq%\\ep2d_bold",
	"MatrixCoilMode": "SENSE",
	"PercentPhaseFOV": 100,
	"PercentSampling": 100,
	"PhaseEncodingSteps": 64,
	"AcquisitionMatrixPE": 64,
	"ReconMatrixPE": 64,
	"PixelBandwidth": 2440,
	"PhaseEncodingDirection": "j-",
	"SliceTiming": [
		1.44,
		1.38,
		1.32,
		1.26,
		1.2,
		1.14,
		1.08,
		1.02,
		0.96,
		0.9,
		0.84,
		0.78,
		0.72,
		0.66,
		0.6,
		0.54,
		0.48,
		0.42,
		0.36,
		0.3,
		0.24,
		0.18,
		0.12,
		0.06,
		0	],
	"ImageOrientationPatientDICOM": [
		1,
		0,
		0,
		0,
		0.997687,
		0.0679734	],
	"InPlanePhaseEncodingDirectionDICOM": "COL",
	"ConversionSoftware": "dcm2niix",
	"ConversionSoftwareVersion": "v1.0.20211220"
}

```

```
{
	"Modality": "MR",
	"MagneticFieldStrength": 2.89362,
	"ImagingFrequency": 123.248,
	"Manufacturer": "Siemens",
	"ManufacturersModelName": "Trio",
	"InstitutionName": "xxxx",
	"InstitutionAddress": "xxxx",
	"DeviceSerialNumber": "20603",
	"StationName": "MRC20603",
	"PatientPosition": "HFS",
	"ProcedureStepDescription": "FUNCTIONAL",
	"SoftwareVersions": "syngo MR 2004A 4VA25A",
	"MRAcquisitionType": "2D",
	"SeriesDescription": "BOLD MOSAIC 64",
	"ProtocolName": "BOLD MOSAIC 64",
	"ScanningSequence": "SE\\EP",
	"SequenceVariant": "SK",
	"ScanOptions": "FS",
	"SequenceName": "*epfid2d1_64",
	"ImageType": ["ORIGINAL", "PRIMARY", "M", "ND", "MOSAIC"],
	"SeriesNumber": 4,
	"AcquisitionTime": "14:56:15.745010",
	"AcquisitionNumber": 1,
	"SliceThickness": 5,
	"SpacingBetweenSlices": 5,
	"SAR": 0.062443,
	"EchoTime": 0.03,
	"RepetitionTime": 1.75,
	"FlipAngle": 90,
	"PartialFourier": 1,
	"BaseResolution": 64,
	"ShimSetting": [
		96,
		-6130,
		-1737,
		1116,
		563,
		-1868,
		1143,
		130	],
	"DelayTime": 0.25,
	"TxRefAmp": 229.286,
	"PhaseResolution": 1,
	"ReceiveCoilName": "CP_Head",
	"PulseSequenceDetails": "%SiemensSeq%\\ep2d_bold",
	"MatrixCoilMode": "SENSE",
	"PercentPhaseFOV": 100,
	"PercentSampling": 100,
	"PhaseEncodingSteps": 64,
	"AcquisitionMatrixPE": 64,
	"ReconMatrixPE": 64,
	"PixelBandwidth": 2440,
	"PhaseEncodingDirection": "j-",
	"SliceTiming": [
		1.44,
		1.38,
		1.32,
		1.26,
		1.2,
		1.14,
		1.08,
		1.02,
		0.96,
		0.9,
		0.84,
		0.78,
		0.72,
		0.66,
		0.6,
		0.54,
		0.48,
		0.42,
		0.36,
		0.3,
		0.24,
		0.18,
		0.12,
		0.06,
		0	],
	"ImageOrientationPatientDICOM": [
		1,
		0,
		0,
		0,
		0.997687,
		0.0679734	],
	"InPlanePhaseEncodingDirectionDICOM": "COL",
	"ConversionSoftware": "dcm2niix",
	"ConversionSoftwareVersion": "v1.0.20211220"
}
```

**Comment by neurolabusc** [comment]
The scanner that acquired these images was running 2004 vintage software (VA25 system). The oldest data I have is 2006 vintage [VB12](https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#Archival_MRI). I suspect that back in 2004 the [CSA header](https://nipy.org/nibabel/dicom/siemens_csa.html) did not include the sequence parameters that allow us to infer TotalReadoutTime. Note that you can guess on readout time: it only influences the calibrated estimates for effect sizes, the images that are calculated and used for further processing are not influenced by this value (at least assuming your images with forward phase encoding have the same readout time as the reverse phase encoding, which seems extremely likely).

**Comment by zhengchencai** [comment]
Thanks @neurolabusc, I remember seeing some posts on Neurostars setting TotalReadoutTime = 1 and was wondering why, now it is clear. This may not be related to dcm2niix, the error I got from fmripreo for SDC was actually SyN-based, do you think TotalReadoutTime = 1 is also appropriate in this case, feel free to ignore this question.

**Comment by neurolabusc** [comment]
@zhengchencai for your images, I believe that you can accurately determine total readout time using the `PixelBandwidth` and `AcquisitionMatrixPE` values using a simple [formula](https://lcni.uoregon.edu/kb-articles/kb-0003). dcm2niix can not do this for you because it is unable to determine if in-plane acceleration (SENSE, GRAPPA) was applied. I believe VA25 did not support these methods, so you can use the simple equation.

**Comment by pvelasco** [comment]
@zhengchencai, in case it helps: the coil used to acquire this images is `"CP_Head", which is single channel, so the in-plane acceleration would be 1.

**Comment by neurolabusc** [comment]
The dcm2niix heuristic is that if the manufacturer is Siemens with V* software the private tag [0021,1009](https://github.com/rordenlab/dcm2niix/blob/002ebcdb9b2a87de7b883e9ddada3963a1cc2327/console/nii_dicom.cpp#L5746) is used to determine in plane acceleration. If this tag is missing, dcm2niix is unable to determine the TotalReadoutTime. It is common for private tags to be stripped by anonymization tools, so one needs to be careful when vital tags are missing. dcm2niix attempts to err on the side of caution when calculating BIDS tags. If someone can assure me that Siemens VA* systems **never** allowed in-plane acceleration, we could update the heuristic.

**Comment by pvelasco** [comment]
Even if Siemens didn't support in-plane acceleration (I suspect they did support it), nothing prevented a customer from programming their own accelerated sequence. So, if you want to be on the safe side, I would not update the heuristic assuming there was not in-plane acceleration.

A safer bet would be to assume that if the in-plane acceleration tag is missing, the value was 1. But you should probably confirm with real data, and I don't know how easy would be to get a hold on those. Maybe Ben Inglis has some more insight? (I don't know his Github handle...)

**Comment by pvelasco** [comment]
Sounds good.

**Comment by mharms** [comment]
> 



> @zhengchencai for your images, I believe that you can accurately determine total readout time using the `PixelBandwidth` and `AcquisitionMatrixPE` values using a simple [formula](https://lcni.uoregon.edu/kb-articles/kb-0003). dcm2niix can not do this for you because it is unable to determine if in-plane acceleration (SENSE, GRAPPA) was applied. I believe VA25 did not support these methods, so you can use the simple equation.

I'm afraid that the preceding from earlier in this thread is not correct.  `EffectiveEchoSpacing` (from which `TotalReadoutTime` is derived) is based on bandwidth per pixel in the *phase* direction `BandwidthPerPixelPhaseEncode` -- not `PixelBandwidth` (which is the bandwidth per pixel in the *read* direction).  `BandwidthPerPixelPhaseEncode` is contained in (0019,1028), for Siemens data, so I suspect that your DICOMs are missing that private DICOM field.

**Comment by zhengchencai** [comment]
@mharms, thanks for the clarification. sure I don't have ```BandwidthPerPixelPhaseEncode``` tag in my DICOM data. I thought ```PixelBandwidth``` divided by ```PhaseEncodingSteps``` could approximate ```BandwidthPerPixelPhaseEncode```. I tried to validate this on DICOM with (0019,1028) tag. The approximated ```TotalReadoutTime``` = 1/```hat(BandwidthPerPixelPhaseEncode)``` = ```PhaseEncodingSteps```/```PixelBandwidth``` = 64/2440 = 0.02622951ms. However, the real ```TotalReadoutTime``` recorded in the sidecar is 0.0296097ms. I was not sure if this is a sufficiently precise approximation, so eventually, I decided to not use approximations and don't perform SDC if there is no ```TotalReadoutTime```.

**Comment by mharms** [comment]
No, you can't divide `PixelBandwidth` by `PhaseEncodingSteps` to get `BandwidthPerPixelPhaseEncode`.  The first is a parameter of the *readout* axis.  The latter two are parameters of the *phase* axis.  The *readout* and *phase* axes are distinct.

**Comment by zhengchencai** [comment]
@mharms thanks a lot, that’s great to know. No wonder why my silly approximation was not exactly the same as the real one.
