### ISSUE TITLE
syntax problem in JSON siedecar when FrameDuration have only 1 element

### ISSUE THREAD

**Issue by benoitberanger** [rordenlab/dcm2niix#616]
**Describe the bug**

On a DWI dataset, the JSON sidecar `FrameDuration` have only 1 element, but is written as an array, and the line is finished by a comma :
```
                105,
                108,
                114,
                117,
                120,
                129     ],
        "FrameDuration": [
                1200,
        ],
        "SliceThickness": 2,
        "SpacingBetweenSlices": 2,
        "SAR": 0.171903,
        "EchoTime": 0.095,
        "SpoilingState": true,
        "FlipAngle": 90,
        "PartialFourier": 0.875,
        "BaseResolution": 116,

```
This syntax in not JSON compatible.

**To reproduce**

Version number : 20211220
Commit number : 002ebcdb9b2a87de7b883e9ddada3963a1cc2327
Command : `dcm2niix -o /mnt/data/benoit/project/ADNI/nifti_20211220 -ba n /mnt/data/benoit/project/ADNI/dicom`

**Expected behavior**

I would expect a JSON standard syntax : 
```
                105,
                108,
                114,
                117,
                120,
                129     ],
        "FrameDuration": 1200,
        "SliceThickness": 2,
        "SpacingBetweenSlices": 2,
        "SAR": 0.171903,
        "EchoTime": 0.095,
        "SpoilingState": true,
        "FlipAngle": 90,
        "PartialFourier": 0.875,
        "BaseResolution": 116,

```

**Output log**

_see above_

**Version**

Please report the complete version string:

```
Chris Rorden's dcm2niiX version v1.0.20211220  GCC7.5.0 x86-64 (64-bit Linux)
v1.0.20211220
```

**Comment by benoitberanger** [comment]
From reading the code, it comes from these lines : 
https://github.com/rordenlab/dcm2niix/blob/002ebcdb9b2a87de7b883e9ddada3963a1cc2327/console/nii_dicom_batch.cpp#L1378
```
	if (dti4D->frameDuration[0] >= 0.0) { //see BEP009 PET https://docs.google.com/document/d/1mqMLnxVdLwZjDd4ZiWFqjEAmOmfcModA_R535v3eQs0
		fprintf(fp, "\t\"FrameDuration\": [\n");
		for (int i = 0; i < h->dim[4]; i++) {
			if (i != 0)
				fprintf(fp, ",\n");
			if (dti4D->frameDuration[i] < 0)
				break;
			if ((isSameFloatGE(dti4D->frameDuration[i], 0.0)) && (d.TR > 0.0))
				fprintf(fp, "\t\t%g", d.TR / 1000.0); // from 0018,1242 ms -> sec
			else
				fprintf(fp, "\t\t%g", dti4D->frameDuration[i] / 1000.0); // from 0018,1242 ms -> sec
		}
		fprintf(fp, "\t],\n");
```
The comma is written, then the break happens.

**Comment by neurolabusc** [comment]
@benoitberanger can you confirm that the latest commit to the development branch resolves this issue. The BIDS tag [FrameDuration](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/09-positron-emission-tomography.html#time) will now only be populated for 4D datasets. Perhaps you can provide more details on the ADNI dataset that is eliciting this error, as a DWI DICOM dataset should not contain this tag.

@captainnova maybe you want to track down why an ADNI DWI MR reports the [Actual Frame Duration](https://dicom.innolitics.com/ciods/nm-image/nm-image/00181242#:~:text=Actual%20Frame%20Duration%20(0018%2C1242,in%20the%20appropriate%20IOD%20Module.) from the [Nuclear Medicine](https://dicom.nema.org/medical/Dicom/2016c/output/chtml/part03/sect_C.8.4.9.html#table_C.8-9) module. I added this in to support BIDS BEP009.

**Comment by captainnova** [comment]
@neurolabusc, we certainly would like to track this down, although since we only use product sequences it will probably be more a matter of data curation than being able to do much about improving DICOM compliance in already acquired scans. We also don't acquire the sort of b = 0 + 3 b = 1000 scans that "DWI" often means, but often additional series get uploaded from the site to LONI along with the standard ADNI protocol. Such series should be filtered out and not leave LONI, but mistakes happen.

@benoitberanger can you please share the participant ID, scan date, and series number of this series? If you got it from LONI I should already have the DICOM in our local filesystem. If instead it came from some other source, such as an "ADNI-like" study, that will be important to know.

Thanks,

Rob

**Comment by benoitberanger** [comment]
@neurolabusc using this dev commit 63c76f2603c56137d76f70b88c23af996cf8f2d9, here is the same JSON : 
```
{
	"Modality": "MR",
	"MagneticFieldStrength": 3,
	"ImagingFrequency": 123.259,
	"Manufacturer": "Siemens",
	"ManufacturersModelName": "Verio",
	"InstitutionName": "(HS)",
	"DeviceSerialNumber": "45BRw1yUPwCA",
	"SeriesInstanceUID": "2.16.124.113543.6006.99.04340590288885489085",
	"StudyInstanceUID": "2.16.124.113543.6006.99.04326325390037115711",
	"PatientName": "014_S_6437",
	"PatientID": "014_S_6437",
	"PatientSex": "O",
	"PatientWeight": 106.028,
	"PatientPosition": "HFS",
	"SoftwareVersions": "syngo MR B19",
	"MRAcquisitionType": "2D",
	"SeriesDescription": "Axial DTI",
	"ProtocolName": "Axial DTI",
	"ScanningSequence": "EP",
	"SequenceVariant": "SK\\SP",
	"ScanOptions": "PFP\\FS",
	"SequenceName": "*ep_b0",
	"ImageType": ["ORIGINAL", "PRIMARY", "DIFFUSION", "NONE", "ND", "NORM", "MOSAIC"],
	"SeriesNumber": 11,
	"AcquisitionTime": "14:36:32.697500",
	"AcquisitionDateTime": "2020-10-06T14:36:32.697500",
	"AcquisitionNumber": 1,
	"FrameTimesStart": [
		0,
		3,
		6,
		12,
		15,
		21,
		24,
		27,
		30,
		39,
		42,
		45,
		48,
		54,
		57,
		60,
		66,
		69,
		78,
		81,
		84,
		87,
		96,
		99,
		102,
		105,
		108,
		114,
		117,
		120,
		129	],
	"FrameDuration": [
		1200,
	],
	"FrameReferenceTime": [
		0,
	],
	"SliceThickness": 2,
	"SpacingBetweenSlices": 2,
	"SAR": 0.171903,
	"EchoTime": 0.095,
	"SpoilingState": true,
	"FlipAngle": 90,
	"PartialFourier": 0.875,
	"BaseResolution": 116,
	"ShimSetting": [
		-1045,
		14235,
		7858,
		139,
		151,
		-849,
		551,
		7	],
	"DiffusionScheme": "Monopolar",
	"TxRefAmp": 531.957,
	"PhaseResolution": 1,
	"VendorReportedEchoSpacing": 0.00078,
	"ReceiveCoilName": "HeadMatrix",
	"PulseSequenceDetails": "%SiemensSeq%\\ep2d_diff",
	"RefLinesPE": 40,
	"CoilCombinationMethod": "Adaptive Combine",
	"MatrixCoilMode": "GRAPPA",
	"PercentPhaseFOV": 100,
	"PercentSampling": 100,
	"PhaseEncodingSteps": 100,
	"AcquisitionMatrixPE": 116,
	"ReconMatrixPE": 116,
	"BandwidthPerPixelPhaseEncode": 22.104,
	"ParallelReductionFactorInPlane": 2,
	"EffectiveEchoSpacing": 0.000390006,
	"DerivedVendorReportedEchoSpacing": 0.000780012,
	"TotalReadoutTime": 0.0448507,
	"PixelBandwidth": 1486,
	"DwellTime": 2.9e-06,
	"PhaseEncodingDirection": "j-",
	"SliceTiming": [
		6.225,
		0,
		6.38,
		0.155,
		6.535,
		0.31,
		6.69,
		0.4675,
		6.8475,
		0.6225,
		7.0025,
		0.7775,
		7.1575,
		0.9325,
		7.3125,
		1.09,
		7.47,
		1.245,
		7.625,
		1.4,
		7.78,
		1.555,
		7.935,
		1.7125,
		8.0925,
		1.8675,
		8.2475,
		2.0225,
		8.4025,
		2.1775,
		8.5575,
		2.335,
		8.715,
		2.49,
		8.87,
		2.645,
		9.025,
		2.8,
		9.18,
		2.9575,
		9.3375,
		3.1125,
		9.4925,
		3.2675,
		9.6475,
		3.4225,
		9.8025,
		3.58,
		9.96,
		3.735,
		10.115,
		3.89,
		10.27,
		4.045,
		10.425,
		4.2025,
		10.5825,
		4.3575,
		10.7375,
		4.5125,
		10.8925,
		4.6675,
		11.0475,
		4.825,
		11.205,
		4.98,
		11.36,
		5.135,
		11.515,
		5.29,
		11.67,
		5.4475,
		11.8275,
		5.6025,
		11.9825,
		5.7575,
		12.1375,
		5.9125,
		12.2925,
		6.0675	],
	"ImageOrientationPatientDICOM": [
		1,
		0,
		0,
		0,
		1,
		0	],
	"InPlanePhaseEncodingDirectionDICOM": "COL",
	"ConversionSoftware": "dcm2niix",
	"ConversionSoftwareVersion": "v1.0.20220606"
}
```

JSON syntax is not correct here :
```
	"FrameDuration": [
		1200,
	],
	"FrameReferenceTime": [
		0,
	],
```

**Comment by neurolabusc** [comment]
Can you share the DICOMs privately with me by sending a GoogleDrive or DropBox link to my [institutional email](https://sc.edu/study/colleges_schools/artsandsciences/psychology/our_people/directory/rorden_chris.php)? It would be nice to have a concrete example to understand what is happening.

**Comment by benoitberanger** [comment]
I just shared the whole dataset I have.

Here is the complete command line I run after changing the commit (or try a modification in the source myself) : 
```
benoit.beranger@icm-cenir-le33: /usr/local/dcm2niix $ rm -rf build; mkdir build; cd build; cmake ..; make -j 4; cd ..; rm -f /mnt/data/benoit/project/ADNI/nifti_20211220/*; dcm2niix -o /mnt/data/benoit/project/ADNI/nifti_20211220 -ba n /mnt/data/benoit/project/ADNI/dicom; vi /mnt/data/benoit/project/ADNI/nifti_20211220/dicom_Axial_DTI_20201006135507_11.json
```

_dcm2niix binary_ file have a symlink in `/usr/local/bin` : 
```
benoit.beranger@icm-cenir-le33: /usr/local/dcm2niix $ which dcm2niix
/usr/local/bin/dcm2niix
benoit.beranger@icm-cenir-le33: /usr/local/dcm2niix $ ll /usr/local/bin/dcm2niix
lrwxrwxrwx 1 root root 38 2021-11-22 14:05 /usr/local/bin/dcm2niix -> /usr/local/dcm2niix/build/bin/dcm2niix*
benoit.beranger@icm-cenir-le33: /usr/local/dcm2niix $ 
```

**Comment by benoitberanger** [comment]
With the new commit in the dev branch (3583fcc80a0c01b6b3f555184c34e3bcc9e9ec6f), the JSON syntax problem is resolved !
Thanks you !

**Comment by captainnova** [comment]
Hi, to follow up on the possible ADNI data curation issue, @benoitberanger, @neurolabusc, could you please specify the ADNI subject ID and scan date of the problem session? ADNI is longitudinal, and 016_S_6790 has had more than one scan date, none of which are 2020-10-06. There was one on 2020-10-21 where both the dMRI and fMRI failed our protocol checker and thus should not have been released from quarantine (but they were).

Meanwhile 014_S_6437 20201006 from the BIDS Benoit posted above appears to be normal.

Thanks
