### ISSUE TITLE
GE Direct field mapping deltaTE (or TE1/TE2)

### ISSUE THREAD

**Issue by mr-jaemin** [rordenlab/dcm2niix#617]
What do you think about adding the delta TE or (TE1, TE2) from GE direct field mapping DICOM to BID JSON?

```
The delta TE = 1e6 / (2 x pi x VelocityEncodeScale)
```
where VelocityEncodeScale can be found from DICOM
> Example value from [dcm_qa_fmap/GE_6_CV_Neuro](https://github.com/neurolabusc/dcm_qa_fmap):
> (0019,10e2) DS [-69.077667]                             #  10, 1 VelocityEncodeScale

Delta TE = 2304 us (TE1 = 4608 us, TE2=6912 us)

I confirmed the TE1/TE2/VelocityEncodeScale on the console as well as the above formula from the code. Any suggestion to save the delta TE or TE2 information in the BIDS sidecar JSON file?

[GE_6_CV_Neuro_HH_Adv_fieldmaphz.json](https://github.com/neurolabusc/dcm_qa_fmap/blob/main/Ref/GE_6_CV_Neuro_HH_Adv_fieldmaphz.json)
```
{
	"Modality": "MR",
	"MagneticFieldStrength": 3,
	"ImagingFrequency": 127.738,
	"Manufacturer": "GE",
	"ManufacturersModelName": "SIGNA Architect",
	"InstitutionName": "Bay6 NOT FOR DIAGNOSTIC USE",
	"DeviceSerialNumber": "0000000LXBAY6NET",
	"StationName": "GEHCBAY6",
	"BodyPartExamined": "BRAIN",
	"PatientPosition": "HFS",
	"SoftwareVersions": "27\\LX\\MR Software release:DV27.0_R01_1850.a",
	"MRAcquisitionType": "2D",
	"SeriesDescription": "B0map",
	"ProtocolName": "CV_Neuro_HH_Adv",
	"ScanningSequence": "RM",
	"SequenceVariant": "NONE",
	"ScanOptions": "VB_GEMS",
	"ImageType": ["ORIGINAL", "PRIMARY", "OTHER", "REAL", "FIELDMAPHZ"],
	"RawImage": false,
	"SeriesNumber": 6,
	"AcquisitionNumber": 1,
	"Units": "Hz",
	"SliceThickness": 5,
	"SpacingBetweenSlices": 9,
	"SAR": 0.0122642,
	"EchoTime": 0.004608,
	"RepetitionTime": 0.2,
	"FlipAngle": 20,
	"CoilString": "48HAP",
	"PercentPhaseFOV": 100,
	"PercentSampling": 100,
	"AcquisitionMatrixPE": 128,
	"ReconMatrixPE": 128,
	"ParallelReductionFactorInPlane": 2,
	"EffectiveEchoSpacing": 0.00114293,
	"TotalReadoutTime": 0.145152,
	"PixelBandwidth": 488.281,
	"PhaseEncodingAxis": "j",
	"ImageOrientationPatientDICOM": [
		1,
		-0,
		0,
		-0,
		1,
		0	],
	"InPlanePhaseEncodingDirectionDICOM": "COL",
	"ConversionSoftware": "dcm2niix",
	"ConversionSoftwareVersion": "v1.0.20211006"
> }
```

**Comment by mr-jaemin** [comment]
The delta TE is controlled by the User CV implicitly:

- If Scan Modes: 1=Patient Scanning (CV2 for 2D or CV30 for 3D), B0 Field Mapping Range is set based on Fat/Water Chemical Shift (i.e. 220 Hz for 3T). In this mode, the UI "B0 Field Mapping Range" (CV4 for 2D) will be displayed but will NOT be utilized.
- If Scan Modes: 0=Service Mode, the B0 Field Mapping Range is set by the UI "B0 Field Mapping Range" (CV4 for 2D or CV33 for 3D)
- DICOM private tags store these CV values (CV2, CV2, CV30, CV33):

2D (B0map or B0rf)
![Screen Shot 2022-07-19 at 4 57 56 PM](https://user-images.githubusercontent.com/72111485/179847209-007da214-c75a-425c-8253-b99b8bb9642e.png)
![Screen Shot 2022-07-19 at 3 36 43 PM](https://user-images.githubusercontent.com/72111485/179845055-69e49d65-7c66-418b-a236-957f770c6b34.png)
![Screen Shot 2022-07-19 at 5 00 45 PM](https://user-images.githubusercontent.com/72111485/179847621-eba23d9b-02ad-49a0-8736-62203f46fada.png)

3D (3db0map)
![Screen Shot 2022-07-19 at 5 04 35 PM](https://user-images.githubusercontent.com/72111485/179848283-8227c99d-d810-420e-b942-f7db55ecc176.png)
![Screen Shot 2022-07-19 at 4 43 44 PM](https://user-images.githubusercontent.com/72111485/179845045-7210be21-a786-4700-b270-6c6a5cbe6db4.png)
![Screen Shot 2022-07-19 at 5 00 11 PM](https://user-images.githubusercontent.com/72111485/179847767-989532de-9016-44c3-bc14-e63af6e6c064.png)

**Comment by neurolabusc** [comment]
@mr-jaemin I think the [BIDS fields are ](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#case-1-phase-difference-map-and-at-least-one-magnitude-image) would be `EchoTime1` and `EchoTime2`, right?

**Comment by mr-jaemin** [comment]
Sounds good! `EchoTime1` and `EchoTime2` to both magnitude and fieldmap JSON files? Please let me know if you want me to do pull request or you could take care of this.

**Comment by neurolabusc** [comment]
@mr-jaemin GE scanners generate a [direct field mapping](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#case-3-direct-field-mapping). So the only required BIDS field for the `FIELDMAPHZ` image type is `Units` which dcm2niix correctly populates (as `Hz`). The `EchoTime1` and `EchoTime2` are only required for a phase difference map.

So it looks like adding these values is optional. My sense is that they would only obfuscate the raw magnitude, phase, raw and imaginary images, as each of those only has a single echo time associated with the image. It seems like it might be helpful (but not required) to include  `EchoTime1` and `EchoTime2` in the derived `FIELDMAPHZ` image as it is the derived from two images with different echo times.

I suggest you submit a pull request, I am recovering from shoulder surgery so typing is laborious for me.

**Comment by mr-jaemin** [comment]
Agreed that it may be confusing to add `EchoTime1` and `EchoTime2` to the magnitude images of the first echo (i.e single echo).  I would add the `EchoTime1` and `EchoTime2` to the `FIELDMAPHZ` JSON file only since they would be a useful information, especially for unwrapping.

I would submit a pull request. Hope you recover soon.

**Comment by neurolabusc** [comment]
Fixed in development branch
