### ISSUE TITLE
Bad conversions of date "0001-01-01"

### ISSUE THREAD

**Issue by cmadjar** [rordenlab/dcm2niix#620]
**Describe the bug**

Date `'0001-01-01'` gets converted to either `"   1-01-01"` or `"  10-10-01T01:01:1.000000"` depending on whether the DICOM field set is of format DT or DA. 

**To reproduce**

Modify the DICOM to match:
```
(0010,0030) DA [00010101]                               #   8, 1 PatientBirthDate
(0008,002a) DT [00010101010101.000000+0000]             #  26, 1 AcquisitionDateTime
```

run dcm2niix `dcm2niix -ba n -z y -o <niftis_dir> <dicom_dir>`

And see the content of the JSON file

**Version**

```
$ dcm2niix --version
Chris Rorden's dcm2niiX version v1.0.20211006  (JP2:OpenJPEG) (JP-LS:CharLS) GCC7.5.0 x86-64 (64-bit Linux)
v1.0.20211006
```

**Comment by neurolabusc** [comment]
The [DT Value Representation](https://dicom.nema.org/dicom/2013/output/chtml/part05/sect_6.2.html) is in the format YYYYMMDDHHMMSS.FFFFFF&ZZXX. dcm2niix assumes that all years are 1000 AD or later, which seems like a reasonable assumption. I suggest you check the provenance of your images to determine why bogus values were stored in these fields.

**Comment by cmadjar** [comment]
Right. Makes sense. We will definitely notify the people who sent us the DICOMs. I just thought you would want to know about this in case there could be other cases like that. 

Best,
