### ISSUE TITLE
Advanced build fails to clone openjpeg

### ISSUE THREAD

**Issue by treanus** [rordenlab/dcm2niix#623]
Since a few weeks, it seems that the advanced build fails as follows:

[  4%] Creating directories for 'openjpeg'
[  8%] Performing download step (git clone) for 'openjpeg'
Cloning into 'openjpeg'...
fatal: unable to connect to github.com:
github.com[0: 140.82.121.3]: errno=Connection timed out

Cloning into 'openjpeg'...
fatal: unable to connect to github.com:
github.com[0: 140.82.121.4]: errno=Connection timed out

Cloning into 'openjpeg'...
fatal: unable to connect to github.com:
github.com[0: 140.82.121.4]: errno=Connection timed out

-- Had to git clone more than once:
          3 times.
CMake Error at openjpeg-prefix/tmp/openjpeg-gitclone.cmake:31 (message):
  Failed to clone repository: 'git://github.com/ningfei/openjpeg.git'

make[2]: *** [CMakeFiles/openjpeg.dir/build.make:98: openjpeg-prefix/src/openjpeg-stamp/openjpeg-download] Error 1
make[1]: *** [CMakeFiles/Makefile2:87: CMakeFiles/openjpeg.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by neurolabusc** [comment]
Have you tried the development branch? Github authentication has changed. New stable release is imminent.

**Comment by treanus** [comment]
Building with the development branch works like a charm. Thank you Chris!
