### ISSUE TITLE
Siemens XA30 - interleaved mag/phase in SBRef

### ISSUE THREAD

**Issue by droediger** [rordenlab/dcm2niix#626]
[This is an example](https://drive.google.com/drive/folders/1bn1BMp55n1FEBisHozC_WsZWpk6I3p3v?usp=sharing) of the single band reference image dicom we get from a 4 echo, multi-echo, multi-band acquisition that includes mag and phase contrast. Under XA30, the scanner stores the BOLD mag and phase images just fine, as 2 separate series with proper separation between contrasts and echoes. Unfortunately, the scanner is packing the SBRef image in a weird way. The first file contains alternating mag-phase slices for the first echo and the inferior portion of the image. The second through 4th files contain echoes 2-4, again interleaved mag/phase, again for the inferior part of the image. The fifth file is alternating mag/phase slices for echo 1 but for the superior portion of the image. The images are tagged as mixed contrast in the dicom, the header contains all of the slice and contrast information. We are wondering if dcm2niix could be modified to use these tags to create per echo SBRef files that concatenate the mag slices into one file and the phase images into a second file rather the mag/phase interleaved and half the brain as is the output with the current stable release (20220720).

**Comment by mharms** [comment]
Is this not something that CMRR can quickly fix on their end?

**Comment by eauerbach** [comment]
Depends on what you consider quickly, but it is certainly something I intend to address on the sequence/scanner side.

**Comment by neurolabusc** [comment]
My sense is that we wait to the CMRR team to address this. The current conversion is a faithful attempt to follow the `recipe` of the provided DICOM. Creating dispensation for these images would mean that dcm2niix's behavior would diverge from proper DICOM tools (which might surprise users) and would make maintenance of the dcm2niix code even more tricky. I think a Python script that rectifies these images regardless of converter (dcm2niix, dicm2nii, etc) seems like the appropriate approach. If someone strongly disagrees with my view, I encourage them to generate a pull request to resolve this issue more directly.

**Comment by droediger** [comment]
That's understandable. We can deal with it. 

Thanks for your response!
