### ISSUE TITLE
The new version of dcm2niix (version 20-July-2022) requires libopenjp2-7

### ISSUE THREAD

**Issue by soichih** [rordenlab/dcm2niix#629]
Although the README currently says that jp2 is optional, the compiled binary now requires libopenjp2-7 to be installed on the host machine.

**Comment by neurolabusc** [comment]
@soichih it is easy to build dcm2niix without the JPEG2000 dependency:

```
git clone https://github.com/rordenlab/dcm2niix.git
cd ./dcm2niix/console
ldd ./dcm2niix
	linux-vdso.so.1 (0x00007fff0e3b2000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f937e6e5000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f937e4f3000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f937e93f000)
```

@ningfei would it be possible to update the automated AppVeyor script so that the stock executable does have a  libopenjp2-7 dependency? Either we could run the superbuild with `USE_OPENJPEG` set to false, or we could add the library statically? If you decide to make this without JPEG2000, tell me and I will update the dcm_qa validation to not include JPEG2000 test images. 

```
curl -fLO https://github.com/rordenlab/dcm2niix/releases/latest/download/dcm2niix_lnx.zip
unzip ./dcm2niix_lnx.zip
ldd ./dcm2niix
	linux-vdso.so.1 (0x00007ffe8c7e8000)
	libopenjp2.so.7 => /lib/x86_64-linux-gnu/libopenjp2.so.7 (0x00007f9e3adc6000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f9e3ada3000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f9e3ac54000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9e3aa62000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f9e3b0ec000)
```

**Comment by ningfei** [comment]
actually the static runtime option is on, but somehow it still linked against the shared lib. We can either try to fix the dynamic link issue or a much easier solution would be adding an additional CMake option `USE_SYSTEM_OPENJPEG` and set to to `OFF` by default, so it would build openjpeg from github by default. What do you think?

**Comment by neurolabusc** [comment]
@ningfei thanks! I have tested the new Linux executable and it resolves this issue. However, it would be great if you could move the CI to Travis.

**Comment by ningfei** [comment]
@neurolabusc since Travis stopped offering free account to public repositories, did you mean moving the CI to AppVeyor? will do.

**Comment by hanayik** [comment]
Just chiming in here since this thread was in my email... why not change the CI to use Github actions? That way, there's no third party to deal with. Windows, Linux, and macOS machines are available. This is what we use for NiiVue. 

https://github.com/niivue/niivue/tree/main/.github/workflows

**Comment by ningfei** [comment]
@hanayik I don't have experience with it but looks great. With Github actions, are artifacts available upon each commit or only for release?

**Comment by hanayik** [comment]
@ningfei , artifacts can be made available each time the action workflow is triggered (usually on each push to a branch or on merge requests to master). You have to setup the artifact upload as part of the workflow file though. 

https://github.com/actions/upload-artifact

artifacts are stored for 90 days by default (and I think that is the max).

**Comment by ningfei** [comment]
@hanayik thanks! then it's perfect! will play around with it and see~

**Comment by neurolabusc** [comment]
@ningfei yes I meant `CI to AppVeyor`. As ever, I am grateful for your work on this.
