### ISSUE TITLE
Siemens coil-uncombined, multi-echo GRE DICOM conversion problem

### ISSUE THREAD

**Issue by joowon-kim** [rordenlab/dcm2niix#631]
The current dcm2niix (v1.0.20220720) does not handle Siemens coil-uncombined, multi-echo GRE DICOM files.
 
The converted files are number-of-echo Nifti files with (nx * ny * nz * n-channel) dimensions. The dimensions look correct, but the contents are mixed. The order of stored image dimension is actually nx, ny, n-channel, nz (i.e., z and channel were swapped). Moreover, they are not grouped by channel (coil) correctly. I guess Siemens has changed the rules for outputting coil name in the dicom field (0051,100F), which confuses dcm2niix coil information from extraction.
 
An offline way to group the DICOM files by coils is as follows. First, use strings to get Siemens the shadow header information, and grep a line above "B_value" (or the end of the ICE_Dims section), which will be numbers separated by _ (e.g., 32_5_1_1_1_1_160_1_1_1_1_1_3000012). These numbers represent nested loop structures used for Siemens ICE image reconstruction and should be quite consistent across Siemens software versions. The first number is the coil number corresponding to the DICOM file. Next, group the files from the same coil number in separate directories. Finally, run dcm2niix in each directory.
 
It would be very helpful if dcm2niix can implement this internally, maybe with the filename=%a option.

**Comment by neurolabusc** [comment]
Is it possible to share a dataset directly with my [institutional email](https://sc.edu/study/colleges_schools/artsandsciences/psychology/our_people/directory/rorden_chris.php)? I think your comment provides the definition for the first item in the [ICE_Dims](https://github.com/rordenlab/dcm2niix/tree/master/Siemens#siemens-x-series). Specifically, for typical combined data the value looks like this:

```
X_4_1_1_1_1_160_1_1_1_1_1_277
```
The non-numerical `X` suggests that the image is combined from multiple coils. Siemens provided my with the ICE_Dims definitions for modern XA software (where it is stored in 0021,1106), but I am not sure if this perfectly matches the order of values provided for the legacy V* software (where it is in the shadow header).

**Comment by joowon-kim** [comment]
I sent a shared file link to your institutional email address. Please let
me know if you do not receive it.

**Comment by neurolabusc** [comment]
Can you test out the latest commit to the development branch (v1.0.20220903):

```
$ git clone --branch development https://github.com/rordenlab/dcm2niix
$ cd dcm2niix/console
$ make
$ ./dcm2niix
Chris Rorden's dcm2niiX version v1.0.20220903  Clang12.0.5 ARM (64-bit MacOS)
```

You will want to turn off image merging (`-m o`) to segment coils:

```
dcm2niix -f %s -m o ~/issue631/
```

I have tried to make this backward compatible with [alternative methods for storing the Siemens coil name](https://github.com/rordenlab/dcm2niix/issues/187). I have not seen uncombined data from Siemens XA systems. If anyone can send me a sample XA dataset I can add support.

**Comment by joowon-kim** [comment]
It works! Thank you very much.
