### ISSUE TITLE
GE software version format changed in version 30

### ISSUE THREAD

**Issue by mr-jaemin** [rordenlab/dcm2niix#634]
In GE software version 30, the reported string format has changed in `(0018,102)` Software Versions.

The previous format was either 
`27\LX\MR Software release:RX27.0_R02_1831.a`
or
`28\LX\MR29.1_EA_2039.g`

In version 30, the format would be `30\LX\SIGNA_LX1.MR30.0_R01_2236.d`

I will submit Pull requests to accommodate this new string so that slice time information, which uses software version, would be accurate.

**Comment by neurolabusc** [comment]
Thanks for your PR

**Comment by mr-jaemin** [comment]
v1.0.20220915+
