### ISSUE TITLE
Conversion of dicom to nifti results in incorrect axial slice ordering 

### ISSUE THREAD

**Issue by deepakri201** [rordenlab/dcm2niix#637]
Hi, 

I am using dcm2niix to convert DICOM CT files to nii for patients from the NSCLC-Radiomics collection. For one such patient (DICOM files attached), dcm2niix produces two nifti files which both seem to have a few issues. 

In both files the axial slices are not in the correct order. In one file, the spacing in the z direction is 30 mm while it should be 3 mm, and in the second file, the number of z slices is incorrect. 

I have opened the DICOM CT files in various programs (3DSlicer, Mango viewer), and it seems like they load properly. I have also tried plastimatch to convert to nii, and do not see the same issue of the slices in the incorrect order. 

Here is a [dropbox link](https://www.dropbox.com/s/hg6smuzdnm0yz8k/dcm2niix_issue.zip?dl=0) with the CT files in question, along with the nii files produced and the log file. The following command was run: 

dcm2niix -z y -m y -o output_folder ct

I am using the compiled version of dcm2niix through Google Colab, which I installed by running `sudo apt-get install dcm2niix`. 

Thank you, 

Deepa

**Comment by neurolabusc** [comment]
In future, please complete the questions posed in the dcm2niix issues template:

```
**Troubleshooting**

Please try the following steps to resolve your issue:

 - Is this the [latest stable release](https://github.com/rordenlab/dcm2niix/releases)? If not, does the latest stable release resolve your issue?
 - If the latest stable version fails, and you are using Windows. Does the latest commit on the development branch resolve your issue? You can get a pre-compiled version from [AppVeyor](https://ci.appveyor.com/project/neurolabusc/dcm2niix) (click on the Artifacts button).
```

In the examples you provided, the version string is `v1.0.20171215` which was released in late 2017. In my test, your issue is resolved with the [latest stable release](https://github.com/rordenlab/dcm2niix/releases)  v1.0.20220720 from mid-2022.

![issue637](https://user-images.githubusercontent.com/8930807/191740954-70ef1922-b632-42a6-8d22-ad03fd16e8e7.jpg)

**Comment by deepakri201** [comment]
Thank you!
