### ISSUE TITLE
dcm2niix v1.0.20220923 (development) has become more picky about slightly corrupted DICOM

### ISSUE THREAD

**Issue by captainnova** [rordenlab/dcm2niix#639]
Hi,

The latest development version is refusing to recognize some DICOM that an earlier version (v1.0.20211006) accepts without complaint. I am fairly sure that the DICOM **has** been modified by a PACS en route, but suspect that the modification is not severe enough to get the PACS fixed. I am hoping that what ever recent dcm2niix change is tripping on this sort of flaw can be tweaked to continue as it did before.

For better or worse, the problem goes away when the DICOM is anonymized with `dcanon orig anon "nopatientdesc nostudydesc noclinicaltrial nomove keepprivate"`, making it difficult to impossible for me to share DICOM with you that would reproduce the problem. However, we would like to be able to use dcm2niix without running dcanon first, since that mangles the DICOM in a different way.

Example:
```
$ dcm2niix/build/bin/dcm2niix -o . orig
Chris Rorden's dcm2niiX version v1.0.20220923  (JP2:OpenJPEG) GCC4.8.5 x86-64 (64-bit Linux)
Found 16 DICOM file(s)
No valid DICOM images were found
```

**Expected behavior**
```
$ dcm2niix -o . orig
Chris Rorden's dcm2niiX version v1.0.20211006  (JP2:OpenJPEG) GCC4.8.5 x86-64 (64-bit Linux)
Found 16 DICOM file(s)
Warning: All images appear to be a single slice - please check slice/vector orientation
Convert 16 DICOM as ./orig_csf_flow_fl2d_tra_Venc20_20200924072853_12_ph (256x256x1x16)
Warning: Check that 2D images are not mirrored.
Conversion required 0.150304 seconds (0.022767 for core code).
```
The warning is fine, and correct. This really is a time series of a single axial slice. The sequence does not seem to matter much, and I only chose this one because it is small.

A diff of the "original" and anonymized DICOM gave me a suspect: the "original" was modified by Compass/Laurel Bridge when someone took a peek at the image and the window settings were recorded. dcanon removed this clause:
```
(0400, 0561)  Original Attributes Sequence  1 item(s) ---- 
   (0400, 0550)  Modified Attributes Sequence  1 item(s) ---- 
      (0028, 1050) Window Center                       DS: '-28.0'
      (0028, 1051) Window Width                        DS: '4846.0'
      ---------
   (0400, 0562) Attribute Modification DateTime     DT: '20200924082016'
   (0400, 0563) Modifying System                    LO: 'Compass 2.7.6'
   (0400, 0564) Source of Previous Values           LO: ''
   (0400, 0565) Reason for the Attribute Modificati CS: 'COERCE'
```
I have previously seen a matlab library complain about these with "Warning: File and dictionary VR values do not match for attribute
"OriginalAttributesSequence" (0400,0561). Expected: SQ. Found: UN. Consider
setting the 'UseDictionaryVR' parameter to true."

I'm sorry I can't share the triggering data, but I'm hoping the relevant dcm2niix change was recent enough that you know where to look.

Thanks,

Rob

**Comment by neurolabusc** [comment]
Rob,
  Sorry this does not explain the issue. Do the images contain a [thumbnail (00880200)](https://dicom.innolitics.com/ciods/basic-structured-display/structured-display/00880200)? I did change the detection of the GEIIS icon corruption, and it now cares whether sequences have implicit or explicit lengths.


Often logorrheic (`-v 2`) mode helps to understand how dcm2niix parses each tag in a DICOM:

```
dcm2niix -v 2 /path/to/dioms
```

**Comment by captainnova** [comment]
(0088, 0200) is not present.

There was a lot of logorrhea so I diffed it:
```
$ diff -b old.log new.log 
1c1
< Chris Rorden's dcm2niiX version v1.0.20211006  (JP2:OpenJPEG) GCC4.8.5 x86-64 (64-bit Linux)
---
> Chris Rorden's dcm2niiX version v1.0.20220923  (JP2:OpenJPEG) GCC4.8.5 x86-64 (64-bit Linux)
3c3
<  0002,0000 4@140 UL 196 
---
> 196 
281c281
<  7fe0,0010 131072@134198 <131072 bytes> 
---
>  0001,0001 131072@134198 <131072 bytes>
285,286c285,286
<  acq 1 img 1 ser 12 dim 256x256x1x1 mm 0.625x0.625x3.1 offset 134198 loc 0 valid 1 ph 1 mag 0 nDTI 0 3d 0 bits 16 littleEndian 1 echo 1 coilCRC -1715816593 TE 6.22 TR 20.86
<  0002,0000 4@140 UL 196 
---
>  acq 1 img 1 ser 12 dim 256x256x1x1 mm 0.625x0.625x3.1 offset 0 loc 0 valid 0 ph 1 mag 0 nDTI 0 3d 0 bits 16 littleEndian 1 echo 1 coilCRC -1715816593 TE 6.22 TR 20.86
> 196 
```
The pattern starting at 281 repeated at 564, 847, etc....

```
4247,4248c4247,4248
<  acq 1 img 11 ser 12 dim 256x256x1x1 mm 0.625x0.625x3.1 offset 134200 loc 0 valid 1 ph 1 mag 0 nDTI 0 3d 0 bits 16 littleEndian 1 echo 1 coilCRC -1715816593 TE 6.22 TR 20.86
<  0002,0000 4@140 UL 196 
---
>  acq 1 img 11 ser 12 dim 256x256x1x1 mm 0.625x0.625x3.1 offset 0 loc 0 valid 0 ph 1 mag 0 nDTI 0 3d 0 bits 16 littleEndian 1 echo 1 coilCRC -1715816593 TE 6.22 TR 20.86
> 196 
4526c4526
<  7fe0,0010 131072@134204 <131072 bytes> 
---
>  0001,0001 131072@134204 <131072 bytes>
4530,4535c4530,4531
<  acq 1 img 16 ser 12 dim 256x256x1x1 mm 0.625x0.625x3.1 offset 134204 loc 0 valid 1 ph 1 mag 0 nDTI 0 3d 0 bits 16 littleEndian 1 echo 1 coilCRC -1715816593 TE 6.22 TR 20.86
< Converting orig/1.dcm
< Warning: All images appear to be a single slice - please check slice/vector orientation
< Convert 16 DICOM as ./orig_csf_flow_fl2d_tra_Venc20_20200924072853_12_ph (256x256x1x16)
< Warning: Check that 2D images are not mirrored.
< Conversion required 0.125042 seconds (0.028513 for core code).
---
>  acq 1 img 16 ser 12 dim 256x256x1x1 mm 0.625x0.625x3.1 offset 0 loc 0 valid 0 ph 1 mag 0 nDTI 0 3d 0 bits 16 littleEndian 1 echo 1 coilCRC -1715816593 TE 6.22 TR 20.86
> No valid DICOM images were found
```

**Comment by neurolabusc** [comment]
@captainnova you can try out the latest commit. If the pixel data [7fe0,0010](https://dicom.innolitics.com/ciods/rt-dose/image-pixel/7fe00010) tag is missing, but the final tag is large enough to hold the pixel data, the software will assume the final tag is the pixel data. I would not call you images `slightly corrupted`: the tag `0001,0001` is a private tag so it has no formal definition. The  pixel data tag is `Required if Pixel Data Provider URL (0028,7FE0) is not present.` Therefore, I think your source images are invalid. 

Did you mean [dcmanon](https://github.com/ayplam/dicomtools/blob/master/dcmanon.py) instead of `dcanon` or is it a tool I have not heard of. In any case, it seems it is able to rescue your dataset.

Not sure why previous versions of my software succeeded.

**Comment by captainnova** [comment]
Thank you for the amazingly fast turnaround, @neurolabusc, it works!

I don't see (0001,0001), though, and I do see (7fe0,0010).

This is the only 0001 in dcmdump's output:
```
(0002,0001) OB 00\01                                    #   2, 1 FileMetaInformationVersion
```
and the pixel data is immediately after the suspect SQ from Compass:
```
(0400,0561) ?? fe\ff\00\e0\6a\00\00\00\00\04\50\05\20\00\00\00\fe\ff\00\e0\18\00... # 114, 1 Unknown Tag & Data
(7fe0,0010) OW 0800\0800\0800\0800\0800\0800\0800\0800\0800\0800\0800\0800\0800... # 131072, 1 PixelData
```
(dcmdump formatting again. (0400,0561) as unpacked by pydicom was already posted in a previous comment.)

But the solution working without fully figuring out the (unprovided) DICOM just makes it more impressive. I think a lot of users will be glad to skip past dubious DICOM SQs if they can get a reasonable .nii and BIDS .json. The BIDS values appear to be correct in this case.

I'll run this version on my test suite in the next day or two, but it looks good so far.

**Comment by captainnova** [comment]
dcanon is from dicom3tools. I just sent download instructions for a gdcmanonned example to @neurolabusc's institutional email.

Meanwhile, the current development branch passed my regular test suite.

**Comment by neurolabusc** [comment]
Thanks @captainnova I have added a patch that ignores Original Attributes Sequence ([0400,0561](https://dicom.innolitics.com/ciods/cr-image/sop-common/04000561)) Referenced Image Evidence Sequence Attribute ([0008,9092](https://dicom.innolitics.com/ciods/x-ray-3d-craniofacial-image/x-ray-3d-image/00089092)) tags.

This will handle your data appropriately without resorting to my earlier kludge.

**Comment by captainnova** [comment]
Confirmed.

**Comment by jrdalenberg** [comment]
Would it be possible to give the warning referring to this Issue just once? 

I am trying to convert a dicom dataset and for every subject, the console is being overflooded with:

`Assuming final tag is Pixel Data (7fe0,0010) (issue 639)` 

And what should a user do to prevent this?

**Comment by neurolabusc** [comment]
@jrdalenberg if you see this issue multiple times, it suggests that multiple DICOMs in your volume have unexpected pixel data tags. My best guess is some tool that touched these images removed or inserted tags. For example, a PACS that adds a non-DICOM compliant thumbnail or an anonymization tool that is deleting some important tags. I would check the provenance of these images and see if you can ensure that you are creating archival quality, DICOM compliant images. While it sounds like dcm2niix is compensating for these deficiencies, it does hint at a deeper problem. I would first see if an image exported directly off the scanner console exhibits this issue (I doubt it), and then work out the sequence of tools that touch your data. Historically, a common source of this issue was a GEIIS PACS that inserted non-compliant thumbnails into images, with subsequent tools mangling these outputs further and obscuring the root cause.

**Comment by jrdalenberg** [comment]
@neurolabusc Ah thanks. I'll investigate where these unexpected data originate from then. 

Just for reference, the console output for the datasets that I am converting looks like this:

```
Chris Rorden's dcm2niiX version v1.0.20230411  (JP2:OpenJPEG) (JP-LS:CharLS) GCC8.4.0 x86-64 (64-bit Linux)
Found 8106 DICOM file(s)
```
Followed by 8105 lines containing:
```
Assuming final tag is Pixel Data (7fe0,0010) (issue 639)
```
And then:
```
Convert 29 DICOM as ./_T2_TSE_2mm_FS_cor_2mm_loodr_AC_PC_20220426140048_13 (280x320x29x1)
Convert 84 DICOM as ./_SMS_ep2d_diff_mddw_64_Richtingen_p2_1,7_iso_20220426140048_8 (128x128x84x1)
Convert 6552 DICOM as ./_SMS_ep2d_diff_mddw_64_Richtingen_p2_1,7_iso_20220426140048_7 (128x128x84x78)
Convert 220 DICOM as ./_t1_mprage_sag_p2_iso_Gd_MPR_cor_20220426140048_18 (256x256x220x1)
Convert 84 DICOM as ./_SMS_ep2d_diff_mddw_64_Richtingen_p2_1,7_iso_20220426140048_10 (128x128x84x1)
Convert 192 DICOM as ./_t1_mprage_sag_p2_iso_Gd_20220426140048_17 (256x256x192x1)
Convert 41 DICOM as ./_t2_tirm_tra_dark-fluid_20220426140048_6 (256x256x41x1)
Convert 192 DICOM as ./_t1_mprage_sag_p2_iso_Gd_MPR_tra_20220426140048_19 (256x256x192x1)
Warning: Instance Number (0020,0013) order is not spatial.
Unable to determine spatial orientation: 0020,0037 missing (probably not a problem: derived image)
Warning: Unable to determine slice direction: please check whether slices are flipped (derived image)
Warning: Bogus spatial matrix (perhaps non-spatial image): inspect spatial orientation
Convert 84 DICOM as ./_SMS_ep2d_diff_mddw_64_Richtingen_p2_1,7_iso_20220426140048_11 (128x128x84x1)
Convert 15 DICOM as ./_t1_fl2d_sag_voor_hoek_AC_PC_20220426140048_5 (640x640x15x1)
Convert 176 DICOM as ./_t1_mp2rage_sag_p3_iso_FLAWS_20220426140048_14 (240x256x176x1)
Convert 176 DICOM as ./_t1_mp2rage_sag_p3_iso_FLAWS_20220426140048_15 (240x256x176x1)
Convert 176 DICOM as ./_t1_mp2rage_sag_p3_iso_FLAWS_20220426140048_16 (240x256x176x1)
Convert 84 DICOM as ./_SMS_ep2d_diff_mddw_64_Richtingen_p2_1,7_iso_20220426140048_9 (128x128x84x1)
Conversion required 124.505381 seconds (11.898572 for core code).
```

The warning seemed a little excessive :)
