### ISSUE TITLE
updates to defaults ini not as expected

### ISSUE THREAD

**Issue by jmatthews-rotman** [rordenlab/dcm2niix#644]
**Describe the bug**

When I use the "-g o" flag to update the default parameters saved in dcm2nii.ini, some of the parameters I specified and wanted saved are not represented in the ini file, and some parameters I did not specify in my command were added to the ini file. 

For context, I'm preparing scripts at our institute that call on dcm2niix. I was hoping to use the ini file as a way for users to specify their own defaults that could override the dcm2niix flags I choose to include in my scripts. 

**To reproduce**

Here is my terminal history showing:
first: ini contents before I had every purposefully manipulated it (just learned about it!).
second: my attempt to use "-g o" to change the parameter defaults I wanted different than the "-h" documentation implied.
third: ini contents after "-g o" update. Some flags I specified were not updated (-ba, -i), and some I did not specify were updated (isMaximize16BitRange ?= "-l o")

$ cat /home2/jmatthews/.dcm2nii.ini
isGZ=0
isBIDS=1
filename=%f_%p_%t_%s

$ dcm2niix -ba n -f '%n_%s_%p' -g o -i y -z i
Chris Rorden's dcm2niiX version v1.0.20211006  GCC9.4.0 x86-64 (64-bit Linux)
Defaults reset
Saving defaults file /home2/jmatthews/.dcm2nii.ini
Example output filename: 'John_Doe_1_MPRAGE.nii.gz'

$ cat /home2/jmatthews/.dcm2nii.ini
isGZ=1
isMaximize16BitRange=2
isBIDS=1
filename=%n_%s_%p

**Expected behavior**

I expected every parameter specified in the command alongside "-g o" to be represented in the ini file. I expected any parameters not specified in the "-g o" command not to be changed in the ini file. 

Information regarding the ini was minimal in the nitrc wiki. Past github issues had a little more information. 

Two updates I think might help. 
-If it is intentional that only certain parameters can be saved as defaults, it should be clarified somewhere more visible, probably in the "-g" flag description within "-h". If we're able to save parameter defaults though, I see no reason not to be able to adjust any parameter default with an out-of-the-box default setting. 
-The naming of the parameters and their settings in the ini do not match the "-h" documentation. e.g. when "isMaximize16BitRange=2" showed up in my ini, I can only assume from context clues that is related to the "-l" flag and hopefully corresponds to the "o" setting which is the third (assuming the ini settings are zero based) option listed in "-h". Adjusting the ini file to be a list of flags corresponding to the "-h" documentation might be more intuitive to users. Of course, if defaults were only updated in the ini file when specified, it wouldn't be difficult to make the connections.

Somewhat unrelated point: If the legacy dcm2nii used the same ini file name, perhaps the dcm2niix should use a dcm2niix.ini file name? I know at out institute there was a conversation about leaving dcm2nii installed in parallel with dcm2niix to enable legacy pipelines with legacy data. 

**Version**

Please report the complete version string:

Chris Rorden's dcm2niiX version v1.0.20211006  GCC9.4.0 x86-64 (64-bit Linux)

**Comment by neurolabusc** [comment]
@jmatthews-rotman you may want to look at the comments [here](https://github.com/rordenlab/dcm2niix/issues/152) where script developers voiced the opinion that command line tools should not save persistent initialization files that change the output behavior. My initial goal was to allow the user to tune the default behavior similar to [AFNI](https://afni.nimh.nih.gov/pub/dist/doc/program_help/README.environment.html) and [FSL](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FslEnvironmentVariables).

I am glad the previous dcm2niix has proved mature and popular. However, be aware that active development switched from dcm2nii to dcm2niix 6 years ago. Therefore, the older software pre-dates enhanced DICOM, Siemens XA, BIDS and many other changes. I think the main utility of the old software is for archival studies where the data was stored in formats that [pre date DICOM](https://www.dclunie.com/medical-image-faq/html/part4.html). I realize that dcm2niix does operate differently than the older software, and these changes were required to support the consistent behavior required by BIDS. If you must use dcm2nii and dcm2niix on the same computer, and you do not want them to share common properties, you can use the `-g i` to have dcm2niix ignore the defaults file and explicitly set its behavior.
