### ISSUE TITLE
Add manufacturer name for MR Solutions

### ISSUE THREAD

**Issue by halfSpinDoctor** [rordenlab/dcm2niix#648]
**Describe the bug**

Our Varian/Agilent 4.7T preclinical scanner was recently upgraded to MR Solutions. When I convert DICOM output from the scanner, the manufacturer name shows "Philips" instead of "MR Solutions"

`Warning: Found 0018,9087 but manufacturer (0008,0070) unknown: assuming Philips.`

JSON output shows incorrect manufacturer:
`	"Manufacturer": "Philips",`

**To reproduce**

Convert data from MR Solutions system.

**Expected behavior**

Manufacturer should show MR Solutions

**Version**

Please report the complete version string:

Chris Rorden's dcm2niiX version v1.0.20220720  Clang14.0.0 ARM (64-bit MacOS)
v1.0.20220720

**Comment by neurolabusc** [comment]
I think this is a [duplicate of issue 642](https://github.com/rordenlab/dcm2niix/issues/642) that is addressed [in the development branch](https://github.com/rordenlab/dcm2niix/commit/2a9fbe82aaf29bf0830c23a5e44fccea9382ee32). You can test this yourself:

```
git clone --branch development https://github.com/rordenlab/dcm2niix
cd dcm2niix/console
make
./dcm2niix /path/toDICOMs
```

**Comment by neurolabusc** [comment]
@halfSpinDoctor your sequence reports [Diffusion b-value Attribute (0018,9087)](https://dicom.innolitics.com/ciods/enhanced-mr-image/enhanced-mr-image-multi-frame-functional-groups/52009229/00189117/00189087), I would also suggest you confirm that the diffusion b-vectors are correctly extracted. These tend to vary [by manufacturer](https://www.na-mic.org/wiki/NAMIC_Wiki:DTI:DICOM_for_DWI_and_DTI) and perhaps they even do things different for [quadrupeds](https://dicom.innolitics.com/ciods/enhanced-mr-image/enhanced-mr-image-multi-frame-functional-groups/52009229/00189117/00189601). I have not seen any validation datasets, so you may want to validate your equipments behavior.

**Comment by halfSpinDoctor** [comment]
> I think this is a https://github.com/rordenlab/dcm2niix/issues/642
Yes, sorry about this. I just converted on the development branch and works as expected.

> your sequence reports [Diffusion b-value Attribute (0018,9087)](https://dicom.innolitics.com/ciods/enhanced-mr-image/enhanced-mr-image-multi-frame-functional-groups/52009229/00189117/00189087), I would also suggest you confirm that the diffusion b-vectors are correctly extracted

thanks, yes it is a diffusion sequence, and the vectors are _different_ that what we had prescribed on the system. Working to validate this.

**Comment by halfSpinDoctor** [comment]
Quick note, in the conversion in the development branch, the bvecs are all 0's (but the bvals are populated and look correct)

**Comment by neurolabusc** [comment]
bvec definition is often [manufacturer specific](https://www.na-mic.org/wiki/NAMIC_Wiki:DTI:DICOM_for_DWI_and_DTI). Some vendors specify gradients in world space (Philips, Siemens) and others in Physics coordinate space (GE), while the BIDS/FSL convention is for image space. The DICOM public tag [00189601](https://dicom.innolitics.com/ciods/enhanced-mr-image/enhanced-mr-image-multi-frame-functional-groups/52009229/00189117/00189601) is unfortunate as opposite polarities (e.g. [1,0,0] and [-1,0,0]) will create an identical matrix but will have different eddy effects which can be modeled with tools like FSL's Eddy.

**Comment by neurolabusc** [comment]
@halfSpinDoctor if you want the bvecs populated you will either need to submit a pull request or provide sample datasets (you can share data with my [institutional email](https://sc.edu/study/colleges_schools/artsandsciences/psychology/our_people/directory/rorden_chris.php).

**Comment by halfSpinDoctor** [comment]
I will work on a sample dataset for you to look at, thank you! (Juggling a few things right now, probably will not happen until after Thanksgiving break).
