### ISSUE TITLE
Is Siemens XA software still accounting for imaging gradients in reported bvals/bvecs?

### ISSUE THREAD

**Issue by mharms** [rordenlab/dcm2niix#649]
Does anyone know (@eauerbach) if Siemens is still accounting for the impact of the imaging gradients on the reported b-values and b-vectors in a diffusion acquisition in the XA* software line?  The particular XA30 data that I'm looking at currently no longer has the usual +/- 5 variances in reported b-values around the nominal b-values that have been present in the Siemens outputs for a long time (e.g., VBx, VEx).

And if no longer accounting for the imaging gradients in the reported b-values, does that mean Siemens stopped doing the same for the b-vectors as well under XA?

@neurolabusc :  I know its in the code somewhere, but I'm not sure where to quickly look -- Is it easy for you to point out where `dcm2niix` is getting the b-value and b-vector information from the Siemens DICOMs under XA (prior to applying any rotation due to FOV angulation)?  And do you know if Siemens still storing the full tensor somewhere inside its XA DICOMs?

**Comment by neurolabusc** [comment]
@mharms the [Siemens dcm2niix documentation contains details for XA](https://github.com/rordenlab/dcm2niix/tree/master/Siemens#siemens-x-series). As noted in [issue 236](https://github.com/rordenlab/dcm2niix/issues/236) Siemens uses public tags in some cases and private tags in others.

**Comment by mharms** [comment]
So, to summarize here:
"Classic" DICOMs under XA30 use (0019,100c) and (0019,100e) for b-value and "diffusion gradient orientation", respectively. 
Whereas, "Enhanced" DICOMs under XA30 use (0018,9087) and (0018,9089), respectively.
Neither appear to be accounting for the effect of the imaging gradients on the reported b-values any longer (as was the case under the V series).

**Comment by neurolabusc** [comment]
@mharms, the behavior of [V* Siemens DICOMs is described here](https://www.nitrc.org/forum/forum.php?thread_id=6220&forum_id=4703). In general, dcm2nix assume that the DICOMs are truthful. Perhaps now Siemens XA reports the gradient amplitudes that are requested, not applied. However, beyond documenting this change, I am not sure what else we should do.

**Comment by mharms** [comment]
I'm not saying `dcm2niix` is doing anything wrong.  Just documenting the change in behavior.  Clearly, the b-values are no longer being adjusted for the impact of the imaging/crusher gradients.  But harder to tell if that is the case for the reported gradient directions as well.  Do you have any insight @eauerbach?  To deduce that empirically would seemingly require the collection of some dMRI data without any angulation on the same scanner (e.g., Prisma) under both VE11 and XA30, and then compare the reported gradient directions.

**Comment by captainnova** [comment]
> the b-values are no longer being adjusted for the impact of the imaging/crusher gradients.
@mharms, my experience has been that whether or not and how Siemens adjusts b(vec) for reality depends more on where you look than the software version.

In particular note that they quantize `(0018, 9087) Diffusion b-value` to the nearest 50 s/mm^2, and the effect of the imaging/crusher gradients is typically only a few s/mm^2. I only found this out when an ADNI-like sequence was ported from a Prisma (VE) to a Vida (XA11), which has weaker gradients. On one part of the prescribed b=2000 shell the Vida was unexpectedly reporting 1950 in (0018, 9087). It turned out that it was actually getting to 1972 or something like that, so the quantization rounded it down to 1950 and made this variation visible.

To get the full picture you have to use the b-matrix, like this from a Skyra running XA30:
```
(5200, 9230)  Per-frame Functional Groups Sequence   81 item(s) ---- 
   (0018, 9114)  MR Echo Sequence   1 item(s) ---- 
      (0018, 9082) Effective Echo Time                 FD: 91.0
      ---------
   (0018, 9117)  MR Diffusion Sequence   1 item(s) ---- 
      (0018, 9075) Diffusion Directionality            CS: 'BMATRIX'
      (0018, 9076)  Diffusion Gradient Direction Sequence   1 item(s) ---- 
         (0018, 9089) Diffusion Gradient Orientation      FD: [0.10202924907207489, -0.9690888524055481, -0.22462518513202667]
         ---------
      (0018, 9087) Diffusion b-value                   FD: 2000.0
      (0018, 9601)  Diffusion b-matrix Sequence   1 item(s) ---- 
         (0018, 9602) Diffusion b-value XX                FD: 21.0
         (0018, 9603) Diffusion b-value XY                FD: -198.0
         (0018, 9604) Diffusion b-value XZ                FD: -46.0
         (0018, 9605) Diffusion b-value YY                FD: 1881.0
         (0018, 9606) Diffusion b-value YZ                FD: 436.0
         (0018, 9607) Diffusion b-value ZZ                FD: 101.0
```
It's basically the same in VE, minus the enhanced part.

I think (0018, 9089) is the first eigenvector of the matrix, but I'm not sure how imperfections should be reported in (0018, 9087). Not how Siemens is doing it.

Getting the b matrix from GE requires manually starting a log on the console, so it's not in the DICOM.
I asked Philips, and it got noted, but as far as I know it's not available yet.

**Comment by mharms** [comment]
I would say that the software version matters a lot.  In the V series software, b-values are only quantized to +/- 5.  If Siemens has changed the quantization to +/- 50 in XA30, as you state above, then perhaps they are still "accounting for the imaging/crusher gradients", but the coarser quantization/rounding means that effect is no longer as readily apparent in the reported b-values.  If that is indeed the case, then that would suggest that in my "empircal test" that I outlined above, the diffusion gradient orientations, and tensor components themselves shouldn't change between the V and X series software, since quantization/rounding doesn't come into play for those.

Also, in my experience, the V series software does NOT use the (0018,x) fields for reporting diffusion information, nor do "Classic" DICOMS under XA30.  Rather both of those situations use (0019,100c) and (0019,100e) (per above).  The (0018,x) public fields for diffusion information only seem to be used in the "Enhanced" DICOMs under the X series (specifically, XA30, which is what I have access to, but maybe earlier X series software use (0018,x) for their "Enhanced" DICOMs as well).

**Comment by neurolabusc** [comment]
Closing. Thanks for describing this change. dcm2niix reports the values with the same precision (or lack there of) provided by the vendor.
