### ISSUE TITLE
dcm2niix can't find pigz.exe in Windows

### ISSUE THREAD

**Issue by marcelzwiers** [rordenlab/dcm2niix#650]
**Describe the bug**

Pigz.exe is on the windows path but dcm2niix can't find it

**To reproduce**

1. Open a windows command shell
2. Run:

```console
C:\Users\Marcel>set "PATH=%PATH%;C:\Program Files\MRIcroGL\Resources"
C:\Users\Marcel>dcm2niix -v
```

3. Output:

```console
C:\Users\Marcel>dcm2niix -v
Compression will be faster with pigz.exe in the same folder as the executable
Chris Rorden's dcm2niiX version v1.0.20220720  (JP2:OpenJPEG) (JP-LS:CharLS) MSC1900  (64-bit Windows)
v1.0.20220720
```

The pigz executable, however, is present in the same folder:

```console
C:\Users\Marcel>dir C:\"Program Files"\MRIcroGL\Resources\*.exe
Directory of C:\Program Files\MRIcroGL\Resources

18/11/2022  13:06         3,014,656 bet2.exe
18/11/2022  13:06           943,104 dcm2niix.exe
18/11/2022  13:06           328,704 pigz.exe
               3 File(s)      4,286,464 bytes
```

**Expected behavior**

I don't expect that pigz warning message

**Version**

v1.0.20220720 (see also above)

**Comment by neurolabusc** [comment]
Acknowledged. With the Windows operating system pigz.exe must be in the current working directory to be detected. This will be fixed in a future release.

**Comment by neurolabusc** [comment]
@marcelzwiers can you test that the latest development build (v1.0.20221120) fixes your issue? Compiling on Windows is a bit tricky, so you can download the pre-compiled executable by going to the [AppVeyor web page](https://ci.appveyor.com/project/neurolabusc/dcm2niix) and clicking on the `Artifacts` button.

**Comment by marcelzwiers** [comment]
Still the same (I unzipped the AppVeypor files in the Resources folder) :-(
```console
C:\Users\Marcel>set "PATH=%PATH%;C:\Program Files\MRIcroGL\Resources"

C:\Users\Marcel>dcm2niix -v
Compression will be faster with C:\Users\Marcel\pigz.exe in the same folder as the executable
Chris Rorden's dcm2niiX version v1.0.20221120  (JP2:OpenJPEG) (JP-LS:CharLS) MSC1900  (64-bit Windows)
v1.0.20221120
```

**Comment by neurolabusc** [comment]
Unable to replicate. It appears that the copy of dcm2niix in the path `C:\Users\Marcel\dcm2niix` is taking precedence over the copy in ';C:\Program Files\MRIcroGL\Resources\dcm2niix'. You could either explicitly run the latter or copy pigz to the folder C\Users\Marcel

**Comment by marcelzwiers** [comment]
Mhhh, I don't think it did?
```console
C:\Users\Marcel>where dcm2niix
C:\Program Files\MRIcroGL\Resources\dcm2niix.exe

C:\Users\Marcel>dir "C:\Program Files\MRIcroGL\Resources"\*.exe
 Volume in drive C is OS
 Volume Serial Number is E22C-857C

 Directory of C:\Program Files\MRIcroGL\Resources

18/11/2022  13:06         3,014,656 bet2.exe
20/11/2022  16:20         1,159,680 dcm2niibatch.exe
20/11/2022  16:20           948,736 dcm2niix.exe
18/11/2022  13:06           328,704 pigz.exe
               4 File(s)      5,451,776 bytes
               0 Dir(s)  121,035,911,168 bytes free

C:\Users\Marcel>dir *.exe
 Volume in drive C is OS
 Volume Serial Number is E22C-857C

 Directory of C:\Users\Marcel

File Not Found

C:\Users\Marcel>dcm2niix -v
Compression will be faster with C:\Users\Marcel\pigz.exe in the same folder as the executable
Chris Rorden's dcm2niiX version v1.0.20221120  (JP2:OpenJPEG) (JP-LS:CharLS) MSC1900  (64-bit Windows)
v1.0.20221120
```

**Comment by neurolabusc** [comment]
Did you try providing the working directory with your call? 
```
"C:\Program Files\MRIcroGL\Resources\dcm2niix.exe"
```

**Comment by marcelzwiers** [comment]
That works!
```console
C:\Users\Marcel>C:\"Program Files"\MRIcroGL\Resources\dcm2niix -v
Chris Rorden's dcm2niiX version v1.0.20221120  (JP2:OpenJPEG) (JP-LS:CharLS) MSC1900  (64-bit Windows)
v1.0.20221120
```

**Comment by neurolabusc** [comment]
Why don't you try the latest commit (v1.0.20221122). I try to use [the GetModuleFileName](https://stackoverflow.com/questions/1528298/get-path-of-executable) function if pigz is not in the current working directory and the location of dcm2niix can not be determined from the first argument. I did not test for [MinGW ](https://www.mingw-w64.org/) compilation, so we might need to wrap the new code in a `#ifdef _MSC_VER` conditional.

**Comment by marcelzwiers** [comment]
Yes, it all works now :-)
```console
C:\Users\Marcel>C:\"Program Files"\MRIcroGL\Resources\dcm2niix -v
Chris Rorden's dcm2niiX version v1.0.20221121  (JP2:OpenJPEG) (JP-LS:CharLS) MSC1900  (64-bit Windows)
v1.0.20221121

C:\Users\Marcel>set "PATH=%PATH%;C:\Program Files\MRIcroGL\Resources"

C:\Users\Marcel>dcm2niix -v
Chris Rorden's dcm2niiX version v1.0.20221121  (JP2:OpenJPEG) (JP-LS:CharLS) MSC1900  (64-bit Windows)
v1.0.20221121
```
