### ISSUE TITLE
XA30 tags

### ISSUE THREAD

**Issue by huchengMRI** [rordenlab/dcm2niix#651]
I’m using pydicom to read the dicom files from XA30. I have trouble finding the repetition time tag. The usual value of (0018, 0080) returns an error. I guess the TR is probably buried under a certain sequences, do you know what the new tag value associated with TR?
Thank you very much!

Hu

**Comment by huchengMRI** [comment]
I figured it out, the tag value is still (0018, 0080), but it's embedded in (0018, 9112) "MR Timing and Related Parameters Sequence", which is embedded in (5200, 9229) "Shared Functional Groups Sequence". The TR value can be retrieved from dataset[0x52009229].value[0][0x00189112].value[0][0x00180080].value.

**Comment by neurolabusc** [comment]
XA30 is designed to export enhanced DICOM, where multiple slices are stored in a single file. As you have discovered, enhanced DICOMs use hierarchical sequences to store attributes. You may want to try to use [gdcmdump}(https://sourceforge.net/projects/gdcm/files/) or [dcmdump](https://dicom.offis.de/dcmtk.php.en) to inspect your files. These can either report all DICOM tags (and enhanced DICOMs are very verbose), or search for specific tags. For example, you can inspect the [public XA30 datasets you helped develop](https://github.com/neurolabusc/dcm_qa_xa30) with the command:

```
dcmdump +P 0018,0080 myDICOM.dcm
(0018,0080) DS [3516]                                   #   4, 1 RepetitionTime
```

**Comment by huchengMRI** [comment]
Thank you! The dcmdump tool is very handy.
