### ISSUE TITLE
Unknown manufacturer: Hyperfine Inc

### ISSUE THREAD

**Issue by emilljungberg** [rordenlab/dcm2niix#653]
I'm converting some DICOM data acquired on the Hyperfine Swoop (64 mT portable MRI scanner). When I execute `dcm2niix` I get the warning message that the manufacturer is unknown and that it is assuming Philips instead.

To produce this error I executed
```
dcm2niix -o ./ hyperfine_dicoms
```

and the output I get is
```
Chris Rorden's dcm2niiX version v1.0.20220720  Clang13.1.6 ARM (64-bit MacOS)
Found 1 DICOM file(s)
Warning: Found 0018,9087 but manufacturer (0008,0070) unknown: assuming Philips.
...
```
I've tried compiling the development branch and I get the same warning.

If I look at the header of the Hyperfine DICOM files, the manufacturer tag is listed as:
```
(0008,0070) ?? (LO) [Hyperfine Research]                          # 18,1 Manufacturer
```

It is not a major problem, but the .json sidecar will list the manufacturer erroneously as Philips.

Is it possible to add Hyperfine Inc as a known manufacturer?

And of course, thanks for making this great piece of software!

**Comment by neurolabusc** [comment]
This simply reflects the fact the I have never seen a Hyperfine DICOM. dcm2niix attempts to identify [manufacturer specific private tags](https://github.com/rordenlab/dcm2niix/tree/master/BIDS) to populate the BIDS fields. In general, most newer and smaller manufacturers tend to create simpler DICOMs that rely more on public DICOM tags not private tags. However, details like slice timing, phase encoding polarity and diffusion gradient direction are often not provided. If you can provide sample datasets with my [institutional email](https://sc.edu/study/colleges_schools/artsandsciences/psychology/our_people/directory/rorden_chris.php) I would be happy to help. It is exciting to see companies like Hyperfine and MR Solutions filling exciting new niches.

**Comment by neurolabusc** [comment]
Closing: unable to validate support for a manufactuer without concrete exemplars. Hopefully DICOM public tags are sufficient for most modalities.
