### ISSUE TITLE
dcm2niix splits BOLD time series into two nifti files (enhanced DICOM, Siemens Prisma XA30)

### ISSUE THREAD

**Issue by GayathriSatheesh** [rordenlab/dcm2niix#655]
Hello,

I would really appreciate your help with the following issue.

I am using dcm2niix (v1.0.2022072) to convert DICOM data to NIFIT files, however for certain runs it splits the data into two separate NIFTI files, although all the volumes belong to the same BOLD run. This has happened for random runs and for multiple subjects.

Based on previous discussions on this issue [https://neurostars.org/t/dcm2niix-splitting-a-scan-run-into-multiple-files/17659](url), [https://github.com/rordenlab/dcm2niix/issues/599](url), I tried to understand the conflicting tags between the two sets of DICOM images within the same run.

- I renamed the files using their series UID
```$ dcm2niix -r y -f %j/%r.dcm ~/path to dicom```

- It split the data into two files indicating conflicting series UID (it did not follow any particular order of instance number).

- Looking at the DICOM meta data I can see SQs (0008,9092 and 0400,0561) are added that modify the tag (0020,000e), however the final reported value of 0020,000e is the same for both sets of images.
```
$dcmdump +F +P 0020,000E /path/to/DICOM/1.3.12.2.1107.5.2.43.166043.2022110712425775958339397.0.0.0/00221.dcm 
# dcmdump (1/1): /path/to/DICOM/1.3.12.2.1107.5.2.43.166043.2022110712425775958339397.0.0.0/00221.dcm
(0020,000e) UI [1.3.12.2.1107.5.2.43.166043.2022110712131881946101831.0.0.0] #  60, 1 SeriesInstanceUID
(0020,000e) UI [1.3.12.2.1107.5.2.43.166043.30000022112109065569000005343] #  58, 1 SeriesInstanceUID
(0020,000e) UI [1.3.12.2.1107.5.2.43.166043.2022110712425775958339397.0.0.0] #  60, 1 SeriesInstanceUID

$ dcmdump +F +P 0020,000E /path/to/DICOM/1.3.12.2.1107.5.2.43.166043.30000022112109065569000005343/00001.dcm 
# dcmdump (1/1): /path/to/DICOM/1.3.12.2.1107.5.2.43.166043.30000022112109065569000005343/00001.dcm
(0020,000e) UI [1.3.12.2.1107.5.2.43.166043.2022110712131881946101831.0.0.0] #  60, 1 SeriesInstanceUID
(0020,000e) UI [1.3.12.2.1107.5.2.43.166043.30000022112109065569000005343] #  58, 1 SeriesInstanceUID
(0020,000e) UI [1.3.12.2.1107.5.2.43.166043.2022110712425775958339397.0.0.0] #  60, 1 SeriesInstanceUID
```
- I also looked at the study instance UID repeating the same steps.

> - Renaming the dicom images did not split them.
> - However looking at the value of the tags, they seem to be modified differently for the two sets of dicom images

```
$ dcmdump +F +P 0020,000D /path/to/DICOM/1.3.12.2.1107.5.2.43.166043.30000022112109065569000005343/00001.dcm 
# dcmdump (1/1): /path/to/DICOM/1.3.12.2.1107.5.2.43.166043.30000022112109065569000005343/00001.dcm
(0020,000d) UI [1.3.12.2.1107.5.2.43.166043.30000022110709163113100000003] #  58, 1 StudyInstanceUID
(0020,000d) UI [1.3.12.2.1107.5.2.43.166043.30000022112109065569000005345] #  58, 1 StudyInstanceUID
$ dcmdump +F +P 0020,000D /path/to/DICOM/1.3.12.2.1107.5.2.43.166043.2022110712425775958339397.0.0.0/00221.dcm 
# dcmdump (1/1): /path/to/DICOM/1.3.12.2.1107.5.2.43.166043.2022110712425775958339397.0.0.0/00221.dcm
(0020,000d) UI [1.3.12.2.1107.5.2.43.166043.30000022110709163113100000003] #  58, 1 StudyInstanceUID
(0020,000d) UI [1.3.12.2.1107.5.2.43.166043.30000022112109065569000005345] #  58, 1 StudyInstanceUID
(0020,000d) UI [1.3.12.2.1107.5.2.43.166043.30000022110709163113100000003] #  58, 1 StudyInstanceUID

```

- Based on the solution to the issue 599, I also used dcm2niiX development version v1.0.20221121 , which I believe is set to ignore all DICOM tags in the original attributes SQ 0400,561 and SQ 0008,9092, but the exact same result was produced - DICOM images were compressed into two nifti files (indicative of dcm images compressed based on the series UID).

Additionally as a sanity check we also used a matlab script to loop through all the dicoms in a run that splits and output the SeriesInstanceUID. It showed alll the dicom images to have the exact same series UID (1.3.12.2.1107.5.2.43.166043.30000022112109065569000005343).

Incase its useful, attached below in the Google drive is a functional run that gets split into two nifti files.

[https://drive.google.com/drive/folders/1H4WpyKQKFc-HFWZtHenKtsrZW4o_91B8?usp=sharing](url)

I am quite confused as to what might be causing this unwanted behavior. Would really appreciate your comments on the issue.

Thank you.

Gayathri 

Gayathri Satheesh
Research Assistant
Sreenivasan Lab
NYU Abu Dhabi

**Comment by neurolabusc** [comment]
Please test the latest development branch (v1.0.20221127). As you note, this is related to [issue 599](https://github.com/rordenlab/dcm2niix/issues/599). It seems that different SeriesInstanceUID (0020,000e) are described by root as well as the OriginalAttributesSequence (0400,0561) and ReferencedImageEvidenceSequence (0008,9092). My new solution is to use the root if it is available. I have only heard of this issue from your center, so it might be related to a PACS or a version of XA30 without a service pack. I would suggest you work with the Siemens Research Collaboration Manager associated with your center to gain some insight into what is going on. I feel I am just adding a kludge without any understanding of why data is being assigned multiple UIDs.

**Comment by GayathriSatheesh** [comment]
Hello Chris,

Just tested the development branch and it worked beautifully. Thank you so much.

Our center did reach out to Siemens when the problem had occurred earlier. Siemens checked the data and confirmed that all the series have same SerienceInstanceUID.  They said they don't and cannot use different UIDs for the same series. We don't understand how and why dcm2niix reads different UID?

**Comment by neurolabusc** [comment]
@GayathriSatheesh each of your DICOMs contains multiple SeriesInstanceUID (0020,000e) . It is unclear to me if these are inserted by the scanner, or if a hospital PACS system generating new identifiers. If you look at the full output of  dcmdump (e.g. `dcmdump /path/to/dicom/file.dcm > file.txt`) you will see that oneSeriesInstanceUID is at the root level, while others are nested in OriginalAttributesSequence (0400,0561) and ReferencedImageEvidenceSequence (0008,9092) sequences. If you check the provenance of your images you can understand what is happening. For example, if you export a DICOM image directly from the scanner console to a USB memory stick you can remove any PACS from the equation.

**Comment by GayathriSatheesh** [comment]
Thank you for explaining that. The issue definitely requires a closer investigation. I will check the provenance of my image and try to understand what might be generating the new identifiers.
