### ISSUE TITLE
Bruker scanner multi echo data issue

### ISSUE THREAD

**Issue by LenaDorfschmidt** [rordenlab/dcm2niix#662]
Hi, 
I have been trying to convert multi-echo rodent MRI data from a Bruker scanner and am running into issues. 

The error I am seeing is the following:

```
Found 53970 DICOM file(s)
Slices not stacked: echo varies (TE 5.5, 27.5; echo 0, 0). Use 'merge 2D slices' option to force stacking
Slice positions repeated, but number of slices (17994) not divisible by number of repeats (450): missing images?
Warning: Interslice distance varies in this volume (incompatible with NIfTI format).
Unable to equalize slice distances: slice order not consistently ascending.
First spatial position repeated 450 times
Slice positions repeated, but number of slices (17983) not divisible by number of repeats (449): missing images?
Warning: Interslice distance varies in this volume (incompatible with NIfTI format).
Unable to equalize slice distances: slice order not consistently ascending.
First spatial position repeated 449 times
Slice positions repeated, but number of slices (17993) not divisible by number of repeats (449): missing images?
Warning: Interslice distance varies in this volume (incompatible with NIfTI format).
Unable to equalize slice distances: slice order not consistently ascending.
First spatial position repeated 449 times
```

I am using:
`Chris Rorden's dcm2niiX version v1.0.20220720  GCC4.8.5 x86-64 (64-bit Linux)`

I found this issue reporting a similar error message https://neurostars.org/t/incomplete-acquisition-dicom-to-nifti/5398, and saying this may be related to scans being aborted. However, I am not sure this is the case for me: I am receiving the error message above for all my images, and I doubt that all scans have been aborted. I am wondering whether dcm2nii is struggling to recognise the fact this is multi echo data? I noticed it lists only two TEs (and calls each of the echoes '0'?), in` (TE 5.5, 27.5; echo 0, 0)`. We should have three echoes. 

Any advice would be appreciated. 
All the best, 
Lena

**Comment by neurolabusc** [comment]
I have never seen multi-echo data from a Bruker instrument. Is it possible for you to share the problematic dataset with [my institutional email](https://sc.edu/study/colleges_schools/artsandsciences/psychology/our_people/directory/rorden_chris.php)? Bruker has a iconoclastic interpretation of the DICOM standard, and in my experience this can cause issues with PACS systems. So one thought would be to see if you can get the data directly off of the scanner console to ensure that the data is not muddled by being touched by a PACS server.

**Comment by neurolabusc** [comment]
You may also want to encourage your contacts at Bruker to implement the optional [Echo Number](https://dicom.innolitics.com/ciods/mr-image/mr-image/00180086) (0018,0086) to disambiguate echo times.  This allows tools to detect discrete echo times without being concerned about rounding errors with the string based [Echo Time](https://dicom.innolitics.com/ciods/mr-image/mr-image/00180081) (0018,0081) tag.

**Comment by neurolabusc** [comment]
Unable to replicate as I have no exemplars. Please work with the vendor to support the public DICOM tags that disambiguate multi-echo series.
