### ISSUE TITLE
Is SAR Private Information?

### ISSUE THREAD

**Issue by neurolabusc** [rordenlab/dcm2niix#668]
In default mode, dcm2niix excludes private information from the BIDS sidecar it generates. However, if one chooses `-ba n` then the data will not be anonymized and the sidecar will include [private information](https://github.com/rordenlab/dcm2niix/tree/master/BIDS#global-private-information) like `PatientWeight` from DICOM tag 0010,1030.  However, dcm2niix currently does not consider [SAR as personal information](https://github.com/rordenlab/dcm2niix/tree/master/BIDS#modality-magnetic-resonance-imaging).  Since the unit of [SAR](https://radiopaedia.org/articles/specific-absorption-rate) is watts per kilogram (W/kg) it is directly related to patient weight. I realize that weight is only considered personal information in some situations, but it makes me wonder if dcm2niix should only include SAR with the `-ba n` option. 

Based on DICOM chapter E, and [Table E.1-1](https://dicom.nema.org/medical/dicom/current/output/html/part15.html#table_E.1-1) I conclude that the DICOM standard does *not* consider SAR personally identifiable, so the current dcm2niix behavior is justified. However, I wonder if the community agrees. Off the top of my head I am interested if @mharms, @captainnova, @effigies and @satra disagree with my interpretation.

@CPernet this query also related to some [BIDS PET fields](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/09-positron-emission-tomography.html#pharmaceuticals) where weight is implicit in the units (e.g. `mg/kg`)

**Comment by effigies** [comment]
I don't disagree. Exposure of this field seems at most to expose ratios of `PatientWeight`s between subjects, and even that should be assumed to be approximate unless the scanning site collected precise weight data and the wattage of each sequence were known.

That said, reading the radiopaedia entry, this is mostly useful as assurance that participants were not exposed to harmful levels of energy absorption. Is there a situation in which this would be useful public data? If the benefits are low enough, even a low risk of PII exposure might not seem worth it.

**Comment by pvelasco** [comment]
AFAIK, SAR also depends on the loading of the RF coil, which depends on the actual subject's placement inside the coil, tissue distribution, padding, etc. So I really doubt you can derive any identifiable information from the SAR...

**Comment by captainnova** [comment]
Thank you @neurolabusc, I think you have found a new potential PHI leak, and we should not expect the DICOM or HIPAA committees to have thought of everything. (The former used "Patient Weight", but kg as the units!)  I agree with @effigies that it is a low risk and low benefit field. I'm fairly sure that in practice some scanners/sequences adjust their wattages for mass (so SAR would not be simply proportional to 1/mass), and some don't. On the other hand, I would not want straight NIFTI + BIDS users to be completely unaware of SAR. Maybe it should be rounded to the nearest power of 10 when being anonymized? And I really mean power of 10; anyone trying to identify people using this would have to look for extreme outliers, so 200 kg would stand out from 100 kg.

**Comment by neurolabusc** [comment]
Adding to this, Siemens use ([0018,1316](http://dicomlookup.com/lookup.asp?sw=Tnumber&q=(0018,1316))) when exporting data as classic DICOMs, but [0018,9181](http://dicomlookup.com/lookup.asp?sw=Tnumber&q=(0018,9181)) for the same image exported as enhanced DICOM. Extending @pvelasco's comments, for 2D EPI sequences Siemens now calculates SAR independently for different slabs. Consider this [BOLD series](https://github.com/neurolabusc/dcm_qa_xa30/tree/main/In/7_func-bold_task-fa_run-1) with 33 slices and multiband 3 which reports 0018,9181 six times: 0.0632651, 0.280049, 0.297001, 0.928127, 0.800317, 0.356414 for each volume. So SAR is now an array not a scalar number.

**Comment by mharms** [comment]
Per the comments above that mass cannot be directly calculated from SAR (https://github.com/rordenlab/dcm2niix/issues/668#issuecomment-1385900504 and https://github.com/rordenlab/dcm2niix/issues/668#issuecomment-1386043245) keeping SAR included (without rounding) seems fine to me.

**Comment by captainnova** [comment]
Whether or not SAR calculations are difficult to convert to (rough) mass for certain (manufacturer, software version, sequence) combinations does not prove that it can never be done.

It seems to me that studies making data publicly available as NIFTI + anonymous BIDS only should ideally not release individual SARs, and should include e.g. (mean, stddev) SAR for each sequence in their protocol documentation. But that's ideally, and practically this probably won't occur to most people. I mildly favor leaving it out as the default for dcm2niix, but I am also of the opinion that nobody should expect BIDS to be complete (keeping up with scanner software updates is a never ending task). 

There's an opportunity, if it hasn't already been done, for someone to release a script that takes a collection of individual non-anonymized BIDS .jsons as input and outputs (mean, stddev, quantile) BIDS .jsons.

**Comment by neurolabusc** [comment]
I am now leaning to removing this attribute altogether. Users can preserve private details like weight with the `-ba n` option and the fact that now different values are stored for different slices seems to complicate uses. Are there any reasons why we would want to store this? This SAR is not even defined by BIDS, so it is peculiar to the dcm2niix JSON files. Is there a compelling reason to keep this parameter, beyond trying to reduce the variability in the output of dcm2niix?

**Comment by CPernet** [comment]
+1 as having optional the ability to preserve such info but not as default since most people don't look at this 
of topic for PET, the level of exposure is usually not of concern; people who get high doses of something often have a tumour so it's not much of their priority ... and for healthy participants this is highly regulated.

**Comment by captainnova** [comment]
I had happened to mention this, in the context of MR, to a deidentification expert this afternoon, and he told me that research studies using PET usually include PatientWeight because it is needed for dose, attenuation(?), etc. correction. (I am not familiar with the details and may be paraphrasing.)

But back to MR, my guess is most recipients of anonymized BIDS metadata know that less SAR is better, but don't know what constitutes high SAR (0.002, 0.2, ???) and are unlikely to do anything with it. Typically it is handled preventatively; the scanner should refuse to exceed the SAR guideline at scan time.

**Comment by neurolabusc** [comment]
With enhanced DICOM, a single MR series can report multiple different SAR values based on different [definitions (0018,9179)](https://dicom.innolitics.com/ciods/enhanced-mr-color-image/enhanced-mr-color-image-multi-frame-functional-groups/52009229/00189112/00189239/00189179). 

```
  (fffe,e000) na (Item with undefined length #=2)         # u/l, 1 Item
    (0018,9179) CS [IEC_WHOLE_BODY]                         #  14, 1 SpecificAbsorptionRateDefinition
    (0018,9181) FD 0.068333965250363971                     #   8, 1 SpecificAbsorptionRateValue
  (fffe,e00d) na (ItemDelimitationItem)                   #   0, 0 ItemDelimitationItem
  (fffe,e000) na (Item with undefined length #=2)         # u/l, 1 Item
    (0018,9179) CS [IEC_PARTIAL_BODY]                       #  16, 1 SpecificAbsorptionRateDefinition
    (0018,9181) FD 0.30248700341731571                      #   8, 1 SpecificAbsorptionRateValue
  (fffe,e00d) na (ItemDelimitationItem)                   #   0, 0 ItemDelimitationItem
  (fffe,e000) na (Item with undefined length #=2)         # u/l, 1 Item
    (0018,9179) CS [IEC_HEAD]                               #   8, 1 SpecificAbsorptionRateDefinition
    (0018,9181) FD 0.32079685733033934                      #   8, 1 SpecificAbsorptionRateValue
  (fffe,e00d) na (ItemDelimitationItem)                   #   0, 0 ItemDelimitationItem
  (fffe,e000) na (Item with undefined length #=2)         # u/l, 1 Item
    (0018,9179) CS [IEC_LOCAL]                              #  10, 1 SpecificAbsorptionRateDefinition
    (0018,9181) FD 1.002490179157310646                     #   8, 1 SpecificAbsorptionRateValue
```

**Comment by neurolabusc** [comment]
Closing this issue. For the time being, dcm2niix will continue to report classic DICOM SAR (0018,1316) but we will not transcribe the enhanced SAR (0018,9181). This will retain backward compatilibity.
