### ISSUE TITLE
Suggestion: Include some EncodingSteps fields?

### ISSUE THREAD

**Issue by mharms** [rordenlab/dcm2niix#671]
The following is motivated by a comparison of jsons from an `Enhanced` vs. `Interoperability` ("Classic") DICOM export from an XA30 system.

Currently, for Classic DICOMs, we have a field called `PhaseEncodingSteps`, presumably extracted from (0018,0089).

Enhanced DICOMs from XA30 do not appear to populate that field, but have the following 3 fields available instead (this is an example from a 3D structural scan; for a 2D EPI scan, just the first two are populated):
```
(0018,9058) US 320                                      #   2, 1 MRAcquisitionFrequencyEncodingSteps
(0018,9231) US 300                                      #   2, 1 MRAcquisitionPhaseEncodingStepsInPlane
(0018,9232) US 208                                      #   2, 1 MRAcquisitionPhaseEncodingStepsOutOfPlane
```
The suggestion is that we consider adding those 3 to the jsons, possibly named as “FrequencyEncodingSteps”, “PhaseEncodingStepsInPlane”, and “PhaseEncodingStepsOutOfPlane”.

This also raises the issue of whether, as a general principle, `dcm2niix` attempts to "re-use" existing json tags for what is apparently the same information albeit from different DICOM fields, or whether different DICOM fields should get a unique json tag.

This is relevant for (0018,9231), which seems in principle to be the same as (0018,0089) (and thus the already existing `PhaseEncodingSteps` tag). But who knows if that is always the case (and for all vendors).  E.g., one vendor interprets them as identical information, whereas another (rightly or wrongly) interprets one as the actual number of k_y lines acquired and the other as the number of lines after recon).

**Comment by neurolabusc** [comment]
@mharms can you please test out the latest release. According to my source at Siemens 0018,9231 is the explicit enhanced tag that stores what was previously in 0018,0089, therefore it maps directly to the existing `PhaseEncodingSteps` BIDS tag. The fields `FrequencyEncodingSteps` and `PhaseEncodingStepsOutOfPlane` are added as you suggest. I have very few XA30 datasets, so you are ideally placed to validate this solution.

**Comment by mharms** [comment]
This looks fine, although what I have for testing this probably isn't much different from the variations that you already have in https://github.com/neurolabusc/dcm_qa_xa30
