### ISSUE TITLE
PhaseEncodingPolarityGE report incorrectly with GE PROGRES' REV_POL

### ISSUE THREAD

**Issue by mr-jaemin** [rordenlab/dcm2niix#674]
dcm2niix  detect `PhaseEncodingPolarityGE` correctly either reading `Rectilinear Phase Encode` tag [(0018, 9034) (27+ versions)](https://github.com/rordenlab/dcm2niix/tree/master/GE#phase-encoding-polarity) or decoding the private UserDefineDataGE [(0043,102A) here](https://github.com/rordenlab/dcm2niix/blob/bb3a6c35d2bbac6ed95acb2cd0df65f35e79b5fb/console/nii_dicom.cpp#L6819). Sample DICOM datasets & details are documented [here](https://github.com/neurolabusc/dcm_qa_ge/). However, I found an exception. dcm2niix reports `PhaseEncodingPolarityGE` incorrect with the `REV_POL` series from GE diffusion `Distortion Correction (PROGRES)` feature. 

GE PROGRES collects two sets of spin-echo images with opposite phase-encoding polarity.  While the `REV_POL` (reverse polarity) images is internally collected & utilized for distortion correction, DICOM will not be generated by default. With CV `rhdistcorr_ctrl +=16` change, including ABCD study, this `REV_POL` images will be saved as a separate series.

Despite of the correctly reported  `Rectilinear Phase Encode` tag (0018, 9034) in the `REV_POL`, dcm2niix currently reports `PhaseEncodingPolarityGE` and `PhaseEncodingDirection` incorrectly including the development version (v1.0.20230127). I suspect this public tag information was overridden by the private tag (0043,102A). I would suggest that precedence should be given to `Rectilinear Phase Encode` tag (0018, 9034)

[Sample dataset](https://gehealthcare-amer.my.salesforce.com/sfc/p/30000001F94O/a/3a000000YKJa/YH_IXbQtAdA__dq599Yf5tkEsHsimoB82LMfCMcZZSw) consists of 3 series from a single DTI scan with PROGRES:
05_DTI  (Distortion Corrected)
510_ORIG__DTI (UnCorrected Forward polarity)
511_REV_POL__DTI (UnCorrected Reverse polarity)

511_REV_POL__DTI reports
```
(0018,9034) CS [REVERSE_LINEAR]                         #  14, 1 RectilinearPhaseEncodeReordering
```
But, dcm2niix reports incorrectly:
```
"PhaseEncodingPolarityGE": "Flipped",
"PhaseEncodingDirection": "j",
```

Both 510_ORIG_DTI and  05_DTI reports correctly
```
(0018,9034) CS [LINEAR]                                 #   6, 1 RectilinearPhaseEncodeReordering
```
```
"PhaseEncodingPolarityGE": "Flipped",
"PhaseEncodingDirection": "j",
```

**Comment by neurolabusc** [comment]
@mr-jaemin thanks. Please test latest commit to development branch and close if this resolves your issue.

**Comment by mr-jaemin** [comment]
@neurolabusc Thanks Chris! The commit implemented the precedence correctly. But, I realized that the original code implementation with the public tag `Rectilinear Phase Encode tag`(0018, 9034) was swapped:

https://github.com/rordenlab/dcm2niix/blob/865dab86761bbc73f89ea4df6a5655679af28a75/console/nii_dicom.cpp#L5613-L5622

`LINEAR` corresponds to  `PhaseEncodingPolarityGE` = "Flipped"
`REVERSE_LINEAR` corresponds to  `PhaseEncodingPolarityGE` = "Unflipped"

as shown below:

![Slide2](https://user-images.githubusercontent.com/72111485/216383866-af3d8fd8-8ea2-442e-b274-80512e66ff99.jpeg)


The code should be swapped as follows:
```
if (toupper(buffer[lPos]) == 'L')
	d.phaseEncodingGE = kGE_PHASE_ENCODING_POLARITY_FLIPPED;
if (toupper(buffer[lPos]) == 'R')
	d.phaseEncodingGE = kGE_PHASE_ENCODING_POLARITY_UNFLIPPED;
break;
```
We didn't realize this swap bug because the private tag previously overrides the public tag in a correct way until this commit.

**Comment by mr-jaemin** [comment]
Please let me find the GE in-vivo datasets, demonstrating the behavior very soon.

-Prior to 27 version (like DV26), dcm2niix would be still accurate 
-But, 27+ version dataset with the public tag, after above commit, the behavior has changed now.

**Comment by mr-jaemin** [comment]
Here are the visual demonstration using DV26 and RX29 datasets with two dcm2niix versions (v1.0.20230201 and v1.0.20220915):

dMRI_PA:
"SoftwareVersions": "29\\LX\\RX29.1_R01_2111.a", **with** the public tag
`(0018,9034) CS [LINEAR]`
"ConversionSoftwareVersion": "v1.0.20230201", "PhaseEncodingDirection": "j-" (**wrong**)
"ConversionSoftwareVersion": "v1.0.20220915", "PhaseEncodingDirection": "j", (correct)

![Screen Shot 2023-02-02 at 12 55 00 PM](https://user-images.githubusercontent.com/72111485/216407572-c3c37d93-0797-4209-baf8-a87c7e48ed8c.png)

dMRI_AP:
"SoftwareVersions": "29\\LX\\RX29.1_R01_2111.a", **with** the public tag
`(0018,9034) CS [REVERSE_LINEAR]`
"ConversionSoftwareVersion": "v1.0.20230201", "PhaseEncodingDirection": "j" (**wrong**)
"ConversionSoftwareVersion": "v1.0.20220915", "PhaseEncodingDirection": "j-", (correct)

![Screen Shot 2023-02-02 at 12 55 07 PM](https://user-images.githubusercontent.com/72111485/216408270-dec91757-cec5-4177-aa44-97587b0fab05.png)



dMRI_PA
"SoftwareVersions": "27\\LX\\MR Software release:DV26.0_R06_2132.a", **without** the public tag
"ConversionSoftwareVersion": "v1.0.20230201", "PhaseEncodingDirection": "j" (correct)
"ConversionSoftwareVersion": "v1.0.20220915", "PhaseEncodingDirection": "j", (correct)

dMRI_AP
"SoftwareVersions": "27\\LX\\MR Software release:DV26.0_R06_2132.a", **without** the public tag
"ConversionSoftwareVersion": "v1.0.20230201", "PhaseEncodingDirection": "j-" (correct)
"ConversionSoftwareVersion": "v1.0.20220915", "PhaseEncodingDirection": "j-", (correct)

![Screen Shot 2023-02-02 at 1 17 43 PM](https://user-images.githubusercontent.com/72111485/216411793-df15c86a-e825-421c-9f55-3535f8d0b957.png)

**Comment by mr-jaemin** [comment]
> @mr-jaemin the current behavior seems consistent with both dcm2niix and dicm2nii for both GE and Siemens. 

@neurolabusc Could you please confirm that your GE dataset was with version 26 or older? In other word, the `Rectilinear Phase Encode` tag (0018, 9034) doesn't exist. If so, this makes sense.

**Comment by mharms** [comment]
@mr-jaemin : I find it interesting that your first set of images for "dMRI_PA" show a region of pronounced frontal _compression_ in the sagittal view.  That's not what I'd expect for a "PA" polarity scan.

Also, I'm curious if you know if `Linear` and `Reverse_Linear` in (0018,9034) are actually defined by the DICOM standard?  i.e., as a practical matter, can one vendor's coordinate system be such that `Linear` for them is `Reverse_Linear` for another?

**Comment by mr-jaemin** [comment]
@mharms Agreed that images looks different. But, a pair of images with opposite phase encoding polarity (AP/PA or pepolar=0,1 for GE) were collected on the same subject within a single exam. For this thread, let's keep it simple.

Regarding the (0018, 9034), that's a good question. I can find [this](http://dicomlookup.com/lookup.asp?sw=Tnumber&q=(0018,9034)):

> Rectilinear phase encode reordering. Defined Terms: LINEAR CENTRIC SEGMENTED REVERSE_LINEAR REVERSE_CENTRIC

I can't comment on the DICOM standard or other vendors. However,  for GE systems, this tag is well-defined with the CV `pepolar` in diffusion EPI only since 27 version or later such that:
peopolar = 0 --> LINEAR
peopolar = 1 --> REVERSE_LINEAR
as summarized in the above slide.

**Comment by mr-jaemin** [comment]
Also, in dcm2niix, the tag is currently utilized for GE only as shown in the above code.

**Comment by mr-jaemin** [comment]
I wanted to add additional images (clinical DWI images, not DTI) with typical PA/AP distortion:

40005_ORIG_Ax_DWI_fwd_hi_res (PA)
(0018,9034) CS [LINEAR]
![Screen Shot 2023-02-02 at 4 21 18 PM](https://user-images.githubusercontent.com/72111485/216452461-0bbd7cde-77a9-43d5-9518-3a0cf2fe33b7.png)

40006_ORIG_Ax_DWI_rev_hi_res (AP)
(0018,9034) CS [REVERSE_LINEAR]
![Screen Shot 2023-02-02 at 4 21 26 PM](https://user-images.githubusercontent.com/72111485/216452753-6b6b8d64-1eab-4428-a679-ee412b6b6cc9.png)

**Comment by mr-jaemin** [comment]
The latest commit/merge resolved the fix. I have confirmed the below GE phase encoding polarity testing datasets:
- DV26, fMRI (AP/PA, SE-EPI (DistortionMap AP/PA), DTI (AP/PA)
- RX28, DTI with Phase Encoding AP/RL (AP, ORIG, REV_POL)
- DV29, DTI with PROGRES 
- RX29, fMRI, SE-EPI (FieldMap AP/PA), DTI (AP/PA

"ConversionSoftwareVersion": "v1.0.20230201"
