### ISSUE TITLE
Newer version of dcm2niix does not convert dicoms that older version did

### ISSUE THREAD

**Issue by michelevalotti** [rordenlab/dcm2niix#678]
I tried converting some dicoms with the latest version of dcm2niix (v1.0.20220720) and it threw a `No valid DICOM images were found` error.
Downgrading to v1.0.20210317, dcm2niix converted to nifti with no issue.
I have attached one dicom that can be used to replicate the issue.
Thank you!

[example_dicom.dcm.zip](https://github.com/rordenlab/dcm2niix/files/10708005/example_dicom.dcm.zip)

**Comment by neurolabusc** [comment]
Resolved in development branch. You can get a compiled beta copy of the upcoming release by going to [AppVeyor](https://ci.appveyor.com/project/neurolabusc/dcm2niix), selecting your desired operating system and downloading the `artifacts`. Alternatively, you can build yourself on MacOS or Linux:

```
git clone --branch development https://github.com/rordenlab/dcm2niix.git
cd dcm2niix/console
make
```

**Comment by michelevalotti** [comment]
Thank you! Could I ask what the issue was and why it might have worked with the older version?

**Comment by neurolabusc** [comment]
[issue 639](https://github.com/rordenlab/dcm2niix/issues/639) to ignore [Original Attributes Sequence ](https://dicom.innolitics.com/ciods/cr-image/sop-common/04000561).
