### ISSUE TITLE
Slice Timing and PE direction issues.

### ISSUE THREAD

**Issue by jsf-umd** [rordenlab/dcm2niix#679]
We have recently "upgraded" to Siemens XA30 on a PrismaFit and are having 2 issues converting dicoms
1. Siemens MB images report incorrect slice timing for image000001 but not image000002. I believe this was reported elsewhere for XA20, but its still an issue. Minnesota MB images do not seem to have the same problem nor do our older images.

2. The PE direction of Minnesota MB spin echos we use for distortion correction as well as the MB fMRI data are reported with inconsistent directions. Within the same scanning session some AP images are reported as i and the PA image as i- and sometimes an AP image is reported as j- with the PA image as j.  

**To reproduce**
Issue 1
$ dcm2niix -b o -ba n -f DICOMHeader -s y ${PWD}/image000001.dcm
Compression will be faster with 'pigz' installed
Chris Rorden's dcm2niiX version v1.0.20220720  (JP2:OpenJPEG) (JP-LS:CharLS) GCC5.5.0 x86-64 (64-bit Linux)
Warning: Slice timing appears corrupted (range 0..4755, TR=1250 ms)
Conversion required 0.040472 seconds (0.010000 for core code).

Issue 2
$ cd 19-cmrr_se_AP_forMB6_matched_R2.2/
$ dcm2niix -b o -ba n -f DICOMHeader -s y ${PWD}/image000001.dcm
Compression will be faster with 'pigz' installed
Chris Rorden's dcm2niiX version v1.0.20220720  (JP2:OpenJPEG) (JP-LS:CharLS) GCC5.5.0 x86-64 (64-bit Linux)
Conversion required 0.033449 seconds (0.030000 for core code).
$ jq-linux64 '.PhaseEncodingDirection' ${PWD}/DICOMHeader.json
"j-"

$ cd 35-cmrr_se_AP_forMB6_matched_R2.2/
$ dcm2niix -b o -ba n -f DICOMHeader -s y ${PWD}/image000001.dcm
Chris Rorden's dcm2niiX version v1.0.20220720  (JP2:OpenJPEG) (JP-LS:CharLS) GCC5.5.0 x86-64 (64-bit Linux)
Conversion required 0.030893 seconds (0.030000 for core code).
$ jq-linux64 '.PhaseEncodingDirection' ${PWD}/DICOMHeader.json
"i"

$ cd 16-F6_R2.2C_TR1250_V390_Bang_SB/
$ dcm2niix -b o -ba n -f DICOMHeader -s y ${PWD}/image000001.dcm
Chris Rorden's dcm2niiX version v1.0.20220720  (JP2:OpenJPEG) (JP-LS:CharLS) GCC5.5.0 x86-64 (64-bit Linux)
Conversion required 0.043745 seconds (0.040000 for core code).
$ jq-linux64 '.PhaseEncodingDirection' ${PWD}/DICOMHeader.json
"j-"

$ cd 42-F6_R2.2C_TR1250_V373_1_SB/
$ dcm2niix -b o -ba n -f DICOMHeader -s y ${PWD}/image000001.dcm
Compression will be faster with 'pigz' installed
Chris Rorden's dcm2niiX version v1.0.20220720  (JP2:OpenJPEG) (JP-LS:CharLS) GCC5.5.0 x86-64 (64-bit Linux)
Conversion required 0.030792 seconds (0.030000 for core code).
$ jq-linux64 '.PhaseEncodingDirection' ${PWD}/DICOMHeader.json
"i"

**Expected behavior**

These images all have the same PE direction and the results should be identical. The two sets of SEs and the two fMRI series are to my knowledge identical.

Our linux version is a bit old if that matters.
$ uname -r
3.10.0-1160.80.1.el7.x86_64

p.s. TR is also reported incorrectly for the single-band reference image for a Minnesota multiband. Its reported as the Multiband TR so the slice times are much larger than the actual TR but it doesn't give a warning about slice timing like above. This has no impact on our processing but I thought I'd mention it for completeness.

**Comment by neurolabusc** [comment]
Are you exporting data as [enhanced](https://github.com/neurolabusc/dcm_qa_xa30) or [Classic Interoperability](https://github.com/neurolabusc/dcm_qa_xa30i) mode? I have note seen the behavior you describe in either validation datasets, but the classic DICOMs are more impoverished and quirky.

Does using the development release (v1.0.20230210) resolve your issue:

```
git clone --branch development https://github.com/rordenlab/dcm2niix.git
cd dcm2niix/console
make
```

If this does not fix your issue, can you send an example to my [institutional email](https://sc.edu/study/colleges_schools/artsandsciences/psychology/our_people/directory/rorden_chris.php). I also suggest you contact the Siemens Research Collaboration Manager associated with your center to make sure this issue is addressed and that you are on the latest service pack.

**Comment by neurolabusc** [comment]
Thanks for the sample data.

1. I can confirm that the first volume of your fMRI series using the Siemens product sequence on XA30 includes the incorrect single-band times. However, the current stable release of dcm2niix will always look at the second volume for determining slice timing. Therefore, one does not observe this error unless you restrict dcm2niix to only process a single file (`-s y`). Slice timing correction requires multiple volumes, so this issue will not typically impact users of 4D datasets. This is a limitation of your DICOMs, not dcm2niix. You should report this to Siemens for support.
2. I agree that InPlanePhaseEncodingDirection (0018,1312) switches between `column` and `row`, and visual inspection of the images reveals that the EPI distortion agrees with this. I also note that the two volumes are acquired with an extreme oblique angle (38.3 and 45.2 degrees). The latter pushes the image from a canonical axial to coronal alignment. I assume this angulation impacted the phase encoding direction. Again, dcm2niix seems to accurately capture the acquisition parameters.

**Comment by jsf-umd** [comment]
Hello
Thank you. We just switched to XA30 and switched to dcm2niix because afni
didn't work on this set. This is the first subject off the new system so I
was just checking the headers. The PE change was not expected
though, that's a new event.
Sorry for the hassle.
Thanks again.

Jason F. Smith, Ph.D.                   _.--~~~.~-._
Assoc. Research Scientist             .(      ./    ).
Department of Psychology             (        {       ).
University of Maryland College Park ('        / _    ./ )
***@***.***                    ('      .~~~'    /   .}
Rm 1147J BPS building              (    .~~              )
College Park MD, 20742-4411         '~~(        _,,'{{}}'
PH) 301.314.1566                        '..:~~'' {{{}}}

**Comment by neurolabusc** [comment]
@jsf-umd wise to thoroughly check XA30 behavior. You may also want to share experiences with [snug-discuss](https://www.snug-discuss.org/). Please do update me if your Siemens Research Collaboration manager has feedback. XA is a moving target, but it is moving in the right direction.
