### ISSUE TITLE
MP-RAGE conversion for GE wrongly assumes multiframe and fails

### ISSUE THREAD

**Issue by IlonaLipp** [rordenlab/dcm2niix#681]
Hi,

I tried converting an MP-RAGE from a GE scanner (part of the ADNI dataset), and using your package as it is, I get "AttributeError: module 'dicom2nifti' has no attribute 'settings'", the conversion failing.

I managed to trouble-shoot the error and what I found was that the culprit is the function "is_multiframe_dicom(dicom_input)" in common.py. It wrongly concludes that my data are 4D, as the header file (of my 3D anatomical image) possesses the field "PerFrameFunctionalGroupsSequence", even though it is empty.

When I comment out the following two lines from common.py, the conversion works:

#    if "PerFrameFunctionalGroupsSequence" in header:
#        return True

Not sure that this is the best solution to deal with it, I now do get warnings "Removing duplicate slice from series".

I hope you find a way to prevent this issue in the future,
thanks very much for the package,

Ilona

**Comment by neurolabusc** [comment]
Hello, [dicom2nifti](https://github.com/icometrix/dicom2nifti) is a Python script that has no relation to dcm2niix. I suggest you repost your issue to the correct repository.

**Comment by IlonaLipp** [comment]
oh dear, i pasted this in the wrong tab, so sorry!!!
