### ISSUE TITLE
Rows/Columns and NIfTI dimensions

### ISSUE THREAD

**Issue by amwink** [rordenlab/dcm2niix#684]
In a check for correctness I came across this with a Siemens scan (CSA header version 20200219):

$ dcmdump dcm000046.2020021910070624212514784 | grep Rows
(0028,0010) US 256                                      #   2, 1 Rows
$ dcmdump dcm000046.2020021910070624212514784 | grep Columns
(0028,0011) US 232                                      #   2, 1 Columns
$ dcm2niix dcm000046.2020021910070624212514784
Chris Rorden's dcm2niiX version v1.0.20220720  (JP2:OpenJPEG) GCC9.3.0 x86-64 (64-bit Linux)
Found 47 DICOM file(s)
Convert 47 DICOM as /home/data/dicom/tmp/MRI_T2W_MR_Axial_T2_TSE_FatSat-8_Axial_T2_TSE_FatSat_20200219092722_8b (232x256x47x1)
Conversion required 0.035644 seconds (0.035520 for core code).
$ fslinfo MRI_T2W_MR_Axial_T2_TSE_FatSat-8_Axial_T2_TSE_FatSat_20200219092722_8.nii 
data_type       INT16
dim1            232
dim2            256
dim3            47
dim4            1
datatype        4
pixdim1         0.937500
pixdim2         0.937500
pixdim3         3.000000
pixdim4         4.000000
cal_max         0.000000
cal_min         0.000000
file_type       NIFTI-1+

So in the DICOM header it says Rows="256", Columns="232" which would mean the 1st row of the 1st matrix would be 256 pixels, then the second row of 256 pixels, ... until the 232nd row of 256 pixels. Counting 256  rows of size 232 would not work (each next row would be shifted 24 pixels). So it seems like this conversion is the correct one!

The image looks fine in the viewer as well, so I guess in this case that means, that a NIfTI image with a 256x232 matrix would have given a distorted matrix. Is there a DICOM tag which determines that the Rows tag determines dim2 and the Columns tag determines dim1, instead of the more traditionally correct assignment?

If this is a correct conversion, then this is not so much an issue as a puzzle I guess.

**Comment by neurolabusc** [comment]
By default, dcm2niix losslessly reorders/mirrors the columns, rows and slices of data so that the resulting image orientation approximately matches the NIfTI identity matrix ([RAS orientation](http://www.grahamwideman.com/gw/brain/orientation/orientterms.htm)).

You can disable this behavior with the `-x i` argument.

```
  -x : crop 3D acquisitions (y/n/i, default n, use 'i'gnore to neither crop nor rotate 3D acquistions)
```
