### ISSUE TITLE
Consider increasing the number of significant digits in the ImagingFrequency tag

### ISSUE THREAD

**Issue by po09i** [rordenlab/dcm2niix#685]
**Describe the bug**

The `ImagingFrequency` tag of the BIDS Json sidecar has a limited number of significant digits.
<img width="241" alt="Screen Shot 2023-03-03 at 7 47 01 PM" src="https://user-images.githubusercontent.com/47249340/222862731-a3635d28-2f27-4244-b770-d16c113eb3b8.png">

This introduces limitations since that tag only stores the approximate B0 frequency used during a scan. This is very limiting for a particular application I am doing where I need to know the exact frequency used during a scan. 

Since the DICOM tag has the significant digits up to Hz, I was wondering why the `ImagingFrequency` tag is truncated and if there is a good reason for it. If not, I would suggest increasing the number of significant digits to match the source (DICOM) so that no information is loss during the conversion of that tag. 

**To reproduce**

Run dcm2niix on any MRI data. (I tried Siemens and Philips data)

**Expected behavior**

ImagingFrequency tag to have significant digits up to the same level as the original DICOM files.

**Version**

Please report the complete version string:

- Chris Rorden's dcm2niiX version v1.0.20220720  Clang13.0.1 x86-64 (64-bit MacOS)
v1.0.20220720

**Comment by neurolabusc** [comment]
It is unfortunate that both DICOM and BIDS use decimal strings rather than IEEE binary floats for storing many values including imaging frequency [0018,0084](https://dicom.innolitics.com/ciods/mr-image/mr-image/00180084). As [Kernighan and Plauger](https://www.amazon.com/Elements-Programming-Style-Brian-Kernighan/dp/0070341990) note `Floating point numbers are like piles of sand; every time you move one you lose a little sand and pick up a little dirt`.

What value does the input DICOM image provide?
```
dcmdump --search 0018,0084 /path/to/dicom.dcm
```

**Comment by neurolabusc** [comment]
I note that with enhanced DICOM [Transmitter Frequency (0018,9098)](https://dicom.innolitics.com/ciods/mr-spectroscopy/mr-spectroscopy/00189098) is provided as a double precision binary. If you test the developmental branch, you will find enhanced precision, but you may need enhanced DICOM to see optimal precision.

**Comment by po09i** [comment]
Thank you for your quick replies.

> What value does the input DICOM image provide?
> 
> ```
> dcmdump --search 0018,0084 /path/to/dicom.dcm
> ```

(0018,0084) DS [123.260423]                             #  10, 1 ImagingFrequency

Using the development branch, I now see the same precision as the DICOM files:
<img width="273" alt="Screen Shot 2023-03-04 at 9 39 35 AM" src="https://user-images.githubusercontent.com/47249340/222908590-ae5cdc3c-443c-40f6-9d58-170762c28efd.png">

Thanks a lot for the quick fix!
