### ISSUE TITLE
Handle signed 12-bit images with negative values

### ISSUE THREAD

**Issue by neurolabusc** [rordenlab/dcm2niix#688]
This issue is described in [PR687](https://github.com/rordenlab/dcm2niix/pull/687) with a sample validation data set [here](https://github.com/neurolabusc/dcm_qa_12bit). In practice, signed 12-bit integers are rare in DICOM as the bit-storage restrictions mean they provide no advantage over 16-bit integers, MRI magnitude scans only have positive values, and negative values are often encoded with a [rescale intercept](https://dicom.innolitics.com/ciods/ct-image/ct-image/00281052). In practice, many DICOM viewers do not handle this legal format correctly.

**Comment by luissantosHCIT** [comment]
I did a quick conversion of my test adc and t1 datasets and the results look good. I have no reason to believe this change will be an issue for other datasets based on my testing. If something else comes up I will inform you. I think you can close this issue.

Thank you for your help.
