### ISSUE TITLE
Problems with newer Siemens 4D Twist

### ISSUE THREAD

**Issue by tpenzkofer** [rordenlab/dcm2niix#689]
**Describe the bug**

With newer Siemens MRI twist sequences the resulting 4D nifti is not ordered correctly (when scrolling through the timepoints, it scrolls slightly down and rotates quickly through the phases). Older Twist sequences convert fine.

see https://user-images.githubusercontent.com/1944948/224773051-6bbf5186-6fbb-4ee8-954e-c9867e9b6645.mp4

**To reproduce**

1. convert using e.g. "dcm2niix.exe -f "%s_%e_%d" -m y -i n -b y -z i -x i -o <outdir> <dcmindir>"
2. view using nii viewer

**Expected behavior**

A working 4D dicom which scrolls through time not space.

**Output log**

Convert 1300 DICOM as test_nii4\10_1_t1_twist_tra_dyn (192x192x26x50)
Ignoring derived image(s) of series 7 test\0\MR.1.3.12.2.1107.5.2.19.45227.30000022121613301282900000224
Warning: Siemens MoCo? Bogus slice timing (range -1..32800, TR=820 seconds)
Warning: Siemens XA exported as classic not enhanced DICOM (issue 236)

**Version**

Chris Rorden's dcm2niiX version v1.0.20211006  (JP2:OpenJPEG) (JP-LS:CharLS) MSC1900  (64-bit Windows)

**Troubleshooting**

Tried newest Version, no effect. Also tried different NII viewers, same problem. Tried different settings for -x (y,n,i)

**Comment by tpenzkofer** [comment]
Hey, I tried with all versions up to the current development branch (downloaded the artifact) - same result

**Comment by neurolabusc** [comment]
I am unfamiliar with this sequence and can provide no more insight unless you [can share an example datasets with my institutional email](https://sc.edu/study/colleges_schools/artsandsciences/psychology/our_people/directory/rorden_chris.php). The role of your Siemens RCM is to help you with precisely these sorts of situations.

**Comment by neurolabusc** [comment]
I would heed dcm2niix's warning `Siemens XA exported as classic not enhanced DICOM` referencing [issue 236](https://github.com/rordenlab/dcm2niix/issues/236). Be aware that the [XA classic DICOMs are impoverished](https://github.com/rordenlab/dcm2niix/tree/master/Siemens), and that limits the capabilities of any existing or future tool. For archival quality XA data, you really want to export as enhanced data. Does exporting the data as enhanced DICOM resolve your problem?

**Comment by tpenzkofer** [comment]
Thank you for the helpful comments, will investiage further. Please note that the files were not exported at the console but pulled from PACS.

**Comment by neurolabusc** [comment]
@tpenzkofer the latest commit to the development branch should resolve your issue. This issue is specific to the Siemens `fldyn3d1` and requires that XA* images do not use the kludge described in [issue 252](https://github.com/rordenlab/dcm2niix/issues/252) for VE*. Now the volumes are distinguished by [acquisition number (0020,0012)](https://dicom.innolitics.com/ciods/surface-scan-mesh/scan-procedure/00200012) rather than [series number (0020,0011)](https://dicom.innolitics.com/ciods/mr-image/general-series/00200011). This reflects an improvement in Siemens DICOM images across generations.

**Comment by tpenzkofer** [comment]
It works, thank you for that extraordinarily swift response!
