### ISSUE TITLE
DWI file with no bval or bvec

### ISSUE THREAD

**Issue by cmadjar** [rordenlab/dcm2niix#696]
**Describe the bug**

We have some DWI DICOMs files for which the bval or bvec files are not generated by dcm2niix. This is unclear to us as to why this fails in rare occasions. We have some test dataset acquired on phantom scans that we could share with you if that helps figuring out what the issue is.

**To reproduce**

Run dcm2niix on the data sample I can send you. Let me know how you would like me to share that with you. 

**Expected behavior**

Expected having bval and bvec files created along the NIfTI and JSON files.

**Version**

We are using commit [3eeef67e837](https://github.com/rordenlab/dcm2niix/tree/3eeef67e837f193fcaec1091d8f2bcf57c299b49) of dcm2niix that includes a fix you did for a previous issue we reported regarding B1 map files coming from GE or Philips scanners:

```
dcm2niix_dev_3eeef67e837 -v
Chris Rorden's dcm2niiX version v1.0.20221013  GCC9.4.0 x86-64 (64-bit Linux)
v1.0.20221013
```

Also tested the latest version of the development branch and the issue remains for those DWI files.

**Comment by neurolabusc** [comment]
Feel free to share data with my [institutional email](https://sc.edu/study/colleges_schools/artsandsciences/psychology/our_people/directory/rorden_chris.php). dcm2niix is designed to generate bvec files for directional DWI, not for isotropic DWI images. It also requires that the [relevant DICOM tags are preserved](https://www.na-mic.org/wiki/NAMIC_Wiki:DTI:DICOM_for_DWI_and_DTI).

**Comment by cmadjar** [comment]
@neurolabusc I just shared the dataset via Google drive. Let me know if you do not receive it. Thank you!

**Comment by neurolabusc** [comment]
@cmadjar this is a limitation of your DICOM images, not dcm2niix. You can view the headers of these using gdcmdump, dcmdump or simply by running dcm2niix in verbose mode (`dcm2niix -v 2 /path/to/dicoms`). Note the data was acquired on a Siemens 3T Prisma running VE11, therefore [Diffusion details should be in the CSA header](https://github.com/rordenlab/dcm2niix/tree/master/Siemens). The CSA header will be in [private group 0029](https://nipy.org/nibabel/dicom/siemens_csa.html). However, no private tags survive in your DICOM images. I suspect that these details were stripped by some anonymization tool. You need to check the provenance of your images, and get a copy before they were stripped.

**Comment by cmadjar** [comment]
@neurolabusc Thank you for the detailed explanation and for having looked into it :-).
