### ISSUE TITLE
dcm2niix 20220720 misinterprets slicetiming in functional image on GE Signa Premier 

### ISSUE THREAD

**Issue by chrisvriend** [rordenlab/dcm2niix#699]
when running dcm2niix 20220720 on the dicoms of an fMRI scan with sequentially acquired ascending slices, the json files suggests that the slices were acquired interleaved. dcm2niix 2018 does produce the correct slicetiming. 
It's an EPI multiphase acquired on a GE Signa Premier 3T.
We think that this latest version ignores the trigger time tag in the dicom header (0018,1060) and assumes an interleaved order for all EPI multiphase sequences. In GE’s document ‘Slice Timing Information for fMRI’: “The slice order is always Interleaved for EPI multiphase.” but we had to modify the sequence to harmonize it with that from other international sites. 

"Manufacturer": "GE",
"ManufacturersModelName": "SIGNA Premier"

Version 2018: 

"SliceTiming": [
                               0,
                               0.052,
                               0.105,
                               0.157,
                               0.209,
                               0.262,
                               0.314,
                               0.367,
                               0.419,
                               0.471,
                               0.524,
                               0.576,
                               0.628,
                               0.681,
                               0.733,
                               0.786,
                               0.838,
                               0.89,
                               0.943,
                               0.995,
                               1.048,
                               1.1,
                               1.152,
                               1.205,
                               1.257,
                               1.309,
                               1.362,
                               1.414,
                               1.467,
                               1.519,
                               1.571,
                               1.624,
                               1.676,
                               1.728,
                               1.781,
                               1.833,
                               1.886,
                               1.938,
                               1.99,
                               2.043,
                               2.095,
                               2.148     ]

Version 2022:
"SliceTiming": [
                               0,
                               1.1,
                               0.052381,
                               1.15238,
                               0.104762,
                               1.20476,
                               0.157143,
                               1.25714,
                               0.209524,
                               1.30952,
                               0.261905,
                               1.3619,
                               0.314286,
                               1.41429,
                                0.366667,
                               1.46667,
                               0.419048,
                               1.51905,
                               0.471429,
                               1.57143,
                               0.52381,
                               1.62381,
                               0.57619,
                               1.67619,
                               0.628571,
                               1.72857,
                               0.680952,
                               1.78095,
                               0.733333,
                               1.83333,
                               0.785714,
                               1.88571,
                               0.838095,
                               1.9381,
                               0.890476,
                               1.99048,
                               0.942857,
                               2.04286,
                               0.995238,
                               2.09524,
                               1.04762,
                               2.14762                ]

**Comment by neurolabusc** [comment]
@mr-jaemin has the best insight on GE slice timing. The algorithm is described  [here](https://github.com/rordenlab/dcm2niix/tree/master/GE#slice-timing) with sample data [here](https://github.com/neurolabusc/dcm_qa_stc).

For troubleshooting and support, it helps to get the details from the first line when you run dcm2niix, which will look like this:

```
Chris Rorden's dcm2niiX version v1.0.20230411  Clang14.0.3 ARM (64-bit MacOS)
```

I would also suggest seeing if the development branch resolves your issue:

```
git clone --branch development https://github.com/rordenlab/dcm2niix.git
cd dcm2niix/console
make
./dcm2niix ....
```

**Comment by chrisvriend** [comment]
that's Chris Rorden's dcm2niiX version v1.0.20220720  (JP2:OpenJPEG) (JP-LS:CharLS) GCC8.5.0 x86-64 (64-bit Linux).
Running it with the dev version (Chris Rorden's dcm2niiX version v1.0.20230411  GCC11.3.0 x86-64 (64-bit Linux)
) does not resolve it:
"SliceTiming": [
		0,
		1.1,
		0.052381,
		1.15238,
		0.104762,
		1.20476,
		0.157143,
		1.25714,
		0.209524,
		1.30952,
		0.261905,
		1.3619,
		0.314286,
		1.41429,
		0.366667,
		1.46667,
		0.419048,
		1.51905,
		0.471429,
		1.57143,
		0.52381,
		1.62381,
		0.57619,
		1.67619,
		0.628571,
		1.72857,
		0.680952,
		1.78095,
		0.733333,
		1.83333,
		0.785714,
		1.88571,
		0.838095,
		1.9381,
		0.890476,
		1.99048,
		0.942857,
		2.04286,
		0.995238,
		2.09524,
		1.04762,
		2.14762	]

**Comment by mr-jaemin** [comment]
@chrisvriend Here is [the code section](https://github.com/rordenlab/dcm2niix/blob/development/console/nii_dicom_batch.cpp#L6267-L6296) you could modify w.r.t. `isInterleaved` under the EPI Multi-Phase (epi) subsection for your custom dcm2niix as I am not sure how to support this case without affecting other cases.

**Comment by chrisvriend** [comment]
Thanks, we are using RX28. I've 'fixed' it now by just using the json file created with an older version of dcm2niix as i assume that it doesn't affect the nii file itself or am I mistaken?

    "SoftwareVersions": "28_LX_MR_Software_release:RX28.0_R05_2035.a",

**Comment by mr-jaemin** [comment]
> Thanks, we are using RX28. I've 'fixed' it now by just using the json file created with an older version of dcm2niix as i assume that it doesn't affect the nii file itself or am I mistaken?
> 
> ```
> "SoftwareVersions": "28_LX_MR_Software_release:RX28.0_R05_2035.a",
> ```

I would suggest to validate your JSON slice timing with values from [the code](https://github.com/neurolabusc/dcm_qa_ge/blob/master/slicetime.cpp), specifically with HyperBand.

It sounds like you have the documentation 'Slice Timing Information for fMRI' by Brice (@brice82). Please make sure that you understand how Ns/HBfactor = even number handles as Rx28 handles different from older version. 

Could you please share the JSON sidecar information, specifically?
- TR
- Ns
- HBfactor

**Comment by neurolabusc** [comment]
@mr-jaemin I think we can close this issue. The modern version of dcm2niix is correctly detecting the recent GE software. As I understand it, the specific issue here is that user has created a non-standard sequence that overrides the default behavior and there is no way to auto-detect this from the DICOMs. In this situation, the user will need to manually set the slice timing.

**Comment by mr-jaemin** [comment]
> @mr-jaemin I think we can close this issue. The modern version of dcm2niix is correctly detecting the recent GE software. As I understand it, the specific issue here is that user has created a non-standard sequence that overrides the default behavior and there is no way to auto-detect this from the DICOMs. In this situation, the user will need to manually set the slice timing.

Agreed

@chrisvriend please feel free to contact us via email.

**Comment by brice82** [comment]
I agree as well. 
@chrisvriend let us know if you need more information.

**Comment by chrisvriend** [comment]
thank you all for your quick responses! So, not a bug but a custom implemention of the sequence that needs a custom handling.
