### ISSUE TITLE
par/PAR

### ISSUE THREAD

**Issue by fliem** [rordenlab/dcm2niix#70]
Hi guys,
thanks for providing the tool. 
I converted par/rec files to nifti and encountered the following problem: 
our files have a lower case ext: data.rec / data.par
If I pass data.par to dcm2niix (1Nov2016) it creates an empty nii file. It seems to be looking for data.PAR. Linking or renaming the .par file to a .PAR file and passing the .PAR correctly converts the file.

This only occurs on linux systems, not on Mac.

**Comment by neurolabusc** [comment]
I just fixed this in the master branch - specific to Linux as macOS and Windows filenames are not case sensitive.
