### ISSUE TITLE
Field map without magnitude image

### ISSUE THREAD

**Issue by Yingfeng-Zhac** [rordenlab/dcm2niix#710]
Hi, I am new to magnetic resonance data analysis. Recently I used the dcm2niix to convert my dicoms to nifti. In the output fold, I only found one files named gre_field_mapping_20170226112428_3_e2_ph.nii (The json information and all the other nii files you can see below ) . From the FSL FUGUE guide, I need one phase difference image and two magnitude images (one for each echo time). It seems like i only get one phase image. I wonder if this is because of the wrong MRI scan parameter export settings or because of the dcom2nii conversion error, and if i can't get the magnitude images, how can i do the data processing for DTI?

Could  anyone help me
Thank you
Yingfeng
![data-1](https://github.com/rordenlab/dcm2niix/assets/128027566/a67c5a20-c2a1-4e74-bd46-7cb37979dc34)
![data-2](https://github.com/rordenlab/dcm2niix/assets/128027566/201e66a1-d25b-4565-8227-3027c74a6768)
![json information-1](https://github.com/rordenlab/dcm2niix/assets/128027566/79c4a131-866c-4f65-a0f6-c564293fb0f2)
![json information-2](https://github.com/rordenlab/dcm2niix/assets/128027566/30bbbfc9-89de-4e48-9ec4-427cf6ef958a)

**Comment by neurolabusc** [comment]
For the expected DICOM data see [here](https://github.com/neurolabusc/dcm_qa_fmap). There are two things you need to be aware of.  First, when acquiring these images you must make sure that the sequence is set to save **both** the magnitude and field images, as shown in the sequence PDF in the image below. Second, you need to be aware that Siemens will generate an identical instance number [(0020,0013)](https://dicom.innolitics.com/ciods/rt-dose/general-image/00200013) for each echo. This is legal in DICOM, but some archive systems assume they are duplicates and therefore they only store a single file. This is described in [here](https://github.com/neurolabusc/dcm_qa_fmap).  I suggest you work with the Siemens Research Collaboration Manager associated with your center. It is their role to help you set up sequences and help you understand unexpected behavior.

![SiemensPDF](https://github.com/rordenlab/dcm2niix/assets/8930807/e7ce14f3-adf4-4e73-ac99-ad92b7af917a)

**Comment by Yingfeng-Zhac** [comment]
I see. Thanks for your replay.
