### ISSUE TITLE
Need EffectiveEchoSpacing or TotalReadoutTime

### ISSUE THREAD

**Issue by ins0mniac2** [rordenlab/dcm2niix#711]
I have a BOLD EPI dataset from a Prisma_fit system that I am converting and ultimately running fmriprep on. In the past, dcm2niix (versions from 2018 and later) has always extracted TotalReadoutTime from Siemens data, but for this dataset it doesn't, and fmriprep fails as we have B0 field map which it is trying to use. It does not produce EchoSpacing or EchoTrainLength either.

I am not able to share raw dicom data can share other relevant information. If I want to calculate the values and add to the json sidecar file, how do I reliably do so ?

**Comment by neurolabusc** [comment]
The formula for computing this depends on whether your Prisma is running VE11 or XA30.

Here is a validation dataset for [E11](https://github.com/neurolabusc/dcm_qa) and [here is one for XA30](https://github.com/neurolabusc/dcm_qa_xa30). For details see [here](https://github.com/rordenlab/dcm2niix/tree/master/Siemens).

Since I can not view your dataset, I am unable to provide much insight. I suspect that if you use dcmdump or gdcmdump you will observe that many crucial DICOM tags have been stripped from your source data by an over-zealous anonymization stage, e.g. the [CSA header for E11](https://nipy.org/nibabel/dicom/siemens_csa.html). The solution would be to convert a dataset before it has been censored. I believe this reveals a limitation in your images, not dcm2niix.

**Comment by ins0mniac2** [comment]
Thanks @neurolabusc . Looks like it is a limitation of the images. I am trying to manually calculate based on the validation datset notes.

I have 
`"SoftwareVersions": "syngo_MR_E11"`
`"ConsistencyInfo": "N4_VE11C_LATEST_20160120"`

Looks like I need `BandwidthPerPixelPhaseEncode` and `ReconMatrixPE`. I have `ReconMatrixPE` , but don't see `BandwidthPerPixelPhaseEncode` (and header does not have [0019,1028]), but dcm2niix does extract `PixelBandwidth`. Are they the same ? 

I also have access to the pdf file for the sequence.

**Comment by neurolabusc** [comment]
For E11 you can read [BandwidthPerPixelPhaseEncode from the CSA header](https://github.com/rordenlab/dcm2niix/blob/fe2f26005109f396a4f828aa438241f73fc25fe8/console/nii_dicom.cpp#L1486). The should match the bandwidth reported in the PDF:

![bandwidth](https://github.com/rordenlab/dcm2niix/assets/8930807/31e38a4f-ded5-4c2f-8890-ed268d5a1bad)

The Siemens Research Collaboration Manager can help you with the details. Be aware that the BIDS definition of [TotalReadoutTime](https://bids-specification.readthedocs.io/en/stable/glossary.html#objects.metadata.TotalReadoutTime) is not the actual physical readout time.

**Comment by pvelasco** [comment]
Hmm, I seem to recall that the `Bandwidth` reported in the protocol PDF refers to the ReadOut, not the Phase Encoding (PE). The one for the PE is 1/(Echo Spacing), but there are acceleration factors to consider...

**Comment by neurolabusc** [comment]
@pvelasco good point. Another issue for using just the PDF is that it gives the requested not acquired values. Having some insight into [how manufacturers handle rounding of floating point values to integers](https://github.com/rordenlab/dcm2niix/tree/master/GE#total-readout-time) is required for precision. This is really a topic where your Siemens Research Collaboration Manager can provide the required insight.

**Comment by ins0mniac2** [comment]
OK thanks for the insight. One good thing is that we know for sure this sequence did not use acceleration. I am hoping we can get [BandwidthPerPixelPhaseEncode from the CSA header](https://github.com/rordenlab/dcm2niix/blob/fe2f26005109f396a4f828aa438241f73fc25fe8/console/nii_dicom.cpp#L1486) .

**Comment by ins0mniac2** [comment]
This is the output of "gdcmdump -C " when I look for 'BandwidthPerPixelPhaseEncode' 

79 - 'BandwidthPerPixelPhaseEncode' VM 1, VR FD, SyngoDT 4, NoOfItems 0, Data

I haven't worked with this kind of output, but this doesn't look very promising.

**Comment by neurolabusc** [comment]
Closing this issue - this appears to be a limitation of the images, not dcm2niix. Please check the provenance of your images and work with your  Siemens Research Collaboration Manager to resolve.
