### ISSUE TITLE
Questions about reorienting the DWI data

### ISSUE THREAD

**Issue by stepKWyang** [rordenlab/dcm2niix#712]
Dear expert, 
I have a couple of DSI data and have changed the original IMA files _(original.IMA)_ into the NIFTY  files _(original.nii.gz, original.bval, original.bvec, original.json)_ using the Mricrogl. 
when loading the _original.nii.gz_ file in the Mricrogl, the software reported that only 68 of 257 volumes be loaded. 
![image](https://github.com/rordenlab/dcm2niix/assets/134992694/72112cd8-1ff6-4e18-ae87-d53644296107)

Besides, in order to make my data match the orientation of the template, I reoriented my data _(reoriented.nii)_ using the Rotation function listed in  "Import->Tools->Rotation". 
![image](https://github.com/rordenlab/dcm2niix/assets/134992694/79a11f45-cd83-4299-99ab-a26f9977b2a2)

My problem is, when comparing the header of the  _(original.nii)_and the  _(reoriented.nii)_ , the dimension of "Time" changed from 257 to 68.
![image](https://github.com/rordenlab/dcm2niix/assets/134992694/e0ce0424-72c0-408f-a665-81b3d4af5774)

and when loading the _reoriented.nii, original.bval, original.bvec files_ into the DSI studio, the read values of the bval and bvec are also only a part of the original values. 
![image](https://github.com/rordenlab/dcm2niix/assets/134992694/690a3288-d5a6-4870-8e6f-d225c6810337)

I'm confused about what happened during the reorienting process, and if I want to obtain all the bval and bvec values when reorienting my nifty file, what methods can I take?
Any advice will be appreciated.
Best wishes,
Yuanyuan

**Comment by neurolabusc** [comment]
This is the intended behavior.

1. The checkbox `Only initial volumes (load 4D series faster)` in the `Preferences` window allows you to choose whether the software only loads the first few volumes (fast and requiring less RAM) or loads the entire series.
2. You ***never*** want to rotate EPI data (fMRI, resting state, DWI) as slice time correction tools are require slices on disk to match temporal slices. 

Is this an acquisition of a bipedal brain acquired with [head-first supine](https://dicom.innolitics.com/ciods/ct-image/general-series/00185100) or did an operator make an error in setting up the patient position? In general, when you convert a DICOM image to NIfTI using dcm2niix (the tool used by MRIcroGL), you can process the resulting images directly with DSI studio, AFNI or FSL tools.

**Comment by stepKWyang** [comment]
Thanks for your kind and patient reply. 
As all my images are nonhuman primates (Cynomolgus macaques), and there isn't a standard template as MNI in human, and the orientation of different templates may be different, I need to reorient my original data to make the orientation of my data match the template and do the further analysis. Based on this demand, I'm trying to reorient my data using the Mricrogl. 
Could you please give me some advice about rotating the DWI images? 
Thank you so much!
Best wishes,
Yuanyuan

**Comment by neurolabusc** [comment]
I would strongly discourage using the rotate function for diffusion images. The [FSL format](http://justinblaber.org/brief-introduction-to-dwmri/) [bvec files](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FDT/FAQ#What_conventions_do_the_bvecs_use.3F) files are in image space, so if you rotate your images you will need to rotate these as well. The FSL format is unusual as it requires a negative determinant, and will flip column order of the images to enforce this. If these prmates are scanned head-first supine and this is correctly reported in the [DICOMs](https://dicom.innolitics.com/ciods/ct-image/general-series/00185100) you should use the raw data directly from dcm2niix without any issues. 

If you really want to rotate your images, you will probably be best served by writing your own Matlab or Python functions that rotate the images and bvecs while controlling for the determinant. You will want to acquire special diffusion images [to validate your solutions](https://www.nitrc.org/docman/?group_id=880). This is well outside my expertise and the validation/scope of dcm2niix, so please proceed with caution. The scope of dcm2niix is to provide a minimal, lossless translation from manufacturer-specific DICOM to a generic NIfTI/BIDS. You will want to think carefully about how subsequent tools (e.g. Eddy, TOPUP, etc) consider details like slice direction, phase encoding direction, etc.

**Comment by stepKWyang** [comment]
I see, it seems like the DSI studio can reorient both the image and the bval at the same time, I will try it. 
Thank you for your professional advice!
