### ISSUE TITLE
Fail to use dcm2niix v1.0.20230411 to convert DWI DICOM files with Errorcode 139: Segmentation fault (core dumped)) 

### ISSUE THREAD

**Issue by ella09may** [rordenlab/dcm2niix#714]
Hi there,

I got an error when using `BIDScoin` with `dcm2niix` **v1.0.20230411** to convert multimodal DICOM files (T1w, rest-fMRI, and dwi) to BIDS formats. The output folder for DWI is empty while the other two have been completed without any error.

The details of the error can be found below:
```
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2023-05-26 16:34:57 - ERROR | Failed to run:
dcm2niix -b y -z y -i n -l n -f "sub-410001_ses-01_run-1_dwi" -o "/media/zqn/Imaging/test1/bidsfolder/sub-410001/ses-01/dwi" "/media/zqn/Imaging/test1/sourcedata/sub-410001/ses-01/007_oblDTInew"
Errorcode 139:

Segmentation fault (core dumped)
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
```

When I used the `dcm2niix` **v1.0.20220720** in the `MRIcroGL` to convert the DWI DICOM file to Nifti, I successfully got the `.bval`, `.bvec`, `.json`, and `.nii.gz` files as outputs although some warning as below:

```
/home/zqn/Applications/MRIcroGL_linux/MRIcroGL/Resources/dcm2niix -f "%f_%p_%t_%s" -p y -z y -o "/media/zqn/Imaging/test1/bidsfolder/sub-410001/ses-01/dwi" "/media/zqn/Imaging/test1/sourcedata/sub-410001/ses-01/007_oblDTInew"
Chris Rorden's dcm2niiX version v1.0.20220720  (JP2:OpenJPEG) (JP-LS:CharLS) GCC9.4.0 x86-64 (64-bit Linux)
Found 800 DICOM file(s)
Warning: Unable to compute slice times for GE Diffusion
Convert 800 DICOM as /media/zqn/Imaging/test1/bidsfolder/sub-410001/ses-01/dwi/007_oblDTInew_SCH-new_20180707102422_7 (256x256x50x16)
Conversion required 1.640890 seconds (1.640549 for core code).
```

After I change the `dcm2niix` command in `BIDScoin` to `/home/zqn/Applications/MRIcroGL_linux/MRIcroGL/Resources/dcm2niix` in the bidseditor, the converting for DWI files is done without any errors.

Information about my OS: Ubuntu 22.04;
Python environment for running `bidscoin`: `python` v3.8.16, `bidscoin` v4.0.0, `dcm2niix` v1.0.20230411;
`dcm2niix` version when using `MRIcroGL`: v1.0.20220720.
Scanner information: `GE Signa EXCITE`

Qiannan Zhao

**Comment by neurolabusc** [comment]
I would suggest removing BIDScoin from the equation. Can you tell me if the following works:

```
git clone https://github.com/rordenlab/dcm2niix.git
cd dcm2niix/console
make
./dcm2niix -v 2 /path/to/DICOMs/
```
There are multiple ways of installing dcm2niix, but for Linux users you always have to make sure that executables are compatible with your core libraries (or compile them with a [holy build box](https://github.com/phusion/holy-build-box)).

**Comment by neurolabusc** [comment]
Unable to replicate, and no additional feedback. Therefore, I am closing this.
