### ISSUE TITLE
EchoTrainLength

### ISSUE THREAD

**Issue by mharms** [rordenlab/dcm2niix#717]
Not sure if this was intentional or not, but it appears that `v20230411` no longer reports the `EchoTrainLength` for certain sequences (e.g., T2 SPACE, and 2D TSE), whereas it did in a previous development version (`v20230127`).

**Comment by neurolabusc** [comment]
@mharms can you share an example dataset that exhibits this change. For enhanced DICOMs we should now expect [Gradient Echo Train Length 0018,9241](https://dicom.innolitics.com/ciods/enhanced-mr-color-image/enhanced-mr-color-image-multi-frame-functional-groups/52009229/00189112/00189241) whereas for classic DICOM we expect [Echo Train Length(0018,0091)](https://dicom.innolitics.com/ciods/mr-image/mr-image/00180091).

**Comment by mharms** [comment]
Well, you wouldn't expect that for non gradient echo sequences, such as T2 SPACE and TSE, right?

FWIW, Siemens still populates (0018,0091) for GRE sequences in its Enhanced DICOMs, so I'm not sure if switching to using (0018,9241) for GRE sequences was necessary (although it quite possibly is also harmless, assuming that 0018,0091 and 0018,9241 are always the same, when they both exist.

**Comment by neurolabusc** [comment]
I have updated the development branch to only use 0018,9241 if it is greater than 1. This field is specific to dcm2niix, and is not (yet) defined in BIDS. Siemens uses both the classic DICOM generic tag (0018,0091) as well as the modern tags (0018,9240; 0018,9241). As I recall, other manufacturers provide only one or the other. Below is an example from a [Siemens TSE sequence](https://github.com/neurolabusc/dcm_qa_cs_dl). Perhaps in future, dcm2niix should explicitly report both `RFEchoTrainLength` and `GradientEchoTrainLength` to mirror the new enhanced DICOM tags. If this is desired, I think they should first be added to the formal BIDS specification.

```
(0018,0091) IS [17] #   2, 1 EchoTrainLength
(0018,9240) US 17  #   2, 1 RFEchoTrainLength
(0018,9241) US 0  #   2, 1 GradientEchoTrainLength
```

I am closing this for now, but happy to update dcm2niix to reflect the evolving BIDS standard.

**Comment by mharms** [comment]
Thanks!
