### ISSUE TITLE
our mp2rage is sending an additional T1 reconstruction that is causing problems

### ISSUE THREAD

**Issue by marcomeixner** [rordenlab/dcm2niix#719]
Dear Chris, dear users,

since a month or so our mp2rage is sending an additional T1 reconstruction that is causing problems. It is 141 MB in size, while the 'normal' T1 is just around 40 MB in size.

dcm2niix works to some degree, but gives this output:
Found 176 DICOM file(s)
Warning: Unable to determine manufacturer (0008,0070), so conversion is not tuned for vendor.
Unable to determine spatial orientation: 0020,0037 missing (probably not a problem: derived image)
Warning: Unable to determine slice direction: please check whether slices are flipped (derived image)
Warning: Bogus spatial matrix (perhaps non-spatial image): inspect spatial orientation
Convert 176 DICOM as ./_T1qA_mp2rage-leipzig_A-1_KS-s-a-1-1-3-88-1010103D-3-5000_20230603102630_30 (512x546x176x1)
Conversion required 157.700311 seconds (0.919583 for core code).

The produces json file therefore is very short:
{
	"Modality": "MR",
	"InstitutionName": "NIC",
	"InstitutionAddress": "deleted",
	"StationName": "MRC35213",
	"ProcedureStepDescription": "Kopf KKNW",
	"SeriesDescription": "T1qA_mp2rage-leipzig_A-1_KS-s-a-1-1-3-88-1010103D-3-50_T1_Images",
	"ProtocolName": "T1qA_mp2rage-leipzig_A-1_KS-s-a-1-1-3-88-1010103D-3-5000",
	"ImageType": ["DERIVED", "PRIMARY", "T1 MAP", "DIS3D", "GSPS", "MFSPLIT"],
	"RawImage": false,
	"SeriesNumber": 30,
	"AcquisitionTime": "11:43:55.295000",
	"SliceThickness": 1,
	"ConversionSoftware": "dcm2niix",
	"ConversionSoftwareVersion": "v1.0.20211006"
}

Image type in the 'normal' T1 is:
"ImageType": ["DERIVED", "PRIMARY", "T1 MAP", "DIS3D", "MFSPLIT"],

And the nii that is generated behaves weird in the sense that when opened with MRIcro the orientation is different and the colors are fixed:
![grafik](https://github.com/rordenlab/dcm2niix/assets/85572783/8740004c-96e8-42b3-a334-b7532422eebc)

Sorry for posting this here, but maybe someone has an idea what might be happening or a better place to post this.
I also contacted Tobias Kober.

Thanks for any help and best wishes,

Marco

**Comment by neurolabusc** [comment]
@marcomeixner feel free to share a sample dataset to [my institutional email](https://sc.edu/study/colleges_schools/artsandsciences/psychology/our_people/directory/rorden_chris.php), however, this seems like a limitation of your DICOM images and not dcm2niix. The [image orientation (0020,0037)](https://dicom.innolitics.com/ciods/mr-image/image-plane/00200037) is crucial to determining the alignment of your images. Also, details like manufacturer are missing which are crucial for interpreting properties. I suggest tracing the provenance of these images - I assume some overly aggressive anonymization step has stripped out vital details.

**Comment by neurolabusc** [comment]
@marcomeixner I also notice that the image type reports being `derived` and that a colorbar is burned into the image. While your anonymization tool has removed the manufacturer, is it possible that this derived image was created by a Siemens MR scanner? If so, you will need to work with your Siemens Research Collaboration Manager to resolve this. Many Siemens derived images intentionally remove the image orientation (0020,0037) details as the derived images are intended for visual inspection only, not subsequent analyses. If I am correct, this reflects a limitation of your DICOMs, not dcm2niix.
