### ISSUE TITLE
Ability to control split by acquisition number

### ISSUE THREAD

**Issue by kretes** [rordenlab/dcm2niix#721]
**Describe the bug**

Unexpected behaviour of dcm2niix for multiple acquisition numbers. 

**To reproduce**

I am using dcm2niix to convert dicoms done in a contrast-enhanced abdominal study with multiple contrast phases being recorded in same dicom series, varying in 'Acquisition Number'.

Running on an example dicom dir what I get is this output:
```
~/ext/dcm2niix -f %f_%s_%z -o tmp/dcm2niix_out2 b550/2
Chris Rorden's dcm2niiX version v1.0.20230609  (JP2:OpenJPEG) (JP-LS:CharLS) GCC8.4.0 x86-64 (64-bit Linux)
Found 553 DICOM file(s)
Convert 1 DICOM as tmp/dcm2niix_out2/2_1_ (888x966x1x1)
Convert 80 DICOM as tmp/dcm2niix_out2/2_2_ (512x512x80x1)
Slice positions repeated, but number of slices (469) not divisible by number of repeats (3): missing images?
Warning: Instance Number (0020,0013) order is not spatial.
Warning: Interslice distance varies in this volume (incompatible with NIfTI format).
Warning: Missing images? Expected 469 images, but instance number (0020,0013) ranges from 366 to 367
Convert 469 DICOM as tmp/dcm2niix_out2/2_3_ (512x512x469x1)
Conversion required 17.634517 seconds (1.363044 for core code).
```

and the effect is unexpected volume `tmp/dcm2niix_out2/2_3_` that contains interleaved slices from multiple acquisitions. At the same time - In the json files I see the following acquisition nnumbers:
```
grep AcquisitionNumber tmp/dcm2niix_out2/*.json
tmp/dcm2niix_out2/2_1_.json:    "AcquisitionNumber": 1,
tmp/dcm2niix_out2/2_2_.json:    "AcquisitionNumber": 1,
tmp/dcm2niix_out2/2_3_.json:    "AcquisitionNumber": 2,
```

while in reality there are the following counts of slices per series and acquisition:
series=3, acq=1  count=205
series=3, acq=2  count=161
series=3, acq=3  count=103
series=2, acq=1  count=80
series=1, acq=1  count=1

I thought that it might be the case of not adding '%u' to the output file name but the result is the same with it. I've looked at https://github.com/rordenlab/dcm2niix/issues/526 but this describes different case.

My expectation would be that:
1. if there are multiple acquisitions per series it should be either a) detected or b) up to the user to decide if they should be splitted or combined. 
2. My feeling is that here it could be detected that they ought to be splitted, because each acquisition covers a different region. It seems that when this `Slice positions repeated, but number of slices (469) not divisible by number of repeats (3): missing images?` happens - maybe the decision should be to split it or at least give a hint to the user on how to obtain this eg. `Did you mean to split each acquisition in a separated nifti file? if so add option -xyz to command line args`

**Version**

Chris Rorden's dcm2niiX version v1.0.20230609  (JP2:OpenJPEG) (JP-LS:CharLS) GCC8.4.0 x86-64 (64-bit Linux)

**Comment by neurolabusc** [comment]
@kretes the NIfTI format was designed for popular brain imaging measures, and it is popular because it is simple. This simplicity arises because it is constrained: all 3D volumes in 4D time series must have the same dimensions and orientation, all 2D slices in a 3D volume must have the same dimensions, orientation and must be equidistantly spaced. Many DICOM MR and CT acquisitions do not conform to these requirements. Feel free to send a sample dataset to my [email](https://sc.edu/study/colleges_schools/artsandsciences/psychology/our_people/directory/rorden_chris.php). However, my gut instinct is that NIfTI is not a good representation for your data, and you should consider DICOM tools for your application.
