### ISSUE TITLE
images appear to be a single slice - WARNING as well

### ISSUE THREAD

**Issue by chopraamhk** [rordenlab/dcm2niix#724]
Hi, 

I am using dcm2niix (Latest version - v1.0.20230411). I am trying to convert my dicom images to nifti using 

dcm2niix -z y -f %p_%t_%s -o output_dir input_dir

It is converting my  dicom images to nifti but all images appear to be a single slice and it is giving me warning. I need my dimensions in xyzt but Why am i getting 1 here and why are all the images are appearing to be a single slice??? 

Found 100 DICOM file(s)
Warning: All images appear to be a single slice - please check slice/vector orientation
Convert 100 DICOM as /output (240x196x1x100)
Conversion required 0.556236 seconds (0.556104 for core code).

Thank you. 

Regards, 
Mehak

**Comment by neurolabusc** [comment]
@chopraamhk the most likely reason is that the DICOM tag [patient position (0020,0032)](https://dicom.innolitics.com/ciods/mr-image/image-plane/00200032) does not correctly specify spatial details. You can check this with dcmdump or gdcmdump. You should check the provenance of your image, perhaps some anonymization tool removed these critical details.

**Comment by chopraamhk** [comment]
Thank you for the response @neurolabusc ..
