### ISSUE TITLE
List DICOM issues to channel to manufacturers

### ISSUE THREAD

**Issue by yarikoptic** [rordenlab/dcm2niix#728]
@neurolabusc please join me in the fun of filling out https://docs.google.com/spreadsheets/d/1wcal4qi2z14bSKm7lTuqyzb3FdvmCDfXHl0iMhIFeaE/edit#gid=0 spreadsheet to first collect the issues we should talk to manufacturers about so they do express that metadata in the exported DICOMs.

**Comment by neurolabusc** [comment]
@yarikoptic I have added some details. Others may want to extend this.
