### ISSUE TITLE
Localizer not ignored with option -i

### ISSUE THREAD

**Issue by agarcia-ruiz** [rordenlab/dcm2niix#731]
Hi, first of all, thanks for the best DICOM converter out there!

While converting some CT scans with the parameter -i y, I found a localizer in the output that was not ignored (other derived images were ignored).

The command options:
`-m y -e n -w 1 -i y -f %s-%d `

**Output log**

```
Chris Rorden's dcm2niiX version v1.0.20230411  (JP2:OpenJPEG) (JP-LS:CharLS) GCC8.4.0 x86-64 (64-bit Linux)
Found 1035 DICOM file(s)
Ignoring derived image(s) of series 80456 ...
Gantry Tilt based on 0018,1120 0, estimated from slice vector -45
Warning: Note these images have gantry tilt of -45 degrees (manufacturer ID = 3)
Convert 6 DICOM as ... (512x768x2x3)
```

In the output json I can find "ImageType": ["ORIGINAL", "PRIMARY", "LOCALIZER", "ES"].
Note the output image is 512x768x2x3, merging a coronal and sagittal views.

Running -m n gives the views in two separate files, and these additional lines:
```
Slices not stacked: orientation varies (vNav or localizer?) [1 0 0 0 0 -1] != [0 1 0 0 0 -1]
Warning: All images appear to be a single slice - please check slice/vector orientation
```

From the ImageType I can filter out the localizers, but I wonder how are these identified internally and why they were kept in this case.

Thanks in advance,

**Comment by neurolabusc** [comment]
Either share an example dataset with me [institutional email](https://sc.edu/study/colleges_schools/artsandsciences/psychology/our_people/directory/rorden_chris.php) or simply ignore localizer data. dcm2niix is more widely used for MR than CT, so you need to convert CT data with care.
