### ISSUE TITLE
Unable to determine slice times for early GE HyperBand,the output folder doesn't generate any files

### ISSUE THREAD

**Issue by zhanghuanfmri** [rordenlab/dcm2niix#734]
Our data is collected using GE scanner (HyperBand). I used dcm2niix to convert the specific time point data  and use the -n command.

`import os

def dicom_to_nii(dist_dir, nii_dir, file_name):
    os.system('chcp 65001')
    os.system(r'D:\MRIcroGL\MRIcroGL\Resources\dcm2niix -b n -n 2 -o {1} -f {2} {0} '
              .format(dist_dir, nii_dir, file_name))

if __name__ == "__main__":
    dist_dir = r'F:\fingermotor\e359\dicom\s3794'
    nii_dir = r'F:\fingermotor\e359\NII_dcm2nii'
    file_name = '002'
    dicom_to_nii(dist_dir, nii_dir, file_name)`

But **the output folder doesn't generate any files** and prompts a warning:**Unable to determine slice times for early GE HyperBand**. However, when the -n command is not used,
`os.system(r'D:\MRIcroGL\MRIcroGL\Resources\dcm2niix -b n  -o {1} -f {2} {0} '
              .format(dist_dir, nii_dir, file_name))`
the warning also exists, but a file containing all time points can be generated.

So how can I generate a nii file at a specific point in time? This is very important to my research. I look forward to your answer, thank you.

**Comment by mr-jaemin** [comment]
Based on the warning message, "Unable to determine slice times for early GE HyperBand", you have fMRI datasets collected with software release DV25 or earlier with HyperBand, which unfortunately slice times cannot be reliable extracted. 

You can confirm the software release from either the JSON file from dcm2niix like this below:
``
	"SoftwareVersions": "30\\LX\\SIGNA_LX1.MR30.1_R01_2322.c", 
``
or DICOM tag:
``
(0018,1020) LO [30\LX\SIGNA_LX1.MR30.1_DA_2312.g]       #  32, 3 SoftwareVersions
``

If you have dataset with 26 or later, please share a sample DICOM here:
https://gehealthcare.ent.box.com/f/3e5433ace5184a82850c6d00f8ca0d14

**Comment by neurolabusc** [comment]
@zhanghuanfmri the `-n` parameter is a very advanced feature that does not do what you want. This feature converts an entire series, so all volumes in a 4D fMRI time series. Note that with this option you provide the CRC-code of the series UID, not the series number. The rationale of this feature is for FSLeyes and MRIcroGL to load and view a single series when a user drops a DICOM folder that has many different series. You use this feature by first providing a negative value: `dcm2niix -n -1 /path/to/DICOMs` - dcm2niix will respond by providing one line per series that includes series details as well as the CRC code, you subsequently convert the desired series by providing the code, e.g. `dcm2niix -n 3079816820 /path/to/DICOMs`.

The [SliceTiming](https://bids-specification.readthedocs.io/en/stable/glossary.html#objects.metadata.SliceTiming) is stored in the BIDS JSON file. If you only want the slice timing, without the imaging data you can run `dcm2niix -b o /path/to/DICOMs` to `o`nly create the bids file. 

Alternatively, if you run `dcm2niix -b y /path/to/DICOMs` you will get **both** the bids file with the SliceTiming as well as the entire 4D timeseries as a NIfTI image - you can always use [fslsplit](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/Fslutils) to extract a single 3D volume.

**Comment by mr-jaemin** [comment]
For future reference, if you have data collected with MR30 version on GE HealthCare scanners and receive an warning message "Unable to determine slice times for early GE HyperBand", please update your dcm2niix to v1.0.20220915 or later as MR30 version string format has changed (see #634 for details) and the SliceTiming extractions requires version information.
