### ISSUE TITLE
Empty values?

### ISSUE THREAD

**Issue by nilgoyette** [rordenlab/dcm2niix#735]
I wonder if it's possible for dcm2niix to produce empty values, such as

    "BodyPartExamined": "",

I checked several json and I think that the line is simply not added when the value is empty. Can you please confirm this?

**Comment by neurolabusc** [comment]
Precisely. [JSON text fields are only populated if they are not empty](https://github.com/rordenlab/dcm2niix/blob/fe2f26005109f396a4f828aa438241f73fc25fe8/console/nii_dicom_batch.cpp#L1038). A missing field could either indicate that the DICOM file did not include [0018,0015](https://dicom.innolitics.com/ciods/cr-image/general-series/00180015) or that 0018,0015 was empty in the DICOM.

**Comment by nilgoyette** [comment]
Perfect. Thank you @neurolabusc
