### ISSUE TITLE
GE non-HFS DTI

### ISSUE THREAD

**Issue by mr-jaemin** [rordenlab/dcm2niix#737]
While current dcm2niix generates the following message for GE non-HFS (i.e. feet-first) DTI, 
"GE DTI directions require head first supine acquisition"
Diffusion gradient vector (*.bvec) will be generated without any required conversion. So, bvec will be inaccurate as shown below

This [PR #736](https://github.com/rordenlab/dcm2niix/pull/736) enables the geCorrectBvecs() routine for GE non-HFS DTI with the following warning message:
"Limited validation for non-HFS (Head first supine) GE DTI: confirm gradient vector transformation"

The bvec conversion for non-HFS would be same as HFS on GE based on [this validation dataset](https://gehealthcare-amer.my.salesforce.com/sfc/p/30000001F94O/a/3a000000YL6c/3fX_agno5e94ADHAdZm22o8khDG78SDpYh1eQgrSLzQ):
Both Head-first and feet-first Knee DTI with both freq. encoding directions: RL and AP collected on the same volunteer within the same exam.

I tested several non-HFS DTI with the proposed change and didn't notice any issue. But, I keep the above warning message to be safe until we fully validate this kind of non-HFS DTI.
   

![Screenshot 2023-08-07 at 3 49 32 PM](https://github.com/rordenlab/dcm2niix/assets/72111485/56381b77-0117-42f4-a2bf-8e7c4093db4d)

**Comment by neurolabusc** [comment]
Thanks. This fix is applied to the development branch.

**Comment by mr-jaemin** [comment]
dcm2niix (v1.0.20230807+) supports feet-first GE DTI
