### ISSUE TITLE
future-proof BidsGuess

### ISSUE THREAD

**Issue by yarikoptic** [rordenlab/dcm2niix#739]
why not to have instead of 

	"BidsGuess": ["anat","_acq-tse2_run-3_PDw"],

a

	"BidsGuess": {
            "datatype": "anat",
            "filename_suffix": "_acq-tse2_run-3_PDw",
            "entities": {"acq": "tse2", "run": "3"},
            "suffix": "PDw"
        },

so it would make it easier and more robust for underlying tools, happen you decide to e.g. add some extra metadata field  (e.g. "subject" which is available in DICOM or "accession" to be used for a session happen someone desires).

`"filename_suffix"` is just a convenience composition from `"entities"` and `"suffix"`.  Having those entities separate would facilitate reuse (e.g. in [heudiconv](https://github.com/nipy/heudiconv/issues/697)) without adding ad-hoc splitting logic.

**Comment by neurolabusc** [comment]
This issue refers to the [experimental BidsGuess](https://github.com/rordenlab/dcm2niix/tree/development/BidsGuess) feature found in the latest development branch of dcm2niix. I certainly appreciate community input, and am happy to modify the behavior if there is a consensus in the community.

One thing I do not like with your suggestions it redundancy which can lead to conflict (e.g. what gets precedence if items in the `filename_suffix` do not match items in `entities` or `suffix` list. A feature I like with the current implementation is that it makes the order of items very clear. BIDS and the bids-validator are very specific regarding not only the presence and absence of entities, but also their order.

I do think a couple of lines of Python will parse the values you want from the current structure:

```
import json
jsonFile = open('bids.json', 'r')
values = json.load(jsonFile)
jsonFile.close()
datatype = values['BidsGuess'][0]
str = values['BidsGuess'][1].split("_")
str.remove("")
suffix = str.pop()
entities = dict(s.split('-') for s in str)
print(suffix)
print(entities)
```
