### ISSUE TITLE
Philips B1 map (using Dual TR) to nifti conversion error

### ISSUE THREAD

**Issue by sandeepganji** [rordenlab/dcm2niix#743]
One way to obtain the Philips B1 map is to use a dual TR Actual Flip angle Imaging (AFI) protocol. That generates 4 sets of NSlices images (number of slices) which are
First set of NSlices images - Magnitude images (with TR1)
Second set of NSlices images - Magnitude images (with TR2)
Third set of NSlices images - Magnitude B1 map images (in %)
Fourth set of NSlices images - Phase B1 map images (in mradians)

Bug:
When using the dcm2niix conversion, with comannd ```dcm2niix.exe -f "%s_%d_%z" -p y -z y -ba n ```, we get three NIFTI and three json files which are described below

*_e1.json
*_e1.nii.gz (two volumes that has the Magnitude images with TR1 and TR2)

*_e1_ph.json
*_e1_ph.nii.gz (one volumes that has B1 map phase data)

*_e1a.json
*_e1a.nii.gz (one volumes that has B1 map phase data)

The issue is the in the *_e1.json (which has the two volumes that has the Magnitude images with TR1 and TR2), only has one value for "RepetitionTime".

Desired/Expected behavior:
It may be better if the first *_e1.nii.gz files is converted into two separate files each with its own *.json file and respective TR value.

In the DICOM tags it self the repetition time changes shown by the (0018,0080) tag, the DICOM tag (2005,1030) contains both the TR values.

What is the best approach to force dcm2niix to generate two separate files each with its own *.json file and respective TR value.?

Thank you,
-Sandeep

**Comment by neurolabusc** [comment]
@sandeepganji you have two options. 
 1. Your can develop a patch for dcm2niix and submit a pull request to share it. 
 2. You can share an example DICOM dataset [with my institutional email](https://sc.edu/study/colleges_schools/artsandsciences/psychology/our_people/directory/rorden_chris.php).

**Comment by sandeepganji** [comment]
Hi Chris,
I just shared a OneDrive (SharePoint) link with your institutional email address that contains the B1 map data from a Phantom scan. I included both Classic and Enhanced DICOM format for your reference. In the DICOM tags it self the repetition time changes shown by the (0018,0080) tag, the DICOM tag (2005,1030) contains both the TR values. If needed, I'm happy to have a zoom call with you.
Thank you,
-Sandeep

**Comment by neurolabusc** [comment]
@sandeepganji can you try the latest commit to the development branch. It should append a `r1`..`rN` for each repetition time.

```
git clone --branch development https://github.com/rordenlab/dcm2niix.git
cd dcm2niix/console
make
./dcm2niix
```

**Comment by sandeepganji** [comment]
hi Chris,
I just tried it on my Linux machine and it worked like a charm.
Thank you so much for your swift action in fixing it – your efficiency is greatly appreciated!
Best,
-Sandeep

**Comment by neurolabusc** [comment]
@sandeepganji an unintended consequence of my patch for this is that it assumes some single TR images are multiple TR. For example, the data for [issue 749](https://github.com/rordenlab/dcm2niix/issues/749) lists two elements in the array 2005,1030. So do we ignore elements with a value of 0? Does this tag always list two elements? What if a sequence had 3 tags? Does Philips have a formal description for this private tag?

```
(2005,1030) UN (FL) 4527.34\0            # 8,1-n Repetition Time
```

**Comment by sandeepganji** [comment]
Hi Chris,

Sorry for the delayed response.

Yes that tag (2005,1030) will always have two elements (as of the Philips MR SW R5.7 release). Its primarily designed for mixed sequences and contains the repetition times for respectively images and for all other sequences it contains a single repetition time. Even when you are doing multiple TR values scans (such as for Spectroscopy multi-TR scan for T1 estimation), it contains the first TR value and the actual TR value for each image is represented by (0018,0080).

Best,
-Sandeep
