### ISSUE TITLE
US convertion error

### ISSUE THREAD

**Issue by opennog** [rordenlab/dcm2niix#747]
Hi, 

I came across some US data, probably the NifTi format is not so used with this type of ultrasound data but still I wanted to convert it, and I got weird results. Please find attached a zip file with the original dcm file (with JPEG Baseline (Process 1) syntax) and the converted dcm file to allow dcm2niix conversion. Conversion was done with dcmdjpeg as recommended. 

This is the dcm2niix behavior in both cases:
(expected)
```$ dcm2niix -v y original/
Chris Rorden's dcm2niiX version v1.0.20230411  (JP2:OpenJPEG) (JP-LS:CharLS) GCC8.4.0 x86-64 (64-bit Linux)
Found 1 DICOM file(s)
Error: Compressed image stored as 2 fragments: decompress with gdcmconv, Osirix, dcmdjpeg or dcmjp2k original/image-00000.dcm
DICOM file: original/image-00000.dcm
 patient position (0020,0032)	nan	nan	nan
 orient (0020,0037)	0	0	0	0	0	0
 acq 0 img 1 ser 1 dim 64x64x1x1 mm 1x1x1 offset 0 loc 0 valid 0 ph 0 mag 0 nDTI 0 3d 0 bits 8 littleEndian 1 echo 0 coilCRC 0 TE 0 TR 0
Image Decompression is new: please validate conversions
No valid DICOM images were found
```

(non expected behavour)
```
$ dcm2niix -v y converted/
Chris Rorden's dcm2niiX version v1.0.20230411  (JP2:OpenJPEG) (JP-LS:CharLS) GCC8.4.0 x86-64 (64-bit Linux)
Found 1 DICOM file(s)
DICOM file: converted/image-00000_1.dcm
 patient position (0020,0032)	nan	nan	nan
 orient (0020,0037)	0	0	0	0	0	0
 acq 0 img 1 ser 1 dim 64x64x1x1 mm 1x1x1 offset 14154 loc 0 valid 1 ph 0 mag 0 nDTI 0 3d 0 bits 8 littleEndian 1 echo 0 coilCRC 0 TE 0 TR 0
Warning: Empty protocol name(s) (0018,1030)
Warning: PatientOrient (0018,5100) not specified (issue 642).
Warning: Unable to determine manufacturer (0008,0070), so conversion is not tuned for vendor.
Converting converted/image-00000_1.dcm
Warning: Unable to append protocol name (0018,1030) to filename (it is empty).
Convert 1 DICOM as converted/converted_20131219112221_1 (64x64x1x1)
Compress: "/usr/bin/pigz" -n -f -6 "converted/converted_20131219112221_1.nii"
Conversion required 0.016255 seconds (0.009399 for core code).
```

If you see the dimensions of the converted NifTi file are 64x64x1x1, however, for both the original and the converted the data is (434, 636, 3) as indicated in the DICOM header. 

I know it is not standard data to be converted to NifTi and that other important information is missing, but I'd appreciate if you could you have a look?

Thanks!

Ps. I could provide more sample files if needed.

**Comment by neurolabusc** [comment]
No attached zip file. 

Looking at the output it looks like Image Position (Patient) [(0020,0032)](http://dicomlookup.com/lookup.asp?sw=Tnumber&q=(0020,0032)) is missing or corrupted. This is a Type 1 (required) DICOM tag for raw DICOM images. Therefore, this does not appear to be a valid DICOM. dcm2niix assumes DICOM images are valid and truthful. dcm2niix uses this tag to preserve spatial information. I suspect some anonymization or format tool stripped out required details. I would check the provenance of these images, if you can get one direct from the system prior to these tags being removed you should be OK.

 In general, dcm2niix is developed for CT, MR, and PT. I would suggest US users try out Slicer3D.

**Comment by opennog** [comment]
[sample.zip](https://github.com/rordenlab/dcm2niix/files/12483148/sample.zip)

Sorry for that. 
As you say, you'll see the image has a very strange content, but given that the dimensions of the raw data are (434, 636, 3) I was just wondering if your created nifti could be the same. 
Unfortunately, I can not provide you with similar images directly provided by the device.

**Comment by neurolabusc** [comment]
This 2D RGB image of a timecourse is not a spatial 3D image. This is outside of the remit of dcm2niix and indeed that of the NIfTI file format. I would suggest using tools and formats that are appropriate for the modality.
