### ISSUE TITLE
Siemens XA20 3D PCASL

### ISSUE THREAD

**Issue by araikes** [rordenlab/dcm2niix#748]
Hi @neurolabusc,

I recognize that there is extensive query and discussion about ASL sequences here, as well as vendor specific pages. However, I didn't find a specific answer to my question. I apologize if I missed it somewhere.

We are collecting data on a Siemens Vida running XA20 and producing enhanced DICOMs. I converted the data with dcm2niix `v1.0.20230411`. The sequence is an Axial 3D PCASL. 

The JSON file reports the `PostLabelDelay` (for BIDS should this be `PostLabelingDelay`?) as 800ms. However, the sequence was set up with a labelling duration of 800ms and PLD of 2s (see below).

Additionally, the DICOM reports the following:

```
(0018, 9258) ASL Pulse Train Duration            UL: 800
```

I'm not sure where in the DICOM I would expect to find the PLD for this software version. A bit of confirmation bias finds:

```
(0021, 1189) Private tag data                    FD: 2000.0
```

Can you help me figure out what I'm looking for and where so I get things specified correctly.

![image](https://github.com/rordenlab/dcm2niix/assets/18663624/adfff498-99a3-45e1-9768-e8c998f681d4)

**Comment by neurolabusc** [comment]
@araikes perhaps @mcraig-ibme, @jan-petr or @HenkMutsaerts can help you out. I did spend a lot of effort trying to support BIDS ASL tags, and you can find my Siemens [XA30](https://github.com/neurolabusc/dcm_qa_xa30) and [VE11](https://github.com/neurolabusc/dcm_qa_asl) validation datasets. I worked closely with  The [XA30 dataset includes a sequence PDF](https://github.com/neurolabusc/dcm_qa_xa30/blob/main/XA_validation.pdf).

**Comment by jan-petr** [comment]
The correct tag name is indeed PostLabelingDelay. And 800 ms is rather low for Labeling duration - the typical values are chosen around 1800-2000ms according to the 2015 consensus. Is this the XA20 product sequence you are using?

Decoding Siemens data is indeed very tricky as most information is in the Phoenix protocol under unlabeled private fields and they differ from version to version. We're working on getting the Rosetta Stone for that as well.

I'll check what I can do with the online examples.
