### ISSUE TITLE
BidsGuess feedback (issues with derived data)

### ISSUE THREAD

**Issue by dlevitas** [rordenlab/dcm2niix#751]
Hi Chris,

I've been testing the BidsGuess feature on the development dcm2niix (`version v1.0.20230411`) instance and have noticed a few instances where BidsGuess appears to incorrectly define specific data as `derived`. I've shared this data (all from our Siemens Prisma scanner) with your institutional email, containing 3 separate sub-folders:

1).  *anat_T1w* - this data was correctly identified as `anat` (datatype) and `T1w` (suffix). This is simply reference data.
2). *b1map* - I'm not particularly familiar with this data; however, I believe it is a `fmap/TB1TFL` ([BIDS ref](https://bids-specification.readthedocs.io/en/stable/appendices/qmri.html#tb1tfl-and-tb1rfm-specific-notes)) sequence. BidsGuess however identifies this as `derived` and `localizer` for the datatype and suffix respectively. 
3). *derived_T1w* - BidsGuess identifies this as `derived` (datatype) and `T1w` (suffix), though it is unclear to me why it is specified as `derived` when it seems to recognize this is a mprage T1w sequence. 

I primarily focused on the `datatype` and `suffix` identification rather than the entity labels. As such, the dcm2niix command I used was `dcm2niix -z y -o $PWD *.dcm`, without the `-f $h` flag to generate a BIDS dataset. I then simply examined the `BidsGuess` field in the sidecar json files.

**Comment by neurolabusc** [comment]
@dlevitas thanks. Please test the development branch and close if this resolves your issues.

**Comment by dlevitas** [comment]
All issues have been resolved, thanks again.
