### ISSUE TITLE
Unsupported overlay origin 0/0

### ISSUE THREAD

**Issue by andreacivita** [rordenlab/dcm2niix#752]
Hi, i'm having this bug while converting a dicom file to a nifti file: 
`Unsupported overlay origin 0/0`.

How can i solve or remove overlay? 
Thank you in advance

**Comment by neurolabusc** [comment]
This depends on how your [overlay](https://dicom.nema.org/dicom/2013/output/chtml/part03/sect_C.9.html) was generated. Overlays are binary bitmap objects drawn on top of your DICOM image - for example a circle identifying the location of a lesion. If the overlay was not added by the MR technologist on the scanner console, you can simply export the raw DICOMs direct from the scanner before the overlay was added. In general, dcm2niix users ignore DICOM overlays, and simply export the main image. You can create new drawings on NIfTI images with tools like FSLeyes, MRIcroGL and ITKsnap.

**Comment by andreacivita** [comment]
Could the overlay affect the size and number of images in the NIfTI file? Because when I convert a DICOM file with 365 images to NIfTI format and then pass it to the LST toolbox, it outputs more than 800 images.

**Comment by neurolabusc** [comment]
Overlays are binary (black and white) bitmaps that can be shown on top of the medical image. Each DICOM can have up to 16 overlays. If you count overlays as independent images, a single classic DICOM file could therefore have 16 overlay images.
