### ISSUE TITLE
Additional BidsGuess feedback

### ISSUE THREAD

**Issue by dlevitas** [rordenlab/dcm2niix#753]
I've shared additional DICOM data pertaining to several issues and suggestions. Some of these are more nit-picky, so if they seem outside the scope of BidsGuess (and dcm2niix more generally), feel free to ignore.  

1). *func_multiecho_mag_phase* - this dataset contains multi-echo `func/bold` and `func/sbref` magnitude & phase sequences. BidsGuess however does not specify the `part-phase` (or corresponding `part-mag`) entity label. 

2). *func_tasks* - For the `func/bold` and `func/sbref` sequences, BidsGuess doesn't specify the `task-` entity, despite this being a required label. In the past I've seen BidsGuess default to `task-rest` for `func` sequences, but doesn't appear to do so here (or in some other datasets I've tested). 

3). *dwi_fieldmap* - This dataset mostly contains `dwi/dwi` (`dir-AP`) data, but with a "distmap" (`dir-PA`) sequence. BidsGuess determined the datatype/suffix pairing for this "distmap" sequence to also be `dwi/dwi`, yet it should be `fmap/epi`, as it is a PEpolar spin-echo sequence. I'm unsure though how simple it would be to determine that from the DICOM header alone. 

4). *dwi_mag_phases* - This dataset mainly contains a collection of magnitude and (I believe) phase `dwi/dwi` sequences. For these latter sequences, BidsGuess identifies them as `fmap` (datatype) and `phasediff` (suffix), when instead I believe these are`dwi/dwi` (`part-phase`) sequences. 

Lastly, I have a general suggestion that is particularly relevant to (2) but applies to any dataset. A number of researchers use the [ReproIn naming convention](https://dbic-handbook.readthedocs.io/en/latest/mri/reproin.html) when describing their scan protocols, typically in the `SeriesDescription` and/or `ProtocolName`. Since this convention, essentially BIDS, is an explicit attempt by researchers to describe specific entity values, BidsGuess could extract this information when determining entities. Example:
    
    "SeriesDescription": "func_task-bart" ----> "BidsGuess": ["func","_task-bart_acq-epfid2m8_dir-AP_run-16_bold"] 

That said, I would consider only applying this logic to entity labels that can't be inferred from the DICOM header. One exception would be the `run-` entity label; using `SeriesNumber` is a smart approach for avoiding file naming conflicts.

**Comment by neurolabusc** [comment]
@dlevitas I have some partial solutions and comments:
 - func_multiecho_mag_phase dcm2niix now adds the part-phase, but it does not set part-mag. These datasets are stored as two series, so they can not be reconciled by a one-pass filter like the bids-guess divide and conquer that converts each series independently. This would be easy to reconcolie with a 2nd-pas wrapper that can detect that both images share "AcquisitionTime".
 - The dcm2niix is only designed to help wrapper writers, and is not assumed to be used by end users, all bold datasets are labelled `task-rest` as a dummy for the bids-validator. Obviously, a wrapper can look at the protocol name to determine if a matches a common convention. Series 10 (anat-T2w) is incomplete 145 of 208 files. Series 2 (anat-T1w) is incomplete 174 of 208 files.
 - dwi_fieldmap is a challenge, as this is XA20 without the CSA header of V* series or XA30+. I will try to refine this a bit more.
 - dwi_mag_phases is from a Philips scanner, and it would help to have some insight from one of their engineers. Can you put me in touch with the Philips Clinical Scientist associated with the site that acquired these?

**Comment by dlevitas** [comment]
These all sound appropriate, thanks again. 

> * dwi_mag_phases is from a Philips scanner, and it would help to have some insight from one of their engineers. Can you put me in touch with the Philips Clinical Scientist associated with the site that acquired these?

This data was kindly shared with us, I will look into who is the best point of contact.
