### ISSUE TITLE
Error: Converted 37675 of 72956 files 

### ISSUE THREAD

**Issue by acooperr1** [rordenlab/dcm2niix#754]
**Describe the bug**
Using dcm2niix_afni  -v 2 -l y -p y -z y produced a series of nil.gz files, however, when the command runs through, I receive these messages at the end:
"Warning: Check that 2D images are not mirrored" and "Error: Converted 42599 of 77914 files"

The converted nifti images will not load in MRIcron, and I receive this error message when trying to load the images: "Error: this does not appear to be a valid 2D or 3D image."

**Steps to reproduce the behavior:**
Run the command dcm2niix_afni  -v 2 -l y -p y -z y -o "output_directory" "input_directory"
Output directory contains my ON_MB3_fMRI_01.nii.gz file, but my terminal includes the two errors mentioned above and the file will not load in MRIcron.

**Expected Behavior**
The Dicom file should be converted to Nifti and have the ability to be opened in MRIcron.

**version:**
v1.020211006

**Comment by neurolabusc** [comment]
Can you see if following the troubleshooting from the bug report template resolves your issue? You are using v1.020211006 which predates modern enhanced DICOM implementations. So I would see if [v1.0.20230411](https://github.com/rordenlab/dcm2niix/tree/v1.0.20230411) resolves your issue. Given your command, it sounds like your data is from a Philips scanner, is this correct? If so, do you have a lot of DICOM exam cards in addition to DICOM images? I would add the `-i y` to ignore the derived and localizer images to see if this removes the 2D image warnings. In general, we discard the low resolution and high artifact 2D localizers as they are simply used as scouts for planning the subsequent 3D images.


**Troubleshooting**

Please try the following steps to resolve your issue:

 - Is this the [latest stable release](https://github.com/rordenlab/dcm2niix/releases)? If not, does the latest stable release resolve your issue?
 - If the latest stable version fails, and you are using Windows. Does the latest commit on the development branch resolve your issue? You can get a pre-compiled version from [AppVeyor](https://ci.appveyor.com/project/neurolabusc/dcm2niix) (click on the Artifacts button).
 - If the latest stable version fails, and you are using macOS or Linux. Does the latest commit on the development branch resolve your issue? You can build this using the recipe below:
