### ISSUE TITLE
Wrong EchoTime, RepetitionTime, InversionTime saved in generated JSON file

### ISSUE THREAD

**Issue by nshkr** [rordenlab/dcm2niix#755]
**Describe the bug**

When I convert dicom to nifti, the EchoTime, RepetitionTime, and InversionTime (and maybe more dicom tags) are saved with a wrong value in the JSON metadata file. The values are saved by being divided by 1000. For example, the original dicom tags are:

![image](https://github.com/rordenlab/dcm2niix/assets/99551131/48dcff0d-0cbe-466f-acc9-1b682f49b3f2)

while in the JSON file generated by dcm2niix, we see:

"EchoTime": 0.15314,
"RepetitionTime": 8.8,
"InversionTime": 2.2,

**To reproduce**

1. Run the command 'dcm2niix -f %i_%j ./input_folder/'
2. Compare the dicom tags of the original dicom files with the metadata in the generated JSON file

**Expected behavior**

The values saved in JSON file for the EchoTime, RepetitionTime, InversionTime should be equal to the original dicom tags. These are the parameters that I came across, so the same problem might exist with more parameters.

**Version**

Chris Rorden's dcm2niiX version v1.0.20230411  (JP2:OpenJPEG) (JP-LS:CharLS) GCC8.4.0 x86-64 (64-bit Linux)

**Comment by neurolabusc** [comment]
Note that the JSON file is in BIDS format, which specifies the [International System of Units](https://en.wikipedia.org/wiki/International_System_of_Units). Specifically, [seconds is the unit for time](https://bids-specification.readthedocs.io/en/stable/02-common-principles.html#units): `Elapsed time SHOULD be expressed in seconds. Please note that some DICOM parameters have been traditionally expressed in milliseconds. Those need to be converted to seconds.`
