### ISSUE TITLE
BidsGuess labeling issue

### ISSUE THREAD

**Issue by dlevitas** [rordenlab/dcm2niix#756]
I've shared a folder containing two distortion sequences (`BIAS_BC`, `BIAS_64CH`) that are both incorrectly labeled as an `anat/T1w` datatype/suffix pairing. The `BIAS_BC` is a distortion from the body coil and the `BIAS_64CH` is a distortion from the head coil, I believe these are akin to the distortion correction procedures in the HCP pipeline. I'm unsure which BIDS field-mapping procedure most appropriately describes these, but they're meant for the `dwi/dwi` sequences in this dataset.

**Comment by neurolabusc** [comment]
Thanks. The Fall release improves support for these, but we will not be able to disambiguate the intention for all sequences.
