### ISSUE TITLE
BidsGuess feedback

### ISSUE THREAD

**Issue by astewartau** [rordenlab/dcm2niix#758]
Hi Chris,

I've started testing BidsGuess with some of my data and have a problem.

The `run-` identifier currently uses the `SeriesNumber` DICOM field. As I understand, the `run` entity (as defined in BIDS) identifies multiple instances of the same acquisition to avoid name conflicts. For QSM, we typically have multiple series for a single acquisition (e.g. magnitude+phase). BidsGuess currently gives each magnitude and phase series different run numbers, even if they were actually from the same acquisition. It might be easier for tools to identify matching pairs of mag/phase images if their run numbers matched.

Could it make sense to use the `AcquisitionTime` field to determine separate runs, since this field should be identical across multiple series? Or maybe something else? BidsGuess could then use a simple incrementing counter for the `run-` entity starting from `run-1` to avoid name conflicts wherever they would otherwise occur. 

It is possible to handle this on the tool side, but this could be worth handling here as other tools might encounter the same problem.

**Comment by neurolabusc** [comment]
Yup, I am aware of this situation with some fieldmaps as well. 

I am still waiting for Philips validation datasets, so the bids guess will be suppressed by default for the stable Fall 2023 release - we will have a more robust solution for the Spring 2024 release.

-c

Chris Rorden, PhD
Endowed Chair of Neuroimaging
Co-Director, McCausland Center for Brain Imaging
Department of Psychology
University of South Carolina
Columbia, SC 29208, USA
email ***@***.***
web www.mricro.com
I am unable to opt-out of my institution’s spam filter, if I do not respond please contact me via ***@***.***
