### ISSUE TITLE
On some DICOM file renames, am getting "Illegal DICOM tag 7651,5351 (odd element length 20305)" I cannot find this DICOM tag in order to troubleshoot.

### ISSUE THREAD

**Issue by Spockaccino** [rordenlab/dcm2niix#759]
**Describe the bug**

**To reproduce**

1. Run the command 'dcm2niix ...'
2. See error ...

**Expected behavior**

**Output log**

If applicable, output generated converting data.

**Version**

Please report the complete version string:

 - dcm2niix version string, e.g. `dcm2niiX version v1.0.20201207  Clang12.0.0 ARM (64-bit MacOS)` The version string is always the first line generated when dcm2niix is run.

**Troubleshooting**

Please try the following steps to resolve your issue:

 - Is this the [latest stable release](https://github.com/rordenlab/dcm2niix/releases)? If not, does the latest stable release resolve your issue?
 - If the latest stable version fails, and you are using Windows. Does the latest commit on the development branch resolve your issue? You can get a pre-compiled version from [AppVeyor](https://ci.appveyor.com/project/neurolabusc/dcm2niix) (click on the Artifacts button).
 - If the latest stable version fails, and you are using macOS or Linux. Does the latest commit on the development branch resolve your issue? You can build this using the recipe below:

```
git clone --branch development https://github.com/rordenlab/dcm2niix.git
cd dcm2niix/console
make
./dcm2niix ....
```

**Comment by neurolabusc** [comment]
Closing as question is underspecified and issue template not followed. If you wish to have a meaningful response, your may want to follow one of these approaches:
 1. provide the complete feedback of running dcm2niix with the hyper-verbose mode (`dcm2nix -v /path/toDICOMs`)
 2. provide the DICOM header output of dcmdump or gdcmdump (make sure you anonymize).
 3. Send a sample dataset [to my institutional email](https://sc.edu/study/colleges_schools/artsandsciences/psychology/our_people/directory/rorden_chris.php).
