### ISSUE TITLE
Incorrect reading of DICOM information and generation of invalid images

### ISSUE THREAD

**Issue by mbrzus** [rordenlab/dcm2niix#760]
**Describe the bug**

We are working on converting an anonymized dataset of DICOM MRI. Many of the subjects were incorrectly anonymized and the DICOM metadata is damaged. However, for many subjects, we experience this bug that produces "invalid" images as shown below. Additionally, dcm2niix fails to read DICOM header information as shown in the log output.

We were able to open and save as a nifti file the same DICOM directory in 3D Slicer and we were able to convert the DICOM directory to a nifti volume image using ITK (I can provide the function if needed). I could share a subject that leads to this error privately as we do not have permission to upload it publicly here.

**To reproduce**
This bug occurred running this command:
`dcm2niix -v y -o <output_dir> -f <filename> -z y <dcm_dir>`

**Expected behavior**
This is the axial slice of the image saved using ITK in Python. Opening the DICOM directory in Slicer 3D produces the same volume.
![itk_write](https://github.com/rordenlab/dcm2niix/assets/44876465/cb819f1f-4213-4c77-a6ca-70ece9ea6473)

**Observed behavior**
This is the file generated by dcm2niix
![dcm2niix_write](https://github.com/rordenlab/dcm2niix/assets/44876465/e3c8107d-f18c-48f7-aad0-7230b6a55601)

**Output log**

```
Chris Rorden's dcm2niiX version v1.0.20230411  (JP2:OpenJPEG) GCC11.4.0 x86-64 (64-bit Linux)
Found 31 DICOM file(s)
DICOM file: <path>/0018.dcm
 patient position (0020,0032)	nan	nan	nan
 orient (0020,0037)	0	0	0	0	0	0
 acq 0 img 0 ser -1 dim 128x128x1x1 mm 1x1x1 offset 1678 loc 0 valid 1 ph 0 mag 0 nDTI 0 3d 0 bits 16 littleEndian 1 echo 0 coilCRC 0 TE 0 TR 0
Warning: Instance number (0020,0013) not found: <path>/0018.dcm
DICOM file: <path>/0009.dcm
 patient position (0020,0032)	nan	nan	nan
 orient (0020,0037)	0	0	0	0	0	0
 acq 0 img 0 ser -1 dim 128x128x1x1 mm 1x1x1 offset 1678 loc 0 valid 1 ph 0 mag 0 nDTI 0 3d 0 bits 16 littleEndian 1 echo 0 coilCRC 0 TE 0 TR 0
Warning: Instance number (0020,0013) not found: <path>/0009.dcm
...
DICOM file: <path>/0031.dcm
 patient position (0020,0032)	nan	nan	nan
 orient (0020,0037)	0	0	0	0	0	0
 acq 0 img 0 ser -1 dim 128x128x1x1 mm 1x1x1 offset 1674 loc 0 valid 1 ph 0 mag 0 nDTI 0 3d 0 bits 16 littleEndian 1 echo 0 coilCRC 0 TE 0 TR 0
Warning: Instance number (0020,0013) not found: <path>/0031.dcm
Warning: PatientOrient (0018,5100) not specified (issue 642).
Converting <path>/0004.dcm
Warning: Expected 1 volumes but found spatial position repeats 0 times.
Warning: Instance Number (0020,0013) order is not spatial.
Unable to determine spatial orientation: 0020,0037 missing (Type 1 attribute: not a valid DICOM) Series 0
Warning: Unable to determine slice direction: please check whether slices are flipped
Warning: Bogus spatial matrix (perhaps non-spatial image): inspect spatial orientation
Convert 31 DICOM as <path> (128x128x31x1)
Compress: "/usr/bin/pigz" -b 960 -n -f -6 "<path>"
Conversion required 0.076499 seconds (0.031138 for core code).
```
This was alarming since the DICOM header (extracted using dcm2xml) shows that those values for (0020,0032) and (0020,0037) are present:

`<element tag="0020,0032" vr="DS" vm="3" len="26" name="ImagePositionPatient">-105.23\-138.521\-43.0114</element>`
`<element tag="0020,0037" vr="DS" vm="6" len="58" name="ImageOrientationPatient">0.997504\0.0639672\-0.0299083\-0.0604573\0.992495\0.106296</element>`

Both ITK and Slicer were able to get that information correctly. We were not able to determine if the incorrect reading of those fields causes the conversion problem or if this is a deeper issue.

**Version**

The same behavior was replicated using the fe2f260 commit, the latest version (v1.0.20230411), and versions from 2021 and 2020.

**Comment by neurolabusc** [comment]
OK, feel free to send a sample to my [institutional email](https://sc.edu/study/colleges_schools/artsandsciences/psychology/our_people/directory/rorden_chris.php). My best guess is that these DICOMs have thumbnails embedded.

**Comment by mbrzus** [comment]
I sent the sample sequence. Let me know if you need more data/info.

**Comment by neurolabusc** [comment]
@mbrzus please try out the latest development version (v1.0.20231005) and close this issue if it resolves your problem. As I feared, these DICOM images were touched by a GEIIS PACS that inserted thumbnail icons. In my experience, these cause a myriad of issues with other tools that touch the images, so it is hard to develop a single solution. What makes your images particularly problematic is that they use a private SQ `0009,1110` rather than the public [Icon Image Sequence (0088,0200)](https://dicom.innolitics.com/ciods/basic-structured-display/structured-display/00880200) tag. I do not consider your images archival quality, and you should handle these with care. While I have patched dcm2niix, other tools may also be confused. I am glad to see the data was acquired a decade ago - hopefully the offending GEIIS system has been retired.

```
git clone --branch development https://github.com/rordenlab/dcm2niix.git
cd dcm2niix/console
make
./dcm2niix
```

**Comment by mbrzus** [comment]
The patch fixed the issue! And I agree, this dataset has been giving us a lot of trouble and we are trying to recover as much data as possible. We were surprised, as dcm2niix has been wonderful and always works with pretty much anything. 
Thank you so much for your help!
