### ISSUE TITLE
Feature request: include PatientAge (0010, 1010) in JSON sidecar made using -ba n

### ISSUE THREAD

**Issue by pwrightkcl** [rordenlab/dcm2niix#763]
Would it be possible to include PatientAge (0010, 1010) in the JSON sidecar with the `-ba n` option?

The [dcm2niix/BIDS](https://github.com/rordenlab/dcm2niix/tree/master/BIDS#global-private-information) documentation says this tag is not included. Behaviour of my version of dcm2niix is consistent:

`Chris Rorden's dcm2niiX version v1.0.20230411  (JP2:OpenJPEG) (JP-LS:CharLS) GCC8.4.0 x86-64 (64-bit Linux)`

My use case: I have images with anonymised DICOM files where PatientBirthDate is removed, but PatientAge is retained. These will be passed to a pipeline that receives only the DICOM as input but requires age for analysis. If this tag was added, I could just use dcm2niix to process, rather than having an extra step to retrieve age directly from the DICOM. I could also run the pipeline on .nii + .json data, which my data provider would prefer over sending me DICOM.

I'm not sure how common this use case might be, but I hope it would be a simple change to implement and wouldn't affect anything else.

**Comment by captainnova** [comment]
+1. I think this is a good idea, and would be happy to submit a PR if @neurolabusc isn't halfway to implementing this himself.

Removing or altering birth dates is basically universal for anonymization, age is a commonly needed input for aging studies, and your data provider is correct to trust nii + json anonymization over DICOM anonymization.

**Comment by captainnova** [comment]
[The BIDS specification](https://bids-specification.readthedocs.io/en/stable/glossary.html#age-columns) calls subject age "age", although I think that is in the context of the cohort description .tsv. I think we should at least capitalize it for the .json describing an individual series.

**Comment by neurolabusc** [comment]
@pwrightkcl and @captainnova I agree this would be a nice idea. One question is whether we obey the [safe harbor method](https://www.hhs.gov/hipaa/for-professionals/privacy/special-topics/de-identification/index.html) and aggregate all ages over 89 as 90 (or older)? In other words, if the DICOMs have omitted the birthday, it seems like there has been an attempt at some form of de-identification. Happy to add this myself, but we have passed the feature freeze for the Fall release, so lets focus on this after that gets merged.

**Comment by captainnova** [comment]
I wondered about clamping the age at 90 myself, but @pwrightkcl asked for it with -ba n. The principle of least surprise suggests that -ba n does not do anonymization, while -ba y leaves out Patient* + a few other things. The given use case would require the user to examine and edit the -ba n BIDS .jsons as needed, but that is an easier task than it would be with DICOM.

> if the DICOMs have omitted the birthday, it seems like there has been an attempt at some form of de-identification. 

Yes, but omitting the birthday or setting it to Jan. 1 of the appropriate year is so common that the presence or absence of the  PatientBirthDate tag does not give much info about the desired level of anonymization. Really upstream should have already filtered PatientAge if that is what they wanted.

There is also the internal use case - if the data aren't being shared, _and_ plots aren't being externally published showing those > 90 y old ages, then there is no reason to not use the actual ages.

I admit there are limits on -ba n, though. The DICOM tag shouldn't literally be poured into BIDS since DICOM's AS VR is \d\d\d[DWMY], while my impression is that BIDS favors ints or floats with the unit (years) defined in the specification.

**Comment by pwrightkcl** [comment]
My tuppennyworth is that PatientAge should be passed more or less as is. As @captainnova said, if the user switches off anonymisation they won't expect the values to be modified. Moreover, this particular modification might be difficult to spot if it only happens to a small fraction of participants. For my particular use case, we need the ages over 90 because they are used for an age model.

I think it should have the key PatientAge in the JSON, consistent with others corresponding to DICOM attributes. I'm agnostic on converting the age string to a number. I had a good look at other BIDS sidecar values and couldn't find any other where a string like "021D" could be converted to a float "0.05749".  All the [private fields](https://github.com/rordenlab/dcm2niix/tree/master/BIDS#global-private-information) are defined by dcm2niix not BIDS, so it is up to @neurolabusc.

**Comment by neurolabusc** [comment]
@captainnova and @pwrightkcl can you please test the latest build of the development branch with your large datasets. It will now add `PatientAge` (in years) if the following conditions are met: the `-ba n` is used and the DICOM reports the [Patient Age (0010,1010) tag](https://dicom.innolitics.com/ciods/rt-dose/patient-study/00101010) in years. Note that in theory the tag can specify [age in years, months, weeks or days](https://dicom.nema.org/dicom/2013/output/chtml/part05/sect_6.2.html) so the JSON tag will not be created if the unit is not years.

**Comment by captainnova** [comment]
A git pull of development just now yielded v1.0.20231111. It passed our lab's test suite with flying colors. There were some differences in the .json outputs, as expected, but they appear to be improvements.

I also did some spot checking, like verifying that -b y still defaults to -ba y, -ba y still omits patient info (unless you count PatientPosition - I don't), and the PatientAge's behavior changed as expected. It did, and the local scan I tried it on happened to also have PatientBirthDate in it. So the discussion above of clamping PatientAge really seems futile now; -ba n seriously means not anonymized, and users need to inspect its output before sharing.

We mostly study dementia, and do not have any baby or animal data where the DICOM should use anything other than Y. Even our phantoms tend to get artificially old ages entered at the scanner. So I couldn't test that, but everything looks good.

**Comment by pwrightkcl** [comment]
With apologies for very belated response and purely for the record: I've now compiled the dev version and tested on one of our clinical images; PatientAge appears in the JSON as expected.

I haven't tested a range of images nor looked for edge values (I expect all our scans to be from adults).
