### ISSUE TITLE
How to extract magnitude and phase sequences in the same QSM Dicom folder as separate Nifti files using dcm2niix?

### ISSUE THREAD

**Issue by kaiyuliu123** [rordenlab/dcm2niix#764]
Hello guys,

I'm trying to use the latest version of dcm2niix (v-20-July-2022) to convert QSM dicom images to separate magnitude and phase Nifiti (nii.gz) files with different time echos. Unfortunately, it seems that I only get the magnitude nifti files after the conversion and all the phase images are missing. Has anyone been through this before?

<img width="719" alt="image" src="https://github.com/rordenlab/dcm2niix/assets/135558568/785e3a46-9b41-4231-9b18-7f1b0455178c">
<img width="707" alt="image" src="https://github.com/rordenlab/dcm2niix/assets/135558568/61d02d0e-d107-4a35-a298-212808bcf947">
<img width="419" alt="image" src="https://github.com/rordenlab/dcm2niix/assets/135558568/1d46777e-2da4-44cc-89e6-ce5cadf8f6fe">
The first time echo↑↑
---------------------------------------------------------------------
<img width="704" alt="image" src="https://github.com/rordenlab/dcm2niix/assets/135558568/ffc69683-a1fd-4af3-8c69-437cc1b6c518">
<img width="455" alt="image" src="https://github.com/rordenlab/dcm2niix/assets/135558568/0962c5d6-8265-412e-a27f-bdb07888df09">
The last time echo↑↑

I would really appreciate your help!

**Comment by neurolabusc** [comment]
Hello,
 1. Does the latest stable release [v1.0.20230411](https://github.com/rordenlab/dcm2niix/tree/v1.0.20230411) address this issue?
 2. I do not have access to GE hardware, and I am unfamiliar with their QSM data. However, the overlay messages suggest that this may have been pre-processed by another tool. Can you check the provenance of your images and make sure they are direct from the scanner.  The software also reports that it thinks images are missing - are you convinced that this is the entire sequence.
 3. Perhaps @mr-jaemin has some insights.

**Comment by brianlburns** [comment]
What version of the MR software platform did you acquire this data on? Which CVs did you modify at scan time to generate the Mag/Phase images? I just ran the latest dcm2nix (v1.0.20230411) on data that I acquired on MR29.1 and it successfully found all of the images for both the Mag/Phase and Mag/Real/Imag cases. I agree with the previous comment. Please check the provenance of your data and verify all of the phase images are present.
