### ISSUE TITLE
CoilString set, even when concatenating dicoms with varying values

### ISSUE THREAD

**Issue by bpinsard** [rordenlab/dcm2niix#766]
**Describe the bug**

When converting uncombined data, (eg. localizer), the dicoms get grouped by slice orientation which is what I would expect:
(get the warning `Slices stacked despite coil variation 'H82' vs 'H12'`)
and the resulting nifti is named with a random value, eg. `_cH63`, which is also present as CoilString in the json.

If you need data to reproduce, I might be able to find phantom scans. 

Also, this is clearly not super-critical, just a bit bothering when heudiconv uses that info to name BIDS files automatically.

**Expected behavior**

I would expect the `CoilString` to be empty and the name of the nifti not to include a misleading coil number when the nifti has mixed coils. Other/better option would be for `CoilString` to become an ordered list matching what is aggregated in the nifti.

**Output log**

If applicable, output generated converting data.

**Version**

Please report the complete version string:

`v1.0.20230411`

**Comment by neurolabusc** [comment]
Feel free to send me data. However, localizer's are used to position subsequent scans and are usually not helpful for subsequent scans due to T1 artifacts, partial volume issues, etc. Furthermore, it does sound like your DICOMs explicitly claim different coils were used, which would require dcm2niix to separate the slices. In general, dcm2niix assumes that DICOM images are truthful. If the files are not truthful, you should work with the manufacturer to resolve the issue.

My own advice is to convert DICOMs with the `-i y` argument to ignore localizer scans.

**Comment by bpinsard** [comment]
Thanks for your extremely fast feedback.

We acquire localizers uncombined with the goal of monitoring coil elements as a QA procedure, and for sure it is a niche use-case for nifti and BIDS. 

Not sure what you mean by "truthful", the dicoms are correctly formatted, each dicom file contain the right value for  `ImaCoilString` in the CSA header. It is just when converted to nifti that things go wrong, it likely takes the ImaCoilString value of the first dicom of all the dicoms which are stacked together, which is counter-intuitive. 

The problem should also arise for uncombined other than localizers, again niche case, but some researcher at our center save such data for a custom SWI sequence IIRC. Of course it is possible to explicitly ask to split these in separate niftis, but having 4d (3d+1+coil) or 5d (3d+t+coil) data seems more convenient.

**Comment by neurolabusc** [comment]
To quote a popular Sci-Fi line `Logic clearly dictates that the needs of the many outweigh the needs of the few.`. Supporting extreme niche cases will cause issues with typical usage. As you note, tools like heudiconv can include extra logic for such cases.
