### ISSUE TITLE
Feature request: par/rec slice timing

### ISSUE THREAD

**Issue by fliem** [rordenlab/dcm2niix#77]
Is there a way to get slice timing into the bids sidecar files when converting par/rec files? Thanks

**Comment by neurolabusc** [comment]
The PAR/REC files I have seen do not report the slice timing information (e.g. ascending, descending, interleaved, multi band, slice time). There is a value "dyn_scan_begin_time" but I am afraid this is identical for all slices in a volume and refers to the time of the first 2D slice in the 3D volume.
