### ISSUE TITLE
Warning of conversion from dicom to nifti for DWI from GE 1.5T and confirmation of converted files

### ISSUE THREAD

**Issue by YoonhoH** [rordenlab/dcm2niix#772]
1. Version of dcm2niix
     - Chris Rorden's dcm2niiX version v1.0.20230411  GCC12.2.0 x86-64 (64-bit Linux)

2.  Command of dcm2niix
     - dcm2niix -ba y -v y -z y -f %d -o /output_path /input_path (folder including dicom series)

3. Warning
     - Found 928 DICOM file(s)
DICOM file: ./input_path/I0000631
 patient position (0020,0032)	-121.287	-143.629	-12.7905
 orient (0020,0037)	1	-0	0	-0	1	0
 acq 1 img 591 ser 5 dim 256x256x1x1 mm 0.9375x0.9375x2.4 offset 2268 loc 928 valid 1 ph 0 mag 0 nDTI 1 3d 0 bits 16 littleEndian 1 echo 1 coilCRC -2028423569 TE 93.8 TR 15000
 DWI bxyz 1000 0.128 -0.959 0.254 ...............
 **Converting ./input_path/I0000041
_DICOM images may be missing, expected 928 spatial locations per volume, but found 58.
Warning: Unable to determine GE Slice timing, no Protocol Data Block GE (0025,101B): ./input_path/I0000041_
Saving 16 DTI gradients. GE Reorienting CEN-KOREA UNIV/5 : please validate. isCol=1 sliceDir=3 flp=0 0 1**

When converting for DWI data from GE 1.5T using dcm2niix, there occurs a warning. But the files have been converted from dicom to nifti, creating bvec and bval values. I understand that the warning occurs because the corresponding tag is not present in the header of dicom file. Is there another reason? Is there a way to resolve this in a situation where the data cannot be re-acquired? Also, can I use the converted file as is? Or is there a way to check if it's available?

**Comment by neurolabusc** [comment]
This is a warning and not an error. It suggests that some of the expected DICOM tags were not found, potentially because they were removed by an anonymization stage. There is some redundancy in GE tags, so the performance of dcm2niix likely reflects the number of residual tags left. My suggestion would be to check the provenance of these DICOMs, and convert a set prior to anonymization. Without this, you will need to manually check the resulting JSON sidecars to check which [details](https://github.com/rordenlab/dcm2niix/tree/master/GE#user-define-data-ge-0043102a) survived (e.g PhaseEnodingDirection, TotalReadoutTime, etc. Different versions of GE software store different details in their DICOM files, so there is not a universal answer.

**Comment by YoonhoH** [comment]
Thank you for quick and detailed response.
I'm telling you because I still have some questions as followings:

1. Since it is a warning rather than an error, can I use the resulting nifti file for analysis?
2. What/When is the anonymization stage? Are you talking about when you receive the dicom file from GE 1.5T ? Are you referring to the anonymization process when converting using dcm2niix?
3. How do I check the provenance of these DICOMs?
4. I checked the details, but can you tell me in detail what manullay to check in the JSON sidecars (.json)? What do I do if an element that needs to be present is missing?

**Comment by neurolabusc** [comment]
I would work with the center that acquired the data - try converting the DICOMs as they come directly after the scanner console, before they have been touched by any tools. Given that I do not have GE hardware, and the meta data varies across GE software versions, I do not know what (if any) parameters are missing. You could see if the `bids-validator` detects any errors with your datasets.

**Comment by mr-jaemin** [comment]
I also suspect that DICOMs were modified. Please check the following tags:

DICOMs from the scanner console contain:
(0002,0013) SH [MR30.1]                                 #   6, 1 ImplementationVersionName
(0018,1020) LO [30\LX\SIGNA_LX1.MR30.1_DA_2312.g]       #  32, 3 SoftwareVersions

I often find that (0002,0013) tag is updated by tool:
(0002,0013) SH [dcm4che-1.4.31]                         #  14, 1 ImplementationVersionName
(0002,0013) SH [VERTEX3.6.4.0]                          #  14, 1 ImplementationVersionName

I could take a look if you upload a sample DICOM (as a tar file):
https://gehealthcare.ent.box.com/f/3e5433ace5184a82850c6d00f8ca0d14

**Comment by YoonhoH** [comment]
Thank you for quick and detailed response.

@neurolabusc 
I am appreciated for details you tell me. But currently, we cannot acquire the dicom file that comes directly from the scanner due to data from a long time ago. The scanner has also changed in the center where data is obtained. If I look at the header, it is judged that it was received through the PACS system with INFINTT_3.5. I used the bids-validator (https://github.com/bids-standard/bids-validator) using python, and it turned out to be false for the converted (.nii.gz) file. Can I use this converted file for analysis? Is there any way I can use it?

@mr-jaemin 
I am grateful for details you tell me. I can check what you said.
(0002,0013) SH [OFFIS_DCMTK_361] # 16, 318 ImplementationVersionName
(0018,1020) LO [15 LX MR Software release:15.0_M4_0910.a] # 40, 1416 SoftwareVersions

I check the dicom file from original back-up, it is as below.
(0002,0013) SH [INFINITT_3.5] # 12, 314 ImplementationVersionName
(0018,1020) LO [15 LX MR Software release:15.0_M4_0910.a] # 40, 1416 SoftwareVersions

How can I use it for analysis? I cannot upload the dicom file due to policy.

**Comment by neurolabusc** [comment]
@YoonhoH this sounds like a limitation of your images, not dcm2niix. When provided with impoverished inputs, dcm2niix will be limited in its ability to report sequence details. Since it sounds like you are trying to analyze DWI data, you may want to see if you can process the data you have with your favorite tool (FSL, DSI studio, MRtrix, etc) and see if you have sufficient information for data processing. Alternatively, you could try to organize the data into the BIDS hierarchy and the bids-validator will tell you which sequence details are missing (slice timing, phase encoding direction, total readout time, etc).

**Comment by mr-jaemin** [comment]
@YoonhoH

It looks like you are dealing with old data (version 15 vs 30, latest version).

I would first validate the number of images and DTI (TENSOR) vs clinical DWI. It looks like your # of images 928:
Number of images (e.g 928) = (# of slices) x ((# of T2) + (# of diff direction))

The following DICOM tags contain the information:
(where *.MRDC.1 is the name of DICOM file from the scanner console)

DTI (TENSOR mode) or clinical DWI
$ dcmdump *.MRDC.1 | grep 0021,105a
(0021,105a) SL 16                                       #   4, 1 IntegerSlop
16 --> TENSOR mode (DTI)

Number of Images:
$dcmdump *.MRDC.1 | grep 0020,1002
(0020,1002) IS [8424]                                   #   4, 1 ImagesInAcquisition

Number of T2:
$ dcmdump *.MRDC.1 | grep 0019,10df
(0019,10df) DS [2.000000]                               #   8, 1 UserData

Number of diffusion direction:
$ dcmdump *.MRDC.1 | grep 0019,10e0
(0019,10e0) DS [102.000000]                             #  10, 1 UserData

$ dcmdump *.MRDC.1 | grep 0021,104f
(0021,104f) SS 81                                       #   2, 1 LocationsInAcquisition

For the above example, 
8424 = 81 x (102 +2)

Also, you can extract GE Protocol Data Block from DICOM using `gdcmdump` as a part of DCMTK. The GE Protocol Data Block contains `DIFNUMDIRS`, `DIFNUMT2`, `DFAX`, `NOSLC` and more. 

$ gdcmdump -P -i ${DICOMFILE}

selected list:
```
POSITION "Supine"
ENTRY "Head First"
CLINICALCOIL "C0z8#vBB#D9TBAJjzCrmITA"
COIL "48HAP"
COILPLUGS "GE48chHeadAnt2;GE48chHeadPos2"
PLANE "AXIAL"
SEDESC "DTI_5800"
REVSLICEORDER "0"
HOS "0"
IMODE "2D"
PSEQ "Spin Echo"
IOPT "EDR, Cla, EPI, DIFF, ARC, HB"
PSDNAME "epi2asaltoff"
MULTIBVALUE "3000.0;"
OPTIMIZED_TE "Yes"
MULTINEXVALUE "1.0;"
DFAX "16"
DIFNUMDIRS "102"
DIFNUMT2 "2"
DUALSPINECHO "0"
DIFPROCTYPE "0"
REOPT "2"
TE "Minimum"
NECHO "1"
TR "5800.0"
NUMSHOTS "1"
Rtb0C "0"
DISTORTIONCORRECTION "0"
FOV "24.0"
SLTHICK "1.70"
SPC "0.0"
NOSLC "81"
HOECC "1"
PHASEACCEL "1.00"
MBACCEL "3"
```

**Comment by YoonhoH** [comment]
@neurolabusc Thank you very much for your quick response. Yes, I agree with your comment. It seems that the header information of the image is lacking. However, the hospital where we originally acquired the data has changed MR scanner and there is no way to re-acquire the data through MR scanner, PACS. Previously, we used "dicom2nifti" python-based library to convert the NIfTI file so that we could process the data using MRtrix, FreeSurfer, FSL, SPM, DIPY and perform analysis. As a new topic, I am checking the DICOM to NIfTI step based on dcm2niix. While there were no errors including warnings when converting NIfTI for DWI based on dicom2nifti, the NIfTI conversion from DICOM for DWI had warnings although bvec and bval files were extracted well. So I asked what could be the cause and why it was needed and what impact it could have on the analysis later.    

**Additionally, I have one more question.** 
    - DICOM: LAS (Radiological convention, left-handed, slice orientation: Axial)
    - NIFTI: RAS (Neurological convention, right-handed, slice orientation: Axial)
After converting DICOM to NIfTI for all sequence except T1w using dcm2niix, when I check the converted NIfTI using "fslhd" and "fslorient", it comes out as Radiological convention, but isn't NIfTI supposed to use RAS (Neurological convention). When saving the data in matrix form, the NIfTI is L -> R for a row, P -> A per row, I -> S for stacking, and the DICOM is R -> L for a row, P -> A per row, I -> S for stacking, so in order not to change the way the data is saved or be compatible with FSL, is the converted NIfTI also following the Radiological convention? **Please tell me in detail about it.**


@mr-jaemin Thank you very much for your quick and detailed response. 
928 (images) = 58 (slices) x (1(b0) + 15 (b1000)). 58, 1, and 15 are all estimates.
The hospital where I acquired the data years ago has changed to new MR scanner (GE 1.5T -> Siemens 3T), so I can't see the dicom file name in the scanner console. I've checked everything you told me, including "dcmdump ${dcm path on my computer}| grep 0021,105a", but it doesn't work. For DWI the header of DICOM doesn't have the information from (0021, *) to (0027, *). I also ran "gdcmdump -P -i ${DICOMFILE}" and it says "no pdb tag found".

**Comment by neurolabusc** [comment]
dicom2nifti does not try to extract as much information as dcm2niix. It sounds like your images have enough information for a basic conversion, but you will still need to provide sequence details if you want to use tools that use advanced information (e.g. readout time, phase encoding polarity, slice timing, etc) to remove noise and spatial distortions from your data. So the data you get may be sufficient for some post processing pipelines, but not others. Therefore, it is not possible to give a universal answer for your question.

DICOM and NIfTI use [different spatial coordinates](https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#Spatial_Coordinates). As you note, the identity matrix for a NIfTI image is RAS. dcm2niix provides spatial transformation matrices (sform and qform) that transform the voxels to world space. These transforms allow a NIfTI image to convert any disk order to world space - [here is an example of all 48 combinations](https://github.com/rordenlab/NIfTIspace). Tools like FSL, SPM, FreeSurfer and AFNI use these transforms to determine world space regardless of the disk order of rows, columns and slices. 

You can always follow the steps described in the [Validate DTI Vectors document](https://www.nitrc.org/docman/?group_id=880) to confirm that dcm2niix has correctly transformed your data for analyses with FSL.
