### ISSUE TITLE
dcm2niix append suffix despite `--terse` option

### ISSUE THREAD

**Issue by nbeliy** [rordenlab/dcm2niix#776]
**Describe the bug**

Despite using options `-f %b -w 0 --terse`, dcm2niix appends suffix `_i00003` to converted localizer files.
`dcm2niix` also produce a warning `Slices not stacked: orientation varies (vNav or localizer?)` which may be the cause of the bug.
 
**To reproduce**

1. Run dcm2niix with options `-f %b -w 0 --terse` on `AAHead_Scout` localizer files.
2. See warning `Slices not stacked: orientation varies (vNav or localizer?) [0.996411 0.0739755 -0.0411539 -0.0761216 0.995674 -0.0532874] != [0.996802 0.0719284 -0.0348248 -0.057621 0.948839 0.310459]`
3. Observe appended suffix: `AAHead_Scout_MPR_tra_000000.IMA_i00001.nii.gz`

I'm awaiting authorization to share files that causes this bug.

**Expected behavior**

The `--terse` and `-f %b` should conserve original image files name with changed extension. In this case output file should be `AAHead_Scout_MPR_tra_000000.IMA.nii.gz`

**Output log**

```
./dcm2niix -a y -d 1 -z o -w 0 -f %b --terse -v 1 prepared_dcm/sub-001/ses-/MRI/004-AAHead_Scout_MPR_tra/
Chris Rorden's dcm2niiX version v1.0.20230411  (JP2:OpenJPEG) (JP-LS:CharLS) GCC8.4.0 x86-64 (64-bit Linux)
Found 3 DICOM file(s)
DICOM file: prepared_dcm/sub-001/ses-/MRI/004-AAHead_Scout_MPR_tra/AAHead_Scout_MPR_tra_000001.IMA
 patient position (0020,0032)	-117.928	-162.028	3.26799
 orient (0020,0037)	0.996411	0.0739755	-0.0411539	-0.0761216	0.995674	-0.0532874
 acq 1 img 2 ser 4 dim 162x162x1x1 mm 1.6x1.6x1.6 offset 132008 loc 0 valid 1 ph 0 mag 0 nDTI 0 3d 1 bits 16 littleEndian 1 echo 1 coilCRC -1324010081 TE 1.37 TR 3.15
DICOM file: prepared_dcm/sub-001/ses-/MRI/004-AAHead_Scout_MPR_tra/AAHead_Scout_MPR_tra_000002.IMA
 patient position (0020,0032)	-118.607	-184.912	-66.4728
 orient (0020,0037)	0.996802	0.0719284	-0.0348248	-0.057621	0.948839	0.310459
 acq 1 img 3 ser 4 dim 162x162x1x1 mm 1.6x1.6x1.6 offset 132012 loc 0 valid 1 ph 0 mag 0 nDTI 0 3d 1 bits 16 littleEndian 1 echo 1 coilCRC -1324010081 TE 1.37 TR 3.15
DICOM file: prepared_dcm/sub-001/ses-/MRI/004-AAHead_Scout_MPR_tra/AAHead_Scout_MPR_tra_000000.IMA
 patient position (0020,0032)	-118.311	-170.656	-51.6347
 orient (0020,0037)	0.996159	0.0854107	-0.0193135	-0.0855193	0.996325	-0.00487084
 acq 1 img 1 ser 4 dim 162x162x1x1 mm 1.6x1.6x1.6 offset 132014 loc 0 valid 1 ph 0 mag 0 nDTI 0 3d 1 bits 16 littleEndian 1 echo 1 coilCRC -1324010081 TE 1.37 TR 3.15
Slices not stacked: orientation varies (vNav or localizer?) [0.996411 0.0739755 -0.0411539 -0.0761216 0.995674 -0.0532874] != [0.996802 0.0719284 -0.0348248 -0.057621 0.948839 0.310459]
Converting prepared_dcm/sub-001/ses-/MRI/004-AAHead_Scout_MPR_tra/AAHead_Scout_MPR_tra_000001.IMA
Convert 1 DICOM as prepared_dcm/sub-001/ses-/MRI/004-AAHead_Scout_MPR_tra/AAHead_Scout_MPR_tra_000001.IMA_i00002 (162x162x1x1)
 Optimal piped gz will fail if pigz version < 2.3.4.
Compress: "/usr/bin/pigz" -n -f -6 > "prepared_dcm/sub-001/ses-/MRI/004-AAHead_Scout_MPR_tra/AAHead_Scout_MPR_tra_000001.IMA_i00002.nii.gz"
Converting prepared_dcm/sub-001/ses-/MRI/004-AAHead_Scout_MPR_tra/AAHead_Scout_MPR_tra_000002.IMA
Convert 1 DICOM as prepared_dcm/sub-001/ses-/MRI/004-AAHead_Scout_MPR_tra/AAHead_Scout_MPR_tra_000002.IMA_i00003 (162x162x1x1)
 Optimal piped gz will fail if pigz version < 2.3.4.
Compress: "/usr/bin/pigz" -n -f -6 > "prepared_dcm/sub-001/ses-/MRI/004-AAHead_Scout_MPR_tra/AAHead_Scout_MPR_tra_000002.IMA_i00003.nii.gz"
Converting prepared_dcm/sub-001/ses-/MRI/004-AAHead_Scout_MPR_tra/AAHead_Scout_MPR_tra_000000.IMA
Convert 1 DICOM as prepared_dcm/sub-001/ses-/MRI/004-AAHead_Scout_MPR_tra/AAHead_Scout_MPR_tra_000000.IMA_i00001 (162x162x1x1)
 Optimal piped gz will fail if pigz version < 2.3.4.
Compress: "/usr/bin/pigz" -n -f -6 > "prepared_dcm/sub-001/ses-/MRI/004-AAHead_Scout_MPR_tra/AAHead_Scout_MPR_tra_000000.IMA_i00001.nii.gz"
Conversion required 0.049991 seconds (0.014205 for core code).
```

**Version**

```
./dcm2niix -u
Chris Rorden's dcm2niiX version v1.0.20230411  (JP2:OpenJPEG) (JP-LS:CharLS) GCC8.4.0 x86-64 (64-bit Linux)
Good news: Your version is up to date: v1.0.20230411
```

**Troubleshooting**

 - Using the latest release
 - Tried with development version, bug is still present

**Comment by nbeliy** [comment]
Looking into code, I see that `isAddNamePostFixes` is applied only to subset of suffixes, and it looks a conscious decision.

For my project I need to be able to identify the original DICOM file(s) that correspond to converted ones. And I don't want to parse the log output.

Would it be easy to add an option to add the original file basename to the json?
Or simply, if  `-f %b`, then bypass the generation of the filename (%b should resolve name conflicts by itself).

**Comment by neurolabusc** [comment]
You have an extremely unusual edge case. I do think it would be very easy for you to write a parser to handle this. Alternatively, it is very easy for you to fork dcm2niix to make a custom version tuned to your usage. I am generally reluctant to make changes to the core code to support individual users, as it complicates usage for others, risks unintended consequences and make code maintenance more difficult. In general, dcm2niix behaves in a very predictable though opinionated fashion.

**Comment by neurolabusc** [comment]
@nbeliy the primary issue here is the NIfTI format requires all images in a volume (and a given filename) to share an identical orientation. However, many localizer scans intentionally acquire orthogonal slices to aid positioning of subsequent scans. These localizers typically suffer from partial volume effects and severe interference effects. For the vast majority of users, they are only used for planning subsequent scans, and should be discarded. Supporting extreme edge cases for advanced users can cause unintended consequences for most users. It is easy to write a simple python script to resolve your situation.
