### ISSUE TITLE
"PhaseEncodingDirectionDisplayed" for GE

### ISSUE THREAD

**Issue by mr-jaemin** [rordenlab/dcm2niix#779]
The dev version incorrectly reports the `PhaseEncodingDirectionDisplayed` for GE data as 
```json
"PhaseEncodingDirectionDisplayed": "EPI2",
``` 

The `d->phaseEncodingDirectionDisplayedUIH` is re-utilized for GE in the `setBidsGE`:
```CPP
void setBidsGE(struct TDICOMdata *d, int nConvert, int isVerbose, const char *filename) {
        char seqName[kDICOMStrLarge] = "";
        strcat(seqName, d->phaseEncodingDirectionDisplayedUIH); //prefer InternalPulseSequenceName (0019,109e) 
        if (strlen(seqName) < 1) //fall back PulseSequenceName (0019,109c)
```

Then, the following code, I believe is intended for UIH, is executed for GE
```CPP
json_Str(fp, "\t\"PhaseEncodingDirectionDisplayed\": \"%s\",\n", d.phaseEncodingDirectionDisplayedUIH);
```

So, I would propose to update to 

```CPP
if (d.manufacturer != kMANUFACTURER_GE)
		json_Str(fp, "\t\"PhaseEncodingDirectionDisplayed\": \"%s\",\n", d.phaseEncodingDirectionDisplayedUIH);
```

OR

```CPP
if (d.manufacturer == kMANUFACTURER_UIH)
		json_Str(fp, "\t\"PhaseEncodingDirectionDisplayed\": \"%s\",\n", d.phaseEncodingDirectionDisplayedUIH);
```
To reproduce the issue, you could use any GE diffusion data including the data shared for issue 777. If needed, I could share a sample GE DICOM.

**Comment by neurolabusc** [comment]
@mr-jaemin thanks for spotting this. Can I suggest you provide a PR to the development branch that implements your suggestion:

```
if (d.manufacturer == kMANUFACTURER_UIH)
		json_Str(fp, "\t\"PhaseEncodingDirectionDisplayed\": \"%s\",\n", d.phaseEncodingDirectionDisplayedUIH);
```

**Comment by mr-jaemin** [comment]
@neurolabusc The PR (v1.0.20240123) address the issue. I tested the PR with GE sample datasets.
