### ISSUE TITLE
Please provide instructions

### ISSUE THREAD

**Issue by bananabr** [rordenlab/dcm2niix#783]
Please provide instructions on how to report a security vulnerability. Ideally, follow the instructions at https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing-information-about-vulnerabilities/privately-reporting-a-security-vulnerability to enable private vulnerability reports.

Thank you,

**Comment by neurolabusc** [comment]
Feel free to contact me directly at my [institutional email](https://sc.edu/study/colleges_schools/artsandsciences/psychology/our_people/directory/rorden_chris.php).
