### ISSUE TITLE
Unable to find any DICOM images if the absolute path of input folder too long

### ISSUE THREAD

**Issue by kaworuist** [rordenlab/dcm2niix#784]
**Describe the bug**

I found that if the path to the input folder is too long, dcm2niix will report that the DCM file cannot be found. And this path is an absolute path, whether you enter a relative path or an absolute path when calling dcm2niix, as long as the folder absolute path is too long, it will report an error

**To reproduce**

1. I got a input folder 'C:\Users\test\Downloads\simulation_storage\medicalimagingeu2bst_test\extracted\batch1\CT\dicom\1927_CT_batch_1_part_0\1.3.6.1.4.1.55648.001577591809738666852943447471372937198\1.3.6.1.4.1.55648.001577591809738666852943447471372937198.3'
[simulation_storage_copy.zip](https://github.com/rordenlab/dcm2niix/files/14174056/simulation_storage_copy.zip)

2. cd ''C:\Users\test\Downloads\simulation_storage\medicalimagingeu2bst_test\extracted\batch1\CT\dicom\1927_CT_batch_1_part_0\1.3.6.1.4.1.55648.001577591809738666852943447471372937198'
3. run dcm2niix ./1.3.6.1.4.1.55648.001577591809738666852943447471372937198.3
4.  error: Unable to find any DICOM images in ./1.3.6.1.4.1.55648.001577591809738666852943447471372937198.3 (or subfolders 5 deep)

**Expected behavior**

I hope it should be able to convert normally

**Output log**

If applicable, output generated converting data.

**Version**

Please report the complete version string:

Chris Rorden's dcm2niiX version v1.0.20230411  (JP2:OpenJPEG) (JP-LS:CharLS) MSC1935  (64-bit Windows)

**Comment by neurolabusc** [comment]
@kaworuist this is a limitation of the Windows file system you are using, not dcm2niix. dcm2niix supports longer paths, but Windows is traditionally limited to [260](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry). 
 - [Enable Long Paths in Windows](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry#enable-long-paths-in-windows-10-version-1607-and-later).
 - Use a Unix system like Unix or MacOS (I have not evaluated path length in Windows Subsystem for Linux).
 - Place the input folder in a shorter path e.g. `C:\Users\test\Downloads\simulation_storage\medicalimagingeu2bst_test\extracted\batch1\CT\dicom\1927_CT_batch_1_part_0\...` -> `C:\dcm\...`

**Comment by kaworuist** [comment]
Thanks for your advice, it works fine on Linux, but this error message is a bit misleading for users
