### ISSUE TITLE
Extract kVp into the json file from DICOM header

### ISSUE THREAD

**Issue by pushkarmutha** [rordenlab/dcm2niix#785]
I'm batch converting CT DICOMS to NIFTI using dcm2niix. I love that a json file with acquisition parameters is automatically saved for each series during conversion. I was wondering if there is any way to specify additional parameters from the DICOM header to be saved in the json. I'm particularly interested in saving the CT acquisition kVp.

Thanks!

**Comment by neurolabusc** [comment]
I added some CT-specific fields as described [here](https://github.com/rordenlab/dcm2niix/tree/master/BIDS#modality-computerized-tomography). However, the BIDS BEP PET and ASL committees both chose different names for fields than I had previously used in dcm2niix. This causes issues, as dcm2niix strives to provide both backward and BIDS compatibility. Therefore, moving forward if you want dcm2niix to officially support modality specific features, please make a proposal to extend the BIDS specification. Specifically, you might consider suggesting [from DICOM 00180060](https://dicom.innolitics.com/ciods/digital-x-ray-image/x-ray-generation/00180060) is added to the [BIDS BEP024 (CT)](https://docs.google.com/document/d/1fqnJZ18x5LJC8jiJ8yvPHUGFzNBZ6gW2kywYrUKWtuo/edit#heading=h.bs4ewiqm3qrq). I am CC'ing @Hboni who might have thoughts.

Alternatively, feel free to make a private fork of dcm2niix that retains your preferred features.
