### ISSUE TITLE
setBidsGE fails to recognize Gradient Echo EPI

### ISSUE THREAD

**Issue by mr-jaemin** [rordenlab/dcm2niix#790]
setBidsGE fails to recognize Gradient Echo EPI when (0040,0254) kProcedureStepDescription is non-empty

```cpp
//research mode EP\RM does not discriminate between SE and GE (EP\SE and EP||GR)
	//solution: check procedureStepDescription
	//if (strstr(d->scanningSequence, "EP\\RM")) {
	reportProtocolBlockGE(d, filename, isVerbose);
	if (strstr(d->procedureStepDescription, "Gradient Echo")) {
		isGR = true;
		if (strstr(d->scanningSequence, "EP\\RM"))
			isEPGR = true;
	}
	if (strstr(d->procedureStepDescription, "Spin Echo")) {
		if (strstr(d->scanningSequence, "EP\\RM"))
			isEPSE = true;
	}
```

The routine reportProtocolBlockGE() include the following line
```cpp
if (strlen(d->procedureStepDescription) < 2)
		strcpy(d->procedureStepDescription, seqName);
```

So, if DICOM tag (0040,0254) kProcedureStepDescription > 1
`seqName` such as `Gradient Echo` or `Spin Echo` will not be copied to `procedureStepDescription`

::autoBids:GE usedSeqName:'EPI' seqName:'epialtoff' internalSeqName:'EPI' seriesDesc:'rsfMRI_Run' scanSeq:'EP\RM' stepDesc:'MR30.1 prodrive2' bidsData:'' bidsSuffix:'_acq-EPIm6_dir-PA_run-7'

Could you have any concern with removing `if (strlen(d->procedureStepDescription) < 2)`? 

I can share sample DICOM.

**Comment by mr-jaemin** [comment]
@neurolabusc Do you know whether the `ProcedureStepDescription` is a part of BIDS specs?
If not, we could ignore `ProcedureStepDescription` and replace with `seqName`, assuming we don't want to add another entry such as d->seqName for this.

@brice82

**Comment by neurolabusc** [comment]
@mr-jaemin what do you think about replacing
```
if (strlen(d->procedureStepDescription) < 2)
	strcpy(d->procedureStepDescription, seqName);
```
with
```
strcat(d->procedureStepDescription, seqName);
```
This should allow the subsequent test to discriminate spin from gradient echo if it is in either location.
