### ISSUE TITLE
Q about where json gets written

### ISSUE THREAD

**Issue by mharms** [rordenlab/dcm2niix#794]
Hi,
I'm trying to backtrack where a given value in the sidecar json comes from, in this particular case `CoilString`.
Strangely, when I search the repo for `CoilString`, all it finds is the `BIDS/README.md` file, which is a descriptive file, and not the actual code.  I would have thought that the string `CoilString` has to exist somewhere in the code itself.  (Otherwise how is that field name making it into the json?)

Can you help me understand what I'm missing (or doing wrong with my search)?

thx

**Comment by neurolabusc** [comment]
dcm2niix attempts to populate a string named `coilName`. Hopefully, this comes from the public tag [Receive Coil Name (0018,1250)](https://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.8.13.5.7.html). For Siemens scanners, it will fall back to the private tag 0051,100F. For older Siemens scanners, the value of last resort comes from the [CSA header](https://nipy.org/nibabel/dicom/siemens_csa.html) `sCoilSelectMeas.sCoilStringForConversion`.

**Comment by mharms** [comment]
Thanks, but how does the actual text "CoilString" get into the json itself?  I was expecting to find some `printf` statement involving "CoilString" somewhere, but wasn't able to find that.

**Comment by mharms** [comment]
Thanks.  Do you have any insight as to why a search in the repo for "coilstring" (or "CoilString") only returns the `BIDS/README.md` file?
 
![Screenshot 2024-02-20 at 9 42 09 AM](https://github.com/rordenlab/dcm2niix/assets/3878918/399b4437-1638-4ed4-a0c4-bc07ce06c265)

**Comment by captainnova** [comment]
> Apparently GitHub code search only searches files smaller than 384 KB, and `nii_dicom_batch.cpp` is 413 KB: 

Thanks! I'd noticed yesterday that searches on GH weren't giving accurate results, but had not figured out why.
