### ISSUE TITLE
GE UHP/7T Diffusion SliceTiming

### ISSUE THREAD

**Issue by mr-jaemin** [rordenlab/dcm2niix#796]
As described #635, if GE Premier/UHP/7T use diffusion gradient cycling, the`SliceTiming` can't be described/generated. 

Diffusion gradient cycling mode (`d.diffCyclingModeGE`) can be determined based on `UserData12` (0019,10B3) and/or `UserData15` (0019,10B6).

While curent dcm2niix reliably detects the cycling mode, ABCD patch on UHP/7T uses a different value 0.53 for `UserData15` (0019,10B6), compared to Premier 0.72, reporting the following warning despite of data collected with cycling off:

>Warning: Unable to compute slice times for GE Diffusion:Cycling

User may use the (undocumented) program option(--diffCyclingModeGE 0) to override the cycling mode from DICOM if data is collected with cycling OFF for sure.

**Comment by mr-jaemin** [comment]
Thanks @psadil for reporting this issue.

**Comment by mr-jaemin** [comment]
On GE Premier XT, diffusion data with HCP lifespan, ABCD, ADNI3-Adv, UK BioBank protocol is collected with cycling off. With this dataset, DICOM UserData15 (0019,10B6) will be set to 0.72

On GE UHP, ABCD data(with ABCD patch) is collected with cycling off & DICOM UserData15 (0019,10B6) = 0.53

In addition, on UHP and 7T, if 0.5 < UserData15 (0019,10B6) < 1, diffusion cycling is OFF.

In short, here is the pseudo-code to generate SliceTiming on Premier/UHP/7T:
```
If (Premier) && (UserData15 = 0.72)
    diffCyclingModeGE = 0 (off)
If (UHP or 7T) && (0.5 < UserData15 <1)
    diffCyclingModeGE = 0 (off)
```

**Comment by mr-jaemin** [comment]
The development branch (v1.0.20240222) addressed the issue. 

@psadil please test your dataset.

**Comment by psadil** [comment]
This seems to work for my dataset. I don't have another DWI that was collected on this scanner with an older SoftwareVersion and the same TR, so I can't check for differences in the generated SliceTiming. But the development version of `dcm2niix` (v1.0.20240222) produces SliceTiming without use of the hidden option on the DWI scan collected with "SoftwareVersions": "30\\LX\\SIGNA_LX1.MR30.1_R01_2322.c". Thanks!

**Comment by mr-jaemin** [comment]
After reviewing the GE PSD epi2.e (diffusion) code, updated dcm2niix

from
```
If (UHP or 7T) && (0.5 < UserData15 <1)
    diffCyclingModeGE = 0 (off)
```
To
```
If (UHP or 7T) && (0.5 < UserData15 <= 1.0)
    diffCyclingModeGE = 0 (off)
```
