### ISSUE TITLE
Siemens conversion problems  (Magnetom Altea)

### ISSUE THREAD

**Issue by ClimbMount** [rordenlab/dcm2niix#799]
**Describe the bug**

I work with short-axis cardiac images performing segmentations with AI. I have been using diciom2niix to transform dicom into nifiti. For example, for a Phillips exam, as output I have a matrix (512, 512, 15, 28) in the process of reading the .nii file. By fixing a frame and varying it over the slices, we obtain a volume (as we can see in the image below)

![WhatsApp Image 2024-02-21 at 23 14 14](https://github.com/rordenlab/dcm2niix/assets/26803415/6bec41b0-492a-4f71-a8b0-dce4184e4422)

For GE and Phillips vendors, I have complete success. However, for Simens machines I have problems. Carrying out the same process for a Siemens exam, in the reading process I obtain a matrix (256, 228, 12, 25). By fixing a frame and varying it over the slices, I do not obtain a volume (as we can see in the image below).  

![WhatsApp Image 2024-02-21 at 23 15 07](https://github.com/rordenlab/dcm2niix/assets/26803415/1268ab9b-564c-403b-9585-6c6daaaafdd5)

Indicating an error in the conversion process, perhaps due to the absence of a tag or violation of dicom standards by the vendor. Additionally, I receive warnings during the transformation process:

- siemens moco? bogus slice timing (range -1..-1, tr=64.16 seconds)
- unable to determine slice direction: please check whether slices are flipped
- Weird CSA 'ProtocolSliceNumber'

![WhatsApp Image 2024-02-21 at 21 30 43](https://github.com/rordenlab/dcm2niix/assets/26803415/bedf86fb-f681-4e23-8d4d-bd06a2b2dff3)

Could you help solve this problem? Or suggest any tips?

**Version**

- dicom2nixx v1.0.20230411
- Siemens siemens magnetom altea

**Comment by neurolabusc** [comment]
@ClimbMount This is outside my expertise. I developed dcm2niix for brain imaging studies. Likewise, the NIfTI format has a lot of assumptions that make it simple and popular for brain imaging (e.g. equidistant slices) but not ideal for all medical imaging applications. Usually, moco (motion correction) warnings suggest volumes are changing position/orientation across your volumes, something that the NIfTI format can not handle. I would think the Siemens Research Collaboration Manager associated with the instrument that acquired this will be your best contact. It is their role to help you understand, tune and convert datasets. If you do work out good solutions, feel free to share them with the community.

**Comment by neurolabusc** [comment]
Closing as this is outside my expertise and I can not replicate. Feel free to send a sample dataset to my [institutional email](https://sc.edu/study/colleges_schools/artsandsciences/psychology/our_people/directory/rorden_chris.php) if you need further advice.
