### ISSUE TITLE
Siemens 2D epi TR is incorrect

### ISSUE THREAD

**Issue by pollaro** [rordenlab/dcm2niix#806]
**Describe the bug**

Much like [issue 369](https://github.com/rordenlab/dcm2niix/issues/369), the TR in our dicoms was per slice. It's almost the exact same thing, only ours was acquired on a Siemens Trio.
dcm2niix result:
```      
"Manufacturer": "Siemens",
"ManufacturersModelName": "Trio",
```
```
"MRAcquisitionType": "2D",
"SeriesDescription": "xxxx_epixxxxxx_32sl2080REST",
"ProtocolName": "xxxx_epixxxxx_32sl2080REST",
"ScanningSequence": "SE",
"SequenceVariant": "SP",
"ScanOptions": "FS",
"SequenceName": "EPI2d1",
```
```
"EchoTime": 0.03,
"RepetitionTime": 0.065,
"FlipAngle": 90,
"PartialFourier": 1,
```
DICOM header:
```
0018 0023        2 [1350    ] //       ACQ MR Acquisition Type //2D
0018 0024        6 [1360    ] //              ACQ Sequence Name//EPI2d1
0018 0025        2 [1374    ] //                 ACQ Angio Flag//N 
0018 0050        2 [1384    ] //            ACQ Slice Thickness//2 
0018 0080        2 [1394    ] //            ACQ Repetition Time//65
0018 0081        2 [1404    ] //                  ACQ Echo Time//30
0018 0083        2 [1414    ] //         ACQ Number of Averages//1 
```
I didn't acquire the data myself. I do know where it came from and the TR should be 2.08s (32 * 0.065).

**Expected behavior**

TR should be what the TR is. This isn't your fault, Siemens messes lots of stuff up.

**Version**

dcm2niiX version v1.0.20230411  (JP2:OpenJPEG) (JP-LS:CharLS) GCC8.4.0 x86-64 (64-bit Linux)

**Troubleshooting**

I don't have admin privileges to do all this. I can force them to update if this has already been taken care of.

**Comment by neurolabusc** [comment]
@pollaro dcm2niix assumes that DICOM images are truthful. Note that 0018,0080 reports a 65ms TR. I would expect resting state data on a Trio to list `EP` as the `ScanningSequence`. Indeed, both gradient echo fMRI and spin echo DTI use the Echo Planar core. Note that for EPI data, the BIDS format strictly defines the TR as the time between consecutive sampling of the same slice. However, some MR scanning sequences may have more frequent (perhaps non-selective) excitation pulses.  If you have a protocol PDF for this sequence, it may provide more insight. Likewise, the Siemens Research Collaboration Manager associated with your center can provide insights. You could also peak at the CSA header:

```
gdcmdump --csa /path/to/dicom.dcm > csa.txt
```

**Comment by pollaro** [comment]
@neurolabusc Yeah, that's kind of what I thought. I've gone through the all the info I have. I'm pretty sure that it's a standard GRE-EPI. I'll ask Siemens, but I'm pretty sure they've got the header wrong. Thanks
