### ISSUE TITLE
dcm2niix is incorrectly attempting to use a JPEG:Lossless transfer syntax that was set inside an Original Attributes Sequence

### ISSUE THREAD

**Issue by captainnova** [rordenlab/dcm2niix#807]
Hi, I think this is related to #599, but it is not quite the same.

A few months ago a study site started sending their DICOM with a JPEG transfer syntax UID inside an (0400, 0561):
```
(0400, 0561)  Original Attributes Sequence   3 item(s) ---- 
   (0400, 0550)  Modified Attributes Sequence   1 item(s) ---- 

      ---------
   (0400, 0565) Reason for the Attribute Modificati CS: 'COERCE'
   ---------
   (0400, 0550)  Modified Attributes Sequence   1 item(s) ---- 

      ---------
   (0400, 0565) Reason for the Attribute Modificati CS: 'COERCE'
   ---------
   (0400, 0550)  Modified Attributes Sequence   1 item(s) ---- 
      (0002, 0010) Transfer Syntax UID                 UI: JPEG Lossless, Non-Hierarchical, First-Order Prediction (Process 14 [Selection Value 1])
      ---------
   (0400, 0565) Reason for the Attribute Modificati CS: 'COERCE'
   ---------
```

The actual pixel data of the main image is **not** JPEG compressed, but dcm2niix (v1.0.20221013 and v1.0.20240229) thinks it is and fails with
```
Chris Rorden's dcm2niiX version v1.0.20240229  (JP2:OpenJPEG) (JP-LS:CharLS) GCC8.5.0 x86-64 (64-bit Linux)
Found 46 DICOM file(s)
Illegal DICOM tag 0000,0000 (odd element length 262149): t2st/2.16.124.113543.6006.99.850957480818432503
Warning: DICOM violation (contact vendor): compressed image without image fragments, assuming image offset defined by 0x7FE0,x0010: t2st/2.16.124.113543.6006.99.850957480818432503
Image Decompression is new: please validate conversions
Illegal DICOM tag 0000,000d (odd element length 720905): t2st/2.16.124.113543.6006.99.01969238476368720372
Warning: DICOM violation (contact vendor): compressed image without image fragments, assuming image offset defined by 0x7FE0,x0010: t2st/2.16.124.113543.6006.99.01969238476368720372
Warning: DICOM violation (contact vendor): compressed image without image fragments, assuming image offset defined by 0x7FE0,x0010: t2st/2.16.124.113543.6006.99.02900512483385941720
...
```
If we remove the (0400, 0561) with dcmodify then everything works, but it seems that a more general solution would be for dcm2niix to ignore anything nested inside a (0400, 0561). From reading [this comment in #599](https://github.com/rordenlab/dcm2niix/issues/599#issuecomment-1112000743) and [nii_dicom.cpp](https://github.com/rordenlab/dcm2niix/blob/d635970cff10720cbb53f792a2b6c97dc2251eb7/console/nii_dicom.cpp#L5130):
```c
		if ((groupElement == kItemTag) && (isEncapsulatedData)) { //use this to find image fragment for compressed datasets, e.g. JPEG transfer syntax
			d.imageBytes = dcmInt(4, &buffer[lPos], d.isLittleEndian);
			lPos = lPos + 4;
			lLength = d.imageBytes;
			if (d.imageBytes <= 0) goto skipRemap;
			if (d.imageBytes > 24) {
				/*if (encapsulatedDataFragments < kMaxDTI4D) {
					dti4D->fragmentOffset[encapsulatedDataFragments] = (int)lPos + (int)lFileOffset;
					dti4D->fragmentLength[encapsulatedDataFragments] = lLength;
				}*/
				encapsulatedDataFragments++;
				if (encapsulatedDataFragmentStart == 0)
					encapsulatedDataFragmentStart = (int)lPos + (int)lFileOffset;
			}
		}
		if ((is4000561SQ) || (is00089092SQ))
			groupElement = kUnused; //ignore Original Attributes
		if ((isIconImageSequence) && ((groupElement & 0x0028) == 0x0028))
			groupElement = kUnused; //ignore icon dimensions
``` 
it looks like that was already the intent. But shouldn't the `groupElement = kUnused` clauses come before incrementing of `encapsulatedDataFragments`? I have not checked with a debugger, but maybe in our case the check for compressed data gets triggered before the "ignore it because it's in a Original Attributes sequence" all-clear takes effect.

Is there any reason not to move these two `kUnused` clauses to immediately ahead of the check for compression?

Unlike #599, this data is from Siemens MR B19, not XA30. For what it's worth, dcmodify also complains that this DICOM is invalid, but unfortunately the site claims to be unable to correct things on their end. Fortunately it does not appear to have other problems like overanonymization or obvious Agfa mangling.

Thanks,

Rob

**Comment by neurolabusc** [comment]
@captainnova this issue should be fixed with the change to the development branch. If we can find examples, it might be worth also changing is2005140FSQ and is00089092SQ so they are not simply booleans, but rather track the nesting depth for unlatching.
