### ISSUE TITLE
Incorrectly (IMHO) splits fieldmap magnitude volume into two (adding up to the target # of slices)

### ISSUE THREAD

**Issue by yarikoptic** [rordenlab/dcm2niix#82]
In one of the experiments with consistently the same sequence at the scanner, in some scanning sessions dcm2niix produces 2 magnitude files and some times a single one.  Looking in detail -- here is two acquisitions from the same date, different subjects (thus FOV adjusted between the two):

```shell
(venv)mvdoc@smaug /tmp $ for A in 1 2; do echo $A;  dcm2niix -b y -z i -x n -t n -m n -f fmap -o /tmp/A00012$A/ -s n -v n /mnt/btrfs/dbic/inbox/DICOM/2016/12/04/A00012$A/006*fmap*/000001.dcm; done    
1
Chris Rorden's dcm2niiX version 1Jan2017 (64-bit Linux)
Found 64 DICOM image(s)
slices not stacked: echo varies (TE 7.38, 4.92; echo 2, 1)
Dims 90 90 61 1 1
Warning: Interslice distance varies in this volume (incompatible with NIfTI format).
 Distance from first slice:
dx=[0 2.4 4.8 7.2 9.59999 12 14.4 16.8 19.2 21.6 24 26.4 28.8 31.2 33.6 36 38.4 40.8 43.2 45.6 48 50.4 52.8 55.2 57.6 60 62.4 64.8 67.2 72 74.4 76.8 79.2 81.6 84 86.4 88.8 91.2 93.6 96 98.4 100.8 105.6 110.4 112.8 115.2 117.6 120 122.4 124.8 127.2 129.6 132 134.4 136.8 139.2 141.6 144 146.4 148.8 151.2]
Convert 61 DICOM as /tmp/_e2fmap (90x90x61x1)
slices not stacked: echo varies (TE 4.92, 7.38; echo 1, 2)
Dims 90 90 3 1 1
Warning: Interslice distance varies in this volume (incompatible with NIfTI format).
 Distance from first slice:
dx=[0 33.6 38.4]
Warning: Weird CSA 'ProtocolSliceNumber' (29): SPATIAL, SLICE-ORDER AND DTI TRANSFORMS UNTESTED
Convert 3 DICOM as /tmp/fmap (90x90x3x1)
Conversion required 0.172428 seconds.
2
Chris Rorden's dcm2niiX version 1Jan2017 (64-bit Linux)
Found 64 DICOM image(s)
Convert 64 DICOM as /tmp/fmapa (90x90x64x1)
Conversion required 0.105576 seconds.
```
So -- you can see dcm2niix deciding on first file having inconsistent interslice distance.  Any clues why? (rounding error during comparison or may be some fancy scanner-side motion correction offsetting the target location for the slice)

For some subjects it split into 63+1, for others 62+2, and here it was 61+3 .

Originally found with dcm2niix 20160921+git16-g0339407  and now verified with current master 20160921+git59-gbd1b713

Thank you in advance for looking into it

edit1: output from running with -v y:  http://www.onerussian.com/tmp/dcm2niix-v.log

**Comment by yarikoptic** [comment]
FWIW -- good old dcm2nii seems to "run" and produce a single file but only with a single slice:

```shell
(venv)mvdoc@smaug /tmp $ ( for A in 1 2; do echo $A;  dcm2nii  -x n -t n -m n -f fmap -o /tmp/A00012${A}_/ -s n -v n /mnt/btrfs/dbic/inbox/DICOM/2016/12/04/A00012$A/006*fmap*/000001.dcm; done; )                          
1                                                                                                                   
Chris Rorden's dcm2nii :: 4AUGUST2014 (Debian) 64bit BSD License
reading preferences file /home/mvdoc/.dcm2nii/dcm2nii.ini
Only converting files explicitly specified
Validating 1 potential DICOM images.
Found 1 DICOM images.
Converting 1/1  volumes: 1
000001.dcm->20161204_134217fmapacq24mms006a2001.nii
For slice timing correction: the slice order is interleaved ascending (1,3..,2,4...)
 brightest voxel was 1340: data will be saved as 16-bit signed integer.
GZip...20161204_134217fmapacq24mms006a2001.nii.gz
2
Chris Rorden's dcm2nii :: 4AUGUST2014 (Debian) 64bit BSD License
reading preferences file /home/mvdoc/.dcm2nii/dcm2nii.ini
Only converting files explicitly specified
Validating 1 potential DICOM images.
Found 1 DICOM images.
Converting 1/1  volumes: 1
000001.dcm->20161204_161659fmapacq24mms006a1001.nii
For slice timing correction: the slice order is interleaved ascending (1,3..,2,4...)
 brightest voxel was 1293: data will be saved as 16-bit signed integer.
GZip...20161204_161659fmapacq24mms006a1001.nii.gz
```

```shell
(venv)mvdoc@smaug /tmp $ nib-ls A00012{1,2}_/*nii.gz
A000121_/20161204_134217fmapacq24mms006a2001.nii.gz int16 [ 90,  90,   1] 2.40x2.40x2.40   sform
A000122_/20161204_161659fmapacq24mms006a1001.nii.gz int16 [ 90,  90,   1] 2.40x2.40x2.40   sform
```

**Comment by yarikoptic** [comment]
FWIW -- MRIConvert seems to have the same behavior! (so could be something new "feature" from Siemens):
```shell
(venv)mvdoc@smaug /tmp $ ( for A in 1 2; do echo $A;  mcverter --verbose -n -f nifti  -o /tmp/A00012${A}__/ /mnt/btrfs/dbic/inbox/DICOM/2016/12/04/A00012$A/006*fmap*/; done; ) 
1                                                                       
Adding files...
Converting...
11:10:44: Reading series 1.3.12.2.1107.5.2.43.66112.2016120413491364541802919.0.0.0
Wrote /tmp/A000121__/SID000084_20161204_001_006_fmap_acq-2_4mm_01.nii
Wrote /tmp/A000121__/SID000084_20161204_001_006_fmap_acq-2_4mm_02.nii
Finished
2
Adding files...
Converting...
11:10:45: Reading series 1.3.12.2.1107.5.2.43.66112.2016120416265447522718355.0.0.0
Wrote /tmp/A000122__/SID000085_20161204_001_006_fmap_acq-2_4mm.nii
Finished
(venv)mvdoc@smaug /tmp $ nib-ls A00012{1,2}__/*nii                                                                                                                              
A000121__/SID000084_20161204_001_006_fmap_acq-2_4mm_01.nii uint16 [ 90,  90,   3] 2.40x2.40x33.60   sform
A000121__/SID000084_20161204_001_006_fmap_acq-2_4mm_02.nii uint16 [ 90,  90,  61] 2.40x2.40x2.40    sform
A000122__/SID000085_20161204_001_006_fmap_acq-2_4mm.nii    uint16 [ 90,  90,  64] 2.40x2.40x2.40    sform
```

**Comment by neurolabusc** [comment]
The error appears to be in the export of DICOM images and not in the conversion. Therefore, this is not a problem with dcm2niix or MRIconvert.

I assume the scanner generated 128 images (64 for TE=7.38, 64 for TE=4.92). When all 64 images from the same echo are converted together they convert fine, but when you have 3 from echo=1 (slices 30, 44, 46) and 61 from echo=2 (all other slices) then one should not convert these into a single NIfTI volume. Nor do either of the two "volume" have contiguous slices (required by NIfTI).

To test my hypothesis, export the images directly from the scanner console to a USB stick - there should be 128 images (or more, if you are acquiring phase and magnitude images). The resulting images will be parsed correctly and convert fine. I assume your system of copying DICOM files into folders for conversion is not recognizing the different echoes and therefore files are getting over written.

**Comment by yarikoptic** [comment]
Thank you @neurolabusc!  we will investigate

**Comment by neurolabusc** [comment]
Not directly related to this problem, but the fact that dcm2nii only detects a single file may suggest that these are not DICOM Part 10 compliant images. Rather, these are probably DICOM datasets without the proper DICOM file meta information to make them images. I would suggest making sure your export process appends the meta information header as it will help with compatibility with a lot of tools.

**Comment by kempaaron** [comment]
I am working with older DICOM files that were collected on a SIEMENS. The B0 scan produced two folders, one with 72 images (magnitude) and the other with 36 images (phase). When using dcm2nii I get one NIfTI file for the magnitude and one for the phase. However, when using dcm2niix (in MRIcroGL) I get TWO NIfTI files from the magnitude folder and one for the phase. 
Here is the message I receive from dcm2niix:
Chris Rorden's dcm2niiX version v1.0.20170624 (OpenJPEG build) MSC1900 (64-bit Windows)
Found 72 DICOM image(s)
slices not stacked: echo varies (TE 10.46, 8; echo 2, 1)
Warning: Weird CSA 'ProtocolSliceNumber' (35): SPATIAL, SLICE-ORDER AND DTI TRANSFORMS UNTESTED
Convert 36 DICOM as S:\MJFF_Galvin\MRI\Year_1\MJF046Control\20100116185403__fm2d2r_22 (64x64x36x1)
slices not stacked: echo varies (TE 8, 10.46; echo 1, 2)
Warning: Weird CSA 'ProtocolSliceNumber' (35): SPATIAL, SLICE-ORDER AND DTI TRANSFORMS UNTESTED
Convert 36 DICOM as S:\MJFF_Galvin\MRI\Year_1\MJF046Control\20100116185403__fm2d2r_22_e1 (64x64x36x1)
Conversion required 1.393000 seconds.
"C:\Users\kempaarons\Documents\mricrogl_windows\mricrogl\dcm2niix" -b n -z y -o S:\MJFF_Galvin\MRI\Year_1\MJF046Control -f "%t_%p_%s" "S:\MJFF_Galvin\MRI\Year_1\MJF046Control\1.3.6.1.4.1.14519.5.2.1.7777.7777.190888136092016674252690455425\22"

**Comment by kempaaron** [comment]
Thanks! Any suggestions on how best to combine the two magnitude files into one .nii so that I can use fsl_prepare_fieldmap command?

**Comment by kempaaron** [comment]
Oh, I see that either of the magnitude images can be used to create the mask for FEAT: https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FUGUE/Guide
As such, I guess it doesn't really matter that I get separate magnitude files for each TE.

**Comment by neurolabusc** [comment]
Precisely - you can use either. If you look at the dcm2nii magnitude image you will see it is a 4D image with two volumes, one for each echo time. In contrast, dcm2niix segments these into two 3D volumes.
