### ISSUE TITLE
Incorrect output files name for a duel echo image.

### ISSUE THREAD

**Issue by MRIDude** [rordenlab/dcm2niix#821]
Hello
I have some duel-echo 2D TSE data. When given to dcm2niix, it labels the first each with an e15 and the second echo as e1 when it should be e1 and e2.   I am using the latest version on dcm2niix. 
I typed in the following command
`dcm2niix -o . -f tse_2d <folder>`
I get 
tse_2d_e1.nii
tse_2d_e15.nii

The have a suspicion the issue is the fact that the echo number in the DICOM headers are 0 and 1. 

I cannot send DICOMS. I saved the DICOM headers to a text. See below. 
[tse_firstecho.txt](https://github.com/rordenlab/dcm2niix/files/15327695/tse_firstecho.txt)
[tse_secondecho.txt](https://github.com/rordenlab/dcm2niix/files/15327696/tse_secondecho.txt)

**Comment by neurolabusc** [comment]
This is an issue with your impoverished images, not dcm2niix. This data comes from `syngo MR 2004A 4VA25A` (from 2004, so 20 years ago). At that stage, the sequence details stored in the DICOM header was very limited. Indeed, all the VA generation created impoverished images. Things improved greatly with the VB series (I think VB11 was released around 2006).
