### ISSUE TITLE
The whole image is inverted in the result of the dcm2nii.gz conversion

### ISSUE THREAD

**Issue by angleboy8** [rordenlab/dcm2niix#822]
![2](https://github.com/rordenlab/dcm2niix/assets/20549943/ba51c047-ffe7-44be-b51c-a2b5534c91c2)
After dicom files are converted to nii.gz files, the left and right sides of the image and the top and bottom of that are reversed. The running code is "dcm2niix.exe -f "outputname" -i y -m y -p y -x y -z y -b n -o "nii files path" "dicom files path". 
How to resolve this issue? Thank you.

**Comment by neurolabusc** [comment]
I do not have access to a dataset to replicate nor do I use Slicer3D, so this is my best guess. I think this just reflects that [NIfTI and DICOM have different spatial coordinates](https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#Spatial_Coordinates). Specifically, NIfTI uses RAS while DICOM uses LPS. To test my hypothesis, drag and drop your [NiiVue](https://niivue.github.io/niivue/features/basic.multiplanar.html) and ensure the (L)eft, (S)uperior and (P)osterior text is correct.

**Comment by Ernest861** [comment]
I found that turning the results directly with the parameters didn't turn out in the right direction, and I'd like to tweak them in bulk, but I don't know how to write the parameters to batch.

the args used to convert the dicom to nii
![bidscoin](https://github.com/rordenlab/dcm2niix/assets/28133972/a12ebba4-b3b7-42f5-90f7-c4dec91b7d87)

the converted nii with error orientation
![sub09anat](https://github.com/rordenlab/dcm2niix/assets/28133972/c4b600cd-6a96-4cff-a15a-26735a379877)

 the right orientation by the import > tools > rotation
![reoratation](https://github.com/rordenlab/dcm2niix/assets/28133972/afbf4b31-731e-4fc1-8f41-c93a68d767e3)

**Comment by neurolabusc** [comment]
Hello, I am not sure that the dcm2niix issue board is the correct place for this as you are using bidscoin (a dcm2niix wrapper) and MRIcroGL. However, I will try my best. Many quadruped scans have errors in terms of defining the patient position, and different templates use different rotations. This may require you to rotate the NIfTI spatial transformation to match your desired orientation. When you run MRIcroGL from the command line and choose to re-orient an image, you will notice it will provide the permutation required to the columns, rows and slices to get them to match the NIfTI identity matrix:
```
Reorient Dimensions -1 3 -2
```
You could always use this to write a nibabel batch script to adjust the NIfTI affine for a huge number of images that required the same rotation. I am not a nibabel expert, but I think ChatGPT can give you some good hints on how to achieve this.
