### ISSUE TITLE
PyPI missing releases newer than v1.0.20220715

### ISSUE THREAD

**Issue by ericearl** [rordenlab/dcm2niix#829]
**Describe the bug**

PyPI appears to be missing releases of dcm2niix beyond v1.0.20220715.

**To reproduce**

Look here: https://pypi.org/project/dcm2niix/#history

**Expected behavior**

I was hoping to see all releases (or at least the stable ones) from here: https://github.com/rordenlab/dcm2niix/releases

**Version**

I would like to pip install from the Python Package Index (using Python Poetry) the latest stable version: v1.0.20240202.

**Comment by neurolabusc** [comment]
@casperdcl I know you support a huge number of projects, but this request seems to be in your wheelhouse.

**Comment by ericearl** [comment]
A minor additional discovery here... the v1.0.20220715 package actually seems to be a package of v1.0.20220505 on the command line after pip-installing.

**Comment by rbonicel** [comment]
Hi,

I just wanted to know if the newest version of dcm2niix will be available on PyPI in the future, please ? I'm not so at ease with installation methods other than pip, when it comes to working with virtual envs (via Pyenv and Poetry). Don't want to bother, but I'm not familiar with how `apt-get install` goes along with pyenv.

If it's not planned, I'll use another listed method, no problem.

Thanks

Robin

**Comment by neurolabusc** [comment]
Will be fixed with upcoming stable release.
