### ISSUE TITLE
What is `offset` and `Valid 0`

### ISSUE THREAD

**Issue by toomanycats** [rordenlab/dcm2niix#831]
While stacking 90 Siemen's MOSAIC DICOMs  into a 4D ASL data set, I see that only 89 make it into the NiFTI.
Using the verbose flag, there's one DICOM that stands out as the problem.

Also this line hiding at the end:
`Slices stacked despite varying acquisition numbers (if this is not desired recompile with 'mySegmentByAcq')`

I don't understand what that means. I see `(0020,0012)` going from 1 - 90 which I assume is expected.

This is what I suspect the offending DICOM is:

```DICOM file: ./1.3.12.2.1107.5.2.19.45205.2023062117334580829562634.dcm
 patient position (0020,0032)   -893.117        -798.041        49.3586
 orient (0020,0037)     0.997922        -0.0336091      0.0549771       0.0446173       0.975983        -0.213228
 acq 90 img 90 ser 35 dim 688x688x1x1 mm 2.5x2.5x2.497 offset 0 loc 0 valid 0 ph 0 mag 1 nDTI 0 3d 0 bits 16 littleEndian 1 echo 1 coilCRC 0 TE 19.5 TR 3725
```
The keyword `offset` in this context, implies to me the location of binary data. Is this DICOM missing something ?

TIA !

UPDATE: Suspecting that there's no image data in the above DICOM, I opened it with `Pydicom`.

    import pydicom
    img = pydicom.read_file("./1.3.12.2.1107.5.2.19.45205.2023062117334580829562634.dcm")
    img.pixel_array

    AttributeError: Unable to convert the pixel data: one of Pixel Data, Float Pixel Data or Double Float Pixel Data must be present in the dataset

**Comment by neurolabusc** [comment]
dcm2niix should handle most Siemens ASL data - [here are validation datasets for product and research sequences](https://github.com/neurolabusc/dcm_qa_asl). I sounds like one of your images is corrupted - perhaps looking at file size will determine this. I often rename my DICOMs with sensible filenames so I can see which instance is unusual.
```
dcm2niix -r y /path/to/DICOMs
```
dcm2niix assumes the DICOM images are truthful and valid.

**Comment by toomanycats** [comment]
Thanks for the ideas, I'll check the file size. As for naming, my lab has a fairly robust inventory ingestion system into a database.
We group sequences into nicely named directories. However, the DICOM rename feature of `dcm2niix` is a great asset. 

Cheers

**Comment by toomanycats** [comment]
Definitely missing data in the above referenced DICOM:

```
bytes    path
1088    ./1.3.12.2.1107.5.2.19.45205.2023062117332277838461924.dcm
1088    ./1.3.12.2.1107.5.2.19.45205.2023062117332710814062066.dcm
1088    ./1.3.12.2.1107.5.2.19.45205.2023062117333580568762226.dcm
1088    ./1.3.12.2.1107.5.2.19.45205.2023062117333639544962352.dcm
1088    ./1.3.12.2.1107.5.2.19.45205.202306211733378530262492.dcm
24      ./1.3.12.2.1107.5.2.19.45205.2023062117334580829562634.dcm
```

**Comment by toomanycats** [comment]
Definitely missing data in the above referenced DICOM:

bytes    path
1088    ./1.3.12.2.1107.5.2.19.45205.2023062117332277838461924.dcm
1088    ./1.3.12.2.1107.5.2.19.45205.2023062117332710814062066.dcm
1088    ./1.3.12.2.1107.5.2.19.45205.2023062117333580568762226.dcm
1088    ./1.3.12.2.1107.5.2.19.45205.2023062117333639544962352.dcm
1088    ./1.3.12.2.1107.5.2.19.45205.202306211733378530262492.dcm
24      ./1.3.12.2.1107.5.2.19.45205.2023062117334580829562634.dcm

**Comment by neurolabusc** [comment]
For booleans in C, `true` is 1 and `false` is zero, so `valid 0` means invalid. It is worth noting that not all DICOM files are image files, and dcm2niix only converts images, so it may consider a file an invalid image even though it is a valid DICOM file.

**Comment by toomanycats** [comment]
Unrelated question. I've been reading the source code for `gdcm` and trying to learn the DICOM standard better for MRI.
I didn't see that `dcm2niix` uses those libraries. Did you reimplement those methods ? Would you mind pointing me to them, as I didn't see them in the source.

**Comment by neurolabusc** [comment]
DICOM is very complex. It is interpretted differently by different manufacturer, has different styles (implicit vs explicit VR, big vs little endian) and has evolved over time (e.g. enhanced DICOM). I do think you could parse the output of `gdcmdump` or `dcmdump`. Personally, I think a bash solution will prove fragile, and I would suggest some of the great Python tools - ChatGPT can help with this. 

dcm2niix has minimal dependencies and parses DICOM headers internally. The code is focused on performance, not readability and would be ill suited for your use case.

We aware Siemens scanners can export images as proper DICOM files but also DICOM fragments (which lack the `DICM` signature), so even detecting whether a file is a DICOM image is not as simple as you might expect.

**Comment by toomanycats** [comment]
Yeah I do parse `dcmdump` which is reasonably fast. I like to practice reading binary and parsing it when the opportunity arises.
I studied physics and have large gaps in my computer science understanding.

Pydicom is written using the typing extension and is really fast. That would be the best way to create an inventory program I think. `vtk-dicom` has a nice `dicomtocsv` binary but it's a PITA to compile. The `scanner` binary in `gdcm` is slow...as is the sqlite example they provide. Been thinking of practicing some C by using pthreads on that example to speed it up.
