### ISSUE TITLE
Error in bvec extraction when UIH diffusion data is converted to nifti

### ISSUE THREAD

**Issue by XYWCQM** [rordenlab/dcm2niix#836]
Hello:
When I converted the UIH diffusion data using the latest Releases version (version 2-February-2024) of dcm2niix, I found that the generated bvec file was reading from the (0018,9089) tag and not from (0065,1037). The correct bvec for UIH should be read from (0065,1037), because the bvec in there takes into account the true orientation of the rotated orientation frame, whereas the (0018,9089) tag holds the original, unrotated orientation.
PS: I tested it with a previous version of dcm2niix and its extracted bvec is read from (0065,1037).

**Comment by neurolabusc** [comment]
Please work with UIH to resolve this. [0018,9089](https://dicom.innolitics.com/ciods/enhanced-mr-image/enhanced-mr-image-multi-frame-functional-groups/52009229/00189117/00189076/00189089) is a public tag with a clearly defined interpretation. dcm2niix assumes that DICOM images are truthful. If this is not the case, your images are in violation of the DICOM standard. The manufacturer has an obligation to meet their DICOM conformance statement. While manufacturers are allow to define private tags as they wish, they are required to obey the standard if they employ public tags.

While we could add a kludge to dcm2niix to handle errors, I am reluctant to do so. The resulting images would break other tools, and dcm2niix would fail when the vendor updates their software to match the DICOM specification.

**Comment by XYWCQM** [comment]
Thanks, I'll try to talk to the manufacturer.

**Comment by neurolabusc** [comment]
I have added a kludge that gives precedence to the private tag if the manufacturer is UIH. However, it would be great to see public tags providing correct values to ensure compatibility with other tools.

**Comment by malaterre** [comment]
> Hello: When I converted the UIH diffusion data using the latest Releases version (version 2-February-2024) of dcm2niix, I found that the generated bvec file was reading from the (0018,9089) tag and not from (0065,1037). The correct bvec for UIH should be read from (0065,1037), because the bvec in there takes into account the true orientation of the rotated orientation frame, whereas the (0018,9089) tag holds the original, unrotated orientation. PS: I tested it with a previous version of dcm2niix and its extracted bvec is read from (0065,1037).

Confirmed today with:

```
% gdcmdump vframe.dcm | grep Orientation
(0018,9089) FD 0.430938\-0.849997\-0.302969                       # 24,3 Diffusion Gradient Orientation
(0020,0037) DS [0.986552119\0.163446918\2.78621087e-06\-0.16336222\0.986040413\0.0322046392 ]         # 76,6 Image Orientation (Patient)
(0065,1037) FD 0.286213\-0.918287\-0.273538                       # 24,3 MRDiffusionGradOrientation
```
