### ISSUE TITLE
Incorrect 3D reconstruction for enhanced multi-frame MRI

### ISSUE THREAD

**Issue by lassoan** [rordenlab/dcm2niix#839]
**Describe the bug**

[A user sent us an enhanced multi-frame MRI](https://discourse.slicer.org/t/wrong-order-of-slices-from-slice-packages/37606) that was loaded into 3D Slicer using ITK (GDCM) reader with slices out of order:

![image](https://github.com/user-attachments/assets/1504766d-0f8d-4bc5-be24-03b76eb957bd)

I was hoping that dcm2niix can deal with it, but unfortunately it created a 4D volume from it, with incorrect slice positions (all 3 subvolumes were in the same position).
The image contains 3 stacks, which could explain the splitting into 3 subvolumes, but it would be nice to have an option to merge them into a single 3D volume, as the slices actually make up a single 3D volume with uniform slice spacing. The `-m y` option did not help (output was still a 4D volume).

**To reproduce**

1. Run the command 'dcm2niix -m y .' with this image in the folder: https://github.com/lassoan/PublicTestingData/releases/download/data/ScrambledEnhancedMRI.dcm
2. The generated image is not a 3D volume, but 4D, with all 3 stacks in the same position.

**Expected behavior**

Output file is a single 3D volume.

**Output log**

```
Chris Rorden's dcm2niiX version v1.0.20240202  (JP2:OpenJPEG) (JP-LS:CharLS) MSC1938  (64-bit Windows)
Found 1 DICOM file(s)
Warning: Anatomical Orientation Type (0010,2210) is QUADRUPED: rotate coordinates accordingly (issue 642)
Convert 1 DICOM as .\_T2_TurboRARE_20240724111850_50001g (256x256x14x3)
Conversion required 0.059000 seconds.
```

**Version**

Please report the complete version string:

`Chris Rorden's dcm2niiX version v1.0.20240202  (JP2:OpenJPEG) (JP-LS:CharLS) MSC1938  (64-bit Windows)`

This is the latest stable version. The issue is the same with the latest commit (appveyor-built artifact).

**Comment by neurolabusc** [comment]
dcm2niix assumes that DICOM images are truthful. This enhanced DICOM provides two incompatible descriptions for the 42 slices. If you order the slices by FrameAcquisitionNumber which has a range of 1..42 you would get the correct result. However, the canonical interpretation seems to be that this is 3 stacks with a very different slice order. The data below is the output of dcmdump, where I only show details from the slices that bound each dimension. Giving precedence to the FrameAcquisitionNumber would have unintended consequences for many sequences, including interleaved EPI. I do think some complicated logic could be added to detect this. However, my sense is that this will cause issues with other tools. I would recommend working with the manufacturer (Bruker BioSpin MRI GmbH) to fix this at the source. I note that most other tools (dicm2nii, Horos, etc) provide the same interpretation as dcm2niix. I would certainly not consider this data of archival quality. The DICOM standard is very complex, and it is important to not only follow the specification but also the simple conventions of the large manufacturers. While the manufacturer resolves this, the user may want to try out [mrconvert](https://mrtrix.readthedocs.io/en/dev/reference/commands/mrconvert.html) which at least as of v3.0.4 seems to provide the desired conversion.

```
        (0020,9056) SH [1]                                      #   2, 1 StackID
        (0020,9057) UL 1                                        #   4, 1 InStackPositionNumber
        (0020,9128) UL 1                                        #   4, 1 TemporalPositionIndex
        (0020,9156) US 28                                       #   2, 1 FrameAcquisitionNumber
        (0020,9157) UL 1\1                                      #   8, 2 DimensionIndexValues
...
        (0020,9056) SH [3]                                      #   2, 1 StackID
        (0020,9057) UL 1                                        #   4, 1 InStackPositionNumber
        (0020,9128) UL 1                                        #   4, 1 TemporalPositionIndex
        (0020,9156) US 42                                       #   2, 1 FrameAcquisitionNumber
        (0020,9157) UL 3\1                                      #   8, 2 DimensionIndexValues
...
        (0020,9056) SH [1]                                      #   2, 1 StackID
        (0020,9057) UL 14                                       #   4, 1 InStackPositionNumber
        (0020,9128) UL 1                                        #   4, 1 TemporalPositionIndex
        (0020,9156) US 1                                        #   2, 1 FrameAcquisitionNumber
        (0020,9157) UL 1\14                                     #   8, 2 DimensionIndexValues
...
        (0020,9056) SH [3]                                      #   2, 1 StackID
        (0020,9057) UL 14                                       #   4, 1 InStackPositionNumber
        (0020,9128) UL 1                                        #   4, 1 TemporalPositionIndex
        (0020,9156) US 15                                       #   2, 1 FrameAcquisitionNumber
        (0020,9157) UL 3\14                                     #   8, 2 DimensionIndexValues
```

**Comment by lassoan** [comment]
Thank you for the quick analysis and the tip of using mrconvert for this!

I would just note that if all stacking/grouping were ignored and all the slices were simply put into a volume based on their ImagePositionPatient and ImageOrientationPatient tags then the result would be a correct 3D volume. The grouping of frames of course should not be ignored by default, but an option could be added to force putting all frames into a single volume. The `-m` option seems to do something similar, maybe it could be used for this, too.

**Comment by neurolabusc** [comment]
@lassoan can you test out the latest commit to the development branch (v1.0.20240730). In particular, I am traveling and can not test on a Windows system (my current implementation uses the stack, which tends to be constrained on Windows). I do want to note that for this example the FrameAcquisitionNumber is also not ordered spatially. So my kludge is triggered when repetitions of the first InStackPositionNumber refers to slices with different spatial position. If this is the case, it falls back to a Hail Mary of using [Image Position (0020,0032)](https://dicom.innolitics.com/ciods/rt-dose/image-plane/00200032) to order slices. Obviously, this trick only works with 3D acquisitions. 

I am not yet committed to this kludge, and we will need to do a lot of testing to ensure there are no unintended consequences (e.g. rounding errors with image position that might trigger this new behavior). From my perspective, the DimensionIndexValues (0020,9157) of enhanced DICOM provide a very strict recipe that must be truthful. If the manufacturer saves data as DICOM, they are obligated to conform to the standard. Even if we patch a few tools, these images will disrupt any tool that obeys the standard.

**Comment by lassoan** [comment]
Thanks a lot for the quick update. I've tested this on Windows and it works perfectly! I'll ask the user to report the problems to Bruker.
