### ISSUE TITLE
Feature request: Instead of providing a source directory, would it be possible to provide dcm2niix a list of files to be processed?

### ISSUE THREAD

**Issue by BlakeGFitch** [rordenlab/dcm2niix#840]
Hello All,

We have automation that runs dcm2niix on inbound DICOM files, once per series. Currently, a staging directory is created with the DICOMs from a single series and that directory is passed as the input area.

I'd prefer to prepare a single file with a list of DICOM files in a serieis which will be selected out of a directory with a very large number of DICOM files.

Tar accepts a list of files -- that is the kind of function hoped for.

Thanks for your consideration!

Best,
Blake

**Comment by neurolabusc** [comment]
Blake,
  For classic DICOM, a single DTI or fMRI series can be composed of thousands of files. This makes specifying each and every filename inefficient. The dcm2niix approach is to use the `-n` argument.

```
  -n : only convert this series CRC number - can be used up to 16 times (default convert all)
```

For example, consider the [160 files from this T1 scan with SeriesInstanceUID (0020,000e)](https://github.com/neurolabusc/dcm_qa_uih/tree/master) "1.2.156.112605.14038013508437.20180925052418.3.14156.1" which you can convert to the CRC32 4042640119:

```python
import binascii
uid = "1.2.156.112605.14038013508437.20180925052418.3.14156.1"
input_bytes = uid.encode('utf-8')
crc32_value = binascii.crc32(input_bytes) & 0xffffffff  # Ensure it is in unsigned 32-bit format
print(crc32_value)
```
Therefore, you can convert just this series with the command
```bash
$ dcm2niix -n 4042640119 /path/to /DICOMs
```
If reading DICOM headers with Python is slow, you can have dcm2niix report all the series CRCs by passing the `-n -1` argument:
```bash
$ dcm2niix -n -1 /Users/chris/Desktop/mixed            
Chris Rorden's dcm2niiX version v1.0.20240327  Clang14.0.3 ARM (64-bit MacOS)
Found 177 DICOM file(s)
	2150155685	/Users/chris/Desktop/mixed/mixed_dti_tra_dir16_PA_rot_132222_12
 /Users/chris/Desktop/mixed/12_dti_tra_dir16_PA_rot/0001_1.2.156.112605.14038013508437.20180925054056.4.12348.25.dcm
	4042640119	/Users/chris/Desktop/mixed/mixed_t1_gre_fsp_3d_sag_132222_2
 /Users/chris/Desktop/mixed/12_dti_tra_dir16_PA_rot/0001_1.2.156.112605.14038013508437.20180925052757.4.14156.11.dcm
Conversion required 0.149618 seconds (0.072855 for core code).
```
Call dcm2niix multiple times if you have more than 16 series you wish to convert.
