### ISSUE TITLE
XA-series missing minor version tracking in sidecar

### ISSUE THREAD

**Issue by bpinsard** [rordenlab/dcm2niix#848]
Hi!

Seems like with the XA series there are no human-readable way to track the scanner software minor versions in data like it was done before.
https://github.com/rordenlab/dcm2niix/blob/6944cad3f1e306886ce0e051a8cbbf688efbd2b4/BIDS/README.md?plain=1#L320 that tag is no longer present (while XA data still contains MRPhoenix data).

Only `sProtConsistencyInfo.ulConvFromVersion`  remains in that section which is a 8 digit number. was `51130001` in our VE11C `63010001` in [XA30 data](https://github.com/neurolabusc/dcm_qa_xa30), `61010002` in [XA10 data](https://github.com/neurolabusc/dcm_qa_enh/tree/master/In/Siemens/XA10).
The logic seems to be that 6 is XA (while 5 was V-series), the next 2 numbers seems to be the XA major variant (10,30,61...), and the fourth would relate to some minor version (usually a letter in human-readable version) and the rest could be "patches" or "service pack". 

Would it make sense to export that string in the sidecar `ConsistencyInfo` for XA-dicoms? Or create a new field?

Thanks!

**Comment by neurolabusc** [comment]
@bpinsard please test the development version and close this issue if it resolves this issue. My latest commit looks give precedence to `sProtConsistencyInfo.tMeasuredBaselineString` (e.g. `N4_VE11C_LATEST_20160120`), and if that does not exist falls back to `sProtConsistencyInfo.tBaselineString` (e.g. `N4_VB17A_LATEST_20090307`) and if that does not exist uses the hail Mary `sProtConsistencyInfo.ulConvFromVersion` (e.g. `63010001`). It seems that Siemens is not very consistent with their naming of their private consistency strings.

**Comment by bpinsard** [comment]
That's perfect! Many thanks for the super-fast resolving!

**Comment by mharms** [comment]
Out of curiosity, I compared the value of `sProtConsistencyInfo.ulConvFromVersion` from two XA30 systems, one with SP02 and one with SP03.  For both, the value was `63010001`.  So, that value does not appear to capture "service pack" level information.

**Comment by mharms** [comment]
If someone has an example of how `sProtConsistencyInfo.ulConvFromVersion` captures something beyond XA major variant (10,30,61,...), please post.

**Comment by bpinsard** [comment]
Thanks for that info, I too have limited data on XA-series. If that's the case, I guess we have no choice but to ask Siemens for that critical info to make it back into the dicoms.

**Comment by neurolabusc** [comment]
@bpinsard I am closing this issue as there is nothing more for the dcm2niix to do. The development branch does now report the data provided by XA systems. To the best of my knowledge, it does not include data about service packs and other features. Specifically, I worked closely with the Siemens engineers in helping ensure that XA20 DICOMs included the sequence details required for reproducible science (XA10 and XA11 create impoverished BIDS headers). I specifically requested that they include patch details, but this was not included. I do encourage you to lobby the Siemens Research Collaboration Manager associated with your center to include this information. However, open issues on dcm2niix denote topics where we are able to actively make progress.

Therefore, the `acknowledged` label is appropriate. I agree it would be great to have patch version details, but this must happen up stream.

**Comment by bpinsard** [comment]
Agreed, thanks!
