### ISSUE TITLE
Incorrect value of PhaseEncodingDirection on Siemens 3D T2w SPACE scans

### ISSUE THREAD

**Issue by mharms** [rordenlab/dcm2niix#849]
3D T2w SPACE scans on Siemens acquired with a typical `Sagittal` orientation with `A >> P` phase encoding direction end up with a sidecar json entry of ` "PhaseEncodingDirection": "i"`, which implies a R/L phase encoding axis after the inherent reorientation/rotation by `dcm2niix` of a 3D scan into a "RAS" oriented volume.  Either `PhaseEncodingDirection` should not be reported if the reorientation changes the volume orientation (easiest), or should be adjusted to reflect the consequence of the reorientation (harder).

3D T1w MPRAGE scans from Siemens do NOT have a reported `PhaseEncodingDirection` value in their json.  I'm not sure if that is because the relevant DICOM field is missing from the MPRAGE (but present in the SPACE), or if the `dcm2niix` code ignores the value for the MPRAGE (but not for the T2w SPACE).

**Comment by neurolabusc** [comment]
@mharms I agree that we should only use the PhaseEncodingDirection for 2D sequences. Can you share a sample with my institutional address. It is worth noting that 3D sequences use phase encoding for [two of the three dimensions](https://s.mriquestions.com/choosing-pefe-direction.html) (e.g. phase encoding is also used in the `slice` direction).

**Comment by mharms** [comment]
Sure, will do.  Meanwhile, I'll post the following interesting observation here, related to versioning.

I'm getting a `PhaseEncodingDirection` tag for a T2w SPACE scan for versions `v1.0.20220720` and `v1.0.20240202`, but not for the stable release between those two, `v1.0.20230411`

**Comment by neurolabusc** [comment]
@mharms please test latest commit to development branch and close this issue if it correctly resolves this.

**Comment by mharms** [comment]
Good. Thanks.
