### ISSUE TITLE
Add github pages demo for dcm2niix WASM with Niivue

### ISSUE THREAD

**Issue by hanayik** [rordenlab/dcm2niix#859]
- show both file dialog use and drag and drop use

**Comment by neurolabusc** [comment]
Closing. Fully functional demo [source](https://github.com/niivue/niivue-dcm2niix) and [live demo](https://niivue.github.io/niivue-dcm2niix/) provide zero-footprint webassembly dcm2niix that works regardless of hardware or operating system. Good job @hanayik
