### ISSUE TITLE
SIEMENS XA50 DIFFUSION DATA

### ISSUE THREAD

**Issue by jim-uofu** [rordenlab/dcm2niix#860]
**Describe the bug**

Used  20240202 version of dcm2niix to convert enhanced-format diffusion data from a Siemens vida scanner running XA50.

bvec table has right number of entries but the vectors are not unit length.

I have read about the problems with dicom headers on vida scanners, and wonder if anyone has successfully used dcm2niix for DTI data?

THANK YOU!

Jim

1. Siemens SMS sequence, acceleration factor PE = 2, SMS factor = 2 (i.e. multiband=2).
2. Standard 30 direction Siemens diffusion sequence
3. Export as enhanced data
4. convert with ./dcm2niix -f %f -o phant_1avg_nii4d phant_1avg

**Expected behavior**

The bval table is perfect. Hoped for same in bvec table.

The first four vectors of the bvec table are:
0
-0.203826 0.197655 0.401954
-0.403124 -0.20186 -0.852643
-0.730265 -0.407187 -0.732182

where ‘0’ is of course the image acquired with no diffusion gradients,
and the length of the last three vectors is 0.8587, 0.4956, 1.1936, rather than 1.

I’m running this on Mac OS with Sonoma 14.5, and compiled the development version of dcm2niix described below and got the same result.

**Output log**

CSA slice timing based on 2nd volume, 1st volume corrupted (CMRR bug, range 0..5625, TR=4600 ms)
Convert 31 DICOM as phant_1avg_nii4d/phant_1avg (88x88x48x31)
Conversion required 0.120298 seconds (0.105328 for core code).

**Version**

Chris Rorden's dcm2niiX version v1.0.20240202  (JP2:OpenJPEG) (JP-LS:CharLS) Clang11.0.0 x86-64 (64-bit MacOS)

** COPY AND PASTE THE BVEC FILE**

0 -0.203826 0.197655 0.401954 -0.403124 -0.20186 -0.852643 -0.730265 -0.407187 -0.732182 -0.650957 -0.32276 -0.325421 -0.65167 -0.978962 -0.856532 0.00074141 0.00316472 0.655362 0.330741 0.197945 0.204632 0.651768 0.323933 0.200179 0.403123 0.731519 0.727675 0.851636 0.859013 0.979498
0 0.519874 0.520549 0.177496 0.731505 0.941503 0.519067 0.520872 0.177819 0.177553 0.731183 0.941338 0.522266 0.52244 0.177561 0.178121 0.734063 0.943261 0.521366 0.523008 -0.17697 0.178127 0.731243 0.941485 0.940238 0.731505 0.177571 0.519809 0.520007 0.178564 0.177474
0 -0.82957 -0.830639 -0.898292 -0.549901 -0.269862 -0.0597382 -0.442047 -0.895868 -0.657559 0.204023 0.0985331 0.788251 0.549893 0.100522 0.484382 0.679081 0.332038 0.546514 0.78554 -0.964105 0.962495 0.201203 0.0931291 -0.275466 -0.549901 -0.658292 -0.447536 -0.0656471 0.479804 0.0953242

**Troubleshooting**

Please try the following steps to resolve your issue:

 - Is this the [latest stable release](https://github.com/rordenlab/dcm2niix/releases)? If not, does the latest stable release resolve your issue?
 - If the latest stable version fails, and you are using Windows. Does the latest commit on the development branch resolve your issue? You can get a pre-compiled version from [AppVeyor](https://ci.appveyor.com/project/neurolabusc/dcm2niix) (click on the Artifacts button).
 - If the latest stable version fails, and you are using macOS or Linux. Does the latest commit on the development branch resolve your issue? You can build this using the recipe below:

```
git clone --branch development https://github.com/rordenlab/dcm2niix.git
cd dcm2niix/console
make
./dcm2niix ….
```

**Comment by neurolabusc** [comment]
1. Can you upload the entire bvec file or insert it. Even the b=0 should have three elements.
2. Did you follow the directions in the dcm2niix manual's [dedicated document](https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#Diffusion_Tensor_Imaging) (this [word document](https://www.nitrc.org/docman/?group_id=880) to check if you get the correct tensor fitting?

**Comment by jim-uofu** [comment]
AFTER LOADING THE BVEC FILE, I realized that the vectors are going the other way.

Read in that way, there are three 0’s, and vectors are unit length!!!!

Jim

**Comment by jim-uofu** [comment]
THANK YOU!

After editing my original post, and copying the bvec file, I realized the vectors are printed a different direction than I expected.

It is all the x values, then all the y values, then all the z values, and now there are three 0's and the length is 1.

Jim

From: Chris Rorden ***@***.***>
Reply-To: rordenlab/dcm2niix ***@***.***>
Date: Thursday, September 12, 2024 at 12:15 PM
To: rordenlab/dcm2niix ***@***.***>
Cc: James Lee ***@***.***>, Author ***@***.***>
Subject: Re: [rordenlab/dcm2niix] SIEMENS XA50 DIFFUSION DATA (Issue #860)


  1.  Can you upload the entire bvec file or insert it. Even the b=0 should have three elements.
  2.  Did you follow the directions in the dcm2niix manual's dedicated document<https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#Diffusion_Tensor_Imaging> (this word document<https://www.nitrc.org/docman/?group_id=880> to check if you get the correct tensor fitting?

**Comment by neurolabusc** [comment]
dcm2niix saves bvec's in FSL format as required by [BIDS](https://bids-specification.readthedocs.io/en/stable/modality-specific-files/magnetic-resonance-imaging-data.html#required-gradient-orientation-information). The format is described [here](https://fsl.fmrib.ox.ac.uk/fsl/docs/#/diffusion/index?id=diffusion-data-in-fsl). Note that not only are the vectors in image (rather than world space), but that the first component will be flipped if the image has a positive determinant as described [here](https://justinblaber.org/brief-introduction-to-dwmri/) and [here](https://fsl.fmrib.ox.ac.uk/fsl/docs/#/diffusion/faq?id=what-conventions-do-the-bvecs-use). For more details, see the [dcm2niix Siemens documentation](https://github.com/rordenlab/dcm2niix/tree/master/Siemens#diffusion-tensor-notes)  or chat with the Siemens Research Collaboration Manager associated with your center.
