### ISSUE TITLE
Reduce stack pressure

### ISSUE THREAD

**Issue by neurolabusc** [rordenlab/dcm2niix#867]
As @hanayik noted when compiling dcm2niix for web assembly, dcm2niix makes huge demands on stack size, requiring [special directives for some operating systems](https://github.com/rordenlab/dcm2niix/blob/6944cad3f1e306886ce0e051a8cbbf688efbd2b4/console/makefile#L43). The next few commits to the development branch attempt to reduce this. These changes are made as three commits to aid understanding any consequences:
  1. v1.0.20240929 will use heap instead of stack memory, but will not reduce the memory allocations. This only slightly reduces the peak memory usage.
  2. v1.0.20240930 adjusts the size of memory allocations based on the size of dataset being converted. This somewhat reduces peak memory demands for the worst case scenarios (e.g. Philips enhanced DICOM with multiple echoes and timepoints).
  3. v1.0.20241001 removes stack size changes in the `makefile` and `CMakeLists.txt`.
  
 @yhuang43 @jonclayden @ningfei @hanayik will want to test their derived code bases to check for unintended consequences.

**Comment by jonclayden** [comment]
Does the version incorporating these changes generally pass the QA batteries? I see some failures – though admittedly none of them look likely to be related to the stack changes

**Comment by neurolabusc** [comment]
@jonclayden the validation dataset I have tried all work. There are tiny changes such as `BodyPartExamined` -> `BodyPart` to match the new entries in the [BIDS specification](https://bids-specification.readthedocs.io/en/stable/glossary.html#bodypart-metadata). Happy to try to replicate and troubleshoot issues if you can give me clues (clang vs gcc; macOS, Linux or Windows).

**Comment by neurolabusc** [comment]
@jonclayden I also had issues with the clash of `DT_UNKNOWN` when compiling for web assembly, that explains why I added a couple of compiler conditionals. 

```C
#ifndef __USE_MISC  /* Check __USE_MISC which includes DT_UNKNOWN in dirent.h */
  #ifndef DT_UNKNOWN
    #define DT_UNKNOWN 0  /* Define DT_UNKNOWN only if it is not already defined */
  #endif
#endif
```
However, it is worth noting that dcm2niix **never** uses the definition of DT_UNKNOWN - this C header file is a direct copy of the [NIFTI C specificaiton](https://nifti.nimh.nih.gov/pub/dist/src/niftilib/nifti1.h). I would be more than happy for you to remove that definition from the header. Feel free to make a pull request with any refactors that clean this up.

**Comment by jonclayden** [comment]
For `divest` the `nifti1.h` header is vended by a different package, so that change doesn't help me, but I've got around it by just ensuring `tinydir.h` is included first.

After sorting that and a JPEG2000 library issue I think it's just the small BIDS mismatches left over, so these changes looks fine from my side. 👍
