### ISSUE TITLE
BIDS Sidecar for PET Data

### ISSUE THREAD

**Issue by lwallace233** [rordenlab/dcm2niix#87]
Hello,

Our lab has been following along with the progress of the PET BIDS specification as it develops, and it seems that the JSON sidecar is quite extensive. Is there a timeline for PET BIDS sidecar generation in dcm2niix? I believe we would be able to provide some PET sample data if it would be of use to you in developing this.

Thanks,

Lauren

**Comment by chrisfilo** [comment]
Hi Lauren,

Indeed PET BIDS includes much more metadata. I did not look into how much
of it can be automatically extracted from DICOMs yet, but I am hopeful.

We are struggling with getting example data, so if you can share some that
would be absolutely fantastic. You can email me at chrisgor@stanford.edu

Best,
Chris

**Comment by neurolabusc** [comment]
Lauren-
 Thanks for your sample images.
 I updated dcm2niix to copy the numeric [DICOM PET module attributes](http://dicomlookup.com/lookup.asp?sw=Ttable&q=C.8-57) to the BIDS JSON output. It is unclear to me how one derives all of the values listed in the [proposed BIDS PET extension](http://bids.neuroimaging.io/) given only the DICOM files. I suspect these will need to come from sources other than the DICOM images. I am closing this issue, as the latest release seems to convert many PET attributes. However, perhaps an expert in PET can generate some pull requests that can derive more attributes.
