### ISSUE TITLE
[Not a Bug][Inquiry] 4D T1w's Off of Philips Achieva 

### ISSUE THREAD

**Issue by bendhouseart** [rordenlab/dcm2niix#873]
Noticing some strange multi-frame/dimensional T1w's popping up onto my radar; I end up getting a flat folder of dicoms and it turns out they are a 4D T1w. Curious if you've had any experience dealing with this sort of thing; it's easy enough to [fix after the fact](https://github.com/openneuropet/nifti_fixer/blob/849e61d0b94da8fb2cd08681dbd646ae16601f8a/niftifixer.py#L50), but I'm wondering how common this sort of thing is in the first place.

That said, I think dcm2niix is behaving properly, it even yells that there is something up with the source data:

 ```
Warning: Volume number does not vary (0019,10A2; 0020,0100; 2005,1063; 2005,1413), assuming meaningful instance number (0020,0013).
Error: Check sorted order: 4D dataset has 2 volumes, but volume index ranges from 1..181
Convert 362 DICOM as anat/anat_3D_T1_TFE_SAG_20080718082627_201 (256x256x181x2)
```

Further, they don't pass BIDS validation so they do get caught eventually.

Let me know what you think.

**Comment by neurolabusc** [comment]
@bendhouseart I do not have access to Philips hardware. If you have access to a Philips dataset that you think dcm2niix can handle more efficiently, you can either submit a pull request or share an image with me or share an example with [my institutional email](https://sc.edu/study/colleges_schools/artsandsciences/psychology/our_people/directory/rorden_chris.php). 

It is worth noting that [Philips DICOM images are impoverished](https://github.com/rordenlab/dcm2niix/tree/master/Philips#missing-information) and do not contain all the sequence details required for reproducible science. This is a limitation of the DICOM images, not dcm2niix and therefore most images will require intervention to pass BIDS validation.

**Comment by neurolabusc** [comment]
@bendhouseart this is a limitation of the DICOM images, not dcm2niix. For classic DICOMs, the public tags provide a recipe for combining 2D slices. This issue with your data is the same image has been saved twice, with all files sharing the same SeriesInstanceUID (0020,000e) but with images duplicated with different root MediaStorageSOPInstanceUIDs (0002,0003). Therefore, the original acquisition had 181 slices, but your dataset has 362 DICOM files (181 * 2):

```
(0002,0003) 1.2.840.113704.7.1.0.243192210156238194.1710784619.* (0020,0013) 1..181 (0008,0013) TM [135658..135659]
(0002,0003) 1.2.840.113704.7.1.0.243192210156238194.1710784624.* (0020,0013) 1..154 (0008,0013) TM [135704..135704] 
(0002,0003) 1.2.840.113704.7.1.0.243192210156238194.1710784625.* (0020,0013) 155..181 (0008,0013) TM [135704..135704]
```
dcm2niix assumes the DICOM is truthful, and creates a 4D timeseries (though each 3D volume is identical). You can fix this by only retaining the 181 images that where 0002,0003 is 1.2.840.113704.7.1.0.243192210156238194.1710784619.*.  The challenge here is that while this specific case is clearly a duplicate, the recipe is a valid DICOM one and indeed dcm2niix's interpretation is flawless (compare to Horos or dicm2nii that do not stack these two discrete volumes correctly).

I would check the provenance of these images - the tool that duplicated the data and gave unique MediaStorageSOPInstanceUIDs should also have created unique SeriesInstanceUIDs. In your example, the data is identical, so the rationale for the duplication is a mystery. Tools that modify the pixel data should set the ImageType (0008,0008) to 'derived'. It looks to me like a separate tool was used to annotate this image (embedding the line on slice 89.55mm) that garbled the dataset.

**Comment by neurolabusc** [comment]
Yes, you can either make the DICOM images valid and truthful, or you can fix the converted images. However, I would strongly suggest fixing this in the DICOMs if this data is archival, as any tool that assumes valid DICOM data will fail for these images. While OpenNeuro expects NIfTI data, some repositories (e.g. ADNI) store the DICOMs.
