### ISSUE TITLE
vertex scalp removed with -x argument

### ISSUE THREAD

**Issue by mauriliogenovese** [rordenlab/dcm2niix#874]
Cropping images with -x argument does not only remove neck tissues but also the scalp at the vertex of the head. This may be a limit in further using the converted images.

**To reproduce**
Convert a large fov 3d sagittal series with:     dcm2niix -x y -f t1 ./
Crop the uncropped converted image with fsl:    robustfov -i t1.nii -r fslcropped.nii
Compare t1_Crop_1.nii and fslcropped.nii: the latter will have intact skin on the top of the head.

**Version**
Chris Rorden's dcm2niiX version v1.0.20220720  (JP2:OpenJPEG) GCC13.2.0 x86-64 (64-bit Linux)
v1.0.20220720
(installed from apt on ubuntu 22.04)

**Comment by neurolabusc** [comment]
Acknowledged. This routine does help for a lot of clinical scans I deal with, where the excess neck brightness can confound some methods that use center-of-brightness for a starting estimate (e.g. fsl `bet` with default settings). It does also remove excess slices above the head, as wrapping effects can sometimes reveal identifiable features. It is unclear why you are interested in preserving the skin on the top of the head, but if this is important to you I would avoid using this option (which is disabled by default). I would also suggest that recent MRI methods make the need for this optional less relevant today (e.g. FSL `bet` now has a robust `-R` option, and the `robustfov` commands). Also, newer tools like [SynthStrip](https://surfer.nmr.mgh.harvard.edu/docs/synthstrip/) are exceptionally robust. Therefore, this feature is preserved for historical purposes, but may not be useful for all pipelines.
