### ISSUE TITLE
"too many NIfTI images" error with multi-shell DWI

### ISSUE THREAD

**Issue by cwatson** [rordenlab/dcm2niix#88]
Hi, I'm using version `10oct2016 (64-bit Linux)`, on CentOS 7.3.1611.

I have a 3T Siemens TrioTim multi-shell diffusion acquisition with 70 volumes. The b-values are 1000, 2000, 3000, each with 20 volumes. There are 4 b=0 volumes and the final 6 in the acquisition are b <= 500. The software version is `syngo MR B17`.

For some reason, there are 26 NIfTI files created and the error:
> Error: too many NIFTI images with the name test/test_dwi.nii.gz
> slices stacked despite varying acquisition numbers (if this is not desired please recompile)
> slices not stacked: protocol name varies`

I tried using the `-s` flag but still no luck. I ran with the `-v` flag and have attached a text file of the output. I ran this with `dcm2nii` from `mricron` and it worked. I have also successfully converted images from the same sequence previously (last scan was several months ago).

Chris
[error.txt](https://github.com/rordenlab/dcm2niix/files/799450/error.txt)

**Comment by neurolabusc** [comment]
Sounds like each direction is saved as a different acquisition, so you will want to distinguish the acquisition number in your file name (-f %p_%s_%u) or perhaps easier to  merge them ("-m y"). We process a lot of B17 data, so not sure what is the issue with this sequence, but if this does not resolve your issue I would probably need to peak at the images.

I would be grateful if you could test out the upcoming release, which is included with MRIcroGL
 https://github.com/neurolabusc/MRIcroGL/releases/tag/v1.0.20170207

**Comment by cwatson** [comment]
Yes, each direction is a separate DICOM file. I was able to use the `-m` flag and it successfully created a single file. I also downloaded the latest release and the results are the same. Thanks for your help and providing these tools.
