### ISSUE TITLE
"USE_STATIC_RUNTIME" set to ON but "libstdc++.a" not found! Set it to OFF

### ISSUE THREAD

**Issue by tashrifbillah** [rordenlab/dcm2niix#892]
Hi Chris, if we set it to OFF, would there be any performance issue of dcm2niix?

![image](https://github.com/user-attachments/assets/12805ee8-f6da-4e47-80d1-98b641084359)

**Comment by tashrifbillah** [comment]
Also, the prompt seems wrong. In Redhat 9, we have to `yum install libstdc++`.

**Comment by neurolabusc** [comment]
@ningfei may want to comment. In general, the static compile is more portable, as it can run in an environment where the library is not in the path. There is typically little difference in speed.

**Comment by tashrifbillah** [comment]
Actually, I have not been able to solve this issue despite `yum install libstdc++`. I wonder if Redhat 9 moved the required library `libstdc++.a` elsewhere or dcm2niix is not able to detect that due to any recent advancement. But I am trying.

**Comment by ningfei** [comment]
You can check on https://pkgs.org to see which package contains `libstdc++.a`. But it's also fine to turn it off. That's mainly for portability. You don't need a static build if you are only using it on the local machine.

**Comment by tashrifbillah** [comment]
It looks like libstdcc++-static is part of a different repository in Redhat 9:

https://stackoverflow.com/a/73242284/11932012

**Comment by tashrifbillah** [comment]
I ended up using `-DUSE_STATIC_RUNTIME=OFF` as I could not trust the different repository.
