### ISSUE TITLE
pip version is out of date

### ISSUE THREAD

**Issue by Jolinda** [rordenlab/dcm2niix#893]
dcm2niix on pypi is still on 1.0.20220715, could you update the version there please?

**Comment by neurolabusc** [comment]
@casperdcl can you help bump [pypi dcm2niix](https://pypi.org/project/dcm2niix/) from v1.0.20220715 to the current stable release (v1.0.20241208).

**Comment by casperdcl** [comment]
Hi @neurolabusc - based on https://github.com/rordenlab/dcm2niix/actions/runs/12225623902/job/34157966879 it looks like the PyPI package might be too large.

Or maybe it's a misleading/temporary error. Could you try restart the job?

**Comment by neurolabusc** [comment]
@jolinda, can you test and close this issue if it is resolved. I believe that [v1.0.20241211](https://pypi.org/project/dcm2niix/#history) is now available.

@casperdcl I did open [a File Limit Request](https://github.com/pypi/support/issues/5269#issuecomment-2543234406). However, I do not think it is necessary. I edited dcm2niix/.github/workflows/release.yml to read `submodules: false` and I think this fixes the issue. We only use the submodules for regression testing, so they do not need to be part of the PyPi workflow.

**Comment by casperdcl** [comment]
Excellent; they'll probably close the issue then :)

**Comment by Jolinda** [comment]
Works great!
