### ISSUE TITLE
Constraint on constant x-ray exposure is too restrictive

### ISSUE THREAD

**Issue by seandoyle** [rordenlab/dcm2niix#91]
At MGH we use Automatic Tube Current Modulation for CT acquisitions - the xray current varies depending on the density of the patient (a preliminary scan is done first to estimate the patient's density).  I think that the program should accept a command line argument to turn off this constraint as a option. 

If you agree - I can do this and create a pull request. If there is an alternative mechanism that you prefer please let me know. I also was planning to add the DICOM InstanceNumber to the error message - at first I had difficulty seeing the problem because the xray exposure in the middle of the head was constant. 

Thanks!

**Comment by neurolabusc** [comment]
If you want to stack CT slices where the exposure (as listed in tag 0018,1152) varies between slices, you would use the command line merge option ("-m y"), this is analogous to stacking MRI scans where the echo time (0018,0081) varies. I think this needs to be an option, as different vendors handle this differently, and acquire multiple exposures that really need to be segmented (or we have to devise clever logic to work out how to detect this automatically).
