### ISSUE TITLE
Export StudyInstanceUID and SeriesInstanceUID in filename

### ISSUE THREAD

**Issue by dimrozakis** [rordenlab/dcm2niix#94]
As far as I can tell, this isn't currently possible. Could an cli option be added to export these fields to the resulting nii file?

**Comment by fedjo** [comment]
+1

This could be very helpful. 
Why are you extracting Series Number instead of SeriesInstanceUID?

**Comment by neurolabusc** [comment]
The updated code now allows you to specify %j and %k to include these in the filename. Personally, I find the series number (e.g. 9) easier to parse than the UID (e.g. 1.3.12.2.1107.5.2.32.35104.30000008061718153321800000002), but it is easy enough to support for those who find it useful.

**Comment by dimrozakis** [comment]
@neurolabusc thanks a lot, much appreciated!

**Comment by fedjo** [comment]
@neurolabusc thanks!
