### ISSUE TITLE
CMake error (libyaml-cpp0.5)

### ISSUE THREAD

**Issue by yeunkim** [rordenlab/dcm2niix#96]
I'm building a docker image, which builds your dcm2niibatch inside.
i.e. the statement in the Dockerfile is as follows:
```
RUN apt-get -y update && apt-get -y install build-essential

RUN apt-get -y update && \
    apt-get -y install pkg-config libyaml-cpp-dev libyaml-cpp0.5 cmake libboost-dev

RUN cd / && git clone https://github.com/rordenlab/dcm2niix.git && \
    cd dcm2niix && mkdir build && cd build && cmake -DBATCH_VERSION=ON .. && make
```

This statement produced no errors a month ago, but last week began to cause the following error (errs out at the make step) :

Step 55/74 : RUN apt-get -y update && apt-get -y install build-essential
 ---> Using cache
 ---> 3300fc67c1df
Step 56/74 : RUN apt-get -y update &&     apt-get -y install pkg-config libyaml-cpp-dev libyaml-cpp0.5 cmake libboost-dev
 ---> Using cache
 ---> ad374ec7f824
Step 57/74 : RUN cd / && git clone https://github.com/rordenlab/dcm2niix.git &&     cd dcm2niix && mkdir build && cd build && cmake -DBATCH_VERSION=ON .. && make
 ---> Running in d87b45ae43f7
Cloning into 'dcm2niix'...
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Git: /usr/bin/git (found version "1.9.1") 
-- Build dcm2niibatch: ON
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
-- checking for module 'yaml-cpp'
--   found yaml-cpp, version 0.5.1
--     Using the system yaml-cpp
-- Configuring done
-- Generating done
-- Build files have been written to: /dcm2niix/build
Scanning dependencies of target console
[ 12%] Creating directories for 'console'
[ 25%] No download step for 'console'
[ 37%] No patch step for 'console'
[ 50%] No update step for 'console'
[ 62%] Performing configure step for 'console'
Not searching for unused variables given on the command line.
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
CMake Warning at CMakeLists.txt:105 (find_package):
  By not providing "FindYAML-CPP.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "YAML-CPP",
  but CMake did not find one.

  Could not find a package configuration file provided by "YAML-CPP" with any
  of the following names:

    YAML-CPPConfig.cmake
    yaml-cpp-config.cmake

  Add the installation prefix of "YAML-CPP" to CMAKE_PREFIX_PATH or set
  "YAML-CPP_DIR" to a directory containing one of the above files.  If
  "YAML-CPP" provides a separate development package or SDK, be sure it has
  been installed.

-- Configuring done
-- Generating done
-- Build files have been written to: /dcm2niix/build/console-build
[ 75%] Performing build step for 'console'
Scanning dependencies of target dcm2niibatch
[  6%] Building CXX object CMakeFiles/dcm2niibatch.dir/main_console_batch.cpp.o
[ 12%] Building CXX object CMakeFiles/dcm2niibatch.dir/nii_dicom.cpp.o
[ 18%] Building CXX object CMakeFiles/dcm2niibatch.dir/jpg_0XC3.cpp.o
[ 25%] Building CXX object CMakeFiles/dcm2niibatch.dir/ujpeg.cpp.o
[ 31%] Building CXX object CMakeFiles/dcm2niibatch.dir/nifti1_io_core.cpp.o
[ 37%] Building CXX object CMakeFiles/dcm2niibatch.dir/nii_foreign.cpp.o
[ 43%] Building CXX object CMakeFiles/dcm2niibatch.dir/nii_ortho.cpp.o
[ 50%] Building CXX object CMakeFiles/dcm2niibatch.dir/nii_dicom_batch.cpp.o
Linking CXX executable dcm2niibatch
CMakeFiles/dcm2niibatch.dir/main_console_batch.cpp.o: In function `bool const YAML::Node::as<bool>() const':
main_console_batch.cpp:(.text._ZNK4YAML4Node2asIbEEKT_v[_ZNK4YAML4Node2asIbEEKT_v]+0x16): undefined reference to `YAML::convert<bool>::decode(YAML::Node const&, bool&)'
CMakeFiles/dcm2niibatch.dir/main_console_batch.cpp.o: In function `YAML::detail::node::mark_defined()':
main_console_batch.cpp:(.text._ZN4YAML6detail4node12mark_definedEv[_ZN4YAML6detail4node12mark_definedEv]+0x37): undefined reference to `YAML::detail::node_data::mark_defined()'
main_console_batch.cpp:(.text._ZN4YAML6detail4node12mark_definedEv[_ZN4YAML6detail4node12mark_definedEv]+0xcd): undefined reference to `YAML::detail::node_data::mark_defined()'
main_console_batch.cpp:(.text._ZN4YAML6detail4node12mark_definedEv[_ZN4YAML6detail4node12mark_definedEv]+0x132): undefined reference to `YAML::detail::node_data::mark_defined()'
main_console_batch.cpp:(.text._ZN4YAML6detail4node12mark_definedEv[_ZN4YAML6detail4node12mark_definedEv]+0x19a): undefined reference to `YAML::detail::node_data::mark_defined()'
main_console_batch.cpp:(.text._ZN4YAML6detail4node12mark_definedEv[_ZN4YAML6detail4node12mark_definedEv]+0x205): undefined reference to `YAML::detail::node_data::mark_defined()'
CMakeFiles/dcm2niibatch.dir/main_console_batch.cpp.o:main_console_batch.cpp:(.text._ZN4YAML6detail4node12mark_definedEv[_ZN4YAML6detail4node12mark_definedEv]+0x267): more undefined references to `YAML::detail::node_data::mark_defined()' follow
CMakeFiles/dcm2niibatch.dir/main_console_batch.cpp.o: In function `YAML::detail::node& YAML::detail::node_data::get<std::string>(std::string const&, boost::shared_ptr<YAML::detail::memory_holder>)':
main_console_batch.cpp:(.text._ZN4YAML6detail9node_data3getISsEERNS0_4nodeERKT_N5boost10shared_ptrINS0_13memory_holderEEE[_ZN4YAML6detail9node_data3getISsEERNS0_4nodeERKT_N5boost10shared_ptrINS0_13memory_holderEEE]+0x28c): undefined reference to `YAML::detail::node_data::convert_to_map(boost::shared_ptr<YAML::detail::memory_holder>)'
main_console_batch.cpp:(.text._ZN4YAML6detail9node_data3getISsEERNS0_4nodeERKT_N5boost10shared_ptrINS0_13memory_holderEEE[_ZN4YAML6detail9node_data3getISsEERNS0_4nodeERKT_N5boost10shared_ptrINS0_13memory_holderEEE]+0xad8): undefined reference to `YAML::detail::memory::create_node()'
main_console_batch.cpp:(.text._ZN4YAML6detail9node_data3getISsEERNS0_4nodeERKT_N5boost10shared_ptrINS0_13memory_holderEEE[_ZN4YAML6detail9node_data3getISsEERNS0_4nodeERKT_N5boost10shared_ptrINS0_13memory_holderEEE]+0xb0a): undefined reference to `YAML::detail::node_data::set_scalar(std::string const&)'
main_console_batch.cpp:(.text._ZN4YAML6detail9node_data3getISsEERNS0_4nodeERKT_N5boost10shared_ptrINS0_13memory_holderEEE[_ZN4YAML6detail9node_data3getISsEERNS0_4nodeERKT_N5boost10shared_ptrINS0_13memory_holderEEE]+0xb1c): undefined reference to `YAML::detail::memory_holder::merge(YAML::detail::memory_holder&)'
main_console_batch.cpp:(.text._ZN4YAML6detail9node_data3getISsEERNS0_4nodeERKT_N5boost10shared_ptrINS0_13memory_holderEEE[_ZN4YAML6detail9node_data3getISsEERNS0_4nodeERKT_N5boost10shared_ptrINS0_13memory_holderEEE]+0xb64): undefined reference to `YAML::detail::memory::create_node()'
main_console_batch.cpp:(.text._ZN4YAML6detail9node_data3getISsEERNS0_4nodeERKT_N5boost10shared_ptrINS0_13memory_holderEEE[_ZN4YAML6detail9node_data3getISsEERNS0_4nodeERKT_N5boost10shared_ptrINS0_13memory_holderEEE]+0xb7c): undefined reference to `YAML::detail::node_data::insert_map_pair(YAML::detail::node&, YAML::detail::node&)'
main_console_batch.cpp:(.text._ZN4YAML6detail9node_data3getISsEERNS0_4nodeERKT_N5boost10shared_ptrINS0_13memory_holderEEE[_ZN4YAML6detail9node_data3getISsEERNS0_4nodeERKT_N5boost10shared_ptrINS0_13memory_holderEEE]+0xbea): undefined reference to `YAML::detail::node_data::mark_defined()'
main_console_batch.cpp:(.text._ZN4YAML6detail9node_data3getISsEERNS0_4nodeERKT_N5boost10shared_ptrINS0_13memory_holderEEE[_ZN4YAML6detail9node_data3getISsEERNS0_4nodeERKT_N5boost10shared_ptrINS0_13memory_holderEEE]+0xd67): undefined reference to `YAML::detail::memory::create_node()'
main_console_batch.cpp:(.text._ZN4YAML6detail9node_data3getISsEERNS0_4nodeERKT_N5boost10shared_ptrINS0_13memory_holderEEE[_ZN4YAML6detail9node_data3getISsEERNS0_4nodeERKT_N5boost10shared_ptrINS0_13memory_holderEEE]+0xd7f): undefined reference to `YAML::detail::node_data::set_null()'
main_console_batch.cpp:(.text._ZN4YAML6detail9node_data3getISsEERNS0_4nodeERKT_N5boost10shared_ptrINS0_13memory_holderEEE[_ZN4YAML6detail9node_data3getISsEERNS0_4nodeERKT_N5boost10shared_ptrINS0_13memory_holderEEE]+0xda3): undefined reference to `YAML::detail::node_data::mark_defined()'
main_console_batch.cpp:(.text._ZN4YAML6detail9node_data3getISsEERNS0_4nodeERKT_N5boost10shared_ptrINS0_13memory_holderEEE[_ZN4YAML6detail9node_data3getISsEERNS0_4nodeERKT_N5boost10shared_ptrINS0_13memory_holderEEE]+0xe72): undefined reference to `YAML::detail::node_data::mark_defined()'
main_console_batch.cpp:(.text._ZN4YAML6detail9node_data3getISsEERNS0_4nodeERKT_N5boost10shared_ptrINS0_13memory_holderEEE[_ZN4YAML6detail9node_data3getISsEERNS0_4nodeERKT_N5boost10shared_ptrINS0_13memory_holderEEE]+0xf05): undefined reference to `YAML::detail::node_data::mark_defined()'
main_console_batch.cpp:(.text._ZN4YAML6detail9node_data3getISsEERNS0_4nodeERKT_N5boost10shared_ptrINS0_13memory_holderEEE[_ZN4YAML6detail9node_data3getISsEERNS0_4nodeERKT_N5boost10shared_ptrINS0_13memory_holderEEE]+0xf92): undefined reference to `YAML::detail::node_data::mark_defined()'
main_console_batch.cpp:(.text._ZN4YAML6detail9node_data3getISsEERNS0_4nodeERKT_N5boost10shared_ptrINS0_13memory_holderEEE[_ZN4YAML6detail9node_data3getISsEERNS0_4nodeERKT_N5boost10shared_ptrINS0_13memory_holderEEE]+0xffd): undefined reference to `YAML::detail::node_data::mark_defined()'
CMakeFiles/dcm2niibatch.dir/main_console_batch.cpp.o:main_console_batch.cpp:(.text._ZN4YAML6detail9node_data3getISsEERNS0_4nodeERKT_N5boost10shared_ptrINS0_13memory_holderEEE[_ZN4YAML6detail9node_data3getISsEERNS0_4nodeERKT_N5boost10shared_ptrINS0_13memory_holderEEE]+0x106d): more undefined references to `YAML::detail::node_data::mark_defined()' follow
CMakeFiles/dcm2niibatch.dir/main_console_batch.cpp.o: In function `YAML::Node YAML::Node::operator[]<char [13]>(char const (&) [13])':
main_console_batch.cpp:(.text._ZN4YAML4NodeixIA13_cEES0_RKT_[_ZN4YAML4NodeixIA13_cEES0_RKT_]+0x47b): undefined reference to `YAML::detail::memory::create_node()'
main_console_batch.cpp:(.text._ZN4YAML4NodeixIA13_cEES0_RKT_[_ZN4YAML4NodeixIA13_cEES0_RKT_]+0x49c): undefined reference to `YAML::detail::node_data::set_null()'
main_console_batch.cpp:(.text._ZN4YAML4NodeixIA13_cEES0_RKT_[_ZN4YAML4NodeixIA13_cEES0_RKT_]+0x4c0): undefined reference to `YAML::detail::node_data::mark_defined()'
main_console_batch.cpp:(.text._ZN4YAML4NodeixIA13_cEES0_RKT_[_ZN4YAML4NodeixIA13_cEES0_RKT_]+0x566): undefined reference to `YAML::detail::node_data::mark_defined()'
main_console_batch.cpp:(.text._ZN4YAML4NodeixIA13_cEES0_RKT_[_ZN4YAML4NodeixIA13_cEES0_RKT_]+0x5f6): undefined reference to `YAML::detail::node_data::mark_defined()'
main_console_batch.cpp:(.text._ZN4YAML4NodeixIA13_cEES0_RKT_[_ZN4YAML4NodeixIA13_cEES0_RKT_]+0x65a): undefined reference to `YAML::detail::node_data::mark_defined()'
main_console_batch.cpp:(.text._ZN4YAML4NodeixIA13_cEES0_RKT_[_ZN4YAML4NodeixIA13_cEES0_RKT_]+0x6c5): undefined reference to `YAML::detail::node_data::mark_defined()'
CMakeFiles/dcm2niibatch.dir/main_console_batch.cpp.o:main_console_batch.cpp:(.text._ZN4YAML4NodeixIA13_cEES0_RKT_[_ZN4YAML4NodeixIA13_cEES0_RKT_]+0x72d): more undefined references to `YAML::detail::node_data::mark_defined()' follow
CMakeFiles/dcm2niibatch.dir/main_console_batch.cpp.o: In function `YAML::Node YAML::Node::operator[]<char [17]>(char const (&) [17])':
main_console_batch.cpp:(.text._ZN4YAML4NodeixIA17_cEES0_RKT_[_ZN4YAML4NodeixIA17_cEES0_RKT_]+0x47b): undefined reference to `YAML::detail::memory::create_node()'
main_console_batch.cpp:(.text._ZN4YAML4NodeixIA17_cEES0_RKT_[_ZN4YAML4NodeixIA17_cEES0_RKT_]+0x49c): undefined reference to `YAML::detail::node_data::set_null()'
main_console_batch.cpp:(.text._ZN4YAML4NodeixIA17_cEES0_RKT_[_ZN4YAML4NodeixIA17_cEES0_RKT_]+0x4c0): undefined reference to `YAML::detail::node_data::mark_defined()'
main_console_batch.cpp:(.text._ZN4YAML4NodeixIA17_cEES0_RKT_[_ZN4YAML4NodeixIA17_cEES0_RKT_]+0x566): undefined reference to `YAML::detail::node_data::mark_defined()'
main_console_batch.cpp:(.text._ZN4YAML4NodeixIA17_cEES0_RKT_[_ZN4YAML4NodeixIA17_cEES0_RKT_]+0x5f6): undefined reference to `YAML::detail::node_data::mark_defined()'
main_console_batch.cpp:(.text._ZN4YAML4NodeixIA17_cEES0_RKT_[_ZN4YAML4NodeixIA17_cEES0_RKT_]+0x65a): undefined reference to `YAML::detail::node_data::mark_defined()'
main_console_batch.cpp:(.text._ZN4YAML4NodeixIA17_cEES0_RKT_[_ZN4YAML4NodeixIA17_cEES0_RKT_]+0x6c5): undefined reference to `YAML::detail::node_data::mark_defined()'
CMakeFiles/dcm2niibatch.dir/main_console_batch.cpp.o:main_console_batch.cpp:(.text._ZN4YAML4NodeixIA17_cEES0_RKT_[_ZN4YAML4NodeixIA17_cEES0_RKT_]+0x72d): more undefined references to `YAML::detail::node_data::mark_defined()' follow
CMakeFiles/dcm2niibatch.dir/main_console_batch.cpp.o: In function `YAML::Node YAML::Node::operator[]<char [8]>(char const (&) [8])':
main_console_batch.cpp:(.text._ZN4YAML4NodeixIA8_cEES0_RKT_[_ZN4YAML4NodeixIA8_cEES0_RKT_]+0x47b): undefined reference to `YAML::detail::memory::create_node()'
main_console_batch.cpp:(.text._ZN4YAML4NodeixIA8_cEES0_RKT_[_ZN4YAML4NodeixIA8_cEES0_RKT_]+0x49c): undefined reference to `YAML::detail::node_data::set_null()'
main_console_batch.cpp:(.text._ZN4YAML4NodeixIA8_cEES0_RKT_[_ZN4YAML4NodeixIA8_cEES0_RKT_]+0x4c0): undefined reference to `YAML::detail::node_data::mark_defined()'
main_console_batch.cpp:(.text._ZN4YAML4NodeixIA8_cEES0_RKT_[_ZN4YAML4NodeixIA8_cEES0_RKT_]+0x566): undefined reference to `YAML::detail::node_data::mark_defined()'
main_console_batch.cpp:(.text._ZN4YAML4NodeixIA8_cEES0_RKT_[_ZN4YAML4NodeixIA8_cEES0_RKT_]+0x5f6): undefined reference to `YAML::detail::node_data::mark_defined()'
main_console_batch.cpp:(.text._ZN4YAML4NodeixIA8_cEES0_RKT_[_ZN4YAML4NodeixIA8_cEES0_RKT_]+0x65a): undefined reference to `YAML::detail::node_data::mark_defined()'
main_console_batch.cpp:(.text._ZN4YAML4NodeixIA8_cEES0_RKT_[_ZN4YAML4NodeixIA8_cEES0_RKT_]+0x6c5): undefined reference to `YAML::detail::node_data::mark_defined()'
CMakeFiles/dcm2niibatch.dir/main_console_batch.cpp.o:main_console_batch.cpp:(.text._ZN4YAML4NodeixIA8_cEES0_RKT_[_ZN4YAML4NodeixIA8_cEES0_RKT_]+0x72d): more undefined references to `YAML::detail::node_data::mark_defined()' follow
CMakeFiles/dcm2niibatch.dir/main_console_batch.cpp.o: In function `YAML::Node YAML::Node::operator[]<char [5]>(char const (&) [5])':
main_console_batch.cpp:(.text._ZN4YAML4NodeixIA5_cEES0_RKT_[_ZN4YAML4NodeixIA5_cEES0_RKT_]+0x47b): undefined reference to `YAML::detail::memory::create_node()'
main_console_batch.cpp:(.text._ZN4YAML4NodeixIA5_cEES0_RKT_[_ZN4YAML4NodeixIA5_cEES0_RKT_]+0x49c): undefined reference to `YAML::detail::node_data::set_null()'
main_console_batch.cpp:(.text._ZN4YAML4NodeixIA5_cEES0_RKT_[_ZN4YAML4NodeixIA5_cEES0_RKT_]+0x4c0): undefined reference to `YAML::detail::node_data::mark_defined()'
main_console_batch.cpp:(.text._ZN4YAML4NodeixIA5_cEES0_RKT_[_ZN4YAML4NodeixIA5_cEES0_RKT_]+0x566): undefined reference to `YAML::detail::node_data::mark_defined()'
main_console_batch.cpp:(.text._ZN4YAML4NodeixIA5_cEES0_RKT_[_ZN4YAML4NodeixIA5_cEES0_RKT_]+0x5f6): undefined reference to `YAML::detail::node_data::mark_defined()'
main_console_batch.cpp:(.text._ZN4YAML4NodeixIA5_cEES0_RKT_[_ZN4YAML4NodeixIA5_cEES0_RKT_]+0x65a): undefined reference to `YAML::detail::node_data::mark_defined()'
main_console_batch.cpp:(.text._ZN4YAML4NodeixIA5_cEES0_RKT_[_ZN4YAML4NodeixIA5_cEES0_RKT_]+0x6c5): undefined reference to `YAML::detail::node_data::mark_defined()'
CMakeFiles/dcm2niibatch.dir/main_console_batch.cpp.o:main_console_batch.cpp:(.text._ZN4YAML4NodeixIA5_cEES0_RKT_[_ZN4YAML4NodeixIA5_cEES0_RKT_]+0x72d): more undefined references to `YAML::detail::node_data::mark_defined()' follow
CMakeFiles/dcm2niibatch.dir/main_console_batch.cpp.o: In function `YAML::Node YAML::Node::operator[]<char [6]>(char const (&) [6])':
main_console_batch.cpp:(.text._ZN4YAML4NodeixIA6_cEES0_RKT_[_ZN4YAML4NodeixIA6_cEES0_RKT_]+0x47b): undefined reference to `YAML::detail::memory::create_node()'
main_console_batch.cpp:(.text._ZN4YAML4NodeixIA6_cEES0_RKT_[_ZN4YAML4NodeixIA6_cEES0_RKT_]+0x49c): undefined reference to `YAML::detail::node_data::set_null()'
main_console_batch.cpp:(.text._ZN4YAML4NodeixIA6_cEES0_RKT_[_ZN4YAML4NodeixIA6_cEES0_RKT_]+0x4c0): undefined reference to `YAML::detail::node_data::mark_defined()'
main_console_batch.cpp:(.text._ZN4YAML4NodeixIA6_cEES0_RKT_[_ZN4YAML4NodeixIA6_cEES0_RKT_]+0x566): undefined reference to `YAML::detail::node_data::mark_defined()'
main_console_batch.cpp:(.text._ZN4YAML4NodeixIA6_cEES0_RKT_[_ZN4YAML4NodeixIA6_cEES0_RKT_]+0x5f6): undefined reference to `YAML::detail::node_data::mark_defined()'
main_console_batch.cpp:(.text._ZN4YAML4NodeixIA6_cEES0_RKT_[_ZN4YAML4NodeixIA6_cEES0_RKT_]+0x65a): undefined reference to `YAML::detail::node_data::mark_defined()'
main_console_batch.cpp:(.text._ZN4YAML4NodeixIA6_cEES0_RKT_[_ZN4YAML4NodeixIA6_cEES0_RKT_]+0x6c5): undefined reference to `YAML::detail::node_data::mark_defined()'
CMakeFiles/dcm2niibatch.dir/main_console_batch.cpp.o:main_console_batch.cpp:(.text._ZN4YAML4NodeixIA6_cEES0_RKT_[_ZN4YAML4NodeixIA6_cEES0_RKT_]+0x72d): more undefined references to `YAML::detail::node_data::mark_defined()' follow
CMakeFiles/dcm2niibatch.dir/main_console_batch.cpp.o: In function `main':
main_console_batch.cpp:(.text.startup+0x118): undefined reference to `YAML::LoadFile(std::string const&)'
main_console_batch.cpp:(.text.startup+0x2ee): undefined reference to `YAML::detail::node_data::begin()'
main_console_batch.cpp:(.text.startup+0x381): undefined reference to `YAML::detail::node_data::end()'
main_console_batch.cpp:(.text.startup+0xf7e): undefined reference to `YAML::detail::node_data::mark_defined()'
main_console_batch.cpp:(.text.startup+0x103a): undefined reference to `YAML::detail::node_data::mark_defined()'
main_console_batch.cpp:(.text.startup+0x1109): undefined reference to `YAML::detail::node_data::mark_defined()'
main_console_batch.cpp:(.text.startup+0x1186): undefined reference to `YAML::detail::node_data::mark_defined()'
main_console_batch.cpp:(.text.startup+0x11fb): undefined reference to `YAML::detail::node_data::mark_defined()'
CMakeFiles/dcm2niibatch.dir/main_console_batch.cpp.o:main_console_batch.cpp:(.text.startup+0x1273): more undefined references to `YAML::detail::node_data::mark_defined()' follow
CMakeFiles/dcm2niibatch.dir/main_console_batch.cpp.o: In function `main':
main_console_batch.cpp:(.text.startup+0x1728): undefined reference to `YAML::detail::memory::create_node()'
main_console_batch.cpp:(.text.startup+0x1746): undefined reference to `YAML::detail::node_data::set_null()'
main_console_batch.cpp:(.text.startup+0x1bae): undefined reference to `YAML::detail::memory::create_node()'
main_console_batch.cpp:(.text.startup+0x1bcc): undefined reference to `YAML::detail::node_data::set_null()'
main_console_batch.cpp:(.text.startup+0x2127): undefined reference to `YAML::detail::memory::create_node()'
main_console_batch.cpp:(.text.startup+0x2145): undefined reference to `YAML::detail::node_data::set_null()'
main_console_batch.cpp:(.text.startup+0x22a6): undefined reference to `YAML::detail::node_data::mark_defined()'
main_console_batch.cpp:(.text.startup+0x231e): undefined reference to `YAML::detail::node_data::mark_defined()'
main_console_batch.cpp:(.text.startup+0x2396): undefined reference to `YAML::detail::node_data::mark_defined()'
main_console_batch.cpp:(.text.startup+0x240e): undefined reference to `YAML::detail::node_data::mark_defined()'
main_console_batch.cpp:(.text.startup+0x2477): undefined reference to `YAML::detail::node_data::mark_defined()'
CMakeFiles/dcm2niibatch.dir/main_console_batch.cpp.o:main_console_batch.cpp:(.text.startup+0x24d7): more undefined references to `YAML::detail::node_data::mark_defined()' follow
collect2: error: ld returned 1 exit status
make[5]: *** [dcm2niibatch] Error 1
make[4]: *** [CMakeFiles/dcm2niibatch.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [console-prefix/src/console-stamp/console-build] Error 2
make[1]: *** [CMakeFiles/console.dir/all] Error 2
make: *** [all] Error 2
The command '/bin/sh -c cd / && git clone https://github.com/rordenlab/dcm2niix.git &&     cd dcm2niix && mkdir build && cd build && cmake -DBATCH_VERSION=ON .. && make' returned a non-zero code: 2

The docker image uses Ubuntu 14.04 LTS (ubuntu:trusty-20170119).
Any suggestions would be greatly appreciated! Thank you.

**Comment by ningfei** [comment]
Hi @yeunkim, from recent updates of the CMake files, you don't need to manually install `libyaml-cpp-dev libyaml-cpp0.5 libboost-dev` to build dcm2niix, `yaml-cpp` will be built during the compilation. We made this change to simplify the cross-platform compliations (especially on windows). `yaml-cpp` package in some linux distributions and macos brew repository don't have proper cmake config files (source of the error you saw here), and have additionally denpendency on boost lib. 
I will update the Dockerfile soon. You may also remove `libyaml-cpp-dev libyaml-cpp0.5 libboost-dev` from it and try again.

**Comment by neurolabusc** [comment]
Fixed in latest build.
